= rpk cluster partitions movement-cancel
:description: rpk cluster partitions movement-cancel
:rpk_version: v23.1.6 (rev cc47e1ad1)

Cancel ongoing partition movements.

By default, this command cancels all the partition movements in the cluster.
To ensure that you do not accidentally cancel all partition movements, this
command prompts users for confirmation before issuing the cancellation request.
You can use `--no-confirm` to disable the confirmation prompt:

[,bash]
----
rpk cluster partitions movement-cancel --no-confirm
----

If `--node` is set, this command will only stop the partition movements
occurring in the specified node:

[,bash]
----
rpk cluster partitions movement-cancel --node 1
----

== Usage

[,bash]
----
rpk cluster partitions movement-cancel [flags]
----

== Flags

////
[cols=",,",]
|===
|*Value* |*Type* |*Description*

|-h, --help |- |Help for movement-cancel.

|--no-confirm |- |Disable confirmation prompt.

|--node |int |ID of a specific node on which to cancel ongoing partition
movements (default -1).

|--admin-api-tls-cert |string |The certificate to be used for TLS
authentication with the Admin API.

|--admin-api-tls-enabled |- |Enable TLS for the Admin API (not necessary
if specifying custom certs).

|--admin-api-tls-key |string |The certificate key to be used for TLS
authentication with the Admin API.

|--admin-api-tls-truststore |string |The truststore to be used for TLS
communication with the Admin API.

|--api-urls |string |Comma-separated list of admin API addresses
(<ip>:<port>

|--brokers |strings |Comma-separated list of broker ip:port pairs (for
example. --brokers
'192.168.78.34:9092,192.168.78.35:9092,192.179.23.54:9092').
Alternatively, you may set the REDPANDA_BROKERS environment variable
with the comma-separated list of broker addresses.

|--config |string |Redpanda config file, if not set the file will be
searched for in the default locations.

|--password |string |SASL password to be used for authentication.

|--sasl-mechanism |string |The authentication mechanism to use.
Supported values:\{" "} `SCRAM-SHA-256`, `SCRAM-SHA-512`.

|--tls-cert |string |The certificate to be used for TLS authentication
with the broker.

|--tls-enabled |- |Enable TLS for the Kafka API (not necessary if
specifying custom certs).

|--tls-key |string |The certificate key to be used for TLS
authentication with the broker.

|--tls-truststore |string |The truststore to be used for TLS
communication with the broker.

|--user |string |SASL user to be used for authentication.

|-v, --verbose |- |Enable verbose logging (default `false`).
|===
////
