= rpk cluster config status
:description: rpk cluster config status

Get configuration status of redpanda nodes.

For each node, indicate whether a restart is required for settings to
take effect, and any settings that the node has identified as invalid
or unknown properties.

Additionally show the version of cluster configuration that each node
has applied: under normal circumstances these should all be equal,
a lower number shows that a node is out of sync, perhaps because it
is offline.

=== Usage

----
rpk cluster config status [flags]
----

=== Flags

////
[cols=",,",]
|===
|*Value* |*Type* |*Description*

|-h, --help |- |Help for status.

|--admin-api-tls-cert |string |The certificate to be used for TLS
authentication with the Admin API.

|--admin-api-tls-enabled |- |Enable TLS for the Admin API (not necessary
if specifying custom certs).

|--admin-api-tls-key |string |The certificate key to be used for TLS
authentication with the Admin API.

|--admin-api-tls-truststore |string |The truststore to be used for TLS
communication with the Admin API.

|--all |- |Include all properties, including tunables.

|--api-urls |string |Comma-separated list of admin API addresses
(<ip>:<port>

|--brokers |strings |Comma-separated list of broker <ip>:<port> pairs
(for example,
` --brokers \'192.168.78.34:9092,192.168.78.35:9092,192.179.23.54:9092\' `
). Alternatively, you may set the `REDPANDA_BROKERS` environment
variable with the comma-separated list of broker addresses.

|--config |string |Redpanda config file, if not set the file will be
searched for in the default locations.

|--password |string |SASL password to be used for authentication.

|--sasl-mechanism |string |The authentication mechanism to use.
Supported values: SCRAM-SHA-256, SCRAM-SHA-512.

|--tls-cert |string |The certificate to be used for TLS authentication
with the broker.

|--tls-enabled |- |Enable TLS for the Kafka API (not necessary if
specifying custom certs).

|--tls-key |string |The certificate key to be used for TLS
authentication with the broker.

|--tls-truststore |string |The truststore to be used for TLS
communication with the broker.

|--user |string |SASL user to be used for authentication.

|-v, --verbose |- |Enable verbose logging (default `false`).
|===
////
