= rpk cluster config import
:description: rpk cluster config import

:::caution
Redpanda does not support importing cluster-specific identification (such as `cluster_id`) with this command.
:::

Import cluster configuration from a file.

Import configuration from a YAML file, usually generated with
corresponding `export` command. This downloads the current cluster
configuration, calculates the difference with the YAML file, and
updates any properties that were changed. If a property is removed
from the YAML file, it is reset to its default value.

=== Usage

----
rpk cluster config import [flags]
----

=== Flags

////
[cols=",,",]
|===
|*Value* |*Type* |*Description*

|-f, --filename |string |full path to file to import, for example
`/tmp/config.yml` .

|-h, --help |- |Help for import.

|--admin-api-tls-cert |string |The certificate to be used for TLS
authentication with the Admin API.

|--admin-api-tls-enabled |- |Enable TLS for the Admin API (not necessary
if specifying custom certs).

|--admin-api-tls-key |string |The certificate key to be used for TLS
authentication with the Admin API.

|--admin-api-tls-truststore |string |The truststore to be used for TLS
communication with the Admin API.

|--all |- |Include all properties, including tunables.

|--api-urls |string |Comma-separated list of admin API addresses
(<ip>:<port>

|--brokers |strings |Comma-separated list of broker <ip>:<port> pairs
(for example,
` --brokers \'192.168.78.34:9092,192.168.78.35:9092,192.179.23.54:9092\' `
). Alternatively, you may set the `REDPANDA_BROKERS` environment
variable with the comma-separated list of broker addresses.

|--config |string |Redpanda config file, if not set the file will be
searched for in the default locations.

|--password |string |SASL password to be used for authentication.

|--sasl-mechanism |string |The authentication mechanism to use.
Supported values: SCRAM-SHA-256, SCRAM-SHA-512.

|--tls-cert |string |The certificate to be used for TLS authentication
with the broker.

|--tls-enabled |- |Enable TLS for the Kafka API (not necessary if
specifying custom certs).

|--tls-key |string |The certificate key to be used for TLS
authentication with the broker.

|--tls-truststore |string |The truststore to be used for TLS
communication with the broker.

|--user |string |SASL user to be used for authentication.

|-v, --verbose |- |Enable verbose logging (default `false`).
|===
////
