= rpk cluster metadata
:description: rpk cluster metadata
:rpk_version: v23.1.6 (rev cc47e1ad1)

Request broker metadata.

The Kafka protocol's metadata contains information about brokers, topics, and
the cluster as a whole.

This command only runs if specific sections of metadata are requested. There
are currently three sections: the cluster, the list of brokers, and the topics.
If no section is specified, this defaults to printing all sections.

If the topic section is requested, all topics are requested by default unless
some are manually specified as arguments. Expanded per-partition information
can be printed with the -d flag, and internal topics can be printed with the -i
flag.

In the broker section, the controller node is suffixed with `\*`.

== Usage

[,bash]
----
rpk cluster metadata [flags]
----

== Aliases

[,bash]
----
metadata, status, info
----

== Flags

////
[cols=",,",]
|===
|*Value* |*Type* |*Description*

|-h, --help |- |Help for metadata.

|-b, --print-brokers |- |Print brokers section.

|-c, --print-cluster |- |Print cluster section.

|-d, --print-detailed-topics |- |Print per-partition information for
topics (implies -t).

|-i, --print-internal-topics |- |Print internal topics (if all topics
requested, implies -t).

|-t, --print-topics |- |Print topics section (implied if any topics are
specified).

|--brokers |strings |Comma-separated list of broker <ip>:<port> pairs
(for example,
` --brokers \'192.168.78.34:9092,192.168.78.35:9092,192.179.23.54:9092\' `
). Alternatively, you may set the `REDPANDA_BROKERS` environment
variable with the comma-separated list of broker addresses.

|--config |string |Redpanda config file, if not set the file will be
searched for in the default locations.

|--password |string |SASL password to be used for authentication.

|--sasl-mechanism |string |The authentication mechanism to use.
Supported values: SCRAM-SHA-256, SCRAM-SHA-512.

|--tls-cert |string |The certificate to be used for TLS authentication
with the broker.

|--tls-enabled |- |Enable TLS for the Kafka API (not necessary if
specifying custom certs).

|--tls-key |string |The certificate key to be used for TLS
authentication with the broker.

|--tls-truststore |string |The truststore to be used for TLS
communication with the broker.

|--user |string |SASL user to be used for authentication.

|-v, --verbose |- |Enable verbose logging (default `false`).
|===
////
