*Breaking change in Redpanda 25.2:* Ephemeral credentials for HTTP Proxy are removed. If your HTTP Proxy API listeners use xref:reference:properties/broker-properties.adoc#http_proxy_auth_method[`authentication_method`]: `none`, you must configure explicit SASL credentials (xref:reference:properties/broker-properties.adoc#scram_username[`scram_username`], xref:reference:properties/broker-properties.adoc#scram_password[`scram_password`], and xref:reference:properties/broker-properties.adoc#sasl_mechanism[`sasl_mechanism`]) for HTTP Proxy to authenticate with the Kafka API.

[WARNING]
====
This allows any HTTP API user to access Kafka using shared credentials. Redpanda Data recommends enabling xref:develop:http-proxy.adoc#authenticate-with-http-proxy[HTTP Proxy authentication] instead.
====

// tag::include-config-link[]
For configuration instructions, see xref:manage:security/authentication.adoc#schema-and-http-to-redpanda[Configure HTTP Proxy to connect to Redpanda with SASL].
// end::include-config-link[]

// tag::include-release-notes-link[]
For details about this breaking change, see xref:get-started:release-notes/redpanda.adoc#http-proxy-authentication-changes[What's new].
// end::include-release-notes-link[]