= Create a Dedicated Cloud Cluster
:description: Learn how to create a Dedicated cluster.
:page-aliases: cloud:create-dedicated-cloud-cluster-aws.adoc, deploy:deployment-option/cloud/provision-a-dedicated-cluster/index.adoc
:page-cloud: true

After you log in to https://cloud.redpanda.com[Redpanda Cloud^], you land on the *Clusters* page. This page lists all the clusters in your organization. 

== Create a Dedicated cluster

. On the Clusters page, click *Create cluster*, then click *Create Dedicated cluster*.
+
Enter a cluster name, then select the resource group, cloud provider (AWS or GCP), xref:reference:tiers/dedicated-tiers.adoc[region, availability zones, tier], and Redpanda version.
+
[NOTE]
====
* If you plan to create a private network in your own VPC, select the region where your VPC is located.
* Three availability zones provide two backups in case one availability zone goes down.
====

. Click *Next*.
. On the Network page, enter the connection type: *Public* or *Private*. For private networks:
** Your network name is used to identify this network.
** For a xref:networking:cidr-ranges.adoc[CIDR range], choose one that does not overlap with your existing VPCs or your Redpanda network.
+
NOTE: Private networks require a VPC peering connection. See xref:networking:dedicated/vpc-peering.adoc[Add a Dedicated VPC Peering Connection] to connect your VPC to the Redpanda Cloud VPC. 

. Click *Create*.

After the cluster is created, you can click the cluster name on the *Clusters* page to see the overview for it.
