= Deploy a Redpanda Cluster in Azure Kubernetes Service
:description: Deploy a secure Redpanda cluster and Redpanda Console in Azure Kubernetes Service (AKS) using the Helm chart.

Deploy a secure Redpanda cluster and Redpanda Console in Azure Kubernetes Service (AKS) using the Helm chart. After you deploy, use rpk both as an internal client and an external client to interact with your Redpanda cluster from the command line.

The Redpanda cluster has the following security features:

* SASL for authenticating users' connections.
* TLS with self-signed certificates for secure communication between the cluster and clients.

include::deploy:partial$kubernetes/guides/operator-note.adoc[]

== Prerequisites

Before you begin, you must have the following:

* You must satisfy the prerequisites listed in the https://learn.microsoft.com/en-us/azure/aks/learn/quick-kubernetes-deploy-cli#prerequisites[AKS quickstart]
to get access to the Azure CLI.
* https://kubernetes.io/docs/tasks/tools/[`kubectl`]. Minimum required Kubernetes version: {supported-kubernetes-version}
+
[,bash]
----
kubectl version --short --client
----

* https://helm.sh/docs/intro/install/[Helm]. Minimum required Helm version: {supported-helm-version}
+
[,bash]
----
helm version
----

== Create an AKS cluster

In this step, you create three worker nodes: one for each Redpanda broker.

You also configure your AKS cluster to give each worker node a public IP address, and allow external access to the node ports on which the Redpanda deployment will be exposed. You'll use these node ports in later steps to configure external access to your Redpanda cluster.

NOTE: The Helm chart configures `podAntiAffinity` rules to make sure that only one Redpanda broker Pod is scheduled on each worker node. For more information, see xref::kubernetes-cluster-requirements.adoc#number-of-worker-nodes[Kubernetes Cluster Requirements].

. Create a resource group for Redpanda:
+
[,bash]
----
az group create --name redpandaResourceGroup --location eastus
----

. Create an AKS cluster with three worker nodes (one for each Redpanda broker):
+
[,bash]
----
az aks create -g redpandaResourceGroup -n redpanda \
  --node-count 3 \
  --generate-ssh-keys \
  --enable-node-public-ip
----
+
TIP: For all available options, see the https://learn.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-create[AKS documentation].

. Get your subscription ID:
+
[,bash]
----
export SUBSCRIPTION_ID=$(az account show --query id --output tsv)
----

. Set up a connection to your AKS cluster:
+
[,bash]
----
az account set --subscription $SUBSCRIPTION_ID
az aks get-credentials --resource-group redpandaResourceGroup --name redpanda
----

. Open the https://portal.azure.com/[Azure Portal], search for 'Network security groups', and click the name of the network security group in the *MC_redpandaResourceGroup_redpanda_eastus* resource group.

. Add an inbound security rule with the following values:

* *Destination port ranges*:
+
----
31644,31092,30082,30081
----

* *Name*
+
----
AllowRedpandaNodePorts
----

include::deploy:partial$kubernetes/guides/deploy-redpanda.adoc[leveloffset=+1]

include::deploy:partial$kubernetes/guides/create-user.adoc[leveloffset=+1]

include::deploy:partial$kubernetes/guides/start-streaming.adoc[leveloffset=+1]

include::deploy:partial$kubernetes/guides/explore-topics-localhost.adoc[leveloffset=+1]

include::deploy:partial$kubernetes/guides/external-access-intro.adoc[leveloffset=+1]

include::deploy:partial$kubernetes/guides/external-access-steps.adoc[]

include::deploy:partial$kubernetes/default-components.adoc[leveloffset=+1]

include::deploy:partial$kubernetes/guides/troubleshoot.adoc[leveloffset=+1]

include::deploy:partial$kubernetes/guides/next-steps.adoc[leveloffset=+1]

include::deploy:partial$kubernetes/guides/suggested-reading.adoc[leveloffset=+1]
