= Deploy a Redpanda Cluster in Google Kubernetes Engine
:description: Deploy a secure Redpanda cluster and Redpanda Console in Google Kubernetes Engine (GKE) using the Helm chart.

Deploy a secure Redpanda cluster and Redpanda Console in Google Kubernetes Engine (GKE) using the Helm chart. Then, use rpk both as an internal client and an external client to interact with your Redpanda cluster from the command line.

The Redpanda cluster has the following security features:

* SASL for authenticating users' connections.
* TLS with self-signed certificates for secure communication between the cluster and clients.

include::partial$deployment-option/self-hosted/kubernetes/guides/operator-note.adoc[]

== Prerequisites

Before you begin, you must have the following:

* Complete the 'Before you begin' steps and the 'Launch Cloud Shell' steps of the https://cloud.google.com/kubernetes-engine/docs/deploy-app-cluster#before-you-begin[GKE quickstart]. Cloud Shell comes preinstalled with the Google Cloud CLI, the `kubectl` command-line tool, and the Helm package manager.
* https://kubernetes.io/docs/tasks/tools/[`kubectl`]. Minimum required Kubernetes version: {supported-kubernetes-version}
+
[,bash]
----
kubectl version --short --client
----

* https://helm.sh/docs/intro/install/[Helm]. Minimum required Helm version: {supported-helm-version}
+
[,bash]
----
helm version
----

== Create a GKE cluster

In this step, you create three worker nodes (one worker node for each Redpanda broker).

NOTE: Each Redpanda broker must run on its own worker node. As a result, the Helm chart configures `podAntiAffinity` rules to make sure that only one Redpanda broker Pod is scheduled on each worker node. For more information, see xref:./kubernetes-cluster-requirements.adoc#number-of-worker-nodes[Kubernetes Cluster Requirements].

You also configure your GKE cluster to allow external access to the node ports on which the Redpanda deployment will be exposed. You'll use these node ports in later steps to configure external access to your Redpanda cluster.

. Create a GKE cluster. Replace the `<region>` placeholder with your own region.
+
[,bash]
----
gcloud container clusters create redpanda \
  --machine-type n1-standard-4 \
  --num-nodes=3 \
  --region=<region>
----
+
[TIP]
====
To see all options that you can specify when creating a cluster, see the https://cloud.google.com/sdk/gcloud/reference/container/clusters/create[Cloud SDK reference].

Or, for help creating a GKE cluster, see the https://cloud.google.com/kubernetes-engine/docs/deploy-app-cluster#create_cluster[GKE documentation].
====

. Add inbound firewall rules to your instances so that external traffic can reach the following node ports on all Kubernetes worker nodes in the cluster:
+
* 31644
* 31092
* 30082
* 30081
+
For help creating firewall rules, see the https://cloud.google.com/vpc/docs/using-firewalls[Google VPC documentation].

include::partial$deployment-option/self-hosted/kubernetes/guides/deploy-redpanda.adoc[leveloffset=+1]

include::partial$deployment-option/self-hosted/kubernetes/guides/create-user.adoc[leveloffset=+1]

include::partial$deployment-option/self-hosted/kubernetes/guides/start-streaming.adoc[leveloffset=+1]

include::partial$deployment-option/self-hosted/kubernetes/guides/explore-topics-localhost.adoc[leveloffset=+1]

include::partial$deployment-option/self-hosted/kubernetes/guides/configure-external-access.adoc[leveloffset=+1]

include::partial$deployment-option/self-hosted/kubernetes/default-components.adoc[leveloffset=+1]

include::partial$deployment-option/self-hosted/kubernetes/guides/troubleshooting.adoc[leveloffset=+1]

include::partial$deployment-option/self-hosted/kubernetes/guides/next-steps.adoc[leveloffset=+1]

include::partial$deployment-option/self-hosted/kubernetes/guides/suggested-reading.adoc[leveloffset=+1]
