= Try the 25.1 Beta of the Redpanda Operator
:page-beta: true
:description: Deploy the 25.1 beta release of the Redpanda Operator or Redpanda Helm chart. This version of the Redpanda Operator no longer requires FluxCD or its custom resource definitions. In this version, the Redpanda Operator is responsible for reconciling the Redpanda cluster.

{description}

This beta version is available for testing and feedback. It is not supported by Redpanda and should not be used in production environments. To give feedback on beta releases, reach out to the Redpanda team in https://redpanda.com/slack[Redpanda Community Slack^].

== Prerequisites

Make sure that your Kubernetes cluster meets the xref:./k-requirements.adoc[requirements].

== Install Redpanda Operator v25.1-k8s-beta1

The Redpanda Operator is namespace scoped. You must install the Redpanda Operator in the same namespace as your Redpanda resource (Redpanda cluster).

. Make sure that you have permission to install custom resource definitions (CRDs):
+
```bash
kubectl auth can-i create CustomResourceDefinition --all-namespaces
```
+
You should see `yes` in the output.
+
You need these cluster-level permissions to install glossterm:cert-manager[^] and Redpanda Operator CRDs in the next steps.

. Install cert-manager:
+
```bash
helm repo add jetstack https://charts.jetstack.io
helm repo update
helm install cert-manager jetstack/cert-manager \
  --set crds.enabled=true \
  --namespace cert-manager \
  --create-namespace
```
+
TLS is enabled by default and cert-manager is used to manage TLS certificates.

. Install the Redpanda Operator CRDs:
+
[,bash,subs="attributes+"]
----
kubectl kustomize "https://github.com/redpanda-data/redpanda-operator//operator/config/crd?ref={operator-beta-tag}" \
    | kubectl apply --server-side -f -
----

. Deploy the Redpanda Operator.
+
[,bash,subs="attributes+"]
----
helm repo add redpanda https://charts.redpanda.com
helm upgrade --install redpanda-controller redpanda/operator \
  --namespace <namespace> \
  --create-namespace \
  --version {operator-beta-tag}
----

. Ensure that the Deployment is successfully rolled out:
+
```bash
kubectl --namespace <namespace> rollout status --watch deployment/redpanda-controller-operator
```
+
[.no-copy]
----
deployment "redpanda-controller-operator" successfully rolled out
----

. Install a xref:reference:k-crd.adoc[Redpanda custom resource] to deploy a Redpanda cluster and Redpanda Console v3.
+
.`redpanda-cluster.yaml`
[,yaml,subs="attributes+"]
----
apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
  name: redpanda
----

. If you want to use enterprise features in Redpanda, add the details of a Secret that stores your Enterprise Edition license key.
+
.`redpanda-cluster.yaml`
[,yaml,subs="attributes+"]
----
apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
  name: redpanda
spec:
  clusterSpec:
    enterprise:
      licenseSecretRef:
        name: <secret-name>
        key: <secret-key>
----
+
For details, see xref:get-started:licensing/add-license-redpanda/kubernetes.adoc[].

. Apply the Redpanda resource:
+
```bash
kubectl apply -f redpanda-cluster.yaml --namespace <namespace>
```
+
The Redpanda resource must be deployed in the same namespace as the Redpanda Operator.

. Wait for the Redpanda Operator to deploy the cluster:
+
```bash
kubectl get redpanda --namespace <namespace> --watch
```
+
[.no-copy]
----
NAME       READY   STATUS
redpanda   True    Redpanda reconciliation succeeded
----
+
This step may take a few minutes. You can watch for new Pods to make sure that the deployment is progressing:
+
```bash
kubectl get pod --namespace <namespace>
```
+
If it's taking too long, see xref:manage:kubernetes/troubleshooting/k-troubleshoot.adoc[Troubleshooting].


== Install the Redpanda Helm chart v25.1-k8s-beta1

. Install cert-manager using Helm:
+
```bash
helm repo add jetstack https://charts.jetstack.io
helm repo update
helm install cert-manager jetstack/cert-manager \
  --set crds.enabled=true \
  --namespace cert-manager  \
  --create-namespace
```
+
The Redpanda Helm chart enables TLS by default and uses cert-manager to manage TLS certificates.

. If you want to use enterprise features in Redpanda, add the details of a Secret that stores your Enterprise Edition license key.
+
.`redpanda-values.yaml`
[,yaml]
----
enterprise:
  licenseSecretRef:
    name: <secret-name>
    key: <secret-key>
----
+
For details, see xref:get-started:licensing/add-license-redpanda/kubernetes.adoc[].

. Install the Redpanda Helm chart to deploy a Redpanda cluster and Redpanda Console v3.
+
[source,bash,subs="attributes+"]
----
helm repo add redpanda https://charts.redpanda.com
helm repo update
helm install redpanda redpanda/redpanda \
  --version {helm-beta-tag}
  --namespace <namespace>
  --create-namespace \
  --values redpanda-values.yaml
----

. Wait for the Redpanda cluster to be ready:
+
```bash
kubectl --namespace <namespace> rollout status statefulset redpanda --watch
```
+
When the Redpanda cluster is ready, the output should look similar to the following:
+
[.no-copy]
----
statefulset rolling update complete 3 pods at revision redpanda-8654f645b4...
----

== Next steps

To give feedback about this beta version, reach out to the Redpanda team in https://redpanda.com/slack[Redpanda Community Slack^].
