= Kubernetes Cluster Requirements
:description: A list of requirements for provisioning Kubernetes clusters and worker nodes for running Redpanda in production.
:page-tags: ["Kubernetes"]

This topic is a checklist with the prerequisites and system requirements for installing production Redpanda in a Kubernetes cluster using the Helm chart.

== Operating system

Minimum required version of the Linux kernel: {supported-linux-kernel-version}

== Kubernetes

Minimum required Kubernetes version: {supported-kubernetes-version}

Make sure to do the following:

. https://kubernetes.io/docs/tasks/tools/[Install kubectl].
. https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/[Configure the `kubeconfig` file for your cluster].

== Helm

Minimum required Helm version: {supported-helm-version}

https://helm.sh/docs/intro/install/[Install Helm].

== Number of worker nodes

You must provision one worker node for each Redpanda broker that you plan to deploy in your Redpanda cluster. Each Pod replica that runs a Redpanda broker requires its own dedicated worker node for the following reasons:

* Redpanda brokers are designed to have access to all resources, such as CPU and memory, on their host machine.
* External clients access Redpanda brokers using the address of a worker node. See <<external-networking,External networking>>.

NOTE: The Helm chart configures `podAntiAffinity` rules to make sure that each Redpanda broker runs on its own worker node.

== Storage volumes

Redpanda brokers must store their data on disk. As a result, each Pod that runs a Redpanda broker must have its own storage volume.

For production, you must create and mount an *XFS file system* on any storage volumes that host the data directory of Redpanda (`/var/lib/redpanda/data`) or the Tiered Storage cache. XFS is a high-performance file system that provides important features for running Redpanda in production. NFS is not supported.

To learn what volumes Redpanda recommends, see the xref:./kubernetes-best-practices.adoc#storage[storage best practices].
To learn how to configure storage, see xref:manage:kubernetes/configure-storage.adoc[Configure storage].

== External networking

For external access, each worker node in your cluster must have a static, externally accessible IP address to allow clients to connect to the NodePort Service and access the Redpanda broker.
Redpanda uses the following default ports:

|===
| Node port | Purpose

| 30081
| Schema Registry

| 30082
| HTTP Proxy

| 31092
| Kafka API

| 31644
| Admin API
|===

Redpanda recommends using NodePorts instead of Loadbalancers. See the xref:./kubernetes-best-practices.adoc#external-networking[external networking best practices].

== Tuning

Before deploying Redpanda to production, each worker node that runs Redpanda must be tuned to optimize the Linux kernel for Redpanda processes.

See xref:./kubernetes-tune-workers.adoc[Tuning Kubernetes Worker Nodes for Production]

== Sizing

For help sizing your Kubernetes cluster, see xref:deploy:deployment-option/self-hosted/manual/sizing.adoc[Sizing Guidelines].

== Next steps

xref:./kubernetes-best-practices.adoc[Review the best practices].
