= Deploy Redpanda in Kubernetes
:description: Deploy a Redpanda cluster in Kubernetes.
:tags: ["Kubernetes"]

This topic describes how to deploy one or more Redpanda clusters in Kubernetes.

== Prerequisites

- Make sure that your Kubernetes cluster meets the xref:./kubernetes-cluster-requirements.adoc[requirements].
- Review the xref:./redpanda-cluster-recommendations.adoc[best practices and recommendations] to ensure that you configure Redpanda with the correct settings.

== Deploy a Redpanda cluster

To deploy Redpanda, you can use the following methods:

- *Helm and the Redpanda Operator*: Use the Redpanda Operator to manage your Redpanda cluster. To deploy a Redpanda cluster, you apply a Redpanda resource, which is used by the underlying Flux controllers to deploy the Redpanda Helm chart.
- *Helm*: Deploy the Redpanda Helm chart directly.

Regardless of the method you choose to deploy Redpanda, you'll deploy the Redpanda Helm chart, which includes Redpanda and the accompanying Redpanda Console. The Redpanda Console comes bundled as a subchart within the Redpanda Helm chart.

TIP: For more details about the differences between these two methods, see xref:./kubernetes-production-deployment.adoc[].

[tabs]
====
Helm + Operator::
+
--

The Redpanda Operator handles the deployment and management of the Redpanda Helm chart for you using https://fluxcd.io/flux/concepts/[Flux^].

The Redpanda Operator extends Kubernetes with custom resource definitions (CRDs), allowing you to define Redpanda clusters as native Kubernetes resources. The resource that the Redpanda Operator uses to represent a Redpanda cluster is the Redpanda resource.

When you deploy a Redpanda resource, the Redpanda Operator takes that configuration and passes it to Flux. Flux, in turn, interacts with Helm, creating the necessary HelmRepository and HelmRelease resources to deploy and manage the Redpanda Helm chart.

NOTE: The Redpanda Operator is namespace scoped. You must install the Redpanda Operator in the same namespace as your Redpanda resource (Redpanda cluster).

. Make sure that you have permission to install custom resource definitions (CRDs):
+
```bash
kubectl auth can-i create CustomResourceDefinition --all-namespaces
```
+
You should see `yes` in the output.
+
You need these cluster-level permissions to install glossterm:cert-manager[^] and Redpanda Operator CRDs in the next steps.

. Install https://cert-manager.io/docs/installation/helm/[cert-manager^]:
+
```bash
helm repo add jetstack https://charts.jetstack.io
helm repo update
helm install cert-manager jetstack/cert-manager \
  --set installCRDs=true \
  --namespace cert-manager  \
  --create-namespace
```
+
The Redpanda Helm chart enables TLS by default and uses cert-manager to manage TLS certificates.

. Install the Redpanda Operator CRDs:
+
```bash
kubectl kustomize https://github.com/redpanda-data/redpanda//src/go/k8s/config/crd | kubectl apply -f -
```

. Deploy the Redpanda Operator:
+
[,bash,subs="attributes+"]
----
helm repo add redpanda https://charts.redpanda.com
helm upgrade --install redpanda-controller redpanda/operator \
  --namespace <namespace> \
  --set image.repository=docker.redpanda.com/redpandadata/redpanda-operator \
  --set image.tag=v{full-version} \
  --create-namespace
----

. Ensure that the Deployment is successfully rolled out:
+
```bash
kubectl --namespace <namespace> rollout status --watch deployment/redpanda-controller-operator
```
+
[.no-copy]
----
deployment "redpanda-controller-operator" successfully rolled out
----

. Install a xref:reference:crd.adoc[Redpanda custom resource] to deploy a Redpanda cluster and Redpanda Console.
+
Ensure that you've read the <<Prerequisites>> section so that you can configure the cluster correctly.
+
.`redpanda-cluster.yaml`
[,yaml,lines=4+6+7]
----
apiVersion: cluster.redpanda.com/v1alpha1
kind: Redpanda
metadata:
  name: redpanda
spec:
  chartRef: {}
  clusterSpec: {}
----
+
- `metadata.name`: Name to assign the Redpanda cluster. This name is also assigned to the Helm release.
- xref:reference:crd.adoc#k8s-api-github-com-redpanda-data-redpanda-src-go-k8s-apis-redpanda-v1alpha1-chartref[`spec.chartRef`]: Information about the Helm chart that will be used to deploy Redpanda.
- xref:reference:crd.adoc#k8s-api-github-com-redpanda-data-redpanda-src-go-k8s-apis-redpanda-v1alpha1-redpandaclusterspec[`spec.clusterSpec`]: This is where you can override default values in the Redpanda Helm chart.

. Apply the Redpanda resource:
+
```bash
kubectl apply -f redpanda-cluster.yaml --namespace <namespace>
```
+
NOTE: The Redpanda resource must be deployed in the same namespace as the Redpanda Operator. Each new deployment of Redpanda requires a separate namespace.

. Wait for the Redpanda Operator to deploy Redpanda using the Helm chart:
+
```bash
kubectl get redpanda --namespace <namespace> --watch
```
+
[.no-copy]
----
NAME       READY   STATUS
redpanda   True    Redpanda reconciliation succeeded
----
+
This step may take a few minutes. You can watch for new Pods to make sure that the deployment is progressing:
+
```bash
kubectl get pod --namespace <namespace>
```
+
If it's taking too long, see xref:manage:kubernetes/troubleshooting/troubleshoot.adoc[Troubleshooting].

. Verify that each Redpanda broker is scheduled on only one Kubernetes node:
+
```bash
kubectl get pod --namespace <namespace>  \
  -o=custom-columns=NODE:.spec.nodeName,NAME:.metadata.name -l \
  app.kubernetes.io/component=redpanda-statefulset
```
+
Expected output:
+
[.no-copy]
----
example-worker3   redpanda-0
example-worker2   redpanda-1
example-worker    redpanda-2
----

--
Helm::
+
--

https://helm.sh/docs[Helm^] is a package manager for Kubernetes, which simplifies the process of defining, installing, and upgrading Kubernetes applications. Helm uses charts, a collection of files that describe a related set of Kubernetes resources, to deploy applications in a Kubernetes cluster.

. Install cert-manager using Helm:
+
```bash
helm repo add jetstack https://charts.jetstack.io
helm repo update
helm install cert-manager jetstack/cert-manager \
  --set installCRDs=true \
  --namespace cert-manager  \
  --create-namespace
```
+
The Redpanda Helm chart enables TLS by default and uses cert-manager to manage TLS certificates.

. Install the Redpanda Helm chart to deploy a Redpanda cluster and Redpanda Console.
+
Ensure that you've read the <<Prerequisites>> section so that you can configure the cluster correctly.
+
```bash
helm repo add redpanda https://charts.redpanda.com
helm install redpanda redpanda/redpanda \
  --namespace <namespace> \
  --create-namespace
```
+
NOTE: Each deployment of the Redpanda Helm chart requires a separate namespace. Ensure you choose a unique namespace for each deployment.

. Wait for the Redpanda cluster to be ready:
+
```bash
kubectl --namespace <namespace> rollout status statefulset redpanda --watch
```
+
When the Redpanda cluster is ready, the output should look similar to the following:
+
[.no-copy]
----
statefulset rolling update complete 3 pods at revision redpanda-8654f645b4...
----

. Verify that each Redpanda broker is scheduled on only one Kubernetes node:
+
```bash
kubectl get pod --namespace <namespace> \
-o=custom-columns=NODE:.spec.nodeName,NAME:.metadata.name -l \
app.kubernetes.io/component=redpanda-statefulset
```
+
Expected output:
+
[.no-copy]
----
example-worker3   redpanda-0
example-worker2   redpanda-1
example-worker    redpanda-2
----

--
====

=== Deploy multiple Redpanda clusters

You can deploy more than one Redpanda cluster in the same Kubernetes cluster by using a different namespace and unique node ports.

[tabs]
====
Helm + Operator::
+
--

. Install another instance of the Redpanda Operator in a different namespace to your existing ones. This Redpanda Operator will manage Redpanda clusters only in its namespace.
+
[,bash,subs="attributes+"]
----
helm repo add redpanda https://charts.redpanda.com
helm upgrade --install redpanda-controller redpanda/operator \
  --namespace <another-namespace> \
  --set image.repository=docker.redpanda.com/redpandadata/redpanda-operator \
  --set image.tag=v{full-version} \
  --create-namespace
----

. Apply a Redpanda resource in the same namespace as your new Redpanda Operator to deploy your new Redpanda cluster.
+
NOTE: Make sure to use unique node ports for the listeners in your Redpanda resource so that they don't conflict with any existing node ports in your other Redpanda clusters.
+
.`redpanda-cluster-two.yaml`
[,yaml]
----
apiVersion: cluster.redpanda.com/v1alpha1
kind: Redpanda
metadata:
  name: redpanda-two
spec:
  chartRef: {}
  clusterSpec:
    listeners:
      kafka:
        external:
          default:
            advertisedPorts: [31093]
      admin:
        external:
          default:
            advertisedPorts: [31645]
      http:
        external:
          default:
            advertisedPorts: [30083]
      rpc:
        port: 33146
      schemaRegistry:
        external:
          default:
            advertisedPorts: [30084]
----
--
Helm::
+
--
Install the Redpanda Helm chart in a different namespace to your existing Redpanda clusters.

NOTE: Make sure to use unique node ports for the listeners in your Redpanda resource so that they don't conflict with any existing node ports in your other Redpanda clusters.

```bash
helm repo add redpanda https://charts.redpanda.com
helm install redpanda-two redpanda/redpanda \
  --namespace <anothernamespace> \
  --set listeners.kafka.external.default.advertisedPorts[0]=31093 \
  --set listeners.admin.external.default.advertisedPorts[0]=31645 \
  --set listeners.http.external.default.advertisedPorts[0]=30083 \
  --set listeners.rpc.port=33146 \
  --set listeners.schemaRegistry.external.default.advertisedPorts[0]=30084
  --create-namespace
```
--

====

== Customize the deployment

To learn how to customize the Redpanda Helm chart, see xref:manage:kubernetes/configure-helm-chart.adoc[Customize the Helm Chart].

== Find the latest versions of the Redpanda Helm charts

To list the latest version of the Redpanda Helm chart, use the `helm search` command:

[,bash]
----
helm search repo redpanda
----

Example output:

[.no-copy]
----
NAME             	CHART VERSION	APP VERSION	DESCRIPTION
redpanda/redpanda	2.4.0        	v22.3.9    	Redpanda is the real-time engine for modern apps.
redpanda/console 	0.3.3        	v2.0.2     	Helm chart to deploy Redpanda Console.
----

To find the versions that are installed on your machine, run the following:

[,bash]
----
helm list --namespace <namespace>
----

include::deploy:partial$kubernetes/default-components.adoc[leveloffset=+1]

== Next steps

See the xref:manage:kubernetes/index.adoc[Manage Kubernetes topics] to learn how to customize the deployment to meet your needs.

include::shared:partial$suggested-reading.adoc[]

- xref:./k-high-availability.adoc[]
- xref:reference:redpanda-helm-spec.adoc[Redpanda Helm Specification]
- xref:reference:crd.adoc[Redpanda CRD Reference]
