= Deploy a Local Development Cluster with kind or minikube
:description: Deploy a local Redpanda cluster with Redpanda Console using the Helm chart.

Deploy a local Redpanda cluster with Redpanda Console using the Helm chart. Explore the essentials of how Redpanda works in Kubernetes and what components are deployed by default. Then, use rpk both as an internal client and an external client to interact with your Redpanda cluster from the command line.

include::deploy:partial$kubernetes/guides/operator-note.adoc[]

== Prerequisites

Before you begin, make sure that you have the correct software for your Kubernetes platform:

[tabs]
======
All platforms::
+
--

* https://kubernetes.io/docs/tasks/tools/[`kubectl`]. Minimum required Kubernetes version: {supported-kubernetes-version}
+
```bash
kubectl version --short --client
```

* https://helm.sh/docs/intro/install/[Helm]. Minimum required Helm version: {supported-helm-version}
+
```bash
helm version
```

--
kind::
+
--

* https://kind.sigs.k8s.io/docs/user/quick-start/#installation[kind]

* https://docs.docker.com/get-docker/[Docker]

--
minikube::
+
--

https://minikube.sigs.k8s.io/docs/start/[minikube]

--
======

== Create a Kubernetes cluster

In this step, you create one master and three worker nodes (one worker node for each Redpanda broker).

[tabs]
======
kind::
+
--

. Define a cluster in the `kind.yaml` configuration file:
+
```bash
cat <<EOF >kind.yaml
---
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
EOF
```

. Create the Kubernetes cluster from the configuration file:
+
```bash
kind create cluster --config kind.yaml
```

--
minikube::
+
--

. Create the Kubernetes cluster:
+
```bash
minikube start --namespace redpanda --nodes 4
```

. Prevent applications from being scheduled on the Kubernetes control plane node:
+
```bash
kubectl taint node \
  -l node-role.kubernetes.io/control-plane="" \
    node-role.kubernetes.io/control-plane=:NoSchedule
```
--
======

== Deploy Redpanda and Redpanda Console

In this step, you deploy Redpanda with self-signed TLS certificates. Redpanda Console is included as a subchart in the Redpanda Helm chart.

. Install https://cert-manager.io/docs/installation/helm/[cert-manager] using Helm:
+
```bash
helm repo add jetstack https://charts.jetstack.io
helm repo update
helm install cert-manager jetstack/cert-manager \
  --set installCRDs=true \
  --namespace cert-manager  \
  --create-namespace
```
+
TLS is enabled by default. The Redpanda Helm chart uses cert-manager to manage TLS certificates by default.

. Install Redpanda:
+
```bash
  export DOMAIN=customredpandadomain.local && \
  helm repo add redpanda https://charts.redpanda.com/
  helm repo update
  helm install redpanda redpanda/redpanda \
    --namespace redpanda \
    --create-namespace \
    --set external.domain=${DOMAIN} \
    --set statefulset.initContainers.setDataDirOwnership.enabled=true
```
+
The installation displays some tips for getting started.

. Wait for the Redpanda cluster to be ready:
+
```bash
kubectl -n redpanda rollout status statefulset redpanda --watch
```
+
When the Redpanda cluster is ready, the output should look similar to the following:
+
[.no-copy]
----
statefulset rolling update complete 3 pods at revision redpanda-8654f645b4...
----
+
If your cluster remains in a pending state, see <<Troubleshooting>>.

== Start streaming

Each Redpanda broker comes with rpk, which is a CLI tool for connecting to and interacting with Redpanda brokers. You can use rpk inside one of the Redpanda broker's Docker containers to create a topic, produce messages to it, and consume messages from it.

. Create an alias to simplify the `rpk` commands:
+
```bash
alias rpk-topic="kubectl -n redpanda exec -i -t redpanda-0 -c redpanda -- rpk topic --brokers redpanda-0.redpanda.redpanda.svc.cluster.local.:9093,redpanda-1.redpanda.redpanda.svc.cluster.local.:9093,redpanda-2.redpanda.redpanda.svc.cluster.local.:9093 --tls-truststore /etc/tls/certs/default/ca.crt --tls-enabled"
```

. Create a topic called `twitch_chat`:
+
[,bash]
----
rpk-topic create twitch_chat
----
+
Example output:
+
[.no-copy]
----
TOPIC STATUS twitch_chat OK
----

. Describe the topic:
+
[,bash]
----
rpk-topic describe twitch_chat
----
+
Example output:
+
[.no-copy]
----
SUMMARY
=======
NAME        twitch_chat
PARTITIONS  1
REPLICAS    1
CONFIGS
=======
KEY                           VALUE       SOURCE
cleanup.policy                delete      DYNAMIC_TOPIC_CONFIG
compression.type              producer    DEFAULT_CONFIG
max.message.bytes             1048576     DEFAULT_CONFIG
message.timestamp.type        CreateTime  DEFAULT_CONFIG
redpanda.remote.delete        true        DEFAULT_CONFIG
redpanda.remote.read          false       DEFAULT_CONFIG
redpanda.remote.write         false       DEFAULT_CONFIG
retention.bytes               -1          DEFAULT_CONFIG
retention.local.target.bytes  -1          DEFAULT_CONFIG
retention.local.target.ms     86400000    DEFAULT_CONFIG
retention.ms                  604800000   DEFAULT_CONFIG
segment.bytes                 134217728   DEFAULT_CONFIG
segment.ms                    1209600000  DEFAULT_CONFIG
----

. Produce a message to the topic:
+
[,bash]
----
rpk-topic produce twitch_chat
----

. Type a message, then press kbd:[Enter]:
+
[,plain,role=no-copy]
----
Pandas are fabulous!
----
+
Example output:
+
[.no-copy]
----
Produced to partition 0 at offset 0 with timestamp 1663282629789.
----

. Press kbd:[Ctrl + C] to finish producing messages to the topic.

. Consume one message from the topic:
+
[,bash]
----
rpk-topic consume twitch_chat --num 1
----
+
Example output:
+
[,json,role=no-copy]
----
{
  "topic": "twitch_chat",
  "value": "Pandas are fabulous!",
  "timestamp": 1663282629789,
  "partition": 0,
  "offset": 0
}
----

include::deploy:partial$kubernetes/guides/explore-topics-localhost.adoc[leveloffset=+1]

include::deploy:partial$kubernetes/guides/external-access-intro.adoc[leveloffset=+1]

. Add mappings in your `/etc/hosts` file between your worker nodes' IP addresses and their custom domain names:
+
```bash
sudo true && kubectl -n redpanda get endpoints,node -A -o go-template='{{ range $_ := .items }}{{ if and (eq .kind "Endpoints") (eq .metadata.name "redpanda-external") }}{{ range $_ := (index .subsets 0).addresses }}{{ $nodeName := .nodeName }}{{ $podName := .targetRef.name }}{{ range $node := $.items }}{{ if and (eq .kind "Node") (eq .metadata.name $nodeName) }}{{ range $_ := .status.addresses }}{{ if eq .type "InternalIP" }}{{ .address }} {{ $podName }}.${DOMAIN}{{ "\n" }}{{ end }}{{ end }}{{ end }}{{ end }}{{ end }}{{ end }}{{ end }}' | envsubst | sudo tee -a /etc/hosts
```
+
.`/etc/hosts`
----
203.0.113.3 redpanda-0.customredpandadomain.local
203.0.113.5 redpanda-1.customredpandadomain.local
203.0.113.7 redpanda-2.customredpandadomain.local
----

. Save the root certificate authority (CA) to your local file system outside Kubernetes:
+
[,bash]
----
kubectl -n redpanda get secret redpanda-default-root-certificate -o go-template='{{ index .data "ca.crt" | base64decode }}' > ca.crt
----

. Install rpk on your local machine, not on a Pod:
+
[tabs]
=====
Linux::
+
--

include::get-started:partial$install-rpk-linux.adoc[]

--
macOS::
+
--

include::get-started:partial$install-rpk-homebrew.adoc[]

--
=====

. Set the `REDPANDA_BROKERS` environment variable to the custom domains of your Redpanda brokers:
+
[,bash]
----
export REDPANDA_BROKERS=redpanda-0.customredpandadomain.local:31092,redpanda-1.customredpandadomain.local:31092,redpanda-2.customredpandadomain.local:31092
----
+
NOTE: 31092 is the Kafka API port that's exposed by the default NodePort Service.

. Describe the topic:
+
```bash
rpk topic describe twitch_chat --tls-enabled --tls-truststore=ca.crt
```
+
Example output:
+
[.no-copy]
----
SUMMARY
=======
NAME        twitch_chat
PARTITIONS  1
REPLICAS    1
CONFIGS
=======
KEY                     VALUE                          SOURCE
cleanup.policy          delete                         DYNAMIC_TOPIC_CONFIG
compression.type        producer                       DEFAULT_CONFIG
message.timestamp.type  CreateTime                     DEFAULT_CONFIG
partition_count         1                              DYNAMIC_TOPIC_CONFIG
redpanda.datapolicy     function_name:  script_name:   DEFAULT_CONFIG
redpanda.remote.read    false                          DEFAULT_CONFIG
redpanda.remote.write   false                          DEFAULT_CONFIG
replication_factor      1                              DYNAMIC_TOPIC_CONFIG
retention.bytes         -1                             DEFAULT_CONFIG
retention.ms            604800000                      DEFAULT_CONFIG
segment.bytes           1073741824                     DEFAULT_CONFIG
----

include::deploy:partial$kubernetes/default-components.adoc[leveloffset=+1]

include::deploy:partial$kubernetes/guides/troubleshoot.adoc[leveloffset=+1]

include::deploy:partial$kubernetes/guides/next-steps.adoc[leveloffset=+1]

include::deploy:partial$kubernetes/guides/suggested-reading.adoc[leveloffset=+1]