= Deserialization in Redpanda Console
:description: Learn how Redpanda Console deserializes records.
:page-aliases: console:features/record-deserialization.adoc

In Redpanda, the messages exchanged between producers and consumers contain raw bytes. Schemas enable producers and consumers to share the information needed to serialize and deserialize those messages. Schemas work as an agreed-upon format, like a contract, for sending and receiving messages. If a producer breaks this contract, consumers can fail. 

Redpanda Console automatically tries to deserialize incoming messages and show them in human-readable format. It tries different deserializers and lets you select the means of deserialization before producing the message in the desired format. Redpanda Console shows the deserialization format it selects, and if the deserialization fails, it provides troubleshooting information. For example, deserialization requires fetching schemas from a schema registry, and that fetch could fail. If downstream applications crash, you can find which messages caused the crash and check the message content and deserialization format. You can find messages (with filters or search) and view record properties and associated schemas. You can also download the raw bytes of the message to feed it directly to your client deserializer or share it with support.

== Automatically deserialize records

Redpanda Console tries to automatically identify the correct deserialization type by decoding the record's key, value, or header with all available deserialization methods. The following deserialization methods are supported:

* Kafka's internal binary formats; for example, the `__consumer_offsets` topic
* JSON
* JSON schema with schema registry encoding
* XML
* Avro with schema registry encoding
* Protobuf
* Protobuf with schema registry encoding
* Messagepack (for topics explicitly enabled to test MessagePack)
* UTF-8 / strings

Decoded messages are rendered as JSON objects and can also be used as JavaScript objects in
xref:./programmable-push-filters.adoc[push filters].
If none of these deserialization attempts are successful, Redpanda Console renders the byte array
in a hex viewer. Encoding formats that are not self-contained requires additional configuration. 

== Manually deserialize records

If you don't want to rely on automatic deserialization, or if the automatic deserialization fails, you can manually select the deserialization format. This is helpful when using plain numbers (for example, int or int32) as the type for key/value, because it might not show up as a number.

== Suggested reading

* xref:manage:schema-reg/schema-reg-overview.adoc[]
* xref:manage:console/protobuf.adoc[]