= Record Deserialization
:description: Learn how record deserialization in Redpanda Console works and what encodings it supports.
:page-aliases: console:features/record-deserialization.adoc

When consuming messages, Redpanda Console's message viewer is capable of automatically deserializing messages.
It identifies the correct deserialization type by trying to decode the record's key, value, or header with all
available deserialization methods. The supported deserialization methods are:

* Kafka's internal binary formats (for example the `__consumer_offsets` topic )
* JSON
* JSON Schema with schema registry encoding
* XML
* Avro with schema registry encoding
* Protobuf
* Protobuf with schema registry encoding
* Messagepack (only for topics that are explicitly enabled to test MessagePack)
* UTF-8 / Strings

Decoded messages will be rendered as JSON objects and can also be used as JavaScript object in
xref:./programmable-push-filters.adoc[push filters].
If none of these deserialization attempts appear to be successful, Redpanda Console will render the byte array
in a hex viewer. Encoding formats that are not self-contained requires additional configuration. 

== Related topics

* xref:manage:console/protobuf.adoc[]
* xref:manage:schema-reg/schema-reg-overview.adoc[]
