= Introduction to rpk
:page-categories: rpk
:description: pass:q[Learn about `rpk` and how to use it to interact with your Redpanda cluster.]
// tag::single-source[]

The `rpk` command line interface tool is designed to manage your entire Redpanda cluster, without the need to run a separate script for each function, as with Apache Kafka. The `rpk` commands handle everything from configuring brokers to high-level general Redpanda tasks. For example, you can use `rpk` to monitor your cluster's health, perform tuning, and implement access control lists (ACLs) and other security features. You can also use `rpk` to perform basic streaming tasks, such as creating topics, producing to topics, and consuming from topics.

After you install `rpk`, you can use it to:

* Manage Redpanda
* Set up access control lists (ACLs) and other security features
* Create topics, produce to topics, and consume from topics

See also:

* xref:get-started:rpk-install.adoc[]
* xref:get-started:config-rpk-profile.adoc[]
// This topic is not available in our Cloud docs.
ifndef::env-cloud[]
* xref:get-started:rpk-quickstart.adoc[]
endif::[]

== Specify configuration properties

You can specify `rpk` command properties in the following ways:

* Create an xref:get-started:config-rpk-profile.adoc[`rpk profile`].
* Specify the appropriate flag on the command line.
* Define the corresponding environment variables.
+
Environment variable settings only last for the duration of a shell session.

Command line flag settings take precedence over the corresponding environment variables, and environment variables take precedence over configuration file settings. If a required flag is not specified on the command line, Redpanda searches the environment variable. If the environment variable is not set, the value in the `rpk.yaml` configuration file is used, if that file is available, otherwise the value in the `redpanda.yaml` configuration file is used.

TIP: If you specify `rpk` command properties in the configuration files or as environment variables, you don't need to specify them again on the command line.

=== Common configuration properties

Every `rpk` command supports a set of common configuration properties. You can set one or more options in an `rpk` command by using the `-X` flag:

[,bash]
----
rpk -X <config-option-1> -X <config-option-2>
----

Get a list of available options with `-X list`:

[,bash]
----
rpk -X list
----

Or, get a detailed description about each option with `-X help`:

[,bash]
----
rpk -X help
----

Every `-X` option can be translated into an environment variable by prefixing it with `RPK_` and replacing periods (`.`) with underscores (`_`). For example, the flag `tls.enabled` has the equivalent environment variable `RPK_TLS_ENABLED`.

Some of the common configuration properties apply across all `rpk` commands as defaults. These default properties have keys with names starting with `globals`, and they're viewable in `rpk -X list` and `rpk -X help`. For more details, see xref:reference:rpk/rpk-x-options.adoc[`rpk -X options`].

=== Environment variables

In addition to the `RPK_*` environment variables that correspond to `-X` options, `rpk` also supports legacy `REDPANDA_*` environment variables for backward compatibility and convenience. For a comprehensive list and configuration examples, see:

* xref:get-started:config-rpk-profile.adoc[rpk profiles] - Create and manage persistent configurations (recommended)
* xref:reference:rpk/rpk-x-options.adoc[rpk -X options] - Complete configuration reference including environment variables

== Next steps

* xref:get-started:rpk-install.adoc[]
* xref:reference:rpk/index.adoc[rpk Command reference]

// end::single-source[]
