= Redpanda Licensing
:description: Self-hosted Redpanda is free and source-available at the Redpanda GitHub repo. Additional features are included with an enterprise license.
:page-aliases: introduction:licenses.adoc

You can deploy Redpanda as a fully-managed cloud service (Redpanda Cloud) or in a self-hosted environment (Redpanda platform). To self-host Redpanda platform, select either the Community Edition or the Enterprise Edition:

* Redpanda Community Edition is free and source-available at the https://github.com/redpanda-data/redpanda[Redpanda GitHub repository^].
* Redpanda Enterprise Edition requires a license key and includes additional features.

[NOTE]
====
To learn about Redpanda Cloud deployments, see the xref:deploy:deployment-option/cloud/cloud-overview.adoc[].
====

== Redpanda Community Edition

Redpanda Community Edition is licensed with the Redpanda https://github.com/redpanda-data/redpanda/blob/dev/licenses/bsl.md[Business Source License^] (BSL). These core features are free and source-available.

[NOTE]
====
* Users cannot provide Redpanda as a commercial streaming or queuing service to others.
* The BSL code converts to Apache 2.0 licensing four years after each code merge.
====

== Redpanda Enterprise Edition

Redpanda Enterprise Edition is licensed with the https://github.com/redpanda-data/redpanda/blob/dev/licenses/rcl.md[Redpanda Community License^] (RCL). It includes the free features licensed under the Redpanda BSL, as well as the following features:

* xref:manage:tiered-storage.adoc[Tiered Storage]
* xref:manage:cluster-maintenance/continuous-data-balancing.adoc[Continuous Data Balancing]
* xref:manage:remote-read-replicas.adoc[Remote Read Replicas]
* xref:manage:audit-logging.adoc[Audit Logging]
* xref:manage:security/fips-compliance.adoc[FIPS Compliance]
* xref:manage:schema-id-validation.adoc[Server-side Schema ID Validation]
* xref:manage:security/authentication.adoc#enable-kerberos[Kerberos Authentication]
* xref:manage:security/authorization/rbac.adoc[Redpanda Role-Based Access Control (RBAC)]
* xref:manage:security/console/authorization.adoc[Redpanda Console Authorization (RBAC)]
* xref:manage:security/console/authentication.adoc[Redpanda Console Authentication]
* xref:redpanda-connect:components:outputs/snowflake_put.adoc[Snowflake connector for Redpanda Connect]
* xref:redpanda-connect:components:outputs/splunk_hec.adoc[Splunk connector for Redpanda Connect]

Enterprise features require a license key. You can evaluate enterprise features with a free 30-day trial. Contact https://redpanda.com/try-redpanda?section=enterprise-trial[Redpanda Sales^] to request a trial license, to extend your trial period, or to purchase an Enterprise Edition license. If you access an enterprise feature without a valid license, you get the following message:

----
Looks like you've enabled a Redpanda Enterprise feature without a valid license.
Please enter an active Redpanda license key (for example, rpk cluster license set <key>).
If you don't have one, please request a new/trial license at https://redpanda.com/license-request.
----

=== Apply a license key to Redpanda

A license key unlocks Redpanda Enterprise Edition features.

[tabs]
======
Linux or Docker::
+
--

To apply the license key to your cluster, run:

`rpk cluster license set`

Either provide a path to a file containing the license or provide the license string inline. For example, assuming you use the default admin host/port of `10.0.0.1:9644`, run:

```bash
rpk cluster license set --path <path-to-license-file> -X admin.hosts=10.0.0.1:9644
```

Or:

```bash
rpk cluster license set <license-string>
```

If neither the path nor the license string are provided, `rpk` looks for the license in `/etc/redpanda/redpanda.license`.

--
Kubernetes::
+
--

To apply the license key to your cluster using the Helm chart,
either provide a secret that contains the license or provide the license string inline:

- Use a secret:
+
[tabs]
====
--values::
+
.`license-key.yaml`
[,yaml]
----
enterprise:
  licenseSecretRef:
    name: <name-of-the-secret>
    key: <key-where-license-is-stored>
----
+
```bash
helm upgrade --install redpanda redpanda/redpanda --namespace <namespace> --create-namespace \
--values license-key.yaml
```

--set::
+
```bash
helm upgrade --install redpanda redpanda/redpanda --namespace <namespace> --create-namespace \
  --set enterprise.licenseSecretRef.name=<name-of-the-secret> \
  --set enterprise.licenseSecretRef.key=<key-where-license-is-stored>
```
====
+
helm_ref:enterprise.licenseSecretRef[]

- Use an inline string:
+
[tabs]
====
--values::
+
.`license-key.yaml`
[,yaml]
----
enterprise:
  license: <license-string>
----
+
```bash
helm upgrade --install redpanda redpanda/redpanda --namespace <namespace> --create-namespace \
--values license-key.yaml
```

--set::
+
```bash
helm upgrade --install redpanda redpanda/redpanda --namespace <namespace> --create-namespace \
  --set enterprise.license=<license-string>
```
====
+
helm_ref:enterprise.license[]

If neither the path nor the license string are provided, Redpanda looks for the license in `/etc/redpanda/redpanda.license`.

--
======

=== Check the status of a license

To check the status of your current license, run:

`rpk cluster license info -X admin.hosts=10.0.0.1:9644`

Redpanda sends warning messages in the cluster logs if you enable enterprise features without a valid license key.

=== Apply a license key to Redpanda Console

To use an enterprise feature with Redpanda Console, you must provide Redpanda Console with a copy of your license key.
You have two options for providing the license:

. Specify the path to the license key file either in the `redpanda.licenseFilepath` property of the `/etc/redpanda/redpanda-console-config.yaml` file or in the `REDPANDA_LICENSE_FILEPATH` environment variable.
. Specify the license key file contents directly either in the `redpanda.license` property of the YAML file or in the `REDPANDA_LICENSE` environment variable.

Redpanda Console checks the license key status on startup and warns you 30 days before the license expires. You can view the license key's expiration date in the startup logs.
If the license key expires at runtime, Redpanda Console shuts down. If the license has already
expired at startup, Redpanda Console prints an error message and exits.
