= Redpanda Self-Managed Quickstart
:description: Learn how to quickly start working with a local Redpanda cluster.
:page-aliases: install-upgrade:index.adoc, install-upgrade:index/index.adoc, install-upgrade:start-streaming.adoc, quickstart:console-installation, quickstart:quick-start-docker.adoc, quickstart:quick-start-linux.adoc, quickstart:quick-start-macos.adoc, quickstart:quick-start-windows.adoc, getting-started:quick-start-docker.adoc, getting-started:quick-start-linux.adoc, getting-started:quick-start-windows.adoc, getting-started:quick-start-macos.adoc, console:installation.adoc, get-started:quick-start/quick-start-console.adoc, get-started:quick-start/quick-start-macos.adoc, get-started:quick-start/quick-start-linux.adoc, get-started:quick-start/quick-start-docker.adoc
:page-categories: Deployment, Development, rpk
:env-docker: true
// ========================AUTOMATED TESTS===================================
// The comments in this file are used to run automated tests of all the documented steps. Tests are run on each pull request to the upstream repository using GitHub Actions. For more details about the testing tool we use, see https://doc-detective.com/.

// (test start {"id": "quickstart", "description": "Redpanda Self-Managed quickstart"})

{description}

This quickstart introduces you to Redpanda Self-Managed in a self-hosted environment with a minimal setup. Docker Compose provides a straightforward and reproducible setup process, whether you're exploring Redpanda for the first time or testing new configurations. The option between a single broker and a three-broker setup helps you test Redpanda for simplicity and resilience.

[NOTE]
====
Redpanda in Docker is supported only for development and testing.
To deploy Redpanda Self-Managed in production, use one of the following environments:

- xref:deploy:deployment-option/self-hosted/manual/index.adoc[Linux]
- xref:deploy:deployment-option/self-hosted/kubernetes/index.adoc[Kubernetes]

To download the Redpanda binary, see https://github.com/redpanda-data/redpanda/releases/latest[GitHub].

====

== Prerequisites

You need Docker Compose. For installation instructions, see the https://docs.docker.com/compose/install/[Docker Compose documentation^].

To check if you have Docker Compose installed, run:

```bash
docker compose version
```

You should see the version of Docker Compose that's installed on your local machine.

== Deploy Redpanda

For lightweight testing, you can start a single Redpanda broker,
or you can use a more robust example with three Redpanda brokers.

A single broker setup is the simplest way to get Redpanda up and running. It's ideal for initial exploration, learning, or development environments where high availability and fault tolerance are not critical concerns.

For production environments where you need more resilience, a three-broker setup is recommended. This configuration allows you to leverage Redpanda's replication capabilities, enhancing the durability and availability of your data.

[tabs]
======
Single Broker::
+
--
. xref:get-started:attachment$single-broker/docker-compose.yml[Download] the following `docker-compose.yml` file on your local file system.
+
.Reveal the YAML content
[%collapsible]
====
.`docker-compose.yml`
[,yaml,subs="attributes+"]
----
include::get-started:attachment$single-broker/docker-compose.yml[]
----
====

// (step {"action":"runShell", "command": "docker pull docker.redpanda.com/redpandadata/${REDPANDA_DOCKER_REPO:-redpanda}:${REDPANDA_VERSION:-latest} && docker pull docker.redpanda.com/redpandadata/${CONSOLE_DOCKER_REPO:-console}:${REDPANDA_CONSOLE_VERSION:-latest}", "workingDirectory": "../test-resources/single-broker", "timeout": 100000, "exitCodes": [0,1]})
// (step {"action":"runShell", "command": "docker compose up -d --wait", "workingDirectory": "../test-resources/single-broker", "timeout": 50000, "exitCodes": [0,1]})
// (step {"action":"wait", "duration": 10000})

. Run the following in the directory where you saved the `docker-compose.yml` file:
+
```bash
docker compose up -d
```
+
[.no-copy]
----
[+] Running 4/4
⠿ Network redpanda_network                 Created  0.0s
⠿ Volume "redpanda-quickstart_redpanda-0"  Created  0.0s
⠿ Container redpanda-0                     Started  0.3s
⠿ Container redpanda-console               Started  0.6s
----
--
Three Brokers::
+
--

. xref:get-started:attachment$three-brokers/docker-compose.yml[Download] the following `docker-compose.yml` file on your local file system.
+
.Reveal the YAML content
[%collapsible]
====
.`docker-compose.yml`
[,yaml,subs="attributes+"]
----
include::get-started:attachment$three-brokers/docker-compose.yml[]
----
====

. Run the following in the directory where you saved the `docker-compose.yml` file:
+
```bash
docker compose up -d
```
+
[.no-copy]
----
[+] Running 8/8
⠿ Network redpanda_network                  Created  0.0s
⠿ Volume "redpanda-quickstart_redpanda-0"   Created  0.0s
⠿ Volume "redpanda-quickstart_redpanda-1"   Created  0.0s
⠿ Volume "redpanda-quickstart_redpanda-2"   Created  0.0s
⠿ Container redpanda-0                      Started  0.3s
⠿ Container redpanda-console                Started  0.6s
⠿ Container redpanda-1                      Started  0.7s
⠿ Container redpanda-2                      Started  0.7s
----

--
======

== Start streaming

To start building a basic streaming application, you can use the `rpk` command-line tool to create a topic, produce messages to it, and consume messages from it.

Each Redpanda broker comes preinstalled with `rpk`, so you can use it inside one of the Redpanda broker's Docker containers, or you can install it on your local machine to test external connectivity.
The `docker-compose.yml` file configured the containers to expose ports on your localhost, so you can communicate with the cluster outside the Docker network.

To use `rpk` inside the Redpanda broker's Docker container:

. Get information about the cluster:
+
```bash
docker exec -it redpanda-0 rpk cluster info
```
// (step {"action":"runShell", "command": "rpk profile create quickstart --from-profile rpk-profile.yaml", "workingDirectory": "../test-resources"})
// (step {"action":"runShell", "command": "rpk cluster info", "workingDirectory": "../test-resources/single-broker"})


. Create a topic called **chat-room**:
+
```bash
docker exec -it redpanda-0 rpk topic create chat-room
```
+
Output:
+
```bash
TOPIC       STATUS
chat-room  OK
```
+
[TIP]
====
If you deployed three brokers, you can configure your topics with a replication factor of three. This replication factor provides high availability and data durability. For more details, see xref:develop:config-topics.adoc#choose-the-replication-factor[Choose the replication factor].

```bash
docker exec -it redpanda-0 rpk topic create chat-room --replicas 3
```
====
// (step {"action":"runShell", "command": "rpk topic create chat-room", "workingDirectory": "../test-resources/single-broker"})

. Produce a message to the topic:
+
```bash
docker exec -it redpanda-0 rpk topic produce chat-room
```

. Enter a message, then press kbd:[Enter]:
+
```text
Pandas are fabulous!
```
+
Example output:
+
[.no-copy]
----
Produced to partition 0 at offset 0 with timestamp 1663282629789.
----
// (step {"action":"runShell", "command": "echo 'Pandas are fabulous!' | rpk topic produce chat-room", "workingDirectory": "../test-resources/single-broker"})


. Press kbd:[Ctrl + C] to finish producing messages to the topic.

. Consume one message from the topic:
+
```bash
docker exec -it redpanda-0 rpk topic consume chat-room --num 1
```
+
Your message is displayed along with its metadata:
+
```json
{
  "topic": "chat-room",
  "value": "Pandas are fabulous!",
  "timestamp": 1663282629789,
  "partition": 0,
  "offset": 0
}
```
// (step {"action":"runShell", "command": "rpk topic consume chat-room --num 1", "output": "/Pandas are fabulous!/", "timeout": 10000})


To test external connectivity using your local machine:

. Install rpk on your local machine:
+
[tabs]
======
Linux::
+
--
[loweralpha]
include::get-started:partial$install-rpk-linux.adoc[tags=latest]
--
macOS::
+
--

[loweralpha]
include::get-started:partial$install-rpk-homebrew.adoc[]
--
======

. Get information about the cluster to test the connection:
+
```bash
rpk cluster info -X brokers=127.0.0.1:19092
```
+
NOTE: The Redpanda broker returns a list of all broker addresses, so `rpk` can communicate with all brokers directly. Each broker returns its configured `advertise-*` address that matches the port to which the initial connection has been made.

== Explore your topic

To explore your topic, you can use Redpanda Console, which you deployed in the `docker-compose.yml` file and is running locally on port 8080.
Redpanda Console is a developer-friendly web UI for managing and debugging your Redpanda cluster and your applications.

. http://127.0.0.1:8080/overview[Open Redpanda Console^] in a web browser.
+
An overview of the cluster status, cluster health, and broker details is displayed.

. Go to http://127.0.0.1:8080/topics/chat-room[**Topics** > **chat-room**].
+
The message that you produced to the topic is displayed along with some other details about the topic.

== Customize the quickstart

If you want to configure Redpanda or Redpanda Console, you need to customize the example Docker Compose file.

=== Configure Redpanda in Docker

To configure the Redpanda services with xref:reference:node-properties.adoc[node configuration properties], you can do the following:

- Pass configuration properties to the `--set` option in the `redpanda start` command. For example:
+
[,yaml]
----
redpanda:
  command:
    - redpanda
    - start
    - --set pandaproxy_client.retries=6
----

- Create a `redpanda.yaml` file and mount it to the `/etc/redpanda/` directory on the `redpanda` containers. For example, if you create the `redpanda.yaml` file in a directory called `redpanda-mounts`, configure the following volume mounts:
+
[,yaml]
----
redpanda:
  volumes:
    - ./redpanda-mounts:/etc/redpanda/
----

=== Configure Redpanda Console in Docker

To configure the Redpanda Console service with xref:reference:console/config.adoc[configuration properties], you can do the following:

* Use environment variables, for example:
+
[,yaml]
----
console:
  environment:
    KAFKA_RACKID: rack1
----

* Create a `redpanda-console-config.yaml` file and mount it to the `/etc/redpanda/` directory on the `redpanda-console` container. For example, if you create the `redpanda-console-config.yaml` file in a directory called `console-mounts`, configure the following volume mounts:
+
[,yaml]
----
console:
  volumes:
    - ./console-mounts:/etc/redpanda/
----

== Clean up

If you don't want to continue experimenting with your cluster, you can shut it down and delete the containers:

```bash
docker compose down
```

To delete the volumes along with all your cluster data:

```bash
docker compose down -v
```

// (step {"action":"runShell", "command": "rpk profile delete quickstart"})
// (step {"action":"runShell", "command": "docker compose down -v", "workingDirectory": "../test-resources/single-broker"})
// (test end)

== Next steps

- xref:redpanda-labs:ROOT:index.adoc[Try more examples in Redpanda Labs]
- xref:manage:console/index.adoc[Learn more about Redpanda Console]
- xref:rpk-install.adoc[Learn more about rpk]
- xref:deploy:deployment-option/self-hosted/manual/production/index.adoc[Deploy for development or production]
- Find the https://hub.docker.com/r/redpandadata/redpanda[Docker images for Redpanda^] on Docker Hub
- Find the https://hub.docker.com/r/redpandadata/console/tags[Docker images for Redpanda Console^] on Docker Hub

include::shared:partial$suggested-reading.adoc[]

Explore the `rpk` commands that you used in this quickstart:

- xref:reference:rpk/rpk-cluster/rpk-cluster.adoc[`rpk cluster`]
- xref:reference:rpk/rpk-topic/rpk-topic-create.adoc[`rpk topic create`]
- xref:reference:rpk/rpk-topic/rpk-topic-produce.adoc[`rpk topic produce`]
- xref:reference:rpk/rpk-topic/rpk-topic-consume.adoc[`rpk topic consume`]
