= Redpanda Cloud Quickstart
:description: Learn how to quickly install and run a Dedicated Cloud cluster.
:page-context-links: [{"name": "Docker", "to": "quick-start.adoc" },{"name": "Cloud", "to": "quick-start-cloud.adoc" }]
:page-cloud: true

TIP: The fastest and easiest way to start data streaming in the cloud is with a Serverless cluster. In less than one minute, you have a Serverless welcome cluster that includes a `hello-world` topic in AWS. You can interact with your Serverless cluster the same way you'd interact with a Dedicated or BYOC cluster. To learn more and sign up for a free trial, see xref:deploy:deployment-option/cloud/serverless.adoc[].

Spin up a Dedicated cluster with Redpanda Cloud, create a basic streaming application using the `rpk` command-line tool, and explore your cluster in glossterm:Redpanda Console[].

== Prerequisites

https://redpanda.com/try-redpanda?section=cloud-trial[Sign up for a trial^] of Redpanda Cloud - Dedicated Clusters.

== Deploy Redpanda

To deploy a Dedicated cluster in Redpanda Cloud, create a namespace, then follow the steps for creating a Dedicated cluster.

To create a namespace:

include::deploy:partial$cloud/create-namespace.adoc[]

To create a cluster:

. Click **Create Dedicated cluster**. 

. For cluster settings, enter **redpandaquickstart** for the cluster name. Use default values for the remaining properties, and click **Next**. 

. On the **Networking** page, use the default **Public** connection type, and click **Create**.

. Wait for your network and your cluster to be created.

== Start streaming

To start building a basic streaming application, you can use `rpk`, Redpanda's CLI, to create a topic, produce messages to it, and consume messages from it.

. Install `rpk` on your local machine:
+
NOTE: The `rpk` binary is not supported on Windows.
+
[tabs]
======
Linux::
+
--

[loweralpha]
include::partial$install-rpk-linux.adoc[]
--
macOS::
+
--

[loweralpha]
include::get-started:partial$install-rpk-homebrew.adoc[]
--
======

. On the **Overview** page of Redpanda Cloud, copy your bootstrap server address and set it as an environment variable on your local machine:
+
```bash
export RPK_BROKERS="<bootstrap-server-address>"
```

. In Redpanda Cloud, go to **Security** and create a user called **redpanda-chat-account** that uses the SCRAM-SHA-256 mechanism.

. Copy the password, and set the following environment variables on your local machine:
+
```bash
export REDPANDA_SASL_USERNAME="redpanda-chat-account"
export REDPANDA_SASL_PASSWORD="<password>"
export REDPANDA_SASL_MECHANISM="SCRAM-SHA-256"
```

. In Redpanda Cloud, click the name of your user and add the following permissions to the ACL (access control list):
+
- **Host**: *
- **Topic name**: `chat-room`
- **Operations**: All
+ 
. Click **Create**.

. Use `rpk` on your local machine to authenticate to Redpanda as the redpanda-chat-account user and get information about the cluster:
+
```bash
rpk cluster info -X tls.enabled=true
```

. Create a topic called `chat-room`.
+
You granted permissions to the **redpanda-chat-account** user to access only this topic.
+
```bash
rpk topic create chat-room -X tls.enabled=true
```
+
Output:
+
[.no-copy]
----
TOPIC       STATUS
chat-room  OK
----

. Produce a message to the topic:
+
```bash
rpk topic produce chat-room -X tls.enabled=true
```

. Enter a message, then press kbd:[Enter]:
+
```text
Pandas are fabulous!
```
+
Example output:
+
[.no-copy]
----
Produced to partition 0 at offset 0 with timestamp 1663282629789.
----

. Press kbd:[Ctrl + C] to finish producing messages to the topic.

. Consume one message from the topic:
+
```bash
rpk topic consume chat-room --num 1 -X tls.enabled=true
```
+
Your message is displayed along with its metadata:
+
```json
{
  "topic": "chat-room",
  "value": "Pandas are fabulous!",
  "timestamp": 1663282629789,
  "partition": 0,
  "offset": 0
}
```

== Explore your topic

In Redpanda Cloud, go to **Topics** > **chat-room**.

The message that you produced to the topic is displayed along with some other details about the topic.

== Clean up

If you don't want to continue experimenting with your cluster, you can delete it.

Go to **Cluster settings** and click **Delete cluster**.

== Next steps

- xref:develop:code-examples.adoc[Continue learning about client applications]
- xref:rpk-install.adoc[Learn more about rpk]
- xref:deploy:deployment-option/cloud/index.adoc[Learn more about Redpanda Cloud]

include::shared:partial$suggested-reading.adoc[]

Explore the `rpk` commands that you used in this quickstart:

- xref:reference:rpk/rpk-cluster/rpk-cluster.adoc[`rpk cluster`]
- xref:reference:rpk/rpk-topic/rpk-topic-create.adoc[`rpk topic create`]
- xref:reference:rpk/rpk-topic/rpk-topic-produce.adoc[`rpk topic produce`]
- xref:reference:rpk/rpk-topic/rpk-topic-consume.adoc[`rpk topic consume`]
