= Install rpk
:description: pass:q[The `rpk` tool is a single binary application that provides a way to interact with your Redpanda clusters from the command line.]
:page-aliases: quickstart:rpk-install.adoc
:page-categories: rpk

The `rpk` tool is a single binary application that provides a way to interact with your Redpanda clusters from the command line. 

* For self-hosted deployments, the `rpk` binary is bundled with the deployment, so it is automatically installed on each Redpanda broker. 

* For Redpanda Cloud deployments, you can install `rpk` on your local machine as a xref:./rpk-install.adoc[standalone binary]. This method can be also be used for self-hosted (including Kubernetes) deployments. To use `rpk` to communicate with a self-hosted Redpanda cluster, ensure the version of `rpk` that you install matches the version of Redpanda running in your cluster.

After you install `rpk`, you can use it to interact with a Redpanda cluster. The cluster can run on your local machine, or it can run externally on Redpanda Cloud or on a remote server.

After you install `rpk`, you can use it to:

* Monitor your cluster's health.
* Set up access control lists (ACLs) and other security features.
* Create topics, produce to topics, and consume from topics.

To install the `rpk` binary as a standalone application, follow the instructions for your operating system.

== Install rpk on Linux

include::partial$install-rpk-linux.adoc[]

== Install rpk on macOS

include::partial$install-rpk-macos.adoc[]

== Next steps

For a list of all `rpk` commands and their syntax, see the xref:reference:rpk/index.adoc[rpk documentation].
