= Introduction to rpk
:description: Redpanda Keeper (rpk) is a single binary application that provides a way to interact with your Redpanda clusters from the command line.
:page-aliases: quickstart:rpk-install.adoc

Redpanda Keeper (rpk) is a single binary application that provides a way to interact with your Redpanda clusters from the command line. You can install the `rpk` binary as a standalone tool. For example, you can use rpk to do the following:

* Interact with a Redpanda cluster.
* Run the xref:reference:rpk/rpk-redpanda/rpk-redpanda-tune.adoc[autotuner tool] to optimize the Linux kernel to give you the best performance.

NOTE: Redpanda includes rpk as part of the installation. Follow this guide only if you want to install rpk as a standalone tool.

To install the rpk binary as a standalone application, follow the instructions for your operating system.

== Install rpk on Linux

include::partial$install-rpk-linux.adoc[]

== Install rpk on macOS

include::partial$install-rpk-macos.adoc[]

== Next steps

For a list of all `rpk` commands and their syntax, see the xref:reference:rpk/index.adoc[rpk documentation].
