= First steps in rpk
:page-categories: rpk
// Do not put page aliases in the single-sourced content
// tag::single-source[]

This guide shows you how to use `rpk` to perform fundamental Redpanda tasks, including creating, producing to, describing, and deleting topics, as well as consuming records and managing consumer groups. Following these examples will help you quickly become more familiar with `rpk` commands and integrate them into your workflow.

== Creating a topic

To start streaming data, first create a topic as the destination for your records.

[source,bash]
----
rpk topic create tutorial
----

Output:
[source,bash]
----
TOPIC     STATUS
tutorial  OK
----

== Producing records to a topic

After creating a topic, produce records to it so downstream consumers can read them.

[source,bash]
----
rpk topic produce tutorial
----

Additional input:
[source,bash]
----
hello
world
----

Output:
[source,bash]
----
Produced to partition 0 at offset 0 with timestamp 1734640650348.
Produced to partition 0 at offset 1 with timestamp 1734640653558.
----

== Getting a description of a topic

Check a topic’s configuration and status to ensure it’s ready for use.

[source,bash]
----
rpk topic describe tutorial
----

Output:
[source,bash]
----
SUMMARY
=======
NAME        tutorial
PARTITIONS  1
REPLICAS    1

CONFIGS
=======
KEY                                   VALUE       SOURCE
cleanup.policy                        delete      DEFAULT_CONFIG
compression.type                      producer    DEFAULT_CONFIG
delete.retention.ms                   -1          DEFAULT_CONFIG
flush.bytes                           262144      DEFAULT_CONFIG
flush.ms                              100         DEFAULT_CONFIG
initial.retention.local.target.bytes  -1          DEFAULT_CONFIG
initial.retention.local.target.ms     -1          DEFAULT_CONFIG
max.message.bytes                     1048576     DEFAULT_CONFIG
message.timestamp.type                CreateTime  DEFAULT_CONFIG
redpanda.iceberg.delete               true        DEFAULT_CONFIG
redpanda.iceberg.mode                 disabled    DEFAULT_CONFIG
redpanda.leaders.preference           none        DEFAULT_CONFIG
redpanda.remote.delete                true        DEFAULT_CONFIG
redpanda.remote.read                  false       DEFAULT_CONFIG
redpanda.remote.write                 false       DEFAULT_CONFIG
retention.bytes                       -1          DEFAULT_CONFIG
retention.local.target.bytes          -1          DEFAULT_CONFIG
retention.local.target.ms             86400000    DEFAULT_CONFIG
retention.ms                          604800000   DEFAULT_CONFIG
segment.bytes                         134217728   DEFAULT_CONFIG
segment.ms                            1209600000  DEFAULT_CONFIG
write.caching                         true        DEFAULT_CONFIG
----

== Consuming records from a topic

Consume records from a topic to verify the data produced.

[source,bash]
----
# Consuming all
rpk topic consume tutorial
----

Output:
[source,bash]
----
\{ "topic": "tutorial", "value": "hello", "timestamp": 1678807229837, "partition": 0, "offset": 0 }
\{ "topic": "tutorial", "value": "world", "timestamp": 1678807232413, "partition": 0, "offset": 1 }
----

Consuming from an offset, where `3` is not inclusive: 
[source,bash]
----
rpk topic consume tutorial --offset 0:3
----
Output:
[source,bash]
----
\{ "topic": "tutorial", "value": "hello", "timestamp": 1678807229837, "partition": 0, "offset": 0 }
\{ "topic": "tutorial", "value": "world", "timestamp": 1678807232413, "partition": 0, "offset": 1 }
----

== Creating consumer groups and consuming topics

Organize consumers into groups to share workloads and balance consumption.

NOTE: The consumer group is created when you consume from a topic.

[source,bash]
----
rpk topic consume tutorial --group tutorial-group
----

Output:
[source,json]
----
{
  "topic": "tutorial",
  "value": "hello",
  "timestamp": 1734640650348,
  "partition": 0,
  "offset": 0
}
{
  "topic": "tutorial",
  "value": "world",
  "timestamp": 1734640653558,
  "partition": 0,
  "offset": 1
}
----

== List all consumer groups

List available consumer groups in your cluster.

[source,bash]
----
rpk group list
----

Output:
[source,bash]
----
BROKER  GROUP           STATE
0       tutorial-group  Empty
----

== Getting a description of a consumer group

View details about the consumer group’s state, coordinator, members, and offsets.

[source,bash]
----
rpk group describe tutorial-group
----
Output:
[source,bash]
----
GROUP        tutorial-group
COORDINATOR  0
STATE        Empty
BALANCER
MEMBERS      0
TOTAL-LAG    0

TOPIC     PARTITION  CURRENT-OFFSET  LOG-START-OFFSET  LOG-END-OFFSET  LAG   MEMBER-ID  CLIENT-ID  HOST
tutorial  0          2               0                 2               0
----

== Deleting a consumer group

Clean up by removing the tutorial consumer group once you’re done.

[source,bash]
----
rpk group delete tutorial-group
----
Output:
[source,bash]
----
GROUP           STATUS
tutorial-group  OK
----

== Deleting a topic

Clean up by removing the tutorial topic once you’re done.

[source,bash]
----
rpk topic delete tutorial
----
Output:
[source,bash]
----
TOPIC     STATUS
tutorial  OK
----

// end::single-source[]