= Install rpk
:page-aliases: quickstart:rpk-install.adoc
:page-categories: rpk
// Do not put page aliases in the single-sourced content
// tag::single-source[]
:description: pass:q[The `rpk` tool is a single binary application that provides a way to interact with your Redpanda clusters from the command line.]

The `rpk` tool is a single binary application that provides a way to interact with your Redpanda clusters from the command line. For example, you can use `rpk` to:

* Monitor your cluster's health.
* Set up access control lists (ACLs) and other security features.
* Create topics, produce to topics, and consume from topics.

ifndef::env-cloud[]
For Redpanda Self-Managed deployments, the `rpk` binary is automatically installed on each Redpanda broker. So, you can use the locally installed `rpk` binary to communicate with the local Redpanda cluster.

You can also install `rpk` on your local machine as a standalone binary. With this setup, you can connect to both a Redpanda cluster on your local machine, or an external one on a remote server.

If you use `rpk` as a standalone binary to communicate with a Redpanda cluster, ensure the version of `rpk` that you install matches the version of Redpanda running in your cluster.
endif::[]

To install the `rpk` binary as a standalone application, follow the instructions for your operating system.

== Install rpk on Linux

include::get-started:partial$install-rpk-linux.adoc[]

== Install rpk on macOS

include::get-started:partial$install-rpk-macos.adoc[]

== Next steps

For a list of all `rpk` commands and their syntax, see the xref:reference:rpk/index.adoc[rpk documentation].

// end::single-source[]
