= Install or Update rpk
:page-aliases: quickstart:rpk-install.adoc
:page-categories: rpk
// Do not put page aliases in the single-sourced content
// tag::single-source[]
:description: pass:q[Install or update `rpk` to interact with Redpanda from the command line.]

The `rpk` tool is a single binary application that provides a way to interact with your Redpanda clusters from the command line. For example, you can use `rpk` to do the following:

* Monitor your cluster's health
* Create, produce, and consume from topics
* Set up access control lists (ACLs) and other security features

ifndef::env-cloud[]
For Redpanda Self-Managed deployments, the `rpk` binary is automatically installed on each Redpanda broker, so you can use the locally installed `rpk` binary to communicate with the local Redpanda cluster.

You can also install `rpk` on your local machine as a standalone binary. With this setup, you can connect to a Redpanda cluster on your local machine and to an external one on a remote server. If you use `rpk` as a standalone binary to communicate with a Redpanda cluster, your installed version of `rpk` must match the version of Redpanda running in your cluster.
endif::[]

ifdef::env-cloud[]
Redpanda Cloud deployments should always use the latest version of `rpk`.
endif::[]

== Check rpk version

include::get-started:partial$rpk-version.adoc[]

== Install or update rpk on Linux

include::get-started:partial$install-rpk-linux.adoc[]

== Install or update rpk on macOS

include::get-started:partial$install-rpk-macos.adoc[]

== Next steps

For the complete list of `rpk` commands and their syntax, see the xref:reference:rpk/index.adoc[rpk reference].
// end::single-source[]
// Excluding the rpk quickstart from single-sourcing because it is not available in our Cloud docs.
Explore `rpk` with the xref:get-started:rpk-quickstart.adoc[].
