= What's New
:description: Summary of new features and updates in the release.

This topic summarizes new content added in version 23.3. For a complete list of all product updates, see the https://github.com/redpanda-data/redpanda/releases/[Redpanda release notes^]. 

See also: xref:deploy:deployment-option/cloud/whats-new-cloud.adoc[]

== Data transforms

Redpanda now provides the framework to build and deploy inline transformations (xref:develop:data-transforms/index.adoc[data transforms]) on data written to Redpanda topics, delivering processed and validated data to consumers in the format they expect. For example, you may have consumers that require you to redact credit card numbers or convert JSON to Avro. Data transforms use WebAssembly (Wasm) engines inside a broker, which eliminates the need to manage a separate stream processing environment or use third-party tools.

== OIDC authentication

You can xref:manage:security/authentication.adoc#enable-oidc[enable OIDC] for Redpanda to delegate the authentication process to an external identity provider (IdP) such as Okta, Azure AD, or on-premise Active Directory Federation Service (AD FS). When you enable OIDC, Redpanda does not need to manage user credentials directly, but can instead rely on the trusted authentication capabilities of IdPs. Redpanda's implementation of OIDC provides SASL/OAUTHBEARER support for the Kafka API, and enables standard OIDC authentication across the Schema Registry, HTTP Proxy, and Admin APIs.

== Audit logging 

Redpanda's xref:manage:audit-logging.adoc[audit logging] supports fine-grained reporting of events in the Kafka, HTTP Proxy, Schema Registry, and Admin APIs. Events include:

* Changes to clusters, users, topics, ACLs, or consumer groups
* Any time a user is authenticated
* Any time a topic is written to or read from (requires explicit opt-in)
* HTTP requests for the Schema Registry, HTTP Proxy, and Admin APIs

You can persistently store auditing events to a topic in an append-only fashion, which guarantees retention for the requested time period, even against Redpanda administrators. Auditing is compatible with the Open Cybersecurity Schema Framework (OCSF) and works with industry-standard tools, such as Splunk, Sumo Logic, and AWS.

== Whole cluster restore

With Tiered Storage enabled, you can do a whole cluster restore to recover data (including its metadata) from a failed cluster to a new cluster. This is a simpler and cheaper alternative to active-active replication, for example with MirrorMaker 2. Use this recovery method to restore your application to the latest functional state as quickly as possible.

== Recovery mode 

xref:manage:recovery-mode.adoc[Recovery mode] lets you repair and restore a failed cluster that cannot start normally due to issues such as a system crash or out-of-memory errors. In recovery mode, Redpanda limits functionality to cluster configuration changes and other manual administrative actions so that you can repair the cluster.

== Compaction improvements

xref:manage:cluster-maintenance/compaction-settings.adoc[Compaction] follows a new algorithm, making it more efficient and similar to Kafka's compaction. Redpanda builds a map of keys to track the latest offset per key using multiple segments. The compaction process uses this key map to de-dupe keys within the compacted segments. It no longer stores full-fidelity keys, but instead maps SHA-256 hashes to offsets. The amount of memory that each shard may use when creating the key map for a partition is configurable (default = 128 MiB). 

== Manually move partitions

As an alternative to Redpanda partition balancing, you now can xref:manage:cluster-maintenance/cluster-balancing.adoc#manually-move-partitions explicitely [change partition assignments] with `rpk cluster partitions move`.

== Broker time retention

Every time a producer posts a message to a topic, Redpanda records the broker's system date and time in the message's `broker_timestamp` property. This helps ensure that retention functions as intended in cases where a producer submits a message with a created timestamp skewed from the broker's time. 

== Monitor TLS certificates

Redpanda now xref:reference:public-metrics-reference.adoc#tls_metrics[exposes metrics] to help administrators manage their installed certificates. When queried, these metrics list details for all resources that have an installed certificate. This may include APIs, storage, or other assets. These metrics also support labels so that you can more readily report statistics on single resources. Configuring alerts on these metrics is a critical tool for managing certificate expiration and avoiding surprise outages. 

== Redpanda Console updates

- You can xref:manage:schema-reg/schema-reg-ui.adoc[perform Schema Registry operations] in Redpanda Console, such as registering a schema, creating a new version of it, and configuring compatibility. The Schema Registry page lists verified schemas, including their serialization format and versions. 
- Redpanda Console automatically tries to xref:reference:console/record-deserialization.adoc[deserialize] incoming messages and show them in human-readable format. It tests different deserialization strategies until it finds one with no errors. If no deserialization attempts are successful, Redpanda Console renders the byte array in a hex viewer and displays troubleshooting information.

== rpk updates

New `rpk` commands in this release include the following:

- xref:reference:rpk/rpk-registry/rpk-registry.adoc[`rpk registry`]: This includes commands to interact with the Schema Registry.
- xref:reference:rpk/rpk-transform/rpk-transform.adoc[`rpk transform`]: This includes commands to develop, deploy, and manage data transforms.
- xref:reference:rpk/rpk-cluster/rpk-cluster-partitions.adoc[`rpk cluster partitions`] This includes commands to move partitions, verify that the reassignment completes, and cancel moves.
- `rpk cluster partitions unsafe-recover`
- `rpk cluster txn` (?)

The following commands have new flags

- xref:reference:rpk/rpk-acl/rpk-acl.adoc[`rpk acl`]
- xref:reference:rpk/rpk-container/rpk-container-start.adoc[`rpk container start`]
- xref:reference:rpk/rpk-container/rpk-container-start.adoc[`rpk profile create`]
- xref:reference:rpk/rpk-topic/rpk-topic-consume.adoc[`rpk topic consume`]
- xref:reference:rpk/rpk-topic/rpk-topic-produce.adoc[`rpk topic produce`]

The following `rpk` commands have improved documentation or examples:

- xref:reference:rpk/rpk-cluster/rpk-cluster-config-set.adoc[`rpk cluster config set`]
- xref:reference:rpk/rpk-cluster/rpk-cluster-partitions-move-status.adoc[`rpk cluster partitions move-status`]
- xref:reference:rpk/rpk-debug/rpk-debug-bundle.adoc[`rpk debug bundle`]
- xref:reference:rpk/rpk-redpanda/rpk-redpanda-config-set.adoc[`rpk redpanda config set`]
- xref:reference:rpk/rpk-version.adoc[`rpk version`] 

The xref:reference:rpk/rpk-cluster/rpk-cluster-storage.adoc[`rpk cluster storage`] command was renamed. It still work with aliases. 

== Deprecated features 

The `delete_retention_ms` property has been xref:upgrade:deprecated/index.adoc[deprecated]. Use `log_retention_ms` instead. 

== Documentation enhancements

- Documentation search now include the option to search Redpanda blogs and videos. 
- xref:manage:cluster-maintenance/rolling-restart.adoc[Rolling restarts] involve restarting one broker at a time while the remaining brokers in your cluster continue running. The documentation has been clarified for restarts and upgrades.
- https://docs.redpanda.com/api/admin-api/#tag/Debugging/operation/get_cpu_profile[CPU profiler]: There is a new Admin API endpoint to query the CPU profiler for troubleshooting. 

== Next steps

xref:manage:cluster-maintenance/rolling-upgrade.adoc[Upgrade Redpanda]
