= What's New
:description: Summary of new features and updates in the release.

This topic includes new content added in version 23.3. For a complete list of all product updates, see the https://github.com/redpanda-data/redpanda/releases/tag/v23.3.1[Redpanda release notes^].

== Data transforms

Redpanda now provides the framework to build and deploy inline transformations (xref:develop:data-transforms/index.adoc[data transforms]) on data written to Redpanda topics, delivering processed and validated data to consumers in the format they expect. For example, you may have consumers that require you to redact credit card numbers or convert JSON to Avro. Data transforms use WebAssembly (Wasm) engines inside a broker, which eliminates the need to manage a separate stream processing environment or use third-party tools.

== OIDC authentication

You can xref:manage:security/authentication.adoc#enable-oidc[enable OIDC] so that Redpanda can delegate the authentication process to an external identity provider (IdP) such as Okta, Azure AD, or on-premise Active Directory Federation Service (AD FS). When you enable OIDC, Redpanda does not need to manage user credentials directly, but can instead rely on the trusted authentication capabilities of IdPs. Redpanda's implementation of OIDC provides SASL/OAUTHBEARER support for the Kafka API, and enables standard OIDC authentication across the Schema Registry, HTTP Proxy, and Admin APIs.

== Audit logging 

Redpanda's xref:manage:audit-logging.adoc[audit logging] supports fine-grained reporting of events in the Kafka, HTTP Proxy, Schema Registry, and Admin APIs. Events include:

* Changes to clusters, users, topics, ACLs, or consumer groups
* Any time a user is authenticated
* Any time a topic is written to or read from (requires explicit opt-in)
* HTTP requests for the Schema Registry, HTTP Proxy, and Admin APIs

You can persistently store auditing events to a topic in an append-only fashion, which guarantees retention for the requested time period, even against Redpanda administrators. Auditing is compatible with the Open Cybersecurity Schema Framework (OCSF) and works with industry-standard tools, such as Splunk, Sumo Logic, and AWS.

== Manually move partitions

As an alternative to Redpanda partition balancing, you now can xref:manage:cluster-maintenance/cluster-balancing.adoc#manually-move-partitions explicitely [change partition assignments] with `rpk cluster partitions move`.

== Improved compaction

To optimize storage utilization, you can enable compaction in a cluster or a topic's cleanup policy, and configure xref:manage:cluster-maintenance/compaction-settings.adoc[compaction settings] settings.

== Recovery mode 

xref:manage:recovery-mode.adoc[Recovery mode] lets you repair and restore a failed cluster that cannot start normally due to issues such as a system crash or out-of-memory errors. In recovery mode, Redpanda limits functionality to cluster configuration changes and other manual administrative actions so that you can repair the cluster.

== CPU profiler

There is a new Admin API endpoint to https://docs.redpanda.com/api/admin-api/#tag/Debugging/operation/get_cpu_profile[query the CPU profiler] for troubleshooting. 

== Redpanda Console updates

- You can xref:manage:schema-reg/schema-reg-ui.adoc[perform Schema Registry operations] in Redpanda Console, such as registering a schema, creating a new version of it, and configuring compatibility. The Schema Registry page lists verified schemas, including their serialization format and versions. 
- Redpanda Console automatically tries to xref:reference:console/record-deserialization.adoc[deserialize] incoming messages and show them in human-readable format. It tests different deserialization strategies until it finds one with no errors. If no deserialization attempts are successful, Redpanda Console renders the byte array in a hex viewer and displays troubleshooting information.

== Not yet merged

- The `delete_retention_ms` property has been deprecated. Use `log_retention_ms` in its place. (issue 1979)
- Whole cluster restore for disaster recovery (waiting final update & merge, issue 1978, https://github.com/redpanda-data/docs/pull/118[pr]) & DR in Kubernetes (Issue 1990). With automatic metadata backup, there's periodic backup of topics and schema definitions, consumer offsets, and users/ACLs to object storage. Metadata lives with topic data in the same bucket/container. With one-step cluster restore, an `rpk` command restores all cluster state from object storage. It aligns consumer offsets with topic data, allowing consumers to resume seamlessly.
- Node-wise partition recovery (Issue 1982)
- Public metrics TLS certificates (Issue 1950). You can monitor client and truststore certificates in Grafana by alerting and protecting against downtime from certificate expiration. This provides information on usage to ensure that services are using the correct certificate including Service (e.g., Kafka, Schema Registry), certificate serial number, date loaded.
- Broker time message retention and timestamp skew alerting (Issue 1980)

== New commands

New commands in this release include the following:

- xref:reference:rpk/rpk-registry/rpk-registry.adoc[`rpk registry`]: This includes commands to interact with the Schema Registry.
- xref:reference:rpk/rpk-transform/rpk-transform.adoc[`rpk transform`]: This includes commands to develop, deploy, and manage data transforms.
- xref:reference:rpk/rpk-cluster/rpk-cluster-partitions.adoc[`rpk cluster partitions`] This includes commands to move partitions, verify that the reassignment completes, and cancel moves.
- `rpk cluster txn` (?)

New flags

- `rpk acl` (and children)
- `rpk container start`
- `rpk profile create`
- `rpk topic consume`
- `rpk topic produce`

Renamed commands (old ones still work with aliases)

- `rpk cluster storage`

- The following `rpk` commands have improved documentation or examples:

** xref:reference:rpk/rpk-cluster/rpk-cluster-config-set.adoc[`rpk cluster config set`]
** xref:reference:rpk/rpk-cluster/rpk-cluster-partitions-move-status.adoc[`rpk cluster partitions move status`]
** xref:reference:rpk/rpk-debug/rpk-debug-bundle.adoc[`rpk debug bundle`]
** xref:reference:rpk/rpk-redpanda/rpk-redpanda-config-set.adoc[`rpk redpanda config set`]
** xref:reference:rpk/rpk-version.adoc[`rpk version`] 

== Documentation enhancements

- Documentation search now include the option to search Redpanda blogs and videos. 
- xref:manage:cluster-maintenance/rolling-restart.adoc[Rolling restarts] involve restarting one broker at a time while the remaining brokers in your cluster continue running. This is to minimize downtime during a full cluster restart.

== Next steps

xref:manage:cluster-maintenance/rolling-upgrade.adoc[Upgrade Redpanda]
