= What's New
:description: Summary of new features and updates in the release.
:page-aliases: get-started:whats-new-233.adoc, get-started:whats-new-241.adoc

This topic includes new content added in version {page-component-version}. For a complete list of all product updates, see the https://github.com/redpanda-data/redpanda/releases/[Redpanda release notes^]. See also:

* xref:redpanda-cloud:get-started:whats-new-cloud.adoc[] 
* xref:redpanda-cloud:get-started:cloud-overview.adoc#redpanda-cloud-vs-self-managed-feature-compatibility[Redpanda Cloud vs Self-Managed feature compatibility]

== Topics as Iceberg tables

The Redpanda xref:manage:topic-iceberg-integration.adoc[integration with Apache Iceberg] allows your topic data to be stored in the cloud in Iceberg's table format. This opens up immediate access to your streaming data for analytical systems such as data warehouses like RedShift, Snowflake, and Clickhouse, and big data processing platforms such as Apache Spark and Flink, without setting up and maintaining additional ETL pipelines.

The Iceberg integration uses Tiered Storage. When a cluster or topic is enabled with Tiered Storage, Redpanda stores the Iceberg files in the configured Tiered Storage bucket or container.

== Mountable Topics

For topics with Tiered Storage enabled, you can xref:manage:mountable-topics.adoc[mount and unmount topics] to transfer the topic data between your cluster and object storage. This effectively frees up unused partition space that can be reclaimed, enables you to migrate a topic to a different cluster, and allows the topic or even the entire cluster to hibernate or be decommissioned.

Redpanda also transfers topic definitions when mounting or unmounting a topic. An unmounted topic in object storage is detached from all clusters. The original cluster releases ownership of the topic. You can mount a topic from object storage that has been previously flushed from a source cluster to a different destination cluster, or back to the same source cluster.
