= What's New in 24.1
:description: Summary of new features and updates in the release.
:page-aliases: get-started:whats-new-233.adoc, get-started:whats-new-241.adoc

This topic includes new content added in version 24.1. For a complete list of all product updates, see the https://github.com/redpanda-data/redpanda/releases/[Redpanda release notes^]. 

See also: xref:deploy:deployment-option/cloud/whats-new-cloud.adoc[]

== Write caching

xref:develop:config-topics.adoc#configure-write-caching[Write caching] is a relaxed mode of `acks=all` that provides better performance at the expense of durability. It acknowledges a message as soon as it is received and acknowledged on a majority of brokers, without waiting for it to fsync to disk. This provides lower latency while still ensuring that a majority of brokers acknowledge the write. For clusters in development mode, write caching is enabled by default. For clusters in production mode, it is disabled by default.

== RBAC
xref:manage:security/authorization/rbac.adoc[Role-based access control] (RBAC) provides an extension to Redpanda's existing access control lists (ACLs). It allows you to create roles and assign those roles as the authorized or denied party for an ACL. Every user you assign to that role inherits those authorizations. RBAC provides a more flexible and efficient way to manage user permissions, especially with complex organizational hierarchies or large numbers of users.  

== Data transforms

* Output to multiple topics: Data transforms can now output to multiple topics, for use cases that might require distributing different message types to multiple event streams, or for writing valid records to an output topic and invalid records to a dead-letter queue. See the xref:reference:data-transform-golang-sdk.adoc[Go] or xref:reference:data-transform-rust-sdk.adoc[Rust] SDK reference for data transforms for implementation details.

* xref:develop:data-transforms/run-transforms.adoc#view-data-transform-logs[Data transform logs] are now stored in an internally-managed topic and are accessible via `rpk` and the Redpanda Console.

== Topic-aware partition balancing 

Redpanda now prioritizes xref:manage:cluster-maintenance/cluster-balancing.adoc[balancing a topic's partition replica count on each broker] while it's balancing the cluster's overall partition count. Because different topics in a cluster can have vastly different load profiles, this better distributes the workload evenly across brokers. This feature is enabled by default with the `partition_autobalancing_topic_aware` property. After upgrading to 24.1, new topics are distributed in a topic-aware fashion, and the next partition rebalance (triggered by adding new brokers or by calling the `/v1/partitions/rebalance` Admin API endpoint) evens out the partition counts on each broker.

== Topic recovery validation

The new properties xref:reference:cluster-properties.adoc[`cloud_storage_recovery_topic_validation_mode`] and xref:reference:cluster-properties.adoc[`cloud_storage_recovery_topic_validation_depth`] add a consistency check that runs before a `redpanda.remote.recovery=true` topic is recovered from object storage.

== Managed identities for Azure
Similar to the existing support for IAM roles for self-hosted deployments on AWS and GCP, Redpanda now supports managed identities for Azure resources. This provides a safer alternative to static credentials, like access keys. Managed identities allow Redpanda clusters deployed on Azure virtual machines (VMs) and on Azure Kubernetes Service (AKS) to access Azure Blob Storage (ABS) and other services without storing credentials in the cluster configuration.

== New commands

The following `rpk` commands are new in this release:

- xref:reference:rpk/rpk-security/rpk-security.adoc[`rpk security`]
- xref:reference:rpk/rpk-security/rpk-security-role.adoc[`rpk security role`]
- xref:reference:rpk/rpk-security/rpk-security-role-assign.adoc[`rpk security role assign`]
- xref:reference:rpk/rpk-security/rpk-security-role-create.adoc[`rpk security role create`]
- xref:reference:rpk/rpk-security/rpk-security-role-delete.adoc[`rpk security role delete`]
- xref:reference:rpk/rpk-security/rpk-security-role-describe.adoc[`rpk security role describe`]
- xref:reference:rpk/rpk-security/rpk-security-role-list.adoc[`rpk security role list`]
- xref:reference:rpk/rpk-security/rpk-security-role-unassign.adoc[`rpk security role unassign`]

Additionally, to bundle security commands together, the existing `rpk acl` commands have moved into this new section as xref:reference:rpk/rpk-security/rpk-security-acl.adoc[`rpk security acl`]. The existing `rpk acl` commands still work as an alias.

== Next steps

* xref:get-started:install-beta.adoc[]