= What's New
:description: Summary of new features and updates in the release.
:page-aliases: get-started:whats-new-233.adoc, get-started:whats-new-241.adoc

This topic includes new content added in version {page-component-version}. For a complete list of all product updates, see the https://github.com/redpanda-data/redpanda/releases/[Redpanda release notes^]. See also:

* xref:redpanda-cloud:get-started:whats-new-cloud.adoc[] 
* xref:redpanda-cloud:get-started:cloud-overview.adoc#redpanda-cloud-vs-self-hosted-feature-compatibility[Redpanda Cloud vs self-hosted feature compatibility]

== Declarative User and ACL management in Kubernetes

Redpanda now supports declarative management of users and access control lists (ACLs) using the new User resource with the Redpanda Operator. This feature allows you to:

- Create and manage Redpanda users and their authentication settings.
- Define and manage ACLs to control access to Redpanda resources.
- Automatically reconcile changes to users and ACLs using the Redpanda Operator.

To learn more, see the xref:manage:kubernetes/security/authentication/k-user-controller.adoc[User resource documentation].
