= What's New
:description: Summary of new features and updates in the release.
:page-aliases: get-started:whats-new-233.adoc, get-started:whats-new-241.adoc

This topic includes new content added in version 24.1. For a complete list of all product updates, see the https://github.com/redpanda-data/redpanda/releases/[Redpanda release notes^]. 

See also: xref:deploy:deployment-option/cloud/whats-new-cloud.adoc[]

== Write caching

xref:develop:config-topics.adoc#configure-write-caching[Write caching] is a relaxed mode of `acks=all` that provides better performance at the expense of durability. It acknowledges a message as soon as it is received and acknowledged on a majority of brokers, without waiting for it to fsync to disk. This provides lower latency while still ensuring that a majority of brokers acknowledge the write. For clusters in development mode, write caching is enabled by default. For clusters in production mode, it is disabled by default.

== RBAC
xref:manage:security/authorization/rbac.adoc[Role-based access control] (RBAC) provides an extension to Redpanda's existing access control lists (ACLs). Using `rpk` or Redpanda Console, you can create roles and assign those roles as the authorized or denied party for an ACL. Every user you assign to that role inherits those privileges. RBAC provides a more flexible and efficient way to manage user privileges, especially with complex organizational hierarchies or large numbers of users.  

== Data transforms

Data transforms is now generally available for all Redpanda Community and Redpanda Enterprise users. This provides the framework to build and deploy inline transformations on data written to Redpanda topics using WebAssembly, delivering processed and validated data to consumers in the format they expect. 

The following features have been added since the 23.3 beta release:

* Data transforms can now output to multiple topics.  For example, you can distribute different message types to multiple event streams, or you can write valid records to an output topic and invalid records to a dead-letter queue. 

* There is a new xref:reference:data-transform-rust-sdk.adoc[Rust SDK] for data transforms. This complements the existing xref:reference:data-transform-golang-sdk.adoc[Golang SDK]. 

* xref:develop:data-transforms/run-transforms.adoc#view-data-transform-logs[Data transform logs] are now stored in an internally-managed topic and are accessible via `rpk` and Redpanda Console.

== Topic-aware partition balancing 

Redpanda now prioritizes xref:manage:cluster-maintenance/cluster-balancing.adoc[balancing a topic's partition replica count evenly across all brokers] while it's balancing the cluster's overall partition count. Because different topics in a cluster can have vastly different load profiles, this better distributes the workload of the most heavily-used topics evenly across brokers. This feature is enabled by default with the `partition_autobalancing_topic_aware` property. After upgrading to 24.1, new topics are distributed in a topic-aware fashion, and the next partition rebalance (triggered by Continuous Data Balancing, by adding new brokers, or by calling the `/v1/partitions/rebalance` Admin API endpoint) evens out the partition counts on each broker.

== Managed identities for Azure
Redpanda xref:manage:tiered-storage.adoc#tabs-1-microsoft-absadls[Tiered Storage] now supports https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/overview[managed identities for Azure] resources, similar to the existing support for IAM roles for self-hosted deployments on AWS and GCP. This provides a more secure alternative to static credentials, like access keys. Managed identities allow Redpanda clusters deployed on Azure virtual machines and on Azure Kubernetes Service (AKS) to access Azure Blob Storage (ABS) and other services without storing credentials in the cluster configuration.

== Improved fetch latency

The new cluster configuration property xref:reference:properties/cluster-properties.adoc#fetch_read_strategy[`fetch_read_strategy`] implements a non-polling strategy to fulfill fetch requests. The backend is signaled when a partition has new data, so it doesn't need to repeatedly read from every partition in the fetch. This improves fetch latency when there is extra CPU space. 

== Validation before topic recovery or cluster restore

Before topic recovery or cluster restore, the properties xref:reference:cluster-properties.adoc#cloud_storage_recovery_topic_validation_mode[`cloud_storage_recovery_topic_validation_mode`] and xref:reference:cluster-properties.adoc#cloud_storage_recovery_topic_validation_depth[`cloud_storage_recovery_topic_validation_depth`] now check that partition manifests exist and confirm that there are no connection issues to object storage. 

== New commands

The following `rpk` commands are new in this release:

- xref:reference:rpk/rpk-redpanda/rpk-redpanda-tune-help.adoc[`rpk redpanda tune help`]
- xref:reference:rpk/rpk-transform/rpk-transform-logs.adoc[`rpk transform logs`]
- xref:reference:rpk/rpk-security/rpk-security.adoc[`rpk security`]
- xref:reference:rpk/rpk-security/rpk-security-role.adoc[`rpk security role`]
- xref:reference:rpk/rpk-security/rpk-security-role-assign.adoc[`rpk security role assign`]
- xref:reference:rpk/rpk-security/rpk-security-role-create.adoc[`rpk security role create`]
- xref:reference:rpk/rpk-security/rpk-security-role-delete.adoc[`rpk security role delete`]
- xref:reference:rpk/rpk-security/rpk-security-role-describe.adoc[`rpk security role describe`]
- xref:reference:rpk/rpk-security/rpk-security-role-list.adoc[`rpk security role list`]
- xref:reference:rpk/rpk-security/rpk-security-role-unassign.adoc[`rpk security role unassign`]

Additionally, to bundle security commands together, the existing `rpk acl` commands have moved into this new section as xref:reference:rpk/rpk-security/rpk-security-acl.adoc[`rpk security acl`]. The existing `rpk acl` commands still work as an alias.

== Documentation enhancements

* https://docs.redpanda.com/redpanda-labs/[Redpanda Labs] provide examples, guidance, best practices, and ideas for how to use Redpanda in your own project.
* Improved search lets you filter for blogs, videos, labs, and documentation for all supported versions.  
* New xref:upgrade:migrate/kubernetes/strimzi.adoc#migrate-kafka[side-by-side codeblocks] let you easily compare code examples.
* Improved listing of changes to `rpk` commands in xref:upgrade:deprecated/index.adoc[deprecated features].
* List of xref:reference:partner-integration.adoc[Redpanda integrations] built and supported by our partners.

== Next steps

* xref:upgrade:rolling-upgrade.adoc[]