= What's New in 23.3 Beta
:description: Summary of new features and updates in the release.

This topic includes new content added in version 23.3 Beta. 

== OIDC authentication

xref:manage:security/console/generic-oidc.adoc[OIDC authentication] provides single sign-on capabilities in Redpanda and Redpanda Console to use external accounts instead of SASL users. With this, you can manage user and client/application credentials in the identity provider, such as Okta, Azure AD, and on-premise Active Directory Federation Service (AD FS).

== Audit logging 

Redpanda's xref:manage:audit-logging.adoc[audit logging] supports fine-grained auditing of Kafka API and ACL operations. You can persistently store auditing events to a topic in an append-only fashion, which guarantees retention for the requested time period, even against Redpanda administrators. Auditing is compatible with the Open Cybersecurity Schema Framework (OCSF) to provide a predictable and extensible solution with industry standard tools, such as Splunk, Sumo Logic, and AWS.

== Data transforms

Redpanda now provides the framework to build and deploy inline transformations (xref:develop:data-transforms/index.adoc[data transforms]) on data written to Redpanda topics, delivering processed and validated data to consumers in the format they expect. For example, you may have consumers that require you to redact credit card numbers or convert JSON to Avro. Data transforms use WebAssembly (Wasm) engines inside a broker, which eliminates the need to manage a separate stream processing environment or use 3rd-party tools.

== New commands and properties

New commands and properties in this release include the following:

- xref:reference:rpk/rpk-registry/rpk-registry.adoc[`rpk registry`]: This includes commands to interact with the Schema Registry.
- xref:reference:rpk/rpk-transform/rpk-transform.adoc[`rpk transform`]: This includes commands to develop, deploy, and manage Redpanda data transforms.



