= What's New
:description: Summary of new features and updates in the release.
:page-aliases: get-started:whats-new-233.adoc, get-started:whats-new-241.adoc

This topic includes new content added in version 24.1 beta. For a complete list of all product updates, see the https://github.com/redpanda-data/redpanda/releases/[Redpanda release notes^]. See also: 

* xref:deploy:deployment-option/cloud/whats-new-cloud.adoc[] 
* xref:deploy:deployment-option/cloud/cloud-overview.adoc#redpanda-cloud-vs-self-hosted-feature-compatibility[Redpanda Cloud vs self-hosted feature compatibility]

== FIPS compliance

Redpanda now provides FIPS-compliant cipher enforcement for brokers using OpenSSL. Both Redpanda and `rpk` leverage validated OpenSSL libraries for all security-related cryptography operations. Install the `redpanda-fips` package to ADD XREF TO manage:security/fips-compliance.adoc[run Redpanda in FIPS compliance mode]

== JSON support for Schema Registry

Redpanda's xref:manage:schema-reg/schema-reg-overview.adoc[Schema Registry] now supports JSON serialization format, in addition to Avro and Protobuf. A serialization format defines how data is converted into bytes that are transmitted and stored. 

== Next steps

* xref:upgrade:rolling-upgrade.adoc[]