= What's New
:description: Summary of new features and updates in the release.
:page-aliases: get-started:whats-new-233.adoc, get-started:whats-new-241.adoc

This topic includes new content added in version {page-component-version}. For a complete list of all product updates, see the https://github.com/redpanda-data/redpanda/releases/[Redpanda release notes^]. See also:

* xref:redpanda-cloud:get-started:whats-new-cloud.adoc[] 
* xref:redpanda-cloud:get-started:cloud-overview.adoc#redpanda-cloud-vs-self-managed-feature-compatibility[Redpanda Cloud vs Self-Managed feature compatibility]

== Mountable topics

For topics with Tiered Storage enabled, you can unmount a topic to safely detach it from a cluster and keep the topic data in the cluster's object storage bucket or container. You can mount the detached topic to either the same origin cluster, or a different one. This allows you to hibernate a topic and free up system resources taken up by the topic, or migrate a topic to a different cluster. See xref:manage:mountable-topics.adoc[Mountable topics] for details.

== Leader pinning

For a Redpanda cluster deployed across multiple availability zones (AZs), xref:develop:produce-data/leader-pinning.adoc[leader pinning] ensures that a topic's partition leaders are geographically closer to clients. Leader pinning can lower networking costs and help guarantee lower latency by routing produce and consume requests to brokers located in certain AZs.

== Debug bundles in Redpanda Console

You can now xref:troubleshoot:debug-bundle/index.adoc[generate a debug bundle] in Redpanda Console for comprehensive diagnostics. A debug bundle can help debug and diagnose issues with a Redpanda cluster, a broker, or the machines on which the brokers are running. You can use this file to debug issues yourself, or you can send it to the Redpanda support team to help resolve your issue.

== Declarative user and ACL management in Kubernetes

Redpanda now supports declarative management of users and access control lists (ACLs) using the new User resource with the Redpanda Operator. This feature allows you to:

- Create and manage Redpanda users and their authentication settings.
- Define and manage ACLs to control access to Redpanda resources.
- Automatically reconcile changes to users and ACLs using the Redpanda Operator.

To learn more, see the xref:manage:kubernetes/security/authentication/k-user-controller.adoc[User resource documentation].

== Licensing updates

This release includes several updates to xref:get-started:licensing/overview.adoc[Redpanda's licensing system] to both improve transparency and make it easier to manage licenses across Redpanda clusters and Redpanda Console.

- *Upgrade restriction for enterprise features*: You cannot upgrade your cluster to Redpanda 24.3 or later if any enterprise feature of Redpanda (excluding Console) is in use without a valid license. The upgrade is aborted immediately and cleanly before any broker is upgraded, minimizing disruption.

- *License reminder in `rpk`*: Every `rpk` command now includes a reminder if the cluster is using licensed features without a valid license.

- *License warnings in Redpanda Console*: If you are using Redpanda Console and one or more enterprise features are active in the connected Redpanda cluster without a valid license, a banner specifies which enterprise features are in use without a license.

- *Unified license management in Redpanda Console*: You can now upload and apply a single license key for both Redpanda Console and the connected Redpanda cluster through the Redpanda Console UI. Any existing license key is overridden by the new one.

== New commands 

The following `rpk` commands are new in this version:

* xref:reference:rpk/rpk-cluster/rpk-cluster-storage-cancel-mount.adoc[`rpk cluster storage cancel mount`]
* xref:reference:rpk/rpk-cluster/rpk-cluster-storage-list-mount.adoc[`rpk cluster storage list mount`]
* xref:reference:rpk/rpk-cluster/rpk-cluster-storage-list-mountable.adoc[`rpk cluster storage list-mountable`]
* xref:reference:rpk/rpk-cluster/rpk-cluster-storage-mount.adoc[`rpk cluster storage mount`]
* xref:reference:rpk/rpk-cluster/rpk-cluster-storage-status-mount.adoc[`rpk cluster storage status mount`]
* xref:reference:rpk/rpk-cluster/rpk-cluster-storage-unmount.adoc[`rpk cluster storage unmount`]

== New properties

The following cluster properties are new in this version:

* xref:reference:properties/cluster-properties.adoc#default_leaders_preference[`default_leaders_preference`]
* xref:reference:properties/cluster-properties.adoc#rpk_path[`rpk_path`]