= What's New
:description: Summary of new features and updates in the release.
:page-aliases: get-started:whats-new-233.adoc, get-started:whats-new-241.adoc

This topic includes new content added in version 24.2 beta. For a complete list of all product updates, see the https://github.com/redpanda-data/redpanda/releases/[Redpanda release notes^]. See also: 

* xref:deploy:deployment-option/cloud/whats-new-cloud.adoc[] 
* xref:deploy:deployment-option/cloud/cloud-overview.adoc#redpanda-cloud-vs-self-hosted-feature-compatibility[Redpanda Cloud vs self-hosted feature compatibility]

== FIPS compliance

Redpanda now provides FIPS-compliant cipher enforcement for brokers using OpenSSL. Both Redpanda and `rpk` leverage validated OpenSSL libraries for all security-related cryptography operations. Install the `redpanda-fips` package to xref:manage:security/fips-compliance.adoc[run Redpanda in FIPS compliance mode].

== Schema Registry support for JSON

Redpanda's xref:manage:schema-reg/schema-reg-overview.adoc[Schema Registry] now supports JSON serialization format, in addition to Avro and Protobuf. A serialization format defines how data is converted into bytes that are transmitted and stored.

== Data transforms

You can now deploy transform functions that xref:develop:data-transforms/deploy.adoc#reprocess[reprocess existing records] in an input topic. Processing existing records can be useful if, for example, the output topic was accidentally deleted, and you need to recreate the lost data by reprocessing those existing records.

The docs now also include an xref:develop:data-transforms/index.adoc[expanded guide] designed to help you master the creation, deployment, and management of data transforms in Redpanda.

== Next steps

* xref:install-beta.adoc[]