= What's New
:description: Summary of new features and updates in the release.
:page-aliases: get-started:whats-new-233.adoc, get-started:whats-new-241.adoc

This topic includes new content added in version {page-component-version} Beta. For a complete list of all product updates, see the https://github.com/redpanda-data/redpanda/releases/[Redpanda release notes^]. See also:

* xref:redpanda-cloud:get-started:whats-new-cloud.adoc[]
* xref:redpanda-cloud:get-started:cloud-overview.adoc#redpanda-cloud-vs-self-managed-feature-compatibility[Redpanda Cloud vs Self-Managed feature compatibility]

== Redpanda Console v3.0.0 (beta)

The Redpanda Console v3.0.0 beta release includes the following updates:

=== New features

Unified authentication and authorization system. Redpanda Console now supports user impersonation so you can authenticate to Redpanda using the same credentials you use to authenticate to Redpanda Console. This feature simplifies user management and allows you to use the same credentials for both Redpanda and Redpanda Console.

See xref:console:config/security/authentication.adoc[] for more information.

=== Breaking changes

include::upgrade:partial$console/v3-breaking-changes.adoc[]

See xref:upgrade:migrate/console-v3.adoc[].