= Redpanda Operator
:description: Redpanda Operator reference topics
:linkRoot: ../../

import DeprecationNote from '../../shared/_operator-deprecation-notice.mdx'

<DeprecationNote frontmatter=\{frontMatter}/>

This section includes information about installing, deploying, and securing Redpanda on Kubernetes using the Redpanda Operator (`redpanda-operator` Helm chart). This is supported only for backward compatibility.

* xref:redpanda-operator:operator-install.adoc[Install]
+
Install Redpanda for Kubernetes with kind or minikube or on Cloud.

* xref:redpanda-operator:operator-deploy.adoc[Deploy]
+
Configure the Redpanda Operator for connectivity or connect remotely to Kubernetes. Also learn about custom configuration and additional properties.

* xref:redpanda-operator:operator-security.adoc[Security]
+
Configure Redpanda TLS, SASL, and mTLS on Kubernetes.

* xref:redpanda-operator:crd.adoc[Operator Custom Resource Definition (CRD)]
+
Apply the CRD to configure the Redpanda cluster and APIs.
