= rpk cluster config
:description: rpk cluster config

Interact with cluster configuration properties.

Cluster properties are redpanda settings which apply to all nodes in
the cluster.  These are separate to node properties, which are set with
'rpk redpanda config'.

Use the 'edit' subcommand to interactively modify the cluster configuration, or
'export' and 'import' to write configuration to a file that can be edited and
read back later.

These commands take an optional '--all' flag to include all properties including
low level tunables such as internal buffer sizes, that do not usually need
to be changed during normal operations.  These properties generally require
some expertize to set safely, so if in doubt, avoid using '--all'.

Modified properties are propagated immediately to all nodes.  The 'status'
subcommand can be used to verify that all nodes are up to date, and identify
any settings which were rejected by a node, for example if a node is running a
different redpanda version that does not recognize certain properties.

== Usage

[,bash]
----
rpk cluster config [flags]
  rpk cluster config [command]
----

== Flags

[cols="1m,1a,2a]
|===
|*Value* |*Type* |*Description*

|`--all` |- |Include all properties, including tunables.

|`-h, --help` |- |Help for config.

|`--config` |string |Redpanda or rpk config file; default search paths are ~/.config/rpk/rpk.yaml, $PWD, and /etc/redpanda/`redpanda.yaml`.

|`-X, --config-opt` |stringArray |Override rpk configuration settings; '-X help' for detail or '-X list' for terser detail.

|`--profile` |string |rpk profile to use.

|`-v, --verbose` |- |Enable verbose logging.
|===