= Deploy for Production: Manual
:description: Steps to deploy a Redpanda production cluster.
:page-aliases: deploy-self-hosted:production-deployment.adoc, deployment:custom-deployment.adoc, deployment:production-deployment.adoc
:env-linux: true
:page-categories: Deployment

You can deploy Redpanda for production with a default deployment, which uses recommended deployment tools, or with a custom deployment, which uses unsupported deployment tools.

[NOTE]
====
* See xref:./production-deployment-automation.adoc[] to use Terraform and Ansible to deploy Redpanda.
* See xref:get-started:quick-start.adoc[Redpanda Quickstart] to try out Redpanda in Docker or xref:./dev-deployment.adoc[Deploy for Development].
====

== Prerequisites

Make sure you meet the xref:deploy:deployment-option/self-hosted/manual/production/requirements.adoc[hardware and software requirements].

=== TCP/IP ports

Redpanda uses the following default ports:

|===
| Port | Purpose

| `9092`
| Kafka API

| `8082`
| HTTP Proxy

| `8081`
| Schema Registry

| `9644`
| Admin API and Prometheus

| `33145`
| internal RPC
|===

== Select deployment type

To start deploying Redpanda for production, choose your deployment type:

* <<Default deployment>>: Use recommended deployment tools.
* <<Custom deployment>>: Use unsupported deployment tools.

== Default deployment

This section describes how to set up a production cluster of Redpanda.

include::deploy:partial$linux/install-redpanda.adoc[leveloffset=+2]

include::deploy:partial$linux/install-fips.adoc[leveloffset=+2]

include::deploy:partial$linux/install-console.adoc[leveloffset=+2]

=== Tune the Linux kernel for production

To get the best performance from your hardware, set Redpanda to production mode on each node and run the autotuner tool. The autotuner identifies the hardware configuration of your node and optimizes the Linux kernel to give you the best performance.

By default, Redpanda is installed in development mode, which turns off hardware optimization.

. Make sure that your current Linux user has root privileges. The autotuner requires privileged access to the Linux kernel settings.

. Set Redpanda to run in xref:reference:rpk/rpk-redpanda/rpk-redpanda-mode.adoc#production-mode[production mode]:
+
[,bash]
----
sudo rpk redpanda mode production
----

. Tune the Linux kernel:
+
[,bash]
----
sudo rpk redpanda tune all
----

Changes to the Linux kernel are not persisted. If a node restarts, make sure to run the autotuner again.

To automatically tune the Linux kernel on a Redpanda broker after the node restarts, enable the `redpanda-tuner` service, which runs `rpk redpanda tune all`:

* For RHEL, after installing the rpm package, run `systemctl` to both start and enable the `redpanda-tuner` service:
+
[,bash]
----
sudo systemctl start redpanda-tuner
sudo systemctl enable redpanda-tuner
----

* For Ubuntu, after installing the apt package, run `systemctl` to start the `redpanda-tuner` service (which is already enabled):
+
[,bash]
----
sudo systemctl start redpanda-tuner
----

For more details, see the xref:reference:rpk/rpk-redpanda/rpk-redpanda-tune.adoc[autotuner reference].

=== Generate optimal I/O configuration settings

After tuning the Linux kernel, you can optimize Redpanda for the I/O capabilities of your worker node by using `rpk` to run benchmarks that capture its read/write IOPS and bandwidth capabilities. After running the benchmarks `rpk` saves the results to an I/O configuration file (`io-config.yaml`) that Redpanda reads upon startup to optimize itself for the node.

NOTE: Unlike the autotuner, it isn't necessary to run `rpk iotune` each time Redpanda is started, as its I/O output configuration file can be reused for each node that runs on the same type of hardware.

Run xref:reference:rpk/rpk-iotune.adoc[rpk iotune]:

[,bash]
----
sudo rpk iotune # takes 10mins
----

For reference, a local NVMe SSD should yield around 1 GB/s sustained writes.
`rpk iotune` captures SSD wear and tear and gives accurate measurements
of what your hardware is capable of delivering. Run this before benchmarking.

If you're on AWS, GCP, or Azure, creating a new instance and upgrading to
an image with a recent Linux kernel version is often the easiest way to
work around bad devices.

include::deploy:partial$linux/bootstrap.adoc[leveloffset=+2]

include::deploy:partial$linux/start-redpanda.adoc[leveloffset=+2]

include::deploy:partial$linux/start-console.adoc[leveloffset=+2]

include::deploy:partial$linux/verify-redpanda.adoc[leveloffset=+2]

=== Enable monitoring

xref:manage:monitoring.adoc[]. Observability is essential in production environments.

== Custom deployment

This section provides information for creating your own automation for deploying Redpanda clusters without using any of the tools that Redpanda supports for setting up a cluster, such as Ansible Playbook, Helm Chart, or Kubernetes Operator.

TIP: Redpanda strongly recommends using one of these supported deployment tools. See xref:./production-deployment-automation.adoc[Automate Deploying for Production].

=== Configure a bootstrap file

Redpanda cluster configuration is written with the Admin API and
the `rpk cluster config` CLIs.

In the special case where you want to provide configuration to Redpanda
before it starts for the first time, you can write a `.bootstrap.yaml` file
in the same directory as `redpanda.yaml`.

This file is only read on the first startup of the cluster. Any subsequent
changes to `.bootstrap.yaml` are ignored, so changes to
cluster configuration must be done with the Admin API.

The content format is a YAML dictionary of cluster configuration properties. For example, to initialize a cluster with Admin API authentication enabled
and a single superuser, the `.bootstrap.yaml` file would contain the following:

[,yaml]
----
admin_api_require_auth: true
superusers:
- alice
----

With this configuration, the Admin API is not accessible until you bootstrap a user account.

=== Bootstrap a user account

When using username/password authentication, it's helpful to be able to create one user before the cluster starts for the first time.

Do this by setting the `RP_BOOTSTRAP_USER` environment variable
when starting Redpanda for the first time. The value has the format
`<username>:<password>`. For example, you could set `RP_BOOTSTRAP_USER` to `alice:letmein`.

NOTE: `RP_BOOTSTRAP_USER` only creates a user account. You must still
set up authentication using cluster configuration.

=== Secure the Admin API

The Admin API is used to create SASL user accounts and ACLs, so it's
important to think about how you secure it when creating a cluster.

* No authentication, but listening only on 127.0.0.1: This may be appropriate
if your Redpanda processes are running in an environment where only
administrators can access the host.
* mTLS authentication: You can generate client and server x509 certificates
before starting Redpanda for the first time, refer to them in
`redpanda.yaml`, and use the client certificate when accessing the Admin API.
* Username/password authentication: Use the combination of `admin_api_require_auth`,
`superusers`, and `RP_BOOTSTRAP_USER` to access the Admin API username/password
authentication. You probably still want to enable TLS on the Admin API
endpoint to protect credentials in flight.

=== Configure the seed servers

Seed servers help new brokers join a cluster by directing requests from newly-started brokers to an existing cluster. The xref:reference:node-properties.adoc#seed_servers[seed_servers] broker configuration property controls how Redpanda finds its peers when initially forming a cluster. It is dependent on the xref:reference:node-properties.adoc#empty_seed_starts_cluster[empty_seed_starts_cluster] broker configuration property.

Starting with Redpanda version 22.3, you should explicitly set `empty_seed_starts_cluster` to `false` on every broker, and every broker in the cluster should have the same value set for `seed_servers`. With this set of configurations, Redpanda clusters form with these guidelines:

* When a broker starts and it is a seed server (its address is in the `seed_servers` list), it waits for all other seed servers to start up, and it forms a cluster with all seed servers as members.
* When a broker starts and it is not a seed server, it sends requests to the seed servers to join the cluster.

It is essential that all seed servers have identical values for the `seed_servers` list. Redpanda strongly recommends at least three seed servers when forming a cluster. Each seed server decreases the likelihood of unintentionally forming a split brain cluster. To ensure brokers can always discover the cluster, at least one seed server should be available at all times.

By default, for backward compatibility, `empty_seed_starts_cluster` is set to `true`, and Redpanda clusters form with the guidelines used prior to version 22.3:

* When a broker starts with an empty `seed_servers` list, it creates a single broker cluster with itself as the only member.
* When a broker starts with a non-empty `seed_servers` list, it sends requests to the brokers in that list to join the cluster.

You should never have more than one broker with an empty `seed_servers` list, which would result in the creation of multiple clusters.

IMPORTANT: Redpanda expects its storage to be persistent, and it's an error
to erase a broker's drive and restart it. However, in some environments (like when migrating to a different Node pool on Kubernetes), truly persistent storage is unavailable,
and brokers may find their data volumes erased. For such environments, Redpanda recommends setting `empty_seed_starts_cluster` to false and designating a set of seed servers such that they couldn't lose their storage simultaneously.

=== Configure broker IDs

Redpanda automatically generates unique IDs for each new broker. This means that you don't need to include IDs in configuration files or worry about policies on `node_id` re-use.

If you choose to assign broker IDs, make sure to use a fresh `node_id` each time you add a broker to the cluster.

CAUTION: Never reuse broker IDs, even for brokers that have been decommissioned and restarted empty. Doing so can result in an inconsistent state.

include::deploy:partial$self-test.adoc[leveloffset=+1]

=== Upgrade considerations

Deployment automation should place each broker into maintenance mode and wait for it to drain leadership before restarting it with a newer version of Redpanda. For more information, see xref:manage:cluster-maintenance/rolling-upgrade.adoc[Upgrade].

If upgrading multiple xref:manage:kubernetes/rolling-upgrade.adoc#find-a-new-version[feature release versions of Redpanda] in succession, make sure to verify that each version upgrades to completion before proceeding to the next version. You can verify by reading the `/v1/features` Admin API endpoint and checking that `cluster_version` has increased.

Starting with Redpanda version 23.1, the `/v1/features` endpoint also includes a `node_latest_version` attribute, and installers can verify that the cluster has activated any new functionality from a previous upgrade by checking for `cluster_version` == `node_latest_version`.

== Next steps

* If clients connect from a different subnet, see xref:manage:security/listener-configuration.adoc[Configure Listeners].
* Observability is essential in production environments. See xref:manage:monitoring.adoc[].

include::shared:partial$suggested-reading.adoc[]

* xref:manage:cluster-maintenance/cluster-property-configuration.adoc[Configure Cluster Properties]
* xref:reference:console/config.adoc[Redpanda Console Configuration]
* xref:manage:schema-registry.adoc[Schema Registry]