= Deploy Redpanda and Redpanda Console

In this step, you deploy Redpanda with SASL authentication and self-signed TLS certificates. Redpanda Console is included as a subchart in the Redpanda Helm chart.

[tabs]
======
Operator::
+
--

. Make sure that you have permission to install custom resource definitions (CRDs):
+
```bash
kubectl auth can-i create CustomResourceDefinition --all-namespaces
```
+
You should see `yes` in the output.
+
You need these cluster-level permissions to install glossterm:cert-manager[] and Redpanda Operator CRDs in the next steps.

. Install https://cert-manager.io/docs/installation/helm/[cert-manager^] using Helm:
+
```bash
helm repo add jetstack https://charts.jetstack.io
helm repo update
helm install cert-manager jetstack/cert-manager \
  --set crds.enabled=true \
  --namespace cert-manager  \
  --create-namespace
```
+
The Redpanda Helm chart uses cert-manager to enable TLS and manage TLS certificates by default.

. Install the Redpanda Operator custom resource definitions (CRDs):
+
include::deploy:partial$kubernetes/install-crds.adoc[]

. Deploy the Redpanda Operator:
+
[,bash,subs="attributes+"]
----
helm repo add redpanda https://charts.redpanda.com
helm repo update
helm upgrade --install redpanda-controller redpanda/operator \
  --namespace <namespace> \
  --set image.tag={latest-operator-version} \
  --create-namespace \
  --timeout 1h
----

. Ensure that the Deployment is successfully rolled out:
+
```bash
kubectl --namespace <namespace> rollout status --watch deployment/redpanda-controller-operator
```
+
[.no-copy]
----
deployment "redpanda-controller-operator" successfully rolled out
----

. Install a xref:reference:k-crd.adoc[Redpanda custom resource] in the same namespace as the Redpanda Operator:
+
.`redpanda-cluster.yaml`
[,yaml,subs="attributes+",lines=10+15+20]
----
apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
  name: redpanda
spec:
  chartRef:
    chartVersion: {latest-redpanda-helm-chart-version}
  clusterSpec:
    external:
      domain: customredpandadomain.local
    auth:
      sasl:
        enabled: true
        users:
          - name: superuser
            password: secretpassword
    storage:
      persistentVolume:
        enabled: true
        storageClass: csi-driver-lvm-striped-xfs
----
+
```bash
kubectl apply -f redpanda-cluster.yaml --namespace <namespace>
```
+
- `external.domain`: The custom domain that each broker will advertise to clients externally. This domain is added to the internal and external TLS certificates so that you can connect to the cluster using this domain.
- `auth.sasl.name`: Creates a superuser called `superuser` that can grant permissions to new users in your cluster using access control lists (ACLs).
- `storage.persistentVolume.storageClass`: Points each PVC associated with the Redpanda brokers to the `csi-driver-lvm-striped-xfs` StorageClass. This StorageClass allows the LVM CSI driver to provision the appropriate local PersistentVolumes backed by NVMe disks for each Redpanda broker.

. Wait for the Redpanda Operator to deploy Redpanda using the Helm chart:
+
```bash
kubectl get redpanda --namespace <namespace> --watch
```
+
[.no-copy]
----
NAME       READY   STATUS
redpanda   True    Redpanda reconciliation succeeded
----
+
This step may take a few minutes. You can watch for new Pods to make sure that the deployment is progressing:
+
```bash
kubectl get pod --namespace <namespace>
```
+
If it's taking too long, see <<Troubleshoot>>.

--

Helm::
+
--

. Install cert-manager using Helm:
+
```bash
helm repo add jetstack https://charts.jetstack.io
helm repo update
helm install cert-manager jetstack/cert-manager \
  --set crds.enabled=true \
  --namespace cert-manager \
  --create-namespace
```
+
TLS is enabled by default. The Redpanda Helm chart uses cert-manager to manage TLS certificates by default.

. Install Redpanda with SASL enabled:
+
[source,bash,subs="attributes+",lines=3+5-9]
----
helm repo add redpanda https://charts.redpanda.com
helm repo update
helm install redpanda redpanda/redpanda \
  --version {latest-redpanda-helm-chart-version} \
  --namespace <namespace> --create-namespace \
  --set auth.sasl.enabled=true \
  --set "auth.sasl.users[0].name=superuser" \
  --set "auth.sasl.users[0].password=secretpassword" \
  --set external.domain=customredpandadomain.local \
  --set "storage.persistentVolume.storageClass=csi-driver-lvm-striped-xfs" \
  --wait \
  --timeout 1h
----
+
- `external.domain`: The custom domain that each broker advertises to clients externally. This domain is added to the internal and external TLS certificates so that you can connect to the cluster using this domain.
- `auth.sasl.name`: Creates a superuser called `superuser` that can grant permissions to new users in your cluster using access control lists (ACLs).
- `storage.persistentVolume.storageClass`: Points each PVC associated with the Redpanda brokers to the `csi-driver-lvm-striped-xfs` StorageClass. This StorageClass allows the LVM CSI driver to provision the appropriate local PersistentVolumes backed by NVMe disks for each Redpanda broker.


The installation displays some tips for getting started.

If the installation is taking a long time, see <<Troubleshoot>>.

--
======

