= Configure external access to Redpanda

If you want to connect to the Redpanda cluster with external clients, Redpanda brokers must advertise an externally accessible address that external clients can connect to. External clients are common in Internet of Things (IoT) environments, or if you use external services that do not implement VPC peering in your network.

When you created the cluster, you set the `external.domain` configuration to `customredpandadomain.local`, which means that your Redpanda brokers are advertising the following addresses:

* `redpanda-0.customredpandadomain.local`
* `redpanda-1.customredpandadomain.local`
* `redpanda-2.customredpandadomain.local`

To access your Redpanda brokers externally, you can map your worker nodes' IP addresses to these domains.

[CAUTION]
====
IP addresses can change. If the IP addresses of your worker nodes change, you must update your `/etc/hosts` file with the new mappings.

In a production environment, it's best practice to use ExternalDNS to manage DNS records for your brokers. See xref:deploy:deployment-option/self-hosted/kubernetes/kubernetes-cluster-requirements.adoc#use-externaldns-for-external-access[Use ExternalDNS for external access].
====
