= Start streaming

In this step, you authenticate to Redpanda with the `redpanda-twitch-account` user to create a topic called `twitch-chat`. This topic is the only one that the `redpanda-twitch-account` user has permission to access. Then, you produce messages to the topic, and consume messages from it.

. Create an alias to simplify the `rpk` commands:
+
[,bash]
----
alias internal-rpk="kubectl --namespace <namespace> exec -i -t redpanda-0 -c redpanda -- rpk -X user=redpanda-twitch-account -X pass=changethispassword -X sasl.mechanism=SCRAM-SHA-256"
----

. Create a topic called `twitch-chat`:
+
[tabs]
======
Operator::
+
--

.. Create a Secret in which to store your user's password:
+
[source,bash]
----
kubectl create secret generic redpanda-secret --from-literal=password='changethispassword' --namespace <namespace>
----

.. Create a xref:manage:kubernetes/k-manage-topics.adoc[Topic resource]:
+
.`topic.yaml`
[,yaml]
----
apiVersion: cluster.redpanda.com/v1alpha2
kind: Topic
metadata:
  name: twitch-chat
spec:
  kafkaApiSpec:
    brokers:
      - "redpanda-0.redpanda.<namespace>.svc.cluster.local:9093"
      - "redpanda-1.redpanda.<namespace>.svc.cluster.local:9093"
      - "redpanda-2.redpanda.<namespace>.svc.cluster.local:9093"
    tls:
      caCertSecretRef:
        name: "redpanda-default-cert"
        key: "ca.crt"
    sasl:
      username: redpanda-twitch-account
      mechanism: SCRAM-SHA-256
      passwordSecretRef:
        name: redpanda-secret
        key: password
----

.. Apply the Topic resource in the same namespace as your Redpanda cluster:
+
[,bash]
----
kubectl apply -f topic.yaml --namespace <namespace>
----

.. Check the logs of the Redpanda Operator to confirm that the topic was created:
+
[,bash]
----
kubectl logs -l app.kubernetes.io/name=operator -c manager --namespace <namespace>
----
+
You should see that the Redpanda Operator reconciled the Topic resource. For example:
+
.Example output
[%collapsible]
====
[,json,.no-copy,lines=5+22]
----
{
  "level":"info",
  "ts":"2023-09-25T16:20:09.538Z",
  "logger":"TopicReconciler.Reconcile",
  "msg":"Starting reconcile loop",
  "controller":"topic",
  "controllerGroup":"cluster.redpanda.com",
  "controllerKind":"Topic",
  "Topic":
  {
    "name":"twitch-chat",
    "namespace":"<namespace>"
  },
  "namespace":"<namespace>",
  "name":"twitch-chat",
  "reconcileID":"c0cf9abc-a553-48b7-9b6e-2de3cdfb4432"
}
{
  "level":"info",
  "ts":"2023-09-25T16:20:09.581Z",
  "logger":"TopicReconciler.Reconcile",
  "msg":"reconciliation finished in 43.436125ms, next run in 3s",
  "controller":"topic",
  "controllerGroup":"cluster.redpanda.com",
  "controllerKind":"Topic",
  "Topic":
  {
    "name":"twitch-chat",
    "namespace":"<namespace>"
  },
  "namespace":"<namespace>",
  "name":"twitch-chat",
  "reconcileID":"c0cf9abc-a553-48b7-9b6e-2de3cdfb4432",
  "result":
  {
    "Requeue":false,
    "RequeueAfter":3000000000
  }
}
----
====

--
Helm::
+
--

[,bash]
----
internal-rpk topic create twitch-chat
----

Example output:

[.no-copy]
----
TOPIC STATUS twitch-chat OK
----

--
======

. Describe the topic:
+
[,bash]
----
internal-rpk topic describe twitch-chat
----
+
.Expected output:
[%collapsible]
====
[.no-copy]
```
SUMMARY
=======
NAME        twitch-chat
PARTITIONS  1
REPLICAS    1

CONFIGS
=======
KEY                     VALUE                          SOURCE
cleanup.policy          delete                         DYNAMIC_TOPIC_CONFIG
compression.type        producer                       DEFAULT_CONFIG
message.timestamp.type  CreateTime                     DEFAULT_CONFIG
partition_count         1                              DYNAMIC_TOPIC_CONFIG
redpanda.datapolicy     function_name:  script_name:   DEFAULT_CONFIG
redpanda.remote.read    false                          DEFAULT_CONFIG
redpanda.remote.write   false                          DEFAULT_CONFIG
replication_factor      1                              DYNAMIC_TOPIC_CONFIG
retention.bytes         -1                             DEFAULT_CONFIG
retention.ms            604800000                      DEFAULT_CONFIG
segment.bytes           1073741824                     DEFAULT_CONFIG
```
====

. Produce a message to the topic:
+
[,bash]
----
internal-rpk topic produce twitch-chat
----

. Type a message, then press kbd:[Enter]:
+
[.no-copy]
----
Pandas are fabulous!
----
+
Example output:
+
[.no-copy]
----
Produced to partition 0 at offset 0 with timestamp 1663282629789.
----

. Press kbd:[Ctrl + C] to finish producing messages to the topic.

. Consume one message from the topic:
+
[,bash]
----
internal-rpk topic consume twitch-chat --num 1
----
+
.Expected output:
[%collapsible]
====
[,json,no-copy]
```
{
  "topic": "twitch-chat",
  "value": "Pandas are fabulous!",
  "timestamp": 1663282629789,
  "partition": 0,
  "offset": 0
}
```
====
