= Uninstall Redpanda

When you finish testing Redpanda, you can uninstall it from your Kubernetes cluster. The steps depend on how you installed Redpanda: using the Redpanda Operator or the Redpanda Helm chart.

[tabs]
======
Operator::
+
--
//tag::operator[]
Follow the steps in **exact order** to avoid race conditions between
the Redpanda Operator's reconciliation loop and Kubernetes garbage collection.

. Delete all Redpanda-related custom resources:
+
[,bash,role="no-wrap"]
----
kubectl delete users      --namespace <namespace> --all
kubectl delete topics     --namespace <namespace> --all
kubectl delete schemas    --namespace <namespace> --all
kubectl delete redpanda   --namespace <namespace> --all
----

. Make sure requests for those resources return no results. For example, if you had a Redpanda cluster named `redpanda` in the namespace `<namespace>`, run:
+
[,bash]
----
kubectl get redpanda --namespace <namespace>
----

. Uninstall the Redpanda Operator Helm release:
+
[,bash]
----
helm uninstall redpanda-controller --namespace <namespace>
----

. Remove the CRDs:
+
[,bash]
----
kubectl delete crd \
  redpandas.cluster.redpanda.com \
  users.cluster.redpanda.com \
  topics.cluster.redpanda.com \
  schemas.cluster.redpanda.com
----

. (Optional) Delete any leftover Pods, PVCs, or Secrets in the namespace:
+
[,bash]
----
kubectl delete pod,pvc,secret --all --namespace <namespace>
----
//end::operator[]
--

Helm::
+
--
If you deployed Redpanda with the Redpanda Helm chart, follow these steps to uninstall it:

. Uninstall the Helm release:
+
[,bash]
----
helm uninstall redpanda --namespace <namespace>
----

. (Optional) Delete any leftover Pods, PVCs, or Secrets in the namespace:
+
[,bash]
----
kubectl delete pod,pvc,secret --all --namespace <namespace>
----
--
======
