= TLS for Redpanda in Kubernetes
:description: Use TLS to authenticate Redpanda brokers and encrypt communication between clients and brokers.
:page-context-links: [{"name": "Linux", "to": "manage:security/encryption.adoc" },{"name": "Kubernetes", "to": "manage:kubernetes/security/kubernetes-tls.adoc" } ]
:tags: ["Kubernetes", "Security"]
:page-aliases: manage:kubernetes/security/kubernetes-tls.adoc, security:kubernetes-tls.adoc, security:kubernetes-mtls.adoc, features:tls-kubernetes.adoc, security:tls-kubernetes.adoc
:page-layout: index
:page-categories: Management, Security
:env-kubernetes: true

Redpanda clusters can use Transport Layer Security (TLS) to secure internal and external communications with clients and other brokers.
In the Redpanda Helm chart, TLS is enabled by default for all internal and external listeners, using self-signed certificates managed by glossterm:cert-manager[^].
You can configure the chart to use your own certificates with or without cert-manager.

Redpanda exposes several public metrics to help administrators manage their installed certificates. Configuring alerts on these metrics is a critical tool for managing certificate expiration and avoiding surprise outages. The xref:reference:public-metrics-reference.adoc#tls_metrics[public metrics reference] contains a full list of available TLS metrics. You can refer to the xref:manage:kubernetes/monitoring/k-monitor-redpanda.adoc[monitor Redpanda in Kubernetes] guide for full details on configuring Prometheus to monitor these metrics. This guide also explains how to create a Grafana dashboard for visualizations and alerting.