= TLS for Redpanda in Kubernetes
:description: Use TLS to authenticate Redpanda brokers and encrypt communication between clients and brokers.
:page-context-links: [{"name": "Linux", "to": "manage:security/encryption.adoc" },{"name": "Kubernetes", "to": "manage:kubernetes/security/kubernetes-tls.adoc" } ]
:tags: ["Kubernetes", "Security"]
:page-aliases: manage:kubernetes/security/kubernetes-tls.adoc, security:kubernetes-tls.adoc
:page-layout: index

Redpanda clusters can use Transport Layer Security (TLS) to secure internal and external communications with clients and other brokers.
In the Redpanda Helm chart, TLS is enabled by default for all internal and external listeners, using self-signed certificates managed by glossterm:cert-manager[^].
You can configure the chart to use your own certificates with or without cert-manager.

Redpanda supports both TLS and mTLS:

--
- TLS, previously SSL, provides encryption for client-server communication. A server certificate prevents third parties from accessing data transferred between the client and server.

- mTLS, or mutual TLS, is a protocol that authenticates both the server and the client. In addition to the server certificate required in TLS, mTLS also requires the client to give a certificate. mTLS is useful for environments that require additional security and only have a small number of verified clients.
--