= Use cert-manager to manage TLS certificates
:description: Learn how to enable TLS encryption in your Redpanda cluster and use cert-manager to simplify the process of obtaining, renewing, and using certificates.
:page-aliases: manage:kubernetes/security/tls/use-cert-manager.adoc
:page-categories: Management, Security
:env-kubernetes: true

When using glossterm:cert-manager[] for TLS certificate management, you can use a self-signed certificate or a certificate signed by a trusted certificate authority (CA). This topic provides instructions for each option.

Redpanda supports both TLS and mTLS:

- TLS, previously SSL, provides encryption for client-server communication. A server certificate prevents third parties from accessing data transferred between the client and the server.

- mTLS, or mutual TLS, is a protocol that authenticates both the server and the client. In addition to the server certificate required in TLS, mTLS also requires the client to give a certificate. mTLS is useful for environments that require additional security and only have a small number of verified clients.

== Prerequisites

You must have the following:

* Kubernetes cluster: Ensure you have a running Kubernetes cluster, either locally, such as with minikube or kind, or remotely.

* https://kubernetes.io/docs/tasks/tools/#kubectl[Kubectl^]. Ensure you have the `kubectl` command-line tool installed and configured to communicate with your cluster.

* https://cert-manager.io/docs/installation/helm/[cert-manager^]. Ensure you have cert-manager and its custom resource definitions (CRDs) installed.

* If you want to connect to your Redpanda cluster from outside Kubernetes, make sure to xref:manage:kubernetes/networking/external/index.adoc[enable external access].

== Use a self-signed certificate

By default, the Redpanda Helm chart uses cert-manager to generate four Certificate resources. These resources provide Redpanda brokers with self-signed TLS certificates for internal and external listeners.

[cols="1a,2a"]
|===
|Type|Default Certificates

|Internal
|
- `redpanda-default-cert`: Self-signed certificate for internal communications.
- `redpanda-default-root-certificate`: Root CA for the internal certificate.

|External
|
- `redpanda-external-cert`: Self-signed certificate for external communications.
- `redpanda-external-root-certificate`: Root CA for the external certificate.

|===

A corresponding Secret resource exists for each Certificate resource. The Secret contains the TLS files.

Having separate self-signed certificates for internal and external connections provides security isolation.
If an external certificate or its corresponding private key is compromised,
it doesn't affect the security of internal communications.

The following steps explain how to set up self-signed certificates in your Redpanda cluster:

. Make sure that TLS is enabled:
+
[tabs]
======
Operator::
+
--
.`redpanda-cluster.yaml`
[,yaml]
----
apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
  name: redpanda
spec:
  chartRef: {}
  clusterSpec:
    tls:
      enabled: true
----

```bash
kubectl apply -f redpanda-cluster.yaml --namespace <namespace>
```
--
Helm::
+
--
[tabs]
====
--values::
+
.`self-signed-tls.yaml`
[,yaml]
----
tls:
  enabled: true
----
+
```bash
helm upgrade --install redpanda redpanda/redpanda --namespace <namespace> --create-namespace \
  --values self-signed-tls.yaml --reuse-values
```

--set::
+
```bash
helm upgrade --install redpanda redpanda/redpanda --namespace <namespace> --create-namespace \
  --set tls.enabled=true
```
====
--
======
+
[NOTE]
====
include::manage:partial$kubernetes/tls-update-note.adoc[]
====

. Make sure the Certificates are in a `READY` state.
+
```bash
kubectl get certificate --namespace <namespace>
```
+
[.no-copy]
----
NAME                                 READY
redpanda-default-cert                True
redpanda-default-root-certificate    True
redpanda-external-cert               True
redpanda-external-root-certificate   True
----

== Connect to Redpanda

You can use the `rpk` command-line client to test both internal and external connections to Redpanda.

=== Test internal connections

Your self-signed certificate's glossterm:SAN['A subject alternative name (SAN) indicates all domain names and IP addresses secured by the certificate.'] includes the internal addresses assigned to brokers by Kubernetes through the headless ClusterIP Service.
As such, you can use `rpk` within the Redpanda container to securely communicate with the cluster.

You can validate your internal connection to Redpanda with `rpk` by executing the following command:

```bash
kubectl exec redpanda-0 --namespace <namespace> -c redpanda -- rpk cluster info
```

.Expected output:
[%collapsible]
====
[.no-copy]
```
CLUSTER
=======
redpanda.19ae8532-c8fa-49ed-8b35-82d74813db3a

BROKERS
=======
ID    HOST                                                PORT
0*    redpanda-0.redpanda.<namespace>.svc.cluster.local.  9093
1     redpanda-.redpanda.<namespace>.svc.cluster.local.   9093
2     redpanda-2.redpanda.<namespace>.svc.cluster.local.  9093
```
====

=== Test external connections

To test external connections, you must enable external access using a custom domain. See <<Prerequisites>>.

The SAN list of your self-signed certificate does not contain the IP addresses of your worker nodes,
but when you enable external access using a custom domain, that domain is included in the SAN list.
Then, you can use `rpk` on your local machine to communicate with the cluster externally using the self-signed certificate for encryption.

. Configure xref:manage:kubernetes/networking/external/index.adoc[external access] to your Redpanda cluster using a custom domain.
+
NOTE: Your Redpanda brokers should advertise addresses in your custom domain.

. Install `rpk` on your local machine, not inside the container:
+
[tabs]
=====
Linux::
+
--
[loweralpha]
include::get-started:partial$install-rpk-linux.adoc[tags=latest]

--
macOS::
+
--
[loweralpha]
include::get-started:partial$install-rpk-homebrew.adoc[]

--
=====

. Save the external root CA to your local file system outside Kubernetes:
+
```bash
kubectl --namespace <namespace> get secret redpanda-external-root-certificate -o go-template='{{ index .data "ca.crt" | base64decode }}' > ca.crt
```

. Configure `rpk` to connect to your cluster using the xref:manage:kubernetes/networking/k-connect-to-redpanda.adoc#rpk-profile[pre-configured profile]:
+
[source,bash]
----
rpk profile create --from-profile <(kubectl get configmap --namespace <namespace> redpanda-rpk -o go-template='{{ .data.profile }}') <profile-name>
----

. Test the connection:
+
```bash
rpk cluster info
```

== Use a public CA certificate

Certificates from a public CA are trusted by default. You can configure the Helm chart to use an Issuer resource or a ClusterIssuer resource to generate publicly trusted Certificates for external connections. These custom resources are managed by cert-manager.

The Issuer or ClusterIssuer specifies the CA that will be used when generating certificates. If you select an ACME server such as Let's Encrypt as the CA, cert-manager automatically handles the required HTTP01 or DNS01 ACME challenges to issue certificates.

. Create an Issuer in the same namespace as your Redpanda cluster, or create a ClusterIssuer in any namespace. For details, see the https://cert-manager.io/docs/configuration/[cert-manager documentation^].

. Configure the Helm chart with your Issuer or ClusterIssuer.
+
Replace the following placeholders:
+
- `<issuer-name>`: The name of your Issuer or ClusterIssuer resource.
- `<issuer>`: `Issuer` or `ClusterIssuer`.
- `<custom-domain>`: Your domain.
+
[tabs]
======
Operator::
+
--
.`redpanda-cluster.yaml`
[,yaml]
----
apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
  name: redpanda
spec:
  chartRef: {}
  clusterSpec:
    tls:
      enabled: true
      certs:
        external:
          issuerRef:
            name: <issuer-name>
            kind: <issuer>
          caEnabled: false
    external:
      domain: <custom-domain>
----

```bash
kubectl apply -f redpanda-cluster.yaml --namespace <namespace>
```

--
Helm::
+
--
[tabs]
====
--values::
+
.`external-tls.yaml`
[,yaml]
----
tls:
  enabled: true
  certs:
    external:
      issuerRef:
        name: <issuer-name>
        kind: <issuer>
      caEnabled: false
external:
  domain: <custom-domain>
----
+
```bash
helm upgrade --install redpanda redpanda/redpanda --namespace <namespace> --create-namespace \
  --values external-tls.yaml
```

--set::
+
```bash
helm upgrade --install redpanda redpanda/redpanda --namespace <namespace> --create-namespace \
  --set tls.enabled=true \
  --set tls.certs.external.issuerRef.name=<issuer-name> \
  --set tls.certs.external.issuerRef.kind=<issuer> \
  --set tls.certs.external.caEnabled=false \
  --set external.domain=<custom-domain>
```
====
--
======
+
[NOTE]
====
include::manage:partial$kubernetes/tls-update-note.adoc[]
====

. Make sure the Certificates are in a `READY` state.
+
```bash
kubectl get certificate --namespace <namespace>
```

By default, this certificate is used to encrypt traffic between clients and all external listeners. You can select specific certificates for each external listener. See xref:manage:kubernetes/networking/k-configure-listeners.adoc#tls[Configure Listeners in Kubernetes].

== Connect to Redpanda

You can use the `rpk` command-line client to test both internal and external connections to Redpanda.

=== Test internal connections

Validate your internal connection to Redpanda with `rpk` by executing the following command.

```bash
kubectl exec redpanda-0 --namespace <namespace> -c redpanda -- rpk cluster info
```

You should see the Kafka API endpoints for the internal listener. For example:

[.no-copy]
----
CLUSTER
=======
redpanda.271dac90-2dc8-48e4-9dc6-652f63684d73

BROKERS
=======
ID    HOST                                             PORT
0*    redpanda-0.redpanda.redpanda.svc.cluster.local.  9093
1     redpanda-1.redpanda.redpanda.svc.cluster.local.  9093
2     redpanda-2.redpanda.redpanda.svc.cluster.local.  9093
----

Kubernetes assigns the `*.redpanda.redpanda.svc.cluster.local.` DNS names to the brokers through the headless ClusterIP Service. These are internal Kubernetes addresses. Port 9093 is the default port of the internal listener for the Kafka API.

=== Test external connections

To test external connections, external access must be enabled on your cluster and your brokers must advertise an address that's resolvable externally by your clients.

To test external connections:

. Install `rpk` on your local machine, not inside the container:
+
[tabs]
=====
Linux::
+
--
[loweralpha]
include::get-started:partial$install-rpk-linux.adoc[tags=latest]

--
macOS::
+
--
[loweralpha]
include::get-started:partial$install-rpk-homebrew.adoc[]

--
=====

. If your TLS certificates were issued by a private CA, save the root CA to your local file system outside Kubernetes:
+
```bash
kubectl --namespace <namespace> get secret <secret-name> -o go-template='{{ index .data "ca.crt" | base64decode }}' > ca.crt
```

. Configure `rpk` to connect to your cluster using the xref:manage:kubernetes/networking/k-connect-to-redpanda.adoc#rpk-profile[pre-configured profile]:
+
[source,bash]
----
rpk profile create --from-profile <(kubectl get configmap --namespace <namespace> redpanda-rpk -o go-template='{{ .data.profile }}') <profile-name>
----

. Test the connection:
+
```bash
rpk cluster info
```

You should see the Kafka API endpoints for the external listener. For example:

[.no-copy]
----
CLUSTER
=======
redpanda.271dac90-2dc8-48e4-9dc6-652f63684d73

BROKERS
=======
ID    HOST                                   PORT
0*    redpanda-0.customredpandadomain.local  31092
1     redpanda-1.customredpandadomain.local  31092
2     redpanda-2.customredpandadomain.local  31092
----

The Helm chart configures brokers with these addresses using the values of the `external.domain` and/or `external.addresses` settings in the Helm values. These are external addresses that external clients use to connect. Port 31092 is the default node port of the external listener for the Kafka API. This node port is assigned to the Kubernetes Services.

If your brokers external addresses are not resolvable, you can test external connections by sending API requests to the container port that's assigned to the external listener. For example:

[source,bash]
----
kubectl exec redpanda-0 -n redpanda -c redpanda -- rpk cluster info -X brokers=redpanda-0.redpanda.redpanda.svc.cluster.local:9094 -X tls.ca=/etc/tls/certs/external/ca.crt
----

Port 9094 is the default container port for the external Kafka API.

For more details on connecting to Redpanda, see xref:manage:kubernetes/networking/k-connect-to-redpanda.adoc[].

include::manage:partial$min-tls-version.adoc[]

include::manage:partial$kubernetes/mtls.adoc[]

include::manage:partial$kubernetes/disable-tls.adoc[leveloffset=+1]

== Troubleshoot

Here are some common troubleshooting scenarios and their solutions. For more troubleshooting steps, see xref:manage:kubernetes/troubleshooting/k-troubleshoot.adoc[Troubleshoot Redpanda in Kubernetes].

include::troubleshoot:partial$errors-and-solutions.adoc[tags=tls;networking]

== Next steps

- xref:manage:kubernetes/security/authentication/k-authentication.adoc[]
- xref:manage:kubernetes/networking/k-configure-listeners.adoc[]
- xref:manage:kubernetes/networking/k-connect-to-redpanda.adoc[]

include::shared:partial$suggested-reading.adoc[]

* https://killercoda.com/redpanda/scenario/redpanda-k8s-secure[Securing Redpanda in Kubernetes (Day 2 Ops)^]
* xref:reference:k-redpanda-helm-spec.adoc#external[Redpanda Helm Specification]
* xref:reference:k-crd.adoc[Redpanda CRD Reference]
