= Redpanda Documentation
:url-playbook: https://github.com/redpanda-data/docs-site

This repository hosts the documentation content for Redpanda Platform.

== Versioning

Versioned content is stored in branches that track the version of Redpanda Platform. Production branches use the *v/x.y* naming pattern. For example, branch `v/22.3` hosts the content for version 22.3.x of Redpanda Platform. The `main` branch always contains docs for the latest release.

The {url-playbook}[docs site playbook] instructs Antora to automatically aggregate content in the `main` branch of this repo and any branch names that start with *v/*.

The version of the content is defined in the link:./antora.yml[`antora.yml`] file.

== Repository Structure

The documentation content is stored in the `modules/` directory, where each module represents a top-level label in the documentation nav tree.

Each module has a `pages/` directory that stores the documentation pages in Asciidoc format. Some modules also include a `partials/` directory that contains single-sourced documentation that can be shared and referenced by any documentation pages across any module.

The `shared` module stores the images, attachments, and partials that do not belong to a single module and can be referenced by any documentation pages across any module.

....
modules/shared
├── attachments
├── images
└── partials
....

== Contributing

The Redpanda docs are open source, and we welcome your contributions! To contribute to the Redpanda docs, you have the following options:

|===
|Option|Description

|<<Open an issue>>
|Suggest a change by opening an issue on GitHub.

|<<Contribute content>>
|Make changes directly to the documentation and submit them through a pull request.

|===

=== Open an issue

The Redpanda docs team uses GitHub issues to track, plan, and prioritize tasks. To suggest changes, you can create an issue, which the team will then evaluate:

. Verify whether a similar issue already exists in that repository to avoid duplication.
. Go to **Issues** > **New Issue** to create a new issue.

You have the option to assign the issue to yourself or leave the assignee field blank. The Redpanda docs team triages all new issues and will allocate a writer if one isn't already assigned.

=== Contribute content

You have two options to contribute to the documentation:

. Directly edit a page on GitHub by selecting **Make a contribution** > **Edit on GitHub** located at the bottom of a documentation page.
. Clone the docs repository to make changes locally on your machine. For a guide, see {url-playbook}/blob/main/meta-docs/CONTRIBUTING.adoc[Submit your first contribution].

If you're looking for an open issue to fix, check the open docs issues. If you find an issue you'd like to work on:

- If the issue is already assigned to someone else, please consider another one.
- If the issue is unassigned, add a comment expressing your interest in working on it.

== Local development

If you want to run the website locally, install the packages:

```bash
npm install
```

Then, build the docs and start a local web server:

```bash
npm run start
```

This command opens a browser window. Most changes are reflected live without having to restart the server.

=== Build the site

To build the files, run:

```bash
npm run build
```

This command generates static content in the `docs` directory and can be served using any hosting service.