= Remote Read Replicas
:description: A Remote Read Replica topic is a read-only topic that mirrors a topic on a different cluster.

NOTE: This feature requires an xref:introduction:licenses.adoc[Enterprise license]. To upgrade, contact https://redpanda.com/try-redpanda[Redpanda sales].

A Remote Read Replica topic is a read-only topic that mirrors a topic on a different cluster.

When a topic has cloud storage enabled, you can create a separate remote cluster just for consumers of this topic, and populate its topics from cloud storage. A read-only topic on a remote cluster can serve any consumer, without increasing the load on the origin cluster.

You can create Remote Read Replica topics in a Redpanda cluster that directly accesses data stored in cloud object storage. Because these read-only topics access data directly from object storage instead of the topics' origin cluster, there's no impact to the performance of the cluster. Furthermore, topic data can be consumed within a region of your choice, regardless of the region where it was produced. If you plan to create a Remote Read Replica topic in another region, consider using a https://aws.amazon.com/s3/features/multi-region-access-points/[multi-region bucket] to simplify deployment and optimize performance. Sample use cases for Remote Read Replicas include data analytics, offline model training, and development clusters.

== Creating a topic with archival storage or Tiered Storage

Before you can create a Remote Read Replica, you must create a topic on the origin cluster, and set up an S3 bucket for the topic's cloud storage. Remote Read Replicas work with both archival storage and xref:data-management:tiered-storage.adoc[Tiered Storage].

. Create an S3 bucket to store the original data.
. Create the original topic by running `rpk topic create <topic_name>`, and specifying the number of partitions and the number of replicas.
. Enable cloud storage on the origin cluster by running `rpk cluster config edit`, and then specify the following cluster configuration properties:
+
|===
| Property | Description

| `cloud_storage_enabled: true`
| Must be set to `true` to enable the cloud storage feature.

| `cloud_storage_bucket: “<bucket_name>”`
| The S3 bucket where the original data is stored.

| `cloud_storage_access_key: “<access_key>”`
| The access key used for authentication. When using xref:security:iam-roles.adoc[IAM roles], you do not have to specify this property.

| `cloud_storage_secret_key: “<secret_key>”`
| The secret key used for authentication.  When using IAM roles, you do not have to specify this property.

| `cloud_storage_region: “<region>”`
| The region where the S3 bucket is located. This must be a supported region.

| `cloud_storage_enable_remote_write`
| When using archival storage or Tiered Storage on the origin cluster, set to `true` to enable data to be uploaded from Redpanda and written to cloud storage for all topics. To only enable data upload for a specific topic, set `cloud_storage_enable_remote_write: false` and run `rpk topic create <topic_name> -c redpanda.remote.write=true` when you create the topic.

| `cloud_storage_enable_remote_read`
| When using Tiered Storage on the origin cluster, set to `true` to enable consumers to read from all topics in cloud storage. To enable consumers to only read from one topic, set `cloud_storage_enable_remote_read: false` and run `rpk topic create <topic_name> -c redpanda.remote.read=true` when you create the topic.
|===

. If you're using Google Cloud Storage, set the `cloud_storage_api_endpoint` property to `storage.googleapis.com`.

== Setting up a Remote Read Replica

To set up a Remote Read Replica topic on a separate remote cluster:

. Create a remote cluster for the Remote Read Replica topic in the same region as the S3 bucket used for the origin cluster. If the S3 bucket is a multi-region bucket, you can create the read replica cluster in any region that has that bucket. If the S3 bucket is a single-region bucket, the remote cluster must be in the same region as the S3 bucket.
. Run `rpk cluster config edit`, and then specify the following cluster configuration properties:
+
|===
| Property | Description

| `cloud_storage_enabled: true`
| Must be set to `true` to enable the cloud storage feature.

| `cloud_storage_bucket: “none”`
| No S3 bucket is needed for the remote cluster.

| `cloud_storage_access_key: “<access_key>”`
| The access key that allows read access to the S3 bucket. When using xref:security:iam-roles.adoc[IAM roles], you do not have to specify this property.

| `cloud_storage_secret_key: “<secret_key>”`
| The secret key that allows read access to the S3 bucket.  When using IAM roles, you do not have to specify this property.

| `cloud_storage_region: “<region>”`
| The region where the remote cluster is created.
|===

. If you're using Google Cloud Storage, set the `cloud_storage_api_endpoint` property to `storage.googleapis.com`.
. Create the Remote Read Replica topic by running `rpk topic create <topic_name> -c redpanda.remote.readreplica=<bucket_name>`. For `<topic_name>`, use the same name as the original topic. For `<bucket_name>`, use the S3 bucket specified in the `cloud_storage_bucket` property for the origin cluster.

'''

== Suggested reading

* https://redpanda.com/blog/remote-read-replicas-for-distributing-work[Remote Read Replicas: Read-only topics in tiered storage]
