= rpk cluster logdirs describe
:description: rpk cluster logdirs describe

Describe log directories on Redpanda brokers.

This command prints information about log directories on brokers, particularly,
the base directory that topics and partitions are located in, and the size of
data that has been written to the partitions. The size you see may not exactly
match the size on disk as reported by du: Redpanda allocates files in chunks.
The chunks will show up in du, while the actual bytes so far written to the
file will show up in this command.

The directory returned is the root directory for partitions. Within Redpanda,
the partition data lives underneath the returned root directory in `+kafka/{topic}/{partition}_{revision}/+` where revision is a Redpanda internal concept.

== Usage

----
rpk cluster logdirs describe [flags]
----

== Flags

[cols=",,",]
|===
|*Value* |*Type* |*Description*

|--aggregate-into |string |If non-empty, what column to aggregate into
starting from the partition column (broker, dir, topic).

|-b, --broker |int32 |If non-negative, the specific broker to describe
(default -1).

|-h, --help |- |Help for describe.

|--sort-by-size |- |If true, sort by size.

|--topics |strings |Specific topics to describe.

|--brokers |strings |Comma-separated list of broker <ip>:<port> pairs
(for example,
` --brokers \'192.168.78.34:9092,192.168.78.35:9092,192.179.23.54:9092\' `
). Alternatively, you may set the `REDPANDA_BROKERS` environment
variable with the comma-separated list of broker addresses.

|--config |string |Redpanda config file, if not set the file will be
searched for in the default locations.

|--password |string |SASL password to be used for authentication.

|--sasl-mechanism |string |The authentication mechanism to use.
Supported values: SCRAM-SHA-256, SCRAM-SHA-512.

|--tls-cert |string |The certificate to be used for TLS authentication
with the broker.

|--tls-enabled |- |Enable TLS for the Kafka API (not necessary if
specifying custom certs).

|--tls-key |string |The certificate key to be used for TLS
authentication with the broker.

|--tls-truststore |string |The truststore to be used for TLS
communication with the broker.

|--user |string |SASL user to be used for authentication.

|-v, --verbose |- |Enable verbose logging (default `false`).
|===
