=== Enable maintenance mode

. Check that all brokers are healthy:
+
[,bash]
----
rpk cluster health
----
+
.Example output:
[%collapsible]
====
[.no-copy]
----
CLUSTER HEALTH OVERVIEW
=======================
Healthy:                     true <1>
Controller ID:               0
All nodes:                   [0 1 2] <2>
Nodes down:                  [] <3>
Leaderless partitions:       [] <3>
Under-replicated partitions: [] <3>
----
<1> The cluster is either healthy (`true`) or unhealthy (`false`).
<2> The node IDs of all brokers in the cluster.
<3> If the cluster is unhealthy, these fields will contain data.
====

ifdef::rolling-upgrade[. Select a broker that has not been upgraded yet and place it into maintenance mode:]
ifdef::rolling-restart[. Select a broker and place it into maintenance mode:]
+
```bash
rpk cluster maintenance enable <node-id> --wait
```
+
The `--wait` option tells the command to wait until a given broker, 0 in this example, finishes draining all partitions it originally served. After the partition draining completes, the command completes.
+
.Expected output:
+
[.no-copy]
----
Successfully enabled maintenance mode for node 0
Waiting for node to drain...
----

. Verify that the broker is in maintenance mode:
+
```bash
rpk cluster maintenance status
```
+
.Expected output:
[%collapsible]
====
[.no-copy]
----
NODE-ID  DRAINING  FINISHED  ERRORS  PARTITIONS  ELIGIBLE  TRANSFERRING  FAILED
0        true      true      false   3           0         2             0
1        false     false     false   0           0         0             0
2        false     false     false   0           0         0             0
----

The `Finished` column should read `true` for the broker that you put into maintenance mode.
====

. Validate the health of the cluster again:
+
```bash
rpk cluster health --watch --exit-when-healthy
```
+
The combination of the `--watch` and `--exit-when-healthy` flags tell rpk to monitor the cluster health and exit only when the cluster is back in a healthy state.
+
[NOTE]
====
ifdef::rolling-upgrade[]
You can also evaluate xref:manage:monitoring.adoc[external metrics] to determine cluster health. If the cluster has any issues, take the broker out of maintenance mode by running the following command before proceeding with other operations, such as decommissioning or retrying the rolling upgrade:
endif::[]
ifdef::rolling-restart[]
You can also evaluate xref:manage:monitoring.adoc[external metrics] to determine cluster health. If the cluster has any issues, take the broker out of maintenance mode by running the following command before proceeding with other operations, such as decommissioning or retrying the rolling restart:
endif::[]

```bash
rpk cluster maintenance disable <node-id>
```
====