== Limitations

The following limitations ensure a smooth transition between versions and help to maintain the stability of your cluster.

* *Broker upgrades*:

** New features are enabled only after upgrading all brokers in the cluster.
** You can upgrade only one feature release at a time, for example from 22.2 to 22.3. Skipping feature releases is not supported.

* *Rollbacks*: You can roll back to the original version only if at least one broker is still running the original version (not yet upgraded) and the cluster hasn't yet restarted.

* *Downgrades*:
Downgrades are possible only between patch releases of the same feature release. For example, you can downgrade from 22.2.2 to 22.2.1. Downgrading to previous feature releases, such as 22.1.x, is not supported.

* *Tiered Storage*:
If you have xref:manage:tiered-storage.adoc[Tiered Storage] enabled and you're upgrading to 23.2, object storage uploads are paused until all brokers are upgraded. If the cluster cannot upgrade, roll it back to the original version.
+
CAUTION: In a mixed-version state, the cluster could run out of disk space. If you need to force a mixed-version cluster to upload, transfer partition leadership to brokers running the original version.

* *Remote Read Replicas*:
Upgrade the Remote Read Replica cluster first, ensuring it's on the same version as the origin cluster or one feature release ahead of the origin cluster.
When upgrading to Redpanda 23.2, metadata from object storage is not synchronized until all brokers in the cluster are upgraded. If you need to force a mixed-version cluster to sync read replicas, transfer partition leadership to brokers running the original version.

* *Controller snapshots*:
Starting in Redpanda version 23.2, when older clusters are upgraded to a version supporting controller snapshots, this feature is enabled by default.  After controller snapshots is enabled, it persists across cluster restarts and future upgrades. New clusters created subsequently automatically enable controller snapshots.