= Usage Metrics
:description: Learn about the metrics Redpanda uses to measure consumption in Redpanda Cloud.
:page-cloud: true

Redpanda Cloud uses various metrics to measure the consumption of resources. 

* All pricing is set in US dollars (USD). 
* All billing computations are conducted in Coordinated Universal Time (UTC). Billing accrues at hourly intervals. Any usage that is less than an hour is billed for the full hour. 

NOTE: Pricing information is available on https://redpanda.com/redpanda-cloud/serverless[redpanda.com]. For questions about billing, contact billing@redpanda.com.

== Serverless metrics

There is no base cost for a Serverless instance. Pricing for Serverless clusters depends on the data in, data out, data stored, and partitions (virtual streams).

|=== 
| Metric | Description 

| Ingress | This tracks the data written into Redpanda (in GB).

The cost varies based on the region you select for your cluster. 

All Kafka protocol requests (_except_ message headers) are counted as ingress as soon as they are read by Redpanda's proxy process. 
| Egress | This tracks the data read out of Redpanda (in GB).

All Kafka protocol responses generated by the cluster (_except_ message headers) are counted as egress as soon as the cluster processes the request, even if the client drops the connection before they are delivered.
| Storage | This tracks the data in object storage per hour (in GB). 
| Partitions | This tracks the number of partitions used per hour.

|===

See also: xref:get-started:cluster-types/serverless.adoc#limitations[Serverless limits]

== Dedicated metrics

Pricing for Dedicated clusters depends on the time the instance in up, the data in, data out, and data stored.

|=== 
| Metric | Description 

| Instance | This tracks the number of hours the instance is running. 

The cost varies based on the xref:reference:tiers/byoc-tiers.adoc[region and tier] you select for your cluster.   
| Ingress | This tracks the data written into Redpanda (in GB). 

The cost varies based on the region you select for your cluster. 

All Kafka protocol requests (_including_ message headers) are counted as ingress as soon as they are read by Redpanda's proxy process. 
| Egress | This tracks the data read out of Redpanda (in GB).

All Kafka protocol responses generated by the cluster (_including_ message headers) are counted as egress as soon as the cluster processes the request, even if the client drops the connection before they are delivered. 

The cost varies based on the number of availability zones (AZ) you select for your cluster. 
| Storage | This tracks the data in object storage per hour (in GB). 

Replication to object storage is implemented with glossterm:Tiered Storage[]. All topics have a fixed replication factor of 3, but Redpanda counts each byte only once.

|=== 

== Next steps

* xref:billing:gcp-commit.adoc[]
* xref:billing:aws-commit.adoc[]