= JavaScript Schema Registry API for Data Transforms
:description: Work with Schema Registry in data transforms using JavaScript.

This page contains the API reference for the Schema Registry client library of the data transforms JavaScript SDK.

== Functions

[[newClient]]
=== newClient()

  newClient (): <<SchemaRegistryClient, `SchemaRegistryClient`>>

Returns a client interface for interacting with Redpanda Schema Registry.

==== Returns

<<SchemaRegistryClient, `SchemaRegistryClient`>>

==== Example

```js
import { newClient, SchemaFormat } from "@redpanda-data/sr";

var sr_client = newClient();
const schema = {
  type: "record",
  name: "Example",
  fields: [
    { "name": "a", "type": "long", "default": 0 },
    { "name": "b", "type": "string", "default": "" }
  ]
};

const subj_schema = sr_client.createSchema(
  "avro-value",
  {
    schema: JSON.stringify(schema),
    format: SchemaFormat.Avro,
    references: [],
  }
);
```

[[decodeSchemaID]]
=== decodeSchemaID()

  decodeSchemaID  (`buf`): <<DecodeResult, `DecodeResult`>>

==== Parameters

- `buf`: `string`, `ArrayBuffer`, or `Uint8Array`

==== Returns

<<DecodeResult, `DecodeResult`>> in the same type as the given argument.

== Interfaces

[[DecodeResult]]
=== DecodeResult

The result of a <<decodeSchemaID, `decodeSchemaID`>> function.

==== Properties

- `id` (read only): The decoded Schema ID
- `rest` (read only): The remainder of the input buffer after stripping the encoded ID.

=== Reference

==== Properties

- `name`: `string`

- `subject`: `string`

- `version`: `number`

=== Schema

==== Properties

- `format` (read only): <<SchemaFormat, `SchemaFormat`>>

- `references` (read only): <<Reference, `Reference`>>

- `schema` (read only): `string`

[[SchemaRegistryClient]]
=== SchemaRegistryClient

Client interface for interacting with Redpanda Schema Registry.

==== Methods

- `createSchema(subject (string), <<Schema, schema>>)`: <<SubjectSchema, `SubjectSchema`>>

- `lookupLatestSchema(subject (string))`: <<SubjectSchema, `SubjectSchema`>>

- `lookupSchemaById(id (number))`: <<Schema, `Schema`>>

- `lookupSchemaByVersion(subject (string), version (number))`: <<SubjectSchema, `SubjectSchema`>>

[[SubjectSchema]]
=== SubjectSchema

==== Properties

- `id` (read only): `number`

- `schema` (read only): <<Schema, `Schema`>>

- `subject` (read only): `string`

- `version` (read only): `number`

== Enumerations

[[SchemaFormat]]
=== SchemaFormat

==== Enumeration Members

- Avro: `0`

- Protobuf: `1`

- JSON: `2`

== Suggested reading

xref:reference:data-transforms/js/js-sdk.adoc[]