= Kafka Connect
:description: Connect one or more Kafka Connect clusters with Redpanda Console.
:page-aliases: console:features/kafka-connect.adoc


Redpanda Console provides a user interface that lets you manage multiple Kafka Connect clusters.
You can inspect or patch connectors; restart, pause, and resume connector tasks; and delete connectors.
Redpanda Console queries all configured Kafka Connect
clusters for their status, so you have an overview of all your Kafka Connect clusters.

NOTE: Redpanda self-hosted deployments do not include a Kafka Connect cluster. For information about Redpanda managed connectors to different data systems, see xref:deploy:deployment-option/cloud/managed-connectors/index.adoc[].

== Configuration

For each cluster, provide a unique name,
the HTTP address of the cluster, and the authentication settings, if required. The name can be any unique string that
helps you to identify the Kafka Connect cluster. 
See all available configuration options in the xref:reference:console/config.adoc[Redpanda Console Configuration].

The following sample configuration goes in the configuration file's root level.

[,yaml]
----
connect:
  enabled: true
  clusters:
    - name: datawarehouse # Required field, will be used as identifier in the frontend
      url: http://dwh-connect.mycompany.com:8083
      tls:
        enabled: false # Trusted certs are still allowed by default
      username: admin
      # password: # Set using flag --connect.clusters.0.password=secret
    - name: analytics # Required field, will be used as identifier in the frontend
      url: http://analytics.mycompany.com:8083
      # No auth configured on that cluster, hence no username/password set
----
