= Manage Schema Registry
:description: Perform common Schema Registry management operations in Redpanda Console.
:page-aliases: console:features/schema-registry.adoc

Producer clients and consumer clients use schemas as an agreed-upon format for sending and receiving messages. They register and retrieve the schemas they use in Redpanda's Schema Registry to ensure data verification. Within Redpanda Console, you can perform common Schema Registry management operations. 

[NOTE]
====
This section describes managing Schema Registry operations in Redpanda Console (or Redpanda Cloud), but you also xref:manage:schema-registry.adoc[manage Schema Registry operations in the Schema Registry API].
====

== Use Schema Registry in the UI

In Redpanda Console, the **Schema Registry** tab lists registered and verified schemas. 

A schema is registered with a subject, which is a logical grouping or category. The subject is associated with the schema as it evolves. To add a new schema, select the topic, the key or value, and the unique subject name you want to register. When data formats are updated, a new version of the schema can be registered under the same subject, allowing for backward and forward compatibility.

You can configure different types of schema compatibility, which are applied to the subject when a new schema is registered. For details about supported compatibility types, see xref:manage:schema-registry.adoc#configure-schema-compatibility[Configure schema compatibility].

Schemas cannot be permanently deleted if any other schemas reference it. They remain readable with a soft delete until you remove all references to it. A soft-deleted schema can be retrieved and re-registered. A hard deleted schema cannot be recovered.

== Use Schema Registry manually

Alternatively, you can use the Schema Registry API for management tasks. For details, see xref:reference:api-reference.adoc[].

To deserialize Kafka records that have been encoded with a serializer, such as +
`io.confluent.kafka.serializers.KafkaAvroSerializer`, you must have a valid `schemaRegistry` configuration in Redpanda Console. Additionally, you can inspect, edit, and delete the registered schemas.

[,yaml]
----
kafka:
  schemaRegistry:
    enabled: true
    urls: ["https://my-schema-registry.com"]
    username: console
    password: redacted # Or set using flags or env variable
  # To enable protobuf support
  protobuf:
    enabled: true
    schemaRegistry:
      enabled: true
      refreshInterval: 5m
----

== Next steps

* xref:./protobuf.adoc[]

