= Manage Schema Registry
:description: Perform common Schema Registry management operations in Redpanda Console.
:page-aliases: console:features/schema-registry.adoc

Producer clients and consumer clients use schemas as an agreed-upon format for sending and receiving messages. They register and retrieve the schemas they use in Redpanda's Schema Registry to ensure data verification. Within Redpanda Console, you can perform common Schema Registry management operations. 

[NOTE]
====
This section describes managing Schema Registry operations in Redpanda Console, but you can also xref:manage:schema-registry.adoc[manage Schema Registry operations with the API].
====

== Prerequisites for self-hosted Redpanda

Redpanda Console with Schema Registry is automatically configured with Redpanda Cloud. If you're running Redpanda Console with self-hosted Redpanda, you must have a valid `schemaRegistry` configuration in Redpanda Console. For example:

[,yaml]
----
kafka:
  schemaRegistry:
    enabled: true
    urls: ["https://my-schema-registry.com"]
    username: console
    password: redacted # Or set using flags or env variable
  # To enable protobuf support
  protobuf:
    enabled: true
    schemaRegistry:
      enabled: true
      refreshInterval: 5m
----

== Use Schema Registry in the UI

In Redpanda Console, the **Schema Registry** tab lists registered and verified schemas. 

A schema is registered with a _subject_, which is a logical grouping or category for schemas. The subject is associated with the schema as it evolves. When data formats are updated, a new version of the schema can be registered under the same subject, allowing for backward and forward compatibility.

A _serialization format_ defines how data is converted into bytes that are transmitted and stored. Serialization, by producers, converts an event into bytes. Deserialization, by consumers, converts the bytes of arrays back into the desired data format. Redpanda supports Avro and Protobuf serialization formats.

=== Create and edit a schema

. To register a new schema, select the the strategy type for how to derive the subject name. For example, if you select the **Topic Name** strategy, then it autofills the topic name (with the key or value) as the subject name. You can select to use topic, topic + record, record, or your own custom name. 

. Select the format (Avro or Protobuf) with the schema definition. 

. You can include a reference, which lets the schema refer to other schemas.

. After registering a schema, you can add a new version to it, delete its subject, or change its compatibility.

=== Edit compatibility 

include::partial$schema-compatibility.adoc[]

=== Delete a schema

Schemas cannot be permanently deleted if any other schemas reference it. They remain readable with a soft delete until you remove all references to it. A soft-deleted schema can be recovered, but a permanently-deleted schema cannot be recovered. Redpanda does not recommend permanently deleting schemas in a production environment.

== Next steps

* xref:./protobuf.adoc[]

