= Manage Schema Registry
:description: Perform common Schema Registry management operations in Redpanda Console.
:page-aliases: console:features/schema-registry.adoc

Producer clients and consumer clients use schemas as an agreed-upon format for sending and receiving messages. They register and retrieve the schemas they use in Redpanda's Schema Registry to ensure data verification. Within Redpanda Console, you can perform common Schema Registry management operations.

For more information about Redpanda's Schema Registry, see xref:manage:schema-registry.adoc[].

== Use Schema Registry in the UI

In Redpanda Console, the Schema Registry tab lists registered and verified schemas. 

A schema is registered with a subject, which is a name that is associated with the schema as it evolves. To add a new schema, select the topic, the key or value, and the unique subject name you want to register. A _subject_ is a logical grouping or category for schemas. When data formats are updated, a new version of the schema can be registered under the same subject, allowing for backward and forward compatibility.

You can add new versions of a schema, edit compatibility, and delete schemas. Schemas cannot be permanently deleted if any other schemas reference it. They remain readable with a soft-delete until you remove all listed references to it. 

== Use Schema Registry manually

To deserialize Kafka records that have been encoded with a serializer, such as +
`io.confluent.kafka.serializers.KafkaAvroSerializer`, you must have a valid schema registry configuration in Redpanda Console. 

Additionally you can inspect, edit, and delete the registered schemas.

[,yaml]
----
kafka:
  schemaRegistry:
    enabled: true
    urls: ["https://my-schema-registry.com"]
    username: console
    password: redacted # Or set using flags or env variable
  # If you want to enable protobuf support enable it here
  protobuf:
    enabled: true
    schemaRegistry:
      enabled: true
      refreshInterval: 5m
----

== Next steps

* xref:./protobuf.adoc[]

