= Docker Compose Samples for Redpanda
:description: Docker Compose Samples for Redpanda and Redpanda Console.

Use these Docker Compose samples to test Redpanda features and applications during development.

.Redpanda in Docker is supported only for development and testing.
[NOTE]
====
To deploy Redpanda in production, use one of the following environments:

* xref:deploy:deployment-option/self-hosted/manual/index.adoc[Linux]
* xref:deploy:deployment-option/self-hosted/kubernetes/index.adoc[Kubernetes]
====

== Prerequisites

To run `docker compose` you must install Docker on your machine. See the
https://docs.docker.com/compose/install/[Docker documentation].

== Owl shop sample application

This `docker-compose.yml` file starts a single Redpanda broker, Redpanda Console, and a sample application called _owl shop_. Owl shop simulates a simple ecommerce shop that uses Redpanda as an asynchronous communication exchange. Owl shop creates topics, produces sample data to those topics, and consumes from those topics.

. Paste the following YAML into a `docker-compose.yml` file on your computer, and run `docker compose up -d` inside the same directory.
+
NOTE: If you are running on an ARM-based device such as the Apple M1 chip, uncomment the `platform: 'linux/amd64'` lines.
+
.Reveal the `docker-compose.yml`
[%collapsible]
====
.`docker-compose.yml`
[,yaml,subs="attributes+"]
----
include::shared:attachment$docker/owl-shop/docker-compose.yml[]
----
====

. Open Redpanda Console at http://localhost:8080[localhost:8080] and go to *Topics* to see the Owl Shop topics.

== Samples for Redpanda Enterprise Edition

This section contains `docker-compose.yml` files with features that require a license key for Redpanda Enterprise Edition. The license key is uploaded to the Redpanda broker through a separate container called `redpandarpk`. This container executes the `rpk cluster license set` command to load the license key from the given filepath.

To request a trial license, to extend your trial period, or to purchase an Enterprise Edition license, contact https://redpanda.com/try-redpanda?section=enterprise-trial[Redpanda Sales].

In the same location as your `docker-compose.yml` file, save your license key to a file called `redpanda.license` in a directory called `license`. Or, to use another location, update the license paths in the `docker-compose.yml` files to another directory that contains your license key.

=== Plain login authentication for Redpanda Console

This `docker-compose.yml` file configures Redpanda Console with a plain login provider so that users of Redpanda Console must log in with a username and password.

. Paste the following YAML into a `docker-compose.yml` file on your computer, and run `docker compose up -d` inside the same directory.
+
.Reveal the `docker-compose.yml`
[%collapsible]
====
.`docker-compose.yml`
[,yaml,subs="attributes+"]
----
include::shared:attachment$docker/console-plain-login/docker-compose.yml[]
----
====

. Open Redpanda Console at [localhost:8080](http://localhost:8080) and log in with the credentials for `john` or `jane`.

== Customize the samples

If you want to configure Redpanda or Redpanda Console, you need to customize the sample YAML files.

=== Configure Redpanda in Docker

To configure the Redpanda services with xref:./nod-properties.adoc[node configuration properties], you can do the following:

- Pass configuration properties to the `--set` option in the `redpanda start` command. For example:
+
[,yaml]
----
redpanda:
  command:
    - redpanda
    - start
    - --set pandaproxy_client.retries=6
----

- Create a `redpanda.yaml` file and mount it to the `/etc/redpanda/` directory on the `redpanda` containers. For example, if you create the `redpanda.yaml` file in a directory called `redpanda-mounts`, configure the following volume mounts:
+
[,yaml]
----
redpanda:
  volumes:
    - ./redpanda-mounts:/etc/redpanda/
----

=== Configure Redpanda Console in Docker

To configure the Redpanda Console service with xref:reference:console/config.adoc[configuration properties], you can do the following:

* Use environment variables, for example:
+
[,yaml]
----
console:
  environment:
    KAFKA_RACKID: rack1
----

* Create a `redpanda-console-config.yaml` file and mount it to the `/etc/redpanda/` directory on the `redpanda-console` container. For example, if you create the `redpanda-console-config.yaml` file in a directory called `console-mounts`, configure the following volume mounts:
+
[,yaml]
----
console:
  volumes:
    - ./console-mounts:/etc/redpanda/
----
