= rpk
:description: rpk commands list

Redpanda Keeper `rpk` is Redpanda's command line interface (CLI) utility.

The `rpk` commands let you configure, manage, and tune Redpanda clusters. They also let you manage topics, groups, and access control lists (ACLs).

The `rpk` commands feature autocompletion, so you that can write the first few letters that uniquely identify a command and then use the tab key to complete it. For more information, see xref:./rpk-generate/rpk-generate-shell-completion.adoc[rpk autocompletion documentation].

== rpk

rpk is the Redpanda CLI & toolbox.

== Usage

----
rpk [command]
----

== Flags


[cols=",,",]
|===
|*Value* |*Type* |*Description*
|-h, --help |- |Help for rpk.
|-v, --verbose |- |Enable verbose logging (default `false`).
|===


== Related topics

* xref:get-started:rpk-install.adoc[Introduction to rpk]

'''

== Suggested reading

* https://redpanda.com/blog/rpk-container/[Introducing rpk container]
* https://redpanda.com/blog/getting-started-rpk/[Getting started with rpk commands]
