= rpk
:description: rpk commands list
:page-aliases: reference:rpk-commands.adoc

Redpanda Keeper `rpk` is Redpanda's command line interface (CLI) utility.

The `rpk` commands let you configure, manage, and tune Redpanda clusters. They also let you manage topics, groups, and access control lists (ACLs).

The `rpk` commands feature autocompletion, so you that can write the first few letters that uniquely identify a command and then use the tab key to complete it. For more information, see xref:rpk/rpk-generate/rpk-generate-shell-completion.adoc[rpk autocompletion documentation].

This section lists the `rpk` commands in alphabetical order. Each command includes a table of flags and their descriptions. You can also get descriptions for each command flag by running `rpk <command> -–help` in your locally installed Redpanda.

== rpk

rpk is the Redpanda CLI & toolbox.

== Usage

[,bash]
----
rpk [command]
----

== Flags

[cols=",,",]
|===
|*Value* |*Type* |*Description*
|-h, --help |- |Help for rpk.
|-v, --verbose |- |Enable verbose logging (default `false`).
|===

== Suggested reading

* https://redpanda.com/blog/rpk-container/[Introducing rpk container]
* https://redpanda.com/blog/getting-started-rpk/[Getting started with rpk commands]
