= rpk iotune
:description: rpk iotune

Measure filesystem performance and create IO configuration file.

== Usage

[,bash]
----
rpk iotune [flags]
----

== Flags

[cols=",,",]
|===
|*Value* |*Type* |*Description*

|--config |string |Redpanda config file, if not set the file will be
searched for in the default locations.

|--directories |strings |List of directories to evaluate.

|--duration |duration |Duration of tests.The value passed is a sequence
of decimal numbers, each with optional fraction and a unit suffix, such
as\{" "} `300ms`, `1.5s` or `2h45m`. Valid time units are `ns`, `us` (or
`µs`),\{" "} `ms`, `s`, `m`, `h` (default 10m0s).

|-h, --help |- |Help for iotune.

|--timeout |duration |The maximum time after -- to wait for iotune to
complete. The value passed is a sequence of decimal numbers, each with
optional fraction and a unit suffix, such as `300ms`, `1.5s` or\{" "}
`2h45m`. Valid time units are `ns`,\{" "} `us` (or `µs`), `ms`, `s`,\{"
"} `m`, `h` (default 1h0m0s).

|-v, --verbose |- |Enable verbose logging (default `false`).
|===
