= Manage Cloud Topics
:description: Cloud Topics are "diskless" Redpanda topics that enable you to store data directly to object storage to trade off latency for lower costs.
:page-topic-type: how-to
:personas: streaming_developer, platform_admin
:learning-objective-1: Describe the latency and cost trade-offs of Cloud Topics compared to standard Redpanda topics
:learning-objective-2: Create a Cloud Topic using rpk after enabling Cloud Topics on your cluster
:learning-objective-3: Identify Cloud Topics limitations and configurations that reduce cross-AZ networking costs
// tag::single-source[]

ifndef::env-cloud[]
[NOTE]
====
include::shared:partial$enterprise-license.adoc[]
====
endif::[]

include::develop:partial$cloud-topics-overview.adoc[tag=intro]

include::develop:partial$cloud-topics-overview.adoc[tag=latency-explanation]

== Prerequisites

ifdef::env-cloud[]
- xref:manage:rpk/rpk-install.adoc[Install rpk] v26.1 or later.
endif::[]
ifndef::env-cloud[]
- xref:get-started:rpk-install.adoc[] v26.1 or later.
- xref:manage:tiered-storage.adoc#set-up-tiered-storage[Enable cloud storage] on your Redpanda cluster.
+
[NOTE]
====
If you plan to use Cloud Topics for all new topics in a Redpanda cluster, be sure to set the following cluster-level property:
[,bash]
----
default_redpanda_storage_mode=cloud
----
This ensures that newly-created Redpanda topics are Cloud Topics by default.
For details, see xref:manage:tiered-storage.adoc#enable-tiered-storage-for-a-cluster[Enable Tiered Storage for a cluster].
====

- xref:manage:tiered-storage.adoc#configure-object-storage[Configure object storage].
- Ensure that you have an Enterprise license.
+
To check your license status, run:
+
[,bash]
----
rpk cluster license info
----

endif::[]

== Limitations

include::develop:partial$cloud-topics-limitations.adoc[tag=limitations]

== Enable Cloud Topics

To enable Cloud Topics for a cluster:

[,bash]
----
rpk cluster config set cloud_topics_enabled=true
----

NOTE: This configuration update requires a restart to take effect.


After enabling Cloud Topics, you can proceed to create new Cloud Topics:

[,bash]
----
rpk topic create -c redpanda.storage.mode=cloud <new-cloud-topic-name>
----

[,console]
----
TOPIC                    STATUS
audit.analytics.may2025  OK
----

You can make a topic a Cloud Topic only at topic creation time.

In addition to replication, cross-AZ ingress (producer) and egress (consumer) traffic can also contribute substantially to cloud networking costs. When running multi-AZ clusters in general, Redpanda strongly recommends using xref:develop:consume-data/follower-fetching.adoc[Follower Fetching], which allows consumers to avoid crossing network zones. When possible, you can use xref:develop:produce-data/leader-pinning.adoc[leader pinning], which positions a topic's partition leader close to the producers, providing a similar benefit for ingress traffic. These features can add additional savings to the replication cost savings of Cloud Topics.

// end::single-source[]
