= Cloud Topics
:description: Cloud Topics are Kafka topics that enable users to trade off latency for lower costs.
:page-beta: true
:page-categories: Clients, Development
// tag::single-source[]

ifndef::env-cloud[]
[NOTE]
====
include::shared:partial$enterprise-license.adoc[]
====
endif::[]

Starting in v25.3, Redpanda provides Cloud Topics to support multi-modal streaming workloads in the most cost-effective way possible. While standard Kafka xref:config-topics.adoc[topics] are ideal for latency-sensitive, high-throughput workloads (for example, for audit logs), Cloud Topics are optimized for high-throughput, cost-sensitive workloads that can tolerate higher latencies. Instead of replicating every byte across expensive network links, Cloud Topics leverage durable, inexpensive Cloud object storage (S3, GCS, MinIO) as the primary mechanism for backing up data. The difference in response time is typically 500ms, which is only impactful for latency-sensitive applications.

== Prerequisites

- xref:get-started:rpk-install.adoc[] v25.3 or later.
ifndef::env-cloud[]
- xref:manage:tiered-storage.adoc#set-up-tiered-storage[Set up] and xref:manage:tiered-storage.adoc#enable-tiered-storage[enable Tiered Storage] on your Redpanda cluster.
- xref:manage:tiered-storage.adoc#configure-object-storage[Configure object storage].
- You must have an Enterprise license.

To check if you already have a license key applied to your cluster:

[,bash]
----
rpk cluster license info
----
endif::[]

== Limitations

Not all Redpanda features are available when using Cloud Topics (beta). The following features are not supported in this beta release:

- Kafka compaction
- Iceberg topics
- Topic recovery
- Remote Read Replicas

Also note that Cloud Topics do not work in simple Docker containers unless Cloud storage is set up in them.

IMPORTANT: You should expect to throw away any cluster running the Cloud Topics (beta) after it becomes generally available (GA). Redpanda will be unable to continue using data that was generated by the beta version of this feature. Also, any topic specified to be a Cloud Topic cannot subsequently be converted back to a standard, or non-Cloud Topic.

== Create Cloud Topics

You can make a topic a Cloud Topic only at creation time. This is a two-step process where you first create the Cloud Topic, then enable that Cloud Topic in your cluster.

IMPORTANT: Once you create a Cloud Topic, you cannot subsequently convert it back into a standard Kafka topic.

To create a Cloud Topic:

[,bash]
----
rpk topic create -c redpanda.cloud_topic.enable=true <new-cloud-topic-name>
----

[,bash,role=no-copy]
----
TOPIC                    STATUS
audit.analytics.may2025  OK
----

To enable a Cloud Topic in a cluster:

[,bash]
----
rpk cluster config set unstable_beta_feature_cloud_topics_enabled=true <topic-name>
----

NOTE: For non-replicated cross-AZ traffic (for example, for producers), if your throughput costs remain elevated, you can use xref:../produce-data/leader-pinning.adoc[leader pinning], which positions a topic's partition leader close to the producers, and helps eliminate this traffic.

// end::single-source[]