= Manage Cloud Topics
:description: Cloud Topics are "diskless" Redpanda topics that enable you to store data directly to object storage to trade off latency for lower costs.
:page-topic-type: how-to
:personas: streaming_developer, platform_admin
// tag::single-source[]
ifdef::env-cloud[:producers-page: develop:topics/configure-producers-for-cloud-topics.adoc]
ifndef::env-cloud[:producers-page: develop:manage-topics/configure-producers-for-cloud-topics.adoc]
:learning-objective-1: Describe the latency and cost trade-offs of Cloud Topics compared to standard Redpanda topics
:learning-objective-2: Create a Cloud Topic using rpk on a cluster that has cloud storage enabled
:learning-objective-3: Identify Cloud Topics limitations and configurations that reduce cross-AZ networking costs

ifndef::env-cloud[]
[NOTE]
====
include::shared:partial$enterprise-license.adoc[]
====
endif::[]

include::develop:partial$cloud-topics-overview.adoc[tag=intro]

include::develop:partial$cloud-topics-overview.adoc[tag=latency-explanation]

After reading this page, you will be able to:

* [ ] {learning-objective-1}
* [ ] {learning-objective-2}
* [ ] {learning-objective-3}

== Prerequisites

ifdef::env-cloud[]
- xref:manage:rpk/rpk-install.adoc[Install rpk] v26.1 or later.
endif::[]
ifndef::env-cloud[]
- xref:get-started:rpk-install.adoc[] v26.1 or later.
- xref:manage:tiered-storage.adoc#set-up-tiered-storage[Enable cloud storage] on your Redpanda cluster.
+
[NOTE]
====
If you plan to use Cloud Topics for all new topics in a Redpanda cluster, be sure to set the following cluster-level property:
[,bash]
----
default_redpanda_storage_mode=cloud
----
This ensures that newly-created Redpanda topics are Cloud Topics by default.
For details, see xref:manage:tiered-storage.adoc#enable-tiered-storage-for-a-cluster[Enable Tiered Storage for a cluster].
====

- xref:manage:tiered-storage.adoc#configure-object-storage[Configure object storage].
- Ensure that you have an Enterprise license.
+
To check your license status, run:
+
[,bash]
----
rpk cluster license info
----

endif::[]

== Limitations

include::develop:partial$cloud-topics-limitations.adoc[tag=limitations]

== Create Cloud Topics

Cloud Topics don't require a separate cluster property to enable them. When cloud storage is enabled for your cluster, you can create Cloud Topics directly.

ifndef::env-cloud[]
NOTE: In Redpanda versions earlier than v26.2, you must also set the `cloud_topics_enabled` cluster property to `true` and restart the cluster. This property is deprecated in v26.2 and later. For details, see xref:upgrade:deprecated/index.adoc[Deprecated features].
endif::[]

To create a Cloud Topic, set the topic property `redpanda.storage.mode` to `cloud`:

[,bash]
----
rpk topic create -c redpanda.storage.mode=cloud <new-cloud-topic-name>
----

[,console]
----
TOPIC                    STATUS
audit.analytics.may2025  OK
----

You can make a topic a Cloud Topic only at topic creation time.

In addition to replication, cross-AZ ingress (producer) and egress (consumer) traffic can also contribute substantially to cloud networking costs. When running multi-AZ clusters in general, Redpanda strongly recommends using xref:develop:consume-data/follower-fetching.adoc[Follower Fetching], which allows consumers to avoid crossing network zones. When possible, you can use xref:develop:produce-data/leader-pinning.adoc[leader pinning], which positions a topic's partition leader close to the producers, providing a similar benefit for ingress traffic. These features can add additional savings to the replication cost savings of Cloud Topics.

For client-side tuning guidance, see xref:{producers-page}[Configure producers for Cloud Topics].

// end::single-source[]
