= Configure AWS PrivateLink for Redpanda Cloud
:description: Set up AWS PrivateLink to securely access Redpanda Cloud. 
:page-cloud: true

include::shared:partial$feature-flag.adoc[]

The Redpanda AWS PrivateLink endpoint service provides secure access to Redpanda Cloud from your own VPC. Traffic over PrivateLink does not go through the public internet because a PrivateLink connection is treated as its own private AWS service. Your VPC has access to the Redpanda VPC, but Redpanda cannot access your VPC.

Consider using the PrivateLink endpoint service if you have multiple VPCs and could benefit from a more simplified approach to network management:

* PrivateLink allows overlapping CIDR ranges in VPC networks.
* PrivateLink does not limit the number of VPC connections. VPC peering on the other hand, is limited to 125 connections (see https://aws.amazon.com/privatelink/faqs/["How scalable is AWS PrivateLink?"]).

After <<get-an-access-token,getting an access token>>, you can <<enable-privatelink-endpoint-service-for-new-clusters,enable PrivateLink when creating a new cluster>>, or you can <<enable-privatelink-endpoint-service-for-existing-clusters,enable PrivateLink for existing clusters>>.

TIP: Make sure to replace the variable values in the code examples on this page with your own values, before running the commands in the terminal or in a script.

== Requirements

* Install `rpk`.
* Your Redpanda cluster and <<create-client-vpc,VPC>> must be in the same region.
* You must use the Redpanda Cloud API to enable the Redpanda endpoint service for your clusters. Follow the steps below to <<get-an-access-token,get an access token>>.  
* Use the AWS CLI to create a new client VPC or modify an existing one to use the PrivateLink endpoint.

== Get an access token 

. Specify the base URL of the Redpanda Cloud API:
+
[,bash]
----
PUBLIC_API_ENDPOINT="https://api.cloud.redpanda.com"
----

. In the Redpanda Cloud UI, go to **Namespaces** and select the namespace where you want to create a cluster.
+
Copy the namespace ID (UUID) from the URL in the browser.
+
[,bash]
----
NAMESPACE_ID=<uuid>
----

. Go to the organization (org) level **Home** in the UI, and navigate to **Clients**. If you don't have an existing client, you can create a new one by clicking **Add client**.
+
Copy the client ID and secret.
+
[,bash]
----
CLOUD_CLIENT_ID=<client-ID>
CLOUD_CLIENT_SECRET=<client-secret>
----

. Get an API token using the client ID and secret. You can click the **Request an API token** link to see code examples to generate the token.
+
[,bash]
----
AUTH_TOKEN=`curl -s --request POST \
    --url 'https://auth.prd.cloud.redpanda.com/oauth/token' \
    --header 'content-type: application/x-www-form-urlencoded' \
    --data grant_type=client_credentials \
    --data client_id=$CLOUD_CLIENT_ID \
    --data client_secret=$CLOUD_CLIENT_SECRET \
    --data audience=cloudv2-production.redpanda.cloud | jq .access_token | sed 's/"//g'`
----

== Enable PrivateLink endpoint service for new clusters

. Call https://docs.api.redpanda.com/#post-/v1beta1/networks[`POST /v1beta1/networks`] to create a network.
+
Make sure to supply your own values in the example request below. Store the network ID (`network_id`) after the network is created.
+
--
- `name`
- `cidr_block`
- `aws_region`
--
+
[,bash]
----
REGION=<aws_region>

NETWORK_POST_BODY=`cat << EOF
{
    "cloud_provider": "CLOUD_PROVIDER_AWS",
    "cluster_type": "TYPE_BYOC",
    "name": "<my-private-link-network>",
    "cidr_block": "<10.0.0.0/20>",
    "namespace_id": "$NAMESPACE_ID",
    "region": "$REGION"
}
EOF`

NETWORK_ID=`curl -vv -X POST \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $AUTH_TOKEN" \
    -d "$NETWORK_POST_BODY" $PUBLIC_API_ENDPOINT/v1beta1/networks | jq .metadata.network_id`

echo $NETWORK_ID
----
+
Wait for the network to be ready before creating the cluster in the next step. You can check the state of the network by calling https://docs.api.redpanda.com/#get-/v1beta1/networks/-id-[`GET /v1beta1/networks/{id}`]. You can create the cluster when the state is `STATE_READY`.

. Create a new cluster with the endpoint service enabled by calling https://docs.api.redpanda.com/#post-/v1beta1/clusters[`POST /v1beta1/clusters`].
+
In the example below, make sure to set your own values for the following fields:
+
--
- `zones`: for example, `"usw2-az1","usw2-az2","usw2-az3"`
- `type`: `TYPE_DEDICATED` for Dedicated Cloud clusters, or `TYPE_BYOC` for BYOC clusters
- `tier`: for example, `tier-1-aws-v2-arm`
- `name`
- `allowed_principals`: Amazon Resource Names (ARNs) for the AWS principals allowed to access the endpoint service. For example, for all principals in an account, use `arn:aws:iam::account_id:root`. See https://docs.aws.amazon.com/vpc/latest/privatelink/configure-endpoint-service.html#add-remove-permission[Configure an endpoint service] for details.
--
+
[,bash]
----
CLUSTER_POST_BODY=`cat << EOF
{
    "cloud_provider": "CLOUD_PROVIDER_AWS",
    "connection_type": "CONNECTION_TYPE_PRIVATE",
    "name": "<my-private-link-cluster>",
    "namespace_id": "$NAMESPACE_ID",
    "network_id": $NETWORK_ID,
    "region": "$REGION",
    "zones": [ <zones> ],
    "throughput_tier": "<tier>",
    "type": "<type>",
    "private_link": {
        "enabled": true,
        "aws": {
        "allowed_principals": ["<principal_1>","<principal_2>", ...]
        }
    }
}
EOF`

CLUSTER_ID=`curl -vv -X POST \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $AUTH_TOKEN" \
    -d "$CLUSTER_POST_BODY" $PUBLIC_API_ENDPOINT/v1beta1/clusters | jq .metadata.cluster_id | sed 's/"//g'`

echo $CLUSTER_ID
----
+
**BYOC clusters:** Check that the cluster operation is completed by calling https://docs.api.redpanda.com/#get-/v1beta1/operations/-id-[`GET /v1beta1/operations/{id}`], and passing the operation ID returned from the Create Cluster call.
+
When the Create Cluster operation is completed (`STATE_COMPLETED`), execute the following `rpk cloud` command to finish creating your BYOC cluster:
+
[,bash]
----
rpk cloud byoc aws apply --redpanda-id=$CLUSTER_ID
----

== Enable PrivateLink endpoint service for existing clusters

. In the Redpanda Cloud UI, go to the cluster overview and copy the cluster ID from the **Details** section.
+
[,bash]
----
CLUSTER_ID=<cluster_id>
----

. Make a https://docs.api.redpanda.com/#patch-/v1beta1/clusters/-cluster.id-[`PATCH /v1beta1/clusters/{cluster.id}`] request to update the cluster with the Redpanda Private Link Endpoint Service enabled.
+
In the example below, make sure to set your own value for the following field:
+
--
- `allowed_principals`: Amazon Resource Names (ARNs) for the AWS principals allowed to access the endpoint service. For example, for all principals in an account, use `arn:aws:iam::account_id:root`. See https://docs.aws.amazon.com/vpc/latest/privatelink/configure-endpoint-service.html#add-remove-permission[Configure an endpoint service] for details.
--
+
[,bash]
----
CLUSTER_PATCH_BODY=`cat << EOF
{
  "private_link": {
     "enabled": true,
     "aws": {
        "allowed_principals": ["<principal_1>","<principal_2>", ...]
     }
  }
}
EOF`

curl -vv -X PATCH \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $AUTH_TOKEN" \
  -d "$CLUSTER_PATCH_BODY" $PUBLIC_API_ENDPOINT/v1beta1/clusters/$CLUSTER_ID
----

. Before proceeding, check the state of the Update Cluster operation by calling https://docs.api.redpanda.com/#get-/v1beta1/operations/-id-[`GET /v1beta1/operations/{id}`], and passing the operation ID returned from Update Cluster call. When the state is `STATE_READY`, proceed to the next step.

. Check the service state by calling https://docs.api.redpanda.com/#get-/v1beta1/clusters/-id-[`GET /v1beta1/clusters/{id}`]. The `service_state` in the `private_link.status` response object must be `Available` for you to <<connect-to-privatelink-endpoint-service,connect to the service>>.
+
[,bash]
----
curl -X GET \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $AUTH_TOKEN" \
    $PUBLIC_API_ENDPOINT/v1beta1/clusters/$CLUSTER_ID | jq '.private_link.status.aws | {service_name, service_state}'
----

== Connect to PrivateLink endpoint service

=== Get cluster domain

Get the domain (`cluster_domain`) of the cluster from the cluster details in the Redpanda Cloud UI.

For example, if the Bootstrap server URL is: `seed-3da65a4a.cki01qgth38kk81ard3g.fmc.dev.cloud.redpanda.com:9092`, then `cluster_domain` is: `cki01qgth38kk81ard3g.fmc.dev.cloud.redpanda.com`.

[,bash]
----
CLUSTER_DOMAIN=<cluster_domain>
----

=== Get name of PrivateLink endpoint service

The service name is required to <<create-vpc-endpoint,create VPC private endpoints>>. Run the following command to get the service name:

[,bash]
----
PL_SERVICE_NAME=`curl -X GET \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $AUTH_TOKEN" \
  $PUBLIC_API_ENDPOINT/v1beta1/clusters/$CLUSTER_ID | jq -r .private_link.status.aws.service_name`
----

=== Create client VPC

If you are not using an existing VPC, you must create a new one. 

The VPC region must be the same region where the Redpanda cluster is deployed. Run the following command to create the VPC:

[,bash]
----
PROFILE=<specific-profile-from-credential-file>

aws ec2 create-vpc --region $REGION --profile $PROFILE --cidr-block 10.0.0.0/20
CLIENT_VPC_ID=<client_vpc_id>
----

You can also use an existing VPC. You need the VPC ID to <<modify-vpc-dns-attributes,modify its DNS attributes>>.

=== Modify VPC DNS attributes

Modify the VPC attributes using the following commands:

[,bash]
----
aws ec2 modify-vpc-attribute --region $REGION --profile $PROFILE --vpc-id $CLIENT_VPC_ID \
    --enable-dns-hostnames "{\"Value\":true}"

aws ec2 modify-vpc-attribute --region $REGION --profile $PROFILE --vpc-id $CLIENT_VPC_ID \
    --enable-dns-support "{\"Value\":true}"
----

These commands enable DNS hostnames and resolution for instances in the VPC.

=== Create security group

Run the following command. You need the security group ID `security_group_id` from the command output to <<add-security-group-rules,add security group rules>>.

[,bash]
----
aws ec2 create-security-group --region $REGION --profile $PROFILE --vpc-id $CLIENT_VPC_ID \
    --description "Redpanda endpoint service client security group" \
    --group-name "${CLUSTER_ID}-sg"
SECURITY_GROUP_ID=<security_group_id>
----

=== Add security group rules

This setting is based on the assumption that the Redpanda broker count is three. If you are not using three brokers, modify the example below:

* Replace `32094` with `32092 + <broker_count-1>`.
* Replace `35084` with `35082 + <broker_count-1>`.

[,bash]
----
aws ec2 authorize-security-group-ingress --region $REGION --profile $PROFILE \
    --group-id $SECURITY_GROUP_ID \
    --protocol "tcp" \
    --port 30292 \
    --cidr 0.0.0.0/0
aws ec2 authorize-security-group-ingress --region $REGION --profile $PROFILE \
    --group-id $SECURITY_GROUP_ID --protocol "tcp" \
    --port 30081 \
    --cidr 0.0.0.0/0
aws ec2 authorize-security-group-ingress --region $REGION --profile $PROFILE \
    --group-id $SECURITY_GROUP_ID --protocol "tcp" \
    --port 30282 \
    --cidr 0.0.0.0/0
# Adjust the port 32094 if the Redpanda broker count is not 3.
aws ec2 authorize-security-group-ingress --region $REGION --profile $PROFILE \
    --group-id $SECURITY_GROUP_ID \
    --protocol "tcp" \
    --port 32092-32094 \
    --cidr 0.0.0.0/0
# Adjust the port 35084 if the Redpanda broker count is not 3.
aws ec2 authorize-security-group-ingress --region $REGION --profile $PROFILE \
    --group-id $SECURITY_GROUP_ID \
    --protocol "tcp" \
    --port 35082-35084 \
    --cidr 0.0.0.0/0
----

=== Create VPC subnet

Run the following command, specifying the subnet availability zone (for example, `usw2-az1`). You need the subnet ID `subnet_id` from the command output to <<create-vpc-endpoint,create a VPC endpoint>>.

[,bash]
----
aws ec2 create-subnet --region $REGION --profile $PROFILE --vpc-id $CLIENT_VPC_ID \
    --availability-zone <zone> \
    --cidr-block 10.0.1.0/24
SUBNET_ID=<subnet_id>
----

=== Create VPC endpoint

[,bash]
----
aws ec2 create-vpc-endpoint \
    --region $REGION --profile $PROFILE \
    --vpc-id $CLIENT_VPC_ID \
    --vpc-endpoint-type "Interface" \
    --ip-address-type "ipv4" \
    --service-name $PL_SERVICE_NAME \
    --subnet-ids $SUBNET_ID \
    --security-group-ids $SECURITY_GROUP_ID \
    --private-dns-enabled
----

== Access Redpanda services through VPC endpoint

You can access Redpanda services such as xref:manage:schema-reg/schema-reg-overview.adoc[Schema Registry] and xref:develop:http-proxy.adoc[HTTP Proxy] from the client VPC, for example, from an EC2 instance in the VPC.

=== Access Kafka API seed service

Use port `30292` to access the Kafka API seed service.

[,bash]
----
export REDPANDA_BROKERS=rp-endpoint.$CLUSTER_DOMAIN:30292
rpk cluster info --tls-enabled --user <user> --password <password>
----

If successful, the `rpk` output should look like the following:

[,bash,role=no-copy]
----
CLUSTER
=======
redpanda.rp-cki01qgth38kk81ard3g

BROKERS
=======
ID    HOST                                                                PORT   RACK
0*    0-3da65a4a-0532364.cki01qgth38kk81ard3g.fmc.dev.cloud.redpanda.com  32092  use2-az1
1     1-3da65a4a-63b320c.cki01qgth38kk81ard3g.fmc.dev.cloud.redpanda.com  32093  use2-az1
2     2-3da65a4a-36068dc.cki01qgth38kk81ard3g.fmc.dev.cloud.redpanda.com  32094  use2-az1
----

=== Access Schema Registry seed service

Use port `30081` to access the Schema Registry seed service.

[,bash]
----
curl -vv -u <user>:<password> -H "Content-Type: application/vnd.schemaregistry.v1+json" --sslv2 --http2 https://rp-endpoint.$CLUSTER_DOMAIN:30081/subjects
----

=== Access HTTP Proxy seed service

Use port `30282` to access the Redpanda Proxy seed service.

[,bash]
----
curl -vv -u <user>:<password> -H "Content-Type: application/vnd.kafka.json.v2+json" --sslv2 --http2 https://rp-endpoint.$CLUSTER_DOMAIN:30081/topics
----

=== Access Kafka API service on a specific broker

- To access broker 0, use port `kafka_broker_port` 32092.
- To access broker 1, use port `kafka_broker_port` 32093.
- To access broker _i_, use port `kafka_broker_port` 32092 +_i_.


[,bash]
----
export REDPANDA_BROKERS=rp-endpoint.$CLUSTER_DOMAIN:<kafka_broker_port>
rpk cluster info --tls-enabled --user <user> --password <password>
----

=== Access HTTP Proxy on a specific broker

- To access broker 0, use port `proxy_broker_port` 35082.
- To access broker 1, use port `proxy_broker_port` 35083.
- To access broker _i_, use port `proxy_broker_port` 35082 + _i_.

[,bash]
----
curl -vv -u <user>:<password> -H "Content-Type: application/vnd.kafka.json.v2+json" --sslv2 --http2 https://rp-endpoint.$CLUSTER_DOMAIN:<proxy_broker_port>/topics
----
