= Manage Billing on Google Cloud Marketplace
:description: Understand how to manage your Redpanda Cloud billing.

When you sign up for Redpanda through Google Cloud Marketplace, you can view your bills and manage your Redpanda subscription directly in Google Cloud Marketplace. 

== Redpanda consumption units

Redpanda Cloud pricing is mapped to the consumption of resources in your organization. To calculate the bill, the number of units consumed is multiplied by the cost for that unit. All pricing is in US dollars (USD), converted to local currency by GCP. 

=== Instance pricing

* Each instance unit = 1 hour the instance is up. 
* The cost for an instance unit depends on the region and tier you selected for your Dedicated cluster.   

|===
| Region | Tier | Price

| us-east1 | Tier 1 | $1.98/hr
| us-east1 | Tier 2 | $3.96/hr
| us-central1 | Tier 1 | $2.26/hr
| us-central1 | Tier 2 | $4.52/hr
| northamerica-northeast1 | Tier 1 | 
| northamerica-northeast1 | Tier 2 | 
| europe-west1 | Tier 1 | 
| europe-west1 | Tier 2 | 
| europe-west2 | Tier 1 | 
| europe-west2 | Tier 2 | 
| asia-south1 | Tier 1 |
| asia-south1 | Tier 2 |
| asia-southeast1 | Tier 1 | 
| asia-southeast1 | Tier 2 | 
| australia-southeast1 | Tier 1 | 
| australia-southeast1 | Tier 2 | 
|===

=== Ingress and egress pricing

Redpanda Cloud charges for all data transfers, including each produce and consume request.

* Each ingress unit = 1 GB data written. 
* The cost for an ingress unit depends on the region you selected for your Dedicated cluster. 

|===
| North America | Europe | Asia | Australia

| $5/GB
| $5.7/GB
| $10/GB
| $12/GB
|===

* Each egress unit = 1 GB data read.
* The cost for an egress unit depends on the number of availability zones (AZ) you selected for your Dedicated cluster. 

|===
| Single AZ | Multiple AZs

| $5/GB
| $9/GB
|===

=== Storage pricing

Redpanda Cloud charges for the volume of data stored on a cluster, including replication. Replication is important for high availability. Because Redpanda Cloud has a default replication factor of three, the amount of data stored typically exceeds the volume of data written to the cluster. To reduce storage usage, you can configure the `retention.bytes` and `retention.ms` on a topic. 

* Each storage unit = 1 GB data in cloud storage per hour. 
* The cost for 1 unit of cloud storage is $0.00007937 per GB per hour. 