= Create a Dedicated Cloud Cluster
:description: Learn how to create a Dedicated cluster.
:page-aliases: cloud:create-dedicated-cloud-cluster-aws.adoc, deploy:deployment-option/cloud/provision-a-dedicated-cluster/index.adoc
:page-cloud: true
:page-categories: Deployment

To create a Dedicated Cloud cluster, log in to https://cloud.redpanda.com[Redpanda Cloud^]. Enter your organization name, and click *Continue*. 

== Create a Dedicated cluster

. On the Home page, select your namespace, or create a new one. 
+
Namespaces help you organize clusters and resources. For example, you can create namespaces for different teams or projects. A default namespace is created with every organization. When an organization has more than one namespace, you can select the namespace where you want to create a new cluster. 
. Click *Create cluster*, then click *Create Dedicated cluster*.
+
Enter a cluster name, and select the provider (AWS or GCP), region, availability zone type (single AZ or multi AZ) and zones, throughput tier, and Redpanda version.
+
[NOTE]
====
* If you plan to create a private network in your own VPC, select the region where your VPC is located.
* Three availability zones provide two backups in case one availability zone goes down.
* The xref:deploy:deployment-option/cloud/cloud-overview.adoc#cluster-tiers[tier] specifies the expected throughput for your cluster, including the maximum ingress, egress, partitions, and connections. 
====

. Click *Next*.
. On the Network page, enter the connection type: *Public* or *Private*.
+
Private networks require a VPC peering connection. See xref:./vpc-peering.adoc[Add a Dedicated VPC Peering Connection] to connect your VPC to the Redpanda Cloud VPC.

. Click *Create*.
+
After the cluster is created, you can click the cluster name on the *Home* page to see the overview for it.
