= Create a BYOC Cluster on AWS
:description: Use the Redpanda Cloud UI to create a BYOC cluster.

To create a Redpanda cluster in your own cloud, log in to the Redpanda Cloud UI and create a namespace, then follow the steps for creating a Bring your own cloud (BYOC) cluster.

== Create a namespace

To prepare to deploy a Redpanda cluster in your own cloud, log in to the Redpanda Cloud UI and add a namespace:

. Go to https://cloudv2.redpanda.com[Redpanda Cloud] and click *Log in*.
+
The Enter Organization page opens.

. Type your organization name and click *Continue*.
+
The Home page opens.

. Click *Add namespace*.
+
Namespaces help you organize clusters by owner, team, or project for example.

. Type a name for your namespace.

== Create a BYOC cluster

After you create a namespace, create a BYOC cluster in your Virtual Private Cloud (VPC):

. Scroll to your namespace (namespaces are listed in alphabetical order) and click *+ Add Cluster*.
. Click *Create BYOC cluster*.
. (Optional) In *Cluster name*, type a name to replace the default name.
. Select throughput.
+
The choices are 1 MBps, 5 MBps, 10 MBps, and 20 MBps.

. Open the *Redpanda version* menu and select a version.
. Click *Next*.
+
The *Cloud settings* page opens.

. For *Provider*, select AWS.
. Open the *Region* menu and select a region.
. Open the *Zones* menu and select three availability zones for your region.
+
Three availability zones provide two backups in case one availability zone goes down.

. Click *Next*.
+
The *Networking* page opens.

. Under *Choose Connection Type*, select either *Public* or *Private*.
. Click *Next*.

After the network is created, you can deploy the agent.

== Deploy the agent

To deploy the agent, you need to prepare your deployment environment, then copy the `rpk plugin install` command into your environment and run it.

=== Prerequisites

Before you deploy a BYOC cluster in your VPC, satisfy the following prerequisites:

* Install the Redpanda CLI (`rpk`) in your deployment environment.
* Ensure your deployment environment has the necessary AWS environment variables to authenticate to the account you are deploying to. Use either:
 ** `AWS_PROFILE`, or
 ** `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`
* Ensure that your role has the necessary permissions to run commands and create clusters.

=== Install the BYOC rpk plugin

To install the BYOC `rpk` plugin in your cloud, copy the command in the text box and paste it into your development environment. This command contains the values you supplied in the settings pages, along with information provided by the system, such as `organization_id` and `redpanda_id`.
