= Create a BYOC Cluster on AWS
:description: Use the Redpanda Cloud UI to create a BYOC cluster on AWS.
:page-aliases: cloud:create-byoc-cluster-aws.adoc
:page-cloud: true

To create a Redpanda cluster in your virtual private cloud (VPC), log in to the Redpanda Cloud UI
and create a namespace, then follow the steps to create a Bring Your Own Cloud
(BYOC) cluster.

== Create a namespace

include::partial$cloud/create-namespace.adoc[]

== Create a BYOC cluster

. On the Home page, select your namespace (namespaces are listed in alphabetical order), and click *Create cluster*.
. Click *Create BYOC cluster*.
+
Enter a cluster name, and select the provider (AWS), region, availability zone type (single AZ or multi AZ) and zones, throughput tier, and Redpanda version.
+
[NOTE]
====
* If you plan to create a private network in your own VPC, select the region where your VPC is located.
* Three availability zones provide two backups in case one availability zone goes down.
* The xref:deploy:deployment-option/cloud/cloud-overview.adoc#cluster-tiers[tier] specifies the expected throughput for your cluster, including the maximum ingress, egress, partitions, and connections. 
====
+ 
Optionally, click *Advanced settings* to specify up to five key-value custom tags. After the cluster is created, the tags are applied to all AWS resources associated with this cluster. For more information, see the https://docs.aws.amazon.com/mediaconnect/latest/ug/tagging-restrictions.html[AWS documentation^].

. Click *Next*.
. On the Network page, enter the connection type: either *Public* or *Private*. For BYOC clusters, *Private* is best-practice.
** Your network name is used in the Redpanda UI to identify this network.
** For a CIDR range, choose one that does not overlap with your existing VPCs or your Redpanda network.
. Click *Next*.
. On the Deploy page, you need to prepare your environment, then run the `rpk plugin install` command in your environment.

As part of agent deployment, Redpanda assigns the permission required to run the agent. For details about these permissions, see xref:./security/authorization/cloud-iam-policies.adoc#aws-iam-policies[AWS IAM policies].

== Next steps

xref:./vpc-peering-aws.adoc[Add a BYOC VPC Peering Connection on AWS]
