= Create a Topic
:description: Learn how to create a topic for a Redpanda Cloud cluster.
:page-aliases: cloud:create-topic.adoc
:page-cloud: true

After you create a cluster, you can create a topic for that cluster.

. From the *Clusters* page, select the cluster where you want to create a topic.
. From the navigation menu, select *Topics*. The *Topics* page displays the current list of topics.

. Click *Create Topic*.
. In *Topic Name*, enter a name for your topic.
. (Optional) For Dedicated and BYOC clusters, you can overwrite the default settings. Defaults are populated from information stored in the broker.
+
[cols="2,2a"]
|===
| Property | Description

| *Partitions*
| The number of partitions for the topic.

| *Replication factor*
| The number of partition replicas for the topic. Three replicas are recommended. The value for this property must meet or exceed the cluster's xref:reference:cluster-properties.adoc#minimum_topic_replication[`minimum_topic_replication`] setting. 

IMPORTANT: While it is possible to modify the replication factor, Redpanda recommends that you do not change the replication factor value without discussing potential outcomes with your Redpanda support or customer success contact. In particular, updating the value for running Redpanda Cloud topics with a replication factor of one is _not_ recommended. If you do so, and data is lost, Redpanda is unable to assist with recovery.

| *Cleanup policy*
| The policy that determines how to clean up old log segments. The default is *delete*.

| *Retention time*
| The maximum length of time to keep messages in a topic. The default is *7 days*.

| *Retention size*
| The maximum size of each partition. If a partition reaches this size and more messages are added, the oldest messages are deleted. The default is *infinite*.
|===
+
Under *Additional Configuration*, you can add more topic properties. See xref:reference:cluster-properties.adoc#topic-and-partition-properties[topic and partition properties].

. Click *Create*.

The *Topics* page adds the topic you created to the list of topics.

