= Create a Topic
:page-aliases: cloud:create-topic.adoc
:description: Learn how to create a topic for a Redpanda Cloud cluster.
:page-cloud: true

After creating a cluster, you can create a topic for that cluster. Topic properties are populated from information stored in the broker. For Dedicated and BYOC clusters, you can optionally overwrite the default settings. 

[cols="2,2a"]
|===
| Property | Description

| *Partitions*
| The number of partitions for the topic.

| *Replication factor*
| The number of partition replicas for the topic. In Redpanda Cloud, the number of topic replicas is set to three. 

IMPORTANT: Redpanda recommends that you do not change the replication factor value without discussing potential outcomes with your Redpanda support or customer success contact. In particular, updating the value for running Redpanda Cloud topics to a replication factor of one is _not_ recommended. If you do so, and data is lost, Redpanda is unable to assist with recovery. 

| *Cleanup policy*
| The policy that determines how to clean up old log segments. The default is *delete*.

| *Retention time*
| The maximum length of time to keep messages in a topic. The default is *7 days*.

| *Retention size*
| The maximum size of each partition. If a partition reaches this size and more messages are added, the oldest messages are deleted. The default is *infinite*.
|===

