= Create a BYOC Cluster on GCP
:description: Use the Redpanda Cloud UI to create a BYOC cluster on GCP.
:page-aliases: cloud:create-byoc-cluster-gcp.adoc
:page-cloud: true

To create a Redpanda cluster in your virtual private cloud (VPC), log in to the Redpanda Cloud UI
and create a namespace, then follow the steps to create a Bring Your Own Cloud
(BYOC) cluster.

NOTE: With standard BYOC clusters, Redpanda manages security policies and resources for your VPC, including subnetworks, service accounts, IAM roles, firewall rules, and storage buckets. For the most security, you can manage these resources yourself with a xref:./vpc-byo-gcp.adoc[customer-managed VPC on GCP].

== Create a namespace

include::partial$cloud/create-namespace.adoc[]

== Create a BYOC cluster

. On the Home page, select your namespace (namespaces are listed in alphabetical order), and click *Create cluster*.
. Click *Create BYOC cluster*.
+
Enter a cluster name, and select the provider (GCP), region, availability zone type (single AZ or multi AZ) and zones, throughput tier, and Redpanda version.
+
[NOTE]
====
* If you plan to create a private network in your own VPC, select the region where your VPC is located.
* Three availability zones provide two backups in case one availability zone goes down.
* The xref:deploy:deployment-option/cloud/cloud-overview.adoc#cluster-tiers[tier] specifies the expected throughput for your cluster, including the maximum ingress, egress, partitions, and connections. 
====
+ 
Optionally, click *Advanced settings* to specify up to five key-value custom labels. After the cluster is created, the labels are applied to all GCP resources associated with this cluster. For more information, see the https://cloud.google.com/compute/docs/labeling-resources[GCP documentation^].

. Click *Next*.
. On the Network page, enter the connection type: either *Public* or *Private*. For BYOC clusters, *Private* is best-practice.
** Your network name is used in the Redpanda UI to identify this network.
** For a CIDR range, choose one that does not overlap with your existing VPCs or your Redpanda network.
. Click *Next*.
. On the Deploy page, you need to prepare your environment, then log in to Redpanda Cloud and deploy the agent.

Note that `rpk` configures the permissions required by the agent to provision and actively maintain the cluster. For details about these permissions, see xref:./security/authorization/cloud-iam-policies.adoc#gcp-iam-permissions[GCP IAM permissions].

== Next steps

- xref:./vpc-peering-gcp.adoc[Add a BYOC VPC Peering Connection on GCP]
