= Monitor Redpanda Cloud
:description: Learn how to integrate the Redpanda Cloud metrics endpoint to monitor the health of your Dedicated or BYOC clusters.
:page-cloud: true
:env-cloud: true

Redpanda exports metrics through Prometheus endpoints for you to monitor system health and optimize performance for your Redpanda Dedicated or BYOC clusters.

A Redpanda broker exports public metrics from the xref:reference:public-metrics-reference.adoc[`/public_metrics`] endpoint through the Admin API port (default: 9644).

== Configure Prometheus

https://prometheus.io/[Prometheus^] is a system monitoring and alerting tool. It collects and stores metrics as time-series data identified by a metric name and key/value pairs. To monitor a Dedicated or BYOC cluster in Prometheus:

. On the Redpanda Cloud *Overview* page for your cluster, under *How to connect*, click the *Prometheus* tab. 

. Click to copy the Prometheus YAML. This provides the URL, username, password.
+
```
- job_name: redpandaCloud-sample
  static_configs:
    - targets:
        - console-321f60a4.cn6b1srsj6j1mdqdhil0.fmc.ppd.cloud.redpanda.com
  metrics_path: /api/cloud/prometheus/public_metrics
  basic_auth:
    username: prometheus
    password: "%kvjQr^E!xQ+lXqJ~g?5HhZ3"
  scheme: https
```

. Save the configuration file, and restart Prometheus to apply changes.

. Observe in Prometheus that metrics from Redpanda endpoints are scraped.

== Configure DataDog

Other monitoring systems (such as Datadog, New Relic, Elastic Cloud, Google, Azure) can similarly pull from this Prometheus endpoint by taking the URL, user, and password.

For example, DataDog only requires the URL, user, and password. The DataDog agent must be run in a container, and the container must be run in your own container infrastructure. Redpanda does not support launching this container inside a Dedicated or BYOC Kubernetes cluster. See the https://github.com/DataDog/integrations-extras/tree/master/redpanda[Redpanda DataDog integration].

To build the DataDog container with the Redpanda integration, define the `openmetrics_endpoint` URL in the Prometheus tab for that monitored cluster. The integration configuration should look similar to the following:

```
instances:
  # The endpoint to collect metrics about Polaris. Replace ORGANIZATION_NAME with the name of your organization.
  - openmetrics_endpoint: https://console/-<id>.<identifier>.fmc.cloud.redpanda.com/api/cloud/prometheus/public_metrics
    use_openmetrics: true
    collect_counters_with_distributions: true

    auth_type: basic
    username: prom_user
    password: prom_pass
```

[NOTE]
====
To maximize monitoring performance by minimizing the cardinality of data, some metrics are exported when their underlying features are in use, and are not exported when not in use. For example, a metric for consumer groups, xref:reference:public-metrics-reference.adoc#redpanda_kafka_consumer_group_committed_offset[`redpanda_kafka_consumer_group_committed_offset`], is not exported when no groups are registered.
====

== References

* xref:reference:public-metrics-reference.adoc[Public Metrics Reference]
* https://github.com/redpanda-data/observability[Redpanda monitoring examples repository^]