= Cloud Providers and Regions
:description: View supported cloud providers and regions.
:page-cloud: true

When you create a cluster, you select a cloud provider and region. Redpanda Cloud supports the following cloud providers and regions.

_QUESTIONS_

_Do we need to break out Serveless/BYOC/Dedicated, tiers, or zones, as shown https://deploy-preview-297--redpanda-docs-preview.netlify.app/api/cloud-api.html#overview[here]?_

_Which AWS regions does Serverless support?_

_ap-southeast-1 is duplicated (instead of 2) https://docs.api.cloud.redpanda.com/#cmp--schemas-cluster[here]_

== Google Cloud Platform (GCP) regions

* Asia Pacific

** asia-south1
** asia-southeast1
** australia-southeast1

* Europe

** europe-west1
** europe-west2
** europe-west3 (BYOC only)

* United States

** northamerica-northeast1
** us-central1
** us-east1
** us-east4 (BYOC only)

== Amazon Web Services (AWS) regions

* Africa

** af-south-1 (BYOC only)

* Asia Pacific 

** ap-southeast-1
** ap-southeast-2

* Canada

** ca-central-1

* Europe 

** eu-central-1
** eu-west-1

* United States 

** us-east-1
** us-east-2
** us-west-2