= Get Started with Redpanda Cloud on Google Cloud Marketplace
:description: Subscribe to Redpanda through Google Cloud Marketplace to provision Dedicated Cloud clusters.

You can use free credits in Google Cloud Marketplace to provision Dedicated Cloud clusters. When the free credits expire, you can purchase Redpanda through your Google billing account on a pay-as-you-go basis. View your bills and manage your Redpanda subscription directly in Google Cloud Marketplace. 

[NOTE]
====
When you sign up for Redpanda through Google Cloud Marketplace, you can only create clusters on GCP. 
====

. On https://console.cloud.google.com/marketplace[Google Cloud Marketplace^], search for "Redpanda Cloud".

. On the Redpanda Cloud overview page, click **Subscribe**.

. On the pop-up, click **Enable Billing** to associate the subscription with a billing account. 
* If you’re not already registered as an administrator of a Google billing account, click **Create Billing Account** to enter your information. 

. On the Redpanda page: 
* For **Email**, enter your email address to register with Redpanda.
* For **Organization name**, enter a name to bill through Google Cloud Marketplace. Redpanda organizations contain all resources, including clusters and users. 

. On the email sent to that address, click **Verify email address** to complete the registration. 

. Log in to Redpanda Cloud, and then you can create Dedicated Cloud clusters on GCP. 

== QUESTIONS

* Do we need to include billing details, similar to https://docs.confluent.io/cloud/current/billing/overview.html[Confluent]?
