= Get Started with Redpanda Cloud on Google Cloud Marketplace
:description: Subscribe to Redpanda through Google Cloud Marketplace to quickly provision Dedicated Cloud clusters.

You can use free credits in Google Cloud Marketplace to provision Dedicated Cloud clusters. When the free credits expire, you can purchase Redpanda through your Google pay-as-you-go account, based on cluster hours, data ingress and egress, and connector usage. View your bills and manage your Redpanda subscription directly in Google Cloud Marketplace. 

[NOTE]
====
When you sign up for Redpanda through Google Cloud Marketplace, you can only create clusters on GCP. 
====

. On https://console.cloud.google.com/marketplace[Google Cloud Marketplace^], search for "Redpanda SaaS Offering".

. On the Redpanda Cloud overview page, click **Subscribe**.

. On the Redpanda page: 
* For **Email**, enter your email address to register with Redpanda.
* For **Organization name**, enter a name to create a new organization to connect through Google Cloud Marketplace. Redpanda organizations contain all resources, including clusters and users.

. On the email sent to the address you entered, click **Verify email address** to complete the registration. 

. Log in to Redpanda Cloud, and then you can create Dedicated Cloud clusters on GCP. 