= Get Started with Redpanda Cloud on Google Cloud Marketplace
:description: Subscribe to Redpanda through Google Cloud Marketplace to quickly provision Dedicated Cloud clusters.

When you subscribe to Redpanda through Google Cloud Marketplace, you can use your existing GCP billing and credits to provision Dedicated Cloud clusters. Pricing is mapped to the consumption of resources in your organization, including data ingress and egress and storage usage. View your bills and manage your Redpanda subscription directly in Google Cloud Marketplace. 

[IMPORTANT]
====
When you sign up for Redpanda through Google Cloud Marketplace, you can only create clusters on GCP. 
====

== Sign up in Google Cloud Marketplace

. On https://console.cloud.google.com/marketplace[Google Cloud Marketplace^], search for and select "Redpanda SaaS Offering".

. On the Redpanda SaaS Offering overview page, click **Subscribe**.
+
[NOTE]
====
If prompted, click **Enable Billing** to link the subscription with a billing account. If you’re not already registered as an administrator of a Google billing account, also click **Create Billing Account** to enter your information.
====

. On the Order Summary page, the **Pay As You Go** plan using Redpanda consumption units is automatically selected. 
* Read and accept the terms.
* Click **Subscribe**.

. On the Redpanda page: 
* For **Email**, enter your email address to register with Redpanda.
* For **Organization name**, enter a name for your new organization connected through Google Cloud Marketplace. Redpanda organizations contain all resources, including clusters and networks. You can rename the organization name later in Redpanda Console. 
* Click **Sign up and create organization**.

. On the email sent to the address you entered, click **Verify email address**. 
+
This completes the registration and associates the email with a Redpanda account. 

. On the **Accept your invitation to sign up** page, click **Sign up** or **Log in**. 
+
You land on the Home page for your organization in Redpanda. 

== Next steps

xref:./create-dedicated-cloud-cluster-aws.adoc#create-a-dedicated-cluster[Create a Dedicated Cloud cluster on GCP]
