= Get Started with Redpanda Cloud on GCP Marketplace
:description: Learn how to provision Dedicated Cloud clusters on Google Cloud Platform (GCP) Marketplace.

You can use free credits in Google Cloud Platform (GCP) Marketplace to provision Dedicated Cloud clusters. When the free credits expire, you can purchase Redpanda through your GCP account on a pay-as-you-go basis. View your bills and manage your subscription directly in GCP Marketplace. 

[NOTE]
====
When you sign up for Redpanda through GCP Marketplace, you can only create clusters on GCP. 
====

. On the https://console.cloud.google.com/marketplace[GCP Marketplace^], search for `Redpanda Cloud`.

. On the Redpanda Cloud overview page, click **Subscribe**.

. On the pop-up, click **Enable Billing** to associate the subscription with a billing account. 
* If you’re not already registered as an administrator of a billing account, click **Create Billing Account** to enter your information. 

. On the Redpanda page: 
* For **Email**, enter your email address to register with Redpanda.
* For **Organization name**, enter a name to bill through GCP Marketplace. Redpanda organizations contains all resources, including clusters and users. 

. On the email sent to that address, click **Verify email address** to complete the registration. 

. Log in to Redpanda Cloud, and then you can create a Dedicated Cloud cluster on GCP. 

== QUESTIONS

* Do we need to include billing details, similar to https://docs.confluent.io/cloud/current/billing/overview.html[Confluent]?
