= Provision a Serverless Cluster
:description: Learn how to create a Serverless Cloud cluster.
:page-cloud: true
:page-beta: true

Redpanda Serverless is the easiest way to test Kafka API streaming in the cloud: You can start streaming 30 seconds after clicking to create the cluster. Redpanda creates an organization and namespace for your multi-tenant cluster in AWS.

[NOTE]
====
To use our Beta release, Redpanda issues you 100 free credits, which is enough to run Redpanda with reasonable throughput. These credits expire 14 days after you activate your tenant through email verification. To ask questions, give feedback, or extend your trial, use the #serverless https://redpandacommunity.slack.com/[Community Slack^] channel.
==== 

For greater control over your deployment, networking, and cluster settings, or to run production workloads with consistently high throughput, use Redpanda BYOC or Dedicated clusters. 

* Limits, capacity model explained (=address capacity expectations)
* Kafka protocol support
* Supported and unsupported Kafka Ecosystem services (only Kafka API now)
* Pricing model, pricing example.

== Prerequisites

Make sure you have the latest version of `rpk`. See xref:get-started:rpk-install.adoc[].

== Create a Serverless cluster

For the Beta release, you receive an activation email to begin the process. 

. Accept the account activation email. 

. Log in to Redpanda Cloud by running the following command in your terminal:
+
```
rpk cloud login
```

. Follow the CLI output for next steps.

== Manage your cluster

You can interact with your Serverless cluster using `rpk` commands. Here are some userful commands:

* xref:reference:rpk/rpk-cloud/rpk-cloud-login.adoc[`rpk cloud login`]: Use this to log in, or refresh the Redpanda Cloud session.
* xref:reference:rpk/rpk-topic.adoc[`rpk topic`]: Use this to manage topics, produce to, and consume data. 
* xref:reference:rpk/rpk-profile/rpk-profile-print.adoc[`rpk profile print`]: Use this to view `rpk` configuration and the URL for your Serverless cluster.
* xref:reference:rpk/rpk-acl/rpk-acl-user.adoc[`rpk acl user`]: Use this to manage Kafka users and permissions.

== Run a demo application

Redpanda provides code examples to create a topic and produce and consume messages. On the *Overview* page, under *How to connect*, click *Python* or *Node.js* for those examples.

For *Go*, run the following command in your terminal:

```
rpk generate app
```

== Integrate an existing application

To integrate an existing Kafka application in your Serverless cluster:

. Clone your application.
. Update your application to use your Redpanda Serverless cluster.
. Test your application.



