= Provision a Serverless Cluster
:description: Learn how to create a Serverless Cloud cluster.
:page-cloud: true
:page-beta: true

Redpanda Serverless is the easiest way to test event streaming in the cloud: You can start streaming 30 seconds after clicking to create the cluster. 

[NOTE]
====
To use our Beta release, Redpanda issues you enough credits to run Redpanda with reasonable throughput. These credits expire 14 days after you activate your tenant through email verification. For details, see <<Beta credits and limits>>. To ask questions, give feedback, or extend your trial, use the **#serverless** https://redpandacommunity.slack.com/[Community Slack^] channel, or contact https://support.redpanda.com/hc/en-us/requests/new[support^].
==== 

== Prerequisites

. https://redpanda.com/try-redpanda?section=cloud-trial[Sign up for a Beta trial^] of Redpanda Serverless.

. Make sure you have the latest version of `rpk`. See xref:get-started:rpk-install.adoc[].

== Create a Serverless cluster

For the Beta release, you'll receive an email to activate your Serverless trial. 

. In your Welcome email, click to activate your trial. 
+
Redpanda creates an organization and namespace for your multi-tenant Serverless cluster in AWS.

. Log in to Redpanda Cloud by running the following command in your terminal:
+
```
rpk cloud login
```

. Follow the CLI output for next steps.

== Manage your cluster

You can interact with your Serverless cluster in Redpanda Cloud, similar to BYOC and Dedicated clusters. You can add team members and grant them access with ACLs on the **Security** page. 

You can also interact with your Serverless cluster with `rpk` commands. For example:

* xref:reference:rpk/rpk-cloud/rpk-cloud-login.adoc[`rpk cloud login`]: Use this to log in to Redpanda Cloud or to refresh the session.
* xref:reference:rpk/rpk-topic.adoc[`rpk topic`]: Use this to manage topics, and produce and consume data. 
* xref:reference:rpk/rpk-profile/rpk-profile-print.adoc[`rpk profile print`]: Use this to view `rpk` configuration and the URL for your Serverless cluster.
* xref:reference:rpk/rpk-acl/rpk-acl-user.adoc[`rpk acl user`]: Use this to manage users and permissions. 

== Run a demo application

Redpanda provides code examples to create a topic and produce and consume messages. On the *Overview* page, in the *How to connect - Kafka API* tab, click *Python* or *Node.js* for code examples.

For *Go*, run the following command in your terminal:

```
rpk generate app
```

== Integrate an existing application

To integrate an existing Kafka application in your Serverless cluster:

. Clone your application.
. Update your application to use your Serverless cluster.
. Test your application.

== Supported features

Serverless clusters work with all Kafka clients. For more information, see xref:develop:kafka-clients.adoc[].

Serverless clusters support all major Apache Kafka messages for managing topics, producing/consuming data (including transactions), managing groups, managing offsets, and managing ACLs. User management is available in the Redpanda Cloud UI or with `rpk acl`.

The following Kafka messages are supported:

* `Produce`                     
* `Fetch`                     
* `ListOffsets`                 
* `Metadata`                    
* `OffsetCommit`                
* `OffsetFetch`                 
* `FindCoordinator`             
* `JoinGroup`                   
* `Heartbeat`                   
* `LeaveGroup`                  
* `SyncGroup`                   
* `DescribeGroups`              
* `ListGroups`                  
* `SASLHandshake`               
* `ApiVersions`                 
* `CreateTopics`                
* `DeleteTopics`                
* `DeleteRecords`               
* `InitProducerID`              
* `OffsetForLeaderEpoch`        
* `AddPartitionsToTxn`          
* `AddOffsetsToTxn`             
* `EndTxn`                      
* `TxnOffsetCommit`             
* `DescribeACLs`                
* `CreateACLs`                  
* `DeleteACLs`                  
* `DescribeConfigs`             
* `AlterConfigs`                
* `AlterReplicaLogDirs`         
* `DescribeLogDirs`             
* `SASLAuthenticate`            
* `CreatePartitions`            
* `DeleteGroups`                
* `IncrementalAlterConfigs`

== Unsupported features

The following features are not yet supported: 

* Redpanda Admin, HTTP Proxy, and Schema Registry APIs are not yet available. You can use an external schema registry.
* Managed connectors
* Data transforms

To use these features, to run production workloads with consistently high throughput, or for greater control over your deployment and cluster settings, use Redpanda BYOC or Dedicated clusters. 

== Serverless configurations

Redpanda Serverless is opinionated about Kafka configurations, including the following:

* Automatic topic creation is disabled. 
+
Some systems expect the Kafka service to automatically create topics when a message is produced to a topic that doesn't exist. Serverless is opinionated about disabling automatic topic creation. Create topics in the Redpanda Cloud UI or with `rpk topic create`.

* Cleanup policy is delete.
+
Serverless currently doesn't support topic compaction. All Serverless topics have `cleanup.policy = delete`. 

* Uses infinite retention to avoid cleaning up older keys.
+
Frameworks like Kafka Streams and Kafka Connect enforce compaction for the changelog topics. Thus, Serverless can't be used with Kafka Streams (for stateful jobs) or Kafka Connect.

== Beta credits and limits

Redpanda issues 100 free credits for the Beta trial. Usage is based on the following:

* Ingress: 0.1 credit per GB in (writes)
* Egress: 0.1 credit per GB out (reads)
* Partitions: 0.003 credit (metered in 10 min fractions) per partition/hr	
* Storage: 0.1 credit (metered in 10 min fractions) per GB stored/mth	

After either the 14 day trial time expires or the 100 credits expire, the cluster moves into a suspended state, and you won't be able to access your data in the Redpanda Cloud UI or with the Kafka API. There is a 14 day grace period following the end of the trial, in case you want to extend it. After that, the data is permanently deleted. 

Each Beta trial can have five Serverless clusters. Each cluster has the following limits:

* Ingress: up to 10 MBps, 0.5 MBps guaranteed
* Egress: up to 30 MBps, 1.5 MBps guaranteed
* Partitions: 100
* Max message size: 20 MB
* Max retention: unlimited
* Storage: unlimited

For additional clusters or to extend your trial, contact https://support.redpanda.com/hc/en-us/requests/new[support^].
