= Redpanda Terraform Provider
:description: Learn how to use the Redpanda Terraform Provider to create and manage resources in Redpanda Cloud.
:page-cloud: true
:page-beta: true

The https://registry.terraform.io/providers/redpanda-data/redpanda/latest[Redpanda Terraform provider^] interfaces with the Redpanda Cloud API, so you can define your Redpanda infrastructure in Terraform configuration files. You can use the Redpanda Terraform provider to create and manage the following resources:

* ACLs
* Clusters 
* Networks
* Resource groups
* Topics
* Users

See also: https://registry.terraform.io/providers/redpanda-data/redpanda/latest/docs[Terraform Registry^] *(Needs update for beta)*

== Prerequisites

. Install Terraform following the https://learn.hashicorp.com/tutorials/terraform/install-cli[Terraform documentation^].
. Clone the https://github.com/redpanda-data/terraform-provider-redpanda[`terraform-provider-redpanda` Github repository^]:
+
[,bash]
----
git clone https://github.com/redpanda-data/terraform-provider-redpanda.git
----

. Change into the directory:
+
[,bash]
----
cd terraform-provider-redpanda
----

== Limitations

*(Confirm limitations; e.g., is it supported on Serverless and Azure? What functionality is supported in Cloud API that the provider does not support, like Connectors)*

== Set up the provider

To configure the provider, reference `redpanda-data/redpanda` as a provider in your Terraform file:

----
terraform {
  required_providers {
    redpanda = {
      source  = "redpanda-data/redpanda"
      version = "~> 0.5.1"
    }
  }
}
----

This instructs Terraform to install the Redpanda provider. 

=== Authenticate

For the Redpanda Terraform provider to authenticate against Redpanda Cloud, enter your client credentials (`client_id` and `client_secret`) in your Terraform file or set them as environment variables:

[tabs]
======
Static credentials::
+
--

```
provider "redpanda" {
  client_id      = "<client_id>"
  client_secret  = "<client_secret>"
}
```

--
Environment variables::
+
--

```
REDPANDA_CLIENT_ID=<CLIENT_ID>
REDPANDA_CLIENT_SECRET=<CLIENT_SECRET>
```

--
======

== Use the Terraform provider

You can use the Terraform provider to manage data resources in existing Redpanda Cloud clusters. You must use data sources and reference the existing cluster using the cluster ID (Redpanda ID). 

For example, to create a topic in a cluster with ID `foo-bar-baz`:

```
data "redpanda_cluster" "test" {
  id = "foo-bar-baz"
}

resource "redpanda_topic" "test" {
  name               = "myTopicName"
  partition_count    = 3
  replication_factor = 3
  cluster_api_url    = data.redpanda_cluster.test.cluster_api_url
}
```

Note that the `redpanda_topic` resource contains a field `cluster_api_url` that references the `data.redpanda_cluster.test.cluster_api_url` data resource. 

See also the https://github.com/redpanda-data/terraform-provider-redpanda/tree/main/examples[Redpanda Terraform Provider examples^], including the https://github.com/redpanda-data/terraform-provider-redpanda/blob/main/examples/datasource/main.tf[data source example^].