= Redpanda Terraform Provider
:description: Learn how to use the Redpanda Terraform provider to create and manage resources in Redpanda Cloud.
:page-cloud: true
:page-beta: true

The https://registry.terraform.io/providers/redpanda-data/redpanda/latest[Redpanda Terraform provider^] interfaces with the Cloud API, so you can define your Redpanda infrastructure in Terraform configuration files. You can use the Terraform provider to create and manage the following resources in Redpanda Cloud:

* ACLs
* Clusters 
* Networks
* Resource groups
* Topics
* Users

== Prerequisites

Install Terraform following the https://learn.hashicorp.com/tutorials/terraform/install-cli[Terraform documentation^].

== Limitations

*?? TO REVIEWERS: Can you please confirm that the provider is supported on Serverless and Azure? And what functionality is supported in Cloud API but not provider, like Connectors?*

== Use the provider

. To install the Redpanda provider, copy and paste the following code into your Terraform configuration file:
+
```
terraform {
  required_providers {
    redpanda = {
      source  = "redpanda-data/redpanda"
      version = "~> 0.5.1"
    }
  }
}
```

. Initialize Terraform:
+
```
terraform init
```

. For the provider to authenticate against Redpanda Cloud, enter your `client_id` and `client_secret` credentials in your Terraform configuration file or set them as environment variables:
+
[tabs]
======
Static credentials::
+
--

```
provider "redpanda" {
  client_id      = "<client_id>"
  client_secret  = "<client_secret>"
}
```

--
Environment variables::
+
--

```
REDPANDA_CLIENT_ID=<client_id>
REDPANDA_CLIENT_SECRET=<client_secret>
```

--
======

. For sample configurations, see the https://registry.terraform.io/providers/redpanda-data/redpanda/latest/docs[Redpanda Terraform provider docs^]. *NOTE TO REVIEWERS: This linked doc needs update for beta*

=== Use the provider to create a new cluster

For an example of how to use the provider to create a new cluster, see https://github.com/redpanda-data/terraform-provider-redpanda/blob/main/examples/cluster/aws/main.tf[this example^].

=== Use the provider to manage an existing cluster

To manage resources in existing Redpanda Cloud clusters, you must reference the existing cluster using the cluster ID (Redpanda ID). The following example creates a topic in a cluster with ID `foo-bar-baz`. The `redpanda_topic` resource contains a field `cluster_api_url` that references the `data.redpanda_cluster.test.cluster_api_url` data resource. 

```
data "redpanda_cluster" "test" {
  id = "foo-bar-baz"
}

resource "redpanda_topic" "test" {
  name               = "myTopicName"
  partition_count    = 3
  replication_factor = 3
  cluster_api_url    = data.redpanda_cluster.test.cluster_api_url
}
```

=== Additional examples

To see more ways to use the provider, see the https://github.com/redpanda-data/terraform-provider-redpanda/tree/main/examples[Redpanda Terraform provider examples^].