= What's New in Redpanda Cloud
:description: Summary of new features in Redpanada Cloud releases.
:page-cloud: true
:page-toclevels: 1

This topic lists new features added in Redpanda Cloud.

== March 2024

=== Serverless: limited availability

xref:deploy:deployment-option/cloud/serverless.adoc[Redpanda Serverless] moved out of beta and into limited availability (LA). This means that it has usage limits and no public SLA. During LA, existing clusters can scale to the usage limits, but new clusters may need to wait for availability. Serverless is the fastest and easiest way to start data streaming. It is a production-ready deployment option with automatically-scaling clusters available instantly. To start using Serverless, https://redpanda.com/try-redpanda/cloud-trial#serverless-trial[sign up for a free trial^]. This is no base cost, and with pay-as-you-go billing after the trial, you only pay for what you consume. 

=== Authentication with SSO

Redpanda Cloud now supports OpenID Connect (OIDC) integration, so administrators can leverage existing identity providers for user authentication to your Redpanda organization with xref:deploy:deployment-option/cloud/security/cloud-authentication.adoc#single-sign-on[single sign-on] (SSO). Redpanda uses OIDC to delegate the authentication process to an external IdP, such as Okta. To enable this for your account, contact https://support.redpanda.com/hc/en-us/requests/new[Redpanda support^].

== February 2024

=== AWS PrivateLink

xref:deploy:deployment-option/cloud/aws-privatelink.adoc[AWS PrivateLink] is now available as an easy and highly secure way to connect to Redpanda Cloud from your VPC. You can set up the PrivateLink endpoint service for a new cluster or an existing cluster. To enable AWS PrivateLink for your account, contact https://support.redpanda.com/hc/en-us/requests/new[Redpanda support^].

=== Additional cloud tiers

When you create a cluster, you select a xref:deploy:deployment-option/cloud/cloud-overview.adoc#cluster-tiers[cloud tier] with the expected throughput for your cluster, including the maximum ingress, egress, partitions, and connections. On February 5, Redpanda added tiers 6 and 7 for BYOC clusters, which provide higher throughput limits.

== January 2024

=== Usage-based billing in marketplace

Redpanda Cloud now supports xref:deploy:deployment-option/cloud/manage-billing/index.adoc[usage-based billing] for Dedicated Cloud clusters. Contact https://redpanda.com/try-redpanda?section=enterprise-trial[Redpanda sales^] to request a private offer for monthly or annual committed use. You can then use existing Google Cloud Marketplace or AWS Marketplace credits to quickly provision Dedicated Cloud clusters, and you can view your bills and manage your subscription directly in the marketplace.

== December 2023: beta

=== Serverless clusters

xref:deploy:deployment-option/cloud/serverless.adoc[Redpanda Serverless] is a managed streaming service (Kafka API) that completely abstracts users from scaling and operational concerns, and you only pay for what you consume. It's the fastest and easiest way to start event streaming in the cloud. You can try the beta release of Redpanda Serverless with a free trial. 

== November 2023

=== AWS BYOC support for ARM-based Graviton2

BYOC clusters on AWS now support ARM-based Graviton2 instances. This lowers VM costs and supports increased partition count.

=== Iceberg Sink connector

With the xref:deploy:deployment-option/cloud/managed-connectors/create-iceberg-sink-connector.adoc[managed connector for Apache Iceberg], you can write data into Iceberg tables. This enables integration with the data lake ecosystem and efficient data management for complex analytics.

=== Schema Registry management

In the Redpanda Console UI, you can xref:manage:schema-registry.adoc[perform Schema Registry operations], such as registering a schema, creating a new version of it, and configuring compatibility. The **Schema Registry** page lists verified schemas, including their serialization format and versions. Select an individual schema to see which topics it applies to.

=== Maintenance windows

With maintenance windows, you have greater flexibility to plan upgrades to your cluster. By default, all Redpanda Cloud upgrades take place anytime on Tuesdays. Optionally, on the **Cluster settings** page, you can select a window of specific off-hours for your business for Redpanda to apply updates. Updates may start at any time during that window.
