= What's New in Redpanda Cloud
:description: Summary of new features in Redpanada Cloud releases.
:page-cloud: true

This topic lists new features added in Redpanda Cloud.

== December 2023: Beta

==== Serverless clusters

xref:deploy:deployment-option/cloud/serverless.adoc[Redpanda Serverless] is a managed streaming service (Kafka API) that completely abstracts users from scaling and operational concerns, and you only pay for what you consume. It's the fastest and easiest way to start event streaming in the cloud. You can try the Beta release of Redpanda Serverless with a free trial. 

== November 2023

=== AWS BYOC support for ARM-based Graviton2

BYOC clusters on AWS now support ARM-based Graviton2 instances. This lowers VM costs and supports increased partition count.

=== Iceberg Sink connector

With the xref:deploy:deployment-option/cloud/managed-connectors/create-iceberg-sink-connector.adoc[managed connector for Apache Iceberg], you can write data into Iceberg tables. This enables integration with the data lake ecosystem and efficient data management for complex analytics.

=== Schema Registry management

In the Redpanda Console UI, you can xref:manage:schema-registry.adoc[perform Schema Registry operations], such as registering a schema, creating a new version of it, and configuring compatibility. The **Schema Registry** page lists verified schemas, including their serialization format and versions. Select an individual schema to see which topics it applies to.

=== Maintenance windows

With maintenance windows, you have greater flexibility to plan upgrades to your cluster. By default, all Redpanda Cloud upgrades take place anytime on Tuesdays. Optionally, on the **Cluster settings** page, you can select a window of specific off-hours for your business for Redpanda to apply updates. Updates may start at any time during that window.
