= What's New in Redpanda Cloud
:description: Summary of new features in Redpanada Cloud releases.
:page-cloud: true

This topic lists new features added in Redpanda Cloud. 

== December 2023

==== Serverless - Beta

streaming data system for the developer who doesn't want to worry about systems or deployment.

Redpanda Serverless is the easiest way to start with streaming in Redpanda Cloud: You can create a cluster in and start streaming in about 30 seconds. 

Good fit for:
Notably growing and starter workloads.
Projects that don't saturate a dedicated cluster all the time. 
Spiky workloads (dev environments, systems that get busy just occasionally, workloads that come and go)
Fast and dynamic cluster creation. You can use Serverless cluster as an isolated container for topics. you can surface this in your applications (for tenant isolation, for example).

Consider Redpanda Dedicated or Redpanda BYOC clusters for:
Control over cluster settings
Control over the deployment
Private networking 
Workloads with constantly high throughput 

== November 2023

==== AWS BYOC support for ARM-based Graviton2

BYOC clusters on AWS now support ARM-based Graviton2 instances. This lowers VM costs and supports increased partition count.

==== Iceberg Sink connector

With the xref:deploy:deployment-option/cloud/managed-connectors/create-iceberg-sink-connector.adoc[managed connector for Apache Iceberg], you can write data into Iceberg tables. This enables integration with the data lake ecosystem and efficient data management for complex analytics.

==== Schema Registry management

In the Redpanda Console UI, you can xref:manage:schema-reg/schema-reg-ui.adoc[perform Schema Registry operations], such as registering a schema, creating a new version of it, and configuring compatibility. The **Schema Registry** page lists verified schemas, including their serialization format and versions. Select an individual schema to see which topics it applies to.

==== Maintenance windows

With maintenance windows, you have greater flexibility to plan upgrades to your cluster. By default, all Redpanda Cloud upgrades take place anytime on Tuesdays. Optionally, on the **Cluster settings** page, you can select a window of specific off-hours for your business for Redpanda to apply updates. Updates may start at any time during that window. 
