= rpk redpanda mode
:description: rpk redpanda mode. Enables a default development or production configuration mode for Redpanda.

Enable a default configuration mode. This command changes the local `redpanda.yaml` and enable or disable the tuners based on each mode. For example `prod` enables multiple tuners whereas mode `dev` disable all tuners.

The available modes:

* <<development-mode,Development (dev)>>
* <<production-mode,Production (prod)>>

== Development mode

Development (dev) mode includes the following development-only settings:

* Sets `developer_mode` to `true`. This starts Redpanda with dev-mode only settings, including:
 ** No minimal memory limits are enforced.
 ** No core assignment rules for Redpanda nodes are enforced.
 ** Bypasses `fsync` (from https://docs.seastar.io/master/structseastar_1_1reactor%5F%5Foptions.html#ad66cb23f59ed5dfa8be8189313988692[Seastar option `unsafe_bypass_fsync`]), which results in unrealistically fast clusters and may result in data loss.
* Sets `overprovisioned` to `true`. Redpanda expects a dev system to be an overprovisioned environment. Based on a https://docs.seastar.io/master/structseastar_1_1reactor%5F%5Foptions.html#a0caf6c2ad579b8c22e1352d796ec3c1d[Seastar option], setting `overprovisioned` disables thread affinity, zeros idle polling time, and disables busy-poll for disk I/O.
* Sets all autotuner xref:rpk/rpk-redpanda/rpk-redpanda-tune-list.adoc#tuners[tuners] to `false`. The tuners are intended to run only for production mode.
+
.Enabled features in development mode
[%collapsible]
====
Enabling development (dev) mode sets the following features:

```
redpanda:
...
  developer_mode: true
rpk:
  tune_network: false tune_disk_scheduler: false
  tune_disk_nomerges: false
  tune_disk_write_cache: false
  tune_disk_irq: false tune_cpu: false
  tune_aio_events: false
  tune_clocksource: false
  tune_swappiness: false
  tune_ballast_file: false
  overprovisioned: true
....
```
====

== Production mode

Production (prod) mode disables dev-mode settings:

* `developer_mode: false`
* `overprovisioned: false`

It also enables a set of tuners of the autotuner. For descriptions about the tuners, see xref:rpk/rpk-redpanda/rpk-redpanda-tune-list.adoc#tuners[Tuners] in the xref:rpk/rpk-redpanda/rpk-redpanda-tune-list.adoc[rpk redpanda tune list] command reference.

.Enabled features in production mode
[%collapsible]
====
Enabling production (prod) mode sets the following features:

```yaml
redpanda:
  developer_mode: false
rpk:
  tune_network: true
  tune_disk_scheduler: true
  tune_disk_nomerges: true
  tune_disk_write_cache: true
  tune_disk_irq: true tune_cpu: true
  tune_aio_events: true
  tune_clocksource: true
  tune_swappiness: true
  tune_ballast_file: true
  overprovisioned: false
```
====

== Usage

[,bash]
----
rpk redpanda mode <mode> [flags]
----

== Flags

[cols=",,",]
|===
|*Value* |*Type* |*Description*

|--config |string |Redpanda config file, if not set the file will be
searched for in the default locations.

|-h, --help |- |Help for mode.

|-v, --verbose |- |Enable verbose logging (default `false`).
|===
