= rpk redpanda start
:description: rpk redpanda start

Start Redpanda.

== Setting up a mode

It's possible to setup a mode for redpanda to start. Currently we support the mode `dev-container`.

To set up the mode `dev-container` run:

----
rpk redpanda start --mode dev-container
----

Mode uses well-known configuration properties for development or tests
environments:

Bundled flags:

* `--overprovisioned`
* `--reserve-memory 0M`
* `--check=false`
* `--unsafe-bypass-fsync`

Bundled cluster properties:

* `auto_create_topics_enabled: true`
* `group_topic_partitions: 3`
* `storage_min_free_bytes: 10485760 (10MiB)`
* `topic_partitions_per_shard: 1000`
* `fetch_reads_debounce_timeout: 10`

After redpanda starts you can modify the cluster properties using:

----
rpk config set <key> <value>
----

== Usage

----
rpk redpanda start [flags]
----

== Flags


[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|--advertise-kafka-addr |strings |A comma-separated list of Kafka
addresses to advertise (<name>://<host>:<port>).

|--advertise-pandaproxy-addr |strings |A comma-separated list of
Pandaproxy addresses to advertise (<name>://<host>:<port>).

|--advertise-rpc-addr |string |The advertised RPC address
(<host>:<port>).

|--check |- |When set to false will disable system checking before
starting redpanda (default `true`).

|--config |string |Redpanda config file, if not set the file will be
searched for in the default locations.

|-h, --help |- |Help for start.

|--install-dir |string |Directory where redpanda has been installed.

|--kafka-addr |strings |A comma-separated list of Kafka listener
addresses to bind to (<name>://<host>:<port>).

|--mode |string |Mode sets well-known configuration properties for
development or test environments; use `--mode help` for more info.
Currently we support `dev-container` mode. To enable the dev-container
mode, run `rpk redpanda start --mode dev-container`.

|--node-id |int |The node ID. Must be an integer and must be unique
within a cluster.

|--pandaproxy-addr |strings |A comma-separated list of Pandaproxy
listener addresses to bind to (<name>://<host>:<port>).

|--rpc-addr |string |The RPC address to bind to (<host>:<port>).

|--schema-registry-addr |strings |A comma-separated list of Schema
Registry listener addresses to bind to (<name>://<host>:<port>).

|-s, --seeds |strings |A comma-separated list of seed node addresses
(<host>[:<port>]) to connect to.

|--timeout |duration |The maximum time to wait for the checks and tune
processes to complete. The value passed is a sequence of decimal
numbers, each with optional fraction and a unit suffix, such as
`300ms`, `1.5s` or `2h45m`. Valid time units are `ns`, `us`
(or `µs`), `ms`, `s`, `m`, `h` (default 10s).

|--tune |- |When present will enable tuning before starting `redpanda`

|--well-known-io |string |The cloud vendor and VM type, in the format
<vendor>:<vm type>:<storage type>.

|-v, --verbose |- |Enable verbose logging (default `false`).
|===

