= rpk redpanda config bootstrap
:unsupported-os: macOS, Windows

include::reference:partial$unsupported-os-rpk.adoc[]

Initialize the configuration to bootstrap a cluster.

This command generates a `redpanda.yaml` configuration file to bootstrap a
cluster. If you are modifying the configuration file further, it is recommended
to first bootstrap and then modify. If the file already exists, this command
will set fields as requested by flags, and this may undo some of your earlier
edits.

The `--ips` flag specifies seed servers (ips, ip:ports, or hostnames) that this
broker will use to form a cluster.

By default, `redpanda` expects your machine to have one private IP address, and
`redpanda` will listen on it. If your machine has multiple private IP addresses,
you must use the `--self` flag to specify which ip `redpanda` should listen on.

The flags `--advertised-kafka` and `--advertised-rpc` specify the advertised addresses that this broker will use to advertise the corresponding listeners. If not set, it will default to the private IP address or the one specified with the `--self` flag.

== Usage

[,bash]
----
rpk redpanda config bootstrap [--self <ip>] [--ips <ip1,ip2,...>] [flags]
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|--advertised-kafka |string |Optional <address>:<port> for Redpanda to advertise the kafka listener; if empty, defaults to `--self`.

|--advertised-rpc |string |Optional <address>:<port> for Redpanda to advertise the rpc listener; if empty, defaults to `--self`.

|-h, --help |- |Help for bootstrap.

|--ips |strings |Comma-separated list of the seed node addresses or
hostnames; at least three are recommended.

|--self |string |Optional IP address for redpanda to listen on; if
empty, defaults to a private address.

|--config |string |Redpanda or rpk config file; default search paths are `/var/lib/redpanda/.config/rpk/rpk.yaml`, `$PWD/redpanda.yaml`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override `rpk` configuration settings. See xref:reference:rpk/rpk-x-options.adoc[`rpk -X`] or execute `rpk -X help` for inline detail or `rpk -X list` for terser detail.

|--profile |string |Profile to use. See xref:reference:rpk/rpk-profile.adoc[`rpk profile`] for more details.

|-v, --verbose |- |Enable verbose logging.
|===

