= Converters and Serialization 
:description: Learn about converters that handle serialization and deserialization of data between a Redpanda topic and a managed connector.
:page-cloud: true

== Key and value converters

Each Redpanda message is a key and value record. Converters handle serialization and deserialization of data between a Redpanda topic and a connector. Record key and value converters are configured separately. This can be specified with the `Redpanda message key format` and `Redpanda message value format` properties. Key and value converters can be different.

[NOTE]
====
If an external system requires structured data (like BigQuery or SQL database), you must provide data with schema. Then you need to use the Avro, Protobuf, or or JSON converter with schema.
====

== ByteArray converter

The ByteArray converter is the most primitive and high-throughput converter. Schema is ignored.
It is a default converter type in Managed Connectors. 

To use the converter, select the `ByteArray` option as a key or value message format.

== String converter

The String converter is a high-throughput converter. Schema is ignored. All data is converted to a string.

To use the converter, select the `String` option as a key or value message format.

== JSON converter

JSON converter can be specified by selecting the `JSON` option as a key or value message format.
The connector needs a message schema to check message format.

The converter supports JSON schema embedded in the message, where each message contains a schema. It results in a bigger message size. Example JSON message with embedded schema:

[source,json]
----
{
  "schema": {
    "type": "struct",
    "fields": [
      {
        "type": "int64",
        "optional": false,
        "field": "person_id"
      },
      {
        "type": "string",
        "optional": false,
        "field": "name"
      }
    ]
  },
  "payload": {
    "person_id": 1,
    "name": "Redpanda"
  }
}
----

If you consume JSON data with no message schema, the schema check for the connector must be disabled with the `Message key JSON contains schema` or `Message value JSON contains schema` option.

== Avro converter

Avro converter requires schema in Schema Registry.

See also: xref:manage:schema-reg/schema-reg-overview.adoc[Redpanda Schema Registry].

== CloudEvents converter

CloudEvents converter is specific to Debezium PostgreSQL and MySQL source connectors. 

See also: https://debezium.io/documentation/reference/2.2/integrations/cloudevents.html[CloudEvents Converter official documentation^]

== Protobuf converter {badge-cloud-beta}

Protobuf converter requires schema in Schema Registry.
Currently the converter supports sink connectors only.
It works only for primitive types (numbers, boolean, string) and enum types.

To use the converter, select the `Protobuf` option as a key or value message format.

See also: xref:manage:schema-reg/schema-reg-overview.adoc[Redpanda Schema Registry].
