= Managed Connectors
:description: Connectors provide a framework for streaming data into and out of Redpanda.
:page-layout: index
:page-aliases: cloud:managed-connectors/index.adoc, cloud:managed-connectors/index/index.adoc
:page-cloud: true
:page-categories: Deployment, Integration

Redpanda connectors provide a way to integrate your Redpanda data with different
data systems. As managed solutions, connectors offer a simpler way to integrate
your data than manually creating a solution with the Kafka API. You can set up
and manage these connectors in Redpanda Console. All connectors are managed by
Redpanda.

Each connector is either a source or a sink:

* A source connector imports data from a source system into a Redpanda cluster.
The source could be a cloud storage system such as S3 or GCS. The source connector's
main task is to fetch data from these sources and convert them into a format
suitable for Redpanda.
* A sink connector exports data from a Redpanda cluster and pushes it into a
target system. The target could be a cloud storage system such as S3 or GCS.
Sink connectors read the data from Redpanda and transform it into a format
that the target system can use.

These sources and sinks work together to create a data pipeline that can move and transform data from one system to another.
