[[bootstrapping]]
= Bootstrap broker configurations

Each broker requires a set of broker configurations that determine how all brokers communicate with each other and with clients. Bootstrapping a cluster configures the listener addresses and advertised addresses, which ensure proper network connectivity and accessibility.

Use the xref:reference:rpk/rpk-redpanda/rpk-redpanda-config-bootstrap.adoc[`rpk redpanda config bootstrap`] command to bootstrap Redpanda:

[,bash]
----
sudo rpk redpanda config bootstrap --self <listener-address> --ips <seed-server-ips> && \
sudo rpk redpanda config set redpanda.empty_seed_starts_cluster false
----

Replace the following placeholders:

* `<listener-address>`: The `--self` flag tells Redpanda the interfaces to bind to for the Kafka API, the RPC API, and the Admin API. These addresses determine on which network interface and port Redpanda listens for incoming connections.

** Set the listener address to `0.0.0.0` to listen on all network interfaces available on the machine.
** Set the listener address to a specific IP address to bind the listener to that address, restricting connections to that interface.
* `<seed-server-ips>`: The `--ips` flag lists all the seed servers in the cluster, including the one being started. Seed servers correspond to the `seed_servers` property in `redpanda.yaml`.
+
NOTE: The `--ips` flag must be set _identically_ (with nodes listed in identical order) on each node.

[IMPORTANT]
====
* Redpanda strongly recommends at least three seed servers when forming a cluster. A larger number of seed servers increases the robustness of consensus and minimizes any chance that new clusters get spuriously formed after brokers are lost or restarted without any data.
* It's important to have one or more seed servers in each fault domain (such as rack or cloud AZ). A higher number provides a stronger guarantee that clusters don't fracture unintentionally.
* It's possible to change the seed servers for a short period of time after a cluster has been created. For example, you may want to designate one additional broker as a seed server to increase availability. To do this without cluster downtime, add the new broker to xref:reference:node-properties.adoc[`seed_servers`] and restart Redpanda to apply the change on a broker-by-broker basis.
====

After bootstrapping Redpanda, your `/etc/redpanda/redpanda.yaml` configuration file will be updated to include your seed servers and listener addresses.

.`/etc/redpanda/redpanda.yaml`
[source,yaml]
----
redpanda:
    data_directory: /var/lib/redpanda/data
    empty_seed_starts_cluster: false
    seed_servers:
        - host:
            address: <seed-server-ip>
            port: 33145
        - host:
            address: <seed-server-ip>
            port: 33145
        - host:
            address: <seed-server-ip>
            port: 33145
    rpc_server:
        address: 0.0.0.0
        port: 33145
    kafka_api:
        - address: 0.0.0.0
          port: 9092
    admin:
        - address: 0.0.0.0
          port: 9644
    advertised_rpc_api:
        address: 127.0.0.1
        port: 33145
    advertised_kafka_api:
        - address: 127.0.0.1
          port: 9092
----

== Update the advertised addresses

Advertised addresses are communicated to clients and other brokers, acting as the endpoints for establishing connections to the Redpanda cluster. Each broker must have a unique advertised address that reflects how it can be reached across the network. This setup is crucial for enabling both internal and external clients to connect to the cluster effectively.

For brokers accessible on the public internet, you might use the broker's public IP address as its advertised address. For brokers in a private network, using the broker's private IP address as the advertised address minimizes exposure to the broader internet, enhancing security.

Configuring advertised addresses ensures that all clients, regardless of their location, can connect to the Redpanda cluster.

By default, <<bootstrapping>> sets the advertised addresses to `127.0.0.1` (localhost). This configuration will not work if you have more than one broker because each broker must advertise a unique address.

Set the `advertised_rpc_api` and `advertised_kafka_api` addresses to public or private IP addresses for the broker.

- Use public IP addresses for external clients or nodes.
- Use private IP addresses for internal network connectivity.

[source,yaml]
----
redpanda:
  advertised_kafka_api:
    - address: <ip-address>
      port: 9092
  advertised_rpc_api:
    address: <ip-address>
    port: 33145
----

== Listeners for mixed environments

In environments where a Redpanda cluster needs to serve both internal services within a secure private network and external clients over the public internet, you can configure multiple listeners for the Kafka API. This setup allows you to specify different interfaces and ports for internal and external traffic.

For more details, see xref:manage:security/listener-configuration.adoc[].