= Install Redpanda

Install Redpanda on each system you want to be part of your cluster. There are binaries available for Fedora/RedHat or Debian systems.

Unless you intend to run Redpanda in FIPS-compliance mode, the following packages should accommodate your needs (for both Debian and Redhat based systems):

`redpanda`

- Contains the Redpanda application and all supporting libraries
- Depends on `redpanda-tuners` and either `redpanda-rpk` or `redpanda-rpk-fips`

`redpanda-rpk`

- Contains the pure GoLang compiled `rpk` application
- If you wish to use `rpk` only, then this is the only required install package

`redpanda-tuners`

- Contains the files used to run Redpanda tuners
- Depends on `redpanda-rpk` or `redpanda-rpk-fips`


[tabs]
=====
Fedora/RedHat::
+
--
[,bash]
----
curl -1sLf 'https://dl.redpanda.com/nzc4ZYQK3WRGd9sy/redpanda/cfg/setup/bash.rpm.sh' | \
sudo -E bash && sudo yum install redpanda -y
----

[IMPORTANT]
====
To install a version of Redpanda that is older than the latest available version, you must also specify each dependency. For example, if installing `24.3.1~rc1-1` and you fail to specify each package and its version, you may encounter the following error:

[source,bash]
----
yum install redpanda=24.3.1~rc1-1
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 redpanda : Depends: redpanda-rpk (= 24.3.1~rc1-1) but it is not going to be installed or
                     redpanda-rpk-fips (= 24.3.1~rc1-1) but it is not going to be installed
            Depends: redpanda-tuner (= 24.3.1~rc1-1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
----
To troubleshoot this error, specify the full list of versions for each package. In this case:

[source,bash]
----
yum install \
  redpanda-tuner=24.3.1~rc1-1 \
  redpanda-rpk=24.3.1~rc1-1 \
  redpanda=24.3.1~rc1-1
----
====

--
Debian/Ubuntu::
+
--
[,bash]
----
curl -1sLf 'https://dl.redpanda.com/nzc4ZYQK3WRGd9sy/redpanda/cfg/setup/bash.deb.sh' | \
sudo -E bash && sudo apt install redpanda -y
----

[IMPORTANT]
====
To install a version of Redpanda that is older than the latest available version, you must also specify each dependency. For example, if installing `24.3.1~rc1-1` and you fail to specify each package and its version, you may encounter the following error:

[source,bash]
----
apt install redpanda=24.3.1~rc1-1
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 redpanda : Depends: redpanda-rpk (= 24.3.1~rc1-1) but it is not going to be installed or
                     redpanda-rpk-fips (= 24.3.1~rc1-1) but it is not going to be installed
            Depends: redpanda-tuner (= 24.3.1~rc1-1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
----
To troubleshoot this error, specify the full list of versions for each package. In this case:

[source,bash]
----
apt install \
  redpanda-tuner=24.3.1~rc1-1 \
  redpanda-rpk=24.3.1~rc1-1 \
  redpanda=24.3.1~rc1-1
----
====
--
=====

