= Install Redpanda

Install Redpanda on each system you want to be part of your cluster. There are binaries available for Fedora/RedHat or Debian systems.

Unless you intend to run Redpanda in FIPS-compliance mode, the following packages should accommodate your needs (for both Debian and Redhat based systems):

`redpanda`

- Contains the Redpanda application and all supporting libraries
- Depends on `redpanda-tuners` and either `redpanda-rpk` or `redpanda-rpk-fips`

`redpanda-rpk`

- Contains the pure GoLang compiled `rpk` application
- If you wish to use `rpk` only, then this is the only required install package

`redpanda-tuners`

- Contains the files used to run Redpanda tuners
- Depends on `redpanda-rpk` or `redpanda-rpk-fips`


[tabs]
=====
Fedora/RedHat::
+
--
[,bash]
----
curl -1sLf 'https://dl.redpanda.com/nzc4ZYQK3WRGd9sy/redpanda/cfg/setup/bash.rpm.sh' | \
sudo -E bash && sudo yum install redpanda -y
----

--
Debian/Ubuntu::
+
--
[,bash]
----
curl -1sLf 'https://dl.redpanda.com/nzc4ZYQK3WRGd9sy/redpanda/cfg/setup/bash.deb.sh' | \
sudo -E bash && sudo apt install redpanda -y
----

--
=====