= Task 4: Add a New Product Component to the Docs Site

In this task, you will create a new product component in the documentation site. This task will help you understand how Antora's modular structure works, and how to add new products or sections to the docs.

== Learning objectives

- Learn how to create new components (products) and integrate them into a documentation site.
- Learn how to modify Antora playbooks to include new content sources.
- Learn how to verify that the new component is correctly displayed in the generated documentation site.

== Prerequisites

Make sure Node.js is installed. You can verify its installation by running:

[source,bash]
----
node --version
----

If Node.js is not installed, https://nodejs.org/[download and install it].

== Steps

. Change into the `task4-add-new-product/` directory.
+
[,bash]
----
cd task4-add-new-product
----

. Install the dependencies:
+
[,bash]
----
npm install
----

. Create a new component directory:
+
.. Create a new directory called `new-product/`.
.. In `new-product/`, create an `antora.yml` file that defines the name of the new product (component), version, the location of the navigation file, and where in the doc header the component should appear.
+
```yml
name: new-product #name of the product for the URL
title: Redpanda Disconnect # name of the product for the UI
version: ~
start_page: ROOT:index.adoc # home page for this product doc set.
nav:
- modules/ROOT/nav.adoc # location of the sidenav doc
asciidoc:
  attributes:
    page-header-data:
      order: 5 # order that the component appears in the header
      color: '#4682B4' # color theme of the header for this product's docs
```

- Create a `modules/ROOT/pages/` directory under `new-product/` and add an introductory page called `index.adoc` and add some content.

. Update the playbook:
+
- Open `playbook.yaml` and add the new component under `content.sources`:
+
```yml
content:
  sources:
    - url: ./new-product
      branches: HEAD
```

. Create the navigation:
+
- Create `new-product/modules/ROOT/nav.adoc`, and define the structure for the new product's documentation. For example:
+
```asciidoc
* xref:ROOT:introduction.adoc[Introduction to New Product]
```

. Build the documentation.
+
- Run the following command to build the documentation:
+
```bash
npm run build
npm run serve
```
- Open the generated site in a browser and verify that the new product is integrated.

== Next steps

xref:../task5-add-new-macro/README.adoc[Task 5: Create a Basic Macro]
