= Manage Redpanda Self-Hosted in Kubernetes
:description: Manage Self-Hosted Redpanda in Kubernetes.

* xref:kubernetes:configure-helm-chart.adoc[Customize the Helm Chart]
+
You can customize the Redpanda Helm chart to configure the cluster and the Kubernetes components that the chart deploys.

* xref:kubernetes:configure-storage.adoc[Storage]
+
Store Redpanda data in PersistentVolumes, hostPath volumes, or emptyDir volumes.

* xref:kubernetes:tiered-storage.adoc[Tiered Storage]
+
Tiered Storage lets you save storage costs by offloading log segments to cloud storage.

* xref:kubernetes:networking:networking-and-connectivity.adoc[Networking and Connectivity]
+
Learn how internal and external connectivity works when Redpanda is running in Kubernetes.

* xref:kubernetes:security.adoc[Security]
+
Configure encryption, authentication, and authorization for production environments.

* xref:kubernetes:kubernetes-rack-awareness.adoc[Rack Awareness]
+
Distribute replicas of the same partition across different racks to minimize data loss in the event of a rack failure.

* xref:kubernetes:remote-read-replicas.adoc[Remote Read Replicas]
+
A Remote Read Replica topic is a read-only topic that mirrors a topic on a different cluster.

* xref:kubernetes:manage-resources.adoc[Pod Resources]
+
Configure your Pod resources such as memory, CPU, and storage.

* xref:kubernetes:troubleshooting:troubleshoot.adoc[Troubleshooting]
+
Find advice on how to diagnose and troubleshoot problems with Redpanda in Kubernetes.
