= Manage Redpanda Self-Hosted in Kubernetes
:description: Manage Self-Hosted Redpanda in Kubernetes.

* xref:kubernetes:configure-helm-chart.adoc[Customize the Helm Chart]
+
Customize the Redpanda Helm chart to configure the cluster and the Kubernetes components that the chart deploys.

* xref:kubernetes:cluster-property-configuration.adoc[Cluster Properties]
+
Learn how to configure cluster properties in Kubernetes.

* xref:kubernetes:configure-storage.adoc[Storage]
+
Store Redpanda data in PersistentVolumes, hostPath volumes, or emptyDir volumes.

* xref:kubernetes:tiered-storage-kubernetes.adoc[Tiered Storage]
+
Tiered Storage lets you save storage costs by offloading log segments to cloud storage.

* xref:kubernetes:networking.adoc[Networking and Connectivity]
+
Learn networking and connectivity options when Redpanda is running in Kubernetes.

* xref:kubernetes:security.adoc[Security]
+
Configure encryption, authentication, and authorization for production environments.

* xref:kubernetes:kubernetes-rack-awareness.adoc[Rack Awareness]
+
Distribute replicas of the same partition across different racks to minimize data loss in the event of a rack failure.

* xref:kubernetes:remote-read-replicas.adoc[Remote Read Replicas]
+
A Remote Read Replica topic is a read-only topic that mirrors a topic on a different cluster.

* xref:kubernetes:manage-resources.adoc[Manage Pod Resources]
+
Configure your Pod resources such as memory, CPU, and storage.

* xref:kubernetes:scale.adoc[Scale]
+
Scaling a Redpanda cluster involves increasing its resources or the number of nodes to handle more data, traffic, and users.

* xref:kubernetes:decommission-brokers.adoc[Decommission Brokers]
+
Remove a broker so that it is no longer considered part of the cluster.

* xref:kubernetes:delete-persistentvolume.adoc[Delete PersistentVolumes]
+
Delete a PersistentVolume to remove a broker and its data from the cluster or to perform maintenance or upgrades on the PersistentVolume.

* xref:kubernetes:rolling-upgrade.adoc[Upgrade Redpanda]
+
Learn how to upgrade Redpanda in Kubernetes.

* xref:kubernetes:upgrade-kubernetes.adoc[Upgrade Kubernetes]
+
Learn how to upgrade Kubernetes on Worker Nodes running Redpanda.

* xref:kubernetes:monitor.adoc[Monitor]
+
Monitor the health of your system to predict issues and optimize performance.

* xref:kubernetes:resilience-testing.adoc[Resilience Testing]
+
Perform resilience testing by introducing failures and observing how the system behaves under each one.

* xref:kubernetes:troubleshooting.adoc[Troubleshooting]
+
Find advice on how to diagnose and troubleshoot problems with Redpanda in Kubernetes.
