= Cluster Configuration
:description: Redpanda cluster configuration general information.

When you install Redpanda software, configuration properties are automatically set to the default values. There are cluster properties, node properties, and topic properties. Some properties can be configured at either the cluster level or the topic level, such as `retention_bytes` (cluster-level) and `retention.bytes` (topic-level). Topic-level properties override cluster-level properties.

=== Cluster properties

Cluster properties are stored internally and automatically replicated across all nodes, which ensures that each node is in sync. Examples of cluster properties include Kafka front-end settings, authentication settings, and settings for enabling features such as xref::tiered-storage.adoc[Tiered Storage] and xref::rack-awareness.adoc[rack awareness]. Most Redpanda configuration properties are cluster properties.

xref:reference:tunable-properties.adoc[Tunable properties] are also considered cluster properties. You should not need to change these default settings for normal operation.

See also:

* xref:reference:cluster-properties.adoc[Cluster configuration properties]
* xref:cluster-maintenance:cluster-property-configuration.adoc[Configure cluster properties]

=== Node properties

Node properties are stored in the `redpanda.yaml` file located in the `/etc/redpanda` directory for each node.

See also:

* xref:reference:node-properties.adoc[Node configuration properties]
* xref:deploy:deployment-option:self-hosted:manual:node-property-configuration.adoc[Configure node properties]
