= Cluster Maintenance
:description: Cluster Maintenance

import ConfigureAvailabilityIntro from './shared/_intro-configure-availability.mdx'

* xref:cluster-maintenance:configuration.adoc[Cluster Configuration]
+
When you install Redpanda software, configuration properties are automatically set to the default values. You can learn more about those properties here.

* xref:cluster-maintenance:cluster-balancing.adoc[Cluster Balancing]
+
When a topic is created, Redpanda evenly distributes its partitions by sequentially allocating them to the node with the least number of partitions. By default, Redpanda provides leadership balancing and partition rebalancing when nodes are added or decommissioned.

* xref:cluster-maintenance:continuous-data-balancing.adoc[Continuous Data Balancing]
+
Continuous Data Balancing continuously monitors your node and rack availability and disk usage. This enables self-healing clusters that dynamically balance partitions, ensuring smooth operations and optimal cluster performance.

* xref:cluster-maintenance:rolling-upgrade.adoc[Upgrade]
+
One of the primary uses for maintenance mode is to perform a rolling upgrade on each node in the cluster. This process involves putting a node into maintenance mode, upgrading the node, taking the node out of maintenance mode, and then repeating the process on the next node in the cluster. Placing nodes into maintenance mode ensures a smooth upgrade of your cluster while reducing the risk of interruption or degradation in service.

* xref:cluster-maintenance:disk-utilization.adoc[Manage Disk Space]
+
Redpanda provides several ways to manage disk space to ensure the production stability of the cluster.

* xref:cluster-maintenance:configure-availability.adoc[Configure Availability]+++<ConfigureAvailabilityIntro>++++++</ConfigureAvailabilityIntro>+++
* xref:cluster-maintenance:cluster-property-configuration.adoc[Cluster Properties]
+
When you install Redpanda software, it automatically generates a cluster configuration with default settings assigned to each cluster property.
  You might want to change some of the default settings, particularly if you plan to use features such as rack awareness or tiered storage, which are disabled by default.
