= CEIL


## Overview

The `CEIL()` function returns the nearest positive or negative integer value greater than or equal to the provided decimal input number.

## Syntax

The syntax of the `CEIL()` function is as follows:

[source,sql]
----
CEIL(x)
----


The `CEIL()` function requires one argument:

*   `x`: A positive or a negative decimal number (or an expression that evaluates to a decimal number).

## Examples

### Case #1: Rounding up a positive decimal value

The following example demonstrates how the `CEIL() `function rounds up a positive decimal value:

[source,sql]
----
SELECT CEIL (300.55);
----


As shown below, it will return 301, as it is the nearest integer value greater than 300.55.

[source,sql]

[cols="1",options="header"]
|===
|f

|301
|===



### Case #2: Rounding up a negative decimal value

The following example demonstrates how the `CEIL() `function rounds up a negative decimal value:

[source,sql]
----
SELECT CEIL(-89.9) AS "Ceil";
----


The output of this statement will be -89, as -89 is the nearest integer value greater than or equal to -89.9, as shown below.

[source,sql]

[cols="1",options="header"]
|===
|Ceil

|-89
|===



### Case #3: Using the `CEIL()` function with a table

The following example demonstrates how the `CEIL()` function can be used with a table to round up the values in a specific column:

. First, create a table called ***CeilRecords*** with the following query:

[source,sql]
----
CREATE TABLE CeilRecords (numbers float);
  
INSERT INTO CeilRecords(numbers) 
VALUES 
    (-28.85),
    (-9.4),
    (0.87),
    (78.16),
    (42.16);
----


The above statement will create a table called **"CeilRecords"** with a column called **"numbers"** and insert 5 decimal values into it.

. The statement below can be used to retrieve and round up the value for all records in the column ***numbers**:

[source,sql]
----
SELECT *, CEIL(numbers) AS CeilValue FROM CeilRecords;
----


The final result will contain the following:

*   A **numbers** column with initial decimal values.

*   A **CeilValue** column with rounded-up integer values.

[source,sql]

[cols="1,1",options="header"]
|===
|numbers |CeilValue

|-28.85 |-28
|-9.4 |-9
|0.87 |1
|78.16 |79
|42.16 |43
|===

