= rpk registry mode set
// tag::single-source[]

Set the mode Schema Registry runs in.

Running this command with no subject sets the global mode for Schema Registry. Alternatively, use the `--global` flag to set the global mode for Schema Registry at the same time as per-subject modes.

Acceptable mode values: 

- `READONLY`

- `READWRITE`


- `IMPORT`

You can only enable `IMPORT` mode on an empty schema registry (if setting mode globally) or an empty subject (if setting at the subject level). Empty means no schemas have ever been registered. Soft deletions are not sufficient — you must hard-delete any existing schemas before enabling `IMPORT` mode. To override this emptiness check, use the `--force` flag.

== Usage

[,bash]
----
rpk registry mode set [SUBJECT...] [flags]
----

== Examples

Set the global schema registry mode to `READONLY`:

[,bash]
----
rpk registry mode set --mode READONLY
----

Set the schema registry mode to `READWRITE` in subjects `<subject-1>` and `<subject-2>`:

[,bash]
----
rpk registry mode set <subject-1> <subject-2> --mode READWRITE
----

Set the schema registry mode to IMPORT, overriding the emptiness check: 

[,bash]
----
rpk registry mode set --mode IMPORT --global --force
----

NOTE: Replace the placeholder values.

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|--force |- |Whether to force setting mode to IMPORT when there are existing schemas.

|--global |- |Set the global schema registry mode in addition to subject modes.

|-h, --help |- |Help for set.

|--mode |string |Schema registry mode to set. Acceptable values: `READONLY`, `READWRITE`, `IMPORT` (case insensitive).

|--format |string |Output format: `json`,`yaml`,`text`,`wide`,`help`. Default: `text`.

|--config |string |Redpanda or `rpk` config file; default search paths are `~/.config/rpk/rpk.yaml`, `$PWD`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override `rpk` configuration settings. See xref:reference:rpk/rpk-x-options.adoc[`rpk -X`] or execute `rpk -X help` for inline detail or `rpk -X list` for terser detail.

|--profile |string |Profile to use. See xref:reference:rpk/rpk-profile.adoc[`rpk profile`] for more details.

|-v, --verbose |- |Enable verbose logging.
|===

// end::single-source[]