= rpk registry compatibility-level set

Set the global or per-subject compatibility levels.

Running this command without a subject sets the global compatibility level. To set the global level at the same time as per-subject levels, use the `--global` flag.

== Concept

=== Levels

- BACKWARD (default): Consumers using the new schema (for example, version 10) can read data from producers using the previous schema (for example, version 9).

- BACKWARD_TRANSITIVE: Consumers using the new schema (for example, version 10) can read data from producers using all previous schemas (for example, versions 1-9).

- FORWARD: Consumers using the previous schema (for example, version 9) can read data from producers using the new schema (for example, version 10).

- FORWARD_TRANSITIVE: Consumers using any previous schema (for example, versions 1-9) can read data from producers using the new schema (for example, version 10).

- FULL: A new schema and the previous schema (for example, versions 10 and 9) are both backward and forward compatible with each other.

- FULL_TRANSITIVE: Each schema is both backward and forward compatible with all registered schemas.

- NONE: No schema compatibility checks are done.


== Usage

[,bash]
----
rpk registry compatibility-level set [SUBJECT...] [flags]
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|--global |- |Set the global level in addition to subject levels.

|-h, --help |- |Help for set.

|--level |string |Level to set, one of `NONE`, `BACKWARD`,`BACKWARD_TRANSITIVE`, `FORWARD`,`FORWARD_TRANSITIVE`, `FULL`, `FULL_TRANSITIVE`.

|--config |string |Redpanda or `rpk` config file; default search paths are `~/.config/rpk/rpk.yaml`, `$PWD`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override `rpk` configuration settings. See xref:reference:rpk/rpk-x-options.adoc[`rpk -X`] or execute `rpk -X help` for inline detail or `rpk -X list` for terser detail.

|--format |string |Output format: `json`,`yaml`,`text`,`wide`,`help`. Default: `text`.

|--profile |string |Profile to use. See xref:reference:rpk/rpk-profile.adoc[`rpk profile`] for more details.

|-v, --verbose |- |Enable verbose logging.
|===