[cols="1m,2a"]
|===
|Field |Description

|
ifdef::env-kubernetes[status]
ifndef::env-kubernetes[License status]
|
Indicates the current state of the license. Possible values include:

* `valid`: The license is active and valid.
* `expired`: The license has expired, and restrictions may apply to enterprise features.
* `not_present`: No license is currently applied.

|
ifdef::env-kubernetes[violation]
ifndef::env-kubernetes[License violation]
|
A boolean value that indicates whether enterprise features are being used in violation of the licensing terms:

* `true`: Enterprise features are enabled without a valid license.
* `false`: No violations are detected.

[NOTE]
====
If the license is in violation, you must either obtain a valid license or disable the enterprise features in use to ensure compliance.
For instructions, see xref:get-started:licensing/disable-enterprise-features.adoc[].
====

|
ifdef::env-kubernetes[organization]
ifndef::env-kubernetes[Organization]
|
The organization for which the license was issued. Typically corresponds to the organization that purchased or activated the license.

If the cluster is less than 30 days old, it has a built-in free trial license. In this case, the organization is set to Redpanda Built-In Evaluation Period.

|
ifdef::env-kubernetes[type]
ifndef::env-kubernetes[Type]
|
The type of license applied to the cluster:

* `enterprise`: A full-featured enterprise license.
* `trial`: A time-limited trial license.
* `free_trial`: A 30-day trial license issued during initial deployment of a cluster.

|
ifdef::env-kubernetes[expiration]
ifndef::env-kubernetes[Expires]
|
The expiration date of the current license. After this date, the license status changes to `expired`.

|
ifdef::env-kubernetes[inUseFeatures]
ifndef::env-kubernetes[Enterprise features in use]
|
A list of enabled enterprise features in the cluster, such as `tiered_storage`, `audit_logging`, and `partition_auto_balancing_continuous`.

NOTE: Enterprise features in use are specific to Redpanda. They do not include enterprise features for xref:get-started:licensing/overview.adoc#connect[Redpanda Connect] or xref:get-started:licensing/overview.adoc#console[Redpanda Console].
|===