= Monitor Data Transforms
:description: This topic provides guidelines on how to monitor the health of your data transforms and view logs.
:page-categories: Development, Stream Processing, Data Transforms

{description}

== Prerequisites

xref:manage:monitoring.adoc[Set up monitoring] for your Redpanda cluster.

== Performance

You can identify performance bottlenecks by monitoring latency and CPU usage:

- xref:reference:public-metrics-reference.adoc#redpanda_transform_execution_latency_sec[`redpanda_transform_execution_latency_sec`]
- xref:reference:public-metrics-reference.adoc#redpanda_wasm_engine_cpu_seconds_total[`redpanda_wasm_engine_cpu_seconds_total`]

If latency is high, investigate the transform logic for inefficiencies or consider scaling the resources. High CPU usage might indicate the need for optimization in the code or an increase in xref:develop:data-transforms/configure.adoc[allocated CPU resources].

== Reliability

Tracking execution errors and error states helps in maintaining the reliability of your data transforms:

- xref:reference:public-metrics-reference.adoc#redpanda_transform_execution_errors[`redpanda_transform_execution_errors`]
- xref:reference:public-metrics-reference.adoc#redpanda_transform_failures[`redpanda_transform_failures`]
- xref:reference:public-metrics-reference.adoc#redpanda_transform_state[`redpanda_transform_state`]

Make sure to xref:develop:data-transforms/build.adoc#errors[implement robust error handling and logging] within your transform functions to help with troubleshooting.

== Resource usage

Monitoring memory usage metrics and total execution time ensures that the Wasm engine does not exceed allocated resources, helping in efficient resource management:

- xref:reference:public-metrics-reference.adoc#redpanda_wasm_engine_memory_usage[`redpanda_wasm_engine_memory_usage`]
- xref:reference:public-metrics-reference.adoc#redpanda_wasm_engine_max_memory[`redpanda_wasm_engine_max_memory`]
- xref:reference:public-metrics-reference.adoc#redpanda_wasm_binary_executable_memory_usage[`redpanda_wasm_binary_executable_memory_usage`]

If memory usage is consistently high or exceeds the maximum allocated memory:

- Review and optimize your transform functions to reduce memory consumption. This step can involve optimizing data structures, reducing memory allocations, and ensuring efficient handling of records.

- Consider increasing the allocated memory for the Wasm engine. Adjust the xref:develop:data-transforms/configure.adoc#resources[`data_transforms_per_core_memory_reservation`] and xref:develop:data-transforms/configure.adoc#resources[`data_transforms_per_function_memory_limit settings`] to provide more memory to each function and the overall Wasm engine.

== Throughput

Keeping track of read and write bytes and processor lag helps in understanding the data flow through your transforms, enabling better capacity planning and scaling:

- xref:reference:public-metrics-reference.adoc#redpanda_transform_read_bytes[`redpanda_transform_read_bytes`]
- xref:reference:public-metrics-reference.adoc#redpanda_transform_write_bytes[`redpanda_transform_write_bytes`]
- xref:reference:public-metrics-reference.adoc#redpanda_transform_processor_lag[`redpanda_transform_processor_lag`]

If there is a significant lag or low throughput, investigate potential bottlenecks in the data flow or consider scaling your infrastructure to handle higher throughput.

== View logs for data transforms

Runtime logs for transform functions are written to an internal topic called `_redpanda.transform_logs`. You can read these logs by using the xref:reference:rpk/rpk-transform/rpk-transform-logs.adoc[`rpk transform logs`] command.

```bash
rpk transform logs <transform-name>
```

Replace `<transform-name>` with the xref:develop:data-transforms/configure.adoc[configured name] of the transform function.

Alternatively, in Redpanda Console, go to *Topics*, and select *Show internal topics* to see `_redpanda.transform_logs` in the topic list. Logs for all transform functions are produced to this topic. To find logs for a specific transform function, search the message keys for the name of the transform function.

By default, Redpanda provides several settings to manage logging for data transforms, such as buffer capacity, flush interval, and maximum log line length. These settings ensure that logging operates efficiently without overwhelming the system. However, you may need to adjust these settings based on your specific requirements and workloads. For information on how to configure logging, see the xref:develop:data-transforms/configure.adoc#log[Configure transform logging] section of the configuration guide.

== Suggested reading

For details about all available metrics, see xref:reference:public-metrics-reference.adoc#data_transform_metrics[Data transforms metrics].