= Upgrade the Data Transforms SDK
:description: Upgrading the SDK version in your data transforms project ensures compatibility with the latest features and fixes. This guide provides step-by-step instructions to upgrade the SDK version for all supported SDK languages.

{description}

== Prerequisites

Before upgrading, check the xref:develop:data-transforms/versioning-compatibility.adoc[compatibility matrix] to ensure the new SDK version is compatible with your Redpanda version.

== Upgrade your local SDK version

[tabs]
======
Go::
+
--
. Open the `go.mod` file in your project's root directory. This file specifies the dependencies for your Go project.

. Locate the line that specifies the data transforms SDK version. It will look something like this:
+
```go-module
require github.com/redpanda-data/redpanda/src/transform-sdk/go v<version>
```

. Change the version to the one you want to upgrade to.

. Run the following command to update the SDK:
+
```bash
go get github.com/redpanda-data/redpanda/src/transform-sdk/go@v<version>
```

. Clean up the `go.mod` and `go.sum` files:
+
```bash
go mod tidy
```

--
Rust::
+
--

. Open the `Cargo.toml` file in your project's root directory. This file specifies the dependencies for your Rust project.

. Locate the line that specifies the Redpanda SDK version. It will look something like this:
+
```toml
[dependencies]
redpanda-transform-sdk = "<version>"
```
. Change the version to the one you want to upgrade to.

. Run the following command to update the dependencies:
+
```bash
cargo update -p redpanda-transform-sdk
```

--
======

== Next steps

Run your xref:develop:data-transforms/test.adoc[tests] to ensure everything works correctly with the new SDK version.