= Versioning and Compatibility for Data Transforms
:description: The data transforms SDKs use semantic versioning to ensure compatibility and stability. Use this guide to learn the SDKs that are compatible with different versions of Redpanda, and what guarantees are provided regarding SDK and Redpanda compatibility.

{description}

== Semantic versioning

The data transforms SDKs use semantic versioning, which is a versioning scheme with a three-part number: `major.minor.patch`. When a new version is released, one part of the version number is changed. The changed part of the version number signifies the level of change:

* *Major*: Indicate breaking changes.
* *Minor*: Indicate backward-compatible functionality.
* *Patch*: Indicate backward-compatible bug fixes.

For example, in the version number `1.2.3`, `1` is the major version, `2` is the minor version, and `3` is the patch version.

== Compatibility matrix

This compatibility matrix provides detailed information on which versions of the SDK are supported with which versions of Redpanda. Always consult the compatibility matrix to ensure that you are using compatible versions.

=== Golang SDK

|===
| Golang SDK Version | Redpanda Version

| 1.0.x       | 24.1.x, 23.3.x
| 0.2.x       | 23.3.x
| 0.1.x       | 23.3.x
|===

=== Rust SDK

|===
| Rust SDK Version | Redpanda Version

| 1.0.x       | 24.1.x, 23.3.x
| 0.2.x       | 23.3.x
| 0.1.x       | 23.3.x
|===


== Backward compatibility

SDK versions will continue to work in the supported versions of Redpanda. However, they may not work in newer versions of Redpanda. Always check the compatibility matrix when upgrading either the SDK or Redpanda.

== Best Practices

- *Stay updated*: Regularly check the <<rn,release notes>> for updates to both the data transform SDK and Redpanda. Ensure that you are using compatible versions as specified in the <<matrix,compatibility matrix>>.

- *Test upgrades*: Before upgrading either the SDK or Redpanda, test the upgrade in a staging environment. This helps ensure that your data transforms continue to work as expected.

- *Monitor logs and metrics*: Watch the logs and metrics to catch any issues early. Ensure that you xref:develop:data-transforms/monitor.adoc[set up monitoring and alerting] to notify you of any problems with your data transforms.

[[rn]]
== Release notes

Release notes for SDK versions are included in the Redpanda release notes. This ensures that all changes related to data transforms and SDKs are documented in one place.

To view the release notes:

1. Visit the https://github.com/redpanda-data/redpanda/releases[Redpanda GitHub releases page].
2. Search for the term `wasm` to filter the release notes for relevant updates to the data transform SDKs.

== Suggested reading

- xref:develop:data-transforms/upgrade.adoc[]
- xref:reference:data-transforms/golang-sdk.adoc[]
- xref:reference:data-transforms/rust-sdk.adoc[]
