ifdef::env-byoc[]
== BYOC usage tiers

When you create a BYOC cluster, you select your usage tier. Each tier provides tested workload configurations for maximum throughput, partitions, and connections. 

|=== 
| Tier | Ingress | Egress | Logical partitions | Connections

| Tier 1 | 20 MBps | 60 MBps | 1,000 | 9,000
| Tier 2 | 50 MBps | 150 MBps | 2,800 | 22,500
| Tier 3 | 100 MBps | 200 MBps | 5,600 | 45,000
| Tier 4 | 200 MBps | 400 MBps | 11,300 | 90,000
| Tier 5 | 400 MBps | 800 MBps | 22,800 | 180,000
| Tier 6 | 800 MBps | 1,600 MBps | 45,000 | 180,000
| Tier 7 | 1,200 MBps | 2,400 MBps | 67,500 | 270,000
| Tier 8 | 1,600 MBps | 3,200 MBps | 90,000 | 360,000
| Tier 9 | 2,000 MBps | 4,000 MBps | 112,500 | 450,000
|===

[NOTE]
====
* Depending on the workload, it may not be possible to achieve all maximum values. For example, a high number of partitions may make it more difficult to reach the maximum value in throughput.
* Logical partition counts assume the Redpanda Cloud default replication factor of 3. If you set a higher replication factor, the maximum value for partitions will be lower.
* Connections are regulated per broker for best performance. For example, in a tier 1 cluster with 3 brokers, there could be up to 3,000 connections per broker. 

====

== BYOC supported regions

[tabs]
====
Google Cloud Platform (GCP)::
+
--
|=== 
| Region 

| asia-east1 
| asia-northeast1
| asia-south1 
| asia-southeast1
| australia-southeast1
| europe-west1
| europe-west2
| europe-west3
| northamerica-northeast1
| southamerica-east1
| us-central1
| us-east1
| us-east4
| us-west1
|===
--
Amazon Web Services (AWS)::
+
--
|=== 
| Region 

| af-south-1 
| ap-east-1
| ap-northeast-1
| ap-south-1
| ap-southeast-1
| ap-southeast-2
| ca-central-1
| eu-central-1
| eu-west-1
| eu-west-2
| me-central-1
| sa-east-1
| us-east-1
| us-east-2
| us-west-2
|===
--
====
endif::[]

ifndef::env-byoc[]
== Dedicated usage tiers

When you create a Dedicated cluster, you select your usage tier. Each tier provides tested workload configurations for maximum throughput, partitions, and connections. 

|=== 
| Tier | Ingress | Egress | Logical partitions | Connections

| Tier 1 | 20 MBps | 60 MBps | 1,000 | 9,000
| Tier 2 | 50 MBps | 150 MBps | 2,800 | 22,500
| Tier 3 | 100 MBps | 200 MBps | 5,600 | 45,000
| Tier 4 | 200 MBps | 400 MBps | 11,300 | 90,000
| Tier 5 | 400 MBps | 800 MBps | 22,800 | 180,000
|===

[NOTE]
====
* Depending on the workload, it may not be possible to achieve all maximum values. For example, a high number of partitions may make it more difficult to reach the maximum value in throughput.
* Logical partition counts assume the Redpanda Cloud default replication factor of 3. If you set a higher replication factor, the maximum value for partitions will be lower.
* Connections are regulated per broker for best performance. For example, in a tier 1 cluster with 3 brokers, there could be up to 3,000 connections per broker. 

====

== Dedicated supported regions

[tabs]
====
Google Cloud Platform (GCP)::
+
--
|=== 
| Region 

| asia-east1 
| asia-northeast1
| asia-south1 
| asia-southeast1
| australia-southeast1
| europe-west1
| europe-west2
| northamerica-northeast1
| southamerica-east1
| us-central1
| us-east1
|===
--
Amazon Web Services (AWS)::
+
--
|=== 
| Region 

| ap-east-1
| ap-northeast-1
| ap-south-1
| ap-southeast-1
| ap-southeast-2
| ca-central-1
| eu-central-1
| eu-west-1
| eu-west-2
| me-central-1
| us-east-1
| us-east-2
| us-west-2
|===
--
====
endif::[]