= Cluster Maintenance
:description: Cluster Maintenance

import ConfigureAvailabilityIntro from './shared/_intro-configure-availability.mdx'
import ClusterDiagnosticsIntro from './shared/_intro-cluster-diagnostics.mdx'
import ManageThroughputIntro from './shared/_intro-manage-throughput.mdx'

* xref:cluster-maintenance:cluster-property-configuration.adoc[Configure Cluster Properties]
+
Learn how to configure cluster properties.

* xref:cluster-maintenance:cluster-balancing.adoc[Cluster Balancing]
+
Redpanda provides leadership balancing and partition rebalancing when nodes are added or decommissioned.

* xref:cluster-maintenance:continuous-data-balancing.adoc[Continuous Data Balancing]
+
Continuous Data Balancing continuously monitors your node and rack availability and disk usage. This enables self-healing clusters that dynamically balance partitions.

* xref:cluster-maintenance:decommission-brokers.adoc[Decommission Brokers]
+
Remove a broker so that it is no longer considered part of the cluster.

* xref:cluster-maintenance:rolling-upgrade.adoc[Upgrade]
+
Learn how to upgrade Redpanda to the latest version.

* xref:manage:node-management.adoc[Maintenance Mode]
+
Maintenance mode lets you take a Redpanda broker offline temporarily while minimizing disruption to client operations.

* xref:cluster-maintenance:disk-utilization.adoc[Manage Disk Space]
+
Redpanda provides several ways to manage disk space to ensure the production stability of the cluster.

* xref:cluster-maintenance:manage-throughput.adoc[Manage Throughput]+++<ManageThroughputIntro>++++++</ManageThroughputIntro>+++
* xref:cluster-maintenance:configure-availability.adoc[Configure Client Connections]+++<ConfigureAvailabilityIntro>++++++</ConfigureAvailabilityIntro>+++
* xref:cluster-maintenance:cluster-diagnostics.adoc[Cluster Diagnostics]+++<ClusterDiagnosticsIntro>++++++</ClusterDiagnosticsIntro>+++
