= rpk generate app
// tag::single-source[]

ifdef::env-cloud[]
NOTE: This command is only supported in Serverless clusters.

endif::[]

Generate a sample application to connect with Redpanda.

This command generates a starter application to produce and consume from the
settings defined in the `rpk profile`. Its goal is to get you producing and
consuming quickly with Redpanda in a language that is familiar to you.

By default, this runs interactively, prompting you to select a language and
a user with which to create your application. To use this without interactivity,
specify how you want your application to be created using flags.

The `--language` flag lets you specify the language. There is no default. Available language: `go`.

The `--new-sasl--user` flag lets you generate a new SASL user
with admin ACLs. If you don't want to use your current profile user or don't want to create a
new one, you can use the `--no-user` flag to generate the starter app without the user.

ifndef::env-cloud[]
If you are having trouble connecting to your cluster, you can use the common xref:reference:rpk/rpk-x-options.adoc#adminhosts[`-X admin.hosts=<host:ports>`] flag to pass a specific Admin API address.

endif::[]

== Examples

* Generate an app with interactive prompts:
+
[,bash]
----
rpk generate app
----

* Generate an app in a specified language with the existing SASL user:
+
[,bash]
----
rpk generate app --language <lang>
----

* Generate an app in the specified language with a new SASL user:
+
[,bash]
----
rpk generate app -l <lang> --new-sasl-user <user>:<password>
----

* Generate an app in the `tmp` directory, but take no action on the user:
+
[,bash]
----
rpk generate app -l <lang> --no-user --output /tmp
----

== Usage

[,bash]
----
rpk generate app [flags]
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-h, --help |- |Help for app.

|-l, --language |string |The language you want the code sample to be
generated with. Available language: `go`.

|--new-sasl-credentials |string |If provided, `rpk` will generate and use
these credentials (<user>:<password>).

|--no-user |- |Generates the sample app without SASL user.

|-o, --output |string |The path where the app will be written.

|--config |string |Redpanda or `rpk` config file; default search paths are `/var/lib/redpanda/.config/rpk/rpk.yaml`, `$PWD/redpanda.yaml`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override `rpk` configuration settings. See xref:reference:rpk/rpk-x-options.adoc[`rpk -X`] or execute `rpk -X help` for inline detail or `rpk -X list` for terser detail.

|--profile |string |Profile to use. See xref:reference:rpk/rpk-profile.adoc[`rpk profile`] for more details.

|-v, --verbose |- |Enable verbose logging.
|===

// end::single-source[]