= rpk generate shell-completion
// tag::single-source[]

Shell completion can help autocomplete `rpk` commands when you press tab.

== Bash

Bash autocompletion relies on the bash-completion package. You can test if you
have this by running `type \_init_completion`, if you do not, you can install
the package through your package manager.

If you have bash-completion installed, and the command still fails, you likely
need to add the following line to your `~/.bashrc`:

[,bash]
----
source /usr/share/bash-completion/bash_completion
----

To ensure autocompletion of `rpk` exists in all shell sessions, add the following
to your `~/.bashrc`:

[,bash]
----
command -v rpk >/dev/null && . <(rpk generate shell-completion bash)
----

Alternatively, to globally enable `rpk` completion, you can run the following:

[,bash]
----
rpk generate shell-completion bash > /etc/bash_completion.d/rpk
----

== Zsh

To enable autocompletion in any zsh session for any user, follow these steps:

Determine which directory in your `$fpath` to use to store the completion file.
   
You can inspect your `fpath` by running:
[,zsh]
----
echo $fpath
----

Choose one of the directories listed. For example, if `/usr/local/share/zsh/site-functions` is present in your `fpath`, you can place the `_rpk` completion file there:

[,zsh]
----
rpk generate shell-completion zsh > /usr/local/share/zsh/site-functions/_rpk
----

If the directory you chose is not already in `fpath`, add it to your `.zshrc`:
[,zsh]
----
fpath+=(/usr/local/share/zsh/site-functions)
----

Finally, ensure that `compinit` is run. Add (or verify) the following in your `.zshrc`:

[,zsh]
----
autoload -U compinit && compinit
----

After restarting your shell, `rpk` completion should be active.

== Fish

To enable autocompletion in any `fish` session, run:

[,fish]
----
rpk generate shell-completion fish > ~/.config/fish/completions/rpk.fish
----

== Usage

[,bash]
----
rpk generate shell-completion [flags]
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-h, --help |- |Help for shell-completion.

|--config |string |Redpanda or `rpk` config file; default search paths are `/var/lib/redpanda/.config/rpk/rpk.yaml`, `$PWD/redpanda.yaml`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override `rpk` configuration settings. See xref:reference:rpk/rpk-x-options.adoc[`rpk -X`] or execute `rpk -X help` for inline detail or `rpk -X list` for terser detail.

|--profile |string |Profile to use. See xref:reference:rpk/rpk-profile.adoc[`rpk profile`] for more details.

|-v, --verbose |- |Enable verbose logging.
|===

// end::single-source[]