= Installing Beta Versions
:description: How to use Redpanda beta versions.

We are constantly updating and improving Redpanda with new features, and capabilities. You can try out these features early on with our beta versions and give us feedback about them. With your help, we can identify and fix potential issues, and make the platform even better for everyone.

If you face any errors during your installation or upgrading process, feel free to reach us in our https://rpnda.co/slack[Slack Community] or on https://github.com/redpanda-data/redpanda/discussions[GitHub Discussions].

CAUTION: Beta versions are not supported for production usage.

== Installation

Choose your desired system and run the commands down below.

=== Debian/Ubuntu

```bash
## Run the setup script to download and install the beta repo
curl -1sLf 'https://dl.redpanda.com/HxYRCzL4xbbaEtPi/redpanda-beta/setup.deb.sh' | sudo -E bash && \
## Use apt to install redpanda
sudo apt install redpanda
```

Run `rpk` to get the version:

```bash
rpk version
```

=== Fedora/RedHat/Amazon Linux

```bash
## Run the setup script to download and install the beta repo
curl -1sLf 'https://dl.redpanda.com/HxYRCzL4xbbaEtPi/redpanda-beta/setup.rpm.sh' | sudo -E bash && \
## Use yum to install redpanda
sudo yum install redpanda
```

Run `rpk` to get the version:

```bash
rpk version
```

=== Docker

There are several ways to choose a version of Redpanda for Docker. You can check our xref:quickstart:quick-start-docker.adoc[getting started guide on Docker] for more information about it. So, for example, you can pull a docker image through this command:

```bash
docker pull docker.redpanda.com/redpandadata/redpanda:v21.12.1-wasm-beta1
```

Run a `docker exec` with `rpk` to get the version:

```bash
docker exec -it <container-name> rpk version
```

=== Kubernetes

. Check which version you want to download at our https://github.com/redpanda-data/redpanda/tags[release page].

. Install the Redpanda operator CRD:

  ```bash
  kubectl apply \ -k https://github.com/redpanda-data/redpanda/src/go/k8s/config/crd?ref=<version>
  ```
  Replace the version variable below with your desired version. So, for example, if you want to download v21.12.1-wasm-beta1 the command will look like this:

  ```bash
  kubectl apply \ -k https://github.com/redpanda-data/redpanda/src/go/k8s/config/crd?ref=v21.12.1-wasm-beta1
  ```

. Update your helm charts:
  ```bash
  helm repo update
  ```
. Install the Redpanda operator on your Kubernetes cluster with:

  ```bash
  helm install \ redpanda-operator \ redpanda/redpanda-operator \ --namespace redpanda-system \ --create-namespace \ --version <version>
  ```

. Execute this command to start a bash inside the cluster:

  ```bash
  kubectl exec --stdin --tty <cluster-name> -- /bin/bash
  ```

. Run `rpk` to get the version:

  ```bash
  rpk version
  ```

The result is similar to this:

```bash
v21.12.1-wasm-beta1 (rev ed9a450)
```

For more information about installing Redpanda in Kubernetes, refer to our xref:quickstart:kubernetes-qs-cloud.adoc[getting started guide on Kubernetes].
