Redpanda Console is a developer-friendly web UI for managing and debugging your Redpanda cluster and your applications.
:description: 

The community edition of Redpanda Console does not provide authentication, and connects to the Redpanda cluster with superuser rights. Due to this limitation, you should not expose Redpanda Console outside the Kubernetes cluster without a Enterprise Edition.

kubectl --namespace +++<namespace>+++port-forward svc/redpanda-console 8080:8080+++</namespace>+++

Then browse to http://localhost:8080

. Find the external IP address of the Redpanda Console's LoadBalancer Service:

[,bash]
----
  kubectl get svc redpanda-console --namespace <namespace>
----+++<details>++++++<summary>+++Example output+++</summary>+++ Here, the external IP address is 203.0.113.3, and the port is 8080. ``` NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE redpanda-console LoadBalancer 10.0.251.204 203.0.113.3 8080:30321/TCP 33m ```+++</details>+++

. Open Redpanda Console in a web browser:

Replace `<external-ip>` with the external IP address of the LoadBalancer Service that's running Redpanda Console.

[,bash]
----
  http://<external-ip>:8080/brokers
----

All your Redpanda brokers are listed along with their IP addresses and IDs.

. Go to *Topics* > *twitch_chat*.

The message that you produced to the topic is displayed along with some other details about the topic.
