= Configure external access to the Redpanda brokers

Because external clients are not in the Kubernetes cluster where the Redpanda brokers are running, they cannot resolve the internal addresses of the headless ClusterIP Service. Instead, if you want to connect to the Redpanda cluster with external clients, Redpanda brokers must advertise an externally accessible address that external clients can connect to. External clients are common in Internet of Things (IoT) environments or in systems using external services that do not implement VPC peering in your network.

When you created the cluster, you set the `external.domain` configuration to `customredpandadomain.local`, which means that your Redpanda brokers are advertising the following addresses:

* `redpanda-0.customredpandadomain.local`
* `redpanda-1.customredpandadomain.local`
* `redpanda-2.customredpandadomain.local`

To access your Redpanda brokers externally, you can map your worker nodes' IP addresses to these domains.

NOTE: IP addresses can change. If the IP addresses of your worker nodes change, you must update your `/etc/hosts` file with the new mappings.

. Add mappings in your `/etc/hosts` file between your worker nodes' IP addresses and their custom domain names:
+
[,bash]
----
sudo true && kubectl -n redpanda get endpoints,node -A -o go-template='{{ range $_ := .items }}{{ if and (eq .kind "Endpoints") (eq .metadata.name "redpanda-external") }}{{ range $_ := (index .subsets 0).addresses }}{{ $nodeName := .nodeName }}{{ $podName := .targetRef.name }}{{ range $node := $.items }}{{ if and (eq .kind "Node") (eq .metadata.name $nodeName) }}{{ range $_ := .status.addresses }}{{ if eq .type "ExternalIP" }}{{ .address }} {{ $podName }}.${DOMAIN}{{ "\n" }}{{ end }}{{ end }}{{ end }}{{ end }}{{ end }}{{ end }}{{ end }}' | envsubst | sudo tee -a /etc/hosts
----
+
.`/etc/hosts`
[,plain,role=no-copy]
----
203.0.113.3 redpanda-0.customredpandadomain.local
203.0.113.5 redpanda-1.customredpandadomain.local
203.0.113.7 redpanda-2.customredpandadomain.local
----

. Save the root certificate authority (CA) to your local file system outside Kubernetes:
+
[,bash]
----
kubectl -n redpanda get secret redpanda-default-root-certificate -o go-template='{{ index .data "ca.crt" | base64decode }}' > ca.crt
----

. Install rpk on your local machine, not on a Pod:
+
[tabs]
=====
Linux::
+
--

include::get-started:partial$install-rpk-linux.adoc[]

--
macOS::
+
--

include::get-started:partial$install-rpk-homebrew.adoc[]

--
=====

. Set the `REDPANDA_BROKERS` environment variable to the custom domains of your Redpanda brokers:
+
[,bash]
----
export REDPANDA_BROKERS=redpanda-0.customredpandadomain.local:31092,redpanda-1.customredpandadomain.local:31092,redpanda-2.customredpandadomain.local:31092
----
+
NOTE: 31092 is the Kafka API port that's exposed by the default NodePort Service.

. Describe the topic:
+
[,bash]
----
rpk topic describe twitch_chat --tls-enabled --tls-truststore=ca.crt --user=redpanda-twitch-account --password=changethispassword --sasl-mechanism SCRAM-SHA-256
----
