Redpanda Console is a developer-friendly web UI for managing and debugging your Redpanda cluster and your applications.

The community edition of Redpanda Console does not provide authentication, and connects to the Redpanda cluster with superuser rights. Due to this limitation, you should not expose Redpanda Console outside the Kubernetes cluster without a Enterprise Edition.

[,bash]
----
kubectl -n redpanda port-forward svc/redpanda-console 8080:8080
----

Then browse to http://localhost:8080

. Find the external IP address of the Redpanda Console's LoadBalancer Service:
+
[,bash]
----
kubectl get svc redpanda-console -n redpanda
----

. Open Redpanda Console in a web browser:
+
Replace `<external-ip>` with the external IP address of the LoadBalancer Service that's running Redpanda Console.
+
[,bash]
----
http://<external-ip>:8080/brokers
----
+
All your Redpanda brokers are listed along with their IP addresses and IDs.

. Go to *Topics* > *twitch_chat*.
+
The message that you produced to the topic is displayed along with some other details about the topic.
