= Add an Enterprise Edition License to Redpanda in Kubernetes
:description: Learn how to add or update a Redpanda Enterprise Edition license in a Kubernetes environment.
:env-kubernetes: true

To enable xref:get-started:licensing/overview.adoc[enterprise features for Redpanda Self-Managed], you must have an Enterprise Edition license. This guide outlines how to apply or update an Enterprise Edition license for Redpanda Self-Managed in a Kubernetes environment.

== Prerequisites

You must have an Enterprise Edition license. To get a trial license key or extend your trial period, https://redpanda.com/try-enterprise[generate a new trial license key^]. To purchase a license, contact https://redpanda.com/upgrade[Redpanda Sales^].

== Add a new license

Redpanda supports the following ways to apply a new license:

- <<secret, Use a Kubernetes Secret to store the license>>.
- <<inline, Provide the license string inline in your Helm values or manifest file>>.
- <<console, Use Redpanda Console to upload the license to Redpanda>>.

[[secret]]
=== Use a Kubernetes Secret

You can store the license in a Kubernetes Secret and reference it in your Helm values or manifest file.

. Download your license file (`redpanda.license`) and create a Kubernetes Secret:
+
[,bash]
----
kubectl create secret generic redpanda-license
--from-file=license=./redpanda.license
--namespace <namespace>
----
+
This command creates a Kubernetes Secret named `redpanda-license` in the specified namespace, containing the license file.

. Reference the Secret:
+
[tabs]
======
Operator::
+
--
.`redpanda-cluster.yaml`
[,yaml]
----
apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
  name: redpanda
spec:
  chartRef: {}
  clusterSpec:
    enterprise:
      licenseSecretRef:
        name: redpanda-license
        key: license
----

```bash
kubectl apply -f redpanda-cluster.yaml --namespace <namespace>
```

--
Helm::
+
--

[tabs]
====
--values::
+
.`redpanda-license.yaml`
[source,yaml]
----
enterprise:
  licenseSecretRef:
    name: redpanda-license
    key: license
----
+
```bash
helm upgrade --install redpanda redpanda/redpanda --namespace <namespace> --create-namespace \
  --values redpanda-license.yaml --reuse-values
```

--set::
+
[,bash]
----
helm upgrade --install redpanda redpanda/redpanda \
  --namespace <namespace> \
  --create-namespace \
  --set enterprise.licenseSecretRef.name=redpanda-license \
  --set enterprise.licenseSecretRef.key=license
----

====
--
======

[[inline]]
=== Provide the license inline

If you prefer to provide the license string directly, you can do so as follows:

[tabs]
======
Operator::
+
--
.`redpanda-cluster.yaml`
[,yaml]
----
apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
  name: redpanda
spec:
  chartRef: {}
  clusterSpec:
    enterprise:
      license: <license-key>
----

```bash
kubectl apply -f redpanda-cluster.yaml --namespace <namespace>
```

--
Helm::
+
--

[tabs]
====
--values::
+
.`redpanda-license.yaml`
[source,yaml]
----
enterprise:
  license: <license-key>
----
+
```bash
helm upgrade --install redpanda redpanda/redpanda --namespace <namespace> --create-namespace \
  --values redpanda-license.yaml --reuse-values
```

--set::
+
[,bash]
----
helm upgrade --install redpanda redpanda/redpanda \
  --namespace <namespace> \
  --create-namespace \
  --set enterprise.license=<license-key>
----

====
--
======


[[console]]
=== Use Redpanda Console

You can upload a license directly through Redpanda Console.

See xref:console:ui/add-license.adoc[].

== Verify a license

After adding or updating a license, you can use `rpk` to verify that the license was set.

include::get-started:partial$licensing/check-license.adoc[]

== Update an existing license

The process for updating a license depends on how it was originally applied:

- <<secret-update, Update the Kubernetes Secret>>.
- <<inline-update, Update the license string inline in your Helm values or manifest file>>.
- xref:console:ui/add-license.adoc[Use Redpanda Console]

When a new license is uploaded, enterprise features in Redpanda Self-Managed are unlocked immediately without requiring a cluster restart. However, to unlock enterprise features in Redpanda Console, you must restart the Redpanda Console instance.

[[secret-update]]
=== Update the Kubernetes Secret

If the license is provided through a Kubernetes Secret, follow these steps to update it:

. Download the updated license file and overwrite the existing `redpanda.license` file.

. Delete the existing Secret:
+
[,bash]
----
kubectl delete secret redpanda-license --namespace <namespace>
----

. Create a new Secret with a **new name** that contains the contents of the updated license:
+
[,bash]
----
kubectl create secret generic redpanda-license-updated \
  --from-file=license=./redpanda.license \
  --namespace <namespace>
----

. Update the Redpanda CRD to use the new Secret.
+
.`redpanda-cluster.yaml`
[,yaml]
----
apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
  name: redpanda
spec:
  chartRef: {}
  clusterSpec:
    enterprise:
      licenseSecretRef:
        name: redpanda-license-updated
        key: license
----

. Apply the changes to the Redpanda CRD:
+
[,bash]
----
kubectl apply -f redpanda-cluster.yaml --namespace <namespace>
----
+
The Redpanda Operator updates the license without restarting the Repanda broker.

. Check the status of the new license to make sure it was successfully applied:
+
[,bash]
----
rpk cluster license info
----
+
The output displays the following details:
+
----
Organization:    Organization the license was generated for.
Type:            Type of license.
Expires:         Expiration date of the license.
Version:         License schema version.
----

. If you use Redpanda Console, delete the Redpanda Console Pods to force Redpanda Console to reload the updated license:
+
[,bash]
----
kubectl delete pod $(kubectl get pod --namespace <namespace> | grep redpanda-console | awk '{print $1}') --namespace <namespace>
----

[[inline-update]]
=== Update the license inline

If you applied the license inline, follow these steps to update it:

. Modify the `enterprise.license` value with the new license string:
+
[tabs]
======
Operator::
+
--
.`redpanda-cluster.yaml`
[,yaml]
----
apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
  name: redpanda
spec:
  chartRef: {}
  clusterSpec:
    enterprise:
      license: <license-key>
----

```bash
kubectl apply -f redpanda-cluster.yaml --namespace <namespace>
```

--
Helm::
+
--

[tabs]
====
--values::
+
.`redpanda-license.yaml`
[source,yaml]
----
enterprise:
  license: <license-key>
----
+
```bash
helm upgrade --install redpanda redpanda/redpanda --namespace <namespace> --create-namespace \
  --values redpanda-license.yaml --reuse-values
```

--set::
+
[,bash]
----
helm upgrade --install redpanda redpanda/redpanda \
  --namespace <namespace> \
  --create-namespace \
  --set enterprise.license=<license-key>
----

====
--
======

. Check the status of new license to make sure it was successfully applied:
+
[,bash]
----
rpk cluster license info
----
+
The output displays the following details:
+
----
Organization:    Organization the license was generated for.
Type:            Type of license:.
Expires:         Expiration date of the license.
Version:         License schema version.
----

. If you use Redpanda Console, delete the Redpanda Console Pods to force a reload of the updated license:
+
[,bash]
----
kubectl delete pod $(kubectl get pod --namespace <namespace> | grep redpanda-console | awk '{print $1}') --namespace <namespace>
----

== Next steps

xref:get-started:licensing/monitor-license-status.adoc[].
