= Add an Enterprise Edition License to Redpanda in Linux
:description: Learn how to add or update a Redpanda Enterprise Edition license in a Linux environment.

To enable xref:get-started:licensing/overview.adoc[enterprise features for Redpanda Self-Managed], it must have an Enterprise Edition license. This guide outlines how to apply or update an Enterprise Edition license for Redpanda Self-Managed in a Linux environment.

== Prerequisites

- You must have xref:get-started:rpk-install.adoc[`rpk` installed] and configured to connect to your Redpanda cluster.

- You must have an Enterprise Edition license. If you don't have a license yet, https://www.redpanda.com/contact[request one^].

== Add a new license

Redpanda supports the following ways to apply a new license:

- <<file, Provide the path to a file containing the license>>.
- <<inline, Pass the license string directly. Follow the instructions below based on your preferred method>>.
- <<console, Use Redpanda Console to upload the license to Redpanda>>.

[[file]]
=== Apply the license using a license file

If you have the license key stored in a file, you can apply it by specifying the file path:

```bash
rpk cluster license set --path <path-to-license-file> -X admin.hosts=<admin-api-url>
```

Replace the following placeholders:
- `<path-to-license-file>` with the path to your license file.
- `<admin-api-url>` the Redpanda admin host and port

[[inline]]
=== Apply the license using an inline license string

If you want to provide the license string directly, use the following command:

```bash
rpk cluster license set <license-string>
```

If neither the path nor the license string are provided, `rpk` looks for the license in `/etc/redpanda/redpanda.license`.

=== Use Redpanda Console

You can upload a license directly through Redpanda Console.

See xref:console:ui/add-license.adoc[].

== Update an existing license

To update an existing license, you can use one the following:

- xref:reference:rpk/rpk-cluster/rpk-cluster-license-set.adoc[]
- xref:console:ui/add-license.adoc[Redpanda Console]

When a new license is uploaded, enterprise features in Redpanda Self-Managed are unlocked immediately without requiring a cluster restart. However, to unlock enterprise features in Redpanda Console, you must restart the Redpanda Console instance.

== Next steps

xref:get-started:licensing/monitor-license-status.adoc[].

== Suggested reading

xref:reference:rpk/rpk-cluster/rpk-cluster-license-set.adoc[]