name: 📚 Documentation update request
description: Suggest a change to existing Redpanda documentation.
body:
  - type: markdown
    attributes:
      value: |
        Help us improve Redpanda documentation! Create issues for doc bugs, improvements, or content gaps. You can search [open doc issues](https://github.com/redpanda-data/documentation/issues), and ask for guidance on our [community Slack docs channel](https://redpanda.com/slack). To request documentation for a new feature, use the New Feature template.
  - type: textarea
    id: issue-body
    attributes:
      label: Issue description
      description: Describe how the current doc is incorrect, incomplete, or unclear, and describe how to fix it. Include as much information as possible.
    validations:
      required: true
  - type: textarea
    id: link
    attributes:
      label: Updates to existing documentation
      description: Provide the URL of the page that requires an update.
    validations:
      required: true  
  - type: textarea
    id: slack
    attributes:
      label: Link to Redpanda Slack conversation
      description: If applicable, provide links to any Redpanda Slack conversations about the issue.
