ifdef::latest-operator-version[]
[,bash,subs="attributes+"]
----
helm repo add redpanda https://charts.redpanda.com
helm repo update
helm upgrade --install redpanda-controller redpanda/operator \
  --namespace <namespace> \
  --create-namespace \
  --version {latest-operator-version} \ <1>
  --set crds.enabled=true <2>
----
+
<1> This flag specifies the exact version of the Redpanda Operator Helm chart to use for deployment. By setting this value, you pin the chart to a specific version, which prevents automatic updates that might introduce breaking changes or new features that have not been tested in your environment.
<2> This flag ensures that the CRDs are installed as part of the Redpanda Operator deployment.
+
This command deploys the Redpanda Operator in cluster scope (default in v25.2+), allowing it to manage Redpanda clusters across multiple namespaces.
+
To deploy the Redpanda Operator in namespace scope (managing only resources within its deployment namespace), use:
+
[,bash,subs="attributes+"]
----
helm upgrade --install redpanda-controller redpanda/operator \
  --namespace <namespace> \
  --create-namespace \
  --version {latest-operator-version} \
  --set crds.enabled=true \
  --set 'additionalCmdFlags=["--namespace=<namespace>"]' <3>
----
+
<3> This flag restricts the Redpanda Operator to manage resources only within the specified namespace.
+
WARNING: Do not run multiple Redpanda Operators in different scopes (cluster and namespace scope) in the same cluster as this can cause resource conflicts.
+
:note-caption: Older versions of the Redpanda Operator
+
[NOTE]
========
The `--set crds.enabled=true` flag is only supported in Redpanda Operator **v25.1.1 and later**.

If you deploy an earlier version (such as v2.4.x), you must install the CRDs separately. See the xref:25.1@ROOT:deploy:deployment-option/self-hosted/kubernetes/k-production-deployment.adoc[v2.4.x deployment documentation] for more information.
========
endif::[]
ifndef::latest-operator-version[]
[,bash,subs="attributes+"]
----
helm repo add redpanda https://charts.redpanda.com
helm repo update
helm upgrade --install redpanda-controller redpanda/operator \
  --namespace <namespace> \
  --create-namespace \
  --set crds.enabled=true <1>
----
<1> This flag ensures that the CRDs are installed as part of the Redpanda Operator deployment.
endif::[]
