:latest-operator-version: 25.2.0
ifdef::latest-operator-version[]
.. To deploy in cluster scope, use:
+
[,bash,subs="attributes+"]
----
helm repo add redpanda https://charts.redpanda.com
helm repo update
helm upgrade --install redpanda-controller redpanda/operator \
  --namespace <namespace> \
  --create-namespace \
  --version {latest-operator-version} \ <1>
  --set crds.enabled=true <2>
----
+
<1> This flag specifies the exact version of the Redpanda Operator Helm chart to use for deployment. By setting this value, you pin the chart to a specific version, which prevents automatic updates that might introduce breaking changes or new features that have not been tested in your environment.
<2> This flag ensures that the CRDs are installed as part of the Redpanda Operator deployment.
+
This command deploys the Redpanda Operator in cluster scope (default in v25.2+), allowing it to manage Redpanda clusters across multiple namespaces.

.. To deploy in namespace scope (managing only resources within its deployment namespace), use:
+
[,bash,subs="attributes+"]
----
helm upgrade --install redpanda-controller redpanda/operator \
  --namespace <namespace> \
  --create-namespace \
  --version {latest-operator-version} \
  --set crds.enabled=true \
  --set 'additionalCmdFlags=["--namespace=<cluster-namespace>"]' <1>
----
+
<1> This flag restricts the Redpanda Operator to manage resources only within the specified namespace.
endif::[]
ifndef::latest-operator-version[]
[,bash,subs="attributes+"]
----
helm repo add redpanda https://charts.redpanda.com
helm repo update
helm upgrade --install redpanda-controller redpanda/operator \
  --namespace <namespace> \
  --create-namespace \
  --set crds.enabled=true <1>
----
<1> This flag ensures that the CRDs are installed as part of the Redpanda Operator deployment.
endif::[]
