= Networking and Connectivity in Kubernetes
:description: Clients must be able to connect directly to each Pod that runs a Redpanda broker.

Set up external access to your Redpanda cluster to allow your applications running outside the Kubernetes cluster to communicate with Redpanda and produce and consume events.

* xref:networking:networking-and-connectivity.adoc[Networking and Connectivity in Kubernetes]
+
Learn about StatefulSets and Pod identities, as well as internal and external networking options.

* xref:networking:configure-external-access-nodeport.adoc[Use a NodePort Service]
+
Learn how to configure external access through a NodePort Service.

* xref:networking:configure-external-access-loadbalancer.adoc[Use LoadBalancer Services]
+
Learn how to configure external access through LoadBalancer Services.

* xref:networking:custom-services.adoc[Use a Custom Service]
+
Learn how to configure external access with a custom service.

* xref:networking:configure-listeners.adoc[Configure Listeners]
+
Learn how to customize the advertised ports for each listener on all Redpanda brokers, or disable listeners altogether.
