= pg_namespace


## Overview

The `pg_namespace` contains information about schema definitions. It mimics the pg_namespace^[https://www.postgresql.org/docs/current/catalog-pg-namespace.html] PostgreSQL system catalog.

[NOTE]
====
To learn more about Schema and how it is managed in Oxla, please refer to the xref:oxla-reference:schema.adoc[schema documentation].
====


## Columns

[NOTE]
====
This table is designed for compatibility with tools that require PostgreSQL system tables, so it mostly has dummy data. Please note that not all columns in `pg_namespace` are applicable to every type of relation.
====


The `pg_namespace` catalog has the following key columns:

[cols="1,1,1",options="header"]
|===
|Column |Type |Description

|`oid` |`int` |This column represents the Object ID, a unique identifier assigned to each namespace
|`nspname` |`text` |This column represents the name of the namespace
|`nspowner` |`int` |This column represents the owner of the namespace
|`nspacl` |`text` |*unused*
|===


## Example

### 1. Create a Schema
In this example, we create "sales" and "hr" schemas using the query below:

[source,sql]
----
CREATE SCHEMA sales;
CREATE SCHEMA hr;
----


The successful result would look like this:

[source,sql]
----
COMPLETE
COMPLETE
----


### 2. View Schema Definitions
We then use a `SELECT` statement on the `pg_namespace` catalog to show the schema definitions.

[source,sql]
----
SELECT nspname AS schema_name, oid AS schema_oid
FROM pg_namespace;
----


The result shows the list of schemas and its ID, as shown below:

[source,sql]
----
schema_name | schema_oid 
-------------+------------
 public      |          0
 sales       |          3
 hr          |          4
----

