= Configure GCP Private Service Connect with the Cloud API
:description: Set up GCP Private Service Connect to securely access Redpanda Cloud.
:page-cloud: true

include::shared:partial$feature-flag.adoc[]

NOTE: This guide is for configuring GCP Private Service Connect using the Redpanda Cloud API. See xref:networking:configure-private-service-connect-in-cloud-ui.adoc[Configure Private Service Connect in the Cloud UI] if you want to set up the endpoint service using the UI.

The Redpanda GCP Private Service Connect service provides secure access to Redpanda Cloud from your own VPC. Traffic over Private Service Connect does not go through the public internet because a Private Service Connect connection is treated as its own private GCP service. While your VPC has access to the Redpanda VPC, Redpanda cannot access your VPC.

Consider using Private Service Connect if you have multiple VPCs and could benefit from a more simplified approach to network management:

* Private Service Connect allows overlapping xref:networking:cidr-ranges.adoc[CIDR ranges] in VPC networks.
* Private Service Connect does not limit the number of connections.
* You control from which GCP projects connections are allowed.
After <<get-a-cloud-api-access-token,getting an access token>>, you can <<create-new-byoc-cluster-with-private-service-connect-enabled,enable Private Service Connect when creating a new BYOC cluster>>, or you can <<enable-private-service-connect-on-an-existing-byoc-cluster,enable Private Service Connect for existing BYOC clusters>>.

== Requirements

* In this guide, you use the xref:manage:api/cloud-api-overview.adoc[Redpanda Cloud API] to enable the Redpanda endpoint service for your clusters. Follow the steps on this page to <<get-a-cloud-api-access-token, get an access token>>.
* Use https://cloud.google.com/sdk/docs/install[gcloud^] to create the consumer-side resources, such as a VPC and forwarding rule, or modify existing resources to use the Private Service Connect service attachment created for your cluster.

== Get a Cloud API access token

. Save the base URL of the Redpanda Cloud API in an environment variable:
+
[,bash]
----
export PUBLIC_API_ENDPOINT="https://api.cloud.redpanda.com"
----

. In the https://cloud.redpanda.com/[Redpanda Cloud UI], go to **Resource groups** and select the resource group in which you want to create a cluster.
+
Copy and store the resource group ID (UUID) from the URL in the browser.
+
[,bash]
----
export RESOURCE_GROUP_ID=<uuid>
----

. Go to the organization (org) level **Home** in the UI, and navigate to **Clients**. If you don't have an existing client, you can create a new one by clicking **Add client**.
+
Copy and store the client ID and secret.
+
[,bash]
----
export CLOUD_CLIENT_ID=<client-id>
export CLOUD_CLIENT_SECRET=<client-secret>
----

. Get an API token using the client ID and secret. You can click the **Request an API token** link to see code examples to generate the token.
+
[,bash]
----
export AUTH_TOKEN=`curl -s --request POST \
    --url 'https://auth.prd.cloud.redpanda.com/oauth/token' \
    --header 'content-type: application/x-www-form-urlencoded' \
    --data grant_type=client_credentials \
    --data client_id=$CLOUD_CLIENT_ID \
    --data client_secret=$CLOUD_CLIENT_SECRET \
    --data audience=cloudv2-production.redpanda.cloud | jq .access_token | sed 's/"//g'`
----

You must send the API token in the `Authorization` header when making requests to the Cloud API.

== Configure BYOC with customer-managed resources

For xref:get-started:cluster-types/byoc/vpc-byo-gcp.adoc[BYOC clusters with customer-managed VPC], you need a NAT subnet with the *Purpose* set to `PRIVATE_SERVICE_CONNECT`. You can create the subnet using the `gcloud` command-line interface (CLI):

[,bash]
----
gcloud compute networks subnets create <subnet-name> \
    --project=<project> \
    --network=<network-name> \
    --region=<region> \
    --range=<subnet-range> \
    --purpose=PRIVATE_SERVICE_CONNECT
----

Provide your values for the following placeholders:

- `<subnet-name>`: The name of the NAT subnet.
- `<project>`: The **host** GCP project ID.
- `<network-name>`: The name of the VPC being used for your Redpanda Cloud cluster.
- `<region>`: The region of the Redpanda Cloud cluster.
- `<subnet-range>`: The CIDR range of the subnet. The mask should be at least `/29`. Each Private Service Connect connection takes up one IP address from the NAT subnet, so the CIDR must be able to accommodate all projects from which connections to the service attachment will be issued.

See the GCP documentation for https://cloud.google.com/vpc/docs/configure-private-service-connect-producer#add-subnet-psc[creating a subnet for Private Service Connect^].

== Create new BYOC cluster with Private Service Connect enabled

. Update the Redpanda Cloud Agent IAM role.
+
To allow the agent to create and manage Private Service Connect resources, add the following permissions to its IAM role:
+
```
compute.forwardingRules.use
compute.regionOperations.get
compute.serviceAttachments.create
compute.serviceAttachments.delete
compute.serviceAttachments.get
compute.serviceAttachments.list
compute.serviceAttachments.update
compute.subnetworks.use
```

. Make a request to the xref:api:ROOT:cloud-api.adoc#post-/v1beta2/networks[`POST /v1beta2/networks`] endpoint to create a network
+
[,bash]
----
network_post_body=`cat << EOF
{
    "cloud_provider": "CLOUD_PROVIDER_GCP",
    "cluster_type": "TYPE_BYOC",
    "name": "<network-name>",
    "resource_group_id": "$RESOURCE_GROUP_ID",
    "region": "<region>",
    "customer_managed_resources": {
        "gcp": {
            "network_name": "<byovpc-network-name>",
            "network_project_id": "<byovpc-network-gcp-project-id>",
            "management_bucket": { "name" : "<byovpc-management-bucket>" }
        }
    }
}
EOF`

curl -vv -X POST \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $AUTH_TOKEN" \
-d "$network_post_body" $PUBLIC_API_ENDPOINT/v1beta2/networks
----
+
Replace the following placeholder variables for the request body:
+
--
- `<network-name>`: Provide a name for the network. The name is used to identify this network in the Cloud UI.
- `<region>`: Choose a GCP region where the network will be created.
- `<byovpc-network-gcp-project-id>`: The ID of the GCP project where your VPC is created.
- `<byovpc-network-name>`: The name of your VPC.
- `<byovpc-management-bucket>`: The name of the Google Storage bucket you created for the cluster.
--


. Store the network ID (`metadata.network_id`) returned in the response to the Create Network request.
+
[,bash]
----
export NETWORK_ID=<metadata.network_id>
----

. Make a request to the xref:api:ROOT:cloud-api.adoc#post-/v1beta2/clusters[`POST /v1beta2/clusters`] endpoint to create a Redpanda Cloud cluster with Private Service Connect enabled:
+
[,bash]
----
export CLUSTER_POST_BODY=`cat << EOF
{
    "cloud_provider": "CLOUD_PROVIDER_GCP",
    "connection_type": "CONNECTION_TYPE_PRIVATE",
    "type": "TYPE_BYOC",
    "name": "<cluster-name>",
    "resource_group_id": "$RESOURCE_GROUP_ID",
    "network_id": "$NETWORK_ID",
    "region": "<region>",
    "zones": <zones>,
    "throughput_tier": "<throughput-tier>",
    "redpanda_version": "<redpanda-version>",
    "gcp_private_service_connect": {
        "enabled": true,
        "consumer_accept_list": <consumer-accept-list>
    },
    "customer_managed_resources": {
        "gcp": {
            "subnet": {
                "name":"<byovpc-subnet-name>",
                "secondary_ipv4_range_pods": { "name": "<byovpc-subnet-pods-range-name>" },
                "secondary_ipv4_range_services": { "name": "<byovpc-subnet-services-range-name>" },
                "k8s_master_ipv4_range": "<byovpc-subnet-master-range>"
            },
            "psc_nat_subnet_name": "<byovpc-psc-nat-subnet-name>"
            "agent_service_account": { "email": "<byovpc-agent-service-acc-email>" },
            "connector_service_account": { "email": "<byovpc-connectors-service-acc-email>" },
            "console_service_account": { "email": "<byovpc-console-service-acc-email>" },
            "redpanda_cluster_service_account": { "email": "<byovpc-redpanda-service-acc-email>" },
            "gke_service_account": { "email": "<byovpc-gke-service-acc-email>" },
            "tiered_storage_bucket": { "name" : "<byovpc-tiered-storage-bucket>" },
        }
    }
}
EOF`

curl -vv -X POST \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $AUTH_TOKEN" \
-d "$CLUSTER_POST_BODY" $PUBLIC_API_ENDPOINT/v1beta2/clusters
----
+
Replace the following placeholders for the request body. Variables with a `byovpc_` prefix represent xref:get-started:cluster-types/byoc/vpc-byo-gcp.adoc[customer-managed resources] that should have been created previously:
+
--
- `<cluster-name>`: Provide a name for the new cluster.
- `<region>`: Choose a GCP region where the network will be created.
- `<zones>`: Provide the list of GCP zones where the brokers will be deployed. Format: `["<zone 1>", "<zone 2>", "<zone N>"]`
- `<throughput-tier>`: Choose a Redpanda Cloud cluster tier. For example, `tier-1-gcp-v2-x86`.
- `<redpanda-version>`: Choose the Redpanda Cloud version.
- `<consumer-accept-list>`: The list of IDs of GCP projects from which Private Service Connect connection requests are accepted. Format: `[{"source": "<GCP-project-ID-1>"}, {"source": "<GCP-project-I-2>"}, {"source": "<GCP-project-ID-N>"}]`
- `<byovpc-subnet-name>`: The name of the GCP subnet that was created for the cluster.
- `<byovpc-subnet-pods-range-name>`: The name of the IPv4 range designated for K8s pods.
- `<byovpc-subnet-services-range-name>`: The name of the IPv4 range designated for services.
- `<byovpc-subnet-master-range>`: The master IPv4 range.
- `<byovpc-psc-nat-subnet-name>`: The name of the GCP subnet that was created for Private Service Connect NAT.
- `<byovpc-agent-service-acc-email>`: The email for the agent service account.
- `<byovpc-connectors-service-acc-email>`: The email for the connectors service account.
- `<byovpc-console-service-acc-email>`: The email for the console service account.
- `<byovpc-redpanda-service-acc-email>`: The email for the Redpanda service account.
- `<byovpc-gke-service-acc-email>`: The email for the GKE service account.
- `<byovpc-tiered-storage-bucket>`: The name of the Google Storage bucket to use for Tiered Storage.
--

== Enable Private Service Connect on an existing BYOC cluster

. In the Redpanda Cloud UI, go to the cluster overview and copy the cluster ID from the **Details** section.
+
[,bash]
----
CLUSTER_ID=<cluster-id>
----

. Update the Redpanda Cloud Agent IAM role. This step is required only for clusters with xref:get-started:cluster-types/byoc/vpc-byo-gcp.adoc[customer-managed resources].
+
To allow the agent to create and manage the service attachment, add the following permissions to its IAM role:
+
[,bash]
----
compute.forwardingRules.use
compute.regionOperations.get
compute.serviceAttachments.create
compute.serviceAttachments.delete
compute.serviceAttachments.get
compute.serviceAttachments.list
compute.serviceAttachments.update
compute.subnetworks.use
----

. Make a request to the xref:api:ROOT:cloud-api.adoc#patch-/v1beta2/clusters/-cluster.id-[`PATCH /v1beta2/clusters/{cluster.id}`] endpoint to update the cluster to include the newly-created Private Service Connect NAT subnet.
+
[,bash]
----
export ACCEPT_LIST='[]'
export PSC_NAT_SUBNET_NAME='<psc-nat-subnet-name>'
export CLUSTER_PATCH_BODY=`cat << EOF
{
    "customer_managed_resources": {
        "gcp": {
            "psc_nat_subnet_name": "$PSC_NAT_SUBNET_NAME"
        }
    }
}
EOF`
curl -v -X PATCH \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $AUTH_TOKEN" \
-d "$CLUSTER_PATCH_BODY" $PUBLIC_API_ENDPOINT/v1beta2/clusters/$CLUSTER_ID
----
+
Replace the following placeholder:
+
`<psc-nat-subnet-name>`: The name of the Private Service Connect NAT subnet. Use the fully-qualified name, for example `"projects/<project>/regions/<region>/subnetworks/<subnet-name>"`.

. Make a xref:api:ROOT:cloud-api.adoc#patch-/v1beta2/clusters/-cluster.id-[`PATCH /v1beta2/clusters/{cluster.id}`] request to update the cluster to enable Private Service Connect.
+
[,bash]
----
CLUSTER_PATCH_BODY=`cat << EOF
{
    "gcp_private_service_connect": {
        "enabled": true,
         "consumer_accept_list": <accept-list>
    }
}
EOF`
curl -v -X PATCH \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $AUTH_TOKEN" \
-d "$CLUSTER_PATCH_BODY" $PUBLIC_API_ENDPOINT/v1beta2/clusters/$CLUSTER_ID
----
+
Replace the following placeholder:
+
`<accept-list>`: a JSON list specifying the projects from which incoming connections will be accepted. All other sources. For example, `[{"source": "consumer-project-ID-1"},{"source": "consumer-project-ID-2"}]`.
+
Wait for the cluster to apply the new configuration (around 15 minutes). The Private Service Connect service attachment is available when the cluster update is complete. You can monitor the service attachment creation by running the following `gcloud` command and supplying the project ID:
+
[,bash]
----
gcloud compute service-attachments list --project '<service-project-id>'
----

== Access Redpanda services through VPC endpoint

After you have enabled Private Service Connect for your cluster, your connection URLs are available in the *How to Connect* section of the cluster overview in the Redpanda Cloud UI.

include::networking:partial$private-links-access-rp-services-through-vpc.adoc[]

== Test the connection

You can test the Private Service Connect connection from any VM or container in the consumer VPC. If configuring a client isn't possible right away, you can do these checks using `rpk` or curl:

include::networking:partial$private-links-test-connection.adoc[]


include::shared:partial$suggested-reading.adoc[]

* xref:networking:dedicated/vpc-peering.adoc[]
* xref:networking:byoc/gcp/vpc-peering-gcp.adoc[]
