import ClusterProperty from '../tiered-storage/_cluster-props.mdx'
:description: 
import TunableClusterProperty from '../tiered-storage/_tunable-cluster-props.mdx'

. To enable Tiered Storage, set <ClusterProperty name="cloud_storage_enabled" frontmatter={props.frontmatter}/> to `true`.
. Configure topics for Tiered Storage. You can configure either all topics in a cluster or only specific topics.
 ** <<enable-tiered-storage-for-a-cluster,Enable Tiered Storage for a cluster>>
 ** <<enable-tiered-storage-for-specific-topics,Enable Tiered Storage for specific topics>>

==== Enable Tiered Storage for a cluster

To enable Tiered Storage for a cluster (in addition to setting `cloud_storage_enabled` to `true`), set the following cluster-level properties to `true`:

* <TunableClusterProperty name="cloud_storage_enable_remote_write" frontmatter={props.frontmatter}/>
* <TunableClusterProperty name="cloud_storage_enable_remote_read" frontmatter={props.frontmatter}/>

When you enable Tiered Storage for a cluster, you enable it for all existing topics in the cluster. When cluster-level properties are changed, the changes apply only to new topics, not existing topics.

:::note
The `cloud_storage_enable_remote_write` and `cloud_storage_enable_remote_read` cluster-level properties are essentially creation-time defaults for the `redpanda.remote.write` and `redpanda.remote.read` topic-level properties.
:::

==== Enable Tiered Storage for specific topics

To enable Tiered Storage for a new or existing topic (in addition to setting `cloud_storage_enabled` to `true`), set the following topic-level properties to `true`:

* `redpanda.remote.write`
* `redpanda.remote.read`

For example, to create a new topic with Tiered Storage:

[,bash]
----
rpk topic create <topic_name> -c redpanda.remote.read=true -c redpanda.remote.write=true
----

To enable Tiered Storage on an existing topic, run:

[,bash]
----
rpk topic alter-config <topic_name> --set redpanda.remote.read=true --set redpanda.remote.write=true
----

Topic-level properties override cluster-level properties. For example, for new topics, if `cloud_storage_enable_remote_write` is set to `true`, you can set `redpanda.remote.write` to `false` to turn it off for a particular topic.

Tiered Storage topic-level properties:

|===
| Property | Description

| `redpanda.remote.write`
| Uploads data from Redpanda to object storage. Overrides the cluster-level `cloud_storage_enable_remote_write` configuration for the topic.

| `redpanda.remote.read`
| Fetches data from object storage to Redpanda. Overrides the cluster-level `cloud_storage_enable_remote_read` configuration for the topic.

| `redpanda.remote.recovery`
| Recovers or reproduces a topic from object storage. Use this property during topic creation. It does not apply to existing topics.

| `redpanda.remote.delete`
| When set to `true`, deleting a topic also deletes its objects in object storage. Both `redpanda.remote.write` and `redpanda.remote.read` must be enabled, and the topic must not be a Remote Read Replica topic. +
 +
When set to `false`, deleting a topic does not delete its objects in object storage.  +
 +
Default is `true` for new topics.
|===

The following tables list outcomes for combinations of cluster-level and topic-level configurations:

|===
| Cluster-level configuration with +
`cloud_storage_enable_remote_write` | Topic-level configuration with +
`redpanda.remote.write` | Outcome: +
whether remote write is enabled +
or disabled on the topic

| `true`
| Not set
| Enabled

| `true`
| `false`
| Disabled

| `true`
| `true`
| Enabled

| `false`
| Not set
| Disabled

| `false`
| `false`
| Disabled

| `false`
| `true`
| Enabled
|===

|===
| Cluster-level configuration with +
`cloud_storage_enable_remote_read` | Topic-level configuration with +
`redpanda.remote.read` | Outcome: +
whether remote read is enabled +
or disabled on the topic

| `true`
| Not set
| Enabled

| `true`
| `false`
| Disabled

| `true`
| `true`
| Enabled

| `false`
| Not set
| Disabled

| `false`
| `false`
| Disabled

| `false`
| `true`
| Enabled
|===
