= CORR()


## Overview

The `CORR()` aggregate function calculates the Pearson correlation coefficient between two sets of number pairs.
This function measures the linear relationship between two variables, providing a value between -1 and 1.

## Syntax

The syntax for this function is as follows:

[source,sql]
----
CORR(y, x)
----


## Parameters

* `y`: variable being predicted
* `x`: variable used for prediction

## Example

For the needs of this section, we are going to use a simplified version of the `film` table from the Pagila database, containing only the `title`, `length` and `rating` columns. The complete schema for the `film` table can be found on the
<a href="https://www.postgresql.org/ftp/projects/pgFoundry/dbsamples/pagila/pagila/" target="_blank">Pagila</a> database website.

[source,sql]
----
DROP TABLE IF EXISTS film;
CREATE TABLE film (
  title text NOT NULL,
  length int,
  rating int
);
INSERT INTO film(title, length, rating) VALUES
  ('ATTRACTION NEWTON', 83, 5),
  ('CHRISTMAS MOONSHINE', 150, 7),
  ('DANGEROUS UPTOWN', 121, 4),
  ('KILL BROTHERHOOD', 54, 3),
  ('HALLOWEEN NUTS', 47, 5),
  ('HOURS RAGE', 122, 7),
  ('PIANIST OUTFIELD', 136, 7),
  ('PICKUP DRIVING', 77, 3),
  ('INDEPENDENCE HOTEL', 157, 7),
  ('PRIVATE DROP', 106, 4),
  ('SAINTS BRIDE', 125, 3),
  ('FOREVER CANDIDATE', 131, 7),
  ('MILLION ACE', 142, 5),
  ('SLEEPY JAPANESE', 137, 4),
  ('WRATH MILE', 176, 7),
  ('YOUTH KICK', 179, 7),
  ('CLOCKWORK PARADISE', 143, 5);
----


The query below uses the `CORR()` function to calculate the correlation between film length and rating:

[source,sql]
----
SELECT
  CORR(length, rating) AS CorrelationCoefficient
FROM film;
----


By running the query above we will get the following output:

[source,sql]
----
correlationcoefficient 
------------------------
     0.6190587870867634
(1 row)
----
