= STDDEV_POP()


## Overview

The `STDDEV_POP()` aggregate function calculates the population stardard deviation of a set of numeric values.

## Syntax

The syntax for this function is as follows:

[source,sql]
----
STDDEV_POP(expression)
----


## Parameters

* `expression`: numeric expression or column for which the population standard deviation is calculated

## Example

For the needs of this section, we're going to use a simplified version of the `film` table from the Pagila database, containing only the `title`, `length` and `rating` columns. The complete schema for the `film` table can be found on the
<a href="https://www.postgresql.org/ftp/projects/pgFoundry/dbsamples/pagila/pagila/" target="_blank">Pagila</a> database website.

[source,sql]
----
DROP TABLE IF EXISTS film;
CREATE TABLE film (
  title text NOT NULL,
  length int,
  rating int
);
INSERT INTO film(title, length, rating) VALUES
  ('ATTRACTION NEWTON', 83, 5),
  ('CHRISTMAS MOONSHINE', 150, 7),
  ('DANGEROUS UPTOWN', 121, 4),
  ('KILL BROTHERHOOD', 54, 3),
  ('HALLOWEEN NUTS', 47, 5),
  ('HOURS RAGE', 122, 7),
  ('PIANIST OUTFIELD', 136, 7),
  ('PICKUP DRIVING', 77, 3),
  ('INDEPENDENCE HOTEL', 157, 7),
  ('PRIVATE DROP', 106, 4),
  ('SAINTS BRIDE', 125, 3),
  ('FOREVER CANDIDATE', 131, 7),
  ('MILLION ACE', 142, 5),
  ('SLEEPY JAPANESE', 137, 4),
  ('WRATH MILE', 176, 7),
  ('YOUTH KICK', 179, 7),
  ('CLOCKWORK PARADISE', 143, 5);
----


They query below uses the `STDDEV_POP()` function to calculate the population standard deviation for the `length` column:

[source,sql]
----
SELECT
    STDDEV_POP(length) AS LengthPopStdDev
FROM film;
----

By executing the above code, we will get the following output:

[source,sql]
----
lengthpopstddev  
-------------------
 37.23496886764368
(1 row)
----
