:page-layout: api-partial

The Redpanda Cloud Control Plane API enables you to programmatically manage your clusters, networks, and resource groups. 

To familiarize yourself with Redpanda Cloud API basics, see the xref:redpanda-cloud:manage:api/cloud-api-overview.adoc[Redpanda Cloud API Overview]. To get started using the API, try the xref:redpanda-cloud:manage:api/cloud-api-quickstart.adoc[Quickstart].

NOTE: To see the available endpoints for managing resources within your clusters, such as topics, users, access control lists (ACLs), and connectors, see the link:https://docs.redpanda.com/api/cloud-dataplane-api.html[Data Plane API Reference].

IMPORTANT: The Control Plane API beta versions v1beta1 and v1beta2 are deprecated. v1beta1 and v1beta2 are still available, but they will be removed in a future release and are not recommended for use. See xref:redpanda-cloud:manage:api/cloud-api-deprecation-policy.adoc[] for details.

== Requirements

To use the Control Plane API:

* You must be a customer with an existing organization in Redpanda Cloud.
* You can only use one organization for authentication. See xref:redpanda-cloud:manage:api/cloud-api-authentication.adoc[Cloud API Authentication] for steps to authenticate API requests.

== Control Plane API URL

The xref:redpanda-cloud:manage:api/cloud-api-overview.adoc#control-plane-api-url[*base URL*] of the Control Plane API for all organizations is:

```
https://api.redpanda.com
```

== See also

* xref:redpanda-cloud:manage:api/cloud-api-quickstart.adoc[Cloud API Quickstart]
* xref:redpanda-cloud:manage:api/cloud-api-errors.adoc[Cloud API Error and Status Codes]
* link:https://docs.redpanda.com/api/cloud-dataplane-api.html[Data Plane API Reference]


