:page-layout: api-partial

The Redpanda Cloud API is a collection of REST APIs that allow you to interact with different parts of Redpanda Cloud. The Control Plane API enables you to programmatically manage your clusters, networks, and resource groups. 

To familiarize yourself with Redpanda Cloud API basics, see the xref:redpanda-cloud:manage:api/cloud-api-overview.adoc[Redpanda Cloud API Overview]. To get started using the API, try the xref:redpanda-cloud:manage:api/cloud-api-quickstart.adoc[Quickstart].

NOTE: To see the available endpoints for managing resources within your clusters, such as topics, users, access control lists (ACLs), and connectors, see the xref:api:ROOT:cloud-dataplane-api.adoc[Data Plane API Reference].

== Requirements

To use the Cloud API:

* You must be a customer with an existing organization in Redpanda Cloud.
* You can only use one organization for authentication. See xref:redpanda-cloud:manage:api/cloud-api-authentication.adoc[Cloud API Authentication] for steps to authenticate API requests.

== Control Plane API URL

The xref:redpanda-cloud:manage:api/cloud-api-overview.adoc#control-plane-api-url[*base URL*] of the Control Plane API for all organizations is:

```
https://api.redpanda.com
```

== See also

* xref:redpanda-cloud:manage:api/cloud-api-quickstart.adoc[Cloud API Quickstart]
* xref:redpanda-cloud:manage:api/cloud-api-errors.adoc[Cloud API Error and Status Codes]
* xref:api:ROOT:cloud-dataplane-api.adoc[Data Plane API Reference]


