= Serverless
:description: Learn how to create a Serverless cluster.
:page-cloud: true

To start using Redpanda Serverless, sign up for a free trial. Each trial supports five Serverless clusters. To continue after the trial expires, you can enter a credit card and pay as you go. 

* To ask questions about the trial, use the *#serverless* https://redpandacommunity.slack.com/[Community Slack^] channel, or contact https://support.redpanda.com/hc/en-us/requests/new[support^].
* For information about Redpanda Cloud cluster types, see xref:get-started:cloud-overview.adoc[].
* For information about billing after the trial ends, see xref:billing:billing.adoc[].

NOTE: Serverless is currently in a limited availability (LA) release with xref:get-started:cluster-types/serverless.adoc#limits[usage limits] and no public SLA. During LA, existing clusters can scale to the usage limits, but new clusters may need to wait for availability.

== Prerequisites

. https://redpanda.com/try-redpanda/cloud-trial#serverless[Sign up for a trial^] of Redpanda Serverless. 

. Make sure you have the latest version of `rpk`. See xref:ROOT:get-started:rpk-install.adoc[].

== Limits

Each Serverless cluster has the following limits:

* Ingress: up to 10 MBps, 0.5 MBps guaranteed
* Egress: up to 30 MBps, 1.5 MBps guaranteed
* Partitions: 100 logical partitions
* Message size: 20 MB
* Retention: unlimited time
* Storage: unlimited
* Users: 30
* ACLs: 120
* Consumer groups: 200

[NOTE]
====
These baseline limits are subject to change. To increase your limits, contact https://support.redpanda.com/hc/en-us/requests/new[support^]. 
====

== Trial credits

New trials receive $100 (USD) in free credits to spend in the first 14 days. This should be enough to run Redpanda with reasonable throughput. No credit card is required. To continue using Serverless after your trial expires, you can enter a credit card and pay as you go. Any remaining credit balance is used before you are charged. 

When either the 100 credits expire or the 14 days in the trial expire, the clusters move into a suspended state, and you won't be able to access your data in either the Redpanda Cloud UI or with the Kafka API. There is a 7 day grace period following the end of the trial. After that, the data is permanently deleted. 

== Get started

After you click to start a trial, Redpanda instantly prepares an account for you. Your account includes a `welcome` cluster with a `hello-world` demo topic you can explore. The `hello-world` topic starts as a free read-only topic. It is materialized and becomes billable with your credits if you produce messages to it. 

== Interact with your cluster

Similar to Dedicated and BYOC clusters, you can interact with your Serverless cluster with `rpk` CLI commands or with the Redpanda Cloud UI. For example, you can run `rpk topic consume hello-world` to read the messages in that topic explaining the `rpk` steps to stream data. Here are some helpful `rpk` commands:

* xref:ROOT:reference:rpk/rpk-cloud/rpk-cloud-login.adoc[`rpk cloud login`]: Use this to log in to Redpanda Cloud or to refresh the session.
* xref:ROOT:reference:rpk/rpk-topic.adoc[`rpk topic`]: Use this to manage topics, produce data, and consume data. 
* xref:ROOT:reference:rpk/rpk-profile/rpk-profile-print.adoc[`rpk profile print`]: Use this to view your `rpk` configuration and see the URL for your Serverless cluster.
* xref:ROOT:reference:rpk/rpk-security/rpk-security-user.adoc[`rpk security user`]: Use this to manage users and permissions. 

Alternatively, in the Redpanda Cloud UI, you can navigate to the *Topics* page and open the `hello-world` topic to see the included messages. Under the *Actions* dropdown, you can produce messages to it. Add team members and grant them access with ACLs on the *Security* page. 

NOTE: Redpanda Serverless is opinionated about Kafka configurations. For example, automatic topic creation is disabled. Some systems expect the Kafka service to automatically create topics when a message is produced to a topic that doesn't exist. Create topics on the *Topics* page or with `rpk topic create`.

== Run a demo application

Run xref:ROOT:reference:rpk/rpk-generate/rpk-generate-app.adoc[`rpk generate app`] to generate a sample application to connect with Redpanda. 

The Redpanda Cloud *Overview* page lists your bootstrap server URL and security settings in the *How to connect - Kafka API* tab. In the same section, you can click *Go*, *Python*, or *Node.js* for code examples to create a topic and produce and consume messages. 

== Create a new cluster

Click the default resource group in the breadcrumbs to return to the *Clusters* page and create a new Serverless cluster. 

Serverless clusters are currently available in certain AWS regions. Redpanda expects your applications to be deployed in the same AWS region. For best performance, select the region closest to your applications. Serverless is not guaranteed to be pinned to a particular availability zone within that region.

== Supported features

Serverless clusters work with all Kafka clients. For more information, see xref:ROOT:develop:kafka-clients.adoc[].

Serverless clusters support all major Apache Kafka messages for managing topics, producing/consuming data (including transactions), managing groups, managing offsets, and managing ACLs. (User management is available in the Redpanda Cloud UI or with `rpk security acl`.) 

=== Unsupported features

Redpanda Serverless supports the Kafka API. The Redpanda Admin, HTTP Proxy, and Schema Registry APIs are not exposed. You can use an external schema registry. 

The following features are not yet supported in Serverless clusters: 

* Managed connectors
* Data transforms
