= Cluster Configuration
:description: Cluster configuration general information.

When you install Redpanda software, configuration properties are automatically set to their default values. These properties are divided into two categories: cluster and node.

== Cluster properties

Cluster properties are those that should be the same for each node in the cluster. These properties are stored internally and automatically replicated across all nodes, which ensures that each node is in sync. Examples of cluster properties include kafka frontend settings, authentication settings, and settings for enabling features such as tiered storage and rack awareness. Most Redpanda configuration properties fall into the cluster category.

xref:reference:tunable-properties.adoc[Tunable properties] are also considered cluster properties. These properties are used for tuning the cluster. You should not need to change these default settings for normal operation.

For a full list of cluster properties, their descriptions, and their default values, see xref:reference:cluster-properties.adoc[Cluster configuration properties].

For instructions on how to change cluster property settings and how to export a configuration to another cluster, see xref:cluster-administration:cluster-property-configuration.adoc[Configuring cluster properties].

== Node properties

Node properties are usually set differently on each node. The `node_id`, which must be unique for each node, is one example. Another example is the `kafka_api` listener IP address. Node properties are stored in the `redpanda.yaml` file located in the `/etc/redpanda` directory for each node.
For a full list of node properties, their descriptions, and their default values, see xref:reference:node-properties.adoc[Node configuration properties].
For instructions on how to change node property settings, see xref:cluster-administration:node-property-configuration.adoc[Configuring node properties].
