= Configuring Node Properties
:description: Node configuration properties using redpanda.yaml file.

When you install Redpanda software, a `redpanda.yaml` file is installed on each node in `/etc/redpanda`. This file contains node configuration properties. A node property is one that is always different for each node, such as the `node_id`, or one that can be set differently from node to node.

See xref:reference:node-properties.adoc[Node Configuration Properties] for a list of node properties, their descriptions, and their default values.

When you open the default `redpanda.yaml` file, you will see that node properties are grouped into categories:

* `pandaproxy` - properties for the Redpanda HTTP proxy
* `redpanda` - runtime configuration properties, such as the cluster member IP addresses, the node_id, and the data directory
* `rpk` - properties that determine how `rpk` starts Redpanda
* `schema registry` - properties related to storage, retrieval, and compatibility of the schemas

To see a sample template that includes all node properties as they appear in the default `redpanda.yaml` file, refer to xref:reference:node-configuration-sample.adoc[Node Configuration Template]. This template is annotated with descriptions of each property.

== Setting node configuration properties

Although the `redpanda.yaml` file rarely needs to be edited after the system is installed, you can change the value of any node configuration property, except for the unique node identifier, `node_uuid`. The `node_uuid` value is automatically populated in the `redpanda.yaml` file when the node is brought up and must not be changed.

To change a node property setting:

. Open a terminal window and navigate to the node where you want to change one or more property settings.
. Go to the `/etc/redpanda` directory.
. Open the `redpanda.yaml` file.
. Change values for properties as needed.
+
CAUTION: Once a node joins the cluster, do not change the `node_id`.
. Save the file and quit the editor.
. Restart the node to apply the changes.

When Redpanda starts up and reads the `redpanda.yaml` file, it checks that each property setting has a valid value. If the file contains an invalid property setting, Redpanda will log an error and refuse to start.
