= Deploy a Redpanda Cluster in Azure Kubernetes Service
:description: Deploy a secure Redpanda cluster and Redpanda Console in Azure Kubernetes Service (AKS).

import Versions from '../../../../shared/_versions.mdx'
import DeployRedpanda from "./shared/guides/_deploy-redpanda.mdx"
import CreateUser from "./shared/guides/_create-user.mdx"
import StartStreaming from "./shared/guides/_start-streaming.mdx"
import ExploreTopics from "./shared/guides/_explore-topics-localhost.mdx"
import ExternalAccessIntro from "./shared/guides/_external-access-intro.mdx"
import ExternalAccessSteps from "./shared/guides/_external-access-steps.mdx"
import DefaultComponents from "./shared/_default-components.mdx"
import NextSteps from "./shared/guides/_next-steps.mdx"
import SuggestedReading from "./shared/guides/_suggested-reading.mdx"

Deploy a secure Redpanda cluster and Redpanda Console in Azure Kubernetes Service (AKS). After you deploy, use rpk both as an internal client and an external client to interact with your Redpanda cluster from the command line.

The Redpanda cluster has the following security features:

* SASL for authenticating users' connections.
* TLS with self-signed certificates for secure communication between the cluster and clients.

== Prerequisites

Before you begin, you must have the following:

* You must satisfy the prerequisites listed in the https://learn.microsoft.com/en-us/azure/aks/learn/quick-kubernetes-deploy-cli#prerequisites[AKS quickstart]
to get access to the Azure CLI.
* https://kubernetes.io/docs/tasks/tools/[`kubectl`]. Minimum required Kubernetes version: +++<Versions name="kubernetes">++++++</Versions>+++
+
[,bash]
----
kubectl version --short --client
----

* https://helm.sh/docs/intro/install/[Helm]. Minimum required Helm version: +++<Versions name="helm">++++++</Versions>+++
+
[,bash]
----
helm version
----

== Create an AKS cluster

In this step, you create three worker nodes (one worker node for each Redpanda broker).

:::info
Each Redpanda broker must run on its own worker node. As a result, the Helm chart configures `podAntiAffinity` rules to make sure that only one Redpanda broker Pod is scheduled on each worker node. For more information, see xref::kubernetes-cluster-requirements.adoc#number-of-worker-nodes[Kubernetes Cluster Requirements].
:::

You also configure your AKS cluster to give each worker node a public IP address, and allow external access to the node ports on which the Redpanda deployment will be exposed. You'll use these node ports in later steps to configure external access to your Redpanda cluster.

. Create a resource group for Redpanda:

[,bash]
----
  az group create --name redpandaResourceGroup --location eastus
----

. Create an AKS cluster with three worker nodes (one for each Redpanda broker):

[,bash]
----
  az aks create -g redpandaResourceGroup --namespace <namespace> \
    --node-count 3 \
    --generate-ssh-keys \
    --enable-node-public-ip
----

:::tip
  For all available options, see the https://learn.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-create[AKS documentation].
  :::

. Get your subscription ID:

[,bash]
----
  export SUBSCRIPTION_ID=$(az account show --query id --output tsv)
----

. Set up a connection to your AKS cluster:

[,bash]
----
  az account set --subscription $SUBSCRIPTION_ID
  az aks get-credentials --resource-group redpandaResourceGroup --name redpanda
----

. Open the https://portal.azure.com/[Azure Portal], search for 'Network security groups', and click the name of the network security group in the *MC_redpandaResourceGroup_redpanda_eastus* resource group.
. Add an inbound security rule with the following values:
 ** *Destination port ranges*:
+
----
31644,31092,30082,30081
----

 ** *Name*
+
----
AllowRedpandaNodePorts
----

== Deploy Redpanda and Redpanda Console+++<DeployRedpanda>++++++</DeployRedpanda>+++

== Create a user+++<CreateUser>++++++</CreateUser>+++

== Start streaming+++<StartStreaming>++++++</StartStreaming>+++

== Explore your topic in Redpanda Console+++<ExploreTopics>++++++</ExploreTopics>+++

== Configure external access to the Redpanda brokers+++<ExternalAccessIntro>++++++</ExternalAccessIntro>++++++<ExternalAccessSteps>++++++</ExternalAccessSteps>+++

== Explore the default Kubernetes components+++<DefaultComponents>++++++</DefaultComponents>+++

== Troubleshooting

Before troubleshooting your cluster, make sure that you have all the <<prerequisites,prerequisites>>.

For troubleshooting steps, see xref:manage:kubernetes:troubleshooting:troubleshoot.adoc[Troubleshoot Redpanda in Kubernetes].

== Next steps+++<NextSteps>++++++</NextSteps>+++

== Suggested reading+++<SuggestedReading>++++++</SuggestedReading>+++
