= Leader Pinning
:page-categories: Clients, Development
// tag::single-source[]
:description: Learn about leader pinning and how to configure a preferred partition leader based on availability zones.

Produce requests to Redpanda topics go through the topic partition leader, which syncs messages across its follower replicas. For a Redpanda cluster deployed across multiple availability zones (AZs), leader pinning ensures that a topic's partition leaders are geographically closer to clients. Leader pinning can lower networking costs and help guarantee lower latency by routing produce and consume requests to brokers located in certain AZs.

xref:develop:consume-data/follower-fetching.adoc[Follower fetching], where you configure consumers to fetch records from the closest replica, can also help reduce overall networking costs. 

== Prerequisites

include::shared:partial$enterprise-license.adoc[]

You must xref:manage:rack-awareness.adoc#configure-rack-awareness[configure rack awareness] for the cluster. If the config_ref:enable_rack_awareness,true,properties/cluster-properties[] cluster configuration property is set to `false`, leadership pinning is disabled across the cluster.

== Configure leader pinning

You can use a topic configuration property as well as a cluster configuration property to configure leader pinning.

The following steps assume that you have Redpanda deployed in a multi-AZ setup, and you have configured each broker so that the config_ref:rack,true,properties/broker-properties[] configuration property contains rack IDs corresponding to the AZ IDs.

* Set the topic configuration property `redpanda.leaders.preference`. The property accepts the following string values:
+
--
** `none`: Opt out the topic from leader pinning.
** `racks:<rack1>[,<rack2>,...]`: Specify the preferred location (rack) of partition leaders to brokers with rack IDs in this list. The list can contain one or more rack IDs. 
--
+
This property inherits the default value from `default_leaders_preference`.
+
You can list the IDs in any order. Spaces in the list are ignored, i.e. `racks:rack1,rack2` and `racks: rack1,  rack2` are equivalent, but you cannot specify empty rack IDs, for example, `racks: rack1,,rack2`.

* Set the cluster configuration property `default_leaders_preference`. This property sets the default leader pinning configuration for all topics that don’t have `redpanda.leaders.preference` explicitly set. It accepts values in the same format as `redpanda.leaders.preference`. Default: `none` 
+
This property also affects internal topics such as `__consumer_offsets` and transaction coordinators.

You can set the configuration property for individual topics only, or set the cluster-wide configuration property that will enable leader pinning by default for all topics. You can also use a combination in which a default setting applies across the cluster, and you toggle the setting on or off for specific topics.

If there is more than one broker in the preferred AZ (or AZs), leader pinning distributes partition leaders uniformly across brokers in the AZ.

== Leader pinning failover across availability zones

If there are three AZs: A, B, and C, and A becomes unavailable, the failover behavior is as follows:

* A topic with "A" as the preferred leader AZ will have its partition leaders uniformly distributed across B and C.
* A topic with "A,B" as the preferred leader AZs will have its partition leaders in B.
* A topic with “B” as the preferred leader AZ will have its partition leaders in B as well.

== Suggested reading

* xref:develop:consume-data/follower-fetching.adoc[]
