= Install Redpanda Console
:description: Deploy Redpanda Console on your Kubernetes cluster, run it locally or deploy it on a bare-metal server.
:page-aliases: console:installation.adoc

== Local / Quickstart

To connect Redpanda Console to a Kafka cluster running on your local machine
or in another Docker container:

[,shell]
----
docker run --network=host \
  -e KAFKA_BROKERS=localhost:9092 \
  docker.redpanda.com/redpandadata/console:latest
----

NOTE: The host networking driver only works on Linux hosts, and is not supported on Docker Desktop for Mac,
Docker Desktop for Windows, or Docker EE for Windows Server. The recommended approach to test Redpanda Console
on a local machine is to run it with xref:console:reference/docker-compose.adoc[Docker compose]
so that it can share the network scope with the container that runs the Kafka cluster.

To connect Redpanda Console to a remote Kafka cluster:

[,shell]
----
docker run -p 8080:8080 \
  -e KAFKA_BROKERS=bootstrap.cluster-hash.redpanda.cloud:9092 \
  -e KAFKA_TLS_ENABLED=true \
  -e KAFKA_SASL_ENABLED=true \
  -e KAFKA_SASL_MECHANISM=SCRAM-SHA-256 \
  -e KAFKA_SASL_USERNAME=xxx \
  -e KAFKA_SASL_PASSWORD=xxx \
  docker.redpanda.com/redpandadata/console:latest
----

The configuration above can be used to connect to a cluster that uses commonly trusted certificates in
combination with SASL plain authentication. To launch Redpanda Console with additional files, such
as certificates or a Redpanda license, you can mount a directory that contains those files.
When you run the docker run command, specify the mount volume and the filepaths to the additional files.

The following example mounts the directory
`console-mounts` in your current path so that all files inside that directory become available at
`/etc/console-mounts` inside the Docker container. The directory contains the files
`redpanda.license` and `ca.crt`, which are specified in the configuration parameters
`REDPANDA_LICENSE_FILEPATH` and `KAFKA_TLS_CAFILEPATH` respectively.

[,shell]
----
docker run -p 8080:8080 \
  -v $(pwd)/console-mounts:/etc/console-mounts \
  -e REDPANDA_LICENSE_FILEPATH=/etc/console-mounts/redpanda.license \
  -e KAFKA_BROKERS=bootstrap.cluster-hash.redpanda.cloud:9092 \
  -e KAFKA_TLS_ENABLED=true \
  -e KAFKA_TLS_CAFILEPATH=/etc/console-mounts/ca.crt \
  -e KAFKA_SASL_ENABLED=true \
  -e KAFKA_SASL_MECHANISM=SCRAM-SHA-256 \
  -e KAFKA_SASL_USERNAME=xxx \
  -e KAFKA_SASL_PASSWORD=xxx \
  docker.redpanda.com/redpandadata/console:latest
----

== Docker

Docker images for amd64 and arm64 systems are available on https://hub.docker.com/r/redpandadata/console/tags[dockerhub].
A new Docker image is published for each new (beta) release.

== Kubernetes

You can use the Redpanda Console Helm chart to deploy Redpanda Console into your Kubernetes cluster. To install
the Helm repository and chart, run:

----
helm repo add redpanda-console 'https://dl.redpanda.com/public/console/helm/charts/'
helm repo update
helm install redpanda-console/console
----

For a complete list of all chart configuration variables see the chart's
https://github.com/redpanda-data/console/blob/master/helm/console/values.yaml[values.yaml] file.

If you prefer to create your own manifests instead, you can browse through the Helm chart linked above
or refer to the <<configuration,configuration>> section, which describes the configuration requirements
to run Redpanda Console. There is also an example YAML file for the Helm chart in the
https://github.com/redpanda-data/console/tree/master/helm/examples[examples] directory.

== Binaries and Linux packages

For each new release Redpanda compiles the Redpanda Console to a single binary for macOS, Linux, and Windows
for 64-bit Intel & ARM based chips. You can find the binaries in the attachments of
each release on GitHub.

Additionally, Redpanda pushes Linux packages for Redpanda Console in two different formats: rpm and deb.

To install the Redpanda Console package on *Debian/Ubuntu*, run the following commands:

----
curl -1sLf \
  'https://dl.redpanda.com/nzc4ZYQK3WRGd9sy/redpanda/cfg/setup/bash.deb.sh' \
  | sudo -E bash

sudo apt-get install redpanda-console
----

To install the Redpanda Console package on *Fedora/RedHat/Amazon Linux*, run the following commands:

----
curl -1sLf \
  'https://dl.redpanda.com/nzc4ZYQK3WRGd9sy/redpanda/cfg/setup/bash.rpm.sh' \
  | sudo -E bash

sudo yum install redpanda-console
----

== Redpanda Enterprise license

To use an Enterprise feature, Redpanda Console must have its own physical copy of
your Enterprise license. You have two options for providing the license:

. Mount the `redpanda.license` file, then specify the filepath to this license file by setting the `redpanda.licenseFilepath` property in the YAML file, or by setting the environment variable `REDPANDA_LICENSE_FILEPATH`.
. Specify the license file contents directly by setting the `redpanda.license` property in the YAML file, or by setting the environment variable `REDPANDA_LICENSE`.

Redpanda Console checks the license status on startup and warns you 30 days before a license expires. You can also view the expiration date in the startup logs.
If the license expires at runtime, Redpanda Console shuts down. If the license has already
expired at startup, Redpanda Console prints an error message and exits.

== Configuration

You can configure Redpanda Console using environment variables, a YAML file, or a mix of both. To use YAML you
need to set the path to the YAML configuration file by either providing the filepath using the
`-config.filepath` flag or by setting the env variable `CONFIG_FILEPATH`. Due to the complexity
of some configuration objects it is recommended that you use YAML and only provide sensitive values such as
passwords using the environment variables.

To view the reference configurations that document all environment and YAML variables:

* xref:console:reference/config.adoc[Redpanda Console Configuration] - Main configuration file for Redpanda Console
* xref:console:reference/role-bindings.adoc[Redpanda Console Role Binding Configuration] - Role binding configuration for RBAC
