= Installing rpk
:description: Redpanda Keeper (rpk) is a single binary application that provides a way to interact with your Redpanda clusters from the command line.

Redpanda Keeper (rpk) is a single binary application that provides a way to interact with your Redpanda clusters from the command line.

You can install `rpk` as part of a bundle that includes `redpanda` (see the link:index.adoc[Install Redpanda] for instructions), or you can install the `rpk` binary separately.

If you are preparing to deploy a BYOC cluster using the Redpanda Cloud UI, for example, you only need to install the `rpk` binary.

NOTE: For a list of all `rpk` commands and their syntax, refer to xref:reference:rpk/index.adoc[rpk documentation].

To install the rpk binary as a standalone application, follow the instructions for your operating system.

[tabs]
=====
Linux::
+
--
Download the `rpk` archive for Linux:

[,bash]
----
curl -LO https://github.com/redpanda-data/redpanda/releases/latest/download/rpk-linux-amd64.zip
----

Ensure that you have the folder `~/.local/bin`:

[,bash]
----
mkdir -p ~/.local/bin
----

Add it to your `$PATH`:

[,bash]
----
export PATH="~/.local/bin:$PATH"
----

Unzip the `rpk` files to your `~/.local/bin/` directory:

[,bash]
----
unzip rpk-linux-amd64.zip -d ~/.local/bin/
----

--
macOS::
+
--

[tabs]
======
Intel macOS::
+
---
Download the `rpk` archive for macOS:

```bash
curl -LO https://github.com/redpanda-data/redpanda/releases/latest/download/rpk-darwin-amd64.zip
```

Ensure that you have the folder `~/.local/bin`:

```bash
mkdir -p ~/.local/bin
```

Add it to your `$PATH`:

```bash
export PATH="~/.local/bin:$PATH"
```

Unzip the `rpk` files to your `~/.local/bin/` directory:

```bash
unzip rpk-darwin-amd64.zip -d ~/.local/bin/
```
---

Apple Silicon::
+
---
Download the `rpk` archive for macOS:

[,bash]
----
curl -LO https://github.com/redpanda-data/redpanda/releases/latest/download/rpk-darwin-arm64.zip
----

Ensure that you have the folder `~/.local/bin`:

[,bash]
----
mkdir -p ~/.local/bin
----

Add it to your `$PATH`:

[,bash]
----
export PATH="~/.local/bin:$PATH"
----

Unzip the `rpk` files to your `~/.local/bin/` directory:

[,bash]
----
unzip rpk-darwin-arm64.zip -d ~/.local/bin/
----

---
======
--
=====

After the files have been unzipped, run `rpk version` to display the rpk binary version.

[,bash]
----
rpk version
----

The output displays the version number. For example:

----
v22.2.6 (rev 449eef2)
----
