= Creating a Dedicated Cloud Cluster on AWS
:description: Use the Redpanda Cloud to create a Dedicated cloud cluster.

To create a Redpanda cluster in the Dedicated cloud, log in to the Redpanda Cloud, add a namespace, then follow the steps for creating a Dedicated cluster.

== Create a namespace

To prepare to deploy a Dedicated cluster, log in to the Redpanda Cloud UI and add a namespace:

. Go to https://cloudv2.redpanda.com[Redpanda Cloud] and click *Log in*.
. Type your organization name and click *Continue*.
. Click *Add namespace*.
+
Namespaces help you organize clusters by owner, team, or project for example.

. Type a name for your namespace.

== Create a Dedicated cluster

Create a dedicated cluster in your namespace by selecting cluster settings, cloud provider settings, and the network connection type:

. Scroll to your namespace (namespaces are listed in alphabetical order) and click *+ Add Cluster*.
. Click *Create Dedicated cluster*.
+
The *Create dedicated cluster* page opens at the *Cluster settings* step.

. (Optional) In *Cluster name*, type a name to replace the default name.
. Select throughput.
+
The choices are 1 MBps, 5 MBps, 10 MBps, and 20 MBps.

. Open the *Redpanda version* menu and select a version.
. Click *Next*.
+
The *Cloud settings* page opens.

. For *Provider*, select AWS.
. Open the *Region* menu and select a region.
+
If you plan to create a private network in your own VPC, select the region where your VPC is located.

. Open the *Zones* menu and select three availability zones for your region.
. Click *Next*.
+
The *Networking* page opens.

. Under *Connection Type*, select either *Public Network* or *Private - VPC Peering*.
. Click *Create*.

After the cluster is created, you can click on the cluster name on the *Home* page to see the *Overview* page for that cluster.

If you chose *Private - VPC Peering* for your connection type, see xref:vpc-peering.adoc[Adding a VPC Peering Connection] to connect your VPC to the Redpanda Cloud VPC.
