= rpk connect streams
:description: rpk connect streams

NAME:
   redpanda-connect streams - Run Redpanda Connect in streams mode

USAGE:
   redpanda-connect streams [command options] [arguments...]

DESCRIPTION:
   Run Redpanda Connect in streams mode, where multiple pipelines can be executed in a
   single process and can be created, updated and removed via REST HTTP
   endpoints.

     redpanda-connect streams
     redpanda-connect -c ./root_config.yaml streams
     redpanda-connect streams ./path/to/stream/configs ./and/some/more
     redpanda-connect -c ./root_config.yaml streams ./streams/*.yaml

   In streams mode the stream fields of a root target config (input, buffer,
   pipeline, output) will be ignored. Other fields will be shared across all
   loaded streams (resources, metrics, etc).

   For more information check out the docs at:
   https://docs.redpanda.com/redpanda-connect/guides/streams_mode/about

OPTIONS:
   --no-api                   Disable the HTTP API for streams mode (default: false)
   --prefix-stream-endpoints  Whether HTTP endpoints registered by stream configs should be prefixed with the stream ID (default: true)
   --help, -h                 show help

== Usage

[,bash]
----

----
|===