= Install Redpanda Guide for Kubernetes with kind
:description: Kubernetes quickstart with local access on kind.
:page-aliases: quickstart:kubernetes-qs-local-access.adoc

IMPORTANT: This guide uses the Redpanda Operator for installation. To use the latest recommended Redpanda Helm chart, see the xref:quickstart:kubernetes-qs-dev.adoc[Install Redpanda Guide for Kubernetes].

This guide helps you set up Redpanda locally for development and testing purposes on macOS, Windows, or Linux. Start here to set up Redpanda quickly to try it out or for CI/CD purposes.

This guide uses kind to create a local Kubernetes cluster in which Redpanda is deployed. It also verifies that the Kafka API port is exposed to your local network so that you can interact with Redpanda from your local machine and not just from inside the Kubernetes cluster.

To get up and running, you create a cluster and deploy the Redpanda operator on the cluster. The steps limit the number of nodes to one, because multi-node local clusters are not currently supported. For details on how to access Redpanda outside the Kubernetes network, see xref:redpanda-operator/kubernetes-external-connect.adoc[Connecting Remotely to Kubernetes].

NOTE: In these steps, the YAML file you use to install Redpanda sets `developerMode: true`. If you choose to set `developerMode: false`, run `rpk redpanda tune all` directly on the host before you create a Redpanda cluster. This command sets tuning parameters for optimal configuration. For more information, see xref:deployment:production-deployment.adoc#Step-2-Set-Redpanda-production-mode[Set Redpanda production mode]. If `rpk` is not available, verify that `fs.aio-max-nr` is set to `1048576` or greater. You can set `fs.aio-max-nr` by running `sysctl -w fs.aio-max-nr=1048576`.

== Prerequisites

Before you install Redpanda, verify that you have the following software installed on the machine where you want to run Redpanda:

* https://kubernetes.io/docs/tasks/tools/[kubectl] - version 1.21 or later
* https://github.com/helm/helm/releases[Helm] - version 3.0.0 or later
* https://kind.sigs.k8s.io/docs/user/quick-start/[kind] - version 0.11.1 or later
* https://go.dev/doc/install[Go] - v1.17 or later (only required for Windows setup)
* https://stedolan.github.io/jq/[jq] - This setup uses jq to set the Redpanda `$VERSION` environment variable. (If you don't have jq installed, you can run the same commands by replacing the `$VERSION` environment variable with the version of Redpanda that you're using.) Run the one of the following commands to install jq:

[tabs]
=====
brew::
+
--
```bash
brew install jq
```

--
apt::
+
--
```bash
sudo apt-get update && \
sudo apt-get install jq
```

--
=====

== Create a Kubernetes cluster

Use https://kind.sigs.k8s.io/[kind] to create a Kubernetes cluster on your local machine. kind lets you create local Kubernetes clusters using Docker. After you install kind, verify that port `30001` is free on your machine before you set up a cluster, or cluster creation will fail.

To enable access from your operating system to the cluster, create a `kind-external.yaml` file that contains the following text:

[,yaml]
----
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
    - containerPort: 30001
      hostPort: 30001
----

Set up a cluster:

[,bash]
----
kind create cluster --config kind-external.yaml
----

== Install cert-manager

The Redpanda operator requires cert-manager to create certificates for TLS communication. You can install cert-manager with https://cert-manager.io/docs/installation/helm/[Helm] or https://cert-manager.io/docs/installation/kubectl/[kubectl].

Before you install cert-manager, verify that the version you're installing is compatible with your Kubernetes version. The cert-manager https://cert-manager.io/docs/installation/supported-releases/#installing-with-helm[Supported Releases] documentation lists which Kubernetes versions are supported.

To install cert-manager with Helm:

[,bash]
----
helm repo add jetstack https://charts.jetstack.io && \
helm repo update && \
helm install \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --version v1.4.4 \
  --set installCRDs=true
----

=== Verify cert-manager installation

Use the https://cert-manager.io/docs/installation/verify/#manual-verification[verification procedure] in the cert-manager documentation to verify that cert-manager is deployed correctly.

== Install `rpk`

Redpanda Keeper, or `rpk`, is a CLI utility that you use to interact with Redpanda.

Install `rpk` on the host machine:

[,bash]
----
brew install redpanda-data/tap/redpanda
----

NOTE: On Windows, you must compile `rpk` yourself with https://go.dev/doc/install[Go]. You can find the `rpk` source files in GitHub under https://github.com/redpanda-data/redpanda/tree/dev/src/go/rpk[redpanda/src/go/rpk].

== Install Redpanda operator with Helm

. Use Helm to add the Redpanda chart repository and update it:
+
[,bash]
----
helm repo add redpanda https://charts.vectorized.io/ && \
helm repo update
----

. Set the `$VERSION` environment variable to the latest operator and Redpanda version:
+
[,bash]
----
export VERSION=$(curl -s https://api.github.com/repos/redpanda-data/redpanda/releases/latest | jq -r .tag_name)
----
+
[NOTE]
====
If you prefer to manually enter the Redpanda version, or if you want to verify the version, the following command returns the installed version:

----
curl -s https://api.github.com/repos/redpanda-data/redpanda/releases/latest | grep tag_name
----

Find information about the versions of the operator in the https://github.com/redpanda-data/redpanda/releases[list of operator releases].
====

. Install the Redpanda operator CRD with the bash or zsh:
+
[tabs]
=====
bash::
+
--
```bash
kubectl apply \
-k https://github.com/redpanda-data/redpanda/src/go/k8s/config/crd?ref=$VERSION
```

--
zsh::
+
--
```bash
noglob kubectl apply \
-k https://github.com/redpanda-data/redpanda/src/go/k8s/config/crd?ref=$VERSION
```

--
=====

. Install the Redpanda operator on your Kubernetes cluster:
+
[,bash]
----
helm install \
redpanda-operator \
redpanda/redpanda-operator \
--namespace redpanda-system \
--create-namespace \
--version $VERSION
----

== Install and connect to a Redpanda cluster

After you set up Redpanda in your Kubernetes cluster, you can use the sample configuration files in GitHub to install a cluster and see Redpanda in action.

This example is an imaginary chat application, `panda-chat`, but you can replace `panda-chat` with any string. In this example, `panda-chat` has five chat rooms.

Complete the following steps to manage a stream of events from `panda-chat`:

. Create a namespace for the cluster:
+
[,bash]
----
kubectl create ns panda-chat
----

. Install a single-node cluster like this (note that only single-node clusters are supported for local access clusters):
+
[,bash]
----
kubectl apply \
-n panda-chat \
-f https://raw.githubusercontent.com/redpanda-data/redpanda/dev/src/go/k8s/config/samples/one_node_external.yaml
----

You can view the resource configuration options, such as storage capacity, network configuration, or TLS configuration in the https://github.com/redpanda-data/redpanda/blob/dev/src/go/k8s/apis/redpanda/v1alpha1/cluster_types.go[cluster_types] file in GitHub. You can also find additional https://github.com/redpanda-data/redpanda/tree/dev/src/go/k8s/config/samples[sample configuration files].

== Check the `/etc/hosts` file

Map `0.local.rp` to `127.0.0.1` on the host machine that runs the kind cluster. The `/etc/hosts` file contains a line similar to this:

[,bash]
----
127.0.0.1 0.local.rp
----

The `local.rp` address is specified in the `one_node_external.yaml` file that you used in the previous step.

If you're running Windows, this is the location of the file:
`C:\Windows\System32\drivers\etc\hosts`

== Start streaming

Use `rpk` to run commands. `rpk` is a CLI tool you can use to work with your Redpanda nodes. See xref:reference:rpk/rpk-topic/rpk-topic.adoc[rpk Commands]. Here are some sample commands to produce and consume streams:

Create a `panda-chat` topic with five partitions:

[,bash]
----
rpk topic create panda-chat -p 5 --brokers localhost:30001
----

Produce messages to the topic:

[,bash]
----
rpk topic produce panda-chat --brokers localhost:30001
----

Type text into the topic, such as `Pandas are fabulous!`.

* Click Enter to separate between messages.
* Click Ctrl + D to exit the produce command.

Consume (or read) the messages in the topic:

[,bash]
----
rpk topic consume panda-chat --brokers localhost:30001
----

Each message is shown with its metadata, like this:

[,json]
----
{
"message": "Pandas are fabulous!\n",
"partition": 0,
"offset": 1,
"timestamp": "2022-02-10T15:52:35.251+02:00"
}
----

List the topics:

[,bash]
----
rpk topic list --brokers localhost:30001
----

== Delete the cluster

Delete the cluster:

[,bash]
----
kind delete cluster
----

For more information, see the kind https://kind.sigs.k8s.io/docs/user/quick-start/#deleting-a-cluster[Deleting a cluster] documentation.
