= rpk connect
:description: rpk connect

NAME:
   redpanda-connect - A stream processor for mundane tasks - https://docs.redpanda.com/redpanda-connect

USAGE:
   redpanda-connect [global options] command [command options]

DESCRIPTION:
   Either run Redpanda Connect as a stream processor or choose a command:

     redpanda-connect list inputs
     redpanda-connect create kafka//file > ./config.yaml
     redpanda-connect run ./config.yaml
     redpanda-connect run -r "./production/*.yaml" ./config.yaml

COMMANDS:
   echo      Parse a config file and echo back a normalised version
   lint      Parse Redpanda Connect configs and report any linting errors
   run       Run Redpanda Connect in normal mode against a specified config file
   streams   Run Redpanda Connect in streams mode
   list      List all Redpanda Connect component types
   create    Create a new Redpanda Connect config
   test      Execute Redpanda Connect unit tests
   template  Interact and generate Redpanda Connect templates
   blobl     Execute a Redpanda Connect mapping on documents consumed via stdin
   help, h   Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --version, -v  display version info, then exit (default: false)
   --help, -h     show help

== Usage

[,bash]
----

----
|===