= rpk redpanda admin brokers list
:description: rpk redpanda admin brokers list

List the brokers in your cluster.

This command lists all brokers in the cluster, active and inactive, unless they have been decommissioned.
Using the "--include-decommissioned" flag, it lists decommissioned brokers with associated UUIDs too.

The output table contains the following columns:

ID               Node ID, an exclusive identifier for a broker
HOST             Internal RPC address for communication between brokers
PORT             Internal RPC port for communication between brokers
RACK             Assigned rack ID
CORES            Number of cores (shards) on a broker
MEMBERSHIP       Whether a broker is decommissioned or not
IS-ALIVE         Whether a broker is alive or offline
VERSION          Broker version
UUID (Optional)  Additional exclusive identifier for a broker

NOTE: The UUID column is hidden when the cluster doesn't expose the UUID in the Admin API, or the API call fails to retrieve UUIDs.

== Usage

[,bash]
----
rpk redpanda admin brokers list [flags]
----

== Aliases

[,bash]
----
list, ls
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-h, --help |- |Help for list.

|-d, --include-decommissioned |- |If true, include decommissioned brokers.

|--config |string |Redpanda or rpk config file; default search paths are `/var/lib/redpanda/.config/rpk/rpk.yaml`, `$PWD/redpanda.yaml`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override rpk configuration settings; '-X help' for detail or '-X list' for terser detail.

|--profile |string |rpk profile to use.

|-v, --verbose |- |Enable verbose logging.
|===