= rpk generate grafana-dashboard
:description: rpk generate grafana-dashboard

Generate Grafana Dashboards for Redpanda Metrics

Use this command to generate sample Grafana dashboards for Redpanda metrics. 
These dashboards can be imported into a Grafana or Grafana Cloud instance.

To select a specific dashboard, use the '--dashboard' flag followed by the 
dashboard name. For example, to generate the operations dashboard, run:

    rpk generate grafana-dashboard --dashboard operations

The selected dashboard will be downloaded from our GitHub repository:

  https://github.com/redpanda-data/observability

Note that the legacy dashboard is still available as an option, and will not be 
downloaded from github. Instead, the dashboard will be generated based on the 
metrics endpoint used.

To see a list of all available dashboards, use the '--dashboard help' flag.

== Usage

[,bash]
----
rpk generate grafana-dashboard [flags]
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|--dashboard |string |The name of the dashboard you wish to download; use --dashboard help for more info (default "operations").

|-h, --help |- |Help for grafana-dashboard.

|--config |string |Redpanda or rpk config file; default search paths are `/var/lib/redpanda/.config/rpk/rpk.yaml`, `$PWD/redpanda.yaml`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override rpk configuration settings; '-X help' for detail or '-X list' for terser detail.

|--profile |string |rpk profile to use.

|-v, --verbose |- |Enable verbose logging.
|===