= Check License Status in Redpanda Console
:description: Learn how to check the status of your Redpanda Enterprise Edition license using the Redpanda Console. This topic includes steps to check license details and understand license warnings.
:page-context-switcher: [{"name": "Redpanda Console v2.x", "to": "24.3@ROOT:console:ui/check-license.adoc" },{"name": "Redpanda Console v3.x", "to": "current" } ]


You can check the expiration date of a license on the **Cluster Overview** page in Redpanda Console, under the **Licensing** section.

Redpanda Console tries to load a valid license at startup in the following order:

. From the local configuration file or environment variables.
. From the connected Redpanda cluster (if available).

== Prerequisites

- Redpanda Console must have an Enterprise Edition license. https://www.redpanda.com/try-enterprise[Request a license^] if you don't have one already.

== Check the expiration date of a license

. Go to the *Cluster Overview* page.
. Locate the *Licensing* section.
. Review the license details.

== License warnings in Redpanda Console

Redpanda Console displays warnings in the following scenarios:

- *Upcoming license expiration*: Redpanda Console checks the license status at startup. If the license expires within 30 days, a warning is displayed in the UI. Redpanda Console also logs the license details at startup, including the expiration date. For example:
+
[,json]
----
{"level":"info","msg":"successfully loaded Redpanda Enterprise license","license_org":"redpanda","license_type":"enterprise","expires_at":"Oct 12 2024"}
----

- *Redpanda Console enterprise features are in use without a valid license*: Redpanda Console fails to start if enterprise features for Redpanda Console are enabled without a valid license.
+
[,json]
----
{"level":"fatal","ts":"2024-12-16T11:27:27.308Z","msg":"Looks like you've enabled a Redpanda Enterprise feature(s) without a valid license. Please enter an active Redpanda license key. If you don't have one, please request a new/trial license at https://redpanda.com/license-request"}
----

- *Redpanda enterprise features are in use without a valid license*: If the connected Redpanda cluster is using enterprise features without a valid license, Redpanda Console displays a warning specifying the features in use without proper licensing.

== Next steps

For more detailed information about a license such as the type, organization, and a list of enterprise features that are in use, use one of the following tools:

- xref:get-started:licensing/check-status/rpk.adoc[`rpk`]
-  xref:get-started:licensing/check-status/redpanda-operator.adoc[Redpanda Operator (Kubernetes)]