= rpk acl user
:description: rpk acl user
:rpk_version: v23.2.1

Manage SCRAM users.

If SCRAM is enabled, a SCRAM user is what you use to talk to Redpanda, and ACLs
control what your user has access to. See `rpk acl --help` for more information
about ACLs, and `rpk acl user create --help` for more information about
creating SCRAM users. Using SCRAM requires setting `kafka_enable_authorization: true` and `authentication_method: sasl` in the
redpanda section of your `redpanda.yaml`, and setting `sasl_mechanisms` with `SCRAM` for your Redpanda cluster.

== Usage

[,bash]
----
rpk acl user [flags]
  rpk acl user [command]
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-h, --help |- |Help for user.

|--config |string |Redpanda or rpk config file; default search paths are
~/.config/rpk/rpk.yaml, $PWD, and /etc/redpanda/redpanda.yaml.

|-X, --config-opt |stringArray |Override rpk configuration settings; '-X
help' for detail or '-X list' for terser detail.

|--profile |string |rpk profile to use.

|-v, --verbose |- |Enable verbose logging.
|===

