= rpk acl user create
:description: rpk acl user create
:rpk_version: v23.2.1

Create a SASL user.

This command creates a single SASL user with the given password, optionally
with a custom mechanism. SASL consists of three parts: a username, a
password, and a mechanism. The mechanism determines which authentication flow
the client will use for this user/pass.

Redpanda currently supports two mechanisms: SCRAM-SHA-256, the default, and
SCRAM-SHA-512, which is the same flow but uses sha512 rather than sha256.

Using SASL requires setting `enable_sasl: true` in the redpanda section of your
`redpanda.yaml`. Before a created SASL account can be used, you must also create
ACLs to grant the account access to certain resources in your cluster. See the
acl help text for more info.

== Usage

[,bash]
----
rpk acl user create [USER] -p [PASS] [flags]
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-h, --help |- |Help for create.

|--mechanism |string |SASL mechanism to use for the user you are
creating (`scram-sha-256`, `scram-sha-512`, case insensitive) (default:
`scram-sha-256`).

|--password |string |New user's password (NOTE: if using --password for
the admin API, use --new-password).

|--config |string |Redpanda or rpk config file; default search paths are
~/.config/rpk/rpk.yaml, $PWD, and /etc/redpanda/redpanda.yaml.

|-X, --config-opt |stringArray |Override rpk configuration settings; '-X
help' for detail or '-X list' for terser detail.

|--format |string |Output format. Possible values: `json`,`yaml`,`text`,`wide`,`help`. Default: `text`.

|--profile |string |rpk profile to use.

|-v, --verbose |- |Enable verbose logging.
|===
