= rpk transform deploy
:description: Deploy a data transform.

Deploy a data transform.

To deploy a data transform configured by a `transform.yaml` configuration file, run the `rpk transform deploy` command in the same directory as `transform.yaml`. The command reads the Wasm bundle with the same name as project. The names of the input and output topics for the transform are read either from `transform.yaml` (if they're specified) or from the command line flags `--input-topic` and `--output-topic`.

Alternatively, to deploy a data transform without a `transform.yaml` configuration file, specify on the command line both the Wasm bundle and the name of the transform:

```bash
rpk transform deploy transform.wasm --name myTransform
```

== Usage

```bash
rpk transform deploy [flags]
```

== Flags

[cols="1m,1a,2a"]
|===
| *Value* | *Type* | *Description*

| -h, --help
| -
| Help for transform.

| --config
| string
| Redpanda or rpk config file; default search paths are ~/.config/rpk/rpk.yaml, $PWD, and /etc/redpanda/`redpanda.yaml`.

| -X, --config-opt
| stringArray
| Override rpk configuration settings; '-X help' for detail or '-X list' for terser detail.

| --profile
| string
| rpk profile to use.

| -v, --verbose
| -
| Enable verbose logging.
|===