= IAM Roles
:description: For self-hosted clusters deployed on a public cloud platform, cloud provider IAM roles provide a safer alternative to the less secure static credential system, which is based on access keys.
:page-aliases: security:iam-roles.adoc
:page-categories: Management, Security


For self-hosted clusters deployed on a public cloud platform, cloud provider IAM roles (also known as managed identities) provide a safer alternative to the less secure static credential system, which is based on access keys. With static credentials, the access key and secret key are stored in plaintext in the configuration file. IAM roles are safer because they supply a role with temporary credentials that are dynamically sourced at runtime, and only last for the duration of a single session. These credentials allow you to access the data stored in an S3 bucket or Google Cloud Storage, as well as other resources.

You can use IAM roles with any Redpanda feature that makes use of cloud storage, such as xref:manage:tiered-storage.adoc[Tiered Storage] or xref:manage:remote-read-replicas.adoc[Remote Read Replicas].

NOTE: IAM roles can only be configured for clusters deployed on a public cloud platform, such as Amazon Web Services (AWS) or Google Cloud Platform (GCP). You cannot use IAM roles with on-premises clusters, even if you are using a feature that makes use of cloud storage. For on-premises clusters, you must use static access keys.

== Prerequisites

Before you can configure IAM roles in Redpanda, you must create a cloud storage bucket and create an IAM policy that will be used to access that bucket. An IAM policy specifies which operations can be performed, such as writing to and reading from a cloud storage bucket, and which resources can be accessed.

=== AWS prerequisites

If you are using Amazon Web Services (AWS) as your cloud provider, you must satisfy the following prerequisites:

. https://docs.aws.amazon.com/AmazonS3/latest/userguide/creating-bucket.html[Create an S3 storage bucket^].
. https://aws.amazon.com/blogs/security/writing-iam-policies-how-to-grant-access-to-an-amazon-s3-bucket/[Create an IAM policy^].
. https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_job-functions_create-policies.html[Create an IAM role and assign the policy to that role^].
. Tiered Storage with AWS requires that the user have the following permissions to read and create objects on the bucket to be used with the cluster (or on all buckets): `GetObject`, `DeleteObject`, `PutObject`, `PutObjectTagging`, `ListBucket`.
. https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html#attach-iam-role[Bind the VM^], or https://docs.aws.amazon.com/eks/latest/userguide/specify-service-account-role.html[Pod in the case of Kubernetes^], to the IAM role.

CAUTION: `GetObject`, `DeleteObject`, `PutObject`, `PutObjectTagging`, and `ListBucket` are required to fully utilize cloud storage. If the bucket is dedicated to Redpanda, we recommend allowing all (*) actions within the bucket.

==== Sample full access IAM policy

The following example policy grants full access to the `test` S3 bucket.

[,json]
----
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
	        "arn:aws:s3:::test",
	        "arn:aws:s3:::test/*"
	    ]
        }
    ]
}
----

==== Sample minimum read/write IAM policy

This policy represents a minimum IAM policy for the `test` S3 buckets required when using Tiered Storage.

[,json]
----
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:PutObjectTagging",
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": "arn:aws:s3:::test/*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": "arn:aws:s3:::test"
        }
    ]
}
----

==== Sample read-only IAM policy

A more restrictive "read-only" IAM policy is shown below. This policy only allows a user to get and list objects in the `test` S3 bucket. Such a policy could be used for a read replica topic on a remote cluster that hosts read replica topics, but not Tiered Storage topics.

[,json]
----
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject"
            ],
            "Resource": [
	        "arn:aws:s3:::test/*"
	    ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": "arn:aws:s3:::test"
        }
    ]
}
----

=== GCP prerequisites

If you are using Google Cloud Platform as your cloud provider, you must satisfy the following prerequisites:

. https://cloud.google.com/storage/docs/creating-buckets[Create a storage bucket^].
. https://cloud.google.com/iam/docs/policies[Create an IAM policy^] that specifies the principal, the role, and the role binding. For examples, see the https://cloud.google.com/iam/docs/granting-changing-revoking-access#iam-grant-single-role-gcloud[Google Cloud documentation^].

NOTE: A full access policy with all storage bucket permissions is required for Tiered Storage.

=== Azure prerequisites

If you are using Microsoft Azure as your cloud provider, you must satisfy the following prerequisites:

. https://learn.microsoft.com/en-us/azure/storage/common/storage-account-create?tabs=azure-portal#create-a-storage-account-1[Create an Azure storage account]^.
. https://learn.microsoft.com/en-us/azure/storage/blobs/blob-containers-portal#create-a-container[Create a container] in the storage account.
. https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/how-manage-user-assigned-managed-identities?pivots=identity-mi-methods-azp#create-a-user-assigned-managed-identity[Create a user-assigned managed identity] with the appropriate permissions.
. Assign the identity to the container.

== Configuring IAM roles

After satisfying the prerequisites for your cloud platform, edit the Redpanda cluster configuration by running `rpk cluster config edit`. Set the xref:reference:cluster-properties.adoc#cloud-storage-credentials-source[`cloud_storage_credentials_source`] property to the appropriate value for your use case. The following table shows all possible values and their descriptions.

|===
| Value | Description

| `config_file` (default)
| If IAM roles are not available, specify credentials in the cluster configuration file.

| `aws_instance_metadata`
| For an AWS EC2 instance, use the instance metadata API from AWS.

| `sts`
| For AWS on Kubernetes, use the Secure Token Service (STS).

| `gcp_instance_metadata`
| For a VM running on GCP, or for Google Kubernetes Engine (GKE), use the instance metadata API from GCP.

| `azure_vm_instance_metadata`
| For a VM running on Azure, use the Instance Metadata Service (IMDS) from Azure.
|===
