= rpk group offset-delete
:description: rpk group offset-delete
:rpk_version: v23.1.6 (rev cc47e1ad1)

Forcefully delete offsets for a Kafka group.

The broker will only allow the request to succeed if the group is in a dead
state (no subscriptions) or there are no subscriptions for offsets for
topic/partitions requested to be deleted.

Use either the `--from-file` or the `--topic` option. They are mutually exclusive.
To indicate which topics or topic partitions you'd like to remove offsets from use
the `--topic` (`-t`) flag, followed by a comma separated list of partition IDs. Supplying
no list will delete all offsets for all partitions for a given topic.

You may also provide a text file to indicate topic/partition tuples. Use the
`--from-file` flag for this option. The file must contain lines of topic/partitions
separated by a tab or space. Example:

----
topic_a 0
topic_a 1
topic_b 0
----

== Usage

[,bash]
----
rpk group offset-delete [GROUP] --from-file FILE --topic foo:0,1,2 [flags]
----

== Flags

////
[cols=",,",]
|===
|*Value* |*Type* |*Description*

|-f, --from-file |string |File of topic/partition tuples for which to
delete offsets for.

|-h, --help |- |Help for offset-delete.

|-t, --topic |stringArray |topic:partition_id (repeatable; e.g. -t
foo:0,1,2 ).

|--brokers |strings |Comma-separated list of broker ip:port pairs (e.g.
--brokers '192.168.78.34:9092,192.168.78.35:9092,192.179.23.54:9092').
Alternatively, you may set the REDPANDA_BROKERS environment variable
with the comma-separated list of broker addresses.

|--config |string |Redpanda config file, if not set the file will be
searched for in the default locations.

|--password |string |SASL password to be used for authentication.

|--sasl-mechanism |string |The authentication mechanism to use.
Supported values: SCRAM-SHA-256, SCRAM-SHA-512.

|--tls-cert |string |The certificate to be used for TLS authentication
with the broker.

|--tls-enabled |- |Enable TLS for the Kafka API (not necessary if
specifying custom certs).

|--tls-key |string |The certificate key to be used for TLS
authentication with the broker.

|--tls-truststore |string |The truststore to be used for TLS
communication with the broker.

|--user |string |SASL user to be used for authentication.

|-v, --verbose |- |Enable verbose logging (default: false).
|===
////
