= rpk container status

Get a local container's status.

== Usage

[,bash]
----
rpk container status [flags]
----

== Example

If you're following xref:get-started:quick-start.adoc#tabs-1-three-brokers[QuickStart -  Deploy Redpanda to Docker with Three Nodes], you can run `rpk container status` to see more information about your containers:

[,bash]
----
$ rpk container status
    NODE-ID  STATUS   KAFKA-ADDRESS    ADMIN-ADDRESS    PROXY-ADDRESS    
    0        running  127.0.0.1:34189  127.0.0.1:36539  127.0.0.1:41235  
    1        running  127.0.0.1:45523  127.0.0.1:35135  127.0.0.1:40155  
    2        running  127.0.0.1:37223  127.0.0.1:42571  127.0.0.1:41907  

You can use rpk to interact with this cluster. For example:

    rpk cluster info --brokers 127.0.0.1:34189,127.0.0.1:45523,127.0.0.1:37223

You may also set an environment variable with the comma-separated list of
broker addresses:

    export REDPANDA_BROKERS="127.0.0.1:34189,127.0.0.1:45523,127.0.0.1:37223"
    rpk cluster info
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-h, --help |- |Help for status.

|--config |string |Redpanda or `rpk` config file. Default search paths are
`~/.config/rpk/rpk.yaml`, `$PWD`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override `rpk` configuration settings. See xref:reference:rpk/rpk-x-options.adoc[`rpk -X`] or execute `rpk -X help` for inline detail or `rpk -X list` for terser detail.

|--profile |string |Profile to use. See xref:reference:rpk/rpk-profile.adoc[`rpk profile`] for more details.

|-v, --verbose |- |Enable verbose logging.
|===

