= rpk container status
// tag::single-source[]

Get a local container's status.

== Usage

[,bash]
----
rpk container status [flags]
----

== Example

ifndef::env-cloud[]
If you're following xref:get-started:quick-start.adoc#tabs-1-three-brokers[QuickStart -  Deploy Redpanda to Docker with Three Nodes], you can run `rpk container status` to see more information about your containers:

endif::[]

[,bash]
----
rpk container status
NODE-ID  STATUS   KAFKA-ADDRESS   ADMIN-ADDRESS   PROXY-ADDRESS   SCHEMA-REGISTRY-ADDRESS
0        running  127.0.0.1:9092  127.0.0.1:9644  127.0.0.1:8082  127.0.0.1:8081

Redpanda Console started in: http://localhost:8080

You can use rpk to interact with this cluster. E.g:

    rpk cluster info
    rpk cluster health

You may also set an environment variable with the comma-separated list of
broker addresses:

    export REDPANDA_BROKERS="127.0.0.1:34189,127.0.0.1:45523,127.0.0.1:37223"
    rpk cluster info
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-h, --help |- |Help for status.

|--config |string |Redpanda or `rpk` config file; default search paths are `/var/lib/redpanda/.config/rpk/rpk.yaml`, `$PWD/redpanda.yaml`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override `rpk` configuration settings. See xref:reference:rpk/rpk-x-options.adoc[`rpk -X`] or execute `rpk -X help` for inline detail or `rpk -X list` for terser detail.

|--profile |string |Profile to use. See xref:reference:rpk/rpk-profile.adoc[`rpk profile`] for more details.

|-v, --verbose |- |Enable verbose logging.
|===

// end::single-source[]