= HeaderFrom
:description: HeaderFrom Single Message Transform for a connector to move or copy fields in the key or value of a record into that record's headers.
:page-cloud: true

HeaderFrom SMT moves or copies fields in the key or value of a record into that record's headers. Corresponding elements of `fields` and `headers` together identify a field and the header it should be moved or copied to.

Use the concrete transformation type designed for the record key (`org.apache.kafka.connect.transforms.HeaderFrom$Key`) or value (`org.apache.kafka.connect.transforms.HeaderFrom$Value`).

== Configuration

|=== 
| Property key | Description

| `fields`
| Comma-separated list of field names in the record whose values are to be copied or moved to headers.

| `headers`
| Comma-separated list of header names, in the same order as the field names listed in the fields configuration property.

| `operation`
| Either `move` if the fields are to be moved to the headers (removed from the key/value), or `copy` if the fields are to be copied to the headers (retained in the key/value).
|===

== Example

----
"transforms": "HeaderFrom",
"transforms.HeaderFrom.type": "org.apache.kafka.connect.transforms.HeaderFrom$Value",
"transforms.HeaderFrom.fields": "id,last_login_ts",
"transforms.HeaderFrom.headers": "user_id,timestamp",
"transforms.HeaderFrom.operation": "move"
----

Before:

* Record value:
[source,json]
----
{
    "id": 11,
    "name": "Harry Wilson",
    "last_login_ts": 1715242380
}
----

* Record header:
[source,json]
----
{
    "conv_id": "uier923"
}
----

After:

* Record value:
[source,json]
----
{
    "name": "Harry Wilson"
}
----

* Record header:
[source,json]
----
{
    "conv_id": "uier923",
    "user_id": 11,
    "timestamp": 1715242380
}
----