= TimestampConverter
:description: How to set TimestampConverter Single Message Transform for a connector to convert timestamps between different formats.
:page-cloud: true

The TimestampConverter SMT converts timestamps between different formats such as Unix epoch, strings, and Connect Date/Timestamp types. Applies to individual fields or to the entire value.

Use the concrete transformation type designed for the record key (`org.apache.kafka.connect.transforms.TimestampConverter$Key`) or value (`org.apache.kafka.connect.transforms.TimestampConverter$Value`).

== Configuration

|=== 
| Property key | Description

| `field`
| The field containing the timestamp, or empty if the entire value is a timestamp. Default: `""`.

| `target.type`
| The desired timestamp representation: `string`, `unix`, `Date`, `Time`, or `Timestamp`.

| `format`
| A `SimpleDateFormat`-compatible format for the timestamp. Used to generate the output when `target.type=string` or used to parse the input if the input is a string. Default: `""`.

| `unix.precision`
| The desired Unix precision for the timestamp: seconds, milliseconds, microseconds, or nanoseconds. Used to generate the output when type=unix or used to parse the input if the input is a Long. Note: This SMT will cause precision loss during conversions from, and to, values with sub-millisecond components. Default: `milliseconds`.

|===

== Example

Sample configuration:

----
"transforms": "TimestampConverter",
"transforms.TimestampConverter.type": "org.apache.kafka.connect.transforms.TimestampConverter$Value",
"transforms.TimestampConverter.field": "last_login_date",
"transforms.TimestampConverter.format": "yyyy-MM-dd",
"transforms.TimestampConverter.target.type": "string"
----

Before: `1702041416`

After: `2023-12-08`