= Cast (Redpanda)
:description: How to set Cast (Redpanda) Single Message Transform for a connector.
:page-cloud: true

Cast (Redpanda) SMT casts fields or the entire key or value to a specific type, e.g. to force an integer field to a smaller width. Cast from integers, floats, boolean and string to any other type, and cast binary to string (base64 encoded).

Use the concrete transformation type designed for the record key (`com.redpanda.connectors.transforms.RedpandaCast$Key`) or value (`com.redpanda.connectors.transforms.RedpandaCast$Value`).

NOTE: Cast (Redpanda) SMT is designed to be used with MirrorMaker2 connector only.

== Configuration

|=== 
| Property key | Description

| `spec`
| Comma-separated list of fields and the type to cast them to of the form `field1:type,field2:type` to cast fields of Maps or Structs. A single type to cast the entire value. Valid types are `int8`, `int16`, `int32`, `int64`, `float32`, `float64`, `boolean`, and `string`. Note that binary fields can only be cast to `string`.
|===

== Example

Sample configuration:

----
"transforms": "RedpandaCast",
"transforms.RedpandaCast.type": "com.redpanda.connectors.transforms.RedpandaCast$Value",
"transforms.RedpandaCast.spec": "field1:int32,field2:string"
----
