= rpk topic consume

Consume records from topics.

Consuming records reads from any amount of input topics, formats each record
according to `--format`, and prints them to `STDOUT`. The output formatter
understands a wide variety of formats.

The default output format `--format json` is a special format that outputs each
record as JSON.

include::reference:partial$topic-format.adoc[]

== Attributes

Each record (or batch of records) has a set of possible attributes. Internally,
these are packed into bit flags. Printing an attribute requires first selecting
which attribute you want to print, and then optionally specifying how you want
it to be printed:

[,bash]
----
%a{compression}
%a{compression;number}
%a{compression;big64}
%a{compression;hex8}
----

Compression is by default printed as text (`none`, `gzip`, ...). Compression
can be printed as a number with `;number`, where number is any number
formatting option described above. No compression is `0`, gzip is `1`, etc.

[,bash]
----
%a{timestamp-type}
%a{timestamp-type;big64}
----

The record's timestamp type prints as:

*  `-1` for very old records (before timestamps existed)
*  `0` for client-generated timestamps
*  `1` for broker-generated timestamps

NOTE: Number formatting can be controlled with `;number`.

[,bash]
----
%a{transactional-bit}
%a{transactional-bit;bool}
----

Prints `1` if the record is a part of a transaction or `0` if it is not.

[,bash]
----
%a{control-bit}
%a{control-bit;bool}
----

Prints `1` if the record is a commit marker or `0` if it is not.

=== Text

Text fields without modifiers default to writing the raw bytes. Alternatively,
there are the following modifiers:

[cols=",",]
|===
|Modifier |Description

|`%t\{hex}` |Hex encoding

|`%k\{base64}` |Base64 standard encoding

|`%k\{base64raw}` |Base64 encoding raw

|`%v{unpack[<bBhH>iIqQc.$]}` |The unpack modifier has a further internal
specification, similar to timestamps above.
|===

Unpacking text can allow translating binary input into readable output. If a
value is a big-endian uint32, `%v` prints the raw four bytes, while
`%v{unpack[>I]}` prints the number in as ASCII. If unpacking exhausts the
input before something is unpacked fully, an error message is appended to the
output.

=== Headers

Headers are formatted with percent encoding inside of the modifier:

```
%h{%k=%v{hex}}
```

This prints all headers with a space before the key and after the value, an
equals sign between the key and value, and with the value hex encoded. Header
formatting actually just parses the internal format as a record format, so all
of the above rules about `%K`, `%V`, text, and numbers apply.

=== Examples

A key and value, separated by a space and ending in newline:

```
-f '%k %v\n'
```

A key length as four big endian bytes and the key as hex:

```
-f '%K{big32}%k{hex}'
```

A little endian uint32 and a string unpacked from a value:

```
-f '%v{unpack[is$]}'
```

=== Offsets

The `--offset` flag allows for specifying where to begin consuming, and
optionally, where to stop consuming. The literal words `start` and `end`
specify consuming from the start and the end.

[cols=",",]
|===
|Offset |Description

|`start` |Consume from the beginning
|`end` |Consume from the end
|`:end` |Consume until the current end
|`+oo` |Consume oo after the current start offset
|`-oo` |Consume oo before the current end offset
|`oo` |Consume after an exact offset
|`oo:` |Alias for oo
|`:oo` |Consume until an exact offset
|`o1:o2` |Consume from exact offset o1 until exact offset o2
|`@t` |Consume starting from a given timestamp
|`@t:` |alias for @t
|`@:t` |Consume until a given timestamp
|`@t1:t2` |Consume from timestamp t1 until timestamp t2
|===

Each timestamp option is evaluated until one succeeds.

[cols=",",]
|===
|Timestamp |Description

|13 digits |Parsed as a unix millisecond

|9 digits |Parsed as a unix second

|YYYY-MM-DD |Parsed as a day, UTC

|YYYY-MM-DDTHH:MM:SSZ |Parsed as RFC3339, UTC; fractional seconds
optional (.MMM)

|-dur |Duration; from now (as t1) or from t1 (as t2)

|dur |For t2 in @t1:t2, relative duration from t1

|end |For t2 in @t1:t2, the current end of the partition
|===

Durations are parsed simply:

```
3ms    three milliseconds
10s    ten seconds
9m     nine minutes
1h     one hour
1m3ms  one minute and three milliseconds
```

For example:

```
-o @2022-02-14:1h   consume 1h of time on Valentine's Day 2022
-o @-48h:-24h       consume from 2 days ago to 1 day ago
-o @-1m:end         consume from 1m ago until now
-o @:-1hr           consume from the start until an hour ago
```

== Usage

[,bash]
----
rpk topic consume TOPICS... [flags]
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-b, --balancer |string |Group balancer to use if group consuming
(range, roundrobin, sticky, cooperative-sticky) (default
"cooperative-sticky").

|--fetch-max-bytes |int32 |Maximum amount of bytes per fetch request per
broker (default 1048576).

|--fetch-max-wait |duration |Maximum amount of time to wait when
fetching from a broker before the broker replies (default 5s).

|-f, --format |string |Output format (see --help for details) (default
"json").

|-g, --group |string |Group to use for consuming (incompatible with -p).

|-h, --help |- |Help for consume.

|--meta-only |- |Print all record info except the record value (for -f
json).

|-n, --num |int |Quit after consuming this number of records (0 is
unbounded).

|-o, --offset |string |Offset to consume from / to (start, end, 47, +2,
-3) (default "start").

|-p, --partitions |int32 |int32Slice Comma delimited list of specific
partitions to consume (default []).

|--pretty-print |- |Pretty print each record over multiple lines (for -f
json) (default true).

|--print-control-records |- |Opt in to printing control records.

|--rack |string |Rack to use for consuming, which opts into follower
fetching.

|--read-committed |- |Opt in to reading only committed offsets.

|-r, --regex |- |Parse topics as regex; consume any topic that matches
any expression.

|--use-schema-registry |strings |[=key,value]   If present, `rpk` will decode the key and the value with the schema registry. Also accepts `use-schema-registry=key` or `use-schema-registry=value`.

|--config |string |Redpanda or `rpk` config file. Default search paths are: 
`~/.config/rpk/rpk.yaml`, `$PWD`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override `rpk` configuration settings. See xref:reference:rpk/rpk-x-options.adoc[`rpk -X`] or execute `rpk -X help` for inline detail or `rpk -X list` for terser detail.

|--profile |string |Profile to use. See xref:reference:rpk/rpk-profile.adoc[`rpk profile`] for more details.

|-v, --verbose |- |Enable verbose logging.
|===

