= rpk topic trim-prefix

Trim records from topics

This command allows you to trim records from topics, where Redpanda
sets the LogStartOffset for partitions to the requested offset. All segments
whose base offset is less then the requested offset are deleted, and any records
within the segment before the requested offset can no longer be read.

The `--offset/-o` flag allows you to indicate which index you want to set the
partition's low watermark (start offset) to. It can be a single integer value
denoting the offset, or a timestamp if you prefix the offset with an '@'. You may
select which partition you want to trim the offset from with the `--partition/-p`
flag.

The `--from-file` option allows to trim the offsets specified in a text file with
the following format:

----
[TOPIC] [PARTITION] [OFFSET]
[TOPIC] [PARTITION] [OFFSET]
...
----

or the equivalent keyed JSON/YAML file.

== Examples

* Trim records in 'foo' topic to offset 120 in partition 1:
+
[,bash]
----
rpk topic trim-prefix foo --offset 120 --partition 1
----

* Trim records in all partitions of topic foo previous to an specific timestamp:
+
[,bash]
----
rpk topic trim-prefix foo -o "@1622505600"
----

* Trim records from a JSON file:
+
[,bash]
----
rpk topic trim-prefix --from-file /tmp/to_trim.json
----

== Usage

[,bash]
----
rpk topic trim-prefix [TOPIC] [flags]
----

== Aliases

[,bash]
----
trim-prefix, trim
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-f, --from-file |string |File of topic/partition/offset for which to
trim offsets for.

|-h, --help |- |Help for trim-prefix.

|--no-confirm |- |Disable confirmation prompt.

|-o, --offset |string |Offset to set the partition's start offset to,
either as an integer or timestamp (`@<timestamp-value>`).

|-p, --partitions |int32 |int32Slice Comma-separated list of partitions
to trim records from (default to all) (default []).

|--config |string |Redpanda or rpk config file; default search paths are `/var/lib/redpanda/.config/rpk/rpk.yaml`, `$PWD/redpanda.yaml`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override `rpk` configuration settings. See xref:reference:rpk/rpk-x-options.adoc[`rpk -X`] or execute `rpk -X help` for inline detail or `rpk -X list` for terser detail.

|--profile |string |Profile to use. See xref:reference:rpk/rpk-profile.adoc[`rpk profile`] for more details.

|-v, --verbose |- |Enable verbose logging.
|===

