= rpk topic create
:description: rpk topic create
:rpk_version: v23.1.6 (rev cc47e1ad1)

Create topics.

All topics created with this command will have the same number of partitions,
replication factor, and key/value configs.

For example,

----
rpk topic create -c cleanup.policy=compact -r 3 -p 20 foo bar
----

will create two topics, `foo` and `bar`, each with 20 partitions, 3 replicas, and the `cleanup.policy=compact` config option set.

== Usage

[,bash]
----
rpk topic create [TOPICS...] [flags]
----

== Flags


[cols=",,",]
|===
|*Value* |*Type* |*Description*

|-d, --dry |- |Dry run: validate the topic creation request; do not
create topics.

|-h, --help |- |Help for create.

|-p, --partitions |int32 |Number of partitions to create per topic; -1
defaults to the cluster's default_topic_partitions (default -1).

|-r, --replicas |int16 |Replication factor (must be odd); -1 defaults to
the cluster's default_topic_replications (default -1).

|-c, --topic-config |stringArray |key=value; Config parameters
(repeatable; for example `-c cleanup.policy=compact)`.

|--brokers |strings |Comma-separated list of broker <ip>:<port> pairs
(for example,
` --brokers '192.168.78.34:9092,192.168.78.35:9092,192.179.23.54:9092' `
). Alternatively, you may set the `REDPANDA_BROKERS` environment
variable with the comma-separated list of broker addresses.

|--config |string |Redpanda config file, if not set the file will be
searched for in the default locations.

|--password |string |SASL password to be used for authentication.

|--sasl-mechanism |string |The authentication mechanism to use.
Supported values: `SCRAM-SHA-256`, `SCRAM-SHA-512`.

|--tls-cert |string |The certificate to be used for TLS authentication
with the broker.

|--tls-enabled |- |Enable TLS for the Kafka API (not necessary if
specifying custom certs).

|--tls-key |string |The certificate key to be used for TLS
authentication with the broker.

|--tls-truststore |string |The truststore to be used for TLS
communication with the broker.

|--user |string |SASL user to be used for authentication.

|-v, --verbose |- |Enable verbose logging (default `false`).
|===

