= rpk topic delete

Delete topics.

This command deletes all requested topics, printing the success or fail status
per topic.

The `--regex` or `-r` flag opts into parsing the input topics as regular expressions
and deleting any non-internal topic that matches any of expressions. The input
expressions are wrapped with `^` and `$` so that the expression must match the
whole topic name (which also prevents accidental delete-everything mistakes).

The topic list command accepts the same input regex format as this delete
command. If you want to check what your regular expressions will delete before
actually deleting them, you can check the output of `rpk topic list -r`.

== Examples

Deletes topics foo and bar:

[,bash]
----
rpk topic  delete foo bar
----

Deletes any topic starting with `f` and any topics ending in `r`:

[,bash]
----
rpk topic  delete -r '^f.*' '.*r$'
----

Deletes all topics:

[,bash]
----
rpk topic  delete -r '.*'
----

Deletes any one-character topics:

== Usage

[,bash]
----
rpk topic delete [TOPICS...] [flags]
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-h, --help |- |Help for delete.

|-r, --regex |- |Parse topics as regex; delete any topic that matches
any input topic expression.

|--config |string |Redpanda or `rpk` config file; default search paths are `/var/lib/redpanda/.config/rpk/rpk.yaml`, `$PWD/redpanda.yaml`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override `rpk` configuration settings. See xref:reference:rpk/rpk-x-options.adoc[`rpk -X`] or execute `rpk -X help` for inline detail or `rpk -X list` for terser detail.

|--profile |string |Profile to use. See xref:reference:rpk/rpk-profile.adoc[`rpk profile`] for more details.

|-v, --verbose |- |Enable verbose logging.
|===

