:node: node
ifdef::env-kubernetes[]
:node: worker node
endif::[]

== Operating system

- Minimum version required of RHEL/CentOS: {supported-rhel-required}. *Recommended*: {supported-rhel-recommended}

- Minimum version required of Ubuntu: {supported-ubuntu-required}. *Recommended*: {supported-ubuntu-recommended}

ifdef::env-kubernetes[]
== Kubernetes version

Minimum required Kubernetes version: {supported-kubernetes-version}

Make sure to do the following:

. https://kubernetes.io/docs/tasks/tools/[Install kubectl^].
. https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/[Configure the `kubeconfig` file for your cluster^].

== Helm version

Minimum required Helm version: {supported-helm-version}

https://helm.sh/docs/intro/install/[Install Helm^].
endif::[]

== Number of {node}s

Provision one physical node or virtual machine (VM) for each Redpanda broker that you plan to deploy in your Redpanda cluster.
Each Redpanda broker requires its own dedicated {node} for the following reasons:

- *Resource isolation*: Redpanda brokers are designed to make full use of available system resources, including CPU and memory. By dedicating a {node} to each broker, you ensure that these resources aren't shared with other applications or processes, avoiding potential performance bottlenecks or contention.
- *External networking*: External clients should connect directly to the broker that owns the partition they're interested in. This means that each broker must be individually addressable. As clients must connect to the specific broker that is the leader of the partition, they need a mechanism to directly address each broker in the cluster. Assigning each broker to its own dedicated {node} makes this direct addressing feasible, since each {node} will have a unique address. See <<External networking>>.
- *Fault tolerance*: Ensuring each broker operates on a separate node enhances fault tolerance. If one node experiences issues, it won't directly impact the other brokers.

ifdef::env-kubernetes[]
NOTE: The Redpanda Helm chart configures xref:reference:redpanda-helm-spec.adoc#statefulset-podantiaffinity[`podAntiAffinity` rules] to make sure that each Redpanda broker runs on its own {node}.


*Recommendations*: xref:./kubernetes-deploy.adoc#pod-replicas[Deploy at least three Pod replicas].
endif::[]

ifndef::env-kubernetes[]
*Recommendations*: Deploy at least three Redpanda brokers.
endif::[]

== CPU and memory

*Requirements*:

- Two physical, not virtual, cores for each {node}.

- x86_64 (Westmere or newer) and AWS Graviton family processors are supported.

- 2 GB or more of memory per core.

- 4 MB of memory for each topic partition replica. You can enforce this requirement in the tunable xref:reference:tunable-properties.adoc#topic_memory_per_partition[`topic_memory_per_partition` property].

*Recommendations*:

- Four physical cores for each {node} are strongly recommended.

ifdef::env-kubernetes[]
- xref:./kubernetes-deploy.adoc#resources[Set resource requests and limits for memory and CPU].
endif::[]

== Storage

*Requirements*:

- An XFS or ext4 file system.
+
The Redpanda data directory (`/var/lib/redpanda/data`) and the Tiered Storage cache must be mounted on an XFS or ext4 file system.
ifdef::env-kubernetes[]
+
For information about supported volume types for different data in Redpanda, see xref:manage:kubernetes/storage/volume-types.adoc[].
endif::[]
+
CAUTION: Avoid using NFS (Network File System) for the Redpanda data directory or the Tiered Storage cache.

ifdef::env-kubernetes[- A default StorageClass that can provision PersistentVolumes with at least 20Gi of storage.]

*Recommendations*:

- Use an XFS file system for its enhanced performance with Redpanda workloads.

- For setups with multiple disks, use a RAID-0 (striped) array. It boosts speed but lacks redundancy. A disk failure can lead to data loss.
ifdef::env-kubernetes[]
- xref:./kubernetes-deploy.adoc#storage[Use local PersistentVolumes backed by NVMe disks].
endif::[]

== Security

*Recommendations*:

- If you're using a cloud platform, use xref:manage:security/iam-roles.adoc[IAM roles] to restrict access to resources in your cluster.

- Secure your Redpanda cluster with TLS encryption and SASL authentication.

== External networking

- For external access, each {node} in your cluster must have a static, externally accessible IP address.

- Minimum 10 GigE (10 Gigabit Ethernet) connection to ensure:

* High data throughput
* Reduced data transfer latency
* Scalability for increased network traffic

ifdef::env-kubernetes[]
*Recommendations*: xref:deploy:deployment-option/self-hosted/kubernetes/kubernetes-deploy.adoc#external-access[Use a NodePort Service for external access].
endif::[]

== Tuning

Before deploying Redpanda to production, each {node} that runs Redpanda must be tuned to optimize the Linux kernel for Redpanda processes.

ifdef::env-kubernetes[]
See xref:deploy:deployment-option/self-hosted/kubernetes/kubernetes-tune-workers.adoc[].
endif::[]
ifndef::env-kubernetes[]
See xref:deploy:deployment-option/self-hosted/manual/production/production-deployment.adoc[].
endif::[]

== Object storage providers for Tiered Storage

Redpanda supports the following storage providers for Tiered Storage:

- Amazon Simple Storage Service (S3)
- Google Cloud Storage (GCS), using the Google Cloud Platform S3 API
- Azure Blob Storage (ABS)

== Cloud instance types

*Recommendations*:

- Use a cloud instance type that supports locally attached NVMe devices with an XFS file system. NVMe devices offer high I/O operations per second (IOPS) and minimal latency, while XFS offers enhanced performance with Redpanda workloads.

=== Amazon

ifdef::env-kubernetes[EKS defaults to the ext4 file system. Use XFS instead where possible.]

- General purpose: General-purpose instances provide a balance of compute, memory, and networking resources, and they can be used for a variety of diverse workloads.
+
[.two-column]
** https://aws.amazon.com/ec2/instance-types/m5/[M5d^]
** https://aws.amazon.com/ec2/instance-types/m5/[M5ad^]
** https://aws.amazon.com/ec2/instance-types/m5/[M5dn^]
** https://aws.amazon.com/ec2/instance-types/m6g/[M6gd^]
** https://aws.amazon.com/ec2/instance-types/m7g/[M7gd^]

- Memory optimized: Memory-optimized instances are designed to deliver fast performance for workloads that process large data sets in memory.
+
[.two-column]
** https://aws.amazon.com/ec2/instance-types/r5/[R5ad^]
** https://aws.amazon.com/ec2/instance-types/r5/[R5d^]
** https://aws.amazon.com/ec2/instance-types/r5/[R5dn^]
** https://aws.amazon.com/ec2/instance-types/r6g/[R6gd^]
** https://aws.amazon.com/ec2/instance-types/r6i/[R6id^]
** https://aws.amazon.com/ec2/instance-types/r6i/[R6idn^]
** https://aws.amazon.com/ec2/instance-types/r7g/[R7gd^]
** https://aws.amazon.com/ec2/instance-types/x2/[X2gd^]
** https://aws.amazon.com/ec2/instance-types/x2i/[X2idn^]
** https://aws.amazon.com/ec2/instance-types/x2i/[X2iedn^]
** https://aws.amazon.com/ec2/instance-types/z1d/[z1d^]

- Storage optimized: Storage-optimized instances are designed for workloads that require high, sequential read and write access to very large data sets on local storage. They are optimized to deliver tens of thousands of low-latency, random IOPS to applications.

** https://aws.amazon.com/ec2/instance-types/i3/[I3^]
** https://aws.amazon.com/ec2/instance-types/i3en/[I3en^]

- Compute optimized: Compute-optimized instances deliver cost-effective high performance at a low price per compute ratio for running advanced compute-intensive workloads.

** https://aws.amazon.com/ec2/instance-types/c5/[C5d^]
** https://aws.amazon.com/ec2/instance-types/c5/[C5ad^]

=== Azure

ifdef::env-kubernetes[AKS often defaults to the ext4 file system. Use XFS instead where possible.]

- Memory optimized: Memory-optimized VM sizes offer a high memory-to-CPU ratio.

** https://learn.microsoft.com/en-us/azure/virtual-machines/ebdsv5-ebsv5-series[Ebsv5 series (NVMe)^]
** https://learn.microsoft.com/en-us/azure/virtual-machines/ebdsv5-ebsv5-series[Ebdsv5 series (NVMe)^]

- Storage optimized: Storage-optimized virtual machine (VM) sizes offer high disk throughput and IO.

** https://learn.microsoft.com/en-us/azure/virtual-machines/lsv2-series[Lsv2 series^]
** https://learn.microsoft.com/en-us/azure/virtual-machines/lsv3-series[Lsv3 series^]
** https://learn.microsoft.com/en-us/azure/virtual-machines/lasv3-series[Lasv3 series^]

=== Google

ifdef::env-kubernetes[GKE often defaults to the ext4 file system. Use XFS instead where possible.]

- General purpose: The general-purpose machine family has the best price-performance with the most flexible vCPU to memory ratios, and provides features that target most standard and cloud-native workloads.

** https://cloud.google.com/compute/docs/general-purpose-machines#c3-with-local-ssd[C3 machine series with local SSD^]
** https://cloud.google.com/compute/docs/general-purpose-machines#n2_series[N2 machine series^]
** https://cloud.google.com/compute/docs/general-purpose-machines#n2d_machines[N2D machine series^]

- Memory optimized: The memory-optimized machine family provides the most compute and memory resources of any Compute Engine machine family offering. They are ideal for workloads that require higher memory-to-vCPU ratios than the high-memory machine types in the general-purpose N1 machine series.

** https://cloud.google.com/compute/docs/memory-optimized-machines#m3_series[M3 machine series^]

- Compute optimized: Compute-optimized VM instances are ideal for compute-intensive and high-performance computing (HPC) workloads.

** https://cloud.google.com/compute/docs/compute-optimized-machines#c2d_series[C2D machine series^]
** https://cloud.google.com/compute/docs/compute-optimized-machines#c2_machine_types[C2 machine series^]
