= rpk cluster maintenance

Interact with cluster maintenance mode.

Maintenance mode is a state that a node may be placed into in which the node
may be shutdown or restarted with minimal disruption to client workloads. The
primary use of maintenance mode is to perform a rolling upgrade in which each
node is placed into maintenance mode prior to upgrading the node.

Use the `enable` and `disable` subcommands to place a node into maintenance mode
or remove it, respectively. Only one node at a time may be in maintenance mode.

When a node is placed into maintenance mode the following occurs:

Leadership draining. All raft leadership is transferred to another eligible
node, and the node in maintenance mode rejects new leadership requests. By
transferring leadership off of the node in maintenance mode all client traffic
and requests are directed to other nodes minimizing disruption to client
workloads when the node is shutdown.

Currently leadership is not transferred for partitions with one replica.

== Usage

[,bash]
----
rpk cluster maintenance [flags] [command]
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-h, --help |- |Help for maintenance.

|--config |string |Redpanda or rpk config file; default search paths are `/var/lib/redpanda/.config/rpk/rpk.yaml`, `$PWD/redpanda.yaml`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override `rpk` configuration settings. See xref:reference:rpk/rpk-x-options.adoc[`rpk -X`] or execute `rpk -X help` for inline detail or `rpk -X list` for terser detail.

|--profile |string |Profile to use. See xref:reference:rpk/rpk-profile.adoc[`rpk profile`] for more details.

|-v, --verbose |- |Enable verbose logging.
|===

