= rpk cluster txn describe-producers

Describe transactional producers to partitions.

This command describes partitions that active transactional producers are producing to. For more information on the producer ID and epoch columns, see `rpk cluster txn --help`.

== Concept

The last timestamp corresponds to the timestamp of the last record that was written by the client. The transaction start offset corresponds to the offset that the transaction is began at. All consumers configured to read only committed records cannot read past the transaction start offset.

The output includes a few advanced fields that can be used for sanity checking: the last sequence is the last sequence number that the producer has written, and the coordinator epoch is the epoch of the broker that is being written to. The last sequence should always go up and then wrap back to 0 at MaxInt32. The coordinator epoch should remain fixed, or rarely, increase.

You can query all topics and partitions that have active producers with --all. To filter for specific topics, use `--topics`. You can additionally filter by partitions with `--partitions`.

== Usage

[,bash]
----
rpk cluster txn describe-producers [flags]
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-a, --all |- |Query all producer IDs on any topic.

|-h, --help |- |Help for describe-producers.

|-p, --partitions |int32 |int32Slice   Partitions to describe producers for (repeatable) (default []).

|-t, --topics |strings |Topic to describe producers for (repeatable).

|--config |string |Redpanda or `rpk` config file; default search paths are `/var/lib/redpanda/.config/rpk/rpk.yaml`, `$PWD/redpanda.yaml`, and `/etc/redpanda/redpanda.yaml`.


|-X, --config-opt |stringArray |Override `rpk` configuration settings. See xref:reference:rpk/rpk-x-options.adoc[`rpk -X`] or execute `rpk -X help` for inline detail or `rpk -X list` for terser detail.

|--format |string |Output format. Possible values: `json`, `yaml`, `text`, `wide`, `help`. Default: `text`.

|--profile |string |Profile to use. See xref:reference:rpk/rpk-profile.adoc[`rpk profile`] for more details.

|-v, --verbose |- |Enable verbose logging.
|===