= rpk cluster config set
:description: rpk cluster config set
:rpk_version: v23.2.1

Set a single cluster configuration property.

This command is provided for use in scripts. For interactive editing, or bulk
changes, use the `edit` and `import` commands respectively.

You may also use `<key>=<value>`` notation for setting configuration properties:

```bash
rpk cluster config set log_retention_ms=-1
```

If an empty string is given as the value, the property is reset to its default.

== Usage

[,bash]
----
rpk cluster config set <key> <value> [flags]
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-h, --help |- |Help for set.

|--all |- |Include all properties, including tunables.

|--config |string |Redpanda or rpk config file; default search paths are
~/.config/rpk/rpk.yaml, $PWD, and /etc/redpanda/redpanda.yaml.

|-X, --config-opt |stringArray |Override rpk configuration settings; '-X
help' for detail or '-X list' for terser detail.

|--profile |string |rpk profile to use.

|-v, --verbose |- |Enable verbose logging.
|===

[NOTE]
====
Setting properties to non-number values (such as setting string values with `-`) can be problematic for some terminals due to how POSIX flags are parsed. For example, the following command may not work from some terminals:

```
rpk cluster config set delete_retention_ms -1
```

Workaround: Use `--` to disable parsing for all subsequent characters. For example:

```
rpk cluster config set -- delete_retention_ms -1
```
====
