= rpk cluster config edit
:description: rpk cluster config edit
:rpk_version: v23.2.1

Edit cluster-wide configuration properties.

This command opens a text editor to modify the cluster's configuration.

Cluster properties are redpanda settings which apply to all nodes in
the cluster. These are separate to node properties, which are set with
`rpk redpanda config`.

Modified values are written back when the file is saved and the editor
is closed. Properties which are deleted are reset to their default
values.

By default, low level tunables are excluded: use the `--all` flag
to edit all properties including these tunables.

== Usage

[,bash]
----
rpk cluster config edit [flags]
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-h, --help |- |Help for edit.

|--all |- |Include all properties, including tunables.

|--config |string |Redpanda or rpk config file; default search paths are
~/.config/rpk/rpk.yaml, $PWD, and /etc/redpanda/redpanda.yaml.

|-X, --config-opt |stringArray |Override rpk configuration settings; '-X
help' for detail or '-X list' for terser detail.

|--profile |string |rpk profile to use.

|-v, --verbose |- |Enable verbose logging.
|===

