= rpk cluster storage unmount
// tag::single-source[]

Unmount a topic from the Redpanda cluster and secure it in glossterm:Tiered Storage[].

This command performs an operation that:

1. Rejects all writes to the topic.

2. Flushes data to Tiered Storage.

3. Removes the topic from the cluster.

Key Points:

- During unmounting, any attempted writes or reads will receive an `UNKNOWN_TOPIC_OR_PARTITION` error.

- The unmount operation works independently of other topic configurations like `remote.delete=false`.

- After unmounting, the topic can be remounted to this cluster or a different cluster if the log segments are moved to that cluster's Tiered Storage.

== Usage

[,bash]
----
rpk cluster storage unmount [TOPIC] [flags]
----

== Examples

Unmount topic '<my-topic>' from the cluster in the '<my-namespace>':

[,bash]
----
rpk cluster storage unmount <my-namespace>/<my-topic>
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-h, --help |- |Help for unmount.

|--config |string |Redpanda or `rpk` config file; default search paths are `/var/lib/redpanda/.config/rpk/rpk.yaml`, `$PWD/redpanda.yaml`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override `rpk` configuration settings. See xref:reference:rpk/rpk-x-options.adoc[`rpk -X`] or execute `rpk -X help` for inline detail or `rpk -X list` for terser detail.

|--profile |string |Profile to use. See xref:reference:rpk/rpk-profile.adoc[`rpk profile`] for more details.

|-v, --verbose |- |Enable verbose logging.
|===

// end::single-source[]