= rpk cluster maintenance
:description: rpk cluster maintenance
:rpk_version: v23.1.6 (rev cc47e1ad1)

Interact with cluster maintenance mode.

Maintenance mode is a state that a node may be placed into in which the node
may be shutdown or restarted with minimal disruption to client workloads. The
primary use of maintenance mode is to perform a rolling upgrade in which each
node is placed into maintenance mode prior to upgrading the node.

Use the `enable` and `disable` subcommands to place a node into maintenance mode
or remove it, respectively. Only one node at a time may be in maintenance mode.

When a node is placed into maintenance mode the following occurs:

Leadership draining. All raft leadership is transferred to another eligible
node, and the node in maintenance mode rejects new leadership requests. By
transferring leadership off of the node in maintenance mode all client traffic
and requests are directed to other nodes minimizing disruption to client
workloads when the node is shutdown.

Currently leadership is not transferred for partitions with one replica.

== Usage

[,bash]
----
rpk cluster maintenance [command]
----

== Flags


[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|--admin-api-tls-cert |string |The certificate to be used for TLS
authentication with the Admin API.

|--admin-api-tls-enabled |- |Enable TLS for the Admin API (not necessary
if specifying custom certs).

|--admin-api-tls-key |string |The certificate key to be used for TLS
authentication with the Admin API.

|--admin-api-tls-truststore |string |The truststore to be used for TLS
communication with the Admin API.

|--api-urls |string |Comma-separated list of admin API addresses
(<ip>:<port>

|-h, --help |- |Help for maintenance.

|--brokers |strings |Comma-separated list of broker <ip>:<port> pairs
(for example,
`--brokers 192.168.78.34:9092,192.168.78.35:9092,192.179.23.54:9092`
). Alternatively, you may set the `REDPANDA_BROKERS` environment
variable with the comma-separated list of broker addresses.

|--config |string |Redpanda config file, if not set the file will be
searched for in the default locations.

|--password |string |SASL password to be used for authentication.

|--sasl-mechanism |string |The authentication mechanism to use.
Supported values: SCRAM-SHA-256, SCRAM-SHA-512.

|--tls-cert |string |The certificate to be used for TLS authentication
with the broker.

|--tls-enabled |- |Enable TLS for the Kafka API (not necessary if
specifying custom certs).

|--tls-key |string |The certificate key to be used for TLS
authentication with the broker.

|--tls-truststore |string |The truststore to be used for TLS
communication with the broker.

|--user |string |SASL user to be used for authentication.

|-v, --verbose |- |Enable verbose logging (default `false`).
|===

