= rpk cluster partitions transfer-leadership

Transfer partition leadership between brokers.

You can transfer only one partition leader at a time.

WARNING: Redpanda tries to balance leadership distribution across brokers by default. If the distribution of leaders becomes uneven as a result of transferring leadership across brokers, the cluster may move leadership back to the original brokers automatically.

== Usage

[,bash]
----
rpk cluster partitions transfer-leadership [flags]
----

== Examples

Transfer partition leadership:

```bash
rpk cluster partitions transfer-leadership foo --partition 0:2
```

The preceding example shows how to transfer leadership for the partition `kafka/foo/0` to broker 2. By default, it uses the `kafka` namespace, but you can specify an internal namespace using the `+{namespace}/+` prefix.

Equivalent command using different syntax:

```bash
rpk cluster partitions transfer-leadership --partition foo/0:2
```

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|--format |string |Output format. Possible values: `json`, `yaml`, `text`, `wide`, `help`. Default: `text`.

|-h, --help |- |Help for transfer-leadership.

|-p, --partition |string |The topic partition to which to transfer leadership and specify the new leader location. Syntax `-p A:B` where A is the partition leader and B will be the new leader. See <<examples>> for how to use it. 

|--config |string |Redpanda or `rpk` config file; default search paths are `/var/lib/redpanda/.config/rpk/rpk.yaml`, `$PWD/redpanda.yaml`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override `rpk` configuration settings. See xref:reference:rpk/rpk-x-options.adoc[`rpk -X`] or execute `rpk -X help` for inline detail or `rpk -X list` for terser detail.

|--profile |string |Profile to use. See xref:reference:rpk/rpk-profile.adoc[`rpk profile`] for more details.

|-v, --verbose |- |Enable verbose logging.
|===