= rpk cluster config force-reset

Forcibly clear a cluster configuration property on a broker.

Do not use this command for general changes to cluster configuration. Use `force-reset` only when Redpanda does not start due to a configuration issue; for example, when a property is set to an invalid value or when a property is missing that Redpanda requires to start.

This command erases the named property from an internal cache of the cluster configuration on the local broker, so that on next startup Redpanda treats
the property as if it was set to the default.

If your cluster is working properly and you want to reset a property
to its default value, either use the `set` command with an empty string, or
use the `edit` command and delete the line containing the property.

WARNING: Use this command only when Redpanda isn't running.

== Usage

[,bash]
----
rpk cluster config force-reset [PROPERTY...] [flags]
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|--cache-file |string |Location of configuration cache file (defaults to
Redpanda `data` directory).

|-h, --help |- |Help for force-reset.

|--all |- |Include all properties, including tunables.

|--config |string |Redpanda or `rpk` config file; default search paths are `/var/lib/redpanda/.config/rpk/rpk.yaml`, `$PWD/redpanda.yaml`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override `rpk` configuration settings. See xref:reference:rpk/rpk-x-options.adoc[`rpk -X`] or execute `rpk -X help` for inline detail or `rpk -X list` for terser detail.

|--profile |string |Profile to use. See xref:reference:rpk/rpk-profile.adoc[`rpk profile`] for more details.

|-v, --verbose |- |Enable verbose logging.
|===

