= rpk cluster storage recovery
:rpk_version: v23.2.1

Interact with the topic recovery process.
This command is used to restore topics from the archival bucket, which can be
useful for disaster recovery or if a topic was accidentally deleted.

To begin the recovery process, use the `recovery start` command. Note that this
process can take a while to complete, so the command will exit after starting
it. If you want the command to wait for the process to finish, use the `--wait`
or `-w` flag.

You can check the status of the recovery process with the `recovery status`
command after it has been started.

== Usage

[,bash]
----
rpk cluster storage recovery [command]
----

== Flags

[cols=",,",]
|===
|*Value* |*Type* |*Description*

|-h, --help |- |Help for recovery.

|--config |string |Redpanda or rpk config file; default search paths are
~/.config/rpk/rpk.yaml, $PWD, and /etc/redpanda/redpanda.yaml.

|-X, --config-opt |stringArray |Override rpk configuration settings; '-X
help' for detail or '-X list' for terser detail.

|--profile |string |rpk profile to use.

|-v, --verbose |- |Enable verbose logging.
|===

