= rpk cluster quotas alter
:description: rpk cluster quotas alter

Add or delete a client quota.

A client quota consists of an entity (to whom the quota is applied) and a quota type (what is being applied).

There are two entity types supported by Redpanda: client ID and client ID prefix. Assigning quotas to default entity types is possible using the `--default` flag.

You can perform a dry run using the `--dry` flag.

== Usage

[,bash]
----
rpk cluster quotas alter [flags]
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|--add |strings |Key=value quota to add, where the value is a float number (repeatable).

|--default |strings |Entity type for default matching, where type is client-id or client-id-prefix (repeatable).

|--delete |strings |Key of the quota to delete (repeatable).

|--dry |- |Key of the quota to delete (repeatable).

|--format |string |Output format. Possible values: `json`, `yaml`, `text`, `wide`, `help`. Default: `text`.

|-h, --help |- |Help for alter.

|--name |strings |Entity for exact matching. Format type=name where type is client-id or client-id-prefix (repeatable).

|--config |string |Redpanda or `rpk` config file; default search paths are `/var/lib/redpanda/.config/rpk/rpk.yaml`, `$PWD/redpanda.yaml`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override `rpk` configuration settings. See xref:reference:rpk/rpk-x-options.adoc[`rpk -X`] or execute `rpk -X help` for inline detail or `rpk -X list` for terser detail.

|--profile |string |Profile to use. See xref:reference:rpk/rpk-profile.adoc[`rpk profile`] for more details.

|-v, --verbose |- |Enable verbose logging.
|===


== Examples

Add quota (consumer_byte_rate) to client ID `<foo>`:

[,bash]
----
rpk cluster quotas alter --add consumer_byte_rate=200000 \
  --name client-id=<foo>
----

Add quota (consumer_byte_rate) to client ID starting with `<bar>-`:

[,bash]
----
rpk cluster quotas alter --add consumer_byte_rate=200000 \
  --name client-id-prefix=<bar>-
----

Add quota (producer_byte_rate) to default client ID:

[,bash]
----
rpk cluster quotas alter --add producer_byte_rate=180000 \
  --default client-id=foo
----

Remove quota (producer_byte_rate) from client ID `foo`:

[,bash]
----
rpk cluster quotas alter --delete producer_byte_rate \
  --name client-id=<foo>
----