= rpk cluster config edit

Edit cluster-wide configuration properties.

This command opens a text editor to modify the cluster's configuration.

Cluster properties are redpanda settings which apply to all nodes in
the cluster. These are separate to node properties, which are set with
`rpk redpanda config`.

Modified values are written back when the file is saved and the editor
is closed. Properties which are deleted are reset to their default
values.

By default, low level tunables are excluded: use the `--all` flag
to edit all properties including these tunables.

== Usage

[,bash]
----
rpk cluster config edit [flags]
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-h, --help |- |Help for edit.

|--all |- |Include all properties, including tunables.

|--config |string |Redpanda or `rpk` config file. Default search paths are: 
`~/.config/rpk/rpk.yaml`, `$PWD`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override `rpk` configuration settings. See xref:reference:rpk/rpk-x-options.adoc[`rpk -X`] or execute `rpk -X help` for inline detail or `rpk -X list` for terser detail.

|--profile |string |Profile to use. See xref:reference:rpk/rpk-profile.adoc[`rpk profile`] for more details.

|-v, --verbose |- |Enable verbose logging.
|===

