= rpk cluster config status
// tag::single-source[]

ifndef::env-cloud[]
Get the configuration status of Redpanda brokers.

For each broker, the command output shows:

- Whether you need to restart the broker to apply the new settings
- Any settings that the broker has flagged as invalid or unknown

The command also returns the version of cluster configuration that each broker
has applied. The version should be the same across all brokers, and
it is incremented each time a configuration change is applied to the
cluster. If a broker is using an earlier version as indicated by a lower number,
it may be out of sync with the rest of the cluster. This can happen if a broker
is offline or if it has not yet applied the latest configuration changes.  The cluster configuration version number is not the same as the Redpanda version number.
endif::[]

ifdef::env-cloud[]
Check the progress of a cluster configuration change.

Some cluster properties require a rolling restart when updated, and it can take several minutes for the update to complete. This command lists the long-running operations run by the update and their status:

- In progress
- Completed
- Failed

endif::[]

== Usage

[,bash]
----
rpk cluster config status [flags]
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-h, --help |- |Help for status.

|--all |- |Include all properties, including tunables.

|--config |string |Redpanda or `rpk` config file; default search paths are `/var/lib/redpanda/.config/rpk/rpk.yaml`, `$PWD/redpanda.yaml`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override `rpk` configuration settings. See xref:reference:rpk/rpk-x-options.adoc[`rpk -X`] or execute `rpk -X help` for inline detail or `rpk -X list` for terser detail.

|--profile |string |Profile to use. See xref:reference:rpk/rpk-profile.adoc[`rpk profile`] for more details.

|-v, --verbose |- |Enable verbose logging.
|===

// end::single-source[]