= rpk cluster partitions enable
:description: rpk cluster partitions enable

Enable partitions of a topic.

You may enable all partitions of a topic using the `--all` flag or you may select a set of topic/partitions to enable with the `--partitions` or `-p` flag.

The partition flag accepts the format `{namespace}/{topic}/[partitions...]` where namespace and topic are optional parameters. 

If the namespace is not provided, `rpk` will assume `kafka`. 

If the topic is not provided in the flag, `rpk` will use the topic provided as an argument to this command.

== Examples

Enable all partitions in topic `foo`:

```bash
rpk cluster partitions enable foo --all
```


Enable partitions 1,2 and 3 of topic `bar` in the namespace `internal`:

```bash
rpk cluster partitions enable internal/bar --partitions 1,2,3
```

Enable partition 1, and 2 of topic `foo`, and partition 5 of topic `bar` in the `internal` namespace:

```bash
rpk cluster partitions enable -p foo/1,2 -p internal/bar/5
```


== Usage

[,bash]
----
rpk cluster partitions enable [TOPIC] [flags]
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-a, --all |- |If true, enable all partitions for the specified topic.

|-h, --help |- |Help for enable.

|-p, --partitions |stringArray |Comma-separated list of partitions you want to enable. Check help for extended usage.

|--config |string |Redpanda or rpk config file; default search paths are ~/.config/rpk/rpk.yaml, $PWD, and /etc/redpanda/`redpanda.yaml`.

|-X, --config-opt |stringArray |Override rpk configuration settings; '-X help' for detail or '-X list' for terser detail.

|--profile |string |rpk profile to use.

|-v, --verbose |- |Enable verbose logging.
|===