= rpk cluster partitions move-status
:page-aliases: reference:rpk/rpk-cluster-partitions-movement-status.adoc

Show ongoing partition movements.

By default this command lists all ongoing partition movements in the cluster. Topics can be specified to print the move status of specific topics. By default, this command assumes the `kafka` namespace, but you can use a `<namespace>/` to specify internal namespaces.

```bash
rpk cluster partitions move-status
```

```bash
rpk cluster partitions move-status foo bar kafka_internal/tx
```

The `--partition / -p` flag can be used with topics to additional filter requested partitions:


```bash
rpk cluster partitions move-status foo bar --partition 0,1,2
```

The output contains the following columns. The Partition-Size column is in bytes. Using -H, it prints the partition size in a human-readable format

- Namespace-Topic
- Partition
- Moving-From
- Moving-To
- Completion-%
- Partition-Size
- Bytes-Moved
- Bytes-Remaining

Using `--print-all / -a` the command additionally prints the column `Reconciliation-Statuses`, which reveals the internal status of the ongoing reconciliations. Reported errors do not necessarily mean real problems.

== Usage

[,bash]
----
rpk cluster partitions move-status [flags]
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-h, --help |- |Help for move-status.

|-H, --human-readable |- |Print the partition size in a human-readable form.

|-p, --partition |strings |Partitions to filter ongoing movements status (repeatable).

|-a, --print-all |- |Print internal states about movements for debugging.

|--config |string |Redpanda or rpk config file; default search paths are ~/.config/rpk/rpk.yaml, $PWD, and /etc/redpanda/`redpanda.yaml`.

|-X, --config-opt |stringArray |Override rpk configuration settings; '-X help' for detail or '-X list' for terser detail.

|--profile |string |rpk profile to use.

|-v, --verbose |- |Enable verbose logging.
|===