= rpk cluster config force-reset
:description: rpk cluster config force-reset
:rpk_version: v23.2.1

Forcibly clear a cluster configuration property on this node.

This command is not for general changes to cluster configuration: use this only
when redpanda will not start due to a configuration issue.

If your cluster is working properly and you would like to reset a property
to its default, you may use the `set` command with an empty string, or
use the `edit` command and delete the property`s line.

This command erases a named property from an internal cache of the cluster
configuration on the local node, so that on next startup redpanda will treat
the setting as if it was set to the default.

WARNING: Use this command only when Redpanda isn't running.

== Usage

[,bash]
----
rpk cluster config force-reset [PROPERTY...] [flags]
----

== Flags

[cols=",,",]
|===
|*Value* |*Type* |*Description*

|--cache-file |string |location of configuration cache file (defaults to
redpanda data directory).

|-h, --help |- |Help for force-reset.

|--all |- |Include all properties, including tunables.

|--config |string |Redpanda or rpk config file; default search paths are
~/.config/rpk/rpk.yaml, $PWD, and /etc/redpanda/redpanda.yaml.

|-X, --config-opt |stringArray |Override rpk configuration settings; '-X
help' for detail or '-X list' for terser detail.

|--profile |string |rpk profile to use.

|-v, --verbose |- |Enable verbose logging.
|===

