= rpk cluster partitions move
:description: rpk cluster partitions move

Move partition replicas across nodes / cores.

This command changes replica assignments for given partitions. By default, it assumes the `kafka` namespace, but you can specify an internal namespace using the `{namespace}/` prefix.


== Examples

To move replicas, use the following syntax:

```bash
rpk cluster partitions move foo --partition 0:1,2,3 -p 1:2,3,4
```

Here, the command assigns new replicas for partition 0 to brokers [1, 2, 3] and for partition 1 to brokers [2, 3, 4] for the topic `foo`.

You can also specify the core id with `-{core_id}` where the new replicas should be placed:


```bash
rpk cluster partitions move foo -p 0:1-0,2-0,3-0
```

Here all new replicas [1, 2, 3] will be assigned on core 0 on the nodes. The command does not change a "core" assignment unless it is explicitly specified. When a core is not specified for a new node, the command randomly picks a core and assign a replica on the core.


Topic arguments are optional. For more control, you can specify the topic name in the `--partition` flag:


```bash
rpk cluster partitions move -p foo/0:1,2,3 -p kafka_internal/tx/0:1-0,2-0,3-0
```

== Usage

[,bash]
----
rpk cluster partitions move [flags]
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|--format |string |Output format (json,yaml,text,wide,help) (default "text").

|-h, --help |- |Help for move.

|-p, --partition |stringArray |Topic-partitions to move and new replica locations (repeatable).

|--config |string |Redpanda or rpk config file; default search paths are ~/.config/rpk/rpk.yaml, $PWD, and /etc/redpanda/`redpanda.yaml`.

|-X, --config-opt |stringArray |Override rpk configuration settings; '-X help' for detail or '-X list' for terser detail.

|--profile |string |rpk profile to use.

|-v, --verbose |- |Enable verbose logging.
|===