= rpk cluster config import
:description: rpk cluster config import

CAUTION: Redpanda does not support importing cluster-specific identification (such as `cluster_id`) with this command.

Import cluster configuration from a file.

Import configuration from a YAML file, usually generated with
corresponding `export` command. This downloads the current cluster
configuration, calculates the difference with the YAML file, and
updates any properties that were changed. If a property is removed
from the YAML file, it is reset to its default value.

== Usage

[,bash]
----
rpk cluster config import [flags]
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-f, --filename |string |full path to file to import, e.g.
'/tmp/config.yml'.

|-h, --help |- |Help for import.

|--all |- |Include all properties, including tunables.

|--config |string |Redpanda or `rpk` config file. Default search paths are
`~/.config/rpk/rpk.yaml`, `$PWD`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override `rpk` configuration settings. See xref:reference:rpk/rpk-x-options.adoc[`rpk -X`] or execute `rpk -X help` for inline detail or `rpk -X list` for terser detail.

|--profile |string |Profile to use. See xref:reference:rpk/rpk-profile.adoc[`rpk profile`] for more details.

|-v, --verbose |- |Enable verbose logging.
|===

