= rpk cluster partitions list

List partitions in the cluster.

This commands lists the cluster-level metadata of all partitions in the cluster.

It shows the current replica assignments on both brokers and CPU cores for given topics. By default, it assumes the `kafka` namespace, but you can specify an internal namespace using the `<namespace>/` prefix.

The `Replica-Core` column displayed in the output table contains a list of replica assignments in the form of <node-id>-<core>.

If the Disabled column contains a '-' value, then it means you are running this command against a cluster that does not support the underlying API.

== Enabled/Disabled


Disabling a partition in Redpanda involves prohibiting any data consumption or production to and from it. All internal processes associated with the partition are stopped, and it remains unloaded during system startup. This measure aims to maintain cluster health by preventing issues caused by specific corrupted partitions that may lead to Redpanda crashes. Although the data remains stored on disk, Redpanda ceases interaction with the disabled partitions to ensure system stability. You may disable/enable partition using `rpk cluster partitions enable/disable`.	



== Examples

List all partitions in the cluster:

```bash
rpk cluster partitions list --all
```

List all partitions in the cluster, filtering for topic foo and bar:

```bash
rpk cluster partitions list foo bar
```

List only the disabled partitions:

```bash
rpk cluster partitions list -a --disabled-only
```



List all in JSON format:

```bash
rpk cluster partition list -a --format json
```

== Usage

[,bash]
----
rpk cluster partitions list [TOPICS...] [flags]
----

== Aliases

[,bash]
----
list, ls, describe
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-a, --all |- |If true, list all partitions in the cluster.

|--disabled-only |- |If true, list disabled partitions only.

|--format |string |Output format. Possible values: `json`, `yaml`, `text`, `wide`, `help`. Default: `text`.

|-h, --help |- |Help for list.

|-p, --partition |- |ints   List of comma-separated partitions IDs that you wish to filter the results with.

|--config |string |Redpanda or `rpk` config file. Default search paths are: 
`~/.config/rpk/rpk.yaml`, `$PWD`, and `/etc/redpanda/redpanda.yaml`.


|-X, --config-opt |stringArray |Override `rpk` configuration settings. See xref:reference:rpk/rpk-x-options.adoc[`rpk -X`] or execute `rpk -X help` for inline detail or `rpk -X list` for terser detail.

|--profile |string |Profile to use. See xref:reference:rpk/rpk-profile.adoc[`rpk profile`] for more details.

|-v, --verbose |- |Enable verbose logging.
|===