= rpk cluster connections list

Display statistics about current Kafka connections.

This command displays a table of active and recently closed connections within the cluster.

Use filtering and sorting to identify the connections of the client applications that you are interested in. See `--help` for the list of filtering arguments and sorting arguments.

In addition to the filtering shorthand CLI arguments (For example, `--client-id`, `--state`), you can also use the `--filter-raw` and `--order-by` arguments that take string expressions. To understand the syntax of these arguments, refer to the Admin API docs of the filter and order-by fields of the [ListKafkaConnections endpoint](https://docs.redpanda.com/api/doc/admin/version/11f41833-5783-4f1a-ad64-5957267abd52/operation/operation-redpanda-core-admin-v2-clusterservice-listkafkaconnections): 

By default only a subset of the per-connection data is printed. To see all of the available data, use `--format=json`.

== Usage

[,bash]
----
rpk cluster connections list [flags]
----

== Examples

List connections ordered by their recent produce throughput:

[,bash]
----
rpk cluster connections list --order-by="recent_request_statistics.produce_bytes desc"
----

List connections ordered by their recent fetch throughput:

[,bash]
----
rpk cluster connections list --order-by="recent_request_statistics.fetch_bytes desc"
----

List connections ordered by the time that they've been idle:

[,bash]
----
rpk cluster connections list --order-by="idle_duration desc"
----

List connections ordered by those that have made the least requests:

[,bash]
----
rpk cluster connections list --order-by="total_request_statistics.request_count asc"
----

List extended output for open connections in JSON format:

[,bash]
----
rpk cluster connections list --format=json --state="OPEN"
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|--client-id |string |Filter results by the client ID.

|--client-software-name |string |Filter results by the client software name.

|--client-software-version |string |Filter results by the client software version.

|--filter-raw |string |Filter connections based on a raw query (overrides other filters).

|--format |string |Output format. Possible values: `json`, `yaml`, `text`, `wide`, `help`. Default: `text`.

|-g, --group-id |string |Filter by client group ID.

|-h, --help |- |Help for connections list.

|-i, --idle-ms |int |Show connections idle for more than `i` milliseconds.

|--ip-address |string |Filter results by the client IP address.

|--limit |int32 |Limit how many records can be returned (default `20`).

|--order-by |string |Order the results by their values. See Examples above.

|-s, --state |string |Filter results by state. Acceptable values: `OPEN`, `CLOSED`.

|-u, --user |string |Filter results by a specific user principal.

|--config |string |Redpanda or `rpk` config file; default search paths are `/var/lib/redpanda/.config/rpk/rpk.yaml`, `$PWD/redpanda.yaml`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override `rpk` configuration settings. See xref:reference:rpk/rpk-x-options.adoc[`rpk -X`] or execute `rpk -X help` for inline detail or `rpk -X list` for terser detail.

|--profile |string |Profile to use. See xref:reference:rpk/rpk-profile.adoc[`rpk profile`] for more details.

|-v, --verbose |- |Enable verbose logging.
|===