= rpk cluster self-test status
:description: Reference for the 'rpk cluster self-test status' command. Queries the status of the currently running or last completed self-test run.

Queries the status of the currently running or last completed self-test run. Returns the status of the currently running or the results of the last completed self-test.

Use this command after invoking xref:./rpk-cluster-self-test-start.adoc[rpk cluster self-test start] to determine the status of
the jobs launched. Possible results are:

* One or more jobs still running
** Returns the IDs of Redpanda nodes still running self-tests. Example:

[,bash,role=no-copy]
----
Node 1 is still running net self test
----

* No jobs running
** Returns the cached results for all nodes of the last completed test.

Test results are grouped by node ID. Each test returns the following:

* *Name*: Description of the test.
* *Info*: Detail about the test run attached by Redpanda itself.
* *Type*: Either `disk` or `network` test.
* *Test Id*: Unique identifier given to jobs of a run. All IDs in a test should match. If they don't match, then newer and/or older test results have been included erroneously.
* *Timeouts*: Number of timeouts incurred during the test.
* *Start time*: Time that the test started, in UTC.
* *End time*: Time that the test ended, in UTC.
* *Avg Duration*: Duration of the test.
* *IOPS*: Number of operations per second. For disk, it's `seastar::dma_read` and `seastar::dma_write`. For network, it's `rpc.send()`
* *Throughput*: For disk, it's throughput rate in bytes per second. For network, it's throughput rate in bits per second in. (Note: GiB vs. Gib is the correct notation displayed by the UI.)
* *Latency*: 50th, 90th, etc. percentiles of operation latency, reported in microseconds(us). Represented as P50, P90, P99, P999, and MAX respectively.

If xref:manage:tiered-storage.adoc[Tiered Storage] is not enabled, the cloud storage tests won't run and a warning will be displayed showing "Cloud storage is not enabled.". All results will be shown as 0.

== Usage

[,bash]
----
rpk cluster self-test status [flags]
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|--format |string |Output format. Possible values: `json`, `text`. Default: `text`.

|-h, --help |- |Help for status.

|--config |string |Redpanda or `rpk` config file; default search paths are `/var/lib/redpanda/.config/rpk/rpk.yaml`, `$PWD/redpanda.yaml`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override `rpk` configuration settings. See xref:reference:rpk/rpk-x-options.adoc[`rpk -X`] or execute `rpk -X help` for inline detail or `rpk -X list` for terser detail.

|--profile |string |Profile to use. See xref:reference:rpk/rpk-profile.adoc[`rpk profile`] for more details.

|-v, --verbose |- |Enable verbose logging.
|===


== Example

Example input:

[,bash]
----
rpk cluster self-test status
----

Example output, for three-broker cluster:

[,bash]
----
NODE ID: 1 | STATUS: IDLE
=========================
NAME          512KB sequential r/w throughput disk test
INFO          write run
TYPE          disk
TEST ID       5632cefe-cf42-44ab-bba9-18fa1c71e3ee
TIMEOUTS      0
START TIME    Thu Jul 11 18:58:13 UTC 2024
END TIME      Thu Jul 11 18:58:43 UTC 2024
AVG DURATION  30007ms
IOPS          140 req/sec
THROUGHPUT    70.17MiB/sec
LATENCY       P50      P90      P99       P999      MAX
              24575us  47103us  188415us  425983us  507903us

NAME          512KB sequential r/w throughput disk test
INFO          read run
TYPE          disk
TEST ID       5632cefe-cf42-44ab-bba9-18fa1c71e3ee
TIMEOUTS      0
START TIME    Thu Jul 11 18:58:43 UTC 2024
END TIME      Thu Jul 11 18:59:13 UTC 2024
AVG DURATION  30008ms
IOPS          276 req/sec
THROUGHPUT    138.5MiB/sec
LATENCY       P50      P90      P99      P999     MAX
              13823us  19455us  24575us  57343us  77823us

NAME          4KB sequential r/w latency/iops disk test
INFO          write run
TYPE          disk
TEST ID       5632cefe-cf42-44ab-bba9-18fa1c71e3ee
TIMEOUTS      0
START TIME    Thu Jul 11 18:59:13 UTC 2024
END TIME      Thu Jul 11 18:59:43 UTC 2024
AVG DURATION  30000ms
IOPS          6769 req/sec
THROUGHPUT    26.44MiB/sec
LATENCY       P50    P90    P99     P999     MAX
              191us  255us  2303us  13311us  81919us

NAME          4KB sequential r/w latency/iops disk test
INFO          read run
TYPE          disk
TEST ID       5632cefe-cf42-44ab-bba9-18fa1c71e3ee
TIMEOUTS      0
START TIME    Thu Jul 11 18:59:43 UTC 2024
END TIME      Thu Jul 11 19:00:13 UTC 2024
AVG DURATION  30001ms
IOPS          13235 req/sec
THROUGHPUT    51.7MiB/sec
LATENCY       P50    P90    P99    P999    MAX
              127us  239us  735us  1919us  63487us

NAME          8Kb Network Throughput Test
INFO          Test performed against node: 2
TYPE          network
TEST ID       5632cefe-cf42-44ab-bba9-18fa1c71e3ee
TIMEOUTS      0
START TIME    Thu Jul 11 19:00:13 UTC 2024
END TIME      Thu Jul 11 19:00:43 UTC 2024
AVG DURATION  30000ms
IOPS          55370 req/sec
THROUGHPUT    3.38Gib/sec
LATENCY       P50    P90    P99    P999   MAX
              167us  231us  351us  495us  7679us

NAME          Cloud Storage Test
TYPE          
TEST ID       5632cefe-cf42-44ab-bba9-18fa1c71e3ee
TIMEOUTS      0
START TIME    Thu Jan  1 00:00:00 UTC 1970
END TIME      Thu Jan  1 00:00:00 UTC 1970
AVG DURATION  0ms
WARNING       Cloud storage is not enabled.
IOPS          0 req/sec
THROUGHPUT    0B/sec
LATENCY       P50   P90   P99   P999  MAX
              0us   0us   0us   0us   0us

NODE ID: 2 | STATUS: IDLE
=========================
NAME          512KB sequential r/w throughput disk test
INFO          write run
TYPE          disk
TEST ID       5632cefe-cf42-44ab-bba9-18fa1c71e3ee
TIMEOUTS      0
START TIME    Thu Jul 11 18:58:13 UTC 2024
END TIME      Thu Jul 11 18:58:43 UTC 2024
AVG DURATION  30006ms
IOPS          141 req/sec
THROUGHPUT    70.52MiB/sec
LATENCY       P50      P90      P99       P999      MAX
              24575us  47103us  188415us  409599us  507903us

NAME          512KB sequential r/w throughput disk test
INFO          read run
TYPE          disk
TEST ID       5632cefe-cf42-44ab-bba9-18fa1c71e3ee
TIMEOUTS      0
START TIME    Thu Jul 11 18:58:43 UTC 2024
END TIME      Thu Jul 11 18:59:13 UTC 2024
AVG DURATION  30011ms
IOPS          279 req/sec
THROUGHPUT    139.5MiB/sec
LATENCY       P50      P90      P99      P999     MAX
              13823us  19455us  24575us  57343us  81919us

NAME          4KB sequential r/w latency/iops disk test
INFO          write run
TYPE          disk
TEST ID       5632cefe-cf42-44ab-bba9-18fa1c71e3ee
TIMEOUTS      0
START TIME    Thu Jul 11 18:59:13 UTC 2024
END TIME      Thu Jul 11 18:59:43 UTC 2024
AVG DURATION  29999ms
IOPS          7045 req/sec
THROUGHPUT    27.52MiB/sec
LATENCY       P50    P90    P99     P999     MAX
              191us  255us  2303us  13823us  81919us

NAME          4KB sequential r/w latency/iops disk test
INFO          read run
TYPE          disk
TEST ID       5632cefe-cf42-44ab-bba9-18fa1c71e3ee
TIMEOUTS      0
START TIME    Thu Jul 11 18:59:43 UTC 2024
END TIME      Thu Jul 11 19:00:13 UTC 2024
AVG DURATION  30000ms
IOPS          13064 req/sec
THROUGHPUT    51.03MiB/sec
LATENCY       P50    P90    P99    P999    MAX
              127us  247us  767us  2175us  61439us

NAME          Cloud Storage Test
TYPE          
TEST ID       5632cefe-cf42-44ab-bba9-18fa1c71e3ee
TIMEOUTS      0
START TIME    Thu Jan  1 00:00:00 UTC 1970
END TIME      Thu Jan  1 00:00:00 UTC 1970
AVG DURATION  0ms
WARNING       Cloud storage is not enabled.
IOPS          0 req/sec
THROUGHPUT    0B/sec
LATENCY       P50   P90   P99   P999  MAX
              0us   0us   0us   0us   0us

NODE ID: 0 | STATUS: IDLE
=========================
NAME          512KB sequential r/w throughput disk test
INFO          write run
TYPE          disk
TEST ID       5632cefe-cf42-44ab-bba9-18fa1c71e3ee
TIMEOUTS      0
START TIME    Thu Jul 11 18:58:13 UTC 2024
END TIME      Thu Jul 11 18:58:43 UTC 2024
AVG DURATION  30009ms
IOPS          140 req/sec
THROUGHPUT    70.38MiB/sec
LATENCY       P50      P90      P99       P999      MAX
              24575us  47103us  180223us  360447us  507903us

NAME          512KB sequential r/w throughput disk test
INFO          read run
TYPE          disk
TEST ID       5632cefe-cf42-44ab-bba9-18fa1c71e3ee
TIMEOUTS      0
START TIME    Thu Jul 11 18:58:43 UTC 2024
END TIME      Thu Jul 11 18:59:13 UTC 2024
AVG DURATION  30005ms
IOPS          278 req/sec
THROUGHPUT    139.2MiB/sec
LATENCY       P50      P90      P99      P999     MAX
              13823us  19455us  24575us  57343us  77823us

NAME          4KB sequential r/w latency/iops disk test
INFO          write run
TYPE          disk
TEST ID       5632cefe-cf42-44ab-bba9-18fa1c71e3ee
TIMEOUTS      0
START TIME    Thu Jul 11 18:59:13 UTC 2024
END TIME      Thu Jul 11 18:59:43 UTC 2024
AVG DURATION  30000ms
IOPS          6767 req/sec
THROUGHPUT    26.43MiB/sec
LATENCY       P50    P90    P99     P999     MAX
              191us  255us  2303us  13823us  102399us

NAME          4KB sequential r/w latency/iops disk test
INFO          read run
TYPE          disk
TEST ID       5632cefe-cf42-44ab-bba9-18fa1c71e3ee
TIMEOUTS      0
START TIME    Thu Jul 11 18:59:43 UTC 2024
END TIME      Thu Jul 11 19:00:13 UTC 2024
AVG DURATION  30003ms
IOPS          13206 req/sec
THROUGHPUT    51.59MiB/sec
LATENCY       P50    P90    P99    P999    MAX
              123us  239us  735us  1855us  63487us

NAME          8Kb Network Throughput Test
INFO          Test performed against node: 1
TYPE          network
TEST ID       5632cefe-cf42-44ab-bba9-18fa1c71e3ee
TIMEOUTS      0
START TIME    Thu Jul 11 19:00:13 UTC 2024
END TIME      Thu Jul 11 19:00:43 UTC 2024
AVG DURATION  30000ms
IOPS          34929 req/sec
THROUGHPUT    2.13Gib/sec
LATENCY       P50    P90    P99    P999   MAX
              303us  367us  511us  671us  6399us

NAME          8Kb Network Throughput Test
INFO          Test performed against node: 2
TYPE          network
TEST ID       5632cefe-cf42-44ab-bba9-18fa1c71e3ee
TIMEOUTS      0
START TIME    Thu Jul 11 19:00:43 UTC 2024
END TIME      Thu Jul 11 19:01:13 UTC 2024
AVG DURATION  30000ms
IOPS          86498 req/sec
THROUGHPUT    5.28Gib/sec
LATENCY       P50    P90    P99    P999   MAX
              107us  151us  247us  351us  10239us

NAME          Cloud Storage Test
TYPE          
TEST ID       5632cefe-cf42-44ab-bba9-18fa1c71e3ee
TIMEOUTS      0
START TIME    Thu Jan  1 00:00:00 UTC 1970
END TIME      Thu Jan  1 00:00:00 UTC 1970
AVG DURATION  0ms
WARNING       Cloud storage is not enabled.
IOPS          0 req/sec
THROUGHPUT    0B/sec
LATENCY       P50   P90   P99   P999  MAX
              0us   0us   0us   0us   0us


----

NOTE: If self-test returns write results that are unexpectedly and significantly lower than read results, it may be because the Redpanda `rpk` client hardcodes the `DSync` option to `true`. When `DSync` is enabled, files are opened with the `O_DSYNC` flag set, and this represents the actual setting that Redpanda uses when it writes to disk.

== Related topics

* xref:manage:cluster-maintenance/cluster-diagnostics.adoc#disk-and-network-self-test-benchmarks[Guide for running self-test for cluster diagnostics]
* xref:./rpk-cluster-self-test.adoc[rpk cluster self-test]
* xref:./rpk-cluster-self-test-start.adoc[rpk cluster self-test start]
* xref:./rpk-cluster-self-test-stop.adoc[rpk cluster self-test stop]
