= rpk cluster config edit

Edit cluster-wide configuration properties.

This command opens a text editor to modify the cluster's configuration.

Cluster properties are Redpanda settings that apply to all brokers in
the cluster. These are separate from broker properties, which you can set with `rpk redpanda config`.

Modified values are saved after the file is saved and the editor
is closed. If you delete a property, Redpanda resets it to its default
value.

By default, low-level tunables are excluded. Use the `--all` flag
to edit all properties including tunables.

== Usage

[,bash]
----
rpk cluster config edit [flags]
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-h, --help |- |Help for edit.

|--all |- |Include all properties, including tunables.

|--config |string |Redpanda or `rpk` config file; default search paths are `/var/lib/redpanda/.config/rpk/rpk.yaml`, `$PWD/redpanda.yaml`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override `rpk` configuration settings. See xref:reference:rpk/rpk-x-options.adoc[`rpk -X`] or execute `rpk -X help` for inline detail or `rpk -X list` for terser detail.

|--profile |string |Profile to use. See xref:reference:rpk/rpk-profile.adoc[`rpk profile`] for more details.

|-v, --verbose |- |Enable verbose logging.
|===

