= rpk cluster partitions move-cancel

Cancel ongoing partition movements.


By default, this command cancels all the partition movements in the cluster. 

To ensure that you do not accidentally cancel all partition movements, this  command prompts users for confirmation before issuing the cancellation request. 


== Example 

You can use `--no-confirm` to disable the confirmation prompt:

```bash
rpk cluster partitions move-cancel --no-confirm
```

If `--node` is set, this command will only stop the partition movements occurring in the specified broker:

```bash
rpk cluster partitions move-cancel --node 1
```

== Usage

[,bash]
----
rpk cluster partitions move-cancel [flags]
----

== Aliases

[,bash]
----
move-cancel, alter-cancel
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-h, --help |- |Help for move-cancel.

|--no-confirm |- |Disable confirmation prompt.

|--node |int |ID of a specific broker on which to cancel ongoing partition movements (default -1).

|--config |string |Redpanda or rpk config file; default search paths are ~/.config/rpk/rpk.yaml, $PWD, and /etc/redpanda/`redpanda.yaml`.

|-X, --config-opt |stringArray |Override rpk configuration settings; '-X help' for detail or '-X list' for terser detail.

|--profile |string |rpk profile to use.

|-v, --verbose |- |Enable verbose logging.
|===