= Enterprise Edition for Redpanda Console
:description: Learn how about Enterprise Edition for Redpanda Console.

This topic introduces Enterprise Edition for Redpanda Console, how Redpanda Console handles licenses at startup, and methods for managing licenses.

== Enterprise features in Redpanda Console

Redpanda Console offers the following enterprise features. To access these features, you must provide a valid Enterprise Edition license.

include::get-started:partial$enterprise-features.adoc[tag=console]

See also: xref:get-started:licensing/overview.adoc[]

== How Redpanda Console handles licenses

If Redpanda Console cannot find a valid license either locally or in the connected Redpanda cluster, it shuts down. Redpanda Console tries to load a valid license at startup in the following order:

. From the local configuration file or environment variables.
. From the connected Redpanda cluster (if available).

Either method can be used to enable Redpanda Console enterprise features. Redpanda Console displays warnings in the following scenarios:

- *Upcoming license expiration*: Redpanda Console checks the license status at startup. If the license expires within 30 days, a warning is displayed in the UI. Redpanda Console also logs the license details at startup, including the expiration date. For example:
+
[,json]
----
{"level":"info","msg":"successfully loaded Redpanda Enterprise license","license_org":"redpanda","license_type":"enterprise","expires_at":"Oct 12 2024"}
----

- *Enterprise features in Redpanda cluster without a valid license*: If the Redpanda cluster is using enterprise features without a valid license, Redpanda Console displays a warning specifying the features in use without proper licensing.

- *Redpanda Console enterprise features without a valid license*: If you configure enterprise features in Redpanda Console without a valid license, Redpanda Console shuts down and logs a warning.

== Ways to manage licenses for Redpanda Console

Redpanda Console offers two methods for applying or updating a license, depending on your setup:

- If you are using Redpanda Console without connecting it to a Redpanda cluster, you can xref:console:config/enterprise-license.adoc[configure the license through the local configuration file or environment variables]. This method allows you to apply a license for Redpanda Console independently of the Redpanda cluster.

- If Redpanda Console is connected to a Redpanda cluster, you can xref:console:ui/add-license.adoc[upload a license through the Redpanda Console UI]. This method allows you to manage and update licenses for both Redpanda Console and the connected Redpanda cluster.

== Next steps

- xref:console:config/enterprise-license.adoc[]
- xref:console:ui/add-license.adoc[]