= Disable Enterprise Features in Redpanda
:description: Disable specific enterprise features in Redpanda to ensure your cluster operates within the scope of the Community Edition without enterprise features.

Enterprise features in Redpanda are available only in the Enterprise Edition and require a valid license. If your cluster has enterprise features enabled without a valid license, it is essential to either upload a valid license or disable these features to maintain compliance with Redpanda licensing terms.

== Prerequisites

Before you begin, consider the following:

- Take a backup of your current configuration to allow rollback if needed.

- Disabling enterprise features may affect cluster performance, security, or functionality. Test these changes in a staging environment before applying them to production.

- If you need enterprise features, consider purchasing a valid license to continue using them. To get a trial license key or extend your trial period, https://redpanda.com/try-enterprise[generate a new trial license key^]. To purchase a license, contact https://redpanda.com/upgrade[Redpanda Sales^].

== Check for enterprise features in violation

To check the status of your license, use the `rpk cluster license info` command. This command provides a detailed overview of your Redpanda license, including whether your cluster has enterprise features enabled without a valid license.

[NOTE]
====
This command reports license violations only if enterprise features in Redpanda are enabled without a valid license. It does not report license violations for enterprise features in xref:get-started:licensing/overview.adoc#connect[Redpanda Connect] or xref:get-started:licensing/overview.adoc#console[Redpanda Console].
====

. Ensure that xref:get-started:rpk-install.adoc[`rpk` is installed] and configured to connect to your cluster's Admin API endpoint.

. Get the details about your cluster's license:
+
[,bash]
----
rpk cluster license info
----
+
If the `License violation` status is `true`, you must either obtain a valid license or disable the enterprise features in use to ensure compliance.
+
If the license is within 30 days of expiration, a warning is logged:
+
[.no-copy]
----
warning: your license will expire soon
----

== Disable enterprise features

To disable specific enterprise features, refer to the following table:

[NOTE]
====
These instructions apply to bare-metal deployments on Linux. If you are running Redpanda in a different environment, such as Kubernetes or Docker, the way you disable features may vary.
====

[cols="1a,2a"]
|===
| Feature | Action to Disable

| xref:manage:audit-logging.adoc[Audit Logging]
|
Set the cluster config `audit_enabled` to `false`:

[,bash]
----
rpk cluster config set audit_enabled false
----

| xref:manage:cluster-maintenance/continuous-data-balancing.adoc[Continuous Data Balancing]
|
Set the cluster config `partition_autobalancing_mode` to `node_add`:

[,bash]
----
rpk cluster config set partition_autobalancing_mode node_add
----

| xref:manage:cluster-maintenance/cluster-balancing.adoc#intra-broker-partition-balancing[Continuous Intra-Broker Partition Balancing]
(`core_balancing_continuous`)
|
Set the cluster config `core_balancing_continuous` to `false`:

[,bash]
----
rpk cluster config set core_balancing_continuous false
----

| xref:manage:security/fips-compliance.adoc[FIPS Compliance]
|
Set the node config `fips_mode` to `disabled`:

[,bash]
----
rpk node config set fips_mode disabled
----

| xref:manage:security/authentication.adoc#kerberos[Kerberos authentication]
|
Remove `GSSAPI` from the cluster config `sasl_mechanisms`:

[,bash]
----
rpk cluster config set sasl_mechanisms <other-mechanisms>
----

| xref:manage:security/authentication.adoc#kerberos[Leader Pinning]
|
Set `default_leaders_preference` to `none`:

[,bash]
----
rpk cluster config set default_leaders_preference none
----

| xref:manage:security/authentication.adoc#oidc[OAUTHBEARER/OIDC authentication]
|
Remove `OIDC` from the cluster config `sasl_mechanisms` and `http_authentication`:
[,bash]
----
rpk cluster config set sasl_mechanisms <other-mechanisms>
rpk cluster config set http_authentication <other-mechanisms>
----

| xref:manage:remote-read-replicas.adoc[Remote Read Replicas]
|
Set the cluster config `cloud_storage_enable_remote_read` to `false`:

[,bash]
----
rpk cluster config set cloud_storage_enable_remote_read false
----

| xref:manage:security/authorization/rbac.adoc[Role-Based Access Control (RBAC)]
|
Use `rpk security role delete` to delete all configured roles:

[,bash]
----
rpk security role list
rpk security role delete <role-name>
----

| xref:manage:schema-reg/schema-id-validation.adoc[Server-Side Schema ID Validation]
|
Set the cluster config `enable_schema_id_validation` to `false`:

[,bash]
----
rpk cluster config set enable_schema_id_validation false
----

| xref:manage:tiered-storage.adoc[Tiered Storage]
|
Set the cluster config `cloud_storage_enabled` to `false`:

[,bash]
----
rpk cluster config set cloud_storage_enabled false
----

|===

== Verify the license status

When all required changes are made, confirm that the `license violation` status is now `false`.

[,bash]
----
rpk cluster license info
----

== Suggested reading

For more information about licensing, see xref:get-started:licensing/overview.adoc[].
