= Check the Status of an Enterprise Edition License
:description: pass:q[Learn how to monitor the status of your Redpanda Enterprise Edition license using `rpk`, the Redpanda Console, the Admin API, and observability tools such as logs and metrics.]

To track license expiration and ensure compliance with xref:get-started:licensing/overview.adoc[Redpanda licensing], you can monitor the status of your Enterprise Edition license using <<rpk, `rpk`>>, <<console, Redpanda Console>>, and observability tools such as <<logs, logs>> and <<metrics, metrics>>.

[[rpk]]
== Use `rpk` to check license status and feature usage

To check the status of your license, use the `rpk cluster license info` command. This command provides a detailed overview of your Redpanda license, including its status, expiration, and enterprise features currently in use.

NOTE: Enterprise features in use are specific to Redpanda. They do not include enterprise features for xref:get-started:licensing/overview.adoc#connect[Redpanda Connect] or xref:get-started:licensing/overview.adoc#console[Redpanda Console].

. Make sure that xref:get-started:rpk-install.adoc[`rpk` is installed] and configured to connect to your cluster's Admin API endpoint.

. Get the details about your cluster's license:
+
```bash
rpk cluster license info
```
+
The command displays the license information in a user-friendly format. The output depends on the license status. It can include the following:
+
- *License status*: Indicates the current state of the license. Possible values include:
  ** `valid`: The license is active and valid.
  ** `expired`: The license has expired, and restrictions may apply to enterprise features.
  ** `not_present`: No license is currently applied.

- *License violation*: A boolean value that indicates whether enterprise features are being used in violation of the licensing terms:
  --
  ** `true`: Enterprise features are enabled without a valid license.
  ** `false`: No violations are detected.
  --
+
[NOTE]
====
If the `license violation` status is `true`, you must either obtain a valid license or disable the enterprise features in use to ensure compliance.
For instructions, see xref:get-started:licensing/disable-enterprise-features.adoc[].
====

- *Organization*: The organization for which the license was issued. Typically corresponds to the organization that purchased or activated the license.

- *Type*: The type of license applied to the cluster:
  ** `enterprise`: A full-featured enterprise license.
  ** `trial`: A time-limited trial license.

- *Expires*: The expiration date of the current license. After this date, the license status changes to `expired`.

- *Enterprise features in use*: A list of enabled enterprise features in the cluster, such as: `tiered_storage`, `audit_logging`, and `partition_auto_balancing_continuous`.

If the license is within 30 days of expiration, a warning is logged:

----
warning: your license will expire soon
----

=== Examples

This section provides examples of what `rpk` reports depending on the license status.

Valid license:

[.no-copy]
----
LICENSE INFORMATION
===================
License status:              valid
License violation:           false
Enterprise features in use:  [partition_auto_balancing_continuous]
Organization:                Devex
Type:                        enterprise
Expires:                     Oct 11 2025
----

Without a valid license:

[.no-copy]
----
LICENSE INFORMATION
===================
License status:              not_present
License violation:           false
Enterprise features in use:  [partition_auto_balancing_continuous]
----

Expired license:

[.no-copy]
----
WARNING: The following enterprise features are being used in your Redpanda cluster: [partition_auto_balancing_continuous]. These features require a license.
LICENSE INFORMATION
===================
License status:              expired
License violation:           true
Enterprise features in use:  [partition_auto_balancing_continuous]
----

=== Change the output format

Different output formats can be useful depending on your scenario. For example, if you are writing scripts or automating license monitoring, you may prefer the JSON format, as it's easily parsed by tools like `jq` or integrated into monitoring systems.

To get the license information in another format, use the `--format` flag:

```bash
rpk cluster license info --format <format>
```

Replace `<format>` with one of the available formats. See xref:reference:rpk/rpk-cluster/rpk-cluster-license-info.adoc[].

[[console]]
== Use Redpanda Console to check license status

You can also check the status of your license in the Redpanda Console UI. See xref:console:ui/add-license.adoc[].

If Redpanda Console cannot find a valid license either locally or in the connected Redpanda cluster, it shuts down. Redpanda Console tries to load a valid license at startup in the following order:

. From the local configuration file or environment variables.
. From the connected Redpanda cluster (if available).

Redpanda Console displays warnings in the following scenarios:

- *Upcoming license expiration*: Redpanda Console checks the license status at startup. If the license expires within 30 days, a warning is displayed in the UI. Redpanda Console also logs the license details at startup, including the expiration date. For example:
+
[,json]
----
{"level":"info","msg":"successfully loaded Redpanda Enterprise license","license_org":"redpanda","license_type":"enterprise","expires_at":"Oct 12 2024"}
----

- *Redpanda Self-Managed enterprise features are in use without a valid license*: If the Redpanda cluster is using enterprise features without a valid license, Redpanda Console displays a warning specifying the features in use without proper licensing.

[[logs]]
== Monitor a license in the logs

Logs are emitted on Redpanda brokers to help you understand how the license is being applied and when enforcement actions are triggered.

[[metrics]]
== Monitor a license using metrics

The xref:reference:public-metrics-reference.adoc#redpanda_cluster_features_enterprise_license_expiry_sec[`redpanda_cluster_features_enterprise_license_expiry_sec`] metric tells you how many seconds remain until the license expires. Use this metric to set up alerts or dashboards to track the license expiration status and ensure timely renewal.

== Next steps

- xref:get-started:licensing/disable-enterprise-features.adoc[]

