= Redpanda Licenses, Editions, and Enterprise Features
:description: Redpanda Self-Managed is free and source-available at the Redpanda GitHub repo. Additional features are included with an Enterprise license.
:page-aliases: introduction:licenses.adoc, get-started:licenses.adoc

Redpanda Self-Managed, Redpanda Console, and Redpanda Connect are available in either the Community Edition or the Enterprise Edition. Each product has its own binary, and each binary supports both the Community Edition and Enterprise Edition. Features in the Enterprise Edition (enterprise features) are only accessible with a valid license key.

* Redpanda Community Edition is free and source-available on GitHub:
** https://github.com/redpanda-data/redpanda[Redpanda Self-Managed^]
** https://github.com/redpanda-data/console[Redpanda Console^]
** https://github.com/redpanda-data/connect[Redpanda Connect^]
* Redpanda Enterprise Edition requires a license key and includes additional features.

[NOTE]
====
Redpanda Cloud is a managed deployment of Redpanda Enterprise Edition. To learn more about Redpanda Cloud, see the xref:redpanda-cloud:get-started:cloud-overview.adoc[].
====

== Community Edition

Community Edition is licensed with the Redpanda https://github.com/redpanda-data/redpanda/blob/dev/licenses/bsl.md[Business Source License^] (BSL). These core features are free and source-available.

[NOTE]
====
* Users cannot provide Redpanda as a commercial streaming or queuing service to others.
* The BSL code converts to Apache 2.0 licensing four years after each code merge.
====

== Enterprise Edition

Enterprise Edition is licensed with the https://github.com/redpanda-data/redpanda/blob/dev/licenses/rcl.md[Redpanda Community License^] (RCL). It includes the free features licensed under the Redpanda BSL, as well as enterprise features.

=== License keys

Enterprise features require an Enterprise Edition license key, sometimes referred to as Enterprise license, license key, or license. You can evaluate enterprise features with a free 30-day trial. To request a trial license key, to extend your trial period, or to purchase a license, contact https://redpanda.com/try-redpanda?section=enterprise-trial[Redpanda Sales^].

[[self-managed]]
=== Enterprise features in Redpanda Self-Managed

The following enterprise features for Redpanda Self-Managed are activated with a valid Enterprise Edition license key:

include::get-started:partial$licensing/enterprise-features.adoc[tag=self-managed]

[[console]]
=== Enterprise features in Redpanda Console

The following enterprise features for Redpanda Console are activated with a valid Enterprise Edition license key:

include::get-started:partial$licensing/enterprise-features.adoc[tag=console]

[[connect]]
=== Enterprise features in Redpanda Connect

The following enterprise features for Redpanda Connect are activated with a valid Enterprise Edition license key:

include::get-started:partial$licensing/enterprise-features.adoc[tag=connect]

== How Redpanda Console handles licenses

If Redpanda Console cannot find a valid license either locally or in the connected Redpanda cluster, it shuts down. Redpanda Console tries to load a valid license at startup in the following order:

. From the local configuration file or environment variables.
. From the connected Redpanda cluster (if available).

Either method can be used to enable Redpanda Console enterprise features. Redpanda Console displays warnings in the following scenarios:

- *Upcoming license expiration*: Redpanda Console checks the license status at startup. If the license expires within 30 days, a warning is displayed in the UI. Redpanda Console also logs the license details at startup, including the expiration date. For example:
+
[,json]
----
{"level":"info","msg":"successfully loaded Redpanda Enterprise license","license_org":"redpanda","license_type":"enterprise","expires_at":"Oct 12 2024"}
----

- *Enterprise features in Redpanda cluster without a valid license*: If the Redpanda cluster is using enterprise features without a valid license, Redpanda Console displays a warning specifying the features in use without proper licensing.

- *Redpanda Console enterprise features without a valid license*: If you configure enterprise features in Redpanda Console without a valid license, Redpanda Console shuts down and logs a warning.

=== Ways to manage licenses for Redpanda Console

Redpanda Console offers two methods for applying or updating a license, depending on your setup:

- If you are using Redpanda Console without connecting it to a Redpanda cluster, you can xref:console:config/enterprise-license.adoc[configure the license through the local configuration file or environment variables]. This method allows you to add a license for Redpanda Console independently of the Redpanda cluster.

- If Redpanda Console is connected to a Redpanda cluster, you can xref:console:ui/add-license.adoc[upload a license through the Redpanda Console UI]. This method allows you to manage and update licenses for both Redpanda Console and the connected Redpanda cluster.

== Next steps

- xref:get-started:licensing/add-license-redpanda/index.adoc[]
- xref:get-started:licensing/monitor-license-status.adoc[]