= rpk plugin uninstall

Uninstall or remove an existing local plugin.

This command lists locally installed plugins and removes the first plugin that
matches the requested removal. If `--include-shadowed` is specified, this command
also removes all shadowed plugins of the same name.

To remove a command under a nested namespace, concatenate the namespace. For example, for the nested namespace `rpk foo bar`, use the name `foo_bar`.

== Usage

[,bash]
----
rpk plugin uninstall [NAME] [flags]
----

== Aliases

[,bash]
----
uninstall, rm
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-h, --help |- |Help for uninstall.

|--include-shadowed |- |Also remove shadowed plugins that have the same
name.

|--config |string |Redpanda or `rpk` config file. Default search paths are
`~/.config/rpk/rpk.yaml`, `$PWD`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override `rpk` configuration settings. See xref:reference:rpk/rpk-x-options.adoc[`rpk -X`] or execute `rpk -X help` for inline detail or `rpk -X list` for terser detail.

|--profile |string |Profile to use. See xref:reference:rpk/rpk-profile.adoc[`rpk profile`] for more details.

|-v, --verbose |- |Enable verbose logging.
|===

