= rpk cluster partitions disable
:description: rpk cluster partitions disable

Disable partitions of a topic

You may disable all partitions of a topic using the --all flag or you may select 
a set of topic/partitions to disable with the '--partitions/-p' flag.

The partition flag accepts the format {namespace}/{topic}/[partitions...]
where namespace and topic are optional parameters. If the namespace is not
provided, rpk will assume 'kafka'. If the topic is not provided in the flag, rpk
will use the topic provided as an argument to this command.

DISABLED PARTITIONS

Disabling a partition in Redpanda involves prohibiting any data consumption or
production to and from it. All internal processes associated with the partition
are stopped, and it remains unloaded during system startup. This measure aims to
maintain cluster health by preventing issues caused by specific corrupted
partitions that may lead to Redpanda crashes. Although the data remains stored
on disk, Redpanda ceases interaction with the disabled partitions to ensure
system stability.

EXAMPLES

Disable all partitions in topic 'foo'
    rpk cluster partitions disable foo --all

Disable partitions 1,2 and 3 of topic 'bar' in the namespace 'internal'
    rpk cluster partitions disable internal/bar --partitions 1,2,3

Disable partition 1, and 2 of topic 'foo', and partition 5 of topic 'bar' in the 
'internal' namespace' 
    rpk cluster partitions disable -p foo/1,2 -p internal/bar/5

== Usage

[,bash]
----
rpk cluster partitions disable [TOPIC] [flags]
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-a, --all |- |If true, disable all partitions for the specified topic.

|-h, --help |- |Help for disable.

|-p, --partitions |stringArray |Comma-separated list of partitions you want to disable. Use --help for additional information.

|--config |string |Redpanda or rpk config file; default search paths are ~/.config/rpk/rpk.yaml, $PWD, and /etc/redpanda/`redpanda.yaml`.

|-X, --config-opt |stringArray |Override rpk configuration settings; '-X help' for detail or '-X list' for terser detail.

|--profile |string |rpk profile to use.

|-v, --verbose |- |Enable verbose logging.
|===