= Cluster Diagnostics
:description: Use tools and tests to help diagnose and debug a Redpanda cluster.
:page-categories: Management, Troubleshooting

This topic provides guides for using tools and tests to help diagnose and debug a Redpanda cluster.

[[self-test]]
== Disk and network self-test benchmarks

When anomalous behavior arises in a cluster and you're trying to figure out whether it's caused by faulty hardware (disks, NICs) of a cluster's machines, run xref:reference:rpk/rpk-cluster/rpk-cluster-self-test.adoc[rpk cluster self-test] (self-test) to characterize their performance and compare it with their expected, vendor-specified performance.

Self-test runs a set of benchmarks to determine the maximum performance of a machine's disks and network connections. For disks, it runs throughput and latency tests by performing concurrent sequential operations. For networks, it selects unique pairs of Redpanda nodes as client/server pairs, then it runs throughput tests between them. Self-test runs each benchmark for a configurable duration, and it returns IOPS, throughput, and latency metrics.

== Cloud storage tests

If you use xref:manage:tiered-storage.adoc[Tiered Storage], run self-test to verify that you have configured your cloud storage accounts correctly.

Self-test performs the following tests to validate cloud storage configuration:

include::reference:partial$rpk-self-test-cloud-tests.adoc[]

See the xref:reference:rpk/rpk-cluster/rpk-cluster-self-test-start.adoc[`rpk cluster self-test start`] reference for cloud storage test details.

== Self-test command examples

=== Start self-test

To begin using self-test, run the `self-test start` command.

----
rpk cluster self-test start
----

For command help, run `rpk cluster self-test start -h`. For additional command flags, see the xref:reference:rpk/rpk-cluster/rpk-cluster-self-test-start.adoc[rpk cluster self-test start] reference.

Before it starts, `self-test start` asks for your confirmation to run its potentially large workload.

Example start output:

[.no-copy]
----
? Redpanda self-test will run benchmarks of disk and network hardware that will consume significant system resources. Do not start self-test if large workloads are already running on the system. (Y/n)
Redpanda self-test has started, test identifier: "031be460-246b-46af-98f2-5fc16f03aed3", To check the status run:
rpk cluster self-test status
----

The `self-test start` command returns immediately, and self-test runs its benchmarks asynchronously.

=== Check self-test status

To check on the status of self-test, run the `self-test status` command.

[,bash]
----
rpk cluster self-test status
----

For command help, run `rpk cluster self-test status -h`. For additional command flags, see the xref:reference:rpk/rpk-cluster/rpk-cluster-self-test-status.adoc[rpk cluster self-test status] reference.

If benchmarks are currently running, `self-test status` returns a test-in-progress message.

Example status output:

[.no-copy]
----
$ rpk cluster self-test status
Nodes [0 1 2] are still running jobs
----

[TIP]
====
To automate checking the status of self-test, the `status` command can output its results in JSON format by using the `--format=json` option:

[,bash]
----
rpk cluster self-test status --format=json
----

====

If benchmarks have completed, `self-test status` returns their results.

include::reference:partial$rpk-self-test-descriptions.adoc[]

.Example status output: test results
include::reference:partial$rpk-self-test-status-output.adoc[]

=== Stop self-test

To stop a running self-test, run the `self-test stop` command.

----
rpk cluster self-test stop
----

Example stop output:

[.no-copy]
----
$ rpk cluster self-test stop
All self-test jobs have been stopped
----

For command help, run `rpk cluster self-test stop -h`. For additional command flags, see the xref:reference:rpk/rpk-cluster/rpk-cluster-self-test-stop.adoc[rpk cluster self-test stop] reference.

For more details about self-test, including command flags, see xref:reference:rpk/rpk-cluster/rpk-cluster-self-test.adoc[rpk cluster self-test].
