= Optimize Compaction Settings
:description: Redpanda's approach to compaction and options for configuring it

Configure compaction for your cluster to optimize storage utilization.

== Repanda Compaction Overview

Compaction is an optional mechanism intended to reduce the storage needs of Redpanda topics. Compaction is enabled through configuration of a cluster or topic's cleanup policy. The cleanup policy is triggered when the retention policy for a given topic is exceeded - either when messages age out or when the topic exceeds a set size - and it operates on a per-partition basis within the topic. When compaction is triggered for a partition, older versions of messages for a given key are purged and only the most recent message in that partition is retained.

Two important considerations must be mentioned for compaction. First, when using tiered storage, compaction functions at the local level before partitions are uploaded to storage. Once a partition is uploaded to storage it is not retrieved for further compaction operations. Second, compaction on Redpanda is bounded by raft leadership terms. The same key may appear across multiple raft terms.

While compaction does reduce storage needs, Redpanda's compaction (just like Kafka's) does not guarantee perfect de-duplication of a topic. Duplicates of a message, or additional messages, may still exist within a topic ordered by time. Compaction is not a complete topic operation, it represents a best effort mechanism to reduce storage needs for things created within a certain time window.

== Configuring Cleanup Policy

Compaction policy may be configured at the cluster level or at the individual topic level. The cluster-level xref:reference:cluster-properties.adoc#_log_cleanup_policy[`log_cleanup_policy`] or topic-level xref:reference:topic-properties.adoc#cleanuppolicy[`cleanup.policy`] supports the following three options:

* `delete`: Messages are deleted from the topic once the specified retention period (time and/or size allocations) is exceeded. This is the default mechanism and is analagous to disabling compaction.
* `compact`: This triggers only cleanup of messages with multiple versions. A message that represents the only version for a given key is not deleted.
* `compact,delete`: This combines both policies, deleting messages exceeding the retention period while compacting multiple versions of messages.

== Retention Policy Settings

The various cleanup policy settings rely on proper tuning of a cluster's or topic's retention policy. The applicable settings include the following options: