= Configure Broker Properties
:description: pass:q[Learn how to configure broker properties with the `redpanda.yaml` file.]
:page-aliases: cluster-administration:node-property-configuration.adoc, deploy:deployment-option/self-hosted/manual/node-property-configuration.adoc, deploy:redpanda/manual/node-property-configuration.adoc
:page-categories: Management

When you install Redpanda, a `redpanda.yaml` file is installed on each broker in `/etc/redpanda`. This file contains broker configuration properties. A broker property is one that can be set differently from broker to broker, such as xref:reference:properties/broker-properties.adoc#data_directory[`data_directory`] or xref:reference:properties/broker-properties.adoc#node_id[`node_id`] (when specified). See xref:reference:properties/broker-properties.adoc[Broker Configuration Properties] for a list of broker properties, their descriptions, and their default values.

The default `redpanda.yaml` file groups broker properties into categories:

* `pandaproxy` - Properties for the Redpanda HTTP Proxy
* `redpanda` - Runtime configuration properties, such as the cluster member IP addresses and the data directory
* `rpk` - Properties that determine how `rpk` starts Redpanda
* `schema registry` - Properties related to storage, retrieval, and compatibility of the schemas

== Set broker configuration properties

The `redpanda.yaml` file rarely needs to be edited after the system is installed, but you can choose to change broker configuration property values.

NOTE: The broker configuration property xref:reference:properties/broker-properties.adoc[`node_id`] is immutable. To ensure safe operations, omit the `node_id` field from `redpanda.yaml` and allow Redpanda to assign it automatically. For more information, see xref:deploy:deployment-option/self-hosted/manual/production/production-deployment.adoc#do-not-configure-broker-ids[Do not configure broker IDs].

To change a broker property setting:

. Open a terminal window and navigate to the broker where you want to change a property setting.
. Go to the `/etc/redpanda` directory.
. Open the `redpanda.yaml` file.
. Change values for properties as needed.
. Save the file and close the editor.
. Restart the broker to apply the changes.

When Redpanda starts up and reads the `redpanda.yaml` file, it checks that each property setting has a valid value. If the file contains an invalid property setting, Redpanda logs an error and refuses to start.
