= Recovery Mode
:description: 

Recovery mode allows you to start Redpanda and form a stable cluster when a cluster fails due to a system crash, OOM errors, or other issues that make a normal startup infeasible. 

In recovery mode, cluster configuration changes and other manual administrative actions are permitted so you can repair and recover the failed cluster. Communication between producers and consumers, as well as topic reads and writes, are disabled.

== About recovery mode

Recovery mode starts a cluster with limited functionality and deactivates normal traffic and data operations for a cluster. This provides a more stable environment for troubleshooting issues and restoring the cluster to a usable state. 

Recovery mode helps to prevent triggering a storm of partition leader elections and replication (e.g. heavy learner replica recovery load after a long broker downtime) that typically occurs on startup (especially after some downtime). 

Normal traffic and especially malicious traffic can disrupt availability for all users, including admin users. Recovery mode helps avoid placing the cluster under a heavy load of Kafka API and HTTP Proxy connections as you are working to resuscitate the cluster.

== Requirements

Recovery mode can only be entered during initial cluster formation as brokers start up and not while they are already running.

== Use recovery mode

To use recovery mode, first configure the node property to enable recovery mode when a broker starts. Once enabled, you can also disable partitions, if the cluster failure is localized to just a few partitions.

=== Enable recovery mode

. Run the `rpk redpanda mode` command to set the `recovery_mode_enabled` broker configuration property to `true`.
// TODO: confirm whether rpk command is available
// TODO: required flags
+
[,bash] 
---- 
rpk 
----
+
. Start the cluster. You can run `rpk cluster health` to check whether the cluster has entered recovery mode.

All brokers in the cluster must enter recovery mode together. If a cluster starts and a broker that doesn't have recovery mode enabled attempts to join, the broker will exit and return an error.

All private Redpanda topics such as `__consumer_offsets` are accessible. While data in user-created topics is not available, you can manage the topics metadata.

You can perform the following operations in recovery mode:
* Edit controller metadata
** Edit cluster configurations
** Enable and disable features
** Add and remove users and ACLs
** Add new brokers to the cluster
** Modify topic properties
** Delete topics
** Delete WASM transforms
* Edit consumer group metadata

Node-wide and cluster-wide processes are disabled as they may disrupt recovery operations:
* Partition and leader balancers
* Tiered storage object storage housekeeping
* Tiered storage cache management
* Compaction

You can use the Admin API when the cluster is in recovery mode. The HTTP Proxy and Schema Registry APIs are not available.

=== Disable partitions

You may find that problems preventing normal cluster startup are often isolated to certain partitions or topics. In these situations, you can manage the partition using the Admin API. You can disable partitions at the topic level, or individual partition level. 

After you disable these partitions and exit recovery mode, starting Redpanda again in non-recovery mode leaves these partitions in a deactivated state. Disabled partitions and topics return a "Replica Not Available" message when making Kafka API requests.

The examples below assume that the Admin API port is `8081`.

==== Disable a specific partition of a topic

// TODO: Confirm whether these are new API endpoints and that they are available
[tabs]
====
Curl::
+
--
curl -X POST -d '{"disabled": true}' http://localhost:8081/cluster/partitions/kafka/<topic_name>/<partition_id>
--
rpk::
+
--
rpk cluster partitions disable --topic <topic_name> --partition <partition_id>
--
====

==== Enable a specific partition of a topic

[tabs]
====
Curl::
+
--
curl -X POST -d '{"disabled": false}' http://localhost:8081/cluster/partitions/kafka/<topic_name>/<partition_id>
--
rpk::
+
--
rpk cluster partitions enable --topic <topic_name> --partition <partition_id>
--
====

==== Disable all partitions of a specific topic

[tabs]
====
Curl::
+
--
curl -X POST -d '{"disabled": true}' http://localhost:8081/cluster/partitions/kafka/<topic>
--
rpk::
+
--
rpk cluster partitions disable --topic <topic>
--
====

==== Enable all partitions of a specific topic

[tabs]
====
Curl::
+
--
curl -X POST -d '{"disabled": false}' http://localhost:8081/cluster/partitions/kafka/<topic>
--
rpk::
+
--
rpk cluster partitions enable --topic <topic>
--
====

==== List all disabled partitions

[tabs]
====
Curl::
+
--
curl http://localhost:8081/cluster/partitions?disabled=true
--
rpk::
+
--
rpk cluster partitions list --disabled
--
====

==== List all disabled partitions of a specific topic

[tabs]
====
Curl::
+
--
curl http://localhost:8081/cluster/partitions/kafka/<topic>?disabled=true
--
rpk::
+
--
rpk cluster partitions list --topic <topic> --disabled
--
====

== Troubleshooting








