= Redpanda Operator - Deploy
:description: Redpanda BYOC Cloud Deployment
:pagination_next:
:pagination_prev:

:::important
This section uses the Redpanda Operator. To use the recommended Redpanda Helm chart, see xref:manage:kubernetes.adoc[Manage Redpanda in Kubernetes].
:::

* xref:redpanda-operator:kubernetes-connectivity.adoc[Configure the Kubernetes Operator for Connectivity]
+
Configure the Redpanda Operator for internal and external connectivity.

* xref:redpanda-operator:kubernetes-external-connect.adoc[Connect Remotely to Kubernetes]
+
Set up the Redpanda Operator in Google GKE, Amazon EKS, or Digital Ocean, so you can work with Redpanda from outside of the Kubernetes network.

* xref:redpanda-operator:kubernetes-additional-config.adoc[Custom Configuration in Kubernetes]
+
Customize the Custom Resource Definition (CRD) with basic configuration for the Redpanda cluster and configuration for the APIs.

* xref:redpanda-operator:arbitrary-configuration.adoc[Use Additional Configuration Parameters for the Redpanda Operator]
+
Create a Redpanda cluster by applying a cluster Custom Resource (CR) that contains the specification of the desired Redpanda cluster.
