= Add a Dedicated VPC Peering Connection
:description: Use the Redpanda Cloud UI to set up VPC peering.
:page-aliases: cloud:vpc-peering.adoc
:page-cloud: true

A VPC peering connection is a networking connection between two VPCs. This connection allows the VPCs to communicate with each other as if they were within the same network. A route table routes traffic between the two VPCs using private IPv4 addresses.

NOTE: Traffic is _not_ routed over the public internet.

When you select a network for deploying your Redpanda Dedicated cluster, you have the option to select a private connection with VPC peering. The VPC peering connection connects your VPC to the Redpanda Cloud VPC.

== Prerequisites

* *VPC network*: Before you set up a peering connection in the Redpanda Cloud UI, you must have a VPC in your own account for Redpanda's VPC to connect to. If you do not already have a VPC, log in to the AWS VPC Console and create one.
* *Matching region*: VPC peering connections can only be established between networks created in the *same region*. Redpanda Cloud does not support inter-region VPC peering connections.
* *Non-overlapping CIDR blocks*: The CIDR block for your VPC network cannot match or overlap with the CIDR block for the Redpanda Cloud VPC.

TIP: Consider adding `rp` at the beginning of the VPC name to indicate that this VPC is for deploying a Redpanda cluster.

== Create a peering connection

To create a peering connection between your VPC and Redpanda's VPC:

. In the Redpanda Cloud UI, go to the *Overview* page for your cluster.
. In the Details section, click the name of the Redpanda network.
. On the *Network* page, click *+Add peering connection*.
. In *Connection name*, enter a name for the connection.
+
For example, the name might refer to the VPC ID of the VPC you created in AWS.

. In *AWS account number*, enter the account number associated with the VPC you want to connect to.
. In *AWS VPC ID*, enter the VPC ID by copying it from the AWS VPC Console.
. Click *Create peering connection*.

== Accept the peering connection request

Redpanda sends a peering request to the AWS VPC console. You must accept the request from the Redpanda VPC to set up the peering connection.

. Log in to the Amazon VPC console.
. Select the region where the VPC was created.
. From the navigation menu, select *Peering Connections*.
. Under *Requester VPC*, select the VPC you created for use with Redpanda.
+
The status should say "Pending acceptance".

. Open the *Actions* menu and select *Accept Request*.
. In the confirmation dialog box, verify that the requester owner ID corresponds to the Redpanda account, and select *Yes, Accept*.
. In the next confirmation dialog box, select *Modify my route tables now*.
