= Data Task Stability


## Overview

The `oxla_data_task_stability` table provides information about the stability of data tasks for tables within Oxla.

* Data tasks are background processes responsible for normalizing and maintaining data layouts 
* The stability status indicates whether the table's files have been processed and are up-to-date
* Regardless of the stability status the table is ready to be queried 

## Example

When running the command below:

[source,sql]
----
SELECT * FROM oxla_internal.oxla_data_task_stability;
----


you will get the following output:

[source,sql]
----
table_id | namespace_id | database_id | is_stable 
----------+--------------+-------------+-----------
    16384 |            0 |           0 | t
(1 row)
----


## Table Schema

[cols="1,1,1,1",options="header"]
|===
|Column Name |Data Type |Constraints |Description

|`table_id` |`BIGINT` |`NOT NULL` |Unique identifier for the table
|`namespace_id` |`BIGINT` |`NOT NULL` |Identifier for the namespace that the table belongs to
|`database_id` |`BIGINT` |`NOT NULL` |Identifier for the database where the table is located
|`is_stable` |`BOOL` |`NOT NULL` |Indicates the state of the data task. `false` means the files are either being processed or queued for processing. `true` means the files have been processed, are stable and this state persists until the user updates the data in the table
|===


[NOTE]
====
You can join the `table_id`, `namespace_id` and `database_id` columns with other virtual tables to obtain human-readable names for the table, namespace and database
====
