= Manage
:description: Manage Redpanda.

* xref:manage:kubernetes.adoc[Kubernetes]
* xref:manage:kubernetes:configure-helm-chart.adoc[Customize the Helm Chart]
+
You can customize the Redpanda Helm chart to configure the cluster and the Kubernetes components that the chart deploys.

 ** xref:manage:kubernetes:configure-storage.adoc[Storage]
+
Store Redpanda data in PersistentVolumes, hostPath volumes, or emptyDir volumes.

 ** xref:manage:kubernetes:tiered-storage.adoc[Tiered Storage]
+
Tiered Storage lets you save storage costs by offloading log segments to cloud storage.

 ** xref:manage:kubernetes:networking:networking-and-connectivity.adoc[Networking and Connectivity]
+
Learn how internal and external connectivity works when Redpanda is running in Kubernetes.

 ** xref:manage:kubernetes:security.adoc[Security]
+
Configure encryption, authentication, and authorization for production environments.

 ** xref:manage:kubernetes:kubernetes-rack-awareness.adoc[Rack Awareness]
+
Distribute replicas of the same partition across different racks to minimize data loss in the event of a rack failure.

 ** xref:manage:kubernetes:remote-read-replicas.adoc[Remote Read Replicas]
+
A Remote Read Replica topic is a read-only topic that mirrors a topic on a different cluster.

 ** xref:manage:kubernetes:troubleshooting:troubleshoot.adoc[Troubleshooting]
+
Find advice on how to diagnose and troubleshoot problems with Redpanda in Kubernetes.

* xref:manage:cluster-maintenance.adoc[Cluster Maintenance]
 ** xref:manage:cluster-maintenance:cluster-balancing.adoc[Cluster Balancing]
+
When a topic is created, Redpanda evenly distributes its partitions by sequentially allocating them to the node with the least number of partitions. By default, Redpanda provides leadership balancing and partition rebalancing when nodes are added or decommissioned.

 ** xref:manage:cluster-maintenance:continuous-data-balancing.adoc[Continuous Data Balancing]
+
Continuous Data Balancing continuously monitors your node and rack availability and disk usage. This enables self-healing clusters that dynamically balance partitions, ensuring smooth operations and optimal cluster performance.

 ** xref:manage:cluster-maintenance:rolling-upgrade.adoc[Rolling Upgrades]
+
One of the primary uses for maintenance mode is to perform a rolling upgrade on each node in the cluster. This process involves putting a node into maintenance mode, upgrading the node, taking the node out of maintenance mode, and then repeating the process on the next node in the cluster. Placing nodes into maintenance mode ensures a smooth upgrade of your cluster while reducing the risk of interruption or degradation in service.

 ** xref:manage:cluster-maintenance:disk-utilization.adoc[Manage Disk Space]
+
Redpanda provides several ways to manage disk space to ensure the production stability of the cluster.

 ** xref:manage:cluster-maintenance:cluster-property-configuration.adoc[Cluster Properties]
+
When you install Redpanda software, it automatically generates a cluster configuration with default settings assigned to each cluster property.
  You might want to change some of the default settings, particularly if you plan to use features such as rack awareness or tiered storage, which are disabled by default.
* xref:manage:security.adoc[Security]
 ** xref:manage:security:authentication.adoc[Configure Authentication]
+
Different components of Redpanda support different authentication methods. You can configure multiple listeners with `redpanda.yaml`, and with each listener, you can configure the `authentication_method` and optionally TLS or mTLS.

 ** xref:manage:security:authorization.adoc[Configure Authorization]
+
Authorization works in tandem with xref:manage:security:authentication.adoc[authentication]. Access-control lists (ACLs) provide a way to configure fine-grained access to provisioned users. ACLs work with SASL/SCRAM and with mTLS with principal mapping for authentication.

 ** xref:manage:security:encryption.adoc[Configure Encryption]
+
By default, Redpanda data is sent unencrypted. A security best practice is to enable encryption with TLS or mTLS.

 ** xref:manage:security:iam-roles.adoc[IAM Roles]
+
For self-hosted clusters deployed on a public cloud platform, cloud provider IAM roles provide a safer alternative to the less secure static credential system, which is based on access keys. With static credentials, the access key and secret key are stored in plaintext in the configuration file.

 ** xref:manage:security:console.adoc[Redpanda Console Security]
  *** xref:manage:security:console:github.adoc[GitHub SSO Setup]
+
Integrating Redpanda Console with GitHub allows your users to use their GitHub identities to sign-in to Console.

  *** xref:manage:security:console:google.adoc[Google SSO Setup]
+
Integrating Redpanda Console with Google allows your users to use their Google identities to sign in to Console.

  *** xref:manage:security:console:okta.adoc[Okta SSO Setup]
+
Integrating Redpanda Console with Okta allows your users to use their Okta identities to sign in to Redpanda Console.

  *** xref:manage:security:console:generic-oidc.adoc[Generic OIDC]
+
If you would like to integrate an OpenID Connect (OIDC) compatible identity provider that is not yet natively supported in Console,
you can configure the generic OIDC provider.
