= Optimize I/O
:description: Learn how to optimize I/O performance.
:page-aliases: deployment:io-optimization.adoc, install-upgrade:autotune.adoc
:page-categories: Management

Redpanda relies on its own disk I/O scheduler, and by default, it tells the kernel to
use the `noop` scheduler. Additionally, `rpk` comes with an embedded database of I/O settings, which are specific combinations of CPUs, SSD types, and VM sizes. Because running software on four VCPUs isn't the same as running on an EC2 i3.metal with 96 physical cores, Redpanda tries to predict the best known settings for VM cloud types.

== System tuning

For general system optimization, use xref:reference:rpk/rpk-redpanda/rpk-redpanda-tune.adoc[rpk redpanda tune] (autotuner), which is a suite of tuners that automatically modify Linux kernel settings to optimize performance.

== I/O configuration

Redpanda can optimize its I/O performance using predefined configurations for common cloud instances and hardware types.

=== Well-known I/O configurations

Currently in its database of I/O settings, Redpanda has well-known-types for AWS and GCP. On startup, `rpk` tries to detect the cloud and instance type from the cloud's metadata API, setting the correct I/O properties.

If access to the metadata API isn't allowed from the instance, you can hint the desired setup by passing the `--well-known-io` flag with the cloud vendor, VM type, and storage type:

[,bash]
----
rpk redpanda start --well-known-io 'aws:i3.xlarge:default'
----

It can also be specified in the `redpanda.yaml` configuration file, under the `rpk`
object:

[,yaml]
----
rpk:
  well_known_io: 'gcp:c2-standard-16:nvme'
----

[TIP]
====
* If `well-known-io` is specified in the config file and also as a flag, then the flag takes precedence.
* Both `--well-known-io` and `rpk.well_known_io` cannot be set at the same time as `--io-properties-file` or `--io-properties`.
====

=== Custom I/O properties

For custom I/O configurations, you can provide I/O properties using a configuration file or as a string parameter.

Using a configuration file:

[,bash]
----
rpk redpanda start --io-properties-file '<io-properties-file-path>'
----

Alternatively, the contents of the I/O configuration can be passed as a string:

[,bash]
----
rpk redpanda start --io-properties '<io-properties-string>'
----

If a certain cloud vendor, machine type, or storage type isn't
found, or if the metadata isn't available and no hint is given, then `rpk` prints a
warning and continues to use the default values.
