= Remote Read Replicas
:description: Create read-only topics (Remote Read Replica topics) that mirror topics on a different cluster.
:contextLinks: [{"name"=>"Linux", "to"=>"manage/remote-read-replicas"}, {"name"=>"Kubernetes", "to"=>"manage/kubernetes/remote-read-replicas"}]
:deployment: Linux
:linkRoot: ../../

import ReduceLag from './shared/remote-read-replicas/_reduce-lag.mdx';
import AboutRemoteReadReplicas from './shared/remote-read-replicas/_intro.mdx';

import ContextLink from '@site/src/components/ContextButton.js'

<ContextLink frontmatter=\{frontMatter}
/>

<AboutRemoteReadReplicas frontmatter=\{frontMatter}/>

You can create xref::remote-read-replicas.adoc[Remote Read Replica] topics in a Redpanda cluster that directly accesses data stored in cloud object storage. Because these read-only topics access data directly from cloud object storage instead of the topics' origin cluster, there's no impact to the performance of the cluster. Furthermore, topic data can be consumed within a region of your choice, regardless of the region where it was produced.

:::tip
To create a Remote Read Replica topic in another region, consider using a https://aws.amazon.com/s3/features/multi-region-access-points/[multi-region bucket] to simplify deployment and optimize performance.
:::

== Create a topic with archival storage or Tiered Storage

When cloud storage is enabled on a topic, Redpanda copies closed log segments to the configured object store. Log segments are closed when the value of xref:reference:tunable-properties.adoc#log_segment_size[`log_segment_size`] has been reached, so a topic's object store lags behind the local copy. To reduce this lag in the data availability for the Remote Read Replica:

* You can lower the value of `segment.bytes`. This lets Redpanda archive smaller log segments more frequently, at the cost of increasing I/O and file count.
* Self-hosted implementations can set an idle timeout with `cloud_storage_segment_max_upload_interval_sec` to force Redpanda to periodically archive the contents of open log segments to object storage. This is useful if a topic's write rate is low and log segments are kept open for long periods of time. The appropriate interval may depend on your total partition count: a system with less partitions can handle a higher number of segments per partition.

== Create a topic with remote storage

Before you can create a Remote Read Replica, you must create a topic on the origin cluster, and set up a bucket for the topic's cloud object storage.

. Create a bucket to store the original data.
. Create the original topic by running `rpk topic create <topic_name>`, and specifying the number of partitions and the number of replicas.
. Enable cloud storage on the origin cluster by running `rpk cluster config edit`, and then specify the following cluster configuration properties:
+
|===
| Property | Description

| `cloud_storage_enabled`
| Must be set to `true` to enable cloud storage.

| `cloud_storage_bucket`
| AWS or GCS bucket name where the original data is stored. +
Required for AWS and GCS.

| `cloud_storage_access_key`
| AWS or GCS access key. +
Required for AWS and GCS authentication with access keys.

| `cloud_storage_secret_key`
| AWS or GCS secret key. +
Required for AWS and GCS authentication with access keys.

| `cloud_storage_region`
| Cloud storage region. +
Required for AWS and GCS.

| `cloud_storage_api_endpoint`
| AWS or GCS API endpoint. +
- For AWS, this can be left blank. It's generated automatically using the region and bucket. +
- For GCS, use `storage.googleapis.com`.

| `cloud_storage_enable_remote_write`
| When using archival storage or Tiered Storage on the origin cluster, set to `true` to enable data to be uploaded from Redpanda and written to cloud storage for all topics. +
To only enable data upload for a specific topic, set `cloud_storage_enable_remote_write: false` and run `rpk topic create <topic_name> -c redpanda.remote.write=true` when you create the topic.

| `cloud_storage_enable_remote_read`
| When using Tiered Storage on the origin cluster, set to `true` to enable consumers to read from all topics in cloud storage. +
To enable consumers to only read from one topic, set `cloud_storage_enable_remote_read: false` and run `rpk topic create <topic_name> -c redpanda.remote.read=true` when you create the topic.
|===

== Set up a Remote Read Replica

To set up a Remote Read Replica topic on a separate remote cluster:

. Create a remote cluster for the Remote Read Replica topic.
 ** If that's a multi-region bucket, you can create the read replica cluster in any region that has that bucket.
 ** If that's a single-region bucket, the remote cluster must be in the same region as the bucket.
. Run `rpk cluster config edit`, and then specify the following cluster configuration properties:
+
|===
| Property | Description

| `cloud_storage_enabled`
| Must be set to `true` to enable cloud storage.

| `cloud_storage_bucket: “none”`
| No AWS or GCS bucket is needed for the remote cluster.

| `cloud_storage_access_key`
| AWS or GCS access key. +
Required for AWS and GCS authentication with access keys.

| `cloud_storage_secret_key`
| AWS or GCS secret key. +
Required for AWS and GCS authentication with access keys.

| `cloud_storage_region`
| Cloud storage region of the remote cluster. +
Required for AWS and GCS.

| `cloud_storage_api_endpoint`
| AWS or GCS API endpoint. +
- For AWS, this can be left blank. It's generated automatically using the region and bucket. +
- For GCS, use `storage.googleapis.com`.
|===

. Create the Remote Read Replica topic by running `rpk topic create <topic_name> -c redpanda.remote.readreplica=<bucket_name>`.
+
For `<topic_name>`, use the same name as the original topic. For `<bucket_name>`, use the bucket specified in the `cloud_storage_bucket` property for the origin cluster.
+
:::note
Do not use `redpanda.remote.read` or `redpanda.remote.write` with `redpanda.remote.readreplica`. Redpanda ignores the values for remote read and remote write properties on read replica topics.
:::

== Reduce lag in data availability

<ReduceLag frontmatter=\{frontMatter}/>

== Suggested reading

* https://redpanda.com/blog/remote-read-replicas-for-distributing-work[Remote Read Replicas: Read-only topics in Tiered Storage]
