= Schema Registry
:description: Redpanda's Schema Registry provides the interface to store and manage event schemas.
:page-aliases: data-management:schema-registry.adoc

Redpanda's Schema Registry provides the interface to store and manage event schemas. Producers and consumers register and retrieve the schemas they use to ensure data verification. Schemas are versioned, and the registry supports configurable compatibility modes between schema versions. When a producer or a consumer makes a request to register a schema change, the registry checks for schema compatibility and returns an error for an incompatible change.

== Schema

A schema is an external mechanism to describe the structure of data and its encoding. Producer clients and consumer clients use a schema as an agreed-upon format for sending and receiving messages. Using schemas provides multiple benefits:

* Enables a loosely coupled, data-centric architecture that minimizes dependencies in code, between teams, and between producers and consumers.
* Provides human-readable documentation for an API.
* Verifies that data conforms to an API.
* Supports the generation of serializers for data.
* Manages the compatibility of evolving APIs, allowing new versions of services to be rolled out independently.

=== Serialization format

A data serialization format defines how data is converted into bytes that are transmitted and stored. Serialization, by producers, converts an event into bytes. Redpanda then stores these bytes in topics. Deserialization, by consumers, converts the bytes of arrays back into the desired data format.

Redpanda's Schema Registry supports Avro and Protobuf serialization formats.

== Redpanda design overview

Redpanda built the Schema Registry directly into the Redpanda binary. It runs out-of-the-box with Redpanda's default configuration, and it requires no new binaries to install and no new services to deploy or maintain.

Every broker allows mutating REST calls, so there is no need to configure leadership or failover strategies. Schemas are stored in a compacted topic, and the registry uses optimistic concurrency control at the topic level to detect and avoid collisions.

The Schema Registry publishes record metadata to an internal topic, `_schemas`, as its backend store. By default, `_schemas` is protected from deletion and configuration changes by Kafka clients (see the xref:reference:cluster-properties.adoc#kafka_nodelete_topics[kafka_nodelete_topics] cluster property).

== Related topics

* xref:api:ROOT:pandaproxy-schema-registry.adoc[Schema Registry API]
* xref:reference:node-configuration-sample.adoc[] (search for `schema_registry`)
* xref:manage:monitoring.adoc#service-level-queries[Monitor Schema Registry service-level metrics]
* xref:deploy:deployment-option/self-hosted/manual/node-property-configuration.adoc[Configure broker properties for Schema Registry]
* xref:manage:console/protobuf.adoc#schema-registry[Configure Schema Registry for Protobuf deserialization]
* xref:reference:console/record-deserialization.adoc[Redpanda Console record deserialization]
* xref:deploy:deployment-option/self-hosted/manual/production/production-deployment.adoc#prepare-infrastructure[Provision ports for deployment]
