= Topics as Iceberg Tables
:description: Learn how to integrate Redpanda topics with Iceberg.
:page-context-links: [{"name": "Linux", "to": "manage:topic-iceberg-integration.adoc" } ]
:page-categories: Management, High Availability, Data Replication, Integration


The Redpanda integration with Apache Iceberg allows your topic data to be stored in the cloud in Iceberg's table format. This opens up immediate access to your streaming data for analytical systems such as data warehouses like RedShift, Snowflake, and Clickhouse, and big data processing platforms such as Apache Spark and Flink, without setting up and maintaining additional ETL pipelines. 

== Prerequisites

include::shared:partial$enterprise-license.adoc[]

. To check if you already have a license key applied to your cluster:
+
[,bash]
----
rpk cluster license info
----

. Install `rpk`.

== Limitations

* You can only enable the Iceberg integration when creating a new Redpanda topic. 
* It is not possible to append or backfill data from Redpanda topics to an existing Iceberg table.
* JSON schemas are not currently supported.
* You can only use one schema per topic. Schema versioning as well as upcasting (where a message is cast into its more generic data type) are not supported. 

== Architecture 

Apache Iceberg is an open source format specification for defining structured tables in a glossterm:data lake[]. The table format enables you to easily and quickly manage, query, and process huge amounts of structured and unstructured data, like you would manage and run SQL queries against relational data in a database or data warehouse. The open format allows many different languages, tools, and applications to process the same data in a consistent way, so you can avoid vendor lock-in. This data management system is also referred to as a _data lakehouse_.

In the Iceberg specification, tables comprise the following:

* Data layer
** Data files: Store the actual data. The Redpanda integration currently supports the Parquet file format. Parquet files are column-based and suitable for analytical workloads at scale, and come with compression capabilities that optimize files for object storage. 
* Metadata layer
+
--
** Manifest files: Track data files and contain metadata about those files, such as record count, partition membership, and file paths.
** Manifest list: Tracks all the manifest files belonging to a table, including file paths and upper and lower bounds for partition fields. 
** Metadata file: Stores metadata about the table, including its schema, partition information, and snapshots. Whenever a change is made to the table, a new metadata file is created and becomes the latest version of the metadata in the catalog.
--
+
In the Redpanda Iceberg integration, the manifest files are in JSON format.
* Catalog: Contains the current metadata pointer for the table. Clients reading and writing data to the table see the same version of the current state of the table. Redpanda creates the catalog in JSON format.

When you enable the Iceberg integration for a Redpanda topic, Redpanda brokers store streaming data in the Iceberg-compatible format in Parquet files in object storage, in addition to writing Kafka messages stored in segment files on disk. Storing the streaming data in Iceberg tables in the cloud allows you to derive real-time insights through business intelligence and machine learning tools that work with Iceberg. 


== Enable Iceberg integration

To use the Iceberg integration for a topic, you must set Redpanda cluster configuration `enable_datalake` to true, and also explicitly set the topic configuration to `true`.

. Enable the Iceberg integration for the cluster by setting the cluster configuration `enable_datalake` to `true`. 
+
[,bash]
----
rpk cluster config set enable_datalake true 
----
+
[,bash,.no-copy]
----
Successfully updated configuration. New configuration version is 2.
----

. Create a new topic.
+
[,bash,]
----
rpk topic create <new-topic> --partitions 1 --replicas 1
----
+
[,bash,.no-copy]
----
TOPIC       STATUS
new-topic   OK
----

. Enable the integration for the topic. 
+
[,bash]
----
rpk topic alter-config <new-topic> --set iceberg_topic=true 
----
+
[,bash,.no-copy]
----
TOPIC       STATUS
new-topic   OK
----

. Optional: Register a schema for the topic. Redpanda uses the schema to derive the Iceberg table format and write data files to object storage in this format. Protobuf schemas are supported.
+
If you don't configure a schema for the topic, Redpanda by default uses a simple schema consisting of the record’s key, value, and the original message timestamp. If you don't have a need for a strict schema and can use the data in a more semi-structured format, consider the schemaless approach.
+
[,bash]
----
rpk registry schema create <new-topic> --schema </path-to-schema> --type <format>
----
+
[,bash,.no-copy]
----
SUBJECT     VERSION   ID   TYPE
new-topic   1         1    PROTOBUF
----

As you produce messages to the topic, the data also becomes available to consume from object storage by Iceberg-compliant clients.

== Consume data in Iceberg tables

You can use the same analytical tools to access and manage data just like you would in a relational database. 





