= Topics as Iceberg Tables
:description: Learn how to integrate Redpanda topics with Iceberg.
:page-context-links: [{"name": "Linux", "to": "manage:topic-recovery.adoc" } ]
:page-categories: Management, High Availability


The Redpanda integration with Apache Iceberg allows your topic data to be stored in the cloud in Iceberg's table format. This opens up immediate access to your streaming data for analytical systems such as data warehouses like RedShift, Snowflake, and Clickhouse, and big data processing platforms such as Apache Spark and Flink, without having to set up and configure ETL pipelines. 

// Apache Iceberg is an open source format for defining structured tables in the Data Lake and enables multiple applications to work together on the same data in a consistent fashion and more effectively track dataset states with transactional consistency as changes are made.

// Reduced cost of data storage, no ETL required, immediate access to late arriving data. 


== Prerequisites

include::shared:partial$enterprise-license.adoc[]

. To check if you already have a license key applied to your cluster:
+
[,bash]
----
rpk cluster license info
----

. Install `rpk`.

== Limitations

* You can only enable the Iceberg integration when creating a new Redpanda topic. 
* You can only use one schema per topic. Schema versioning as well as upcasting (where a message is cast into its more generic data type) are not supported. 

== Architecture 


== Enable Iceberg integration

// Enable data lake support
. Enable the Iceberg integration for the cluster by setting the cluster configuration `enable_datalake` to `true`. 
+
[,bash]
----
rpk cluster config set enable_datalake true 
----
+
[,bash,.no-copy]
----
Successfully updated configuration. New configuration version is 2.
----

. Create a new topic.
+
[,bash,]
----
rpk topic create <new-topic> --partitions 1 --replicas 1
----
+
[,bash,.no-copy]
----
TOPIC       STATUS
new-topic   OK
----

. Enable the integration for the topic.
+
[,bash]
----
rpk topic alter-config <new-topic> --set iceberg_topic=true 
----
+
[,bash,.no-copy]
----
TOPIC       STATUS
new-topic   OK
----

. Optional: Register a schema for the topic. Redpanda uses the schema to derive the Iceberg table format and write data files to object storage in this format.
+
If you don't configure a schema for the topic, Redpanda by default uses a simple schema consisting of the record’s key, value, and the original message timestamp. If you don't have a need for a strict schema and can use the data in a more semi structured format, consider the schemaless approach.
+
[,bash]
----
rpk registry schema create <new-topic> --schema </path-to-schema> --type <format>
----
+
[,bash,.no-copy]
----
SUBJECT     VERSION   ID   TYPE
new-topic   1         1    PROTOBUF
----
+


