= Manage Redpanda using the Admin API
:page-categories: Management, High Availability, Upgrades
:description: Manage components of a Redpanda cluster, such as individual brokers and partition leadership. The Redpanda Admin API also allows you to perform operations that are specific to Redpanda Self-Managed and cannot be done using the standard Kafka API.

The Redpanda Admin API allows you to manage your cluster and perform operations specific to Redpanda Self-Managed that are not available through the standard Kafka API. You can call the Admin API using any HTTP client. 

Most Admin API operations are also available using xref:get-started:intro-to-rpk.adoc[`rpk`], a CLI tool which interacts with the Admin API under the hood. 

Redpanda version 25.3 introduces a version 2 of the Admin API, powered by https://connectrpc.com/docs/introduction[ConnectRPC]. New Redpanda features and operations introduced starting in version 25.3 are available with Admin API v2 only, and are not backported to Admin API v1. Supported Admin API v1 operations remain available and you can continue to use them per usual (including with rpk v25.3 and later).

== Prerequisites

* A running Redpanda Self-Managed cluster.
** For Admin API v1, any supported version of Redpanda. For Admin API v2, Redpanda version 25.3 or later.
* Superuser privileges, if xref:manage:security/authentication.adoc#enable-authentication[authentication] is enabled on your cluster for the Admin API. For more information, see xref:manage:security/authentication.adoc#create-superusers[Configure Authentication]. (Some endpoints are read-only and do not require superuser access.)
* A tool to make HTTP requests, such as `curl`, or client libraries for your programming language of choice. 
** For Admin API v2, you can also make requests using a Connect client. You can install the Connect plugin for your preferred language and use the Protobuf compiler to generate an SDK. Admin API v2 is also available as a Buf module and can be accessed through the https://buf.build/redpandadata/core/docs/dev:redpanda.core.admin.v2[Buf Schema Registry]. The https://buf.build/docs/cli/[Buf CLI] provides an easy way to generate client SDKs.

== Choose an Admin API version

In Redpanda version 25.3, Admin API v2 endpoints are entirely exclusive to v2, and there is virtually no overlap in functionality between v2 and v1. You can use both versions of the Admin API on the same cluster, so choosing which version depends on whether you use the following v2-only features:

// TODO: Add doc links
* Shadowing
* Client monitoring

See the link:/api/doc/admin/v2[Admin API v2 reference] for the current list of available v2 endpoints. Otherwise, see the link:/api/doc/admin/[Admin API v1 reference] for a full list of supported v1 endpoints.

== Use the Admin API

Both Admin API v1 and v2 are accessible on the same port (default: 9644), but they use different endpoints or URL paths.

If authentication is enabled on your cluster, you must provide credentials with each request, either using HTTP Basic authentication or by including an `Authorization` header with a bearer token. For example:

[,bash]
----
curl -u <user>:<password> -X GET "http://localhost:9644/v1/cluster_config"
----

=== Use Admin API v1

The Admin API v1 uses RESTful HTTP endpoints. The base URL for all requests is:

```
http://<broker-address>:<admin-api-port>/v1/
```

For a full list of available endpoints, see the link:/api/doc/admin/[Admin API v1 Reference].

==== Example request

To use the Admin API v1 to xref:manage:cluster-maintenance/decommission-brokers.adoc[decommission a broker], send a PUT request to the link:/api/doc/admin/operation/operation-decommission[`/v1/brokers/\{broker_id}/decommission`] endpoint:

[,bash]
----
curl \
 -u <user>:<password> \
 --request PUT 'http://<broker-address>:<port>/v1/brokers/<broker-id>/decommission'
----

NOTE: The command xref:reference:rpk/rpk-redpanda/rpk-redpanda-admin-brokers-decommission.adoc[`rpk redpanda admin brokers decommission`] also performs this operation on Linux deployments.

=== Use Admin API v2

The Admin API v2 is built on ConnectRPC, so you can send `curl` requests with a JSON payload, or use a generated Connect client to call the same methods directly from your application code. The v2 paths are the fully qualified names of the services. All v2 endpoints accept POST requests only.

For a full list of available endpoints, see the link:/api/doc/admin/v2[Admin API v2 Reference].

==== Limitations

Admin API v2 does not currently include Admin API v1 functionality. Use v1 for operations not available in v2. Feature parity is planned for future releases. In the meantime, v1 remains fully supported.

==== Example request

To fail over a specific shadow topic from an existing shadow link, send a POST request to the link:/api/doc/admin/v2/operation/operation-redpanda-core-admin-v2-shadowlinkservice-failover[`redpanda.core.admin.v2.ShadowLinkService/FailOver`] endpoint:

[,bash]
----
curl \
 -u <user>:<password> \
 --request POST 'http://localhost:9644/redpanda.core.admin.v2.ShadowLinkService/FailOver' \
 --header "Content-Type: application/json" \
 --data '{
  "name": "<shadow-link-name>",
  "shadowTopicName": "<shadow-topic-name>"
}'
----

- Request headers `Connect-Protocol-Version` and `Connect-Timeout-Ms` are optional.
- v2 endpoints also accept binary-encoded Protobuf request bodies. Use the `Content-Type: application/proto` header.

// TODO: Add link to rpk reference
NOTE: The command `rpk shadow failover` also performs this operation.
