== Formatting

Parsing is based on percent escapes and modifiers. If using sizes to specify
something, the size must come before what it is specifying. Delimiters match on
an exact text basis. This command will quit with an error if any input fails to
match your specified format.

Slashes can be used for common escapes:

[cols=",",]
|===
|Escape |Description

|`\t` |Tabs
|`\n` |Newlines
|`\r` |Carriage returns
|`\\` |Slashes
|`\xNN` |Hex encoded characters
|===

Percent encoding reads into specific values of a record:

[cols=",",]
|===
|Percent encoding |Description

|`%t` |Topic
|`%T` |Topic length
|`%k` |Key
|`%K` |Key length
|`%v` |Value
|`%V` |Value length
|`%h` |Begin the header specification
|`%H` |Number of headers
|`%p` |Partition (if using the `--partition` flag)
|`%%` |Percent sign
|`%{` |Left brace
|`%}` |Right brace
|===

=== Modifiers

Text and numbers can be read in multiple formats, and the default format can be
changed within brace modifiers. `%v` reads a value, while pass:q[`%v{hex}`]
reads a value and then hex decodes it before producing. `%T` reads the length
of a topic from the input, while pass:q[`%T{3}`] reads exactly three bytes for
a topic from the input.

All modifiers go within braces following a percent-escape.

=== Numbers

Reading number values can have the following modifiers:

[cols=",",]
|===
|Number |Description

|`ascii` |Parse numeric digits until a non-numeric (default)
|`hex64` |Sixteen hex characters
|`hex32` |Eight hex characters
|`hex16` |Four hex characters
|`hex8` |Two hex characters
|`hex4` |One hex character
|`big64` |Eight byte big endian number
|`big32` |Four byte big endian number
|`big16` |Two byte big endian number
|`big8` |Alias for byte
|`little64` |Eight byte little endian number
|`little32` |Four byte little endian number
|`little16` |Two byte little endian number
|`little8` |Alias for byte
|`byte` |One byte number
|`<digits>` |Directly specify the length as this many digits
|`bool` |Read "true" as 1, "false" as 0
|===

When reading number sizes, the size corresponds to the size of the encoded
values, not the decoded values. pass:q[`%T{6}%t{hex}`] reads six hex bytes and
decodes them into three.

=== Text

Reading text values can have the following modifiers:

[cols=",",]
|===
|Modifier |Description

|`hex` |Read text, then hex decode it
|`base64` |Read text, then std-encoding base64 decode it
|`re` |Read text matching a regular expression
|`json` |Read text as JSON, then compact it
|===

=== Headers

Headers are parsed with an internal key/value specifier format. For example,
the following reads three headers that begin and end with a space and are
separated by an equals sign:

[,bash]
----
%H{3}%h{ %k=%v }
----
