= What's New in the Helm Charts
:description: Summary of new features and updates in the Helm charts for Redpanda and Redpanda Console.

This topic includes new content and significant changes in the Redpanda and Redpanda Console Helm charts. For a complete list of all updates, see:

- https://github.com/redpanda-data/redpanda-operator/blob/{latest-operator-version}/charts/redpanda/CHANGELOG.md[Changelog for the Redpanda chart^].
- https://github.com/redpanda-data/redpanda-operator/blob/{latest-operator-version}/charts/console/CHANGELOG.md[Changelog for the Redpanda Console chart^].

See also:

* xref:get-started:whats-new.adoc[]
* xref:upgrade:k-compatibility.adoc[]
* xref:upgrade:k-rolling-upgrade.adoc[]

== Redpanda chart v25.1.1 (GA)

link:https://github.com/redpanda-data/redpanda-operator/blob/release/v25.1.x/charts/redpanda/CHANGELOG.md[Changelog^].

=== Redpanda Console v3

This version deploys Redpanda Console v3, which includes unified authentication and authorization between the Redpanda Console and Redpanda, including user impersonation. For more information, see xref:console:config/security/authentication.adoc[].

This version does not support Redpanda Console v2.

Before upgrading, migrate your Redpanda Console v2 configuration to the new v3 format. For more information, see xref:migrate:console-v3.adoc[].

=== Schema validation

The Redpanda Helm chart now includes stricter schema validation to ensure configurations conform to expected standards. With schema validation enabled, you must ensure your overrides include valid fields.

=== Removed fields

The following deprecated fields have been removed from the Helm values. Before upgrading, review your configurations and replace the removed fields with their replacements. For the list of removed fields, see the link:https://github.com/redpanda-data/redpanda-operator/blob/release/v25.1.x/charts/redpanda/CHANGELOG.md[changelog^].

=== Updated versioning scheme

An updated versioning scheme now better supports and tracks compatible Redpanda versions, ensuring smoother upgrades and improved compatibility management.

See also: xref:upgrade:k-compatibility.adoc[].

=== Kafka Connect integration removed from Helm chart

Starting with version 25.1.x of the Redpanda Helm chart, Kafka Connect is no longer bundled as a subchart.

If you require Kafka Connect, you must install the `connectors` Helm chart separately after deploying Redpanda.

For instructions, see xref:deploy:kafka-connect/k-deploy-kafka-connect.adoc[].

To check if you're currently using Redpanda's managed Kafka Connect, run:

[,bash]
----
kubectl get pod -l app.kubernetes.io/name=connectors --namespace <namespace>
----

NOTE: For stream processing on Kubernetes, consider using xref:redpanda-connect:get-started:quickstarts/helm-chart.adoc[Redpanda Connect]. It offers a simplified, scalable alternative to Kafka Connect for building data pipelines with a supported Kubernetes integration.

=== Reference Kubernetes Secrets and ConfigMaps for Redpanda cluster configuration

You can now set any Redpanda cluster configuration property using the new `extraClusterConfiguration` field. This allows you to reference values from Kubernetes Secrets or ConfigMaps. For example, use this field to inject sensitive credentials or reuse shared configurations across features like Tiered Storage, Iceberg, and disaster recovery.

This enhancement improves:

- Security: Avoid hardcoding secrets in Helm values or manifests.

- Reusability: Centralize common values used by multiple features.

- Maintainability: Better integrate with GitOps workflows and Kubernetes-native resource management.

See xref:manage:kubernetes/k-configure-helm-chart.adoc#extra-cluster-config[Set Redpanda cluster properties from Kubernetes Secrets or ConfigMaps].

== Redpanda chart v5.10.x

=== Ability to change StatefulSet replicas without restarting brokers

Starting in v5.10.1, the Redpanda Helm chart allows you to increase or decrease the number of replicas in a StatefulSet without restarting existing brokers. This ability is useful for scaling your cluster up or down without downtime.

== Redpanda chart v5.9.x

=== Sidecar for broker decommissioning and PVC cleanup

Version v5.9.21 of the Redpanda Helm chart introduces two new sidecar-based controllers to manage broker decommissioning and persistent volume cleanup:

- xref:manage:kubernetes/k-decommission-brokers.adoc#Automated[BrokerDecommissioner]: Detects **non-graceful broker failures**, such as node crashes, and **triggers automated decommissioning**.
- xref:manage:kubernetes/k-nodewatcher.adoc[PVCUnbinder]: Ensures **persistent volume claims (PVCs) are properly unbound and cleaned up** after broker removal.

The NodeWatcher and Decommission controllers are deprecated and replaced by a single sidecar. To enable the equivalent of the controllers, set the `enabled` flag to `true` in your Redpanda custom resource. For example:

[,yaml]
----
statefulset:
  sideCars:
    brokerDecommissioner:
      enabled: true
      decommissionAfter: 60s
    pvcUnbinder:
      enabled: true
      unbindAfter: 60s
rbac:
  enabled: true
----

If you previously relied on the NodeWatcher or Decommission controllers, switch to the new sidecars for improved stability and control.
