= What's New in the Helm Charts
:description: Summary of new features and updates in the Helm charts for Redpanda and Redpanda Console.

This topic includes new content and significant changes in the Redpanda and Redpanda Console Helm charts. For a complete list of all updates, see:

- https://github.com/redpanda-data/redpanda-operator/blob/{latest-operator-version}/charts/redpanda/CHANGELOG.md[Changelog for the Redpanda chart^].
- https://github.com/redpanda-data/redpanda-operator/blob/{latest-operator-version}/charts/console/CHANGELOG.md[Changelog for the Redpanda Console chart^].

See also:

* xref:get-started:whats-new.adoc[]
* xref:upgrade:k-compatibility.adoc[]
* xref:upgrade:k-rolling-upgrade.adoc[]

== Console chart v26.1.x

link:https://github.com/redpanda-data/redpanda-operator/blob/release/v26.1.x/charts/console/CHANGELOG.md[Changelog^].

=== Prometheus ServiceMonitor

The Console Helm chart now supports deploying a Prometheus `ServiceMonitor` using `monitoring.enabled`, `monitoring.scrapeInterval`, and `monitoring.labels`. See xref:deploy:console/kubernetes/deploy.adoc#prometheus-servicemonitor[Prometheus ServiceMonitor].

== Redpanda chart v26.1.x

link:https://github.com/redpanda-data/redpanda-operator/blob/release/v26.1.x/charts/redpanda/CHANGELOG.md[Changelog^].

=== Config-watcher sidecar resource configuration

You can now configure explicit CPU and memory resource requests and limits for the config-watcher sidecar using `statefulset.sideCars.configWatcher.resources`. This is required in namespaces that enforce LimitRange or ResourceQuota policies. See xref:manage:kubernetes/k-manage-resources.adoc#config-watcher[Configure config-watcher sidecar resources].