= What's New in the Helm Charts
:description: Summary of new features and updates in the Helm charts for Redpanda and Redpanda Console.

This topic includes new content and significant changes in the Redpanda and Redpanda Console Helm charts. For a complete list of all updates, see:

- https://github.com/redpanda-data/redpanda-operator/blob/main/charts/redpanda/CHANGELOG.md[Changelog for the Redpanda chart^].
- https://github.com/redpanda-data/redpanda-operator/blob/main/charts/console/CHANGELOG.md[Changelog for the Redpanda Console chart^].

See also:

* xref:get-started:whats-new.adoc[]
* xref:upgrade:k-compatibility.adoc[]
* xref:upgrade:k-rolling-upgrade.adoc[]

== Redpanda chart v5.9.21

=== Sidecar for broker decommissioning and PVC cleanup

This version of the Redpanda Helm chart introduces two new sidecar-based controllers to manage broker decommissioning and persistent volume cleanup:

- xref:manage:kubernetes/k-decommission-brokers.adoc#Automated[BrokerDecommissioner]: Detects **non-graceful broker failures**, such as node crashes, and **triggers automated decommissioning**.
- xref:manage:kubernetes/k-nodewatcher.adoc[PVCUnbinder]: Ensures **persistent volume claims (PVCs) are properly unbound and cleaned up** after broker removal.

The NodeWatcher and Decommission controllers are deprecated and replaced by a single sidecar. To enable the equivalent of the controllers, set the `enabled` flag to `true` in your Redpanda custom resource. For example:

[,yaml]
----
statefulset:
  sideCars:
    brokerDecommissioner:
      enabled: true
      decommissionAfter: 60s
    pvcUnbinder:
      enabled: true
      unbindAfter: 60s
rbac:
  enabled: true
----

If you previously relied on the NodeWatcher or Decommission controllers, switch to the new sidecars for improved stability and control.