= What's New in the Redpanda Operator
:description: Summary of new features and updates in the Redpanda Operator.

This topic includes new content and significant changes in the Redpanda Operator. For a complete list of all updates, see the https://github.com/redpanda-data/redpanda-operator/blob/{latest-operator-version}/operator/CHANGELOG.md[Redpanda Operator changelog^].

See also:

* xref:get-started:whats-new.adoc[]
* xref:upgrade:k-compatibility.adoc[]
* xref:upgrade:k-rolling-upgrade.adoc[]


== Redpanda Operator v26.1.x

link:https://github.com/redpanda-data/redpanda-operator/blob/release/v26.1.x/operator/CHANGELOG.md[Changelog^]

=== Console custom resource

The Redpanda Operator now supports a `Console` custom resource (CR) for deploying and managing Redpanda Console declaratively. The operator handles the full lifecycle, including the underlying Deployment, Service, and ConfigMap resources.

Use `clusterRef` to connect Console to an operator-managed Redpanda cluster, or `staticConfiguration` for external clusters. See xref:deploy:console/kubernetes/deploy.adoc[Deploy Redpanda Console on Kubernetes].

=== Prometheus ServiceMonitor for Console

The Console custom resource supports a `monitoring` configuration that deploys a Prometheus `ServiceMonitor` to automatically discover and scrape Console metrics. See xref:deploy:console/kubernetes/deploy.adoc#prometheus-servicemonitor[Prometheus ServiceMonitor].