= What's New in Redpanda
:description: Summary of new features and updates in this Redpanda release.
:page-aliases: get-started:whats-new-233.adoc, get-started:whats-new-241.adoc, get-started:whats-new.adoc

This topic includes new content added in version {page-component-version}. For a complete list of all product updates, see the https://github.com/redpanda-data/redpanda/releases/[Redpanda release notes^]. See also:

* xref:redpanda-cloud:get-started:whats-new-cloud.adoc[]
* xref:redpanda-cloud:get-started:cloud-overview.adoc#redpanda-cloud-vs-self-managed-feature-compatibility[Redpanda Cloud vs Self-Managed feature compatibility]

== Client connection monitoring

You can view details about Kafka client connections using the Admin API v2 ListKafkaConnections endpoint. This allows you to view detailed information about about active client connections on a per-broker basis, and identify and troubleshoot problematic clients. For more information, see xref:manage:monitoring.adoc#identify-high-throughput-clients[Monitor Redpanda].