= Deprecated Cluster and Console Custom Resources
:description: Starting from Redpanda version 23.2, the Cluster and Console custom resources are deprecated and replaced by the Redpanda custom resource.

Starting from Redpanda version 23.2, the Cluster and Console custom resources are deprecated and replaced by the xref:reference:crd.adoc#redpandaclusterspec[Redpanda custom resource].

When you define a Redpanda cluster using this Redpanda resource, the updated Redpanda Operator takes that configuration and passes it to https://fluxcd.io/flux/concepts/[Flux^]. Flux, in turn, interacts with Helm, creating the necessary HelmRepository and HelmRelease resources to deploy and manage the Redpanda Helm chart.

Here is an example of a Redpanda custom resource:

```yaml
apiVersion: cluster.redpanda.com/v1alpha1
kind: Redpanda
metadata:
  name: <cluster-name>
spec:
  chartRef:
    helmRepositoryName:
  clusterSpec:
```

- `metadata.name`: Name to assign the Redpanda cluster. This name is also assigned to the Helm release.
- xref:reference:crd.adoc#chartref[`spec.chartRef`]: Information about the Helm chart that will be used to deploy Redpanda.
- xref:reference:crd.adoc#helmrepositoryname[`spec.chartRef.helmRepositoryName`]: Name of the Helm repository where the Redpanda chart is located.
- xref:reference:crd.adoc#redpandaclusterspec[`spec.clusterSpec`]: This is where you can override default values in the Redpanda Helm chart.

== What's changed

|===
|Previous version|Updated version

|The Cluster custom resource was used to configure and deploy Redpanda clusters, while the Console custom resource was used to configure and deploy Redpanda Console.
| The Redpanda custom resource is used to deploy both Redpanda and Redpanda Console.

|The Redpanda Operator could be deployed in a different namespace to the Cluster or Console resources.
|The updated Redpanda Operator must be deployed in the same namespace as the Redpanda custom resource. If you deploy multiple Redpanda resources in different namespaces, you must also deploy an instance of Redpanda Operator in those namespaces.
|===

== Action required

To ensure compatibility with future versions of Redpanda and to benefit from new features, enhancements, and security updates,
you should migrate from the deprecated Cluster and Console custom resources to the latest Redpanda custom resource.
The migration process involves:

. Ensuring you're running at least version 23.2 of the Redpanda Operator.
. Migrating your existing Cluster or Console resources to the Redpanda custom resource.

For detailed steps, see xref:upgrade:migrate/kubernetes/operator.adoc[Migrate from Cluster and Console Custom Resources].

include::shared:partial$suggested-reading.adoc[]

* xref:deploy:deployment-option/self-hosted/kubernetes/kubernetes-production-deployment.adoc[Learn more about the new Redpanda Operator].
* https://github.com/redpanda-data/redpanda/releases/tag/v23.2.1[Redpanda release notes^].
