= Deprecated Cluster and Console Custom Resources
:description: Starting from Redpanda version 23.2, the Cluster and Console custom resources are deprecated and replaced by the new Redpanda custom resource.

Starting from Redpanda version 23.2, the Cluster and Console custom resources are deprecated and replaced by the new Redpanda custom resource.

The Cluster custom resource was used to configure and deploy Redpanda clusters, while the Console custom resource was used to configure and deploy Redpanda Console.

== What's changed

The Redpanda custom resource in this version is used to deploy both Redpanda and Redpanda Console. The latest Redpanda Operator passes configurations defined in Redpanda custom resources to Helm, which then deploys the Redpanda cluster using the Redpanda Helm chart.

The deprecated Redpanda Operator could be deployed in a different namespace to the Cluster or Console resources. However, the latest Redpanda Operator must be deployed in the same namespace as the Redpanda resource.

== Action required

To ensure compatibility with future versions of Redpanda and to benefit from new features, enhancements, and security updates, you should migrate from the deprecated Cluster and Console custom resources to the latest Redpanda custom resource. The migration process involves deploying at least version 23.2 of the Redpanda Operator.

CAUTION: Redpanda Operator is in beta. Do not migrate existing production clusters to the Redpanda Operator.

== Suggested reading

* xref:deploy:deployment-option/self-hosted/kubernetes/kubernetes-production-deployment.adoc[Learn more about the new Redpanda Operator].
* https://github.com/redpanda-data/redpanda/releases/tag/v23.2.1[Redpanda release notes^].
