= rpk cluster storage recovery
:description: 
:rpk_version: v23.1.6 (rev cc47e1ad1)

Interact with the topic recovery process.
This command is used to restore topics from the archival bucket, which can be
useful for disaster recovery or if a topic was accidentally deleted.

To begin the recovery process, use the `recovery start` command. Note that this
process can take a while to complete, so the command will exit after starting
it. If you want the command to wait for the process to finish, use the `--wait`
or `-w` flag.

You can check the status of the recovery process with the `recovery status`
command after it has been started.

== Usage

[,bash]
----
rpk cluster storage recovery [command]
----

== Flags

////
[cols=",,",]
|===
|*Value* |*Type* |*Description*

|-h, --help |- |Help for recovery.

|--brokers |strings |Comma-separated list of broker ip:port pairs (e.g.
--brokers '192.168.78.34:9092,192.168.78.35:9092,192.179.23.54:9092').
Alternatively, you may set the REDPANDA_BROKERS environment variable
with the comma-separated list of broker addresses.

|--config |string |Redpanda config file, if not set the file will be
searched for in the default locations.

|--password |string |SASL password to be used for authentication.

|--sasl-mechanism |string |The authentication mechanism to use.
Supported values: SCRAM-SHA-256, SCRAM-SHA-512.

|--tls-cert |string |The certificate to be used for TLS authentication
with the broker.

|--tls-enabled |- |Enable TLS for the Kafka API (not necessary if
specifying custom certs).

|--tls-key |string |The certificate key to be used for TLS
authentication with the broker.

|--tls-truststore |string |The truststore to be used for TLS
communication with the broker.

|--user |string |SASL user to be used for authentication.

|-v, --verbose |- |Enable verbose logging (default: false).
|===
////
