= Object Storage Properties
:description: Reference of object storage properties.
:page-aliases: reference:object-storage-properties.adoc

Object storage properties are a type of cluster property. Cluster properties are configuration settings that control the behavior of a Redpanda cluster at a global level. Configuring cluster properties allows you to adapt Redpanda to specific workloads, optimize resource usage, and enable or disable features. 

For information on how to edit cluster properties, see xref:manage:cluster-maintenance/cluster-property-configuration.adoc[]. 

NOTE: Some object storage properties require that you restart the cluster for any updates to take effect. See the specific property details to identify whether or not a restart is required.

== Cluster configuration

Object storage properties should only be set if you enable xref:manage:tiered-storage.adoc[Tiered Storage]. 

include::reference:partial$properties/object-storage-properties.adoc[tags=!deprecated,!exclude-from-docs]
