= Topic Configuration Properties
:page-aliases: reference:topic-properties.adoc
:description: Reference of topic configuration properties.

A topic-level property sets a Redpanda or Kafka configuration for a particular topic.

Many topic-level properties have corresponding xref:manage:cluster-maintenance/cluster-property-configuration.adoc[cluster properties] that set a default value for all topics of a cluster. To customize the value for a topic, you can set a topic-level property that overrides the value of the corresponding cluster property.

For information on how to configure topic properties, see xref:manage:cluster-maintenance/topic-property-configuration.adoc[].

include::develop:partial$topic-properties-warning.adoc[]

== Topic property mappings

include::reference:partial$topic-property-mappings.adoc[]

---
== Retention and Compaction Properties

These properties control how data is stored, for how long, and when it is deleted or compacted.

include::reference:partial$properties/topic-properties.adoc[tags=category-retention-compaction,!deprecated,!exclude-from-docs]

== Segment and Message Properties

These properties control the size and lifecycle of log segment files and settings for individual messages.

include::reference:partial$properties/topic-properties.adoc[tags=category-segment-message,!deprecated,!exclude-from-docs]

== Performance and Cluster Properties

These properties control disk flushing, replication, and how topics interact with the cluster.

include::reference:partial$properties/topic-properties.adoc[tags=category-performance-cluster,!deprecated,!exclude-from-docs]

== Tiered Storage properties

Configure properties to manage topics for xref:manage:tiered-storage.adoc[Tiered Storage].

include::reference:partial$properties/topic-properties.adoc[tags=category-tiered-storage,!deprecated,!exclude-from-docs]

== Remote Read Replica properties

Configure properties to manage topics for xref:manage:remote-read-replicas.adoc[Remote Read Replicas].

include::reference:partial$properties/topic-properties.adoc[tags=category-remote-read-replica,!deprecated,!exclude-from-docs]

== Apache Iceberg integration properties

Integrate Redpanda topics as Iceberg tables.

include::reference:partial$properties/topic-properties.adoc[tags=category-iceberg-integration,!deprecated,!exclude-from-docs]