= rpk profile
:page-aliases: reference:rpk/rpk-profile.adoc
// tag::single-source[]
:description: pass:q[These commands let you manage `rpk` profiles.] 

Manage `rpk profiles`.

An `rpk profile` talks to a single Redpanda cluster. You can create multiple
profiles for multiple clusters and swap between them with `rpk profile use`.
Multiple profiles may be useful if, for example, you use `rpk` to talk to
a localhost cluster, a dev cluster, and a prod cluster, and you want to keep
your configuration in one place.

You can also use the `RPK_PROFILE` environment variable to temporarily override the current profile without modifying your configuration. The `--profile` flag takes precedence over the environment variable if both are set.

== Usage

[,bash]
----
rpk profile [flags] [command]
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-h, --help |- |Help for profile.

|--config |string |Redpanda or `rpk` config file; default search paths are `/var/lib/redpanda/.config/rpk/rpk.yaml`, `$PWD/redpanda.yaml`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override `rpk` configuration settings. See xref:reference:rpk/rpk-x-options.adoc[`rpk -X`] or execute `rpk -X help` for inline detail or `rpk -X list` for terser detail.

|--ignore-profile |- |Ignore `rpk.yaml` and `redpanda.yaml`; use default settings.

|--profile |string |Profile to use.

|-v, --verbose |- |Enable verbose logging.
|===

// end::single-source[]