= Store the Redpanda Data Directory in hostPath Volumes
:description: pass:q[Learn how to configure Redpanda to store the data directory in Kubernetes `hostPath` volumes. This setup is only for single-node clusters or development environments. Ensure you follow the prerequisites and take into consideration data safety and node affinity.]

You can configure Redpanda to use Kubernetes xref:./volume-types.adoc[`hostPath`] volumes to store the Redpanda data directory. A `hostPath` volume mounts a file or directory from the host node's file system into your Pod.

WARNING: Use `hostPath` volumes only for development environments. If the Pod is deleted and recreated, it might be scheduled on another worker node and lose access to the data.

== Prerequisites

You must have the following:

* *Kubernetes cluster*: Ensure you have a running Kubernetes cluster, either locally, such as with minikube or kind, or remotely.

* https://kubernetes.io/docs/tasks/tools/#kubectl[*Kubectl*]: Ensure you have the `kubectl` command-line tool installed and configured to communicate with your cluster.

* **Dedicated directory**: Ensure you have a dedicated directory on the host worker node to prevent potential conflicts with other applications or system processes.

* **Filesystem**: Ensure that the chosen directory is on an ext4 or XFS filesystem.

== Configure Redpanda to use hostPath volumes

To store Redpanda data in `hostPath` volumes:

[tabs]
======
Helm + Operator::
+
--
.`redpanda-cluster.yaml`
[,yaml]
----
apiVersion: cluster.redpanda.com/v1alpha1
kind: Redpanda
metadata:
name: redpanda
spec:
chartRef: {}
clusterSpec:
  storage:
    hostPath: "<absolute-path>" <1>
    persistentVolume:
      enabled: false <2>
  initContainers:
    setDataDirOwnership:
      enabled: true <3>
----

```bash
kubectl apply -f redpanda-cluster.yaml --namespace <namespace>
```

--
Helm::
+
--
[tabs]
====
--values::
+
.`hostpath.yaml`
[,yaml]
----
storage:
hostPath: "<absolute-path>" <1>
persistentVolume:
  enabled: false <2>
initContainers:
setDataDirOwnership:
  enabled: true <3>
----
+
```bash
helm upgrade --install redpanda redpanda/redpanda --namespace <namespace> --create-namespace \
--values hostpath.yaml --reuse-values
```

--set::
+
```bash
helm upgrade --install redpanda redpanda/redpanda --namespace <namespace> --create-namespace \
  --set storage.hostPath=<absolute-path> \ <1>
    --set storage.persistentVolume.enabled=false \ <2>
  --set statefulset.initContainers.setDataDirOwnership.enabled=true <3>
```

====
--
======

<1> Absolute path on the host to store the Redpanda data directory.
<2> Determines if a PersistentVolumeClaim (PVC) should be created for the Redpanda data directory. When set to `false`, a PVC is not created.
<3>
+
--
include::manage:partial$kubernetes/init-container.adoc[]
--

include::shared:partial$suggested-reading.adoc[]

- For details about `hostPath` volumes, see the https://kubernetes.io/docs/concepts/storage/volumes/#hostpath[Kubernetes documentation^].
- xref:reference:redpanda-helm-spec.adoc[Redpanda Helm Specification]
- xref:reference:crd.adoc[Redpanda CRD Reference]

== Next steps

xref:manage:kubernetes/monitor.adoc#infrastructure-resources[Monitor disk usage] to detect issues early, optimize performance, and plan capacity.