= Store the Redpanda Data Directory in emptyDir Volumes
:description: pass:q[Learn how to configure Redpanda to store the data directory in Kubernetes `emptyDir` volumes. This setup is only for development environments.]
:page-aliases: manage:kubernetes/storage/configure-emptydir.adoc
:page-categories: Management
:env-kubernetes: true

You can configure Redpanda to use Kubernetes xref:./k-volume-types.adoc[`emptyDir`] volumes to store the Redpanda data directory.

WARNING: Use `emptyDir` volumes only for development environments. When a Pod is removed from a node for any reason, the data in the `emptyDir` volume is deleted permanently.

== Prerequisites

You must have the following:

* Kubernetes cluster: Ensure you have a running Kubernetes cluster, either locally, such as with minikube or kind, or remotely.

* https://kubernetes.io/docs/tasks/tools/#kubectl[Kubectl]: Ensure you have the `kubectl` command-line tool installed and configured to communicate with your cluster.

== Configure Redpanda to use emptyDir volumes

Both the Redpanda Helm chart and the Redpanda custom resource provide an interface for configuring `emptyDir` volumes.

To store the Redpanda data directory in `emptyDir` volumes:

[tabs]
======
Operator::
+
--
.`redpanda-cluster.yaml`
[,yaml,lines=9+11]
----
apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
name: redpanda
spec:
chartRef: {}
clusterSpec:
  storage:
    hostPath: ""
    persistentVolume:
      enabled: false
----

```bash
kubectl apply -f redpanda-cluster.yaml --namespace <namespace>
```

--
Helm::
+
--
[tabs]
====
--values::
+
.`emptydir.yaml`
[,yaml,lines=2+4]
----
storage:
hostPath: ""
persistentVolume:
  enabled: false
----
+
```bash
helm upgrade --install redpanda redpanda/redpanda --namespace <namespace> --create-namespace \
--values emptydir.yaml --reuse-values
```

--set::
+
[,bash,lines=4-5]
----
helm upgrade --install redpanda redpanda/redpanda \
  --namespace <namespace> \
  --create-namespace \
  --set storage.hostPath="" \
  --set storage.persistentVolume.enabled=false
----

====
--
======

- `storage.hostPath`: Absolute path on the host to store the Redpanda data directory. If unspecified, then an `emptyDir` volume is used.
- `storage.persistentVolume.enabled`: Determine if a PersistentVolumeClaim (PVC) should be created for the Redpanda data directory. When set to `false`, a PVC is not created.

include::shared:partial$suggested-reading.adoc[]

- xref:./k-volume-types.adoc[]
- For more details about `emptyDir` volumes, see the https://kubernetes.io/docs/concepts/storage/volumes/#emptydir[Kubernetes documentation^].
- xref:reference:k-redpanda-helm-spec.adoc[Redpanda Helm Specification]
- xref:reference:k-crd.adoc[Redpanda CRD Reference]

== Next steps

xref:manage:kubernetes/monitoring/index.adoc#infrastructure-resources[Monitor disk usage] to detect issues early, optimize performance, and plan capacity.