:page-layout: api-partial

The Redpanda Cloud API is a collection of REST APIs that allow you to interact with different parts of Redpanda Cloud. To understand the Cloud API basics, see the xref:ROOT:deploy:deployment-option/cloud/api/cloud-api-overview.adoc[Redpanda Cloud API Overview]. To get started using the API, try the <<quickstart,Quickstart>>.

== Control Plane API

The Control Plane API enables you to programmatically manage your clusters, networks, and resource groups.

The xref:ROOT:deploy:deployment-option/cloud/api/cloud-api-overview.adoc#control-plane-api-url[*base URL*] of the Control Plane API for all organizations is:

```
https://api.redpanda.com
```

== Data Plane APIs

The Data Plane APIs enable you to programmatically manage the resources within your clusters, including topics, users, access control lists (ACLs), and connectors.

The xref:ROOT:deploy:deployment-option/cloud/api/cloud-api-overview.adoc#data-plane-apis-url[*base URL*] of the Data Plane APIs is unique to every cluster. You can retrieve this value by making a xref:get-/v1beta2/clusters/-id-[Get Cluster] request to your target cluster. Use the `dataplane_api.url` from the response body as the base URL when calling the Data Plane API endpoints. 

== Quickstart

. Authenticate to the API. See <<use-this-page-to-try-the-cloud-api>> if issuing requests on this page, or see the xref:ROOT:deploy:deployment-option/cloud/api/cloud-api-authentication.adoc[authentication guide] for details.
. Create a resource group by making a xref:post-/v1beta2/resource-groups[`POST /v1beta2/resource-groups`] request.
. Create a network by making a xref:post-/v1beta2/networks[`POST /v1beta2/networks`] request. When the long-running operation is complete, proceed to the next step.
. Create a cluster by making a xref:post-/v1beta2/clusters[`POST /v1beta2/clusters`] request.
. For BYOC, run `rpk cloud byoc`, passing the `metadata.cluster_id` from the Create Cluster response as a flag:
+
GCP:
+
```bash
rpk cloud byoc gcp apply --redpanda-id=<metadata.cluster_id> --project-id=<gcp-project-id>
```
+
AWS:
+
```bash
rpk cloud byoc aws apply --redpanda-id=<metadata.cluster_id>
```

See also:

- xref:ROOT:deploy:deployment-option/cloud/api/cloud-controlplane-api.adoc[Manage Clusters Using the Cloud API]
- xref:ROOT:deploy:deployment-option/cloud/api/cloud-dataplane-api.adoc[Manage Cluster Resources Using the Cloud API]

== Use this page to try the Cloud API

Before you can issue requests against the API from your browser, make sure you follow these steps:

. Go to *Authentication* in the sidebar.
. Click the *Get Token* button. Do not edit the input field next to the button.
. If successful, the text “1 API key applied” displays under the *Authentication* section of this page. The token is valid for an hour.
. Choose the correct API server for your request.

WARNING: Your API requests are executed against your actual environment and data, not a sandbox. 

=== Make a request to the Control Plane API

For requests to the Control Plane API endpoints:

. Click *API Servers* in the sidebar. 
. Select “https://api.redpanda.com - Control Plane API”. 
. From the Control Plane API endpoints, you can make a request by using the *Try* option. Make sure to enter any required parameter values, and provide the request body object if necessary.

=== Make a request to the Data Plane APIs

For requests to the Data Plane API endpoints: 

. Make a Get Cluster request for your target cluster.
. The Get Cluster response contains the Data Plane API URL. Copy the value of `dataplane_api.url` from the response body. 
. Click *API Servers* in the sidebar and select “\{dataplane_api_url} - Data Plane API”.
. Paste the URL into the `dataplane_api_url` input field.
. From the Data Plane API endpoints, you can make a request by using the *Try* option. Make sure to enter any required parameter values, and provide the request body object if necessary.

== Response codes and errors

If a request is successful, this is indicated by a `2xx` HTTP status code:

- `200` OK. Request was successful.
- `201` Created. The requested resource was successfully created.
- `202` Accepted. The request is accepted and is processing, for example for a long-running operation.
- `204` No content. Usually returned by a successful delete request.

Errors are indicated by the following HTTP status codes:

- `400` Bad request. There is an error that needs to be fixed in the request, such as an invalid parameter value. Attempt the request again after it is fixed.
- `401` Unauthenticated. The authentication credentials are missing or invalid.
- `404` Not found. The specified resource was not found.
- `409` Conflict. Usually returned when the resource to be created by the request already exists.
- `500` Internal server error. Reach out to Redpanda support.

For errors, the response also includes a gRPC error code and details. See the https://grpc.io/docs/guides/status-codes/[official gRPC status codes documentation^] for further details.


