:page-layout: api-partial

The Redpanda Cloud API is a collection of REST APIs that allow you to interact with different parts of Redpanda Cloud. To familiarize yourself with Redpanda Cloud API basics, see the xref:ROOT:deploy:deployment-option/cloud/api/cloud-api-overview.adoc[Redpanda Cloud API Overview]. To get started using the API, try the <<cloud-api-quickstart,Quickstart>>.

== Cloud API architecture 

=== Control Plane API

The Control Plane API enables you to programmatically manage your clusters, networks, and resource groups.

The xref:ROOT:deploy:deployment-option/cloud/api/cloud-api-overview.adoc#control-plane-api-url[*base URL*] of the Control Plane API for all organizations is:

```
https://api.redpanda.com
```

=== Data Plane APIs

The Data Plane APIs enable you to programmatically manage the resources within your clusters, including topics, users, access control lists (ACLs), and connectors.

The xref:ROOT:deploy:deployment-option/cloud/api/cloud-api-overview.adoc#data-plane-apis-url[*base URL*] of the Data Plane APIs is unique to every cluster. You can retrieve this value by making a xref:get-/v1beta2/clusters/-id-[Get Cluster] request to your target cluster. Use the `dataplane_api.url` from the response body as the base URL when calling the Data Plane API endpoints. 

== Response codes and errors

A `2xx` HTTP status code indicates that a request is successful:

- `200` OK. Request was successful.
- `201` Created. The requested resource was successfully created.
- `202` Accepted. The request is accepted and is processing, for example for a long-running operation.
- `204` No content. Usually returned by a successful delete request.

The following HTTP status codes indicate errors:

- `400` Bad request. There is an error that must be fixed in the request, such as an invalid parameter value. Attempt the request again after it is fixed.
- `401` Unauthenticated. The authentication credentials are missing or invalid.
- `404` Not found. The specified resource was not found.
- `409` Conflict. Usually returned when the resource to be created by the request already exists.
- `500` Internal server error. Reach out to Redpanda support.

For errors, the response also includes a gRPC error code and details. See the https://grpc.io/docs/guides/status-codes/[official gRPC status codes documentation^] for further details.


