:page-layout: api-partial

The Redpanda Cloud API is a collection of REST APIs that allow you to interact with different parts of Redpanda Cloud. To familiarize yourself with Redpanda Cloud API basics, see the xref:ROOT:deploy:deployment-option/cloud/api/cloud-api-overview.adoc[Redpanda Cloud API Overview]. To get started using the API, try the xref:ROOT:deploy:deployment-option/cloud/api/cloud-api-quickstart.adoc[Quickstart].

== Requirements

To use the Cloud API:

* You must be a customer with an existing organization in Redpanda Cloud.
* You can only use one organization for authentication. See xref:ROOT:deploy:deployment-option/cloud/api/cloud-api-authentication.adoc[Cloud API Authentication] for steps to authenticate API requests.

== Cloud API architecture 

Redpanda Cloud uses a control plane and data plane architecture.

=== Control Plane API

The Control Plane API enables you to programmatically manage your clusters, networks, and resource groups.

The xref:ROOT:deploy:deployment-option/cloud/api/cloud-api-overview.adoc#control-plane-api-url[*base URL*] of the Control Plane API for all organizations is:

```
https://api.redpanda.com
```

=== Data Plane APIs

The Data Plane APIs enable you to programmatically manage the resources within your clusters, including topics, users, access control lists (ACLs), and connectors.

The xref:ROOT:deploy:deployment-option/cloud/api/cloud-api-overview.adoc#data-plane-apis-url[*base URL*] of the Data Plane APIs is unique to every cluster. You can retrieve this value by making a xref:get-/v1beta2/clusters/-id-[Get Cluster] request to your target cluster. Use the `dataplane_api.url` from the response body as the base URL when calling the Data Plane API endpoints. 

== See also

* xref:ROOT:deploy:deployment-option/cloud/api/cloud-api-quickstart.adoc[Cloud API Quickstart]
* xref:ROOT:deploy:deployment-option/cloud/api/cloud-api-errors.adoc[Cloud API Error and Status Codes]


