= Security
:description: Security index page.

Redpanda recommends that you always configure encryption, authentication, and authorization for production environments.

* xref:security:authentication.adoc[Configure Authentication]
+
Enable and configure authentication. Different components of Redpanda support different authentication methods.

* xref:security:authorization.adoc[Configure Authorization]
+
Configure access-control lists (ACLs) to enable fine-grained access to provisioned users.

* xref:security:encryption.adoc[Configure Kafka TLS Encryption]
+
A security best practice is to enable encryption with TLS or mTLS.

* xref:security:listener-configuration.adoc[Configure Listeners]
+
Use listeners to advertise the location of the broker, so other brokers in the cluster can be found.

* xref:security:console.adoc[Redpanda Console Security]
+
See security topics specific to Redpanda Console.

* xref:security:iam-roles.adoc[IAM Roles]
+
For self-hosted clusters on a public cloud, cloud provider IAM roles provide a safer alternative to static credentials based on access keys.

:::note
All concepts described in this section are compatible with Kafka and its client libraries and CLIs. This section does not cover ways you can protect your Redpanda cluster externally; for example, through network ACLs or private networks.
:::
