:page-layout: api-partial

The Redpanda Cloud Data Plane APIs enable you to programmatically manage the resources within your clusters, including topics, users, access control lists (ACLs), and connectors. 

To familiarize yourself with Redpanda Cloud API basics, see the xref:redpanda-cloud:manage:api/cloud-api-overview.adoc[Redpanda Cloud API Overview]. To get started using the API, try the xref:redpanda-cloud:manage:api/cloud-api-quickstart.adoc[Quickstart].

NOTE: Redpanda Cloud uses a control plane and data plane architecture. To see the available endpoints for managing your clusters, networks, and resource groups, see the xref:api:ROOT:cloud-controlplane-api.adoc[Control Plane API Reference].

== Requirements

To use the Data Plane APIs:

* You must be a customer with an existing organization in Redpanda Cloud.
* You can only use one organization for authentication. See xref:redpanda-cloud:manage:api/cloud-api-authentication.adoc[Cloud API Authentication] for steps to authenticate API requests.

== Data Plane API URL

The xref:redpanda-cloud:manage:api/cloud-api-overview.adoc#data-plane-apis-url[*base URL*] of the Data Plane APIs is unique to every cluster. You can retrieve this value by making a xref:api:ROOT:cloud-controlplane-api.adoc#get-/v1beta2/clusters/-id-[Get Cluster] request to your target cluster. Use the `dataplane_api.url` from the response body as the base URL when calling the Data Plane API endpoints. 

== See also

* xref:redpanda-cloud:manage:api/cloud-api-quickstart.adoc[Cloud API Quickstart]
* xref:redpanda-cloud:manage:api/cloud-api-errors.adoc[Cloud API Error and Status Codes]
* xref:api:ROOT:cloud-controlplane-api.adoc[Control Plane API Reference]

