= Task 3: Troubleshoot Antora Build Errors

In this task, you will troubleshoot common build errors in Antora. The repository has been pre-configured with errors such as an outdated `package-lock.json`, broken cross-references, and AsciiDoc syntax issues. Your goal is to update the logger to show all logs, identify the errors, and resolve them using the provided guidance.

== Learning objectives

- Identify and diagnose common Antora build errors such as missing components or broken cross-references.
- Learn how to read Antora and Asciidoctor error logs to pinpoint and resolve issues in the documentation build.
- Practice fixing build errors and warnings by investigating the logs.

== Prerequisites

- *Git*
+
Run the following command to check if Git is installed:
+
[source,bash]
----
git --version
----
+
If Git is not installed, https://git-scm.com[download and install it].

- *Node.js*
+
Make sure Node.js is installed. You can verify its installation by running:
+
[source,bash]
----
node --version
----
+
If Node.js is not installed, https://nodejs.org/[download and install it].

== Steps

Try to get the build to succeed.

== Useful links

- https://docs.antora.org/antora/latest/playbook/runtime-log-level/
- https://docs.antora.org/asciidoc/latest/errors-and-warnings/
- https://docs.antora.org/antora/latest/playbook/content-source-url/

== Next steps

xref:../task4-add-new-product/README.adoc[= Task 4: Add a New Product Component to the Docs Site]


