= Redpanda Cloud API Overview
:description: Learn about using the Cloud API to manage clusters and cloud resources.
:page-cloud: true

The Redpanda Cloud API is a collection of REST APIs that allow you to interact with different parts of Redpanda Cloud. You can call the API endpoints directly, or use tools like Terraform or Python scripts to automate cluster management.

== Requirements

To be able to use the Cloud API:

* You must be a customer with an existing organization in Redpanda Cloud.
* You can only use one organization for authentication. See xref:./cloud-api-authentication.adoc[] for steps to authenticate API requests.

== Cloud API versus other Redpanda APIs

HTTP Proxy is an HTTP server that exposes some operations you can perform directly on a Redpanda cluster. You can use the Redpanda HTTP Proxy API to perform a subset of actions that are available through the Kafka API, using simpler REST operations.

The Redpanda Schema Registry API is a REST API to manage schemas within a Redpanda cluster.

The Redpanda Admin API is a REST API to manage aspects of a Redpanda cluster. You can use the Admin API to perform operations that are specific to the Redpanda platform and cannot be done using the standard Kafka API.

Redpanda Cloud uses a control plane and data plane architecture. The *control plane* is where most cluster management, operations, and maintenance takes place. The control plane enforces rules in the data plane. The *data plane* is where your cloud cluster lives. The term _data plane_ is used interchangeably with _cluster_. 

The *Control Plane API* allows you to interact with the control plane. You use the Control Plane API to manage cloud clusters, organization, resource groups, networks, and other cloud resources. The Control Plane API does not interact directly with Redpanda clusters, although some of the actions performed through the API can make their way eventually to a cluster.

The *Data Plane APIs* are a collection of APIs through which you can perform actions against a Redpanda cluster. These APIs expose more high-level operations on the data plane by acting as a wrapper around the various APIs mentioned above that are supported by Redpanda (Kafka API, Admin API, or Schema Registry API). 

== Base URLs

The Control Plane API base URL is distinct from the Data Plane APIs base URL.

=== Control Plane API URL

The Control Plane API has a base URL that is the same for any organization:

----
https://api.redpanda.com
----

When making requests to the Control Plane API endpoints, the request URL is the base URL, plus the API version, plus the resource path, for example:

[,bash]
----
https://api.redpanda.com/v1beta2/clusters
----

The Control Plane API version `v1beta2` is currently supported.

=== Data Plane APIs URL

The Data Plane API base URL is unique to the individual target cluster, and will be different across clusters. When making requests to the Data Plane API endpoints, the request URL is the base URL, plus the API version, plus the resource path, for example:

[,bash]
----
https://api-aeb32d9b.cn20bu40d061nvem7sv0.fmc.prd.cloud.redpanda.com/v1alpha1/users
----

The Data Plane API version `v1alpha1` is currently supported.

== Rate limiting


== Pagination

When an endpoint returns a list containing more items than can be returned in a single response, the response object includes a `next_page_token`. You can pass the token value as a parameter in the next request. When the full list has been returned, `next_page_token` is an empty string.

// Should long-running operations go in this doc?

////

Move this to openapi spec

== Use the API reference to interact with the Cloud API

All Cloud API endpoints are documented in our API reference. In the API docs, you can:

- Invoke all endpoints directly from your browser.
- Inspect the autogenerated cURL request based on the input parameters you provide.
- See the request and response schema for different HTTP status codes, and request and response examples. 

Before you can issue actual requests from the browser against the API, you must:

. Be logged in to your https://cloud.redpanda.com/[Redpanda Cloud] account.
. In the API reference, click *Authentication* in the sidebar.
. Click the *Get Token* button. Do not edit the input field next to the button.
. If successful, the text “1 API key applied” displays near the top of the page.
. Choose the correct API server for your request.

=== Make a request to the Control Plane API on the reference page

For requests to the Control Plane API:

. Click *API Servers* in the sidebar. 
. Select “https://api.redpanda.com - Controlplane API”. 
. From the Control Plane API endpoint reference, you can make a request by clicking the *Try* button. Make sure to enter any required parameter values, and provide the request body object if necessary.

=== Make a request to the Data Plane APIs on the reference page

All other services consist of Data Plane API endpoints. To make requests to these endpoints: 

. Make a Get Cluster request for your target cluster.
. The Get Cluster response contains the Data Plane API URL. Copy the value of `dataplane_api.url` from the response body. 
. Click *API Servers* in the sidebar and select “{dataplane_api_url} - Dataplane API”.
. Paste the URL into the dataplane_api_url input field.


////

