= Manage Clusters using the Cloud API
:description: Use the cloud API to manage your clusters in Redpanda Cloud.
:page-cloud: true

The Redpanda Cloud API is a collection of REST APIs that allow you to interact with different parts of Redpanda Cloud. The Control Plane API enables you to programmatically manage your clusters outside of the Redpanda Cloud UI. You can call the API endpoints directly, or use tools like Terraform or Python scripts to automate cluster management.

== Control Plane API

The Control Plane API is one central API that allows you to provision clusters and networks.

The following services consist of Control Plane API endpoints:

* ClusterService
* NamespaceService
* OperationService
* NetworkService

== Use the API reference to interact with the Control Plane APIs

For requests to the Control Plane API:

. Click *API Servers* in the sidebar. 
. Select “https://api.redpanda.com - Controlplane API”. 

== Long-running operations

Some endpoints do not directly return the resource itself, but instead return an operation. The following is an example response of Create Network (`POST /networks`):

[,bash,role=no-copy]
----
{
  "id": "cl5nlt1c1scg01plkoe0",
  "metadata": {
    "@type": "type.googleapis.com/redpanda.api.controlplane.v1beta1.CreateNetworkMetadata",
    "network_id": "cl5o0td1dafe70i7460g"
  },
  "state": "STATE_IN_PROGRESS",
  "started_at": "2023-11-08T12:35:01.957Z",
  "finished_at": null
}
----

The response object represents the long-running operation of creating a network. Network creation is an example of an operation that can take a longer period of time to complete.

To check the progress of an operation, call the `GET /operations/{id}` endpoint using the operation ID as a parameter: 

```bash
curl https://api.redpanda.com/v1beta1/operations/<operation-id>
```

The response contains the current state of the operation: `COMPLETED` or `FAILED`.

== Throughput tiers

When you create a Dedicated or BYOC cluster, you select a throughput tier. Throughput tiers define the sizing of a cluster. Availability depends on the region and the cluster type.

[tabs]
======
Google Cloud Platform (GCP)::
+
--
//  [tabs]
// ====
// Dedicated::
// +

|=== 
| Region | Zones | Available throughput tiers

| asia-south1 
a| * asia-south1-a 
* asia-south1-b 
* asia-south1-c 
a| * tier-1-gcp-v2-x86
* tier-2-gcp-v2-x86
* tier-3-gcp-v2-x86
* tier-4-gcp-v2-x86
* tier-5-gcp-v2-x86
* tier-6-gcp-v2-x86 - _BYOC only_
* tier-7-gcp-v2-x86 - _BYOC only_

|===


// BYOC::
// +
// ====

--
Amazon Web Services (AWS)::
+
--
// [tabs]
// ====
// Dedicated::
// +


// BYOC::
// +

|=== 
| Region | Zones | Available throughput tiers

| af-south-1 
a| * afs1-az1
* afs1-az2 
* afs1-az3
a| 	* tier-1-aws-v2-x86 - _BYOC only_
* tier-2-aws-v2-x86 - _BYOC only_
* tier-3-aws-v2-x86 - _BYOC only_
* tier-4-aws-v2-x86 - _BYOC only_
* tier-5-aws-v2-x86 - _BYOC only_
* tier-6-aws-v2-x86 - _BYOC only_
* tier-7-aws-v2-x86 - _BYOC only_

|===


--
======

== Create a cluster

. First, create a namespace by making a POST request to the `/v1beta1/namespaces` endpoint. Pass a name for your namespace in the request body.
+
[,bash]
----
curl -H 'Content-Type: application/json' \
-H 'Authorization: Bearer <token>' \
-d '{
  "name": "my-new-namespace"
}' -X POST https://api.redpanda.com/v1beta1/namespaces
----
+
A namespace ID is returned. Pass this namespace ID later when you call the Create Cluster endpoint.

. Create a network by calling `POST /v1beta1/networks`.
+
Choose a CIDR range that does not overlap with your existing VPCs or your Redpanda network.
+
[,bash]
----
curl -d \
'{
  "cidr_block": "10.0.0.0/20",
  "cloud_provider": "CLOUD_PROVIDER_GCP",
  "cluster_type": "TYPE_DEDICATED",
  "name": "my-network",
  "namespace_id": "<namespace_id>",
  "region": "us-west1"
}' -X POST https://api.redpanda.com/v1beta1/networks 
----
+
This endpoint returns a <<long_running_operations,long-running operation>>. 

. After the network is created, call `POST /v1beta1/clusters` with the namespace ID and network ID in the request body. 
+
[,bash]
----
curl -d \
'{
  "cloud_provider": "CLOUD_PROVIDER_GCP",
  "connection_type": "CONNECTION_TYPE_PUBLIC",
  "name": "my-new-cluster",
  "namespace_id": "<namespace_id>",
  "network_id": "<network-id>",
  "region": "us-west1",
  "throughput_tier": "tier-1-gcp-um4g",
  "type": "TYPE_DEDICATED",
  "zones": [
    "us-west1-a",
    "us-west1-b",
    "us-west1-c"
    ]
  }
}' -X POST https://api.redpanda.com/v1beta1/clusters
----

The Create Cluster endpoint returns a long-running operation. When the operation is completed, you can retrieve cluster details by calling `GET /v1beta1/clusters/{id}`, passing the cluster ID as a parameter.

=== Additional steps to create a BYOC cluster

. Ensure that you have installed rpk.
. After calling the Create Cluster endpoint, run the `rpk cloud byoc` command. Pass `metadata.cluster_id` from the Create Cluster call:
+
[tabs]
====
GCP::
+
--
```bash
rpk cloud byoc gcp apply --redpanda-id=<metadata.cluster_id> --project-id=<gcp-project-id>
```
--
AWS::
+
--
```bash
rpk cloud byoc aws apply --redpanda-id=<metadata.cluster_id>
```
--
====

== Delete a cluster

To delete a cluster, call `DELETE /v1beta1/clusters/{id}`, passing the cluster ID as a parameter. This is a long-running operation.

```bash
curl -X DELETE https://api.redpanda.com/v1beta1/clusters/<cluster_id>
```

=== Additional steps to delete a BYOC cluster

. Call `GET /v1beta1/clusters/{id}` to check the state of the cluster. Wait until the state is `STATE_DELETING_AGENT`.
. After the state changes to `STATE_DELETING_AGENT`, run `rpk cloud byoc` to destroy the agent.
+
[tabs]
====
GCP::
+
--
```bash
rpk cloud byoc gcp destroy --redpanda-id=<cluster_id> --project-id=<gcp-project-id>
```
--
AWS::
+
--
```bash
rpk cloud byoc aws destroy --redpanda-id=<cluster_id>
```
--
====

. When the cluster is deleted, the delete operation’s state changes to `STATE_COMPLETED`. At this point, you may call `DELETE /v1beta1/networks/{id}` to delete the network. This is a long running operation.
. Optional: After the network is deleted, call `DELETE /v1beta1/namespaces/{id}` to delete the namespace. 

