= How to Authenticate to the Redpanda Cloud API
:description: Use an OAuth token to authenticate requests to the Cloud API.
:page-cloud: true

The Cloud API uses the Client Credentials Flow as defined in https://datatracker.ietf.org/doc/html/rfc6749#section-4.4O[Auth 2.0 RFC 6749, section 4.4]^. In Redpanda Cloud, you must first create a *service account* through which you can authenticate requests to the cloud API. The service account is associated with your Redpanda Cloud organization. The service account acts as an OAuth client that provides its credentials, in this case a client ID and a client secret, to the API authentication server. The authentication server grants an access token in response. You can then include the access token in each request to the API.

You only need to authenticate once to the cloud API. That is, once you obtain an access token, you can use the same token in requests to both Control Plane and Data Plane API endpoints, for as long as the token is valid.

== Request an access token

. Go to the https://cloud.redpanda.com/clients[Clients] page in the Redpanda Cloud UI to create a service account. 
+
NOTE: Service accounts have admin privileges by default. Cloud user roles are not applied for the API.

// UI change not applied
. Click *Add client*. Enter a name and description.

. Retrieve the client ID and secret by clicking *Copy ID* and *Copy Secret*. Make a POST request to `\https://auth.prd.cloud.redpanda.com/oauth/token` with the ID and secret in the request body. To see code examples for getting a token, click the *Request an API token*.
+
The request response provides the access token that remains valid for one hour.

== Authenticate API requests

You must pass the access token in the authorization header of each API request: 

```bash
curl -H "Authorization: Bearer $YOUR_TOKEN"
```