= Configure Redpanda in Kubernetes
:description: Customize the values of the Redpanda Helm chart to configure the cluster and the Kubernetes components that the chart deploys.
:tags: ["Kubernetes"]
:page-aliases: manage:kubernetes/helm-configuration.adoc, manage:helm-configuration.adoc, deploy-self-hosted:arbitrary-configuration.adoc, features:kubernetes-additional-config.adoc, deployment:arbitrary-configuration.adoc, deployment:kubernetes-additional-config.adoc, manage:kubernetes/configure-helm-chart.adoc
:page-categories: Management
:env-kubernetes: true

To configure the cluster and the Kubernetes components that the chart deploys, you can customize the values of the Redpanda Helm chart.

Helm does a three-way merge with the following:

* Your overridden values
* The values in the existing Helm release
* The default values in the new Helm release (if you're upgrading)

== Find configuration options

To see what options you can override in the chart, use the `helm show values` command:

[,bash]
----
helm repo add redpanda https://charts.redpanda.com
helm repo update
helm show values redpanda/redpanda
----

This command displays all the values, descriptions, and defaults, which are also documented in the xref:reference:k-redpanda-helm-spec.adoc[Redpanda Helm Chart Specification].

== Configure Redpanda

[tabs]
======
Operator::
+
--

To customize the values of the Redpanda Helm chart, you can override the defaults in the xref:reference:k-crd.adoc#redpanda[Redpanda custom resource].

You must add all your overrides to the `spec.clusterSpec` configuration.

.`redpanda-cluster.yaml`
[,yaml]
----
apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
  name: redpanda
spec:
  chartRef: {}
  clusterSpec: {}
----

For example, to override the `storage.persistentVolume.storageClass` configuration:

.`redpanda-cluster.yaml`
[,yaml]
----
apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
  name: redpanda
spec:
  chartRef: {}
  clusterSpec:
    storage:
      persistentVolume:
        storageClass: "<storage-class>"
----

```bash
kubectl apply -f redpanda-cluster.yaml --namespace <namespace>
```

The values in your Redpanda custom resource override their counterparts in the Helm chart's `values.yaml` file. Any values that are not overridden maintain their defaults.

--
Helm::
+
--

To customize the values of the Redpanda Helm chart, you can override the defaults in your own YAML file with the `--values` option or in the command line with the `--set` option.

[TIP]
====
Redpanda Data recommends using the `--values` option and creating separate YAML files for each configuration block that you need to override. The Redpanda documentation follows this best practice.
This way, it's clearer to understand what you've overridden from the `helm` command.

You can pass more than one `--values` option in the same command. For example, if you wanted to override the TLS configuration and the storage configuration, you could put those overrides in separate files:

```bash
helm upgrade --install redpanda redpanda/redpanda \
    --namespace <namespace> --create-namespace \
    --values custom-storage-class.yaml \
    --values enable-tls.yaml
```
====

[tabs]
====
--values::
+
The `--values` option enables you to keep your overrides in one or more YAML files.
If you specify multiple files and then override the same values in two or more of them, the rightmost file takes precedence.
For example, you might override the `storage.persistentVolume.storageClass` configuration in a file called `storage-class.yaml`:
+
.`storage-class.yaml`
[,yaml]
----
storage:
  persistentVolume:
    storageClass: "my-storage-class"
----
+
The `helm` command to apply this configuration override looks something like the following:
+
```bash
helm upgrade --install redpanda redpanda/redpanda \
    --namespace <namespace> --create-namespace \
    --values storage-class.yaml --reuse-values
```
+
The values in your YAML files override their counterparts in the Helm chart's `values.yaml` file. Any values that are not overridden maintain their defaults.
+
Use the `--reuse-values` flag to apply your overrides on top of existing overrides that you've already made. Don't include this flag if you're upgrading to a new version of the Helm chart. If you're upgrading to a new version of the Helm chart, this flag prevents any values in the new release from being applied.

--set::
+
The `--set` option allows you to specify configuration overrides in the command line.
For example, you might override the `storage.persistentVolume.storageClass` configuration like so:
+
[,bash]
----
helm upgrade --install redpanda redpanda/redpanda \
    --namespace <namespace> --create-namespace \
    --set storage.persistentVolume.storageClass=my-storage-class
----
+
For more details, see the https://helm.sh/docs/intro/using_helm/#customizing-the-chart-before-installing[Helm documentation^].
+
The values in the `--set` options override their counterparts in the Helm chart's `values.yaml` file. Any values that are not overridden maintain their defaults.

====
--
======

NOTE: If you're upgrading and you already have Redpanda Console installed, set `console.enabled` to `false` to stop Helm from trying to deploy it again.

== Specify Redpanda CLI flags in the Helm Chart

The Redpanda Helm chart allows you to specify Redpanda CLI flags, such as `--smp`, `--memory`, or `--reserve-memory`, directly rather than having to find the appropriate configuration in the chart's values.

When you specify CLI flags, those values take precedence over the values defined in the chart's values.

[tabs]
======
Operator::
+
--
.`redpanda-cluster.yaml`
[,yaml]
----
apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
  name: redpanda
spec:
  chartRef: {}
  clusterSpec:
    statefulset:
      additionalRedpandaCmdFlags:
        - <flag>
----

```bash
kubectl apply -f redpanda-cluster.yaml --namespace <namespace>
```

--
Helm::
+
--
[tabs]
====
--values::
+
.`redpanda-flags.yaml`
[,yaml]
----
statefulset:
  additionalRedpandaCmdFlags:
    - <flag>
----
+
```bash
helm upgrade --install redpanda redpanda/redpanda \
    --namespace <namespace> --create-namespace \
    --values redpanda-flags.yaml --reuse-values
```

--set::
+
[,bash]
----
helm upgrade --install redpanda redpanda/redpanda \
    --namespace <namespace> --create-namespace \
    --set "statefulset.additionalRedpandaCmdFlags=[<flags>]"
----

====
--
======

== Configure Redpanda Console

Redpanda Console is included as a subchart of the Redpanda Helm chart.

You can configure Redpanda Console in the `console.config` object using the xref:reference:console/config.adoc[Redpanda Console configuration values].

For example, to enable the admin API for Redpanda Console:

[tabs]
======
Operator::
+
--
.`redpanda-cluster.yaml`
[,yaml]
----
apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
  name: redpanda
spec:
  chartRef: {}
  clusterSpec:
    console:
      enabled: true
      console:
        config:
          redpanda:
            adminApi:
              enabled: true
              urls:
              - http://redpanda-0.redpanda.<namespace>.svc.cluster.local.:9644
----

```bash
kubectl apply -f redpanda-cluster.yaml --namespace <namespace>
```
--
Helm::
+
--
[tabs]
====
--values::
+
.`console-enable-admin-api.yaml`
[,yaml]
----
console:
  enabled: true
  console:
    config:
      redpanda:
        adminApi:
          enabled: true
          urls:
          - http://redpanda-0.redpanda.<namespace>.svc.cluster.local.:9644
----
+
```bash
helm upgrade --install redpanda redpanda/redpanda \
    --namespace <namespace> --create-namespace \
    --values console-enable-admin-api.yaml --reuse-values
```

--set::
+
[,bash]
----
helm upgrade --install redpanda redpanda/redpanda \
    --namespace <namespace> --create-namespace \
    --set console.console.config.redpanda.adminApi.enabled=true \
    --set console.console.config.redpanda.adminApi.urls={"http://redpanda-0.redpanda.<namespace>.svc.cluster.local.:9644"}
----

====
--
======

If you want to use the separate Redpanda Console Helm chart, disable Redpanda Console in the Redpanda Helm chart with `console.enabled=false`.
To see what options you can override in the Redpanda Console chart, use the `helm show values` command:

```bash
helm repo add redpanda https://charts.redpanda.com
helm repo update
helm show values redpanda/console
```

For default values and documentation for configuration options, see the https://artifacthub.io/packages/helm/redpanda-data/console?modal=values[`values.yaml`^] file.

== Differences between helm install and helm upgrade

When managing Redpanda deployments with Helm, it's important to understand the differences between `helm install` and `helm upgrade`, particularly in how they handle cluster configuration overrides.

Use `helm install` to install or reinstall Redpanda. Use `helm upgrade` to reconfigure an existing deployment.

=== Reinstall Redpanda

When reinstalling Redpanda with `helm install`, cluster configuration overrides specified in the Helm values may not take effect due to PersistentVolumeClaim (PVC) retention. 

By default, most PVCs are retained when a Helm release is uninstalled. As a result, when Redpanda is reinstalled, the previously created PVCs are adopted, restoring the state of the previous cluster. This adoption results in the new `bootstrap.yaml` file being ignored and the `post_upgrade` job not running. The `post_upgrade` job is a component in the Helm chart that applies configuration overrides during an upgrade.

To ensure the new installation does not adopt the old PVCs and restore the previous state:

. Delete the existing PVCs before reinstalling Redpanda:
+
[,bash]
----
kubectl delete pvc -l app=redpanda --namespace <namespace>
----

. Execute the `helm install` command to reinstall Redpanda with a clean state.

=== Configure an existing cluster

During a `helm upgrade`, the `post_upgrade` job is triggered, which applies the latest overrides to the cluster.

include::shared:partial$suggested-reading.adoc[]

* https://helm.sh/docs/intro/using_helm/#customizing-the-chart-before-installing[Customizing the Chart Before Installing^].
