= Enable Rack Awareness in Kubernetes
:description: Enable rack awareness to place partition replicas across different failure zones.
:page-context-links: [{"name": "Linux", "to": "manage:rack-awareness.adoc" },{"name": "Kubernetes", "to": "manage:kubernetes/kubernetes-rack-awareness.adoc" } ]
:page-tags: ["Kubernetes", "Helm configuration"]

include::manage:partial$rack-awareness.adoc[]

When you enable rack awareness in the Redpanda Helm chart, Kubernetes failure zones are treated as racks. Redpanda maps each rack to a failure zone and places partition replicas across them. For more details about Kubernetes failure zones, see the https://kubernetes.io/docs/setup/best-practices/multiple-zones/[Kubernetes documentation^].

== Prerequisites

You must have the following:

* Kubernetes cluster: Ensure you have a running Kubernetes cluster, either locally, such as with minikube or kind, or remotely.

* https://kubernetes.io/docs/tasks/tools/#kubectl[Kubectl^]: Ensure you have the `kubectl` command-line tool installed and configured to communicate with your cluster.

== Annotate or label Node resources

In Kubernetes, failure zones are treated as racks. Redpanda maps each rack to a failure zone and places partition replicas across them. For more details about Kubernetes failure zones, see the https://kubernetes.io/docs/setup/best-practices/multiple-zones/[Kubernetes documentation^].

To assign a failure zone to your Kubernetes nodes, ensure that each of your Node resources is annotated or labeled with a key/value pair that corresponds to a failure zone. The Helm chart assigns each Redpanda broker to a particular rack, according to the failure zone of the Kubernetes node on which the broker is running.

Managed Kubernetes platforms usually annotate Node resources with the availability zone in which the node instance is hosted. For example `topology.kubernetes.io/zone=us-east-1a`.

To check the value of the `topology.kubernetes.io/zone` key, run the following:

[,bash]
----
kubectl get node \
-o=custom-columns=NODE:.metadata.name,ZONE:.metadata.annotations."topology\.kubernetes\.io/zone"
----

Example output:

[,text,role="no-copy"]
----
NODE                 ZONE
example-worker       us-east-1a
example-worker2      us-east-1b
example-worker3      us-east-1c
----

If you don't see any values in the Zone column, make sure to annotate or label your Node resources with key/value pairs that correspond to your fault-tolerance requirements. For example:

[,bash]
----
kubectl annotate node example-worker topology.kubernetes.io/zone=rack1
kubectl annotate node example-worker2 topology.kubernetes.io/zone=rack2
kubectl annotate node example-worker3 topology.kubernetes.io/zone=rack3
----

== Configure rack awareness

To enable rack awareness in your Redpanda cluster, you need to override the default configuration in the Helm chart depending on the key you used to annotate or label Node resources with the availability zone.

=== Use the default topology.kubernetes.io/zone key

By default, the Helm chart sets the rack to the value in the https://kubernetes.io/docs/reference/labels-annotations-taints/#topologykubernetesiozone[well-known^] `topology.kubernetes.io/zone` key.

If your Node resources are annotated or labeled with the `topology.kubernetes.io/zone` key, do the following:

[tabs]
======
Helm + Operator::
+
--
.`redpanda-cluster.yaml`
[,yaml]
----
apiVersion: cluster.redpanda.com/v1alpha1
kind: Redpanda
metadata:
  name: redpanda
spec:
  chartRef: {}
  clusterSpec:
    rackAwareness:
      enabled: true
    serviceAccount:
      create: true
    rbac:
      enabled: true
----

```bash
kubectl apply -f redpanda-cluster.yaml --namespace <namespace>
```

--
Helm::
+
--
[tabs]
====
--values::
+
.`rack-awareness.yaml`
[,yaml]
----
rackAwareness:
  enabled: true
serviceAccount:
  create: true
rbac:
  enabled: true
----
+
```bash
helm upgrade --install redpanda redpanda/redpanda --namespace <namespace> --create-namespace \
--values rack-awareness.yaml --reuse-values
```

--set::
+
```bash
helm upgrade --install redpanda redpanda/redpanda --namespace <namespace> --create-namespace \
  --set rackAwareness.enabled=true \
  --set serviceAccount.create=true \
  --set rbac.enabled=true
```

====
--
======

NOTE: The `serviceAccount` and `rbac` configurations are required. These configurations allow the initialization container to securely read the node annotations using the Kubernetes API.

=== Other keys

If your Node resources are annotated or labeled with a different key, set `rackAwareness.nodeAnnotation` to match your annotation key.

[tabs]
======
Helm + Operator::
+
--
.`redpanda-cluster.yaml`
[,yaml]
----
apiVersion: cluster.redpanda.com/v1alpha1
kind: Redpanda
metadata:
  name: redpanda
spec:
  chartRef: {}
  clusterSpec:
    rackAwareness:
      enabled: true
      nodeAnnotation: 'example'
    serviceAccount:
      create: true
    rbac:
      enabled: true
----

```bash
kubectl apply -f redpanda-cluster.yaml --namespace <namespace>
```

--
Helm::
+
--
[tabs]
====
--values::
+
.`rack-awareness.yaml`
[,yaml]
----
rackAwareness:
  enabled: true
  nodeAnnotation: 'example'
serviceAccount:
  create: true
rbac:
  enabled: true
----
+
```bash
helm upgrade --install redpanda redpanda/redpanda --namespace <namespace> --create-namespace \
--values rack-awareness.yaml --reuse-values
```

--set::
+
```bash
helm upgrade --install redpanda redpanda/redpanda --namespace <namespace> --create-namespace \
  --set rackAwareness.enabled=true \
  --set rackAwareness.nodeAnnotation='example' \
  --set serviceAccount.create=true \
  --set rbac.enabled=true
```

====
--
======

== Verify that rack awareness is enabled

After deploying Redpanda, make sure that rack awareness is enabled and configured on your Redpanda brokers.

. Make sure that rack awareness has been enabled and configured on your Redpanda brokers:
+
[tabs]
====
TLS Enabled::
+
--
```bash
kubectl --namespace <namespace> exec -i -t redpanda-0 -c redpanda -- \
  rpk cluster config get enable_rack_awareness \
    -X admin.hosts=redpanda-0.redpanda.<namespace>.svc.cluster.local.:9644,redpanda-1.redpanda.<namespace>.svc.cluster.local.:9644,redpanda-2.redpanda.<namespace>.svc.cluster.local.:9644 \
    -X admin.tls.ca=/etc/tls/certs/default/ca.crt \
    -X admin.tls.enabled=true
```

--
TLS Disabled::
+
--

```bash
kubectl --namespace <namespace> exec -i -t redpanda-0 -c redpanda -- \
  rpk cluster config get enable_rack_awareness \
    -X admin.hosts=redpanda-0.redpanda.<namespace>.svc.cluster.local.:9644,redpanda-1.redpanda.<namespace>.svc.cluster.local.:9644,redpanda-2.redpanda.<namespace>.svc.cluster.local.:9644
```
--
====
+
Example output:
+
[.no-copy]
----
true
----

== Next steps

Use rack awareness with xref:manage:cluster-maintenance/continuous-data-balancing.adoc[Continuous Data Balancing] to continually maintain the configured replication level, even after a rack failure. For a given partition, Redpanda tries to move excess replicas from racks that have more than one replica to racks that have no replicas.

include::shared:partial$suggested-reading.adoc[]

- xref:reference:redpanda-helm-spec.adoc#rackawareness[Redpanda Helm Specification]
- xref:reference:crd.adoc[Redpanda CRD Reference]
