= Manage Topics with the Redpanda Operator
:description: Use the Topic resource to declaratively create Kafka topics as part of a Redpanda deployment. Each Topic resource is mapped to a topic in your Redpanda cluster. The topic controller keeps the corresponding Kafka topic in sync with the Topic resource.

The Redpanda Operator allows you to declaratively create and manage Kafka topics using xref:reference:topic-crd.adoc[Topic custom resources] (resources) in Kubernetes. Each Topic resource is mapped to a topic in your Redpanda cluster. The topic controller, a component of the Redpanda Operator, keeps the corresponding Kafka topic in sync with the Topic resource. This resource allows you to create topics as part of a Redpanda deployment.

== Limitations

- You cannot create access control lists (ACLs) directly in the Topic resource. To create ACLs for your topics, you must use rpk or another Kafka client. For details about ACLs, see xref:manage:security/authorization.adoc[].

- Valid topic names must consist of lowercase alphanumeric characters, hyphens (-), or periods (.). Topic names cannot start or end with a non-alphanumeric character. Underscores (_) are not allowed. For example, `chat-room` is a valid name, whereas `chat_room` is not.

== Prerequisites

You must have the following:

* Kubernetes cluster: Ensure you have a running Kubernetes cluster, either locally, such as with minikube or kind, or remotely.

* https://kubernetes.io/docs/tasks/tools/#kubectl[Kubectl^]: Ensure you have the `kubectl` command-line tool installed and configured to communicate with your cluster.

* Redpanda: Ensure you have the xref:deploy:deployment-option/self-hosted/kubernetes/kubernetes-deploy.adoc[Redpanda Operator and a Redpanda resource deployed] in your Kubernetes cluster.

== Create a topic

You can create a topic using a Topic resource:

[,yaml,lines=4+6+10-15]
----
apiVersion: cluster.redpanda.com/v1alpha1
kind: Topic
metadata:
  name:
spec:
  kafkaApiSpec:
    brokers: []
    tls: {}
    sasl: {}
  partitions:
  replicationFactor:
  additionalConfig: {}
  metricsNamespace:
  overwriteTopicName:
  interval:
----

- xref:reference:topic-crd.adoc#k8s-api-github-com-redpanda-data-redpanda-src-go-k8s-apis-cluster-redpanda-com-v1alpha1-topicspec[`metadata.name`] (*required*): The name of the topic. You can overwrite this name using the `overwriteTopicName` property.

- xref:reference:topic-crd.adoc#k8s-api-github-com-redpanda-data-redpanda-src-go-k8s-apis-cluster-redpanda-com-v1alpha1-kafkaapispec[`spec.kafkaApiSpec`] (*required*): Configuration details for connecting to Redpanda brokers.

- xref:reference:topic-crd.adoc#k8s-api-github-com-redpanda-data-redpanda-src-go-k8s-apis-cluster-redpanda-com-v1alpha1-topicspec[`spec.partitions`]: The number of topic shards distributed across the brokers in a Redpanda cluster. This value cannot be decreased post-creation. Overrides the default cluster property xref:reference:cluster-properties.adoc#default_topic_partitions[`default_topic_partitions`].

- xref:reference:topic-crd.adoc#k8s-api-github-com-redpanda-data-redpanda-src-go-k8s-apis-cluster-redpanda-com-v1alpha1-topicspec[`spec.replicationFactor`]: Specifies the number of topic replicas. The value must be an odd number. Overrides the default cluster property xref:reference:cluster-properties.adoc#default_topic_replications[`default_topic_replications`].

- xref:reference:topic-crd.adoc#k8s-api-github-com-redpanda-data-redpanda-src-go-k8s-apis-cluster-redpanda-com-v1alpha1-topicspec[`spec.additionalConfig`]: A map of any topic-specific configuration options. See xref:reference:topic-properties.adoc[]

- xref:reference:topic-crd.adoc#k8s-api-github-com-redpanda-data-redpanda-src-go-k8s-apis-cluster-redpanda-com-v1alpha1-topicspec[`spec.metricsNamespace`]: The fully-qualified name of the topic metrics for use in multi-operator environments. Defaults to `redpanda-operator`.

- xref:reference:topic-crd.adoc#k8s-api-github-com-redpanda-data-redpanda-src-go-k8s-apis-cluster-redpanda-com-v1alpha1-topicspec[`spec.overwriteTopicName`]: Overwrites the topic name in `metadata.name`.

- xref:reference:topic-crd.adoc#k8s-api-github-com-redpanda-data-redpanda-src-go-k8s-apis-cluster-redpanda-com-v1alpha1-topicspec[`spec.interval`]: Sets the reconciliation interval for the topic controller. Default is 3 seconds (`3s`).

=== Example Topic resource

This example creates a topic called `chat-room`.
The `kafkaApiSpec` property configures the connection to a Redpanda cluster using the defaults in the Redpanda Helm chart.

.`example-topic.yaml`
[,yaml]
----
apiVersion: cluster.redpanda.com/v1alpha1
kind: Topic
metadata:
  name: chat-room
spec:
  partitions: 3
  replicationFactor: 3
  kafkaApiSpec:
    brokers:
      - "redpanda-0.redpanda.<namespace>.svc.cluster.local:9093"
      - "redpanda-1.redpanda.<namespace>.svc.cluster.local:9093"
      - "redpanda-2.redpanda.<namespace>.svc.cluster.local:9093"
    tls:
      caCertSecretRef:
        name: "redpanda-default-cert"
        key: "ca.crt"
----

[,bash]
----
kubectl apply -f example-topic.yaml --namespace <namespace>
----

Replace `<namespace>` with the namespace in which you deployed Redpanda.

== Verify a topic

After deploying a Topic resource, verify that the Redpanda Operator reconciled the Topic resource.

[,bash]
----
kubectl logs -l app.kubernetes.io/name=operator -c manager --namespace redpanda
----

.Example output
[%collapsible]
====
[,json,.no-copy,lines=5+22]
----
{
  "level":"info",
  "ts":"2023-09-25T16:20:09.538Z",
  "logger":"TopicReconciler.Reconcile",
  "msg":"Starting reconcile loop",
  "controller":"topic",
  "controllerGroup":"cluster.redpanda.com",
  "controllerKind":"Topic",
  "Topic":
  {
    "name":"chat-room",
    "namespace":"<namespace>"
  },
  "namespace":"<namespace>",
  "name":"chat-room",
  "reconcileID":"c0cf9abc-a553-48b7-9b6e-2de3cdfb4432"
}
{
  "level":"info",
  "ts":"2023-09-25T16:20:09.581Z",
  "logger":"TopicReconciler.Reconcile",
  "msg":"reconciliation finished in 43.436125ms, next run in 3s",
  "controller":"topic",
  "controllerGroup":"cluster.redpanda.com",
  "controllerKind":"Topic",
  "Topic":
  {
    "name":"chat-room",
    "namespace":"<namespace>"
  },
  "namespace":"<namespace>",
  "name":"chat-room",
  "reconcileID":"c0cf9abc-a553-48b7-9b6e-2de3cdfb4432",
  "result":
  {
    "Requeue":false,
    "RequeueAfter":3000000000
  }
}
----
====

Then, verify that the topic now exists in your Redpanda cluster:

[tabs]
====
TLS Enabled::
+
--
[,bash]
----
kubectl --namespace <namespace> exec -i -t redpanda-0 -c redpanda -- \
  rpk topic list \
    -X brokers=redpanda-0.redpanda.<namespace>.svc.cluster.local.:9093 \
    -X tls.ca=/etc/tls/certs/default/ca.crt \
    -X tls.enabled=true
----
--
TLS Disabled::
+
--
[,bash]
----
kubectl --namespace <namespace> exec -i -t redpanda-0 -c redpanda -- \
  rpk topic list \
    -X brokers=redpanda-0.redpanda.<namespace>.svc.cluster.local.:9093
----
--
====

Example output:

[.no-copy]
----
NAME          PARTITIONS  REPLICAS
chat-room     3           3
----

== Update a topic

To update a topic, edit the Topic resource configuration, and apply the changes.

The following example adds a cleanup policy to the `chat-room` topic:

.`example-topic.yaml`
[,yaml,lines=8-9]
----
apiVersion: cluster.redpanda.com/v1alpha1
kind: Topic
metadata:
  name: chat-room
spec:
  partitions: 3
  replicationFactor: 3
  additionalConfig:
    cleanup.policy: "compact"
  kafkaApiSpec:
    brokers:
      - "redpanda-0.redpanda.<namespace>.svc.cluster.local:9093"
      - "redpanda-1.redpanda.<namespace>.svc.cluster.local:9093"
      - "redpanda-2.redpanda.<namespace>.svc.cluster.local:9093"
    tls:
      caCertSecretRef:
        name: "redpanda-default-cert"
        key: "ca.crt"
----

[,bash]
----
kubectl apply -f example-topic.yaml --namespace <namespace>
----

== Delete a topic

To delete a topic, delete the Topic resource.

For example:

[,bash]
----
kubectl delete -f example-topic.yaml --namespace <namespace>
----

NOTE: If you delete the Kafka topic directly using a client such as rpk, the topic controller will recreate an empty topic, and you will lose all records inside the topic.

== Suggested reading

- xref:reference:topic-crd.adoc[]
- xref:reference:topic-properties.adoc[]

== Next steps

Combine xref:manage:kubernetes/security/sasl-kubernetes.adoc[SASL authentication] with xref:manage:security/authorization.adoc[authorization] to control which users have permissions to interact with your topics.