= Upgrade Redpanda in Kubernetes
:description: To benefit from Redpanda's new features and enhancements, use rolling upgrades to upgrade to the latest version. New features are available after all brokers (Pods) in the cluster are upgraded and restarted.
:page-context-links: [{"name": "Linux", "to": "manage:cluster-maintenance/rolling-upgrade.adoc" },{"name": "Kubernetes", "to": "manage:kubernetes/rolling-upgrade.adoc" } ]

To benefit from Redpanda's new features and enhancements, use rolling upgrades to upgrade to the latest version. New features are available after all brokers (Pods) in the cluster are upgraded and restarted.

Redpanda platform version numbers follow the convention AB.C.D, where AB is the two digit year, C is the feature release, and D is the patch release. For example, version 22.3.1 indicates the first patch release on the third feature release of the year 2022. Patch releases include bug fixes and minor improvements, with no change to user-facing behavior. New and enhanced features are documented with each feature release.

include::partial$rolling-upgrades/important-upgrade-note.adoc[]

== Prerequisites

* A running Redpanda cluster.
* https://stedolan.github.io/jq/download/[jq] for listing available versions.
* An understanding of the <<impact-of-broker-restarts,impact of broker restarts>> on clients, node CPU, and any alerting systems you use.
* Review incompatible changes in new versions:
+
|===
| Version | Change

|23.1
| If remote read is disabled, and if the requested term falls below the local log's beginning, then Redpanda updates the Kafka handler to return the start offset of Redpanda's local log. In other words, if you request a value older than the lowest offset, Redpanda returns the lowest offset, not -1.
|===

== Find a new version

Before you perform a rolling upgrade, you must find out which Redpanda version you are currently running, whether you can upgrade straight to the new version, and what's changed since your original version.

. Find your current version:
+
[tabs]
====
TLS Enabled::
+
--

```bash
kubectl exec redpanda-0 --namespace <namespace> -c redpanda -- \
  rpk redpanda admin brokers list \
    --admin-api-tls-enabled \
    --admin-api-tls-truststore <path-to-admin-api-ca-certificate> \
    -X admin.hosts=<broker-url>:<admin-api-port>
```

--
TLS Disabled::
+
--

```bash
kubectl exec redpanda-0 --namespace <namespace> -c redpanda -- \
  rpk redpanda admin brokers list \
    -X admin.hosts=<broker-url>:<admin-api-port> \
```

--
====
+
For all available flags, see the xref:reference:rpk/rpk-redpanda/rpk-redpanda-admin-brokers-list.adoc[`rpk redpanda admin brokers list` command reference].
+
Example output:
+
The Redpanda version for each broker is listed under `BROKER-VERSION`.
+
[,plain,role=no-copy]
----
NODE-ID  BROKER-VERSION
0        v22.2.10
1        v22.2.10
2        v22.2.10
----

. Find the Redpanda version that's used in the latest Redpanda Helm chart:
+
[,bash]
----
helm repo update && \
helm show chart redpanda/redpanda | grep appVersion
----
+
Example output:
+
[,plain,role=no-copy]
----
appVersion:	v22.2.10
----
+
[NOTE]
====
If your current version is more than one feature release behind the version in the latest Redpanda Helm chart, you must first upgrade to an intermediate version. To list all available versions:

```bash
curl -s 'https://hub.docker.com/v2/repositories/redpandadata/redpanda/tags/?ordering=last_updated&page=1&page_size=50' | jq -r '.results[].name'
```
====

. Check the https://github.com/redpanda-data/redpanda/releases[release notes] to find information about what has changed between Redpanda versions.

include::manage:partial$rolling-upgrades/restart-impact.adoc[leveloffset=+1]

== Perform a rolling upgrade

A rolling upgrade involves putting a broker into maintenance mode, upgrading the broker,
taking the broker out of maintenance mode, and then repeating the process on the next broker in the cluster.
Placing brokers into maintenance mode ensures a smooth upgrade of your cluster while reducing the risk of interruption or degradation in service.

When a broker is placed into maintenance mode, it reassigns its partition leadership to other brokers for all topics that have a replication factor greater than one.
Reassigning partition leadership involves _draining_ leadership from the broker and _transferring_ that leadership to another broker.
If you have topics with `replication.factor=1` and sufficient disk space, Redpanda Data recommends temporarily increasing the replication factor.
This can help limit outages for these topics during the rolling upgrade. Do this before the upgrade to ensure there's time for the data to replicate to other brokers.
For details, see xref:manage:data-migration.adoc#change-topic-replication-factor[Change topic replication factor].

To perform a rolling upgrade:

. <<Deploy an upgraded StatefulSet>> with your desired Redpanda version.
. <<Upgrade and restart the brokers>> separately, one after the other.

[WARNING]
====
Redpanda Data does not recommend using the `kubectl rollout restart` command to perform rolling upgrades.
Although the chart's `preStop` lifecycle hook puts the broker into maintenance mode before a Pod is deleted,
the `terminationGracePeriod` may not be long enough to allow maintenance mode to finish.
If maintenance mode does not finish before the Pod is deleted, you may lose data.
After the `terminationGracePeriod`, the container is forcefully stopped using a `SIGKILL` command.

It can be a challenge to determine the necessary value for the `terminationGracePeriod`. In common cases, 30 seconds should be sufficient.
For large clusters, 90 seconds should be sufficient. You can test different values in a development environment. To configure the `terminationGracePeriod`,
use the xref:reference:redpanda-helm-spec.adoc#statefulsetterminationgraceperiodseconds[`statefulset.terminationGracePeriodSeconds`] setting.
====

=== Deploy an upgraded StatefulSet

To deploy an upgraded StatefulSet, you need to delete the existing StatefulSet, then upgrade the Redpanda Helm chart deployment with your desired Redpanda version.

. Delete the existing StatefulSet, but leave the Pods running:
+
```bash
kubectl delete statefulset redpanda --cascade=orphan --namespace <namespace>
```

. Upgrade the Redpanda version by overriding the `image.tag` setting. Replace `<new-version>` with a valid version tag.
+
```bash
helm upgrade --install redpanda redpanda/redpanda \
  --namespace redpanda \
  --create-namespace \
  --set image.tag=<new-version> --set statefulset.updateStrategy.type=OnDelete
```
+
[NOTE]
====
Make sure to include all your configuration overrides in the `helm upgrade` command.
Otherwise, the upgrade may fail.
For example, if you already enabled SASL, include the same SASL overrides.

Do not use the `--reuse-values` flag, otherwise Helm won't include any new values from the upgraded chart.
====

The `statefulset.updateStrategy.type=OnDelete` setting stops the StatefulSet from upgrading all the Pods automatically.
Changing the `upgradeStrategy` to `OnDelete` allows you to keep the existing Pods running and upgrade each broker separately.
For more details, see the https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#update-strategies[Kubernetes documentation].

TIP: To use the Redpanda version in the latest version of the Redpanda Helm chart, set `image.tag` to `""` (empty string).

=== Upgrade and restart the brokers

To upgrade the Redpanda brokers, you must do the following to each broker, one at a time:

. Place the broker into maintenance mode.
. Wait for maintenance mode to finish.
. Delete the Pod that the broker was running in.

TIP: Before placing a broker into maintenance mode, you may want to temporarily disable or ignore alerts related to under-replicated partitions.
When a broker is taken offline during a restart, replicas can become under-replicated.

. Select a broker that has not been upgraded yet and place it into maintenance mode.
+
In this example, the command is executed on a Pod called `redpanda-0` in the `redpanda` namespace. The ordinal of the StatefulSet replica, `0` in this example, is the same as the broker's ID. This ID is used to enable maintenance mode on the broker: `rpk cluster maintenance enable 0`.
+
[tabs]
====
TLS Enabled::
+
--

```bash
kubectl exec redpanda-0 --namespace <namespace> -c redpanda -- \
  rpk cluster maintenance enable 0 --wait \
    --admin-api-tls-enabled \
    --admin-api-tls-truststore <path-to-admin-api-ca-certificate> \
    -X admin.hosts=<broker-url>:<admin-api-port>
```

--
TLS Disabled::
+
--

```bash
kubectl exec redpanda-0 --namespace <namespace> -c redpanda -- \
  rpk cluster maintenance enable 0 --wait \
    -X admin.hosts=<broker-url>:<admin-api-port> \
```

--
====
+
The `--wait` flag ensures that the cluster is healthy before putting the broker into maintenance mode.
+
The draining process won't start until the cluster is healthy.
The amount of time it takes to drain a broker and reassign partition leadership depends on the number of partitions and how healthy the cluster is.
For healthy clusters, draining leadership should take less than a minute.
If the cluster is unhealthy, such as when a follower is not in sync with the leader, then draining the broker can take even longer.
+
Example output:
+
[,plain,role=no-copy]
----
NODE-ID  DRAINING  FINISHED  ERRORS  PARTITIONS  ELIGIBLE  TRANSFERRING  FAILED
0        true      true      false   1           0         1             0
----

. Wait until the cluster is healthy before continuing:
+
[tabs]
====
TLS Enabled::
+
--

```bash
kubectl exec redpanda-0 --namespace <namespace> -c redpanda -- \
  rpk cluster health \
    --admin-api-tls-enabled \
    --admin-api-tls-truststore <path-to-admin-api-ca-certificate> \
    -X admin.hosts=<broker-url>:<admin-api-port>
```

--
TLS Disabled::
+
--

```bash
kubectl exec redpanda-0 --namespace <namespace> -c redpanda -- \
  rpk cluster health \
    -X admin.hosts=<broker-url>:<admin-api-port> \
```

--
====
+
Example output:
+
[,plain,role=no-copy]
----
CLUSTER HEALTH OVERVIEW
=======================
Healthy:               true
Controller ID:         0
All nodes:             [0 2 1]
Nodes down:            []
Leaderless partitions: []
----
+
[NOTE]
====
You can also evaluate xref:./monitor.adoc[external metrics] to determine cluster health.
If the cluster has any issues, take the broker out of maintenance mode by running the following command before proceeding with other operations,
such as decommissioning or retrying the rolling upgrade:

```bash
rpk cluster maintenance disable <node-id>
```
====

. Delete the Pod in which the broker was running:
+
```bash
kubectl delete pod redpanda-0 --namespace <namespace>
```

. When the Pod restarts, make sure that it's now running the upgraded version of Redpanda:
+
[tabs]
====
TLS Enabled::
+
--

```bash
kubectl exec redpanda-0 --namespace <namespace> -c redpanda -- \
  rpk redpanda admin brokers list \
    --admin-api-tls-enabled \
    --admin-api-tls-truststore <path-to-admin-api-ca-certificate> \
    -X admin.hosts=<broker-url>:<admin-api-port>
```

--
TLS Disabled::
+
--

```bash
kubectl exec redpanda-0 --namespace <namespace> -c redpanda -- \
  rpk redpanda admin brokers list \
    -X admin.hosts=<broker-url>:<admin-api-port> \
```

--
====

. Repeat this process for all the other brokers in the cluster.

=== Verify that the upgrade was successful

When you've upgraded all brokers, verify that the cluster is healthy. If the cluster is unhealthy, the upgrade may still be in progress. Try waiting a few moments, then run the command again.

[tabs]
====
TLS Enabled::
+
--

```bash
kubectl exec redpanda-0 --namespace <namespace> -c redpanda -- \
  rpk cluster health \
    --admin-api-tls-enabled \
    --admin-api-tls-truststore <path-to-admin-api-ca-certificate> \
    -X admin.hosts=<broker-url>:<admin-api-port>
```

--
TLS Disabled::
+
--

```bash
kubectl exec redpanda-0 --namespace <namespace> -c redpanda -- \
  rpk cluster health \
    -X admin.hosts=<broker-url>:<admin-api-port> \
```

--
====

Example output:

[,plain,role=no-copy]
----
CLUSTER HEALTH OVERVIEW
=======================
Healthy:               true
Controller ID:         1
All nodes:             [2,1,0]
Nodes down:            []
Leaderless partitions: []
----

== Rollbacks

If something does not go as planned during a rolling upgrade, you can roll back to the original version as long as you have not upgraded every broker.
The StatefulSet uses the `RollingUpdate` strategy by default in xref:reference:redpanda-helm-spec.adoc#statefulsetupdatestrategytype[`statefulset.updateStrategy.type`],
which means all Pods in the StatefulSet are restarted in reverse-ordinal order. For details, see the https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#update-strategies[Kubernetes documentation].

. Find the previous revision:
+
```bash
helm history redpanda --namespace <namespace>
```
+
Example output
+
[,plain,role=no-copy]
----
REVISION	UPDATED                 	STATUS    	CHART          	APP VERSION	DESCRIPTION
1       	Fri Mar  3 15:16:24 year	superseded	redpanda-2.12.2	v22.3.13   	Install complete
2       	Fri Mar  3 15:19:41 year	deployed	  redpanda-2.12.2	v22.3.13   	Upgrade complete
----

. Roll back to the previous revision:
+
```bash
helm rollback redpanda <previous-revision> --namespace <namespace>
```

. Verify that the cluster is healthy. If the cluster is unhealthy, the upgrade may still be in progress. Try waiting a few moments, then run the command again.
+
[tabs]
====
TLS Enabled::
+
--

```bash
kubectl exec redpanda-0 --namespace <namespace> -c redpanda -- \
  rpk cluster health \
    --admin-api-tls-enabled \
    --admin-api-tls-truststore <path-to-admin-api-ca-certificate> \
    -X admin.hosts=<broker-url>:<admin-api-port>
```

--
TLS Disabled::
+
--

```bash
kubectl exec redpanda-0 --namespace <namespace> -c redpanda -- \
  rpk cluster health \
    -X admin.hosts=<broker-url>:<admin-api-port> \
```

--
====
+
Example output:
+
[,plain,role=no-copy]
----
CLUSTER HEALTH OVERVIEW
=======================
Healthy:               true
Controller ID:         1
All nodes:             [2,1,0]
Nodes down:            []
Leaderless partitions: []
----

== Suggested reading

Set up a real-time dashboard to monitor your cluster health, see xref:./monitor.adoc[Monitor Redpanda].