= Redpanda Cloud API Quickstart
:description: Learn how to quickly start using the Cloud API to manage clusters and other resources.
:page-cloud: true
:page-api: cloud
:page-beta: true

The following steps describe how to authenticate with the Cloud API and create a new Redpanda cluster. For more information on the Cloud API, see the xref:manage:api/cloud-api-overview.adoc[Redpanda Cloud API Overview].

== Create a new cluster

. xref:manage:api/cloud-api-authentication.adoc[Authenticate to the API].
. Create a resource group by making a xref:api:ROOT:cloud-api.adoc#post-/v1beta2/resource-groups[`POST /v1beta2/resource-groups`] request.
. Create a network by making a xref:api:ROOT:cloud-api.adoc#post-/v1beta2/networks[`POST /v1beta2/networks`] request. Note that this operation may be long-running.
. Create a cluster by making a xref:api:ROOT:cloud-api.adoc#post-/v1beta2/clusters[`POST /v1beta2/clusters`] request.
. For BYOC, run `rpk cloud byoc`, passing the `metadata.cluster_id` from the Create Cluster response as a flag:
+
GCP:
+
```bash
rpk cloud byoc gcp apply --redpanda-id=<metadata.cluster_id> --project-id=<gcp-project-id>
```
+
AWS:
+
```bash
rpk cloud byoc aws apply --redpanda-id=<metadata.cluster_id>
```

== Try the Cloud API

You can issue requests against the Cloud API from your browser when viewing the xref:api:ROOT:cloud-api.adoc[API reference]. 

Complete the following steps:

. Go to *Authentication* in the sidebar.
. Click *Get Token*.
. If successful, the text “1 API key applied” displays under the *Authentication* section of this page. The token is valid for an hour.
. Choose the correct API server for your request.

WARNING: Your API requests are executed against your actual environment and data, not a sandbox. 

=== Make a request to the Control Plane API

For requests to the Control Plane API endpoints:

. Click *API Servers* in the sidebar. 
. Select “https://api.redpanda.com - Control Plane API”. 
. From the Control Plane API endpoints, you can make a request by using the *Try* option. Make sure to enter any required parameter values, and provide the request body object if necessary.

=== Make a request to the Data Plane APIs

For requests to the Data Plane API endpoints: 

. Make a Get Cluster request for your target cluster.
. The Get Cluster response contains the Data Plane API URL. Copy the value of `dataplane_api.url` from the response body. 
. Click *API Servers* in the sidebar and select “\{dataplane_api_url} - Data Plane API”.
. Paste the URL into the `dataplane_api_url` input field.
. From the Data Plane API endpoints, you can make a request by using the *Try* option. Make sure to enter any required parameter values, and provide the request body object if necessary.

== See also

- xref:manage:api/cloud-controlplane-api.adoc[Use the Control Plane API]
- xref:manage:api/cloud-dataplane-api.adoc[Use the Data Plane APIs]