= Configure Role-based Access Control
:description: Role-based access controls provide an alternative to ACLs for managing permissions.
:page-categories: Management, Security

Role-based Access Control (RBAC) provides a way to configure permissions for provisioned users at scale. RBAC allows you to manage access for many users to many resources with a streamlined interface. This mechanism works in conjunction with all supported authentication methods.

IMPORTANT: At present, Redpanda only supports RBAC for self-hosted clusters.

== RBAC

RBAC is designed to address the critical challenge of access management at scale. It alleviates the process of manually maintaining and verifying a set of raw permissions (ACLs) for a user base that may contain thousands of users. RBAC provides you with a method to onboard new employees easier, audit accesses faster, and adapt more readily to evolutions of usage and compliance needs.

Using RBAC, you can define roles to reflect organizational structure or job duties to gives a coherent approach to access management. This approach decouples users and permissions through the assignment of roles. This allows a one to many mapping of a given role to many users, thereby dramatically reducing the number of custom policies needed for a resource from one per user to one per group of users.

image::../../../../shared/images/rbac-overview[RBAC multiplicity]

=== RBAC terminology

Under the RBAC framework, you create *roles*, grant *permissions* to those roles, and assign the roles to *users*. When you change the permissions for a given role, all principals with that role automatically gain the modified permissions. You grant or deny permissions for a role by creating an ACL and specifying the RBAC role as the allowed or denied principal respectively.

==== Roles

A role is a named collection of ACLs which can be assigned to zero or more users. Redpanda provides two default roles, `user` and `admin`:

* `user` - All authorized users have this role by default. There are no ACLs assigned to this role until you add them. This means users have no permissions to interact with any resources you add to your Redpanda cluster until you add relevant permissions to this or another role.
* `admin` - By default, no users have this role. The default admin role provides full access to all resources in your Redpanda installation.

==== Policy conflicts

You may assign both ACLs and roles to any given principal. ACLs can have either/or allow and deny permissions. As a result, users may at times have conflicting policies. If this situation arises, the user is permitted to perform an operation if and only if:

* There does not exist a DENY permission matching the operation.
* There exists an ALLOW permission matching the operation.

== Managing users and roles

Redpanda allows you to manage your RBAC configurations through both RPK and the web console. Examples of each are given here.

=== Create a role

Creating a new role is a two-step process. First you define the role, giving it a unique and descriptive name. Second, assign that role as the allowed or denied principal to one or more ACLs. This defines the permissions associated with the role.

==== Using Console

Administrators can create a role by:

1. Select the _Access Control_ tab then select the _Roles_ tab.

2. Click the _Create Role_ button.

3. Using the _Create Role_ form, provide a name for the role and assign one or more ACLs which will be inherited by all role members.

==== Using RPK

Using RPK, administrators create a new role by issuing the command:

[,bash]
----
rpk role create [ROLE_NAME]
----

Once the role is created, administrators assign the role as the allowed principal for one or more ACLs. You can modify existing ACLs or create new ones. For example:

[,bash]
----
rpk acl create ... --allow-principal Role:[ROLE_NAME]
----

=== Delete a role

When a role is deleted, Redpanda carries out the following actions automatically:

- All role ACLs are deleted.
- All users are unassigned from role.

==== Using Console

Administrators can delete a role by:

1. Select the _Access Control_ tab.

2. Click the role name to be deleted.

3. Click the “Delete Role” button.

==== Using RPK

Using RPK, administrations delete a role by issuing the command:

[,bash]
----
rpk role delete [ROLE_NAME]
----

=== Assign a role

Administrators may assign a role to any principal created in their Redpanda instance. A principal is composed of two parts: a type and a name. Redpanda currently supports the `User` type only for principals. All principals, therefore, will have the format of `User:[name]`

==== Using Console

Administrators have two options for assigning roles.

*Option 1*

1. Select the _Access Control_ tab.

2. Click the role name to assign.

3. Click the _Edit Role_ button.

4. Using the _Edit Role_ view, find and assign one or more user to the role.

*Option 2*

1. Select the _Access Control_ tab.

2. Click the user you wish to assign to one or more roles.

3. Click the _Edit User_ button.

4. Using the _Edit User_ view, find and assign one or more roles to the user.

==== Using RPK

Using RPK, administrations assign a role to a principal by issuing the command:

[,bash]
----
rpk role assign [ROLE_NAME] [PRINCIPAL]
----

=== Unassign a role

Administrators may remove a role from a principal without deleting the role. A principal is composed of two parts: a type and a name. Redpanda currently supports the `User` type only for principals. All principals, therefore, will have the format of `User:[name]`

==== Using Console

Administrators have two options for assigning roles.

*Option 1*

1. Select the _Access Control_ tab.

2. Click the role name to assign.

3. Click the _Edit Role_ button.

4. Using the _Edit Role_ view, find and unassign one or more user from the role.

*Option 2*

1. Select the _Access Control_ tab.

2. Click the user you wish to assign to one or more roles.

3. Click the _Edit User_ button.

4. Using the _Edit User_ view, find and unassign one or more roles from the user.

==== Using RPK

Using RPK, administrators unassign a role from a principal issuing the command:

[,bash]
----
rpk role unassign [ROLE_NAME] [PRINCIPAL]
----

=== Edit a Role

After a role is created, administrators may still add additional ACLs to the role. Redpanda also allows renaming a role.

==== Using Console

1. Select the _Access Control_ tab.

2. Click the role name to assign.

3. Click the _Edit Role_ button.

4. Using the _Edit Role_ view, change the role name or edit the list of ACLs assigned to the role.

5. Click “Save” when done.

==== Using PRK

Using RPK, Administrators may rename a role by issuing the command:

[,bash]
----
rpk role edit [ROLE_NAME] --rename [NEW_NAME]
----

Using RPK, Administrators may assign the role as the allowed principal for additional ACLs. You can modify existing ACLs or create new ones. For example:

[,bash]
----
rpk acl create ... --allow-role [ROLE_NAME]
----

=== List Roles

Administrators may view a list of all roles within their Redpanda installation.

==== Using Console

1. Select the _Access Control_ tab.

2. Select the _Roles_ tab.

3. Review the list of all roles.

==== Using RPK

Using RPK, administrators can view a list of all actives roles by issuing the command:

[,bash]
----
rpk role list
----

=== View Role Membership

Administrators may view all principals with a given role assignment.

==== Using Console

1. Select the _Access Control_ tab.

2. Click the role name.

3. Find the list of users at the bottom of the _View Role_ view.

==== Using RPK

Using RPK, administrators can view the membership of a given role by issuing the command:

[,bash]
----
rpk role users [ROLE_NAME]
----
