= rpk cluster txn describe
:description: rpk cluster txn describe

Describe transactional IDs.

This command, in comparison to 'list', is a more detailed per-transaction view
of transactional IDs. In addition to the state and producer ID, this command
also outputs when a transaction started, the epoch of the producer ID, how long
until the transaction times out, and the partitions currently a part of the
transaction. For information on what the columns in the output mean, see
'rpk cluster txn --help'.

By default, all topics in a transaction are merged into one line. To print a
row per topic, use --format=long. To include partitions with topics, use
--print-partitions; --format=json/yaml will return the equivalent of the long
format with print partitions included.

If no transactional IDs are requested, all transactional IDs are printed.

== Usage

[,bash]
----
rpk cluster txn describe [TXN-IDS...] [flags]
----

== Flags

[cols="1m,1a,2a]
|===
|*Value* |*Type* |*Description*

|`-h, --help` |- |Help for describe.

|`-p, --print-partitions` |- |Include per-topic partitions that are in the transaction.

|`--config` |string |Redpanda or rpk config file; default search paths are ~/.config/rpk/rpk.yaml, $PWD, and /etc/redpanda/`redpanda.yaml`.

|`-X, --config-opt` |stringArray |Override rpk configuration settings; '-X help' for detail or '-X list' for terser detail.

|`--format` |string |Output format (json,yaml,text,wide,help) (default "text").

|`--profile` |string |rpk profile to use.

|`-v, --verbose` |- |Enable verbose logging.
|===