= rpk transform list
:description: rpk transform list

List data transforms.

This command lists all data transforms in a cluster, as well as showing the
state of a individual transform processor, such as if it's errored or how many
records are pending to be processed (lag).

There is a processor assigned to each partition on the input topic, and each
processor is a separate entity that can make progress or fail independently.

The --detailed flag (-d) opts in to printing extra per-processor information.

== Usage

[,bash]
----
rpk transform list [flags]
----

== Aliases

[,bash]
----
list, ls
----

== Flags

[cols="1m,1a,2a]
|===
|*Value* |*Type* |*Description*

|`-d, --detailed` |- |Print per-partition information for data transforms.

|`--format` |string |Output format (json,yaml,text,wide,help) (default "text").

|`-h, --help` |- |Help for list.

|`--config` |string |Redpanda or rpk config file; default search paths are ~/.config/rpk/rpk.yaml, $PWD, and /etc/redpanda/`redpanda.yaml`.

|`-X, --config-opt` |stringArray |Override rpk configuration settings; '-X help' for detail or '-X list' for terser detail.

|`--profile` |string |rpk profile to use.

|`-v, --verbose` |- |Enable verbose logging.
|===