= rpk transform build
:description: rpk transform build

Build a transform.

This command looks in the current working directory for a transform.yaml file.
It installs the appropriate build plugin, then builds a .wasm file.

When invoked, it passes extra arguments directly to the underlying toolchain.

For example to add debug symbols for tinygo:

  rpk transform build -- -no-debug=false

LANGUAGES

Tinygo - By default tinygo are release builds (-opt=2) for maximum performance.

== Usage

[,bash]
----
rpk transform build [flags]
----

== Flags

[cols="1m,1a,2a]
|===
|*Value* |*Type* |*Description*

|`-h, --help` |- |Help for build.

|`--config` |string |Redpanda or rpk config file; default search paths are ~/.config/rpk/rpk.yaml, $PWD, and /etc/redpanda/`redpanda.yaml`.

|`-X, --config-opt` |stringArray |Override rpk configuration settings; '-X help' for detail or '-X list' for terser detail.

|`--profile` |string |rpk profile to use.

|`-v, --verbose` |- |Enable verbose logging.
|===