= rpk cluster logdirs describe
:description: rpk cluster logdirs describe

Describe log directories on Redpanda brokers.

This command prints information about log directories on brokers, particularly,
the base directory that topics and partitions are located in, and the size of
data that has been written to the partitions. The size you see may not exactly
match the size on disk as reported by du: Redpanda allocates files in chunks.
The chunks will show up in du, while the actual bytes so far written to the
file will show up in this command.

The directory returned is the root directory for partitions. Within Redpanda,
the partition data lives underneath the the returned root directory in

    kafka/{topic}/{partition}_{revision}/

where revision is a Redpanda internal concept.

== Usage

[,bash]
----
rpk cluster logdirs describe [flags]
----

== Flags

[cols="1m,1a,2a]
|===
|*Value* |*Type* |*Description*

|`--aggregate-into` |string |If non-empty, what column to aggregate into starting from the partition column (broker, dir, topic).

|`-b, --broker` |int32 |If non-negative, the specific broker to describe (default -1).

|`-h, --help` |- |Help for describe.

|`-H, --human-readable` |- |Print the logdirs size in a human-readable form.

|`--sort-by-size` |- |If true, sort by size.

|`--topics` |strings |Specific topics to describe.

|`--config` |string |Redpanda or rpk config file; default search paths are ~/.config/rpk/rpk.yaml, $PWD, and /etc/redpanda/`redpanda.yaml`.

|`-X, --config-opt` |stringArray |Override rpk configuration settings; '-X help' for detail or '-X list' for terser detail.

|`--profile` |string |rpk profile to use.

|`-v, --verbose` |- |Enable verbose logging.
|===