= rpk cluster config list
:description: rpk cluster config list

List cluster configuration properties.

This command lists all available cluster configuration properties. Use the 'get'
command to retrieve specific property values, or 'edit' for interactive editing.

Use the --filter flag with a regular expression to filter configuration keys.

== Usage

[,bash]
----
rpk cluster config list [flags]

Examples:

List all cluster configuration properties:
  rpk cluster config list

List configuration properties matching a filter:
  rpk cluster config list --filter="kafka.*"

List configuration properties in JSON format:
  rpk cluster config list --format=json

List configuration properties in YAML format:
  rpk cluster config list --format=yaml
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|--filter |string |Filter configuration keys using regular expression.

|--format |string |Output format (json,yaml,text,wide,help) (default "text").

|-h, --help |- |Help for list.

|--all |- |Include all properties, including tunables.

|--config |string |Redpanda or rpk config file; default search paths are `/var/lib/redpanda/.config/rpk/rpk.yaml`, `$PWD/redpanda.yaml`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override rpk configuration settings; '-X help' for detail or '-X list' for terser detail.

|--profile |string |rpk profile to use.

|-v, --verbose |- |Enable verbose logging.
|===