= rpk cluster self-test status
:description: rpk cluster self-test status

Returns the status of the current running tests or the cached results of the last completed run.

Use this command after invoking 'self-test start' to determine the status of
the jobs launched. Possible results are:

* One or more jobs still running
  * Returns the IDs of Redpanda brokers (nodes) still running self-tests.

* No jobs running:
  * Returns the cached results for all brokers of the last completed test.

Test results are grouped by broker ID. Each test returns the following:

* Name: Description of the test.
* Info: Details about the test run attached by Redpanda.
* Type: Either 'disk', 'network', or 'cloud' test.
* Test Id: Unique identifier given to jobs of a run. All IDs in a test should match. If they don't match, then newer and/or older test results have been included erroneously.
* Timeouts: Number of timeouts incurred during the test.
* Start time: Time that the test started, in UTC.
* End time: Time that the test ended, in UTC.
* Avg Duration: Duration of the test.
* IOPS: Number of operations per second. For disk, it's 'seastar::dma_read' and 'seastar::dma_write'. For network, it's 'rpc.send()'.
* Throughput: For disk, throughput rate is in bytes per second. For network, throughput rate is in bits per second. Note that GiB vs. Gib is the correct notation displayed by the UI.
* Latency: 50th, 90th, etc. percentiles of operation latency, reported in microseconds (μs). Represented as P50, P90, P99, P999, and MAX respectively.
If Tiered Storage is not enabled, the cloud storage tests won't run and a warning will be displayed showing "Cloud storage is not enabled.". All results will be shown as 0.

== Usage

[,bash]
----
rpk cluster self-test status [flags]
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|--format |string |Output format (text, json) (default "text").

|-h, --help |- |Help for status.

|--config |string |Redpanda or rpk config file; default search paths are `/var/lib/redpanda/.config/rpk/rpk.yaml`, `$PWD/redpanda.yaml`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override rpk configuration settings; '-X help' for detail or '-X list' for terser detail.

|--profile |string |rpk profile to use.

|-v, --verbose |- |Enable verbose logging.
|===