= rpk cluster storage mount
:description: rpk cluster storage mount

Mount a topic to the Redpanda cluster from Tiered Storage.

This command mounts a topic in the Redpanda cluster using log segments stored
in Tiered Storage. The topic may be optionally renamed with the --to flag.

Requirements:
- Tiered Storage must be enabled.
- Log segments for the topic must be available in Tiered Storage.
- A topic with the same name must not already exist in the cluster.

== Usage

[,bash]
----
rpk cluster storage mount [TOPIC] [flags]

Examples:

Mounts topic my-typic from Tiered Storage to the cluster in the my-namespace
	rpk cluster storage mount my-topic

Mount topic my-topic from Tiered Storage to the cluster in the my-namespace 
with my-new-topic as the new topic name
	rpk cluster storage mount my-namespace/my-topic --to my-namespace/my-new-topic
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-h, --help |- |Help for mount.

|--to |string |New namespace/topic name for the mounted topic (optional).

|--config |string |Redpanda or rpk config file; default search paths are `/var/lib/redpanda/.config/rpk/rpk.yaml`, `$PWD/redpanda.yaml`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override rpk configuration settings; '-X help' for detail or '-X list' for terser detail.

|--profile |string |rpk profile to use.

|-v, --verbose |- |Enable verbose logging.
|===