= Availability
:description: Learn how Redpanda Cloud supports deploying Redpanda clusters in single or multiple availability zones (AZs).
:page-cloud: true

Redpanda Cloud supports the deployment of Redpanda clusters in single or multiple
availability zones (AZs), spanning at most three AZs. Brokers are evenly distributed
across AZs, and xref:ROOT:reference:cluster-properties.adoc#default_topic_replications[default_topic_replications]
is set to `3` by default. Data is evenly distributed across AZs automatically. This behavior is
known as glossterm:rack awareness[].

To prevent downtime during cluster upgrades, the Redpanda Cloud
cluster operator upgrades one broker at a time. It
waits for the health of the cluster to return to its nominal state before
continuing with the next broker upgrade, until all brokers are fully rolled out.

Redpanda's Support, Security, and Site Reliability Engineering (SRE) teams monitor
Redpanda Cloud clusters 24/7 to ensure they meet availability service level
agreements (SLAs). If incidents occur, teams at Redpanda trigger an incident
response process to quickly mitigate them.
