= rpk cloud auth delete
:description: rpk cloud auth delete

Delete an rpk cloud authentication.

Deleting a cloud authentication removes it from the rpk.yaml file. If the
deleted auth was the current authentication, rpk will use a default SSO auth the
next time you try to login and save that auth.

If you delete an authentication that is used by profiles, affected profiles have
their authentication cleared and you will only be able to access the profile's
cluster using SASL credentials.

== Usage

[,bash]
----
rpk cloud auth delete [NAME] [flags]
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-h, --help |- |Help for delete.

|--config |string |Redpanda or rpk config file; default search paths are `/var/lib/redpanda/.config/rpk/rpk.yaml`, `$PWD/redpanda.yaml`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override rpk configuration settings; '-X help' for detail or '-X list' for terser detail.

|--profile |string |rpk profile to use.

|-v, --verbose |- |Enable verbose logging.
|===