processor:
  # RE2 regular expressions describing types that should be excluded from the generated documentation.
  ignoreTypes:
    - "User$"
    - "UserList$"
    - "UserSpec$"
    - "UserStatus$"
    - "UserAuthenticationSpec$"
    - "UserAuthorizationSpec$"
    - "UserTemplateSpec$"
    - "Password$"
    - "PasswordSource$"
    - "ACLRule$"
    - "ACLType$"
    - "ACLOperation$"
    - "PatternType$"
    - "ResourceType$"
    - "ACLResourceSpec$"
    - "ClusterSource$"
    - "AdminAPISpec$"
    - "AdminSASL$"
    - "MetadataTemplate$"
render:
  kubernetesVersion: 1.23
  knownTypes:
    - name: SecretObjectReference
      package: sigs.k8s.io/gateway-api/apis/v1beta1
      link: https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.SecretObjectReference