= Add a License Key to Redpanda Console
:description: Learn how to apply or update a license key to Redpanda Console.

To enable xref:get-started:licensing/overview.adoc#console[enterprise features for Redpanda Console], it must have an Enterprise Edition license to load at startup. This guide explains how to configure Redpanda Console to load the license key from its local configuration.

TIP: Redpanda Console can also load the license key from a connected Redpanda cluster. To add a license key to Redpanda, see xref:get-started:licensing/add-license-redpanda/index.adoc[].

== Prerequisites

You must have an Enterprise Edition license. If you don't have a license yet, https://www.redpanda.com/contact[request one^].

If Redpanda Console has enterprise features enabled and it cannot find a valid license either locally or in the connected Redpanda cluster, it shuts down. See xref:get-started:licensing/overview.adoc[].

== Add a new license to Redpanda Console

To add a new license to Redpanda Console, you have two options:

- <<file, Provide the path to the license file>>.
- <<inline, Provide the license key contents directly>>.

[[file]]
=== Use a license file

Specify the path to the license file in one of the following ways:

- Set the `redpanda.licenseFilepath` property in the `/etc/redpanda/redpanda-console-config.yaml` configuration file:
+
```yaml
redpanda:
  licenseFilepath: <path-to-license-file>
```
- Set the `REDPANDA_LICENSE_FILEPATH` environment variable:
+
```bash
export REDPANDA_LICENSE_FILEPATH=<path-to-license-file>
```

[[inline]]
=== Use the license key contents directly

If you don't want to provide a path to the license file, you can use the contents of the license key directly in one of the following ways:

- Set the `redpanda.license` property in the `/etc/redpanda/redpanda-console-config.yaml` configuration file:
+
```yaml
redpanda:
  license: <license-key-contents>
```

- Set the `REDPANDA_LICENSE` environment variable:
+
```yaml
export REDPANDA_LICENSE=<license-key-contents>
```

== Update an existing license

To update an existing license:

. Update your configuration file or environment variables with one of the following:

- <<file, The path to your new license file>>
- <<inline, The contents of your new license key>>

. Restart Redpanda Console to make the changes take effect.

== Next steps

xref:get-started:licensing/monitor-license-status.adoc[].

== Suggested reading

- xref:get-started:licensing/index.adoc[]
- xref:console:ui/add-license.adoc[]
