= Add a License Key to Redpanda Console
:description: Learn how to apply or update a license key to Redpanda Console.
:page-context-switcher: [{"name": "Redpanda Console v2.x", "to": "24.3@ROOT:console:config/enterprise-license.adoc" },{"name": "Redpanda Console v3.x", "to": "current" } ]

include::console:partial$operator-console-version-note.adoc[]

To enable xref:get-started:licensing/overview.adoc#console[enterprise features for Redpanda Console], you must have an Enterprise Edition license to load at startup. This guide explains how to configure Redpanda Console to load the license key from its local configuration.

TIP: This option is best for deployments that are not connected to a Redpanda cluster. If you plan to connect Redpanda Console to a Redpanda cluster, consider uploading the license to the Redpanda cluster. See xref:get-started:licensing/add-license-console.adoc[].

== Prerequisites

You must have an Enterprise Edition license. To get a trial license key or extend your trial period, https://redpanda.com/try-enterprise[generate a new trial license key^]. To purchase a license, contact https://redpanda.com/upgrade[Redpanda Sales^].

If Redpanda Console has enterprise features enabled and cannot find a valid license locally or in the connected Redpanda cluster, it shuts down. See xref:get-started:licensing/overview.adoc[].

== Add a new license to Redpanda Console

To add a new license to Redpanda Console, you have two options:

- <<file, Provide the path to the license file>>.
- <<inline, Provide the license key contents directly>>.

[[file]]
=== Use a license file

[tabs]
======
Standalone::
+
--
Set the `licenseFilepath` property in the `/etc/redpanda/redpanda-console-config.yaml` configuration file:

```yaml
licenseFilepath: <path-to-license-file>
```

Or set the `REDPANDA_LICENSE_FILEPATH` environment variable:

```bash
export REDPANDA_LICENSE_FILEPATH=<path-to-license-file>
```
--

Kubernetes embedded::

--
By default, when deploying Console with the Redpanda Operator or Redpanda Helm chart, Console inherits the license provided to Redpanda in `enterprise.license` or `enterprise.licenseSecretRef`. See xref:get-started:licensing/add-license-redpanda/kubernetes.adoc[] for details.

You cannot override the inherited license.

--
Kubernetes standalone::
+
--
For production deployments, the safest and most secure way to provide your license is to store it in a Kubernetes Secret and reference it using `enterprise.licenseSecretRef` in your `values.yaml`. This keeps sensitive license data out of your Helm values and version control. Example:

```yaml
enterprise:
  licenseSecretRef:
    name: <your-license-secret-name>
    key: <your-license-key-field>
```

Alternatively, you can set the license directly in your Helm values using `console.config.license` or `console.config.licenseFilepath`, or with environment variables, but these methods are less secure for production environments.

```yaml
console:
  extraEnv:
    - name: REDPANDA_LICENSE
      value: <license-key-contents>
```

Apply with:

```bash
helm upgrade --install redpanda-console redpanda/console -f values.yaml
```
--
======

[[inline]]
=== Use the license key contents directly

If you don't want to provide a path to the license file, you can use the contents of the license key directly.

[tabs]
======
Standalone::
+
--
Set the `license` property in the `/etc/redpanda/redpanda-console-config.yaml` configuration file:

```yaml
license: <license-key-contents>
```

Or set the `REDPANDA_LICENSE` environment variable:

```bash
export REDPANDA_LICENSE=<license-key-contents>
```
--


Kubernetes embedded::

--
By default, when deploying Console with the Redpanda Operator or Redpanda Helm chart, Console inherits the license provided to Redpanda in `enterprise.license` or `enterprise.licenseSecretRef`. See xref:get-started:licensing/add-license-redpanda/kubernetes.adoc[] for details.

You cannot override the inherited license.
--
Kubernetes standalone::
+
--
For production deployments, the safest and most secure way to provide your license is to store it in a Kubernetes Secret and reference it using `enterprise.licenseSecretRef` in your `values.yaml`. This keeps sensitive license data out of your Helm values and version control. Example:

```yaml
enterprise:
  licenseSecretRef:
    name: <your-license-secret-name>
    key: <your-license-key-field>
```

Alternatively, you can set the license directly in your Helm values using `console.config.license` or `console.config.licenseFilepath`, or with environment variables, but these methods are less secure for production environments.

```yaml
console:
  extraEnv:
    - name: REDPANDA_LICENSE
      value: <license-key-contents>
```

Apply with:

```bash
helm upgrade --install redpanda-console redpanda/console -f values.yaml
```
--
======

== Update an existing license

To update an existing license:

. Update your configuration file or environment variables with one of the following:

- <<file, The path to your new license file>>
- <<inline, The contents of your new license key>>

. Restart Redpanda Console to make the changes take effect.

== Next steps

xref:get-started:licensing/monitor-license-status.adoc[].

== Suggested reading

- xref:get-started:licensing/index.adoc[]
- xref:console:ui/add-license.adoc[]
