= What's New in 23.3 Beta
:description: Summary of new features and updates in the release.

This topic includes new content added in version 23.3 Beta. 

== OIDC authentication

You can xref:manage:security/authentication.adoc#enable-oidc[enable OIDC] so that Redpanda can delegate the authentication process to an external identity provider (IdP) such as Okta, Azure AD, or on-premise Active Directory Federation Service (AD FS). When you enable OIDC, Redpanda does not need to manage user credentials directly, but can instead rely on the trusted authentication capabilities of IdPs. Redpanda's implementation of OIDC provides SASL/OAUTHBEARER support for the Kafka API, and enables standard OIDC authentication across the Schema Registry, HTTP Proxy, and Admin APIs.

== Audit logging 

Redpanda's xref:manage:audit-logging.adoc[audit logging] supports fine-grained reporting of events in the Kafka, HTTP Proxy, Schema Registry, and Admin APIs. Events include:

* Changes to clusters, users, topics, ACLs, or consumer groups
* Any time a user is authenticated
* Any time a topic is written to or read from (requires explicit opt-in)
* HTTP requests for the Schema Registry, HTTP Proxy, and Admin APIs

You can persistently store auditing events to a topic in an append-only fashion, which guarantees retention for the requested time period, even against Redpanda administrators. Auditing is compatible with the Open Cybersecurity Schema Framework (OCSF) and works with industry-standard tools, such as Splunk, Sumo Logic, and AWS.

== Data transforms

Redpanda now provides the framework to build and deploy inline transformations (xref:develop:data-transforms/index.adoc[data transforms]) on data written to Redpanda topics, delivering processed and validated data to consumers in the format they expect. For example, you may have consumers that require you to redact credit card numbers or convert JSON to Avro. Data transforms use WebAssembly (Wasm) engines inside a broker, which eliminates the need to manage a separate stream processing environment or use third-party tools.

== New commands

New commands and properties in this release include the following:

- xref:reference:rpk/rpk-registry/rpk-registry.adoc[`rpk registry`]: This includes commands to interact with the Schema Registry.
- xref:reference:rpk/rpk-transform/rpk-transform.adoc[`rpk transform`]: This includes commands to develop, deploy, and manage data transforms.

== Next steps

* xref:get-started:install-beta.adoc[]


