= Redpanda Licensing
:description: Redpanda is free and source-available at the Redpanda GitHub repo. Additional features are included with an enterprise license.

Redpanda Community Edition is free and source-available at the https://github.com/redpanda-data/redpanda[Redpanda GitHub repo]. Additional features are included with a license for Redpanda Enterprise Edition.

== Redpanda Community Edition

Redpanda Community Edition is licensed with the Redpanda https://github.com/redpanda-data/redpanda/blob/dev/licenses/bsl.md[Business Source License (BSL)]. These core features are free and source-available.

[NOTE]
====
* Users cannot provide Redpanda as a commercial streaming or queuing service to others.
* The BSL code converts to Apache 2.0 licensing four years after each code merge.
====

== Redpanda Enterprise Edition

Redpanda Enterprise Edition is licensed with the https://github.com/redpanda-data/redpanda/blob/dev/licenses/rcl.md[Redpanda Community License (RCL)]. It includes the free features licensed under the Redpanda BSL, as well as the following features:

* xref:data-management:tiered-storage.adoc[Tiered Storage]
* xref:data-management:data-archiving.adoc[Data Archiving]
* xref:cluster-administration:continuous-data-balancing.adoc[Continuous Data Balancing]
* xref:data-management:remote-read-replicas.adoc[Remote Read Replica]
* xref:console:single-sign-on/authentication.adoc[Redpanda Console single sign-on authentication]
* xref:console:single-sign-on/authorization.adoc[Redpanda Console role-based access control]

Enterprise features require a license key. You can evaluate enterprise features with a free 30-day trial. Contact https://redpanda.com/try-redpanda?section=enterprise-trial[Redpanda Sales] to request a trial license, to extend your trial period, or to purchase an Enterprise Edition license.

=== Apply license key

A license key unlocks Redpanda Enterprise Edition features. To apply the license key to your cluster, run:

`rpk cluster license set`

Either provide a path to a file containing the license, or provide the license string inline. For example, run:

`rpk cluster license set --path /home/organization/redpanda.license --api-urls 0.0.0.0:9645`

or

`rpk cluster license set <license string>`

If neither the path or the license string are are provided, `rpk` looks for the license in `/etc/redpanda/redpanda.license`.

=== Check license status

To check the status of your current license, run:

`rpk cluster license info --api-urls 0.0.0.0:9645`

Redpanda sends warning messages in the cluster logs if you enable enterprise features without a valid license key.
