= Technical Preview
:description: Redpanda continuously adds new features and feature updates. Some of these features are designated as technical preview.

== What is a technical preview feature?

Redpanda continuously adds new features and feature updates. Some of these features are designated as _technical preview_, and serve to provide feedback in development and testing environments.

We welcome your feedback, as it helps shape the future of the Redpanda platform. Keep in mind that technical preview features are subject to change and may not become available in future releases.

:::caution
Technical preview features are not supported for production usage.
:::

== Features currently in technical preview

Here is the list of the current features in technical preview and their respective versions. Some features in technical preview are only available through beta versions.

[cols=3*]
|===
| +++<strong>+++Technical Preview Feature +++</strong>+++
| +++<strong>+++Version in Technical Preview +++</strong>+++
| +++<strong>+++Version in General Availability +++</strong>+++

| https://docs.redpanda.com/docs/data-management/data-transform/[Data transformation with WebAssembly]
| v 21.12.1-wasm-beta1
| -

| https://docs.redpanda.com/docs/platform/data-management/tiered-storage/[Tiered Storage]
| v 21.11.3
| v 22.1.1 and later

| Transactions API
| v 21.8.1 and later
| -
|===
