= Manage Redpanda Console
:description: Manage Redpanda Console

* xref:console:kafka-connect.adoc[Kafka Connect]
+
Redpanda Console provides a user interface to manage multiple Kafka connect clusters.

* xref:console:schema-registry.adoc[Schema Registry]
+
Configure Redpanda Console to deserialize Kafka records that were encoded by a Schema Registry compatible serializer.

* xref:console:protobuf.adoc[Protobuf Deserialization]
+
For topics that contain Protobuf serialized messages, you can configure Redpanda Console to deserialize
  the binary content into JSON, which makes the message human-readable.

* xref:console:topic-documentation.adoc[Topic Documentation]
+
Embed your topic's documentation into Redpanda Console by providing access to a GitHub repository that hosts your documentation files in Markdown.

* xref:console:http-path-rewrites.adoc[HTTP Path Rewrites]
+
Host Redpanda Console under an HTTP path different from the root path.

* xref:console:edit-topic-configuration.adoc[Edit Topic Configuration]
+
Use Redpanda Console to edit the configuration of existing topics in a cluster.
