= Manage Redpanda Console
:description: Manage Redpanda Console

* xref:console:kafka-connect.adoc[Kafka Connect]
+
Redpanda Console provides a user interface that enables you to manage multiple Kafka connect clusters.
  You can inspect or patch connectors, restart/pause/resume their tasks, and also delete a connector.
  If you have configured more than one cluster, Redpanda Console will query all configured connect
  clusters for their status, so that you can have an overview across all your connect clusters.

* xref:console:schema-registry.adoc[Schema Registry]
+
To deserialize Kafka records that have been encoded with a schema registry compatible serializer, such as +
  `io.confluent.kafka.serializers.KafkaAvroSerializer`, you must have a valid schema registry configuration in Redpanda Console.

* xref:console:protobuf.adoc[Protobuf Deserialization]
+
If you have one or more topics that contain Protobuf serialized messages, you can configure Redpanda Console to deserialize
  the binary content into JSON, which makes the message human-readable. The resulting message can also be used in the
  xref:reference:console:programmable-push-filters.adoc[programmable push filters] like a JavaScript object.

* xref:console:topic-documentation.adoc[Topic Documentation]
+
You can embed your topic's documentation into the Redpanda Console user interface by providing access to a GitHub repository that hosts your documentation files in Markdown format.

* xref:console:http-path-rewrites.adoc[HTTP Path Rewrites]
+
To host Redpanda Console under an HTTP path different from the root path (for example `+https://my-company.com/redpanda/console+`),
  then you need to configure this in Redpanda Console.
