= Schema Registry Authorization
:page-categories: Management, Schema Registry, rpk, Security
:page-aliases: manage:schema-reg-authorization.adoc
:description: Learn how to set up and manage Schema Registry Authorization using fine-grained ACL definitions for operations that allow users access to specific Schema Registries.
// tag::single-source[]

You can use Schema Registry Authorization to set up and manage ACL definitions for operations that allow users access to specific Schema Registries.

ifndef::env-cloud[]
[NOTE]
====
include::shared:partial$enterprise-license.adoc[]
====
endif::[]

== About Schema Registry Authorization

Schema Registry Authorization is useful for managing permissions for users and applications that interact with the Redpanda Schema Registry, ensuring that only authorized entities can perform operations such as reading, writing, or modifying schemas.

Starting in release 25.2, Schema Registry Authorization allows you to control access to resources by defining fine-grained ACLs (Access Control Lists) using the xref:reference:rpk/rpk-security/rpk-security-acl.adoc[`rpk security acl`] command, or xref:api:ROOT:schema-registry-api.adoc#get-/security/acls[Redpanda Schema Registry API^] endpoints.

In addition to the ACL resources `topic`, `group`, `cluster`, and `transactionalID`, there are two ACL resources specific to Schema Registry:

* `registry-global`: Specifies whether or not to grant ACLs for the Schema Registry. This is for "top level" operations such as `GET :8081/mode`, or `GET :8081/config`.
* `registry-subject`: Specifies Schema Registry subjects to grant ACLs to. This is for "subject-level" operations, such as `GET :8081/subjects`, or `GET :8081/config/{subject}`.

== Supported operations

The following endpoints and operations are supported for Schema Registry Authorization:

|===
| Endpoint | HTTP Verb | Operation | Resource

| `/config`
| `GET`
| `describe_configs`
| `global`

| `/config`
| `PUT`
| `alter_configs`
| `global`

| `/config/{subject}`
| `GET`
| `describe_configs`
| `subject`

| `/config/{subject}`
| `PUT`
| `alter_configs`
| `subject`

| `/config/{subject}`
| `DELETE`
| `alter_configs`
| `subject`

| `/mode`
| `GET`
| `describe_configs`
| `global`

| `/mode`
| `PUT`
| `alter_configs`
| `global`

| `/mode/{subject}`
| `GET`
| `describe_configs`
| `subject`

| `/mode/{subject}`
| `PUT`
| `alter_configs`
| `subject`

| `/mode/{subject}`
| `DELETE`
| `alter_configs`
| `subject`

| `/schemas/types`
| `GET`
| none/open
| -

| `/schema/ids/{id}`
| `GET`
| `read`
| `subject`

| `/schema/ids/{versions}`
| `GET`
| `describe`
| `global`

| `/schema/ids/{subjects}`
| `GET`
| `describe`
| `subject`

| `/subjects`
| `GET`
| `describe`
| `subject`

| `/subjects/{subject}`
| `POST`
| `read`
| `subject`

| `/subjects/{subject}`
| `DELETE`
| `delete`
| `subject`

| `/subjects/{subject}/versions`
| `GET`
| `describe`
| `subject`

| `/subjects/{subject}/versions`
| `POST`
| `write`
| `subject`

| `/subjects/{subject}/versions/{version}`
| `GET`
| `read`
| `subject`

| `/subjects/{subject}/versions/{version}`
| `DELETE`
| `delete`
| `subject`

| `/subjects/{subject}/versions/schema`
| `GET`
| `read`
| `subject`

| `/subjects/{subject}/versions/referencedby`
| `GET`
| `describe`
| `global`

| `compatibility/subjects/{subject}/versions/{version}`
| `POST`
| `read`
| `subject`

| `/status/ready`
| `GET`
| none/open
| -

| `/security/acls`
| `GET`
| `describe`
| `cluster_action`

| `/security/acls`
| `POST`
| `alter`
| `cluster_action`

| `/security/acls`
| `DELETE`
| `alter`
| `cluster_action`
|===

For additional guidance on these operations, see the xref:api:ROOT:schema-registry-api.adoc#get-/security/acls[Redpanda Schema Registry API^].

== Enable Schema Registry Authorization

To enable Schema Registry Authorization for a cluster:

[,bash]
----
rpk cluster config set schema_registry_enable_authorization true
----

You must have a valid Redpanda Enterprise license to:

* Enable Schema Registry Authorization.
* Use the `rpk security acl` command to manage ACLs for the Schema Registry.

