= Use Schema Registry in the UI
:description: Perform common Schema Registry management operations in Redpanda Console.

In the Redpanda UI (Redpanda Console), the **Schema Registry** tab lists registered and verified schemas, including their serialization format and versions. Select an individual schema to see which topics it applies to. 

[NOTE]
====
The Schema Registry is built into Redpanda, and you can use it with the API or the Redpanda Console UI. This section describes Schema Registry operations available in the UI. See also:

* xref:manage:schema-reg/schema-reg-api.adoc[]
* xref:manage:schema-reg/schema-reg-overview.adoc[]
====

== Prerequisite for self-hosted Redpanda

Redpanda Schema Registry UI is automatically configured with new Redpanda Cloud deployments. However, if you're running Redpanda Console with self-hosted Redpanda, you must add a valid `schemaRegistry` configuration in Redpanda Console:

.redpanda-console-config.yaml
[,yaml]
----
kafka:
  schemaRegistry:
    enabled: true
    urls: ["https://my-schema-registry.com"]
    username: console
    password: redacted # Or set using flags or env variable
  # To enable protobuf support
  protobuf:
    enabled: true
    schemaRegistry:
      enabled: true
      refreshInterval: 5m
----

== Create or edit a schema

A schema is registered in the registry with a _subject_, which is a name that is associated with the schema as it evolves. To register a schema, click **Create new schema**. 
+
. On the **Create schema** page, select the strategy type for how to derive the subject name. 
+
- **Topic** (default): The subject name is derived from the Redpanda topic name. See <<Topic strategy use case>>.
- **Record**: The subject name is derived from the Kafka record name. See <<Record strategy use case>>.
- **TopicRecord**: The subject name is derived from both topic name and record name, allowing for finer-grained schema organization. See <<TopicRecord strategy use case>>.
- **Custom**: The subject name is user-defined. 

. Select the serialization format (Avro or Protobuf) with the schema definition. 

. To build more complex schema definitions, add a reference to other schemas. For example, the two `import` statements are references to the `PhoneNumber` and `Address` schemas:
+
[,json]
----
{
syntax = "proto3"; 
import "PhoneNumber.proto";
import "Address.proto"; 
message Person { 
    string name = 1;
    string email = 2;
    PhoneNumber phone  = 3; 
    repeated Address address  = 4; 
}
----

. After registering a schema, you can add a new version to it, change its compatibility, or delete it.

=== Topic strategy use case

The Topic strategy is suitable when you want to group schemas by the topics to which they are associated. Suppose you're tracking product order information in a topic named Transactions. When a producer sends records to the OrderInfo topic, you want the record names to look something like: 

- Transactions - Record1 
- Transactions - Record2 

Where `Record1` and `Record2` are unique identifiers. This is usually defined in your producer settings. Create your schema with the Topic strategy, and the subject name is always Transactions, with all customer transactions under the same topic. 

=== Record strategy use case

The Record strategy is most useful when you have multiple schemas within a topic and need more granular categorization that's influenced by the record name. Suppose there's an Events topic with event types A and B. You may want each of those event types to have their own subject, their own schemas, and their own fully-qualified record names (for example, com.example.EventTypeA). If each event type has its own schema with the Record strategy, then when producers send these event types to the Events topic, their subjects are those record names: 

- com.example.EventTypeA
- com.example.EventTypeB

The record names in the Events topic look like this: 

- Events-com.example.EventTypeA-Record1
- Events-com.example.EventTypeB-Record1
- Events-com.example.EventTypeA-Record2
- Events-com.example.EventTypeB-Record2

=== TopicRecord strategy use case

The TopicRecord strategy is suitable when you want to organize schemas based on both topics and logical record types. Suppose there's a microservices architecture where different services produce to the same topic: SharedEvents. Each microservice has a schema of its own for the shared events, but each schema uses the TopicRecord strategy. This results in the following subject names: 

- SharedEvents-com.example.MicroserviceAEvent
- SharedEvents-com.example.MicroserviceBEvent

The record names look like this: 

- SharedEvents-com.example.MicroserviceAEvent-Record1
- SharedEvents-com.example.MicroserviceBEvent-Record1
- SharedEvents-com.example.MicroserviceAEvent-Record2
- SharedEvents-com.example.MicroserviceBEvent-Record2

This allows for multiple schemas to govern the same shared events for different microservices, allowing granular organization. 

== Configure schema compatibility

include::partial$schema-compatibility.adoc[]

== Delete a schema

Select a schema to soft-delete its entire subject or a single selected version of it. A soft-deleted schema can be recovered, but a permanently-deleted schema cannot be recovered. Schemas cannot be permanently deleted if any other schemas reference it. They remain readable with a soft delete until you remove all references to it. Redpanda does not recommend permanently deleting schemas in a production environment.



== Related topics

* xref:manage:console/protobuf.adoc[]
* xref:reference:console/record-deserialization.adoc[Redpanda Console record deserialization]