= Schema Registry Authorization
:page-categories: Management, Schema Registry, rpk, Security
:page-aliases: manage:schema-reg-authorization.adoc
:description: Learn how to set up and manage Schema Registry Authorization using ACL definitions that control user access to specific Schema Registry operations.
// tag::single-source[]

You can use Schema Registry Authorization to set up and manage ACL definitions for operations that allow users access to specific Redpanda Schema Registry resources.

ifndef::env-cloud[]
[NOTE]
====
include::shared:partial$enterprise-license.adoc[]
====
endif::[]

== About Schema Registry Authorization

Schema Registry Authorization is useful for managing permissions for users and applications that interact with the Redpanda Schema Registry, ensuring that only authorized entities can perform operations such as reading, writing, or modifying schemas.

Prior to release 25.2, Schema Registry supported authentication, but after a user was authenticated they had full access to read, modify, and delete schemas and configuration per-subject as well as globally.

Starting in release 25.2, Schema Registry Authorization allows you to control access to Redpanda Schema Registry resources by:

- Using `rpk` to define fine-grained ACLs (Access Control Lists). More specifically, use the xref:reference:rpk/rpk-security/rpk-security-acl-create.adoc[`rpk security acl create`] command as you would to create other ACLs.
- Using the xref:api:ROOT:schema-registry-api.adoc#get-/security/acls[Redpanda Schema Registry API] endpoints.

In addition to the ACL resources `topic`, `group`, `cluster`, and `transactionalID`, there are two ACL resources specific to Schema Registry ACLs:

* `registry-global`: Specifies whether or not to grant ACLs for the Schema Registry. This is for "top level" or global operations such as `GET :8081/mode`, or `GET :8081/config`.
* `registry-subject`: Specifies Schema Registry subjects to grant ACLs to. This is for "subject-level" operations, such as `GET :8081/subjects`, or `GET :8081/config/{subject}`.

== Supported operations

Redpanda Schema Registry ACLs support the following subset of Kafka endpoints and operations:

|===
| Endpoint | HTTP Verb | Operation | Resource

| `/config`
| `GET`
| `describe_configs`
| `global`

| `/config`
| `PUT`
| `alter_configs`
| `global`

| `/config/{subject}`
| `GET`
| `describe_configs`
| `subject`

| `/config/{subject}`
| `PUT`
| `alter_configs`
| `subject`

| `/config/{subject}`
| `DELETE`
| `alter_configs`
| `subject`

| `/mode`
| `GET`
| `describe_configs`
| `global`

| `/mode`
| `PUT`
| `alter_configs`
| `global`

| `/mode/{subject}`
| `GET`
| `describe_configs`
| `subject`

| `/mode/{subject}`
| `PUT`
| `alter_configs`
| `subject`

| `/mode/{subject}`
| `DELETE`
| `alter_configs`
| `subject`

| `/schemas/types`
| `GET`
| none/open
| -

| `/schema/ids/{id}`
| `GET`
| `read`
| `subject`

| `/schema/ids/{versions}`
| `GET`
| `describe`
| `global`

| `/schema/ids/{subjects}`
| `GET`
| `describe`
| `subject`

| `/subjects`
| `GET`
| `describe`
| `subject`

| `/subjects/{subject}`
| `POST`
| `read`
| `subject`

| `/subjects/{subject}`
| `DELETE`
| `delete`
| `subject`

| `/subjects/{subject}/versions`
| `GET`
| `describe`
| `subject`

| `/subjects/{subject}/versions`
| `POST`
| `write`
| `subject`

| `/subjects/{subject}/versions/{version}`
| `GET`
| `read`
| `subject`

| `/subjects/{subject}/versions/{version}`
| `DELETE`
| `delete`
| `subject`

| `/subjects/{subject}/versions/schema`
| `GET`
| `read`
| `subject`

| `/subjects/{subject}/versions/referencedby`
| `GET`
| `describe`
| `global`

| `compatibility/subjects/{subject}/versions/{version}`
| `POST`
| `read`
| `subject`

| `/status/ready`
| `GET`
| none/open
| -

| `/security/acls`
| `GET`
| `describe`
| `cluster_action`

| `/security/acls`
| `POST`
| `alter`
| `cluster_action`

| `/security/acls`
| `DELETE`
| `alter`
| `cluster_action`
|===

For additional guidance on these operations, see the xref:api:ROOT:schema-registry-api.adoc#get-/security/acls[Redpanda Schema Registry API].

== Enable Schema Registry Authorization

You must have a valid Redpanda Enterprise license to:

* Enable Schema Registry Authorization.
* Use the `rpk security create acl` command to manage ACLs for the Schema Registry.

To enable ACL-based Schema Registry Authorization for a cluster:

[,bash]
----
rpk cluster config set schema_registry_enable_authorization true
----

For details, see xref:reference/cluster-properties/schema_reg_authorization.adoc[`schema_registry_enable_authorization`].

== Create and manage ACLs for Redpanda Schema Registry

This section describes how to create ACLs for the Redpanda Schema Registry.

=== Create an ACL for a topic and a Schema Registry subject

To create an ACL for both the topic resource and a Schema Registry subject, use the `rpk security acl create` command with the appropriate resource types. In this case, the principal `panda` is allowed to read from the topic `bar` and the schema subject `bar-value`:

[,bash]
----
rpk security acl create --allow-principal panda --operation read --topic bar --registry-subject bar-value

PRINCIPAL   HOST  RESOURCE-TYPE  RESOURCE-NAME  RESOURCE-PATTERN-TYPE  OPERATION  PERMISSION  ERROR
User:panda  *     SUBJECT        bar-value      LITERAL                READ       ALLOW
User:panda  *     TOPIC          bar            LITERAL                READ       ALLOW

----

== Create an ACL that provides global access to Schema Registry

To create an ACL that provides global access to the Schema Registry, use the `rpk security acl create` command with the appropriate resource types. In this case, the principal `jane` is allowed to read from all schema subjects:



=== Create a role and add ACLs to it

You can also use ACLs for Schema Registry in conjunction with xref:manage:security/authorization/rbac[RBAC] (Role-Based Access Control) to create roles that encapsulate multiple ACLs. This allows you to manage schema permissions more easily by assigning roles to users or groups.

The following example shows how to create a role, two ACLs (one for a topic and another for a Schema Registry subject), and then assigns the new role to users:

[NOTE]
====
Redpanda recommends that you use the topic naming strategy, where the Schema Registry subject takes the form of `<topicName>-key` or `<topicName>-value`. For details, see xref:manage:schema-reg/schema-id-validation#set-subject-name-strategy-per-topic.adoc[Set subject name strategy per topic].
====

[,bash]
----
rpk security role create SoftwareEng

rpk security acl create \
  --operation read,write \
  --topic private \
  --registry-subject private-key,private-value \
  --allow-role SoftwareEng

# ACLs can now be added to this role using
  rpk security acl create --allow-role "RedpandaRole:SoftwareEng" [acl-flags]
----

You can then assign the role to users or groups:

[,bash]
----

rpk security role assign SoftwareEng --principal User:john,User:jane
Successfully assigned role "SoftwareEng" to
NAME  PRINCIPAL-TYPE
john  User
jane  User
----

=== Troubleshooting

It is possible that in some cases, either the topic or some other resource type specified is created, but the Schema Registry subject is not created. For example:

[,bash]
----
rpk security acl create --allow-principal alice --operation read --topic bar --registry-subject bar-value

PRINCIPAL   HOST  RESOURCE-TYPE  RESOURCE-NAME  RESOURCE-PATTERN-TYPE  OPERATION  PERMISSION  ERROR
User:alice  *     SUBJECT        bar-value      LITERAL                READ       ALLOW.      Not found
User:alice  *     TOPIC          bar            LITERAL                READ       ALLOW
----

In this case, the ACL for the topic `bar` is created, but the ACL for the registry subject `bar-value` was not created. Such an error can occur for a variety of reasons:

* The `registry-subject` specified does not exist in the Schema Registry.
* The wrong URL is specified when sending the request to the Schema Registry.

In such cases, a first step is to repeat the command with the `-v` (verbose logging) option to view more details and debug:

[,bash]
----
rpk security acl create --allow-principal alice --operation read --topic bar --registry-subject bar-value -v
12:17:33.911 DEBUG opening connection to broker {"addr": "127.0.0.1:9092", "broker": "seed_0"}
12:17:33.912 DEBUG connection opened to broker {"addr": "127.0.0.1:9092", "broker": "seed_0"}
12:17:33.912 DEBUG issuing api versions request {"broker": "seed_0", "version": 4}
12:17:33.912 DEBUG wrote ApiVersions v4 {"broker": "seed_0", "bytes_written": 31, "write_wait": 13.416µs", "time_to_write": "17.75µs", "err": null}
12:17:33.912 DEBUG read ApiVersions v4 {"broker": "seed_0", "bytes_read": 266, "read_wait": 16.209µs", "time_to_read": "8.360666ms", "err": null}
12:17:33.920 DEBUG connection initialized successfully {"addr": "127.0.0.1:9092", "broker": "seed_0"}
12:17:33.920 DEBUG wrote CreateACLs  v2 {"broker": "seed_0", "bytes_written": 43, "write_wait": 9.0985ms, "time_to_write": "14µs", "err": null}
12:17:33.935 DEBUG read CreateACLs v2 {"broker": "seed_0", "bytes_read": 19, "read_wait": 23.792µs, "time_to_read": "14.323041ms", "err": null}
12:17:33.935 DEBUG sending request {"method": "POST", "URL: "http://127.0.0.1:8081/security/acls", "has_bearer": false, "has_basic_auth": false}
PRINCIPAL   HOST  RESOURCE-TYPE  RESOURCE-NAME  RESOURCE-PATTERN-TYPE  OPERATION  PERMISSION  ERROR
User:alice  *     SUBJECT        bar-value      LITERAL                READ       ALLOW       Not found
User:alice  *     TOPIC          bar            LITERAL                READ       ALLOW
----

