= Create a BYOC Cluster on GCP
:description: Use the Redpanda Cloud UI to create a BYOC cluster on GCP.
:page-aliases: cloud:create-byoc-cluster-gcp.adoc

To create a Redpanda cluster in your own cloud, log in to the Redpanda Cloud UI and create a namespace, then follow the steps for creating a Bring your own cloud (BYOC) cluster.

== Create a namespace

To prepare to deploy a Redpanda cluster in your own cloud, log in to the Redpanda Cloud UI and add a namespace:

. Go to https://cloudv2.redpanda.com[Redpanda Cloud] and click *Log in*.
+
The Enter Organization page opens.

. Type your organization name and click *Continue*.
+
The Home page opens.

. Click *Add namespace*.
+
Namespaces help you organize clusters by owner, team, or project for example.

. Type a name for your namespace.

== Create a BYOC cluster

After you create a namespace, create a BYOC cluster in your Virtual Private Cloud (VPC):

. Scroll to your namespace (namespaces are listed in alphabetical order) and click *+ Add Cluster*.
. Click *Create BYOC cluster*.
. (Optional) In *Cluster name*, type a name to replace the default name.
. Select throughput.
+
The choices are 1 MBps, 5 MBps, 10 MBps, and 20 MBps.

. Open the *Redpanda version* menu and select a version.
. Click *Next*.
+
The *Cloud settings* page opens.

. For *Provider*, select GCP.
. Open the *Region* menu and select a region.
. For *Availability*, select *Single AZ* or *Multi AZ*.
. Open the *Zones* menu and select the availability zone(s) for your region.
+
If Single AZ was selected in the previous step, then select a single zone. If Multi AZ was selected, then select three availability zones to provide two backups in case one availability zone goes down.

. Click *Next*.
+
The *Networking* page opens.

. Under *Choose Connection Type*, select either *Public* or *Private*.
. Click *Next*.

After the network is created, you can deploy the agent.

== Deploy the agent

=== Prerequisites

* Install the https://docs.redpanda.com/docs/platform/quickstart/rpk-install/[Redpanda CLI].
 ** Minimum `rpk` version: `v22.3+`.
* Install the https://cloud.google.com/sdk/docs/install[`gcloud` CLI].
 ** If the gcloud CLI is already installed, make sure the components are up-to-date by running: `gcloud components update`.
* Setup the gcloud https://cloud.google.com/sdk/gcloud/reference/auth/application-default/login[application-default] credentials.
+
To temporarily use your user credentials for API access, run: `gcloud auth application-default login`. This command opens Google's login page in a browser window.

* Ensure that your role has the necessary permissions to run commands and create clusters.

=== Create Redpanda Cloud client

* From the Redpanda Cloud home page, select *Clients* from the navigation pane.
* Click *Add client* and enter a name and description, or simply use an existing client.
+
Copy the *Client ID* and *Client Secret*.

* Navigate back to the cluster. The wizard takes you back to the Deploy Agent page.
+
Paste the *Client ID* and *Client Secret* in the client credentials boxes.

* Run the `rpk cloud login` command in your deployment environment:
+
[,shell]
----
rpk cloud login --save
  --client-id='...'
  --client-secret='...'
----

=== Deploy agent

* Enter your GCP Project ID.
* Run the `rpk cloud byoc gcp apply` command in your deployment environment:
+
[,shell]
----
rpk cloud byoc gcp apply
  --redpanda-id='...'
  --project-id='...'
----
