= Cloud Configuration Properties 
:description: Cloud configuration properties list. 

Cloud properties intro

== Cloud

=== cloud_storage_access_key

AWS access key.

*Requires Restart:* No

*Nullable:* Yes

*Visibility:* `user`

*Type:* string

*Default:* `null`

---

=== cloud_storage_api_endpoint

Optional API endpoint.

*Requires Restart:* No

*Nullable:* Yes

*Visibility:* `user`

*Type:* string

*Default:* `null`

---

=== cloud_storage_api_endpoint_port

TLS port override.

*Requires Restart:* No

*Nullable:* No

*Visibility:* `user`

*Type:* integer

*Accepted values:* [`-32768`, `32767`]

*Default:* `443`

---

=== cloud_storage_azure_adls_endpoint

Azure Data Lake Storage v2 endpoint override. Use when Hierarchical Namespaces are enabled on your storage account and you have set up a custom endpoint.

*Requires Restart:* Yes

*Nullable:* Yes

*Visibility:* `user`

*Type:* string

*Default:* `null`

---

=== cloud_storage_azure_adls_port

Azure Data Lake Storage v2 port override. Also see cloud_storage_azure_adls_endpoint.

*Requires Restart:* Yes

*Nullable:* Yes

*Visibility:* `user`

*Type:* integer

*Accepted values:* [`0`, `65535`]

*Default:* `null`

---

=== cloud_storage_azure_container

The name of the Azure container to use with Tiered Storage. Note that the container must belong to 'cloud_storage_azure_storage_account'.

*Requires Restart:* Yes

*Nullable:* Yes

*Visibility:* `user`

*Type:* string

*Default:* `null`

---

=== cloud_storage_azure_shared_key

The shared key to be used for Azure Shared Key authentication with the configured Azure storage account (see 'cloud_storage_azure_storage_account)'. Note that Redpanda expects this string to be Base64 encoded.

*Requires Restart:* No

*Nullable:* Yes

*Visibility:* `user`

*Type:* string

*Default:* `null`

---

=== cloud_storage_azure_storage_account

The name of the Azure storage account to use with Tiered Storage.

*Requires Restart:* Yes

*Nullable:* Yes

*Visibility:* `user`

*Type:* string

*Default:* `null`

---

=== cloud_storage_backend

Optional cloud storage backend variant used to select API capabilities. If not supplied, will be inferred from other configuration parameters.

*Requires Restart:* Yes

*Nullable:* No

*Visibility:* `user`

*Default:* `model::cloud_storage_backend::unknown`

---

=== cloud_storage_bucket

AWS bucket that should be used to store data.

*Requires Restart:* No

*Nullable:* Yes

*Visibility:* `user`

*Type:* string

*Default:* `null`

---

=== cloud_storage_cache_check_interval_ms

Minimum time between trims of tiered storage cache.  If a fetch operation requires trimming the cache, and the most recent trim was within this period, then trimming will be delayed until this period has elapsed.

*Requires Restart:* No

*Nullable:* No

*Visibility:* `tunable`

*Type:* integer

*Accepted values:* [`-17592186044416`, `17592186044415`]

*Default:* `5s`

---

=== cloud_storage_cache_chunk_size

Size of chunks of segments downloaded into cloud storage cache. Reduces space usage by only downloading the necessary chunk from a segment.

*Requires Restart:* Yes

*Nullable:* No

*Visibility:* `tunable`

*Type:* integer

*Accepted values:* [`0`, `18446744073709551615`]

*Default:* `16777216`

---

=== cloud_storage_cache_directory

Directory for archival cache. Should be present when `cloud_storage_enabled` is present.

*Requires Restart:* Yes

*Nullable:* Yes

*Visibility:* `user`

*Type:* string

*Default:* `null`

---

=== cloud_storage_cache_max_objects

Maximum number of objects that may be held in the tiered storage cache.  This applies simultaneously with `cloud_storage_cache_size`, and which ever limit is hit first will drive trimming of the cache.

*Requires Restart:* No

*Nullable:* No

*Visibility:* `tunable`

*Type:* integer

*Accepted values:* [`0`, `4294967295`]

*Default:* `100000`

---

=== cloud_storage_cache_size

Max size of archival cache.

*Requires Restart:* No

*Nullable:* No

*Visibility:* `user`

*Type:* integer

*Accepted values:* [`0`, `18446744073709551615`]

*Default:* `0`

---

=== cloud_storage_cache_size_percent

The maximum size of the archival cache as a percentage of unreserved disk space (see disk_reservation_percent). The default value for this option is tuned for a shared disk configuration. When using a dedicated cache disk consider increasing the value.

*Requires Restart:* No

*Nullable:* Yes

*Visibility:* `user`

*Type:* number

*Default:* `20.0`

---

=== cloud_storage_chunk_eviction_strategy

Selects a strategy for evicting unused cache chunks.

*Requires Restart:* No

*Nullable:* No

*Visibility:* `tunable`

*Default:* `model::cloud_storage_chunk_eviction_strategy::eager`

---

=== cloud_storage_chunk_prefetch

Number of chunks to prefetch ahead of every downloaded chunk.

*Requires Restart:* No

*Nullable:* No

*Visibility:* `tunable`

*Type:* integer

*Accepted values:* [`0`, `65535`]

*Default:* `0`

---

=== cloud_storage_cluster_metadata_upload_interval_ms

Time interval to wait between cluster metadata uploads.

*Requires Restart:* No

*Nullable:* No

*Visibility:* `tunable`

*Type:* integer

*Accepted values:* [`-17592186044416`, `17592186044415`]

*Default:* `60s`

---

=== cloud_storage_credentials_host

The hostname to connect to for retrieving role based credentials. Derived from cloud_storage_credentials_source if not set. Only required when using IAM role based access.

*Requires Restart:* Yes

*Nullable:* Yes

*Visibility:* `tunable`

*Type:* string

*Default:* `null`

---

=== cloud_storage_credentials_source

The source of credentials to connect to cloud services.

*Requires Restart:* Yes

*Nullable:* No

*Visibility:* `user`

*Default:* `model::cloud_credentials_source::config_file`

---

=== cloud_storage_disable_chunk_reads

Disable chunk reads and switch back to legacy mode where full segments are downloaded.

*Requires Restart:* No

*Nullable:* No

*Visibility:* `tunable`

*Type:* boolean

*Default:* `false`

---

=== cloud_storage_disable_metadata_consistency_checks

Disable all metadata consistency checks. This will allow redpanda to replay logs with inconsistent tiered-storage metadata. Normally, this option should be disabled.

*Requires Restart:* No

*Nullable:* No

*Visibility:* `tunable`

*Type:* boolean

*Default:* `true`

---

=== cloud_storage_disable_read_replica_loop_for_tests

Begins the read replica sync loop in tiered-storage-enabled topic partitions. The property exists to simplify testing and shouldn't be set in production.

*Requires Restart:* No

*Nullable:* No

*Visibility:* `tunable`

*Type:* boolean

*Default:* `false`

---

=== cloud_storage_disable_tls

Disable TLS for all S3 connections.

*Requires Restart:* No

*Nullable:* No

*Visibility:* `user`

*Type:* boolean

*Default:* `false`

---

=== cloud_storage_disable_upload_consistency_checks

Disable all upload consistency checks. This will allow redpanda to upload logs with gaps and replicate metadata with consistency violations. Normally, this options should be disabled.

*Requires Restart:* No

*Nullable:* No

*Visibility:* `tunable`

*Type:* boolean

*Default:* `false`

---

=== cloud_storage_disable_upload_loop_for_tests

Begins the upload loop in tiered-storage-enabled topic partitions. The property exists to simplify testing and shouldn't be set in production.

*Requires Restart:* No

*Nullable:* No

*Visibility:* `tunable`

*Type:* boolean

*Default:* `false`

---

=== cloud_storage_enable_compacted_topic_reupload

Enable re-uploading data for compacted topics.

*Requires Restart:* No

*Nullable:* No

*Visibility:* `tunable`

*Type:* boolean

*Default:* `true`

---

=== cloud_storage_enable_remote_read

Default remote read config value for new topics.

*Requires Restart:* No

*Nullable:* No

*Visibility:* `tunable`

*Type:* boolean

*Default:* `false`

---

=== cloud_storage_enable_remote_write

Default remote write value for new topics.

*Requires Restart:* No

*Nullable:* No

*Visibility:* `tunable`

*Type:* boolean

*Default:* `false`

---

=== cloud_storage_enable_segment_merging

Enables adjacent segment merging. The segments are reuploaded if there is an opportunity for that and if it will improve the tiered-storage performance.

*Requires Restart:* No

*Nullable:* No

*Visibility:* `tunable`

*Type:* boolean

*Default:* `true`

---

=== cloud_storage_enabled

Enable archival storage.

*Requires Restart:* No

*Nullable:* No

*Visibility:* `user`

*Type:* boolean

*Default:* `false`

---

=== cloud_storage_graceful_transfer_timeout_ms

Time limit on waiting for uploads to complete before a leadership transfer.  If this is null, leadership transfers will proceed without waiting.

*Requires Restart:* No

*Nullable:* Yes

*Visibility:* `tunable`

*Type:* integer

*Accepted values:* [`-17592186044416`, `17592186044415`]

*Default:* `5s`

---

=== cloud_storage_housekeeping_interval_ms

Interval for cloud storage housekeeping tasks.

*Requires Restart:* No

*Nullable:* No

*Visibility:* `tunable`

*Type:* integer

*Accepted values:* [`-17592186044416`, `17592186044415`]

*Default:* `5min`

---

=== cloud_storage_hydrated_chunks_per_segment_ratio

The maximum number of chunks per segment that can be hydrated at a time. Above this number, unused chunks will be trimmed.

*Requires Restart:* No

*Nullable:* No

*Visibility:* `tunable`

*Type:* number

*Default:* `0.7`

---

=== cloud_storage_hydration_timeout_ms

Duration to wait for a hydration request to be fulfilled, if hydration is not completed within this time, the consumer will be notified with a timeout error.

*Requires Restart:* No

*Nullable:* No

*Visibility:* `tunable`

*Type:* integer

*Accepted values:* [`-17592186044416`, `17592186044415`]

*Default:* `600s`

---

=== cloud_storage_idle_threshold_rps

The cloud storage request rate threshold for idle state detection. If the average request rate for the configured period is lower than this threshold the cloud storage is considered being idle.

*Requires Restart:* No

*Nullable:* No

*Visibility:* `tunable`

*Type:* number

*Default:* `1.0`

---

=== cloud_storage_idle_timeout_ms

Timeout used to detect idle state of the cloud storage API. If the average cloud storage request rate is below this threshold for a configured amount of time the cloud storage is considered idle and the housekeeping jobs are started.

*Requires Restart:* No

*Nullable:* No

*Visibility:* `tunable`

*Type:* integer

*Accepted values:* [`-17592186044416`, `17592186044415`]

*Default:* `10s`

---

=== cloud_storage_initial_backoff_ms

Initial backoff time for exponential backoff algorithm (ms).

*Requires Restart:* No

*Nullable:* No

*Visibility:* `tunable`

*Type:* integer

*Accepted values:* [`-17592186044416`, `17592186044415`]

*Default:* `100ms`

---

=== cloud_storage_manifest_cache_size

Amount of memory that can be used to handle tiered-storage metadata.

*Requires Restart:* No

*Nullable:* No

*Visibility:* `tunable`

*Type:* integer

*Default:* `1048576`

---

=== cloud_storage_manifest_cache_ttl_ms

The time interval that determines how long the materialized manifest can stay in cache under contention. This parameter is used for performance tuning. When the spillover manifest is materialized and stored in cache and the cache needs to evict it it will use 'cloud_storage_materialized_manifest_ttl_ms' value as a timeout. The cursor that uses the spillover manifest uses this value as a TTL interval after which it stops referencing the manifest making it available for eviction. This only affects spillover manifests under contention.

*Requires Restart:* No

*Nullable:* No

*Visibility:* `tunable`

*Type:* integer

*Accepted values:* [`-17592186044416`, `17592186044415`]

*Default:* `10s`

---

=== cloud_storage_manifest_max_upload_interval_sec

Wait at least this long between partition manifest uploads. Actual time between uploads may be greater than this interval. If this is null, metadata will be updated after each segment upload.

*Requires Restart:* No

*Nullable:* Yes

*Visibility:* `tunable`

*Type:* integer

*Accepted values:* [`-17179869184`, `17179869183`]

*Default:* `60s`

---

=== cloud_storage_manifest_upload_timeout_ms

Manifest upload timeout (ms).

*Requires Restart:* No

*Nullable:* No

*Visibility:* `tunable`

*Type:* integer

*Accepted values:* [`-17592186044416`, `17592186044415`]

*Default:* `10s`

---

=== cloud_storage_max_connection_idle_time_ms

Max https connection idle time (ms).

*Requires Restart:* No

*Nullable:* No

*Visibility:* `tunable`

*Type:* integer

*Accepted values:* [`-17592186044416`, `17592186044415`]

*Default:* `5s`

---

=== cloud_storage_max_connections

Max number of simultaneous connections to S3 per shard (includes connections used for both uploads and downloads).

*Requires Restart:* No

*Nullable:* No

*Visibility:* `user`

*Type:* integer

*Accepted values:* [`-32768`, `32767`]

*Default:* `20`

---

=== cloud_storage_max_materialized_segments_per_shard

Maximum concurrent readers of remote data per CPU core.  If unset, value of `topic_partitions_per_shard` multiplied by 2 is used.

*Requires Restart:* No

*Nullable:* Yes

*Visibility:* `tunable`

*Type:* integer

*Accepted values:* [`0`, `4294967295`]

*Default:* `null`

---

=== cloud_storage_max_partition_readers_per_shard

Maximum concurrent partition readers of remote data per CPU core.  If unset, value of `topic_partitions_per_shard` is used, i.e. one reader per partition if the shard is at its maximum partition capacity.  These readers have thelifetime of a Kafka consume request, so this property controls how many consumerequests to remote data can make progress at the same time.

*Requires Restart:* No

*Nullable:* Yes

*Visibility:* `tunable`

*Type:* integer

*Accepted values:* [`0`, `4294967295`]

*Default:* `null`

---

=== cloud_storage_max_segment_readers_per_shard

Maximum concurrent I/O cursors of materialized remote segments per CPU core.  If unset, value of `topic_partitions_per_shard` is used, i.e. one segment reader per partition if the shard is at its maximum partition capacity.  These readers are cachedacross Kafka consume requests and store a readahead buffer.

*Requires Restart:* No

*Nullable:* Yes

*Visibility:* `tunable`

*Type:* integer

*Accepted values:* [`0`, `4294967295`]

*Default:* `null`

---

=== cloud_storage_max_segments_pending_deletion_per_partition

The per-partition limit for the number of segments pending deletion from the cloud. Segments can be deleted due to retention or compaction. If this limit is breached and deletion fails, then segments will be orphaned in the cloud and will have to be removed manually.

*Requires Restart:* No

*Nullable:* No

*Visibility:* `tunable`

*Type:* integer

*Default:* `5000`

---

=== cloud_storage_metadata_sync_timeout_ms

Timeout for SI metadata synchronization.

*Requires Restart:* No

*Nullable:* No

*Visibility:* `tunable`

*Type:* integer

*Accepted values:* [`-17592186044416`, `17592186044415`]

*Default:* `10s`

---

=== cloud_storage_min_chunks_per_segment_threshold

The minimum number of chunks per segment for trimming to be enabled. If the number of chunks in a segment is below this threshold, the segment is small enough that all chunks in it can be hydrated at any given time.

*Requires Restart:* No

*Nullable:* No

*Visibility:* `tunable`

*Type:* integer

*Accepted values:* [`0`, `18446744073709551615`]

*Default:* `5`

---

=== cloud_storage_readreplica_manifest_sync_timeout_ms

Timeout to check if new data is available for partition in S3 for read replica.

*Requires Restart:* No

*Nullable:* No

*Visibility:* `tunable`

*Type:* integer

*Accepted values:* [`-17592186044416`, `17592186044415`]

*Default:* `30s`

---

=== cloud_storage_recovery_temporary_retention_bytes_default

Retention in bytes for topics created during automated recovery.

*Requires Restart:* No

*Nullable:* No

*Visibility:* `tunable`

*Type:* integer

*Default:* `1073741824`

---

=== cloud_storage_region

AWS region that houses the bucket used for storage.

*Requires Restart:* No

*Nullable:* Yes

*Visibility:* `user`

*Type:* string

*Default:* `null`

---

=== cloud_storage_roles_operation_timeout_ms

Timeout for IAM role related operations (ms).

*Requires Restart:* No

*Nullable:* No

*Visibility:* `tunable`

*Type:* integer

*Accepted values:* [`-17592186044416`, `17592186044415`]

*Default:* `30s`

---

=== cloud_storage_secret_key

AWS secret key.

*Requires Restart:* No

*Nullable:* Yes

*Visibility:* `user`

*Type:* string

*Default:* `null`

---

=== cloud_storage_segment_max_upload_interval_sec

Time that segment can be kept locally without uploading it to the remote storage (sec).

*Requires Restart:* No

*Nullable:* Yes

*Visibility:* `tunable`

*Type:* integer

*Accepted values:* [`-17179869184`, `17179869183`]

*Default:* `1h`

---

=== cloud_storage_segment_size_min

Smallest acceptable segment size in the cloud storage. Default: cloud_storage_segment_size_target/2.

*Requires Restart:* No

*Nullable:* Yes

*Visibility:* `tunable`

*Type:* integer

*Default:* `null`

---

=== cloud_storage_segment_size_target

Desired segment size in the cloud storage. Default: segment.bytes.

*Requires Restart:* No

*Nullable:* Yes

*Visibility:* `tunable`

*Type:* integer

*Default:* `null`

---

=== cloud_storage_segment_upload_timeout_ms

Log segment upload timeout (ms).

*Requires Restart:* No

*Nullable:* No

*Visibility:* `tunable`

*Type:* integer

*Accepted values:* [`-17592186044416`, `17592186044415`]

*Default:* `30s`

---

=== cloud_storage_spillover_manifest_max_segments

Maximum number of elements in the spillover manifest that can be offloaded to the cloud storage. This property is similar to 'cloud_storage_spillover_manifest_size' but it triggers spillover based on number of segments instead of the size of the manifest in bytes. The property exists to simplify testing and shouldn't be set in the production environment.

*Requires Restart:* No

*Nullable:* Yes

*Visibility:* `tunable`

*Type:* integer

*Default:* `null`

---

=== cloud_storage_spillover_manifest_size

The size of the manifest which can be offloaded to the cloud. If the size of the local manifest stored in redpanda exceeds cloud_storage_spillover_manifest_size x2 the spillover mechanism will split the manifest into two parts and one of them will be uploaded to S3.

*Requires Restart:* No

*Nullable:* Yes

*Visibility:* `tunable`

*Type:* integer

*Default:* `null`

---

=== cloud_storage_topic_purge_grace_period_ms

Grace period during which the scrubber will refuse to purge the topic.

*Requires Restart:* No

*Nullable:* No

*Visibility:* `tunable`

*Type:* integer

*Accepted values:* [`-17592186044416`, `17592186044415`]

*Default:* `30s`

---

=== cloud_storage_trust_file

Path to certificate that should be used to validate server certificate during TLS handshake.

*Requires Restart:* No

*Nullable:* Yes

*Visibility:* `user`

*Type:* string

*Default:* `null`

---

=== cloud_storage_upload_ctrl_d_coeff

Derivative coefficient for upload PID controller.

*Requires Restart:* No

*Nullable:* No

*Visibility:* `tunable`

*Type:* number

*Default:* `0.0`

---

=== cloud_storage_upload_ctrl_max_shares

Maximum number of IO and CPU shares that archival upload can use.

*Requires Restart:* No

*Nullable:* No

*Visibility:* `tunable`

*Type:* integer

*Accepted values:* [`-32768`, `32767`]

*Default:* `1000`

---

=== cloud_storage_upload_ctrl_min_shares

Minimum number of IO and CPU shares that archival upload can use.

*Requires Restart:* No

*Nullable:* No

*Visibility:* `tunable`

*Type:* integer

*Accepted values:* [`-32768`, `32767`]

*Default:* `100`

---

=== cloud_storage_upload_ctrl_p_coeff

Proportional coefficient for upload PID controller.

*Requires Restart:* No

*Nullable:* No

*Visibility:* `tunable`

*Type:* number

*Default:* `-2.0`

---

=== cloud_storage_upload_loop_initial_backoff_ms

Initial backoff interval when there is nothing to upload for a partition (ms).

*Requires Restart:* No

*Nullable:* No

*Visibility:* `tunable`

*Type:* integer

*Accepted values:* [`-17592186044416`, `17592186044415`]

*Default:* `100ms`

---

=== cloud_storage_upload_loop_max_backoff_ms

Max backoff interval when there is nothing to upload for a partition (ms).

*Requires Restart:* No

*Nullable:* No

*Visibility:* `tunable`

*Type:* integer

*Accepted values:* [`-17592186044416`, `17592186044415`]

*Default:* `10s`

---

