= Configure Listeners in Kubernetes
:description: Customize the advertised ports for each listener on all Redpanda brokers, or disable listeners altogether.
:page-tags: ["Kubernetes", "Helm configuration"]

You can customize the advertised ports for each listener on all Redpanda brokers, or disable listeners altogether.

== Customize the advertised ports

To customize the advertised ports for each listener, replace `<port>` with the port that you want to use.

[NOTE]
====
Redpanda doesn’t validate the configured port numbers. Make sure to verify the following:

- Your configured port numbers are within the range that is assigned for node ports in your Kubernetes cluster.
- Your Kubernetes cluster is accessible through your desired node port range. You may need to edit your inbound firewall rules.
- Your configured port numbers are not in use by any other service.
====

[tabs]
======
Admin API::
+
--
[tabs]
====
--values::
+
.`custom-admin-port.yaml`
[,yaml]
----
listeners:
  admin:
    external:
      default:
        advertisedPorts:
        - <port>
----
+
```bash
helm upgrade --install redpanda redpanda/redpanda -n redpanda --create-namespace \
  --values custom-admin-port.yaml --reuse-values
```

--set::
+
```bash
helm upgrade --install redpanda redpanda/redpanda -n redpanda --create-namespace \
  --set "listeners.admin.external.default.advertisedPorts={<port>}"
```
====
--
Kafka API::
+
--
[tabs]
====
--values::
+
.`custom-kafka-port.yaml`
[,yaml]
----
listeners:
  kafka:
    external:
      default:
        advertisedPorts:
        - <port>
----
+
```bash
helm upgrade --install redpanda redpanda/redpanda -n redpanda --create-namespace \
  --values custom-kafka-port.yaml --reuse-values
```

--set::
+
```bash
helm upgrade --install redpanda redpanda/redpanda -n redpanda --create-namespace \
  --set "listeners.kafka.external.default.advertisedPorts={<port>}"
```
====
--
HTTP Proxy::
+
--
[tabs]
====
--values::
+
.`custom-pandaproxy-port.yaml`
[,yaml]
----
listeners:
  http:
    external:
      default:
        advertisedPorts:
        - <port>
----
+
```bash
helm upgrade --install redpanda redpanda/redpanda -n redpanda --create-namespace \
  --values custom-pandaproxy-port.yaml --reuse-values
```

--set::
+
```bash
helm upgrade --install redpanda redpanda/redpanda -n redpanda --create-namespace \
  --set "listeners.http.external.default.advertisedPorts={<port>}"
```
====
--
Schema Registry::
+
--
[tabs]
====
--values::
+
.`custom-schema-registry-port.yaml`
[,yaml]
----
listeners:
  schemaRegistry:
    external:
      default:
        advertisedPorts:
        - <port>
----
+
```bash
helm upgrade --install redpanda redpanda/redpanda -n redpanda --create-namespace \
  --values custom-schema-registry-port.yaml --reuse-values
```

--set::
+
```bash
helm upgrade --install redpanda redpanda/redpanda -n redpanda --create-namespace \
  --set "listeners.schemaRegistry.external.default.advertisedPorts={<port>}"
```
====
--
======
[NOTE]
====
helm_ref:listeners[]
====

=== Disable external access

You can disable external access for all listeners or for individual listeners.

[tabs]
======
All listeners::
+
--
[tabs]
====
--values::
+
.`disable-external-access.yaml`
[,yaml]
----
external:
  enabled: false
----
+
```bash
helm upgrade --install redpanda redpanda/redpanda -n redpanda --create-namespace \
  --values disable-external-access.yaml --reuse-values
```

--set::
+
```bash
helm upgrade --install redpanda redpanda/redpanda -n redpanda --create-namespace \
  --set external.enabled=false
```
====
--
Admin API::
+
--
[tabs]
====
--values::
+
.`disable-external-admin-api.yaml`
[,yaml]
----
listeners:
  admin:
    external:
      default:
        enabled: false
----
+
```bash
helm upgrade --install redpanda redpanda/redpanda -n redpanda --create-namespace \
  --values disable-external-admin-api.yaml --reuse-values
```

--set::
+
```bash
helm upgrade --install redpanda redpanda/redpanda -n redpanda --create-namespace \
  --set listeners.admin.external.default.enabled=false
```
====
--
Kafka API::
+
--
[tabs]
====
--values::
+
.`disable-external-kafka-api.yaml`
[,yaml]
----
listeners:
  kafka:
    external:
      default:
        enabled: false
----
+
```bash
helm upgrade --install redpanda redpanda/redpanda -n redpanda --create-namespace \
  --values disable-external-kafka-api.yaml --reuse-values
```

--set::
+
```bash
helm upgrade --install redpanda redpanda/redpanda -n redpanda --create-namespace \
  --set listeners.kafka.external.default.enabled=false
```
====
--
HTTP Proxy::
+
--
[tabs]
====
--values::
+
.`disable-external-pandaproxy.yaml`
[,yaml]
----
listeners:
  http:
    external:
      default:
        enabled: false
----
+
```bash
helm upgrade --install redpanda redpanda/redpanda -n redpanda --create-namespace \
  --values disable-external-pandaproxy.yaml --reuse-values
```

--set::
+
```bash
helm upgrade --install redpanda redpanda/redpanda -n redpanda --create-namespace \
  --set listeners.http.external.default.enabled=false
```
====
--
Schema Registry::
+
--
[tabs]
====
--values::
+
.`disable-external-schema-registry.yaml`
[,yaml]
----
listeners:
  schemaRegistry:
    external:
      default:
        enabled: false
----
+
```bash
helm upgrade --install redpanda redpanda/redpanda -n redpanda --create-namespace \
  --values disable-external-schema-registry.yaml --reuse-values
```

--set::
+
```bash
helm upgrade --install redpanda redpanda/redpanda -n redpanda --create-namespace \
  --set listeners.schemaRegistry.external.default.enabled=false
```
====
--
======
[NOTE]
====
helm_ref:listeners[]
====


== Next steps

xref:manage:kubernetes/security/index.adoc[Configure security] for your listeners.
