= rpk acl create
:description: rpk acl create

Create ACLs.

Following the multiplying effect of combining flags, the create command works on a
straightforward basis: every ACL combination is a created ACL.

As mentioned in the `rpk acl` help text, if no host is specified, an allowed
principal is allowed access from all hosts. The wildcard principal `*` allows
all principals. At least one principal, one host, one resource, and one
operation is required to create a single ACL.

Allow all permissions to user bar on topic `foo` and group `g`:

`rpk acl create --allow-principal bar --operation all --topic foo --group g`

Allow read permissions to all users on topics biz and baz:

`rpk acl create --allow-principal * --operation read --topic biz,baz`

Allow write permissions to user buzz to transactional id `txn`:

`rpk acl create --allow-principal User:buzz --operation write --transactional-id txn`

== Usage

----
rpk acl create [flags]
----

== Flags


[cols=",,",]
|===
|*Value* |*Type* |*Description*

|--allow-host |strings |Hosts from which access will be granted
(repeatable).

|--allow-principal |strings |Principals for which these permissions will
be granted (repeatable).

|--cluster |- |Whether to grant ACLs to the cluster.

|--deny-host |strings |Hosts from from access will be denied
(repeatable).

|--deny-principal |strings |Principal for which these permissions will
be denied (repeatable).

|--group |strings |Group to grant ACLs for (repeatable).

|-h, --help |- |Help for create.

|--operation |strings |Operation to grant (repeatable).

|--topic |strings |Topic to grant ACLs for (repeatable).

|--transactional-id |strings |Transactional IDs to grant ACLs for
(repeatable).
|===
