[NOTE]
====
include::shared:partial$enterprise-license.adoc[]
====

With data archiving, you can enable remote write to back up topics to cloud storage. In the event of a data center failure, data corruption, or cluster migration, you can recover your archived data from the cloud back to your cluster. Data archiving is a use case of xref:manage:tiered-storage.adoc[Tiered Storage].

Redpanda natively supports Tiered Storage with Amazon S3 and Google Cloud Storage (GCS). Migrating topics from one cloud provider to another is not supported.

== Prerequisites

include::shared:partial$enterprise-license.adoc[]

To check if you already have a license key applied to your cluster:

[,bash]
----
rpk cluster license info
----

== Configure data archiving

Data archiving requires a Tiered Storage configuration.

. xref:manage:tiered-storage.adoc#set-up-tiered-storage[Set up Tiered Storage] for the cluster or for specific topics.
. If you want to read data from cloud storage, xref:manage:tiered-storage.adoc#remote-read[enable remote read]. When remote read is disabled, data can only be read from local storage.
. xref:manage:tiered-storage.adoc#set-retention-limits[Set retention limits].

To recover a topic from cloud storage, use xref:manage:tiered-storage.adoc#remote-recovery[remote recovery].

== Stop data archiving

To cancel archiving jobs, disable remote write.

To delete archival data, adjust `retention.ms` or `retention.bytes`.













