For topics with Tiered Storage enabled, you can mount and unmount topics to transfer the topic data between your cluster and object storage. This effectively frees up unused partition space that can be reclaimed, enables you to migrate a topic to a different cluster, and allows the topic or even the entire cluster to hibernate or be decommissioned.

Redpanda also transfers topic definitions when mounting or unmounting a topic.

An unmounted topic in object storage is detached from all clusters. The original cluster releases ownership of the topic. You can mount a topic from object storage that has been previously flushed from a source cluster to a different destination cluster, or back to the same source cluster.

== Prerequisites

. xref:get-started:rpk-install.adoc[Install `rpk`], or ensure that you have access to the Admin API.
. Enable xref:manage:tiered-storage.adoc[Tiered Storage] for specific topics, or for the entire cluster (all topics).

== Unmount a topic from a cluster to object storage

When you unmount a topic, all incoming writes to the topic are blocked as Redpanda migrates the topic from the cluster to object storage. Producers and consumers of the topic receive an error message indicating that the topic is no longer available. The unmounted topic is deleted in the source cluster.

[tabs]
======
rpk::
+
--
In your cluster, run this command to unmount a topic to object storage:

```
rpk cluster storage unmount <namespace>/<topic-name>
```
--
Admin API::
+
--
To unmount topics from a cluster using the Admin API, make a POST request to the `/v1/topics/unmount` endpoint.  Specify the names of the desired topics in the request body:

```
curl -X POST http://localhost:9644/v1/topics/unmount -d {
  "topics": [
    {
      "topic": "<topic-1-name>"
    }, 
    {
      "topic": "<topic-2-name>"
    }, 
    {
      "topic": "<topic-3-name>"
    }
  ]
}
```

You may optionally include the topic namespace (`ns`). Only `kafka` is currently supported.
--
======


== Mount a topic to a cluster

[tabs]
======
rpk::
+
--
In your target cluster, run this command to mount a topic from object storage:

```
rpk cluster storage mount <source-topic-name>
```

You can also rename the topic as you mount it to the target cluster:

```
rpk cluster storage mount <namespace>/<source-topic-name> --to <namespace>/<new-topic-name>
```
--
Admin API::
+
--
To mount topics to a target cluster using the Admin API, make a POST request to the `/v1/topics/mount` endpoint. Specify the names of the topics in the request body:

```
curl -X POST http://localhost:9644/v1/topics/mount -d {
  "topics": [
    {
      "source_topic": {"ns": "kafka", "topic": "<source-topic-1-name>"}, 
      "alias": {"ns": "kafka", "topic": "<new-topic-1-name>"}
    }, 
    {
      "source_topic": {"ns": "kafka", "topic": "<source-topic-2-name>"}
    }, 
    {
      "source_topic": {"ns": "kafka", "topic": "source-topic-3-name"}, 
      "alias": {"ns": "kafka", "topic": "<new-topic-3-name>"}
    }
  ]
}
```

* `ns` is the topic namespace. This field is optional and only `kafka` is currently supported.
* To rename a topic in the target cluster, use the optional `alias` object in the request body. In the example, topics 1 and 3 are given new names in the target cluster, while topic 2 retains its original name.

--

======

When the migration is complete, the target cluster handles produce and consume workloads for the topics.

== Cancel a migration

You can cancel a topic migration by running the command:

[tabs]
======
rpk::
+
--
```
rpk cluster storage cancel-mount <migration-id>
```
--

Admin API::
+
--
```
curl -X POST http://localhost:9644/v1/<migration-id>/?action=cancel
```
--
======

You cannot cancel migrations in the following <<monitor-progress,states>>:

- `planned` (but you may still xref:api:ROOT:admin-api.adoc#delete-/v1/migrations/-id-[delete] a planned migration)
- `cut_over`
- `finished`
- `canceling`
- `cancelled`

== Monitor progress

[tabs]
======
rpk::
+
--
To list topic migrations, run the command:

```
rpk cluster storage list-mount
```
--

Admin API::
+
--
Issue a GET request to the `/migrations` endpoint to view the state of topic migrations:

```
curl http://localhost:9644/v1/migrations 
```
--
======

The response returns the IDs and state of existing migrations:

|===
| Migration state | Outbound migration (unmount) | Inbound migration (mount)

| `planned`
| Redpanda validates the migration definition.
|

| `preparing`
| Redpanda copies all possible topic data including topic manifests to the destination bucket or container in object storage.
| Redpanda recreates the topics in a disabled state in the target cluster. The cluster allocates partitions but does not add log segments yet. Topic metadata is populated from the topic manifests found in object storage.

| `prepared` 
| The migration is ready to execute. In this state, the cluster still accepts client reads and writes for the topics.
| Topics exist in the cluster but clients do not yet have access to consume or produce.

| `executing` 
| The cluster rejects client reads and writes for the topics. Redpanda uploads any remaining topic data that has not yet been copied to object storage. Uncommitted transactions involving the topic are aborted.
| The target cluster checks that the topic to be mounted has not already been mounted in any cluster.

| `executed` 
| All unmounted topic data from the cluster is available in object storage.
| 

| `cut_over`
| Redpanda deletes topic metadata from the cluster, and marks the data in object storage as available for mount operations.
| The topic data in object storage is no longer available to mount to any clusters.

| `finished`
| The migration is complete and then deleted. 
| The migration is complete and then deleted. The target cluster starts to handle produce and consume workloads.

| `canceling`
| Redpanda is in the process of canceling the migration.
|

| `cancelled`
| The migration is canceled.
|

|===

== Troubleshoot

If Redpanda encounters errors during mounting and unmounting, it retries the operation indefinitely. If you experience issues, check this list:

* You are attempting to mount a topic that does not exist in object storage.
* You are attempting to mount a topic that is already mounted to the current or a different cluster.
* Your Redpanda deployment is experiencing failures, such as Tiered Storage becoming unavailable, or multiple brokers going down.



