For topics with Tiered Storage enabled, you can mount and unmount topics to transfer the topic data between your cluster and object storage. This effectively frees up unused partition space that can be reclaimed, enables you to migrate a topic to a different cluster, and allows the topic or even the entire cluster to hibernate or be decommissioned.

You can mount a topic from object storage that has been previously flushed from a source cluster to a different destination cluster, or back to the same source cluster.

The following data is moved to object storage when unmounting a topic from a cluster:

* Topic definitions. 
* The consumer offsets topic. This allows the destination cluster to also restore consumer group state.

== Prerequisites

. Enable Tiered Storage for specific topics, or for the entire cluster (all topics).
. Install `rpk`, or ensure that you have access to the Admin API.


== Mount a topic to a cluster

In your target cluster, run this command to mount a topic from object storage:

[tabs]
====
rpk::
+
--
```
rpk topic mount <topic-name> -u <cloud-storage-url>
```
--
Admin API::
+
--
```

```
--

====

== Unmount a topic from a cluster to object storage

Run this command to flush a topic from the source cluster to object storage. This deletes the topic from the cluster. Once you initiate this process, all incoming writes to the topic are blocked. Producers and consumers of the topic receive an error message indicating that the topic is no longer available. 

[tabs]
====
rpk::
+
--
```
rpk topic unmount <topic-name>
```
--
Admin API::
+
--
```

```
--

====

== Monitor progress
