ifdef::env-kubernetes[]
:link-tiered-storage: manage:kubernetes/tiered-storage/k-tiered-storage.adoc
endif::[]
ifndef::env-kubernetes[]
:link-tiered-storage: manage:tiered-storage.adoc
endif::[]

[NOTE]
====
include::shared:partial$enterprise-license.adoc[]
====

When you create a topic, you can use remote recovery to download the topic data from object storage. This is useful when you need to restore a single topic in Tiered Storage that was accidentally deleted from a cluster.

include::manage:partial$topic-recovery-warning.adoc[]

== Prerequisites

You must have:

- xref:{link-tiered-storage}[Tiered Storage] enabled on your Redpanda cluster.

- xref:{link-tiered-storage}#remote-read[Remote read] (`redpanda.remote.read`) enabled on the topic you want to recover.

== Limitations

- Remote recovery is only safe when no other clusters are writing to the same bucket or container.
- If you disable `redpanda.remote.read` after remote recovery, previously downloaded data will not be used to serve requests.

== Recover a topic

To create a new topic using remote recovery, in which the recovered topic can read and write in the cloud:

[,bash]
----
rpk topic create <topic_name> -c redpanda.remote.recovery=true -c redpanda.remote.write=true -c redpanda.remote.read=true
----

To create a new topic using remote recovery, while also disabling the `redpanda.remote.write` property:

[,bash]
----
rpk topic create <topic_name> -c redpanda.remote.recovery=true -c redpanda.remote.write=false -c redpanda.remote.read=true
----