//tag::deployment[]
=== A Redpanda Enterprise Edition license is required

During a Redpanda upgrade, if enterprise features are enabled and a valid Enterprise Edition license is missing, Redpanda logs a warning and aborts the upgrade process on the affected broker. This issue prevents a successful upgrade.

If you encounter this issue, follow these steps to recover:

. Downgrade the affected broker to the original version.
. Do one of the following:
- xref:get-started:licensing/add-license-redpanda/index.adoc[Apply a valid Redpanda Enterprise Edition license] to the cluster.
- Disable Enterprise features.
+
If you do not have a valid license and want to proceed without using Enterprise features, you can disable the enterprise features in your Redpanda configuration.

. Retry the upgrade.


//end::deployment[]

//tag::tls[]
=== Invalid large response size

This error appears when your cluster is configured to use TLS, but you don't specify that you are connecting over TLS.

[.no-copy]
----
unable to request metadata: invalid large response size 352518912 > limit 104857600; the first three bytes received appear to be a tls alert record for TLS v1.2; is this a plaintext connection speaking to a tls endpoint?
----

If you're using rpk, ensure to add the `-X tls.enabled` flag, and any other necessary TLS flags such as the TLS certificate:

[,bash]
----
ifdef::env-kubernetes[kubectl exec <pod-name> -c redpanda --namespace <namespace> -- \]
rpk cluster info -X tls.enabled=true
----

For all available flags, see the xref:reference:rpk/index.adoc[rpk command reference].

=== Malformed HTTP response

This error appears when a cluster has TLS enabled, and you try to access the admin API without passing the required TLS parameters.

[.no-copy]
----
Retrying POST for error: Post "http://127.0.0.1:9644/v1/security/users": net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x03\x00\x02\x02"
----

If you're using rpk, ensure to include the TLS flags.

For all available flags, see the xref:reference:rpk/index.adoc[rpk command reference].

=== x509: certificate signed by unknown authority

This error appears when the Certificate Authority (CA) that signed your certificates is not trusted by your system.

Check the following:

- Ensure you have installed the root CA certificate correctly on your local system.
- If using a self-signed certificate, ensure it is properly configured and included in your system's trust store.
- If you are using a certificate issued by a CA, ensure the issuing CA is included in your system's trust store.
ifdef::env-kubernetes[]
- If you are using cert-manager, ensure it is correctly configured and running properly.
endif::[]
- Check the validity of your certificates. They might have expired.

=== x509: certificate is not valid for any names

This error indicates that the certificate you are using is not valid for the specific domain or IP address you are trying to use it with. This error typically occurs when there is a mismatch between the certificate's Subject Alternative Name (SAN) or Common Name (CN) field and the name being used to access the broker.

To fix this error, you may need to obtain a new certificate that is valid for the specific domain or IP address you are using. Ensure that the certificate's SAN or CN entry matches the name being used, and that the certificate is not expired or revoked.

=== cannot validate certificate for 127.0.0.1

This error appears if you are using a CA certificate when you try to establish an internal connection using localhost. For example:

```
unable to request metadata: unable to dial: x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs
```

To fix this error, you must either specify the URL with a public domain or use self-signed certificates:

[,bash]
----
ifdef::env-kubernetes[kubectl exec redpanda-0 -c redpanda --namespace <namespace> -- \]
rpk cluster info \
-X brokers=<redpanda-url>:<port> \
-X tls.enabled=true
----

//end::tls[]

//tag::sasl[]
=== Is SASL missing?

This error appears when you try to interact with a cluster that has SASL enabled without passing a user's credentials.

[.no-copy]
----
unable to request metadata: broker closed the connection immediately after a request was issued, which happens when SASL is required but not provided: is SASL missing?
----

If you're using rpk, ensure to specify the `-X user`, `-X pass`, and `-X sasl.mechanism` flags.

For all available flags, see the xref:reference:rpk/index.adoc[rpk command reference].
//end::sasl[]