= SQL Reference

This section provides information about the syntax and semantics of SQL queries, clauses, data types, and functions that Oxla supports. The information in this section is divided into groups according to the kind of operation they perform as follows:

== SQL Statements

Learn how to create a request for data or information from one or more database tables using our supported statements.

xref:oxla-reference:sql-statements/overview.adoc[View SQL Statements]

== SQL Clauses

This sub-section shows you how to write user-friendly queries and analyze data using different constraints and conditions.

xref:oxla-reference:sql-clauses/overview.adoc[View SQL Clauses]

== SQL Data Types

This sub-section will guide you through implementing our supported data types to run your operations, such as text, timestamp, numeric, and many more.

xref:oxla-reference:sql-data-types/overview.adoc[View SQL Data Types]

== SQL Functions

Functions help you perform various operations on your data. We support various categories of functions including math, string, timestamp, aggregate, window, and more.

xref:oxla-reference:sql-functions/overview.adoc[View SQL Functions]

== SQL Mutations

Learn about UPDATE and DELETE operations to modify and remove data from your tables.

xref:oxla-reference:sql-mutations/overview.adoc[View SQL Mutations]

== Additional Topics

* xref:oxla-reference:schema.adoc[Schema]
* xref:oxla-reference:comment-support.adoc[Comment Support]
* xref:oxla-reference:transactions.adoc[Transactions]
