= Kubernetes Compatibility
:description: Find a compatibility matrix for versions of Redpanda, Redpanda Helm chart, and Redpanda Operator.

This topic describes the compatibility for versions of Redpanda, Redpanda Kubernetes Operator, and the Helm charts. The tables identify the versions required and supported for running the specified version of Redpanda.

include::partial$versioning.adoc[]

The latest version of the Redpanda Helm chart supports not only the most recent Redpanda release but also the previous two feature releases, regardless of the two-digit year.

Support is conditional on the preceding releases still being actively supported. In cases where any of the preceding releases are no longer supported, the Helm chart does not support them.

== Redpanda Helm chart compatibility

The Redpanda Helm chart is compatible with these versions of Redpanda, Kubernetes, and Helm.

include::upgrade:partial$k-redpanda-chart-compatibility-matrix.adoc[]

By default, the Redpanda Helm chart depends on cert-manager for enabling TLS.
Make sure to install a version of the cert-manager CRDs that supports the `certificates.cert-manager.io/v1` resource.
See the https://github.com/cert-manager/cert-manager/releases[cert-manager release notes].

== Redpanda Operator compatibility

Each version of the Redpanda Operator, including its corresponding set of custom resource definitions (CRDs), supports specific versions of the Redpanda Helm chart.

Although new releases of the Redpanda Operator are backward compatible with existing versions of the Redpanda Helm chart, new releases of the Redpanda Helm chart might introduce changes to the Helm values, which could require you to upgrade both the Redpanda Operator and the accompanying CRDs.

Consider the following best practices for upgrades:

- *Prioritize updating the Redpanda Operator*: Always aim to use the latest version of the Redpanda Operator. The newer versions are backward compatible with existing versions of the Redpanda Helm chart, ensuring stability and access to the latest features and fixes.

- *Check the release notes before Redpanda Helm chart upgrades*: New releases of the Redpanda Helm chart might introduce changes to the Helm values, which could require a corresponding upgrade of both the Redpanda Operator and the CRDs to ensure compatibility.

[cols="4*m"]
|===
| Redpanda Operator Helm Chart | Redpanda Operator|CRD | Supported Redpanda Helm Chart

| 0.4.x
| 2.0.x
| v1alpha1
| 5.6.x
|===

== Redpanda Console compatibility

Redpanda Console is integrated as a subchart within these versions of the Redpanda Helm chart. The version of Redpanda Console that is installed depends on the version of the Redpanda Helm chart you choose to install. This interdependency is established when you add or update the Redpanda chart repository, linking a particular version of Redpanda Console with the corresponding version of the Helm chart.

As a result of this integration, any updates you apply to the Redpanda Helm chart might also lead to changes in the version of the Redpanda Console. This means that selecting a different version of the Helm chart can automatically determine the version of the Console that gets installed or updated in your environment.

Redpanda Console is backwards compatible with all versions of Redpanda.

For more details about the Redpanda Console charts, see https://artifacthub.io/packages/helm/redpanda-data/console[Artifact Hub].

include::upgrade:partial$k-redpanda-console-chart-dependencies.adoc[]

== Next steps

- xref:deploy:deployment-option/self-hosted/kubernetes/kubernetes-deploy.adoc[Deploy Redpanda in Kubernetes]
- xref:k-rolling-upgrade.adoc[Upgrade Redpanda in Kubernetes]