= Kubernetes Compatibility
:description: A compatibility matrix for versions of Redpanda, Redpanda Helm chart, and Redpanda Operator.
:page-categories: Upgrades

This topic describes the compatibility for versions of Redpanda, Redpanda Operator, and the Helm charts. The tables identify the version requirements and compatibility guidelines.

include::partial$versioning.adoc[]

== Versioning scheme and compatibility policy

The Redpanda Helm chart and Redpanda Operator are versioned and tested alongside specific Redpanda core releases, Kubernetes, and Helm.

Starting from version v25.1-k8s1-beta1, the Redpanda Operator and Redpanda Helm chart follow a new versioning scheme aligned with Redpanda core releases:

- `v25.1` refers to the Redpanda core feature release deployed by default.

- The suffix `-k8s<number>` denotes the Kubernetes-specific version, where `<number>` is the unique patch version for either the operator or Helm chart.

Each Redpanda Operator and Helm chart version supports the corresponding Redpanda core version plus one minor version above and one below. This approach ensures flexibility and ease during upgrades. For example, Redpanda Operator version 25.1-k8sx supports Redpanda core versions 25.2.x, 25.1.x, and 24.3.x.

Redpanda Operator and Helm chart versions are supported only while their associated Redpanda core version remains supported. If the core version reaches End-of-Life (EoL), the corresponding Operator and Helm chart versions also reach EoL.

NOTE: Beta versions are available only for testing and feedback. They are not supported by Redpanda and should not be used in production environments. To give feedback on beta releases, reach out to the Redpanda team in https://redpanda.com/slack[Redpanda Community Slack^].

== Compatibility matrix

[cols="1a,1a,1a,1a,1a,1a"]
|===
|Redpanda Core / `rpk` |Helm Chart |Operator Helm Chart |Operator |Helm CLI |Kubernetes

// |25.2.x
// |25.3-k8sx, 25.2-k8sx, 25.1-k8sx
// |25.3-k8sx, 25.2-k8sx, 25.1-k8sx
// |25.3-k8sx, 25.2-k8sx, 25.1-k8sx
// |3.13+
// |1.30.x - 1.33.x

|25.1.x
|25.1-k8s-beta, 5.10.x, 5.9.x
|25.1-k8s-beta, 0.4.41, 0.4.36
|25.1-k8s-beta, 2.4.x, 2.3.x
|3.12+
|1.29.x - 1.32.x

|24.3.x
|25.1-k8s-beta, 5.9.x
|25.1-k8s-beta, 0.4.41, 0.4.36, 0.4.29
|25.1-k8s-beta, 2.4.x, 2.3.x, 2.2.x
|3.11+
|1.28.x - 1.31.x

|24.2.x
|5.9.x, 5.8.x
|0.4.29
|2.2.x
|3.10+
|1.27.x - 1.30.x
|===

By default, the Redpanda Helm chart depends on cert-manager for enabling TLS.
Make sure to install a version of the cert-manager CRDs that supports the `certificates.cert-manager.io/v1` resource.
See the https://github.com/cert-manager/cert-manager/releases[cert-manager release notes].

== Redpanda Console integration

Redpanda Console is integrated as a subchart within the Redpanda Helm chart. Each version of the Redpanda Helm chart defines a range of versions of the Redpanda Console chart that it supports. The version of Redpanda Console that is installed depends on the version of the Redpanda Helm chart you choose to install.

This interdependency is established when you add or update the Redpanda chart repository, linking a particular version of Redpanda Console with the corresponding version of the Redpanda Helm chart. As a result of this integration, any updates you apply to the Redpanda Helm chart might also lead to changes in the version of the Redpanda Console. This means that selecting a different version of the Redpanda Helm chart can automatically determine the version of the Console that gets installed or updated in your environment.

[cols="1a,1a,1a"]
|===
|Redpanda Console |Helm Chart |Operator

|v3.x.x
|v25.1-k8s-beta
|v25.1-k8s-beta

|v2.x.x
| 5.10.1, 5.9.x, 5.8.x
|2.4.x, 2.3.x, 2.2.x

|===

== Next steps

- xref:deploy:deployment-option/self-hosted/kubernetes/kubernetes-deploy.adoc[Deploy Redpanda in Kubernetes]
- xref:k-rolling-upgrade.adoc[Upgrade Redpanda in Kubernetes]
