= Kubernetes Compatibility
:description: A compatibility matrix for versions of Redpanda, Redpanda Helm chart, and Redpanda Operator.
:page-categories: Upgrades
:fn-k8s-compatibility: footnote:fn-k8s-compatibility[These Kubernetes versions are suggested ranges, based on testing and reported usage. Not every patch or minor version within these ranges is explicitly tested.]

This topic describes the compatibility for versions of Redpanda, Redpanda Operator, and the Helm charts. The tables identify the version requirements and compatibility guidelines.

include::partial$versioning.adoc[]

== Versioning scheme and compatibility policy

The Redpanda Helm chart and Redpanda Operator are versioned and tested alongside specific Redpanda core releases, Kubernetes, and Helm.

Starting from version v25.1.1, the Redpanda Operator and Redpanda Helm chart follow a new versioning scheme aligned with Redpanda core releases:

- `v25.1` refers to the Redpanda core feature release deployed by default.

- The patch version denotes the patch version for either the operator or Helm chart. It is not the patch version of Redpanda core.

NOTE: If a version includes `-beta`, it is a pre-release version of the Redpanda Operator and Helm chart. These versions are not supported and should not be used in production environments. Beta versions are available only for testing and feedback. To give feedback on beta releases, reach out to the Redpanda team in https://redpanda.com/slack[Redpanda Community Slack^].

Each Redpanda Operator and Helm chart version supports the corresponding Redpanda core version plus one minor version above and one below. This approach ensures flexibility during upgrades. For example, Redpanda Operator version 25.1.1 supports Redpanda core versions 25.2.x, 25.1.x, and 24.3.x.

Redpanda Operator and Helm chart versions are supported only while their associated Redpanda core version remains supported. If the core version reaches end of life (EoL), the corresponding versions of the Redpanda Operator and Helm chart also reach EoL.

== Kubernetes version policy

The Kubernetes versions listed in the compatibility matrix are suggested ranges, based on testing and reported usage. Not every patch or minor version within these ranges is explicitly tested.

To request compatibility testing of a Kubernetes version outside of the given ranges, contact https://support.redpanda.com/hc/en-us/requests/new[Redpanda support^].

Redpanda Core has no direct dependency on Kubernetes. Compatibility is influenced indirectly by the Helm chart or Operator that you use.

== Compatibility matrix

[cols="1a,1a,1a,1a,1a,1a"]
|===
|Redpanda Core / `rpk` |Helm Chart |Operator Helm Chart |Operator |Helm CLI |Kubernetes

.2+|25.2.x

|25.2.x
|25.2.x
|25.2.x
|3.12+
d|1.30.x - 1.33.x{fn-k8s-compatibility}

|25.1.x
|25.1.x
|25.1.x
|3.12+
d|1.28.x - 1.32.x{fn-k8s-compatibility}

.3+|25.1.x
|25.1.x
|25.1.x
|25.1.x
|3.12+
// d (default) here is required to get footnotes to appear at the bottom of the page
// instead of inside the table cell.
// See https://github.com/asciidoctor/asciidoctor/issues/2350#issuecomment-546841684
d|1.28.x - 1.32.x{fn-k8s-compatibility}

|5.10.x
|2.4.x
|2.4.x
|3.12+
d|1.28.x - 1.32.x{fn-k8s-compatibility}

|5.9.x
|0.4.36
|2.3.x
|3.12+
d|1.28.x - 1.32.x{fn-k8s-compatibility}

.4+|24.3.x
|25.1.x
|25.1.x
|25.1.x
|3.11+
d|1.28.x - 1.32.x{fn-k8s-compatibility}

|5.9.x
|0.4.41
|2.4.x
|3.11+
d|1.28.x - 1.31.x{fn-k8s-compatibility}

|5.9.x
|0.4.36
|2.3.x
|3.11+
d|1.28.x - 1.31.x{fn-k8s-compatibility}

|5.9.x
|0.4.29
|2.2.x
|3.11+
d|1.28.x - 1.31.x{fn-k8s-compatibility}

.2+|24.2.x
|5.9.x
|0.4.29
|2.2.x
|3.10+
d|1.27.x - 1.30.x{fn-k8s-compatibility}

|5.8.x
|0.4.29
|2.2.x
|3.10+
d|1.27.x - 1.30.x{fn-k8s-compatibility}
|===

By default, the Redpanda Helm chart depends on cert-manager for enabling TLS.
Make sure to install a version of the cert-manager CRDs that supports the `certificates.cert-manager.io/v1` resource.
See the https://github.com/cert-manager/cert-manager/releases[cert-manager release notes].

== Redpanda Console integration

Redpanda Console is deployed through the Redpanda Helm chart. It is included as a subchart, and its version is determined by the version of the parent Helm chart.

The Redpanda Helm chart defines which Redpanda Console versions it supports. When you install or update the Helm chart, it automatically selects the appropriate Redpanda Console version.

Upgrading the Helm chart may also upgrade Redpanda Console. Because of this built-in dependency, selecting a different Helm chart version can change the Redpanda Console version deployed in your environment.

[cols="1a,1a,1a"]
|===
|Redpanda Console |Helm Chart |Operator

|v3.x.x
|25.2.x, 25.1.x
|Not yet supported

|v2.x.x
|5.10.1, 5.9.x, 5.8.x
|25.2.x, 25.1.x, 2.4.x, 2.3.x, 2.2.x

|===

== Next steps

- xref:deploy:deployment-option/self-hosted/kubernetes/kubernetes-deploy.adoc[Deploy Redpanda in Kubernetes]
- xref:k-rolling-upgrade.adoc[Upgrade Redpanda in Kubernetes]
