= Upgrade Redpanda in Kubernetes
:description: To benefit from Redpanda's new features and enhancements, upgrade to the latest version.
:page-context-links: [{"name": "Linux", "to": "upgrade:rolling-upgrade.adoc" },{"name": "Kubernetes", "to": "upgrade:k-rolling-upgrade.adoc" } ]
:page-aliases: manage:kubernetes/rolling-upgrade.adoc
:page-categories: Upgrades
:env-kubernetes: true

To benefit from Redpanda's new features and enhancements, upgrade to the latest version. New features are available after all brokers in the cluster are upgraded and restarted.

include::partial$versioning.adoc[]

include::partial$rolling-upgrades/upgrade-limitations.adoc[]

== Prerequisites

* xref:deploy:deployment-option/self-hosted/kubernetes/index.adoc[A Redpanda cluster running in Kubernetes].
* The default xref:reference:k-redpanda-helm-spec.adoc#statefulset-updatestrategy-type[RollingUpdate strategy] configured in the Helm values.

include::partial$incompat-changes.adoc[]

include::partial$rolling-upgrades/restart-impact.adoc[leveloffset=+1]

== Check your current Redpanda version

Before you perform a rolling upgrade:

- Find the Redpanda version that you are currently running.
+
To find your current version of Redpanda, use xref:reference:rpk/rpk-redpanda/rpk-redpanda-admin-brokers-list.adoc[`rpk redpanda admin brokers list`]:
+
```bash
kubectl exec <pod-name> --namespace <namespace> -c redpanda -- \
  rpk redpanda admin brokers list
```
+
.Expected output:
[%collapsible]
====
The Redpanda version for each broker is listed under `BROKER-VERSION`.
[role="no-copy",subs="attributes+"]
```
NODE-ID  BROKER-VERSION
0        {latest-redpanda-tag}
1        {latest-redpanda-tag}
2        {latest-redpanda-tag}
```
====
- xref:upgrade:k-compatibility.adoc[Review the Kubernetes compatibility matrix] to find out if you need to upgrade the Helm chart or the Redpanda Operator to use your chosen version of Redpanda.
+
If your current version of Redpanda is more than one feature release behind the one to which you want to upgrade, you must first upgrade to an intermediate version of Redpanda.
- Learn what's changed since your original version.
+
To find information about what has changed between Redpanda versions, check the https://github.com/redpanda-data/redpanda/releases[release notes^].

== Check license status

If you use xref:get-started:licensing/overview.adoc#self-managed[enterprise features] of Redpanda, make sure that you have a valid Enterprise Edition license key. From version 24.3, Redpanda fails to upgrade to a new feature release if you have enterprise features enabled without a valid license key.

include::get-started:partial$licensing/check-license.adoc[]

== Prepare your cluster

Before you upgrade, you must make sure that your cluster is in a healthy state and that your topics are configured to limit outages during the upgrade process.

. Check for topics that have a replication factor greater than one.
+
If you have topics with a replication factor of 1, and if you have sufficient disk space, temporarily xref:manage:data-migration.adoc#change-topic-replication-factor[increase the replication factor] to limit outages for these topics during the rolling upgrade.
+
Increase the replication factor before you upgrade to ensure that Redpanda has time to replicate data to other brokers.

. Ensure that the cluster is healthy:
+
```bash
kubectl exec <pod-name> --namespace <namespace> -c redpanda -- \
  rpk cluster health
```
+
The draining process won't start until the cluster is healthy.
+
.Example output:
[%collapsible]
====
[.no-copy]
----
CLUSTER HEALTH OVERVIEW
=======================
Healthy:                     true <1>
Controller ID:               0
All nodes:                   [0 1 2] <2>
Nodes down:                  [] <3>
Leaderless partitions:       [] <3>
Under-replicated partitions: [] <3>
----
<1> The cluster is either healthy (`true`) or unhealthy (`false`).
<2> The node IDs of all brokers in the cluster.
<3> These fields contain data only when the cluster is unhealthy.
====

[[upgrade]]
== Perform a rolling upgrade

Performing a rolling upgrade allows you to update the version of Redpanda managed by the Redpanda Helm chart without downtime. This process ensures that each broker is sequentially updated and restarted, minimizing the impact on your environment.

You can use two methods to upgrade a Redpanda cluster in Kubernetes. The first method is to upgrade the Helm release to a newer version of the Redpanda Helm chart that uses the desired Redpanda version as a default. The second method is to update the existing Helm release to use a newer Redpanda image. The first method is preferred because upgrading the entire chart ensures that any new parameters required to configure the cluster are defined.

Upgrading a Redpanda cluster in Kubernetes triggers a sequential restart of the Pods managed by the StatefulSet. During each broker's restart, the following steps occur:

- The `preStop` lifecycle hook is executed to place the broker into maintenance mode. This step ensures that the broker stops accepting new connections and finishes processing its current tasks.
- Kubernetes then terminates the Pod. If the broker does not shut down within the allowed grace period (default 90 seconds), Kubernetes forcefully terminates it using a `SIGKILL` signal.
- After the Pod is terminated, the `postStart` lifecycle hook is executed to take the broker out of maintenance mode, allowing it to rejoin the cluster once restarted.

[tabs]
======
Operator::
+
--

. xref:upgrade:k-compatibility.adoc[Review the Kubernetes compatibility matrix] and determine the version of the Redpanda Operator that is compatible with the Helm chart version you plan to use. The Redpanda Operator must be able to understand and manage the Helm chart and the Redpanda version you are deploying. If you need to upgrade, see xref:upgrade:k-upgrade-operator.adoc[].

. Check the default Redpanda version of a chart to make sure that it uses the version that you want to upgrade your cluster to.
+
[source,bash]
----
helm show chart --version <chart-version> redpanda/redpanda | grep  "appVersion"
----
+
Replace `<chart-version>` with the version number of a newer chart.

. Upgrade the Redpanda version by either updating the Helm chart version or the Redpanda image.
+
.`redpanda-cluster.yaml`
[source,yaml]
----
apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
  name: redpanda
spec:
  chartRef:
    chartVersion: <helm-chart-version> <1>
  clusterSpec:
    image:
      # Optional
      tag: <new-version> <2>
    statefulset:
      # Optional
      terminationGracePeriodSeconds: <grace-period> <3>
----
+
<1> The version of the Redpanda Helm chart to deploy.
<2> If you need to upgrade to an intermediate version of Redpanda, use this setting to specify the version of Redpanda to deploy. This version overrides the default one in the Helm chart. Replace `<new-version>` with a valid version tag.
<3> The xref:reference:k-redpanda-helm-spec.adoc#statefulsetterminationgraceperiodseconds[`statefulset.terminationGracePeriodSeconds`] setting defines how long Kubernetes will wait for the broker to shut down gracefully before forcefully terminating it. The default value is 90 seconds, which is enough for most clusters, but might require adjustment based on your workload. Modify this setting in your Helm values file if your Redpanda brokers have high loads or hold large amounts of data, as they might need more time to shut down gracefully.

. Apply the Redpanda resource to deploy the Redpanda cluster:
+
```bash
kubectl apply -f redpanda-cluster.yaml --namespace <namespace>
```

--
Helm::
+
--

. xref:upgrade:k-compatibility.adoc[Review the Kubernetes compatibility matrix] and verify which version of the Redpanda Helm chart supports the Redpanda version you plan to upgrade to. The Helm chart version can dictate which configurations and Kubernetes resources are available or required for that specific version of Redpanda.

. Check the default Redpanda version of a chart to make sure that it uses the version that you want to upgrade your cluster to.
+
[source,bash]
----
helm show chart --version <chart-version> redpanda/redpanda | grep  "appVersion"
----
+
Replace `<chart-version>` with the version number of a newer chart.

. Back up your current Helm values for the Redpanda Helm chart:
+
[source,bash]
----
helm get values redpanda --namespace <namespace> > redpanda-values-backup.yaml
----
+
You'll need to apply these overrides in the next step.

. Optional: Update the following settings:
+
.`redpanda-version.yaml`
[,yaml]
----
image:
  tag: <new-version> <1>
statefulset:
  terminationGracePeriodSeconds: <grace-period> <2>
----
+
<1> If you need to upgrade to an intermediate version of Redpanda, use this setting to specify the version of Redpanda to deploy. This version overrides the default one in the Helm chart. Replace `<new-version>` with a valid version tag.
<2> The xref:reference:k-redpanda-helm-spec.adoc#statefulsetterminationgraceperiodseconds[`statefulset.terminationGracePeriodSeconds`] setting defines how long Kubernetes will wait for the broker to shut down gracefully before forcefully terminating it. The default value is 90 seconds, which is enough for most clusters, but might require adjustment based on your workload. Modify this setting in your Helm values file if your Redpanda brokers have high loads or hold large amounts of data, as they might need more time to shut down gracefully.

. Deploy Redpanda with the new Helm chart version:
+
```bash
helm upgrade --install redpanda redpanda/redpanda --namespace <namespace> \
  --create-namespace \
  --version <helm-chart-version> \
  --values redpanda-version.yaml
```
+
Make sure to include all existing overrides, otherwise the upgrade may fail.
For example, if you already enabled SASL, include the same SASL overrides.
+
CAUTION: Do not use the `--reuse-values` flag, otherwise Helm won't include any new values from the upgraded chart.
--
======

== Verify the upgrade

After upgrading, verify that your Redpanda cluster is functioning correctly:

. Wait for the Pods to be terminated and recreated with the new version of Redpanda.
+
[,bash]
----
kubectl get pod --namespace <namespace> --watch
----
+
Each Pod in the StatefulSet is terminated one at a time, starting from the one with the highest ordinal.
+
.Example output
[%collapsible]
====
[.no-copy]
----
NAME                                    READY   STATUS
redpanda-controller-operator            2/2     Running
redpanda-0                              2/2     Running
redpanda-1                              2/2     Running
redpanda-2                              0/2     Init:0/3
redpanda-configuration-88npt            0/1     Completed
redpanda-console-7cf85cf87f-rmtnj       1/1     Running
redpanda-post-upgrade-ljqpr             0/1     Completed
----
====

. When all of the Pods are ready and have a `Running` status, verify that the brokers are now running the upgraded version of Redpanda:
+
```bash
kubectl exec <pod-name> --namespace <namespace> -c redpanda -- \
  rpk redpanda admin brokers list
```

== Roll back

If something does not go as planned during a rolling upgrade, you can roll back to the original version as long as you have not upgraded all brokers.

The StatefulSet uses the `RollingUpdate` strategy by default in xref:reference:k-redpanda-helm-spec.adoc#statefulsetupdatestrategytype[`statefulset.updateStrategy.type`],
which means all Pods in the StatefulSet are restarted in reverse-ordinal order. For details, see the https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#update-strategies[Kubernetes documentation^].

[tabs]
======
Operator::
+
--
Revert the change that you made to the version and reapply the manifest.
--
Helm::
+
--
. Find the previous revision:
+
```bash
helm history redpanda --namespace <namespace>
```
+
Example output
+
[.no-copy]
----
REVISION	UPDATED                 	STATUS    	CHART          	APP VERSION	DESCRIPTION
1       	Fri Mar  3 15:16:24 year	superseded	redpanda-2.12.2	v22.3.13   	Install complete
2       	Fri Mar  3 15:19:41 year	deployed	  redpanda-2.12.2	v22.3.13   	Upgrade complete
----

. Roll back to the previous revision:
+
```bash
helm rollback redpanda <previous-revision> --namespace <namespace>
```

. Verify that the cluster is healthy. If the cluster is unhealthy, the upgrade may still be in progress. The command exits when the cluster is healthy.
+
```bash
kubectl exec <pod-name> --namespace <namespace> -c redpanda -- \
  rpk cluster health \
  --watch --exit-when-healthy
```
+
.Example output:
[%collapsible]
====
[.no-copy]
```
CLUSTER HEALTH OVERVIEW
=======================
Healthy:               true
Controller ID:         1
All nodes:             [2,1,0]
Nodes down:            []
Leaderless partitions: []
```
====
--
======

== Troubleshooting

include::troubleshoot:partial$errors-and-solutions.adoc[tags=deployment]

include::shared:partial$suggested-reading.adoc[]

Set up a real-time dashboard to monitor your cluster health, see xref:manage:kubernetes/monitoring/index.adoc[Monitor Redpanda].
