= Upgrade Redpanda in Kubernetes
:description: To benefit from Redpanda's new features and enhancements, upgrade to the latest version.
:page-context-links: [{"name": "Linux", "to": "upgrade:rolling-upgrade.adoc" },{"name": "Kubernetes", "to": "upgrade:k-rolling-upgrade.adoc" } ]
:page-aliases: manage:kubernetes/rolling-upgrade.adoc

To benefit from Redpanda's new features and enhancements, upgrade to the latest version. New features are available after all brokers in the cluster are upgraded and restarted.

Redpanda platform version numbers follow the convention AB.C.D, where AB is the two digit year, C is the feature release, and D is the patch release. For example, version 22.3.1 indicates the first patch release on the third feature release of the year 2022. Patch releases include bug fixes and minor improvements, with no change to user-facing behavior. New and enhanced features are documented with each feature release. You can find a list of all releases on https://github.com/redpanda-data/redpanda/releases[GitHub^].

include::partial$rolling-upgrades/upgrade-limitations.adoc[]

== Prerequisites

* xref:deploy:deployment-option/self-hosted/kubernetes/index.adoc[A Redpanda cluster running in Kubernetes].
* https://stedolan.github.io/jq/download/[jq^] for listing available versions.
* An understanding of the <<impact-of-broker-restarts,impact of broker restarts>> on clients, node CPU, and any alerting systems you use.
* <<Review incompatible changes>> in new versions.

include::partial$rolling-upgrades/restart-impact.adoc[leveloffset=+1]

== Review incompatible changes

Patch releases in https://github.com/redpanda-data/redpanda/discussions/9522[22.3.14^] and https://github.com/redpanda-data/redpanda/discussions/9523[23.1.2^] changed the behavior when remote read is disabled and the requested Raft term falls below the local log's beginning. In earlier versions, Redpanda returned an offset -1. With the patch, when you request a value older than the lowest offset, Redpanda returns the lowest offset, not -1.

== Find a new version

Before you perform a rolling upgrade, you must find out:

- Which Redpanda version you are currently running.
- Whether you can upgrade directly to the new version.
- What's changed since your original version.


. Find your current version of Redpanda:
+
```bash
kubectl exec <pod-name> --namespace <namespace> -c redpanda -- \
  rpk redpanda admin brokers list
```
+
For all available flags, see the xref:reference:rpk/rpk-redpanda/rpk-redpanda-admin-brokers-list.adoc[`rpk redpanda admin brokers list` command reference].
+
.Expected output:
[%collapsible]
====
The Redpanda version for each broker is listed under `BROKER-VERSION`.
[.no-copy]
```
NODE-ID  BROKER-VERSION
0        v22.2.10
1        v22.2.10
2        v22.2.10
```
====

. Find the Redpanda version that's used in the latest version of the Redpanda Helm chart:
+
[,bash]
----
helm repo update && \
helm show chart redpanda/redpanda | grep appVersion
----
+
Example output:
+
[.no-copy]
----
appVersion:	v22.2.10
----
+
[NOTE]
====
If your current version is more than one feature release behind the version in the latest Redpanda Helm chart, you must first upgrade to an intermediate version. To list all available versions:

```bash
curl -s 's://hub.docker.com/v2/repositories/redpandadata/redpanda/tags/?ordering=last_updated&page=1&page_size=50' | jq -r '.results[].name'
```
====

. Check the https://github.com/redpanda-data/redpanda/releases[release notes^] to find information about what has changed between Redpanda versions.

== Perform a rolling upgrade

A rolling upgrade involves running the following procedure on each broker, one at a time:

. Upgrade the version of Redpanda on the broker that's running in the Pod with the highest ordinal.
. Place the broker into maintenance mode.
. Wait for maintenance mode to finish.
. Terminate the Pod so that it is recreated with the new version of Redpanda.
. Take the broker out of maintenance mode.

Placing brokers into maintenance mode ensures a smooth upgrade of your cluster while reducing the risk of interruption or degradation in service. When a broker is placed into maintenance mode, it reassigns its partition leadership to other brokers for all topics that have a replication factor greater than one (three is the default replication factor for topics). Reassigning partition leadership involves _draining_ leadership from the broker and _transferring_ that leadership to another broker.

[NOTE]
====
The Redpanda Helm chart and the Redpanda Operator automate this procedure.

The Helm chart's `preStop` lifecycle hook puts each broker into maintenance mode before the Pod that it's running on is terminated. If maintenance mode does not complete before the `terminationGracePeriod` the container is forcefully terminated using a `SIGKILL` command.

The default `terminationGracePeriod` is 90 seconds, which should be long enough for large clusters.
You can test different values in a development environment.
To configure the `terminationGracePeriod`,
use the xref:reference:redpanda-helm-spec.adoc#statefulsetterminationgraceperiodseconds[`statefulset.terminationGracePeriodSeconds`] setting.
====

To upgrade:

. Check for topics that have a replication factor greater than one.
+
If you have topics with a replication factor of 1, and if you have sufficient disk space, temporarily xref:manage:data-migration.adoc#change-topic-replication-factor[increase the replication factor] to limit outages for these topics during the rolling upgrade.
+
Increase the replication factor before you upgrade to ensure that Redpanda has time to replicate data to other brokers.

. Ensure that the cluster is healthy:
+
```bash
kubectl exec <pod-name> --namespace <namespace> -c redpanda -- \
  rpk cluster health
```
+
The draining process won't start until the cluster is healthy.
The amount of time it takes to drain a broker and reassign partition leadership depends on the number of partitions and how healthy the cluster is.
For healthy clusters, draining leadership should take less than a minute.
If the cluster is unhealthy, such as when a follower is not in sync with the leader, then draining the broker can take even longer.
+
.Example output:
[%collapsible]
====
[.no-copy]
----
CLUSTER HEALTH OVERVIEW
=======================
Healthy:                     true <1>
Controller ID:               0
All nodes:                   [0 1 2] <2>
Nodes down:                  [] <3>
Leaderless partitions:       [] <3>
Under-replicated partitions: [] <3>
----
<1> The cluster is either healthy (`true`) or unhealthy (`false`).
<2> The node IDs of all brokers in the cluster.
<3> If the cluster is unhealthy, these fields will contain data.
====

. If you're using the Redpanda Helm chart without the Redpanda Operator, list all your existing overrides of the Helm values:
+
[,bash]
----
helm get values redpanda --namespace <namespace>
----
+
You'll need to apply these overrides in the next step.

. Upgrade the Redpanda version by overriding the `image.tag` setting. Replace `<new-version>` with a valid version tag.
+
[tabs]
======
Helm + Operator::
+
--
.`redpanda-cluster.yaml`
[,yaml,lines=9-15]
----
apiVersion: cluster.redpanda.com/v1alpha1
kind: Redpanda
metadata:
  name: redpanda
spec:
  chartRef: {}
  clusterSpec:
    image:
      tag: <new-version>
----

```bash
kubectl apply -f redpanda-cluster.yaml --namespace <namespace>
```

--
Helm::
+
--
[tabs]
====
--values::
+
.`redpanda-version.yaml`
[,yaml]
----
image:
  tag: <new-version>
----
+
```bash
helm upgrade --install redpanda redpanda/redpanda --namespace <namespace> --create-namespace \
--values redpanda-version.yaml --reuse-values
```

--set::
+
[,bash,lines=2-5]
----
helm upgrade --install redpanda redpanda/redpanda --namespace <namespace> --create-namespace \
  --set image.tag=<new-version>
----

====
--
======
+
CAUTION: Make sure to include all existing overrides, otherwise the upgrade may fail.
For example, if you already enabled SASL, include the same SASL overrides.
Do not use the `--reuse-values` flag, otherwise Helm won't include any new values from the upgraded chart.

. Wait for the Pods to be terminated and recreated with the new version of Redpanda.
+
[,bash]
----
kubectl get pod --namespace <namespace> --watch
----
+
Each Pod in the StatefulSet is terminated one at a time, starting from the one with the highest ordinal.
+
.Example output
[%collapsible]
====
[.no-copy]
----
NAME                                    READY   STATUS
redpanda-controller-operator            2/2     Running
redpanda-0                              2/2     Running
redpanda-1                              2/2     Running
redpanda-2                              0/2     Init:0/3
redpanda-configuration-88npt            0/1     Completed
redpanda-console-7cf85cf87f-rmtnj       1/1     Running
redpanda-post-upgrade-ljqpr             0/1     Completed
----
====

. When all of the Pods are ready and have a `Running` status, verify that the brokers are now running the upgraded version of Redpanda:
+
```bash
kubectl exec <pod-name> --namespace <namespace> -c redpanda -- \
  rpk redpanda admin brokers list
```

== Rollbacks

If something does not go as planned during a rolling upgrade, you can roll back to the original version as long as you have not upgraded every broker.

NOTE: The Redpanda Operator rolls back automatically after three failed attempts to upgrade the cluster.

If you are using the Redpanda Helm chart without the Redpanda Operator, you can roll back manually.

The StatefulSet uses the `RollingUpdate` strategy by default in xref:reference:redpanda-helm-spec.adoc#statefulsetupdatestrategytype[`statefulset.updateStrategy.type`],
which means all Pods in the StatefulSet are restarted in reverse-ordinal order. For details, see the https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#update-strategies[Kubernetes documentation^].

. Find the previous revision:
+
```bash
helm history redpanda --namespace <namespace>
```
+
Example output
+
[.no-copy]
----
REVISION	UPDATED                 	STATUS    	CHART          	APP VERSION	DESCRIPTION
1       	Fri Mar  3 15:16:24 year	superseded	redpanda-2.12.2	v22.3.13   	Install complete
2       	Fri Mar  3 15:19:41 year	deployed	  redpanda-2.12.2	v22.3.13   	Upgrade complete
----

. Roll back to the previous revision:
+
```bash
helm rollback redpanda <previous-revision> --namespace <namespace>
```

. Verify that the cluster is healthy. If the cluster is unhealthy, the upgrade may still be in progress. The command exits when the cluster is healthy.
+
```bash
kubectl exec <pod-name> --namespace <namespace> -c redpanda -- \
  rpk cluster health \
  --watch --exit-when-healthy
```
+
.Example output:
[%collapsible]
====
[.no-copy]
```
CLUSTER HEALTH OVERVIEW
=======================
Healthy:               true
Controller ID:         1
All nodes:             [2,1,0]
Nodes down:            []
Leaderless partitions: []
```
====

include::shared:partial$suggested-reading.adoc[]

Set up a real-time dashboard to monitor your cluster health, see xref:manage:kubernetes/monitoring/index.adoc[Monitor Redpanda].