= Upgrade the Redpanda Operator
:description: Upgrading the Redpanda Operator ensures your deployment benefits from the latest features, fixes, and improvements. Follow these steps carefully to ensure a successful upgrade.
// Unset this attribute so that we don't pre-fill the version in code snippets
:!latest-operator-version:

{description}

. Make sure to https://github.com/redpanda-data/redpanda-operator/releases[review the release notes^] to understand any significant changes, bug fixes, or potential disruptions that could affect your existing deployment.

. xref:upgrade:k-compatibility.adoc[Review the Kubernetes compatibility matrix] and determine the version of the Redpanda Operator that is compatible with the Helm chart version you plan to use. The Redpanda Operator must be able to understand and manage the Helm chart and the Redpanda version you are deploying.

. Back up your current Helm values for the Redpanda Operator Helm chart:
+
[source,bash]
----
helm get values redpanda-controller --namespace <namespace> > redpanda-operator-values-backup.yaml
----
+
You'll need to apply these overrides in the next step.

. Upgrade the Redpanda Operator. Replace `<operator-version>` with the version of the Redpanda Operator you want to upgrade to.
+
[,bash,subs="attributes+"]
----
helm repo add redpanda https://charts.redpanda.com
helm repo update
helm upgrade redpanda-controller redpanda/operator \
  --namespace <namespace> \
  --version <operator-version> \
  --set crds.enabled=true \
  --reuse-values
----
+
This command:
+
- Pins the upgrade to a specific version of Redpanda Operator.
- Ensures the latest CRDs are applied as part of the upgrade.
- Retains all previously set custom values using `--reuse-values`.
+
[NOTE]
====
If you're using a values file, you can specify it with the `--values` flag instead of `--reuse-values`:

[,bash]
----
helm upgrade redpanda-controller redpanda/operator \
  --namespace <namespace> \
  --version <operator-version> \
  --set crds.enabled=true \
  --values redpanda-operator-values-backup.yaml
----
====
+
CAUTION: Omitting custom overrides may result in a broken or partial deployment.

. Ensure that the Deployment is successfully rolled out:
+
```bash
kubectl --namespace <namespace> rollout status --watch deployment/redpanda-controller-operator
```
+
[.no-copy]
----
deployment "redpanda-controller-operator" successfully rolled out
----

== Next steps

xref:upgrade:k-rolling-upgrade.adoc[].