= Upgrade Redpanda
:description: To benefit from Redpanda’s new features and enhancements, upgrade to the latest version. 
:page-context-links: [{"name": "Linux", "to": "upgrade:rolling-upgrade.adoc" },{"name": "Kubernetes", "to": "upgrade:k-rolling-upgrade.adoc" } ]
:page-aliases: manage:cluster-maintenance/rolling-upgrade.adoc, \
install-upgrade:rolling-upgrade.adoc, \
install-upgrade:version-upgrade.adoc, \
cluster-management:version-upgrade.adoc, \
cluster-administration:version-upgrade.adoc, \
reference:version-upgrade.adoc

To benefit from Redpanda's new features and enhancements, upgrade to the latest version. Redpanda recommends that you perform a rolling upgrade on production clusters, which requires all brokers to be placed into maintenance mode and restarted separately, one after the other.

Redpanda platform version numbers follow the convention AB.C.D, where AB is the two digit year, C is the feature release, and D is the patch release. For example, version 22.3.1 indicates the first patch release on the third feature release of the year 2022. Patch releases include bug fixes and minor improvements, with no change to user-facing behavior. New and enhanced features are documented with each feature release.

include::partial$rolling-upgrades/important-upgrade-note.adoc[]

== Prerequisites

* A running Redpanda cluster.
* https://stedolan.github.io/jq/download/[jq^] for listing available versions.
* An understanding of the <<impact-of-broker-restarts,impact of broker restarts>> on clients, node CPU, and any alerting systems you use.
* Review incompatible changes in new versions:

=== Review incompatible changes

Patches in https://github.com/redpanda-data/redpanda/discussions/9522[22.3.14] and https://github.com/redpanda-data/redpanda/discussions/9523[23.1.2] changed the behavior when remote read is disabled and the requested term falls below the local log's beginning. In earlier versions, Redpanda returned an offset -1. With the patch, when you request a value older than the lowest offset, Redpanda returns the lowest offset, not -1.

== Find a new version

Before you upgrade, find out which Redpanda version you are currently running, whether you can upgrade straight to the new version, and what's changed since your original version. To find your current version, run:

[tabs]
=====
Linux::
+
--
[,bash]
----
rpk redpanda admin brokers list
----

For all available flags, see the xref:reference:rpk/rpk-redpanda/rpk-redpanda-admin-brokers-list.adoc[`rpk redpanda admin brokers list` command reference].

--
Docker::
+
--
CAUTION: Running Redpanda directly on Docker is not supported for production usage. This platform should only be used for testing.

[,bash]
----
docker exec -it <container_name><container_tag> rpk version
----

Remember to replace the variables `<container_name>` and `<container_tag>`. The container tag determines which version of `rpk` to use. The release process bundles `rpk` and `Redpanda` into the same container tag with the same version.

--
macOS::
+
--
[,bash]
----
brew list --versions | grep redpanda
----

--
=====

Example output:

[,bash,subs="attributes+"]
----
v{full-version} (rev {latest-release-commit})
----

[NOTE]
====
If your current version is more than one feature release behind the latest Redpanda version, you must first upgrade to an intermediate version. To list all available versions:

[,bash]
----
curl -s 'https://hub.docker.com/v2/repositories/redpandadata/redpanda/tags/?ordering=last_updated&page=1&page_size=50' | jq -r '.results[].name'
----
====

Check the https://github.com/redpanda-data/redpanda/releases[release notes^] to find information about what has changed between Redpanda versions.

include::partial$rolling-upgrades/restart-impact.adoc[leveloffset=+1]

== Perform a rolling upgrade

A rolling upgrade involves putting a broker into xref:manage:node-management.adoc[maintenance mode], upgrading the broker, taking the broker out of maintenance mode, and then repeating the process on the next broker in the cluster. Placing brokers into maintenance mode ensures a smooth upgrade of your cluster while reducing the risk of interruption or degradation in service.

When a broker is placed into maintenance mode, it reassigns its partition leadership to other brokers for all topics that have a replication factor greater than one. Reassigning partition leadership involves _draining_ leadership from the broker and _transferring_ that leadership to another broker. If you have topics with `replication.factor=1`, and if you have sufficient disk space, Redpanda recommends temporarily increasing the replication factor. This can help limit outages for these topics during the rolling upgrade. Do this before the upgrade to make sure there's time for the data to replicate to other brokers. For more information, see xref:manage:data-migration.adoc#change-topic-replication-factor[Change topic replication factor].

To ensure that all brokers are active before upgrading, run:

[,bash]
----
rpk redpanda admin brokers list
----

All brokers should show `active` for `MEMBERSHIP-STATUS` and `true` for `IS-ALIVE`:

.Example output
[%collapsible]
====
[.no-copy]
```
NODE-ID  NUM-CORES  MEMBERSHIP-STATUS  IS-ALIVE  BROKER-VERSION
0        1          active             true      v22.3.11
1        1          active             true      v22.3.11
2        1          active             true      v22.3.11
```
====

New features in a version are enabled after all brokers in the cluster are upgraded. If problems occur, the upgrade is not committed.

NOTE: Redpanda started supporting xref:develop:consume-data/consumer-offsets.adoc[consumer offsets] in version 22.1. When upgrading from version 21.11 to 22.1, after all brokers are upgraded, Redpanda starts to migrate consumer group topics to `__consumer_offsets`. This takes some time, depending on the data size. Until it finishes, all consumer group-related operations (consume, offset commit, coordinator election) are blocked. The migration to consumer offsets is complete when you see `consumer offset feature enabled` in all brokers.

=== Enable maintenance mode

. Check that all brokers are healthy:
+
[,bash]
----
 rpk cluster health
----
+
.Expected output:
[%collapsible]
====
[.no-copy]
```
CLUSTER HEALTH OVERVIEW
=======================
Healthy:                     true
Controller ID:               0
All nodes:                   [0 1 2]
Nodes down:                  []
Leaderless partitions:       []
Under-replicated partitions: []
====

. Select a broker that has not been upgraded yet and place it into maintenance mode:
+
```bash
rpk cluster maintenance enable <node-id> --wait
```
+
The `--wait` option tells the command to wait until a given broker, 0 in this example, finishes draining all partitions it originally served. After the partition draining completes, the command completes.
+
.Expected output:
[%collapsible]
====
[.no-copy]
```
Successfully enabled maintenance mode for node 0
Waiting for node to drain...
NODE-ID  DRAINING  FINISHED  ERRORS  PARTITIONS  ELIGIBLE  TRANSFERRING  FAILED
0        false     false     false   0           0         0             0
0        false     false     false   0           0         0             0
0        false     false     false   0           0         0             0
0        false     false     false   0           0         0             0
0        false     false     false   0           0         0             0
0        false     false     false   0           0         0             0
0        true      true      false   3           0         2             0
====

. Verify that the broker is in maintenance mode:
+
```bash
rpk cluster maintenance status
```
+
.Expected output:
[%collapsible]
====
[.no-copy]
```
NODE-ID  DRAINING  FINISHED  ERRORS  PARTITIONS  ELIGIBLE  TRANSFERRING  FAILED
0        true      true      false   3           0         2             0
1        false     false     false   0           0         0             0
2        false     false     false   0           0         0             0
====

. Validate again the health of the cluster:
+
```bash
rpk cluster health
```
+
.Expected output:
[%collapsible]
====
[.no-copy]
```
CLUSTER HEALTH OVERVIEW
=======================
Healthy:                     true
Controller ID:               0
All nodes:                   [0 1 2]
Nodes down:                  []
Leaderless partitions:       []
Under-replicated partitions: []
====
+
[NOTE]
====
You can also evaluate xref:manage:monitoring.adoc[external metrics] to determine cluster health. If the cluster has any issues, take the broker out of maintenance mode by running the following command before proceeding with other operations, such as decommissioning or retrying the rolling upgrade:

```bash
rpk cluster maintenance disable <node-id>
```
====

=== Upgrade your version

[tabs]
======
Linux::
+
--
For Linux distributions, the process changes according to the distribution:

[tabs]
====
Fedora/RedHat::
+
In the terminal, run:
+
[,bash]
----
sudo yum update redpanda
----

Debian/Ubuntu::
+
In the terminal, run:
+
[,bash]
----
sudo apt update
sudo apt install redpanda
----

====
--

Docker::
+
--

CAUTION: Running Redpanda directly on Docker is not supported for production usage. This platform should only be used for testing.

To perform an upgrade you must replace the current image with a new one.

First, check which image is currently running in Docker:

```bash
docker ps
```

Stop and remove the containers:

```bash
docker stop <container_id>
docker rm <container_id>
```

Remove current images:

```bash
docker rmi <image_id>
```

Pull the desired Redpanda version, or adjust the setting to `latest` in the `version` tag:

```bash
docker pull docker.redpanda.com/redpandadata/redpanda:<version>
```

After it completes, restart the cluster:

```bash
docker restart <container_name>
```

For more information, see the xref:get-started:quick-start.adoc[Redpanda Quickstart].

--
macOS::
+
--

If you previously installed Redpanda with brew, run:

```bash
brew upgrade redpanda-data/tap/redpanda
```

For installations from binary files, download the preferred version from the release list and then overwrite the current rpk file in the installed location.

--
======

=== Check metrics

Check the following metrics before continuing with the upgrade:

[options="header"]
|===
| Metric | Description

| xref:reference:public-metrics-reference.adoc#redpanda_kafka_under_replicated_replicas[redpanda_kafka_under_replicated_replicas]
| If this shows any non-zero value, then replication cannot catch up, and the upgrade should be paused.

| xref:reference:public-metrics-reference.adoc#redpanda_cluster_unavailable_partitions[redpanda_cluster_unavailable_partitions]
| Before restart, wait for this to show zero unavailable partitions.

| xref:reference:public-metrics-reference.adoc#redpanda_kafka_request_bytes_total[redpanda_kafka_request_bytes_total]
| Before restart, the produce and consume rate for each broker should recover to the pre-upgrade value.

| xref:reference:public-metrics-reference.adoc#redpanda_kafka_request_latency_seconds[redpanda_kafka_request_latency_seconds]
| Before restart, the p99 histogram should recover to the pre-upgrade value.

| xref:reference:public-metrics-reference.adoc#redpanda_rpc_request_latency_seconds[redpanda_rpc_request_latency_seconds]
| Before restart, the p99 histogram should recover to the pre-upgrade value.

| xref:reference:public-metrics-reference.adoc#redpanda_cpu_busy_seconds_total[redpanda_cpu_busy_seconds_total]
| Check the CPU utilization. The derivative gives you a 0.0-1.0 value for how much time the core was busy in a given second.
|===


=== Restart broker

Restart the broker's Redpanda service with xref:reference:rpk/rpk-redpanda/rpk-redpanda-stop.adoc[`rpk redpanda stop`], then xref:reference:rpk/rpk-redpanda/rpk-redpanda-start.adoc[`rpk redpanda start`].

=== Disable maintenance mode

After you've successfully upgraded the broker:

. Take the broker out of maintenance mode:
+
```bash
rpk cluster maintenance disable <node-id>
```
+
Expected output:
+
[.no-copy]
----
Successfully disabled maintenance mode for node 0
----

. Ensure that the broker is no longer in maintenance mode:
+
```bash
rpk cluster maintenance status
```
+
.Expected output:
[%collapsible]
====
[.no-copy]
```
NODE-ID  DRAINING  FINISHED  ERRORS  PARTITIONS  ELIGIBLE  TRANSFERRING  FAILED
0        false     false     false   0           0         0             0
1        false     false     false   0           0         0             0
2        false     false     false   0           0         0             0
```
====

=== Post-upgrade tasks

To verify that the cluster is running properly, run:

```bash
rpk cluster health
```

To view additional information about your brokers, run:

```bash
rpk redpanda admin brokers list
```

== Suggested reading

To set up a real-time dashboard to monitor your cluster health, see xref:manage:monitoring.adoc[Monitor Redpanda].
