= Upgrade Redpanda
:description: To benefit from Redpanda's new features and enhancements, upgrade to the latest version.
:page-context-links: [{"name": "Linux", "to": "upgrade:rolling-upgrade.adoc" },{"name": "Kubernetes", "to": "upgrade:k-rolling-upgrade.adoc" } ]
:page-aliases: manage:cluster-maintenance/rolling-upgrade.adoc,install-upgrade:rolling-upgrade.adoc,install-upgrade:version-upgrade.adoc,cluster-management:version-upgrade.adoc,cluster-administration:version-upgrade.adoc,reference:version-upgrade.adoc
:rolling-upgrade:
:page-categories: Upgrades
:env-linux: true

To benefit from Redpanda's new features and enhancements, upgrade to the latest version. Redpanda Data recommends that you perform a glossterm:rolling upgrade[] on production clusters, which requires all brokers to be placed into maintenance mode and restarted separately, one after the other.

include::partial$versioning.adoc[]

include::partial$rolling-upgrades/upgrade-limitations.adoc[]

== Prerequisites

* A running Redpanda cluster.
* https://stedolan.github.io/jq/download/[jq^] for listing available versions.
* An understanding of the <<impact-of-broker-restarts,impact of broker restarts>> on clients, node CPU, and any alerting systems you use.
* Review incompatible changes in new versions.

include::partial$incompat-changes.adoc[]

include::partial$rolling-upgrades/restart-impact.adoc[leveloffset=+1]

== Find a new version

Before you upgrade, find out which Redpanda version you are currently running, whether you can upgrade straight to the new version, and what's changed since your original version. To find your current version, run:

[tabs]
=====
Linux::
+
--
[,bash]
----
rpk redpanda admin brokers list
----

For all available flags, see the xref:reference:rpk/rpk-redpanda/rpk-redpanda-admin-brokers-list.adoc[`rpk redpanda admin brokers list` command reference].

--
Docker::
+
--
CAUTION: Running Redpanda directly on Docker is not supported for production usage. This platform should only be used for testing.

[,bash]
----
docker exec -it <container_name><container_tag> rpk version
----

Remember to replace the variables `<container_name>` and `<container_tag>`. The container tag determines which version of `rpk` to use. The release process bundles `rpk` and `Redpanda` into the same container tag with the same version.

--
macOS::
+
--
[,bash]
----
brew list --versions | grep redpanda
----

--
=====

Example output:

[,bash,subs="attributes+"]
----
{latest-redpanda-tag} (rev {latest-release-commit})
----

[NOTE]
====
If your current version is more than one feature release behind the latest Redpanda version, you must first upgrade to an intermediate version. To list all available versions:

[,bash]
----
curl -s 'https://hub.docker.com/v2/repositories/redpandadata/redpanda/tags/?ordering=last_updated&page=1&page_size=50' | jq -r '.results[].name'
----
====

Check the https://github.com/redpanda-data/redpanda/releases[release notes^] to find information about what has changed between Redpanda versions.

== Check license status

If you use xref:get-started:licensing/overview.adoc#self-managed[enterprise features] of Redpanda, make sure that you have a valid Enterprise Edition license key. Redpanda fails to upgrade to a new feature release if you have enterprise features enabled without a valid license key.

include::get-started:partial$licensing/check-license.adoc[]

== Perform a rolling upgrade

include::partial$rolling-upgrades/rolling-restart-intro.adoc[]

include::partial$rolling-upgrades/enable-maintenance-mode.adoc[]

include::partial$rolling-upgrades/upgrade-your-version.adoc[]

include::partial$rolling-upgrades/check-metrics.adoc[]

include::partial$rolling-upgrades/restart-the-broker.adoc[]

include::partial$rolling-upgrades/disable-maintenance-mode.adoc[]

include::partial$rolling-upgrades/post-upgrade-tasks.adoc[]

== Upgrade Redpanda Console

Before upgrading to Console v3, xref:upgrade:migrate/console-v3.adoc[review the migration guide] to address breaking changes.

[tabs]
======
Linux::
+
--
For Linux distributions, the process changes according to the distribution:

[tabs]
====
Fedora/RedHat::
+
In the terminal, run:
+
[,bash]
----
sudo yum update redpanda-console -y
----

Debian/Ubuntu::
+
In the terminal, run:
+
[,bash,role="no-wrap"]
----
sudo apt-get update && sudo apt-get install --only-upgrade redpanda-console -y
----

====
--

Docker::
+
--

CAUTION: Running Redpanda Console directly on Docker is not supported for production usage. Docker should only be used for testing.

To perform an upgrade you must replace the current image with a new one.

. Check which image is currently running in Docker:
+
```bash
docker ps
```

. Stop and remove the current container:
+
```bash
docker stop <container-id>
docker rm <container-id>
```

. Remove the existing Docker image:
+
```bash
docker rmi <image-id>
```

. Pull the desired Redpanda version, or adjust the setting to `latest` in the `version` tag:
+
```bash
docker pull docker.redpanda.com/redpandadata/console:<version>
```

. Restart the Docker container using the new image:
+
```bash
docker run -d --name <container-name> docker.redpanda.com/redpandadata/console:<version>
```

For more information, see the xref:get-started:quick-start.adoc[Redpanda Quickstart].

--
======

== Troubleshooting

include::troubleshoot:partial$errors-and-solutions.adoc[tags=deployment]

include::shared:partial$suggested-reading.adoc[]

* xref:manage:monitoring.adoc[]
