= Upgrade Redpanda
:description: To benefit from Redpanda's new features and enhancements, upgrade to the latest version.
:page-context-links: [{"name": "Linux", "to": "upgrade:rolling-upgrade.adoc" },{"name": "Kubernetes", "to": "upgrade:k-rolling-upgrade.adoc" } ]
:page-aliases: manage:cluster-maintenance/rolling-upgrade.adoc,install-upgrade:rolling-upgrade.adoc,install-upgrade:version-upgrade.adoc,cluster-management:version-upgrade.adoc,cluster-administration:version-upgrade.adoc,reference:version-upgrade.adoc
:rolling-upgrade:
:page-categories: Upgrades
:env-linux: true

To benefit from Redpanda's new features and enhancements, upgrade to the latest version. Redpanda Data recommends that you perform a glossterm:rolling upgrade[] on production clusters, which requires all brokers to be placed into maintenance mode and restarted separately, one after the other.

include::partial$versioning.adoc[]

include::partial$rolling-upgrades/upgrade-limitations.adoc[]

== Prerequisites

* A running Redpanda cluster.
* https://stedolan.github.io/jq/download/[jq^] for listing available versions.
* An understanding of the <<impact-of-broker-restarts,impact of broker restarts>> on clients, node CPU, and any alerting systems you use.
* Review incompatible changes in new versions.

=== Review incompatible changes

Patch releases in https://github.com/redpanda-data/redpanda/discussions/9522[22.3.14^] and https://github.com/redpanda-data/redpanda/discussions/9523[23.1.2^] changed the behavior when remote read is disabled and the requested Raft term falls below the local log's beginning. In earlier versions, Redpanda returned an offset -1. With the patch, when you request a value older than the lowest offset, Redpanda returns the lowest offset, not -1.

== Find a new version

Before you upgrade, find out which Redpanda version you are currently running, whether you can upgrade straight to the new version, and what's changed since your original version. To find your current version, run:

[tabs]
=====
Linux::
+
--
[,bash]
----
rpk redpanda admin brokers list
----

For all available flags, see the xref:reference:rpk/rpk-redpanda/rpk-redpanda-admin-brokers-list.adoc[`rpk redpanda admin brokers list` command reference].

--
Docker::
+
--
CAUTION: Running Redpanda directly on Docker is not supported for production usage. This platform should only be used for testing.

[,bash]
----
docker exec -it <container_name><container_tag> rpk version
----

Remember to replace the variables `<container_name>` and `<container_tag>`. The container tag determines which version of `rpk` to use. The release process bundles `rpk` and `Redpanda` into the same container tag with the same version.

--
macOS::
+
--
[,bash]
----
brew list --versions | grep redpanda
----

--
=====

Example output:

[,bash,subs="attributes+"]
----
v{full-version} (rev {latest-release-commit})
----

[NOTE]
====
If your current version is more than one feature release behind the latest Redpanda version, you must first upgrade to an intermediate version. To list all available versions:

[,bash]
----
curl -s 'https://hub.docker.com/v2/repositories/redpandadata/redpanda/tags/?ordering=last_updated&page=1&page_size=50' | jq -r '.results[].name'
----
====

Check the https://github.com/redpanda-data/redpanda/releases[release notes^] to find information about what has changed between Redpanda versions.

include::partial$rolling-upgrades/restart-impact.adoc[leveloffset=+1]

== Perform a rolling upgrade

include::partial$rolling-upgrades/rolling-restart-intro.adoc[]

include::partial$rolling-upgrades/enable-maintenance-mode.adoc[]

include::partial$rolling-upgrades/upgrade-your-version.adoc[]

include::partial$rolling-upgrades/check-metrics.adoc[]

include::partial$rolling-upgrades/restart-the-broker.adoc[]

include::partial$rolling-upgrades/disable-maintenance-mode.adoc[]

include::partial$rolling-upgrades/post-upgrade-tasks.adoc[]

include::shared:partial$suggested-reading.adoc[]

* xref:manage:monitoring.adoc[]
