= API Reference
:description: See the Schema Registry API, the HTTP Proxy API, and the Admin API.

Use Redpanda's API reference documentation to learn about and interact with API endpoints:

* link:/api/doc/schema-registry/[Schema Registry API Reference]
+
Manage schemas within a Redpanda cluster. See also: xref:manage:schema-reg/index.adoc[Schema Registry documentation].
* link:/api/doc/http-proxy/[HTTP Proxy API Reference]
+
HTTP Proxy is an HTTP server that exposes operations you can perform directly on a Redpanda cluster. Use the Redpanda HTTP Proxy API to perform a subset of actions that are also available through the Kafka API, but using simpler REST operations. See also: xref:develop:http-proxy.adoc[Use Redpanda with the HTTP Proxy API].
* Admin API Reference
+
Manage components of a Redpanda cluster, such as individual brokers and partition leadership. The xref:manage:use-admin-api.adoc[Redpanda Admin API] also allows you to perform operations that are specific to Redpanda Self-Managed and cannot be done using the standard Kafka API.
+
--
* link:/api/doc/admin/[Admin API v1] is available on all supported versions of Redpanda.
* xref:reference:admin-api-v2.adoc[Admin API v2] is available on Redpanda version 25.3 and later. v2 provides access to new functionality introduced starting in Redpanda v25.3.
--

