= API and SDK Reference
:description: See the Schema Registry API, the HTTP Proxy API, the Admin API, and the Data Transforms SDKs. 

Use Redpanda's API reference documentation to learn about and interact with API endpoints:

* xref:api:ROOT:pandaproxy-schema-registry.adoc[Schema Registry API Reference]
+
Manage schemas within a Redpanda cluster. See also: xref:manage:schema-reg/index.adoc[Schema Registry documentation].
* xref:api:ROOT:pandaproxy-rest.adoc[HTTP Proxy API Reference]
+
HTTP Proxy is an HTTP server that exposes operations you can perform directly on a Redpanda cluster. Use the Redpanda HTTP Proxy API to perform a subset of actions that are also available through the Kafka API, but using simpler REST operations. See also: xref:develop:http-proxy.adoc[Use Redpanda with the HTTP Proxy API].
* xref:api:ROOT:admin-api.adoc[Admin API Reference]
+
Manage components of a Redpanda cluster, such as individual brokers and partition leadership. The Redpanda Admin API also allows you to perform operations that are specific to the Redpanda platform and cannot be done using the standard Kafka API.
* xref:api:ROOT:cloud-api.adoc[Cloud API Reference]
+
Use the Cloud API to manage Redpanda Cloud clusters and resources. See also: xref:deploy:deployment-option/cloud/api/cloud-api-overview.adoc[Cloud API Overview].

Use the SDK reference documentation to build and deploy data transforms on Redpanda topics:

* xref:reference:data-transform-golang-sdk.adoc[]
* xref:reference:data-transform-rust-sdk.adoc[]
