= Cloud Metrics
:description: Use Redpanda Cloud metrics to create your system dashboard.

This section provides reference descriptions about the public metrics exported from Redpanda Cloud.

== redpanda_cloud_storage_cache_space_size_bytes

Sum of size of cached objects

== redpanda_cloud_storage_housekeeping_drains

Number of times upload housekeeping queue was drained

== redpanda_cloud_storage_spillover_manifests_materialized_bytes

Bytes of memory used for spilled manifests currently cached in memory

== redpanda_cloud_storage_cache_op_put

Number of objects written into cache

== redpanda_cloud_storage_segments

Total number of accounted segments in the cloud for the topic

== redpanda_cloud_storage_jobs_local_segment_reuploads

Number of segment reuploads from local data directory

== redpanda_cloud_storage_cache_trim_failed_trims

Number of times could not free the expected amount of space, indicating possible bug or configuration issue

== redpanda_cloud_storage_cache_trim_exhaustive_trims

Number of times we couldn't free enough space with a fast trim and had to fall back to a slower exhaustive trim

== redpanda_cloud_storage_deleted_segments

Count of deleted remote segments

== redpanda_cloud_storage_segment_uploads_total

Successful data segment uploads

== redpanda_cloud_storage_active_segments

Number of remote log segments currently hydrated for read

== redpanda_cloud_storage_cache_trim_fast_trims

Number of times we have trimmed the cache using the normal (fast) mode

== redpanda_cloud_storage_housekeeping_jobs_failed

Number of failed housekeeping jobs

== redpanda_cloud_storage_partition_readers_delayed

How many partition readers were delayed due to hitting reader limit. This indicates cluster is saturated with tiered storage reads

== redpanda_cloud_storage_segments_pending_deletion

Total number of segments pending deletion from the cloud for the topic

== redpanda_cloud_storage_housekeeping_rounds

Number of upload housekeeping rounds

== redpanda_cloud_storage_segment_readers_delayed

How many segment readers were delayed due to hitting reader limit. This indicates cluster is saturated with tiered storage reads

== redpanda_cloud_storage_cache_space_hwm_size_bytes

High watermark of sum of size of cached objects

== redpanda_cloud_storage_cache_space_hwm_files

High watermark of number of objects in cache

== redpanda_cloud_storage_cache_op_in_progress_files

Number of files that are being put to cache

== redpanda_cloud_storage_jobs_cloud_segment_reuploads

Number of segment reuploads from cloud storage sources (cloud storage cache or direct download from cloud storage)

== redpanda_cloud_storage_jobs_manifest_reuploads

Number of manifest reuploads performed by all housekeeping jobs

== redpanda_cloud_storage_housekeeping_pauses

Number of times upload housekeeping was paused

== redpanda_cloud_storage_segment_index_uploads_total

Successful segment index uploads

== redpanda_cloud_storage_cache_op_miss

Number of failed get requests because of missing object in the cache

== redpanda_cloud_storage_errors_total

Number of transmit errors

== redpanda_cloud_storage_spillover_manifest_uploads_total

Successful spillover manifest uploads

== redpanda_cloud_storage_housekeeping_requests_throttled_average_rate

Average rate of requests from the read and write path which were throttled by tiered storage (per shard)

== redpanda_cloud_storage_jobs_segment_deletions

Number of segments deleted by all housekeeping jobs

== redpanda_cloud_storage_segment_materializations_delayed

How many segment materializations were delayed due to hitting reader limit. This indicates cluster is saturated with tiered storage reads

== redpanda_cloud_storage_jobs_metadata_syncs

Number of archival configuration updates performed by all housekeeping jobs

== redpanda_cloud_storage_housekeeping_jobs_completed

Number of executed housekeeping jobs

== redpanda_cloud_storage_readers

Number of segment read cursors for hydrated remote log segments

== redpanda_cloud_storage_partition_manifest_uploads_total

Successful partition manifest uploads

== redpanda_cloud_storage_limits_downloads_throttled_sum

Total amount of throttling applied to cloud storage downloads

== redpanda_cloud_storage_housekeeping_resumes

Number of times upload housekeeping was resumed

== redpanda_cloud_storage_cache_op_hit

Number of get requests for objects that are already in cache

== redpanda_cloud_storage_spillover_manifests_materialized_count

How many spilled manifests are currently cached in memory

== redpanda_cloud_storage_uploaded_bytes

Total number of uploaded bytes for the topic

== redpanda_cloud_storage_cache_space_files

Number of objects in cache

== redpanda_cloud_storage_housekeeping_jobs_skipped

Number of skipped housekeeping jobs

== redpanda_cloud_storage_partition_readers

Number of partition reader instances (number of current fetch/timequery requests reading from tiered storage)
