= Rust SDK for Data Transforms
:description: Work with data transforms using Rust.

Rust SDK reference documentation for Redpanda data transforms.

The `redpanda_transform_sdk` crate contains the core functions and types for transforming data within Redpanda.

== Functions

The Rust SDK includes the following https://doc.rust-lang.org/rust-by-example/fn.html[function] to manage data transforms to an output topic.  

=== on_record_written

[,rust]
----
pub fn on_record_written<E, F>(cb: F) -> !
where
    E: Debug,
    F: Fn(WriteEvent<'_>, &mut dyn RecordWriter) -> Result<(), E>,
----

The `on_record_written()` function transforms individual records after they have been written to an input topic. The function registers a callback to be fired when a record is written to the topic. This callback is triggered after the record has been written and fsynced to disk and the producer has been acknowledged (see <<writeevent,`WriteEvent`>>).

Since this method blocks and runs forever, it should be called from the `main()` function. Perform the necessary steps before transforming any records before calling this method.

---

== Structs

A https://doc.rust-lang.org/rust-by-example/custom_types/structs.html[struct] is a custom data type that allows you to define a structure composed of related data attributes.

=== BorrowedHeader

[,rust]
----
pub struct BorrowedHeader<'a> { /* private fields */ }
----

`BorrowedHeader` is a zero-copy <<borrowedrecord,`BorrowedRecord`>> header.

=== BorrowedRecord

[,rust]
----
pub struct BorrowedRecord<'a> { /* private fields */ }
----

`BorrowedRecord` is a zero-copy representation of a <<record,`Record`>> in Redpanda. 

=== Record

[,rust]
----
pub struct Record { /* private fields */ }
----

`Record` is a record in Redpanda. It consists of a key-value pair of bytes, along with a collection of <<recordheader,`RecordHeader`>>.

Records are generated as the result of any transforms that act upon a `BorrowedRecord`.

=== RecordHeader

[,rust]
----
pub struct RecordHeader { /* private fields */ }
----

A `RecordHeader` is a key-value pair attached to a <<record,`Record`>>. Headers are opaque to the broker and are purely a mechanism for the producer and consumers to pass information.

=== RecordWriter

[,rust]
----
pub struct RecordWriter<'a> { /* private fields */ }
----

`RecordWriter` is a struct that writes transformed records to the output topic.

=== WriteEvent

[,rust]
----
pub struct WriteEvent<'a> {
    pub record: WrittenRecord<'a>,
}
----

`WriteEvent` is an event generated after the broker completes a write. A `WriteEvent` is asynchronously triggered after the broker acknowledges the producer's write request, and is then passed to <<on_record_written,on_record_written>>. 

=== WrittenRecord

[,rust]
----
pub struct WrittenRecord<'a> { /* private fields */ }
----

A written <<record,Record>> within Redpanda. A `WrittenRecord` is handed to <<on_record_written,on_record_written>> event handlers as the record that Redpanda wrote. The record contains a key-value pair with some headers and the record's timestamp.

== Enums

An https://doc.rust-lang.org/rust-by-example/custom_types/enum.html[enum] is a custom data type that is defined by enumerating its possible variants.

=== WriteError

[,rust]
----
#[non_exhaustive]
pub enum WriteError {
    Unknown(i32),
}
----

A `WriteError` can occur when writing records to the output topic.

== Traits

A https://doc.rust-lang.org/rust-by-example/trait.html[trait] defines shared behavior that a particular type shares with other types.

=== RecordSink

[,rust]
----
pub trait RecordSink {
    // Required method
    fn write(&mut self, r: BorrowedRecord<'_>) -> Result<(), WriteError>;
}
----

A trait that can receive a stream of records and output them to a destination topic.

== Related topics

- xref:develop:data-transforms/run-transforms.adoc[]
- xref:develop:data-transforms/how-transforms-work.adoc[]