= Internal Metrics Reference
:description: Reference of Redpanda internal metrics for detailed analysis, debugging, and troubleshooting.

This section provides reference descriptions about the internal metrics exported from Redpanda's `/metrics` endpoint.

include::shared:partial$metrics-usage-tip.adoc[]

[IMPORTANT]
====
In a live system, Redpanda metrics are exported only for features that are in use. For example, a metric for consumer groups is not exported when no groups are registered.

To see the available internal metrics in your system, query the `/metrics` endpoint:

[,bash]
----
curl http://<node-addr>:9644/metrics | grep "[HELP|TYPE]"
----
====

== Internal metrics

Most internal metrics are useful for debugging. The following subset of internal metrics can be useful to monitor system health.

---

=== vectorized_application_uptime

Redpanda uptime in milliseconds.

---

=== vectorized_cloud_storage_read_bytes

Number of bytes Redpanda has read from cloud storage. This is tracked on a per-topic and per-partition basis, and increments each time a cloud storage read operation successfully completes.

---

=== vectorized_cluster_partition_last_stable_offset

Last stable offset.

If this is the last record received by the cluster, then the cluster is up-to-date and ready for maintenance.

---

=== vectorized_cluster_partition_schema_id_validation_records_failed

Number of records that failed schema ID validation.

---

=== vectorized_cluster_partition_start_offset

Raft snapshot start offset.

---

=== vectorized_io_queue_delay

Total delay time in the queue.

Can indicate latency caused by disk operations in seconds.

---

=== vectorized_io_queue_queue_length

Number of requests in the queue.

Can indicate latency caused by disk operations.

---

=== vectorized_kafka_rpc_active_connections

Number of currently active Kafka RPC connections, or clients.

---

=== vectorized_kafka_rpc_connects

Number of accepted Kafka RPC connections.

Compare to the value at a previous time to derive the rate of accepted connections.

---

[[vectorized_kafka_rpc_produce_bad_create_time]]
=== vectorized_kafka_rpc_produce_bad_create_time

An incrementing counter for the number of times a producer created a message with a timestamp skewed from the broker's date and time. This metric is related to the following properties:

* `log_message_timestamp_alert_before_ms`: Increment this gauge when the `create_timestamp` on a message is too far in the past as compared to the broker's time.
* `log_message_timestamp_alert_after_ms`: Increment this gauge when the `create_timestamp` on a message is too far in the future as compared to the broker's time.

---

=== vectorized_kafka_rpc_received_bytes

Number of bytes received from Kafka RPC clients in valid requests.

Compare to the value at a previous time to derive the throughput in Kafka layer in bytes/sec received.

---

=== vectorized_kafka_rpc_requests_completed

Number of successful Kafka RPC requests.

Compare to the value at a previous time to derive the messages per second per shard.

---

=== vectorized_kafka_rpc_requests_pending

Number of Kafka RPC requests being processed by a server.

---

=== vectorized_kafka_rpc_sent_bytes

Number of bytes sent to Kafka RPC clients.

---

=== vectorized_kafka_rpc_service_errors

Number of Kafka RPC service errors.

---

=== vectorized_ntp_archiver_compacted_replaced_bytes

Number of bytes removed from cloud storage by compaction operations. This is tracked on a per-topic and per-partition basis.

This metric resets every time partition leadership changes. It primarily exists to track the fact that compaction is performing operations on cloud storage.

The `namespace` label supports the following options for this metric:

* `kafka` - user topics
* `kafka_internal` - internal kafka topic such as consumer groups
* `redpanda - redpanda-only internal data

*Labels*:

* `namespace=("kafka" | "kafka_internal" | "redpanda")`
* `topic`
* `partition`

---

=== vectorized_ntp_archiver_pending

The difference between the last committed offset and the last offset uploaded to Tiered Storage for each partition. A value of zero for this metric indicates that all data for a partition is uploaded to Tiered Storage.

This metric is impacted by the xref:reference:tunable-properties.adoc#cloud_storage_segment_max_upload_interval_sec[`cloud_storage_segment_max_upload_interval_sec`] tunable property. If this interval is set to 10 seconds, the archiver will upload committed segments to Tiered Storage every 10 seconds or less. If this metric continues growing for longer than the configured interval, it can indicate a potential network issue with the upload path for that partition.

The `namespace` label supports the following options for this metric:

* `kafka` - user topics
* `kafka_internal` - internal kafka topic such as consumer groups
* `redpanda - redpanda-only internal data

*Labels*:

* `namespace=("kafka" | "kafka_internal" | "redpanda")`
* `topic`
* `partition`

---

=== vectorized_raft_leadership_changes

Number of leadership changes.

High value can indicate nodes failing and causing leadership changes.

---

=== vectorized_reactor_utilization

Redpanda process utilization.

Shows the true utilization of the CPU by a Redpanda process.

---

=== vectorized_storage_log_compacted_segment

Number of compacted segments.

---

=== vectorized_storage_log_compaction_removed_bytes

Number of bytes removed from local storage by compaction operations. This is tracked on a per-topic and per-partition basis. It primarily exists to track the fact that compaction is performing operations on local storage.

The `namespace` label supports the following options for this metric:

* `kafka` - user topics
* `kafka_internal` - internal kafka topic such as consumer groups
* `redpanda - redpanda-only internal data

*Labels*:

* `namespace=("kafka" | "kafka_internal" | "redpanda")`
* `topic`
* `partition`

---

=== vectorized_storage_log_log_segments_created

Number of created log segments.

---

=== vectorized_storage_log_partition_size

Current size of partition in bytes.

---

=== vectorized_storage_log_read_bytes

Total number of bytes read.

---

=== vectorized_storage_log_written_bytes

Total number of bytes written.

== Related topics

* xref:manage:monitoring.adoc[Learn how to monitor Redpanda]
* xref:./public-metrics-reference.adoc[Public metrics reference]
