= Broker Configuration Properties 
:description: Broker configuration properties list. 

Broker configuration properties are applied individually to each broker in a cluster. 

IMPORTANT: After you change a broker-level property setting, you must restart the broker for the change to take effect. 

To learn how to set these properties from studying a sample configuration file, see the xref:./node-configuration-sample.adoc[broker configuration sample].

---

== admin

Address and port of admin server

*Example:* 
[,yaml]
----
"description": "Address and port of admin server"
"is_secret": !!bool "false"
"items":
  "type": "broker_endpoint"
"needs_restart": !!bool "true"
"nullable": !!bool "false"
"type": "array"
"visibility": "user"
----

*Nullable:* No

*Requires Restart:* Yes

*Visibility:* user

*Is Secret:* No

*Type:* array

== admin_api_doc_dir

Admin API doc directory

*Example:* 
[,yaml]
----
"description": "Admin API doc directory"
"is_secret": !!bool "false"
"needs_restart": !!bool "true"
"nullable": !!bool "false"
"type": "string"
"visibility": "user"
----

*Nullable:* No

*Requires Restart:* Yes

*Visibility:* user

*Is Secret:* No

*Type:* string

== admin_api_tls

TLS configuration for admin HTTP server

*Example:* 
[,yaml]
----
"description": "TLS configuration for admin HTTP server"
"is_secret": !!bool "false"
"items":
  "type": "endpoint_tls_config"
"needs_restart": !!bool "true"
"nullable": !!bool "false"
"type": "array"
"visibility": "user"
----

*Nullable:* No

*Requires Restart:* Yes

*Visibility:* user

*Is Secret:* No

*Type:* array

== advertised_kafka_api

Address of Kafka API published to the clients

*Example:* 
[,yaml]
----
"description": "Address of Kafka API published to the clients"
"is_secret": !!bool "false"
"items":
  "type": "broker_endpoint"
"needs_restart": !!bool "true"
"nullable": !!bool "false"
"type": "array"
"visibility": "user"
----

*Nullable:* No

*Requires Restart:* Yes

*Visibility:* user

*Is Secret:* No

*Type:* array

== advertised_rpc_api

Address of RPC endpoint published to other cluster members

*Example:* 
[,yaml]
----
"description": "Address of RPC endpoint published to other cluster members"
"is_secret": !!bool "false"
"needs_restart": !!bool "true"
"nullable": !!bool "true"
"type": "net::unresolved_address"
"visibility": "user"
----

*Nullable:* Yes

*Requires Restart:* Yes

*Visibility:* user

*Is Secret:* No

*Type:* net::unresolved_address

== cloud_storage_cache_directory

Directory for archival cache. Should be present when `cloud_storage_enabled` is present

*Example:* 
[,yaml]
----
"description": "Directory for archival cache. Should be present when `cloud_storage_enabled`\
  \ is present"
"is_secret": !!bool "false"
"needs_restart": !!bool "true"
"nullable": !!bool "true"
"type": "string"
"visibility": "user"
----

*Nullable:* Yes

*Requires Restart:* Yes

*Visibility:* user

*Is Secret:* No

*Type:* string

== crash_loop_limit

Maximum consecutive crashes (unclean shutdowns) allowed after which operator intervention is needed to startup the broker.

*Example:* 
[,yaml]
----
"description": "Maximum consecutive crashes (unclean shutdowns) allowed after which\
  \ operator intervention is needed to startup the broker."
"is_secret": !!bool "false"
"needs_restart": !!bool "true"
"nullable": !!bool "true"
"type": "integer"
"visibility": "user"
----

*Nullable:* Yes

*Requires Restart:* Yes

*Visibility:* user

*Is Secret:* No

*Type:* integer

== data_directory

Place where redpanda will keep the data

*Example:* 
[,yaml]
----
"description": "Place where redpanda will keep the data"
"is_secret": !!bool "false"
"needs_restart": !!bool "true"
"nullable": !!bool "false"
"type": "string"
"visibility": "user"
----

*Nullable:* No

*Requires Restart:* Yes

*Visibility:* user

*Is Secret:* No

*Type:* string

== developer_mode

Skips most of the checks performed at startup, not recomended for production use

*Example:* 
[,yaml]
----
"description": "Skips most of the checks performed at startup, not recomended for\
  \ production use"
"example": "true"
"is_secret": !!bool "false"
"needs_restart": !!bool "true"
"nullable": !!bool "false"
"type": "boolean"
"visibility": "tunable"
----

*Nullable:* No

*Requires Restart:* Yes

*Visibility:* tunable

*Is Secret:* No

*Type:* boolean

== empty_seed_starts_cluster

If true, an empty seed_servers list will denote that this node should form a cluster. At most one node in the cluster should be configured configured with an empty seed_servers list. If no such configured node exists, or if configured to false, all nodes denoted by the seed_servers list must be identical among those nodes' configurations, and those nodes will form the initial cluster.

*Example:* 
[,yaml]
----
"description": "If true, an empty seed_servers list will denote that this node should\
  \ form a cluster. At most one node in the cluster should be configured configured\
  \ with an empty seed_servers list. If no such configured node exists, or if configured\
  \ to false, all nodes denoted by the seed_servers list must be identical among those\
  \ nodes' configurations, and those nodes will form the initial cluster."
"example": "false"
"is_secret": !!bool "false"
"needs_restart": !!bool "true"
"nullable": !!bool "false"
"type": "boolean"
"visibility": "user"
----

*Nullable:* No

*Requires Restart:* Yes

*Visibility:* user

*Is Secret:* No

*Type:* boolean

== kafka_api

Address and port of an interface to listen for Kafka API requests

*Example:* 
[,yaml]
----
"description": "Address and port of an interface to listen for Kafka API requests"
"is_secret": !!bool "false"
"items":
  "type": "config::broker_auth_endpoint"
"needs_restart": !!bool "true"
"nullable": !!bool "false"
"type": "array"
"visibility": "user"
----

*Nullable:* No

*Requires Restart:* Yes

*Visibility:* user

*Is Secret:* No

*Type:* array

== kafka_api_tls

TLS configuration for Kafka API endpoint

*Example:* 
[,yaml]
----
"description": "TLS configuration for Kafka API endpoint"
"is_secret": !!bool "false"
"items":
  "type": "endpoint_tls_config"
"needs_restart": !!bool "true"
"nullable": !!bool "false"
"type": "array"
"visibility": "user"
----

*Nullable:* No

*Requires Restart:* Yes

*Visibility:* user

*Is Secret:* No

*Type:* array

== memory_allocation_warning_threshold

Enables log messages for allocations greater than the given size.

*Example:* 
[,yaml]
----
"description": "Enables log messages for allocations greater than the given size."
"is_secret": !!bool "false"
"needs_restart": !!bool "true"
"nullable": !!bool "true"
"type": "integer"
"visibility": "tunable"
----

*Nullable:* Yes

*Requires Restart:* Yes

*Visibility:* tunable

*Is Secret:* No

*Type:* integer

== node_id

Unique id identifying a node in the cluster. If missing, a unique id will be assigned for this node when it joins the cluster

*Example:* 
[,yaml]
----
"description": "Unique id identifying a node in the cluster. If missing, a unique\
  \ id will be assigned for this node when it joins the cluster"
"is_secret": !!bool "false"
"needs_restart": !!bool "true"
"nullable": !!bool "true"
"type": "integer"
"visibility": "user"
----

*Nullable:* Yes

*Requires Restart:* Yes

*Visibility:* user

*Is Secret:* No

*Type:* integer

== rack

Rack identifier

*Example:* 
[,yaml]
----
"description": "Rack identifier"
"is_secret": !!bool "false"
"needs_restart": !!bool "true"
"nullable": !!bool "true"
"type": "rack_id"
"visibility": "user"
----

*Nullable:* Yes

*Requires Restart:* Yes

*Visibility:* user

*Is Secret:* No

*Type:* rack_id

== rpc_server

IpAddress and port for RPC server

*Example:* 
[,yaml]
----
"description": "IpAddress and port for RPC server"
"is_secret": !!bool "false"
"needs_restart": !!bool "true"
"nullable": !!bool "false"
"type": "net::unresolved_address"
"visibility": "user"
----

*Nullable:* No

*Requires Restart:* Yes

*Visibility:* user

*Is Secret:* No

*Type:* net::unresolved_address

== rpc_server_tls

TLS configuration for RPC server

*Example:* 
[,yaml]
----
"description": "TLS configuration for RPC server"
"is_secret": !!bool "false"
"needs_restart": !!bool "true"
"nullable": !!bool "false"
"type": "tls_config"
"visibility": "user"
----

*Nullable:* No

*Requires Restart:* Yes

*Visibility:* user

*Is Secret:* No

*Type:* tls_config

== seed_servers

List of the seed servers used to join current cluster. If the seed_server list is empty the node will be a cluster root and it will form a new cluster

*Example:* 
[,yaml]
----
"description": "List of the seed servers used to join current cluster. If the seed_server\
  \ list is empty the node will be a cluster root and it will form a new cluster"
"is_secret": !!bool "false"
"items":
  "type": "seed_server"
"needs_restart": !!bool "true"
"nullable": !!bool "false"
"type": "array"
"visibility": "user"
----

*Nullable:* No

*Requires Restart:* Yes

*Visibility:* user

*Is Secret:* No

*Type:* array

== storage_failure_injection_config_path

Path to the configuration file used for low level storage failure injection

*Example:* 
[,yaml]
----
"description": "Path to the configuration file used for low level storage failure\
  \ injection"
"is_secret": !!bool "false"
"needs_restart": !!bool "true"
"nullable": !!bool "true"
"type": "string"
"visibility": "tunable"
----

*Nullable:* Yes

*Requires Restart:* Yes

*Visibility:* tunable

*Is Secret:* No

*Type:* string

== storage_failure_injection_enabled

If true, inject low level storage failures on the write path. **Not** for production usage.

*Example:* 
[,yaml]
----
"description": "If true, inject low level storage failures on the write path. **Not**\
  \ for production usage."
"example": "true"
"is_secret": !!bool "false"
"needs_restart": !!bool "true"
"nullable": !!bool "false"
"type": "boolean"
"visibility": "tunable"
----

*Nullable:* No

*Requires Restart:* Yes

*Visibility:* tunable

*Is Secret:* No

*Type:* boolean

== upgrade_override_checks

Whether to violate safety checks when starting a redpanda version newer than the cluster's consensus version

*Example:* 
[,yaml]
----
"description": "Whether to violate safety checks when starting a redpanda version\
  \ newer than the cluster's consensus version"
"example": "true"
"is_secret": !!bool "false"
"needs_restart": !!bool "true"
"nullable": !!bool "false"
"type": "boolean"
"visibility": "tunable"
----

*Nullable:* No

*Requires Restart:* Yes

*Visibility:* tunable

*Is Secret:* No

*Type:* boolean

