= Cloud Topics
:description: Cloud Topics are Kafka topics that enable users to trade off latency for lower costs.
:page-beta: true
:page-categories: Clients, Development
// tag::single-source[]

ifndef::env-cloud[]
[NOTE]
====
include::shared:partial$enterprise-license.adoc[]
====
endif::[]

While standard Kafka glossterm:topics[] are ideal for high-throughput, cost-sensitive workloads, Cloud Topics are optimized for high-throughput, cost-sensitive workloads. Instead of replicating every byte across expensive network links, Cloud Topics leverage durable, inexpensive Cloud object storage (S3, GCS, MinIO) as the primary mechanism for backing up data. The difference in response time is typically 500ms, which is only impactful for latency-sensitive applications. So when using Cloud Topics, you get the same durability that you have with standard topics, but you also eliminate the significant cross-AZ costs typically incurred when you have high-throughput workloads (for example, for audit logs).

== Prerequisites

- rpk v25.3.1: See xref:get-started:rpk-install.adoc[].
ifndef::env-cloud[]
- xref:manage:tiered-storage.adoc#set-up-tiered-storage[Set up] and xref:manage:tiered-storage.adoc#enable-tiered-storage[enable Tiered Storage] on your Redpanda cluster.
- xref:manage:tiered-storage.adoc#configure-object-storage[Configure object storage]
- include::shared:partial$enterprise-license.adoc[]

To check if you already have a license key applied to your cluster:

[,bash]
----
rpk cluster license info
----
endif::[]

== Limitations

Not all Redpanda features are available when using Cloud Topics (beta). The following features are not supported in this beta release:

- Kafka compaction
- Iceberg topics
- Topic recovery
- Remote Read Replicas

IMPORTANT: You should expect to throw away any cluster running the Cloud Topics (beta) after it becomes generally available (GA). Redpanda will be unable to continue using data that was generated by the beta version of this feature. Also, any topic specified to be Cloud Topic cannot subsequently be converted back to a standard, or non-Cloud Topic.

== Create Cloud Topics

To create a Cloud Topic:

[,bash]
----
rpk topic create -c redpanda.cloud_topic.enable=true <new-cloud-topic-name>
----
+
[,bash,role=no-copy]
----
TOPIC                    STATUS
audit.analytics.may2025  OK
----

To enable a Cloud Topic in a cluster:

[,bash]
----
rpk topic create -c redpanda.cloud_topic.enabled=true <cloud-topic-name>
----

// end::single-source[]