= Build a Chat Room Application with Redpanda Cloud and Java
:description: Create a basic chat room application with Redpanda Cloud and Kafka Java clients.
:contextLinks: [{"name"=>"Docker", "to"=>"guide-java"}, {"name"=>"Cloud", "to"=>"guide-java-cloud"}]
:deployment: Cloud
:linkRoot: ../../

import Intro from "../develop/shared/chat-app/_intro.mdx"
import SetUpCloud from "../develop/shared/chat-app/_set-up-cloud.mdx"
import NextSteps from "../develop/shared/chat-app/_next-steps.mdx"
import ContextLink from '@site/src/components/ContextButton.js'
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';

<ContextLink frontmatter=\{frontMatter}
/>

Create a basic chat room application with Redpanda Cloud and https://central.sonatype.com/artifact/org.apache.kafka/kafka-clients[Kafka Java clients].+++<Intro>++++++</Intro>+++

== Prerequisites

You must have:

* Java 11 or 17 (OpenJDK is recommended)
* Maven+++<Tabs groupId="operating-system" queryString="">++++++<TabItem value="ubuntu" label="Windows/Linux" default="">+++You can download OpenJDK from [Adoptium](https://adoptium.net/temurin/releases), and can follow the installation instructions for Maven on the [official Maven website](https://maven.apache.org/install.html).+++</TabItem>+++ +++<TabItem value="macos" label="macOS">+++Mac users with Homebrew installed can run the following commands to install these dependencies: ```bash brew install openjdk@11 maven ``` Make sure to follow any symlinking instructions in the Caveats output.+++</TabItem>++++++</Tabs>+++

When the prerequisites are installed, the following commands should print the version of both Java and Maven:

[,bash]
----
java --version
mvn --version
----

:::note
Redpanda Cloud environments use certificates signed by
https://letsencrypt.org/[Let's Encrypt]. Most programming languages will
load their root certificate authority (CA), `ISRG Root X1`, by default so you
shouldn't need to provide a custom CA.
:::

== Set up Redpanda Cloud

<SetUpCloud frontmatter=\{frontMatter}/>

== Set up your environment

. Bootstrap a new Java project using the following Maven command:

[,bash]
----
  mvn archetype:generate \
    -DgroupId=com.example \
    -DartifactId=chat-room \
    -DarchetypeArtifactId=maven-archetype-quickstart \
    -DarchetypeVersion=1.4 \
    -DinteractiveMode=false
----

. Set your working directory to the project folder:

[,bash]
----
  cd chat-room
----

. Add the required dependencies to your `pom.xml` file:

[,xml]
----
  <dependencies>
    <dependency>
      <groupId>org.apache.kafka</groupId>
      <artifactId>kafka-clients</artifactId>
      <version>3.4.0</version>
    </dependency>
    <dependency>
      <groupId>com.google.code.gson</groupId>
      <artifactId>gson</artifactId>
      <version>2.8.9</version>
    </dependency>
  </dependencies>
----

:::tip
  You can check for new versions of the Kafka Java client on the https://search.maven.org/artifact/org.apache.kafka/kafka-clients[Sonatype website].
  :::

. Set the source and target Java version to 11 in your `pom.xml` file:

[,xml]
----
  <properties>
    <maven.compiler.source>11</maven.compiler.source>
    <maven.compiler.target>11</maven.compiler.target>
  </properties>
----

. Install the dependencies by building the project:

[,bash]
----
  mvn package
----

The output is verbose, but you should see a successful build message:

----
  [INFO] BUILD SUCCESS
----

== Create a topic

You need a topic named `chat-room` for both Redpanda and the client to use to store chat room messages. If you completed the Redpanda Quickstart, this topic already exists in your cluster.

. Verify that the `chat-room` topic exists in your cluster by listing all topics:

[,bash]
----
  docker exec -it redpanda-0 rpk topic list
----

Output:

----
  NAME       PARTITIONS  REPLICAS
  chat-room  1           1
----

. If the topic doesn't exist yet, use xref:reference:rpk.adoc[rpk] to create a `chat-room` topic:

[,bash]
----
  docker exec -it redpanda-0 rpk topic create chat-room
----

Output:

----
  TOPIC      STATUS
  chat-room  OK
----

== Confirm that the topic exists on the client side

The client may not always know that the topic exists. You can verify that it exists and create it if not. In `chat-room/` create a source file called `src/main/java/com/example/Admin.java` with the following content.

Replace the placeholders with the same values that you used in the Redpanda Cloud Quickstart.

```java title="src/main/java/com/example/Admin.java"
package example;

import org.apache.kafka.clients.admin.AdminClient;
import org.apache.kafka.clients.admin.NewTopic;
import org.apache.kafka.clients.admin.AdminClientConfig;
import org.apache.kafka.clients.CommonClientConfigs;
import org.apache.kafka.clients.producer.ProducerConfig;
import org.apache.kafka.common.config.SaslConfigs;
import org.apache.kafka.common.serialization.StringDeserializer;
import org.apache.kafka.common.serialization.StringSerializer;

import java.util.Collections;
import java.util.Properties;

public class Admin {
  private static final String BOOTSTRAP_SERVERS = "+++<bootstrap-server-address>+++"; private static final String SASL_USERNAME = "redpanda-chat-account"; private static final String SASL_PASSWORD = "+++<password>+++";+++</password>++++++</bootstrap-server-address>+++

public static Properties getProducerProps() {
    Properties props = getAdminProps();
    props.put("key.serializer", StringSerializer.class.getName());
    props.put("value.serializer", StringSerializer.class.getName());
    return props;
  }

public static Properties getConsumerProps(String groupId) {
    Properties props = getAdminProps();
    props.put("group.id", groupId);
    props.put("key.deserializer", StringDeserializer.class.getName());
    props.put("value.deserializer", StringDeserializer.class.getName());
    return props;
  }

public static boolean topicExists(String topicName) {
      Properties props = getAdminProps();
      try (AdminClient client = AdminClient.create(props)) {
        return client.listTopics().names().get().contains(topicName);
      } catch (Exception e) {
          throw new RuntimeException(e);
      }
  }

public static void createTopic(String topicName) {
    Properties props = getAdminProps();
    try (AdminClient client = AdminClient.create(props)) {
      NewTopic newTopic = new NewTopic(topicName, 1, (short) 1);
      client.createTopics(Collections.singletonList(newTopic));
    } catch (Exception e) {
      throw new RuntimeException(e);
    }
  }

private static Properties getAdminProps() {
    Properties props = new Properties();
    props.put(AdminClientConfig.BOOTSTRAP_SERVERS_CONFIG, BOOTSTRAP_SERVERS);

 props.put(CommonClientConfigs.SECURITY_PROTOCOL_CONFIG, "SASL_SSL");
 props.put(SaslConfigs.SASL_MECHANISM, "SCRAM-SHA-256");
 props.put(SaslConfigs.SASL_JAAS_CONFIG,
       "org.apache.kafka.common.security.scram.ScramLoginModule required username=\""
               + SASL_USERNAME + "\" password=\"" + SASL_PASSWORD + "\";");
 return props;   } } ```

This code is a utility class that provides methods for checking if a topic exists, creating a topic, and returning producer and consumer configuration properties. You will use these methods in the other classes in the chat room application.

== Create a producer

A client needs a producer to publish `chat-room` topic messages.

To create a producer for the client, in `chat-room/` create a source file `src/main/java/com/example/ChatProducer.java` with the following content.

```java title="src/main/java/com/example/ChatProducer.java"
package example;

import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.ProducerRecord;
import com.google.gson.Gson;

import java.util.HashMap;
import java.util.Map;

public class ChatProducer implements AutoCloseable {
  private KafkaProducer<String, String> producer;
  private String topic;
  private Gson gson;

public ChatProducer(String topic) {
    this.producer = new KafkaProducer<>(Admin.getProducerProps());
    this.topic = topic;
    this.gson = new Gson();
  }

public void sendMessage(String user, String message) {
    Map<String, String> messageMap = new HashMap<>();
    messageMap.put("user", user);
    messageMap.put("message", message);

....
String jsonMessage = gson.toJson(messageMap);

producer.send(new ProducerRecord<>(topic, null, jsonMessage));
producer.flush();   }
....

@Override
  public void close() {
    producer.close();
  }
}

----

You now have a working producer that sends strings entered by the user to the
`chat-room` topic. Messages are sent as JSON encoded strings here,
but keep in mind that the producer only sends buffers, so you can encode the
messages however you like.

## Create a consumer

A client needs a consumer to receive `chat-room` topic messages.

To create a consumer for the client, in `chat-room/` create a source file `src/main/java/com/example/ChatConsumer.java` with the following content.

```java title="src/main/java/com/example/ChatConsumer.java"
package example;

import org.apache.kafka.clients.consumer.ConsumerRecords;
import org.apache.kafka.clients.consumer.KafkaConsumer;
import org.apache.kafka.clients.consumer.ConsumerRecord;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.lang.reflect.Type;
import java.util.Map;

import java.time.Duration;
import java.util.Collections;

public class ChatConsumer implements Runnable, AutoCloseable {
  private volatile boolean running = true;
  private KafkaConsumer<String, String> consumer;
  private Gson gson;
  private Type type;

  public ChatConsumer(String topic, String groupId) {
    this.consumer = new KafkaConsumer<>(Admin.getConsumerProps(groupId));
    this.consumer.subscribe(Collections.singletonList(topic));
    this.gson = new Gson();
    this.type = new TypeToken<Map<String, String>>(){}.getType();
  }

  @Override
  public void run() {
    while (running) {
      ConsumerRecords<String, String> records = consumer.poll(Duration.ofMillis(1000));
      for (ConsumerRecord<String, String> record : records) {
        Map<String, String> messageMap = gson.fromJson(record.value(), type);
        System.out.println(messageMap.get("user") + ": " + messageMap.get("message"));
      }
    }
  }

  @Override
  public void close() {
    running = false;
    consumer.close();
  }
}
----

You now have a consumer that reads all messages from the `chat-room`
topic and prints them to the console. You can start as many consumer groups as
you like, but remember that each group reads a message only once, which is
why the example is using a generated UUID for the group ID.

== Create a client application

The client needs an application that creates the topic, producer, and consumer and implements the chat logic.

To create a client application, in `chat-room/` create a source file `src/main/java/com/example/Main.java` with the following content.

```java title="src/main/java/com/example/Main.java"
package example;

import java.util.Scanner;
import java.util.UUID;
import java.util.concurrent.Executors;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Future;

public class Main {
  private static final String TOPIC = "chat-room";

public static void main(String[] args) {
    if (!Admin.topicExists(TOPIC)) {
      Admin.createTopic(TOPIC);
    }

....
Scanner scanner = new Scanner(System.in);
System.out.print("Enter your username: ");
String username = scanner.nextLine();

ExecutorService executorService = Executors.newSingleThreadExecutor();
try (ChatConsumer consumer = new ChatConsumer(TOPIC, UUID.randomUUID().toString());
      ChatProducer producer = new ChatProducer(TOPIC)) {

  Future<?> future = executorService.submit(consumer);
  System.out.print("Connected, press Ctrl+C to exit\n");

  while (!future.isDone()) {
    String message = scanner.nextLine();
    producer.sendMessage(username, message);
  }
} catch (Exception e) {
    System.out.println("Closing chat...");
} finally {
    executorService.shutdownNow();
}   } } ```
....

== Build and run the application

Compile the client chat application, run it from multiple client terminals, and chat between the clients.

. From `chat-room/`, compile the client application:

[,bash]
----
  mvn compile
----

. Open at least two terminals, and for each terminal:
 .. Run the client application:

+
----
   mvn exec:java -Dexec.mainClass="example.Main"
----
 .. When prompted with `Enter user name:`, enter a unique name for the chat room.
. Use the chat application: enter a message in a terminal, and verify that the message is received in the other terminals.

For example:

----
  Enter user name:
  Alice
  Connected, press Ctrl+C to exit
  Alice: Hi, I'm Alice
  Bob: Hi Alice, I'm Bob, nice to meet you
----

== Next steps+++<NextSteps>++++++</NextSteps>+++
