= Develop
:description: Develop doc topics.

* xref:develop:kafka-clients.adoc[Supported Kafka Clients]
+
Redpanda is compatible with Apache Kafka version 0.11 through 3.1.

* xref:develop:code-examples.adoc[Build a Chat Room Application]
+
As a follow-up to the quickstart, learn how to create a chat room application in Go, Node.js, or Python.

* xref:develop:http-proxy.adoc[Use Redpanda with the HTTP Proxy API]
+
Redpanda HTTP Proxy (`pandaproxy`) lets you access your data through a REST API.

* xref:develop:config-topics.adoc[Configure Topics]
+
Learn how to create topics and update topic configurations.

* xref:develop:produce-data.adoc[Produce Data]
+
Learn how to configure producers and idempotent producers.

* xref:develop:consume-data:.adoc[Consume Data]
+
Redpanda uses an internal topic, `__consumer_offsets`, to store committed offsets from each Kafka consumer that is attached to Redpanda.

* xref:develop:transactions.adoc[Transactions]
+
Learn how to use transactions; for example, you can fetch messages starting from the last consumed offset and transactionally process them one by one, updating the last consumed offset and producing events at the same time.
