= Kafka Compatibility
:page-aliases: development:kafka-clients.adoc
:page-categories: Clients, Development, Kafka Compatibility
:pp: {plus}{plus}
:description: Kafka clients, version 0.11 or later, are compatible with Redpanda. Validations and exceptions are listed.
// tag::single-source[]

Redpanda is compatible with Apache Kafka versions 0.11 and later, with specific exceptions noted on this page.

== Kafka client compatibility

Clients developed for Kafka versions 0.11 or later are compatible with Redpanda. Modern clients auto-negotiate protocol versions or use an earlier protocol version accepted by Redpanda brokers.

TIP: Redpanda Data recommends always using the latest supported version of a client.

The following clients have been validated with Redpanda.

|===
| Language | Client

| Java
| https://github.com/apache/kafka[Apache Kafka Java Client^]

| C/C{pp}
| https://github.com/edenhill/librdkafka[librdkafka^]

| Go
| https://github.com/twmb/franz-go[franz-go^]

| Python
| https://pypi.org/project/kafka-python-ng[kafka-python-ng^]

| Rust
| https://github.com/kafka-rust/kafka-rust[kafka-rust^]

| Node.js
a| 
* https://kafka.js.org[KafkaJS^] 
* https://github.com/confluentinc/confluent-kafka-javascript[confluent-kafka-javascript^]

|===

Clients that have not been validated by Redpanda Data, but use the Kafka protocol, remain compatible with Redpanda subject to the limitations below (particularly those based on librdkafka, such as confluent-kafka-dotnet or confluent-python).

If you find a client that is not
supported, reach out to the Redpanda team in the community https://redpanda.com/slack[Slack^].

== Unsupported Kafka features

Redpanda does not currently support the following Apache Kafka features:

* Multiple SCRAM mechanisms simultaneously for SASL users; for example, a user having both a `SCRAM-SHA-256` and a `SCRAM-SHA-512` credential. Redpanda supports only one SASL/SCRAM mechanism per user, either `SCRAM-SHA-256` or `SCRAM-SHA-512`.
+
ifndef::env-cloud[]
See the xref:manage:security/authentication.adoc#sasl[Configure Authentication] guide for details.
endif::[]
ifdef::env-cloud[]
See the xref:security:cloud-authentication.adoc[Authentication] guide for details.
endif::[]
* HTTP Proxy (pandaproxy): Unlike other REST proxy implementations in the Kafka ecosystem, Redpanda HTTP Proxy does not support topic and ACLs CRUD through the HTTP Proxy. HTTP Proxy is designed for clients producing and consuming data that do not perform administrative functions.
ifdef::env-cloud[]
+
* The `delete.retention.ms` topic configuration in Kafka is not supported. Tombstone markers are not removed for topics with a `compact` xref:get-started:config-topics.adoc#change-the-cleanup-policy[cleanup policy]. Redpanda only deletes tombstone markers when topics with a cleanup policy of `compact,delete` have reached their xref:get-started:create-topic.adoc[retention limits].
endif::[]
ifndef::env-cloud[]
+
* Quotas per user for bandwidth and API request rates. However, xref:manage:cluster-maintenance/manage-throughput.adoc#client-throughput-limits[quotas per client and per client group] using AlterClientQuotas and DescribeClientQuotas APIs are supported.
endif::[]

If you have any issues while working with a Kafka tool, you can https://github.com/redpanda-data/redpanda/issues/new[file an issue^].

// end::single-source[]
