= rpk topic describe-storage
:description: rpk topic describe-storage
:rpk_version: v23.2.1

Describe the topic storage status.

This commands prints detailed information about the cloud storage status of a
given topic. The information is divided into four sections:

* *Summary*
+
The summary section contains general information about the topic, the cloud
storage mode (one of disabled, write_only, read_only, full, and read_replica),
and the delta in milliseconds since the last upload of either the partition
manifest or a segment.

* *Offset*
+
The offset section contains the start and last offsets (inclusive) per
partition of data available in both the cloud and on local disk.

* *Size*
+
The size section contains the total bytes per partition in the cloud and on
local disk, the total size of the log of each partition (excluding cloud and
local overlap), and the number of segments in the cloud and on local disk. The
cloud segment count does not include segments queued for deletion.

* *Sync*
+
The sync section contains the state of cloud synchronization: milliseconds
since the last upload of the partition manifest, milliseconds since the last
segment upload, milliseconds since the last manifest sync (for read replicas),
and whether the remote metadata has a pending update to include all uploaded
segments.

== Usage

[,bash]
----
rpk topic describe-storage [TOPIC] [flags]
----

== Flags

////
[cols=",,",]
|===
|*Value* |*Type* |*Description*

|-h, --help |- |Help for describe-storage.

|-H, --human-readable |- |Print the times and bytes in a human-readable
form.

|-a, --print-all |- |Print all cloud storage status.

|-o, --print-offset |- |Print the offset section.

|-z, --print-size |- |Print the log size section.

|-s, --print-summary |- |Print the summary section.

|-y, --print-sync |- |Print the sync section.

|--config |string |Redpanda or rpk config file; default search paths are
~/.config/rpk/rpk.yaml, $PWD, and /etc/redpanda/`redpanda.yaml`.

|-X, --config-opt |stringArray |Override rpk configuration settings; '-X
help' for detail or '-X list' for terser detail.

|--profile |string |rpk profile to use.

|-v, --verbose |- |Enable verbose logging.
|===
////
