= rpk topic list
:description: rpk topic list
:rpk_version: v23.2.1

List topics, optionally listing specific topics.

This command lists all topics that you have access to by default. If specifying
topics or regular expressions, this command can be used to know exactly what
topics you would delete if using the same input to the delete command.

Alternatively, you can request specific topics to list, which can be used to
check authentication errors (do you not have access to a topic you were
expecting to see?), or to list all topics that match regular expressions.

The `--regex` or `-r` flag opts into parsing the input topics as regular expressions
and listing any non-internal topic that matches any of expressions. The input
expressions are wrapped with `^` and `$` so that the expression must match the
whole topic name. Regular expressions cannot be used to match internal topics,
as such, specifying both `-i` and `-r` will exit with failure.

Lastly, `--detailed` or `-d` flag opts in to printing extra per-partition information.

== Usage

[,bash]
----
rpk topic list [flags]
----

== Aliases

[,bash]
----
list, ls
----

== Flags

////
[cols=",,",]
|===
|*Value* |*Type* |*Description*

|-d, --detailed |- |Print per-partition information for topics.

|-h, --help |- |Help for list.

|-i, --internal |- |Print internal topics.

|-r, --regex |- |Parse topics as regex; list any topic that matches any
input topic expression.

|--config |string |Redpanda or rpk config file; default search paths are
~/.config/rpk/rpk.yaml, $PWD, and /etc/redpanda/`redpanda.yaml`.

|-X, --config-opt |stringArray |Override rpk configuration settings; '-X
help' for detail or '-X list' for terser detail.

|--profile |string |rpk profile to use.

|-v, --verbose |- |Enable verbose logging.
|===
////
