= rpk cloud auth
:description: rpk cloud auth

Manage rpk cloud authentications.

An rpk cloud authentication allows you to talk to Redpanda Cloud. Most likely,
you will only ever need to use a single SSO based login and you will not need
this command space. Multiple authentications can be useful if you have multiple
Redpanda Cloud accounts for different organizations and want to swap between
them, or if you use SSO as well as client credentials. It is recommended to
only use a single SSO based login.

== Usage

[,bash]
----
rpk cloud auth [flags]
  rpk cloud auth [command]
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-h, --help |- |Help for auth.

|--config |string |Redpanda or rpk config file; default search paths are `/var/lib/redpanda/.config/rpk/rpk.yaml`, `$PWD/redpanda.yaml`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override rpk configuration settings; '-X help' for detail or '-X list' for terser detail.

|--profile |string |rpk profile to use.

|-v, --verbose |- |Enable verbose logging.
|===