= rpk group delete
// tag::single-source[]

Delete consumer groups explicitly through `rpk group delete`.

This allows you to proactively manage offsets, for example, when you've created temporary groups for quick investigation or testing and you want to clear offsets sooner than the automatic cleanup.

Consumer groups are automatically deleted when the last committed offset expires. Group offset deletion can happen through:

* Kafka `OffsetDelete` API: Offsets can be explicitly deleted using the Kafka `OffsetDelete` API. See xref:reference:rpk/rpk-group/rpk-group-offset-delete.adoc[`rpk group offset delete`].
* Periodic Offset Expiration: Offsets expire automatically when the group has been empty for a set duration. 
ifndef::env-cloud[]
+
See also: xref:reference:properties/cluster-properties.adoc#group_offset_retention_sec[Cluster properties: `group_offset_retention_sec`]

endif::[]

== Usage

[,bash]
----
rpk group delete [GROUPS...] [flags]
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-h, --help |- |Help for delete.

|--config |string |Redpanda or `rpk` config file; default search paths are `/var/lib/redpanda/.config/rpk/rpk.yaml`, `$PWD/redpanda.yaml`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override `rpk` configuration settings. See xref:reference:rpk/rpk-x-options.adoc[`rpk -X`] or execute `rpk -X help` for inline detail or `rpk -X list` for terser detail.

|--profile |string |Profile to use. See xref:reference:rpk/rpk-profile.adoc[`rpk profile`] for more details.

|-v, --verbose |- |Enable verbose logging.
|===

// end::single-source[]
