= rpk cloud auth delete

Delete an `rpk` cloud authentication (auth).

Deleting a cloud authentication removes it from the `rpk.yaml` file. If the deleted
authentication was the current authentication, `rpk` will use a default SSO authentication the next time
you try to login, and if the login is successful, it will save the authentication.

If you delete an authentication that is used by profiles, affected profiles have their authentication cleared and you will only be able to access the profile's cluster using SASL credentials.

== Usage

[,bash]
----
rpk cloud auth delete [NAME] [flags]
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-h, --help |- |Help for delete.

|--config |string |Redpanda or `rpk` config file; default search paths are `/var/lib/redpanda/.config/rpk/rpk.yaml`, `$PWD/redpanda.yaml`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override `rpk` configuration settings. See xref:reference:rpk/rpk-x-options.adoc[`rpk -X`] or execute `rpk -X help` for inline detail or `rpk -X list` for terser detail.

|--profile |string |Profile to use. See xref:reference:rpk/rpk-profile.adoc[`rpk profile`] for more details.

|-v, --verbose |- |Enable verbose logging.
|===

