= rpk cloud auth

Manage `rpk` cloud authentications (auths).

An `rpk` cloud authentication allows you to talk to Redpanda Cloud. Most likely,
you will only ever need to use a single SSO based login and you will not need
this command space. Multiple authentications can be useful if you have multiple
Redpanda Cloud accounts for different organizations and you want to swap between
them, or if you use both SSO and client credentials. Redpanda Data recommends
using only a single SSO based login.

== Usage

[,bash]
----
rpk cloud auth [command] [flags]
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-h, --help |- |Help for auth.

|--config |string |Redpanda or `rpk` config file; default search paths are `/var/lib/redpanda/.config/rpk/rpk.yaml`, `$PWD/redpanda.yaml`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override `rpk` configuration settings. See xref:reference:rpk/rpk-x-options.adoc[`rpk -X`] or execute `rpk -X help` for inline detail or `rpk -X list` for terser detail.

|--profile |string |Profile to use. See xref:reference:rpk/rpk-profile.adoc[`rpk profile`] for more details.

|-v, --verbose |- |Enable verbose logging.
|===

