= Use AWS Commits
:description: Subscribe to Redpanda in AWS Marketplace with discounted commitment billing.

With a usage-based billing commitment, you sign up for a minimum spend amount and get a discount on your committed usage. This allows you to subscribe to Redpanda Cloud through AWS Marketplace to quickly provision Redpanda Dedicated clusters. 

Commitments are minimums: 

- If your usage is below your commitment, you still pay the minimum, but the unused amount at the end of your commitment term can roll over. 
- If your usage is above your commitment, you can continue using Redpanda Cloud without interruption. You are charged at your discounted rate for additional usage until the end of your commitment term.

[IMPORTANT]
====
When you subscribe for Redpanda Cloud through AWS Marketplace, you can only create clusters on AWS. 
====

== Sign up in AWS Marketplace

. Contact https://redpanda.com/contact[Redpanda sales^] to request a private offer for an AWS Redpanda Cloud commitment. 

. You will receive a private offer on AWS Marketplace. Review the policy and required terms, and click *Accept*.
+
[NOTE]
====
If you don't have a billing account associated with your project, you're prompted to enable billing to link the subscription with a billing account.
====
+
You are taken to the Redpanda sign-up page.

. On the Redpanda sign-up page: 
* For **Email**, enter your email address to register with Redpanda.
* For **Organization name**, enter a name for your new organization connected through AWS Marketplace. Redpanda organizations contain all resources, including clusters and networks. 
* Click **Sign up and create organization**.
+
You will receive an email sent to the address you entered.

. In the email, click **Verify email address**. 
+
This completes the registration and associates the email with a Redpanda account. 

. On the **Accept your invitation to sign up** page, click **Sign up** or **Log in**. 
+
You can now create namespaces and clusters in your organization.

== Next steps

* xref:deploy:deployment-option/cloud/create-dedicated-cloud-cluster-aws.adoc#create-a-dedicated-cluster[Create a Dedicated cluster]