= Marketplace Consumption Metrics
:description: Learn about the consumption units in Redpanda Cloud billing.

When you subscribe to Redpanda through Google Cloud Marketplace, you can use your existing GCP billing and credits to provision Dedicated Cloud clusters. View your bills and manage your Redpanda subscription directly in Google Cloud Marketplace. You can either pay as you go or purchase ahead with a discounted commitment. 

== Redpanda consumption units

Redpanda Cloud billing is mapped to the consumption of resources in your organization, including data ingress and egress and storage usage. To calculate the bill, the number of units consumed is multiplied by the cost for that unit. 

* All pricing is set in US dollars (USD). GCP automatically converts the bill to the currency of the billing account. 
* All billing computations are conducted in Coordinated Universal Time (UTC). Billing accrues at hourly intervals. Any usage that is less than an hour is billed for the full hour. 

=== Instance metrics

The cost for an instance unit depends on the region and tier you selected for your Dedicated cluster. Each instance unit equals one hour the instance is up.   

=== Ingress and egress metrics

Redpanda Cloud charges for all data transferred each hour, including each produce and consume requests.

* The cost for an ingress unit depends on the region you selected for your Dedicated cluster. Each ingress unit equals one GB of data written. 
* The cost for an egress unit depends on the number of availability zones (AZ) you selected for your Dedicated cluster. Each egress unit equals one GB of data read.

=== Storage metrics

Redpanda Cloud charges for the volume of data stored on a cluster, including replication. Each storage unit equals one GB of data in cloud storage per hour. 

Replication is important for high availability. Because Redpanda Cloud has a default replication factor of three, the amount of data stored typically exceeds the volume of data written to the cluster. To reduce storage usage, you can configure the `retention.bytes` and `retention.ms` on a topic. See xref:reference:topic-properties.adoc[Topic Properties].

== Next steps

* xref:./gcp-pay-as-you-go.adoc[Use with GCP Pay As You Go]
* xref:./gcp-commit.adoc[Use with GCP Commitment]