= Usage Metrics
:description: Learn about the metrics Redpanda uses to measure consumption in Redpanda Cloud.
:page-cloud: true

Redpanda Cloud billing is mapped to the consumption of resources. Billing is based on the resources consumed, multiplied by the cost of that resource.

* All pricing is set in US dollars (USD). The marketplace automatically converts the bill to the currency of the billing account. 
* All billing computations are conducted in Coordinated Universal Time (UTC). Billing accrues at hourly intervals. Any usage that is less than an hour is billed for the full hour. 

NOTE: For questions about billing, contact billing@redpanda.com.

== Serverless metrics

When you create a Serverless cluster, your data is stored in the Redpanda Cloud account, in the region you select. For more information, see xref:deploy:deployment-option/cloud/serverless.adoc#limitations[Serverless cluster limits].

|=== 
| Metric | Description 

| Instance | This tracks the number of hours the instance is running.  

The cost varies based on the region you select for your cluster. 
| Ingress | This tracks the data written into Redpanda (in GB).

The cost varies based on the region you select for your cluster. 

All Kafka protocol requests are counted as ingress as soon as they are read by Redpanda's proxy process. Kafka message headers are not included in the bytes measured.
| Egress | This tracks the data read out of Redpanda (in GB).

All Kafka protocol responses generated by the cluster are counted as egress as soon as the cluster processes the request, even if the client drops the connection before they are delivered. Kafka message headers are not included in the bytes measured.
| Storage | This tracks the data (in GB) in object storage per hour. 

Replication to object storage is implemented with glossterm:Tiered Storage[]. All topics have a fixed replication factor of 3, but Redpanda counts each byte only once. Redpanda measures storage at the end of each hour. 
|===


== BYOC/Dedicated metrics

When you create a BYOC or a Dedicated Cloud cluster, you select a tier that specifies the expected throughput for your cluster, including the maximum ingress, egress, partitions, and connections. For more information, see xref:deploy:deployment-option/cloud/cloud-overview.adoc#cluster-tiers[cluster tiers].

|=== 
| Metric | Description 

| Instance | This tracks the number of hours the instance is running. 

The cost varies based on the region and tier you select for your cluster.   
| Ingress | This tracks the data written into Redpanda (in GB). 

The cost varies based on the region you select for your cluster. 

All Kafka protocol requests, including headers, are counted as ingress as soon as they are read by Redpanda's proxy process. 
| Egress | This tracks the data read out of Redpanda (in GB).

All Kafka protocol responses generated by the cluster, including headers, are counted as egress as soon as the cluster processes the request, even if the client drops the connection before they are delivered. 

The cost varies based on the number of availability zones (AZ) you select for your cluster. 
| Storage | This tracks the data (in GB) in object storage per hour. 

Replication to object storage is implemented with glossterm:Tiered Storage[]. All topics have a fixed replication factor of 3, but Redpanda counts each byte only once.

Redpanda measures the total amount of storage used by each topic every 10 minutes. Rapid changes in the allocated storage within 10 minutes may not be detected. Data is measured as bytes/hour used; that is, if a vcluster uses 600 MB storage for 1 hour, the metering collection records a total usage of 600000000 bytes/hour. Because the system updates every 10 minutes, it communicates 100000000 bytes/hour every 10 minutes (summing to 600000000 at the end of the hour). For billing, the data is converted to gigabytes/hour, by dividing the total consumption by 1000000000. For example, a total of 1000000000 bytes/hour corresponds to 1 gigabyte/hour (which corresponds to a vcluster storing 1 GB for 1 hour, or a vcluster running with 100 MB for 10 hours, or any other combination of that). The price is applied to the number of gigabytes/hour used.

|=== 

== Next steps

* xref:./gcp-commit.adoc[]
* xref:./aws-commit.adoc[]