= Usage Metrics
:description: Learn about the metrics Redpanda uses to measure consumption in Redpanda Cloud.
:page-cloud: true

Redpanda Cloud uses various metrics to measure the consumption of resources. 

* All pricing is set in US dollars (USD). 
* All billing computations are conducted in Coordinated Universal Time (UTC). Billing accrues at hourly intervals. Any usage that is less than an hour is billed for the full hour. 

NOTE: Pricing information is available on https://redpanda.com/redpanda-cloud/serverless[redpanda.com]. For questions about billing, contact billing@redpanda.com.

== Serverless metrics

There is no base cost for a Serverless instance. Pricing for Serverless clusters depends on the data in, data out, data stored, and partitions (virtual streams).

|=== 
| Metric | Description 

| Ingress | This tracks the data written into Redpanda (in GB).

The cost varies based on the region you select for your cluster. 

All Kafka protocol requests (_except_ message headers) are counted as ingress as soon as they are read by Redpanda's proxy process. 
| Egress | This tracks the data read out of Redpanda (in GB).

All Kafka protocol responses generated by the cluster (_except_ message headers) are counted as egress as soon as the cluster processes the request, even if the client drops the connection before they are delivered.
| Storage | This tracks the data (in GB) in object storage per hour. 
| Partitions | This tracks the number of partitions used per hour.

Data is measured as milli-partitions/hour used; that is, if a vcluster uses 3 partitions for 1 hour, the metering collection records a total usage of 3000 milli-partitions/hour. Because the system updates every 10 minutes, it communicates 500 milli-partitions/hour every 10 minutes (3000 at the end of the hour). For billing, the data is converted to partitions/hour, by dividing the total consumption by 3000. For example, 72000 milli-partitions/hour corresponds to 24 partitions/hour (which corresponds to a vcluster running with 1 partition for 24 hours, or a vcluster running with 24 partitions for 1 hour).
|===

See also: xref:deploy:deployment-option/cloud/serverless.adoc#limitations[Serverless limits]

== Dedicated metrics

Pricing for Dedicated clusters depends on the time the instance in up, the data in, data out, and data stored.

|=== 
| Metric | Description 

| Instance | This tracks the number of hours the instance is running. 

The cost varies based on the region and tier you select for your cluster.   
| Ingress | This tracks the data written into Redpanda (in GB). 

The cost varies based on the region you select for your cluster. 

All Kafka protocol requests (_including_ message headers) are counted as ingress as soon as they are read by Redpanda's proxy process. 
| Egress | This tracks the data read out of Redpanda (in GB).

All Kafka protocol responses generated by the cluster (_including_ message headers) are counted as egress as soon as the cluster processes the request, even if the client drops the connection before they are delivered. 

The cost varies based on the number of availability zones (AZ) you select for your cluster. 
| Storage | This tracks the data (in GB) in object storage per hour. 

Replication to object storage is implemented with glossterm:Tiered Storage[]. All topics have a fixed replication factor of 3, but Redpanda counts each byte only once.

Redpanda measures the storage used by each topic every 10 minutes. Rapid changes in the allocated storage within 10 minutes may not be detected. Data is measured as bytes/hour used; that is, if a vcluster uses 600 MB storage for 1 hour, the metering collection records a total usage of 600000000 bytes/hour. Because the system updates every 10 minutes, it communicates 100000000 bytes/hour every 10 minutes (600000000 at the end of the hour). For billing, the data is converted to gigabytes/hour, by dividing the total consumption by 1000000000. For example, 1000000000 bytes/hour corresponds to 1 gigabyte/hour (which corresponds to a vcluster storing 1 GB for 1 hour, or a vcluster running with 100 MB for 10 hours, or any other combination of that). 

|=== 

See also: xref:deploy:deployment-option/cloud/cloud-overview.adoc#cluster-tiers[Cluster tiers]

== Next steps

* xref:./gcp-commit.adoc[]
* xref:./aws-commit.adoc[]