= Consumption Metrics
:description: Learn about the consumption units in Redpanda Cloud billing.

Redpanda Cloud billing is mapped to your consumption of resources. When you create a cluster, you select a xref:deploy:deployment-option/cloud/cloud-overview.adoc#cluster-tiers[throughput tier] for expected data ingress and egress, partitions, and connections. Billing is based on the number of units consumed is multiplied by the cost for that unit.

You can subscribe to Redpanda Cloud through Google Cloud Marketplace or AWS Marketplace and use your existing marketplace billing and credits to provision Redpanda Dedicated Cloud clusters. View your bills and manage your subscription directly in the marketplace.

* All pricing is set in US dollars (USD). The marketplace automatically converts the bill to the currency of the billing account. 
* All billing computations are conducted in Coordinated Universal Time (UTC). Billing accrues at hourly intervals. Any usage that is less than an hour is billed for the full hour. 

=== Instance meters

Each instance unit equals one hour the instance is up and running. The cost for an instance unit depends on the region and tier you selected for your cluster.  

=== Ingress and egress meters

Redpanda Cloud charges for all data transferred each hour, including each produce and consume request.

* Each ingress unit equals one GB/hour of data written. The cost for an ingress unit depends on the region you selected for your cluster. 
* Each egress unit equals one GB/hour of data read. The cost for an egress unit depends on the number of availability zones (AZ) you selected for your cluster. 

=== Storage meters

Each storage unit equals one GB of data in object storage. 

== Next steps

* xref:./gcp-commit.adoc[]
* xref:./aws-commit.adoc[]