= Use with GCP Commits
:description: Subscribe to Redpanda Cloud in Google Cloud Marketplace with discounted commitment billing.

With a usage-based billing commitment, you sign up for a minimum spend amount and get a discount on your committed usage. This allows you to subscribe to Redpanda Cloud through Google Cloud Marketplace to quickly provision Redpanda Dedicated clusters. 

Commitments are minimums. If you use more than your committed amount, you can continue using Redpanda Cloud without interruption. You will be charged at your discounted rate for usage beyond the committed amount until the end of your commitment term. 

[IMPORTANT]
====
When you sign up for Redpanda Cloud through Google Cloud Marketplace, you can only create clusters on GCP. 
====

== Sign up in Google Cloud Marketplace

. Contact https://redpanda.com/contact[Redpanda sales^] to request a quote for a GCP Redpanda Cloud commitment. You will receive a private quote.

. Click the private quote link to view the quote on the GCP Marketplace. Review the policy and required terms, and click *Accept*.
+
[NOTE]
====
If you don't have a billing account associated with your project, you're prompted to enable billing to link the subscription with a billing account.
====
+
You are taken to the Redpanda sign-up page.

. On the Redpanda sign-up page: 
* For **Email**, enter your email address to register with Redpanda.
* For **Organization name**, enter a name for your new organization connected through Google Cloud Marketplace. Redpanda organizations contain all resources, including clusters and networks. 
* Click **Sign up and create organization**.
+
You will receive an email sent to the address you entered.

. In the email, click **Verify email address**. 
+
This completes the registration and associates the email with a Redpanda account. 

. On the **Accept your invitation to sign up** page, click **Sign up** or **Log in**. 
+
You can now create namespaces and clusters in your organization.

== Next steps

* xref:deploy:deployment-option/cloud/create-dedicated-cloud-cluster-aws.adoc#create-a-dedicated-cluster[Create a Dedicated cluster]