= rpk redpanda mode
:description: rpk redpanda mode

Enable a default configuration mode

This command allows you to set one of the following modes: Development,
Production, or Recovery.

PRODUCTION

  - Enforces optimal runtime checks.
  - Enables all rpk tuners, for you to run 'rpk redpanda tune'.

DEVELOPMENT

  - Disables optimal checks and bypasses fsync, which results in unrealistically
    fast clusters and may result in data loss.
  - Disables all rpk tuners. The tuners are intended to run only for production 
    mode.

RECOVERY

Sets the broker configuration property 'redpanda.recovery_mode_enabled=true' in 
your `redpanda.yaml`. This provides a stable environment for troubleshooting and 
restoring a failed cluster. Restart required.

== Usage

[,bash]
----
rpk redpanda mode [MODE] [flags]
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-h, --help |- |Help for mode.

|--config |string |Redpanda or rpk config file; default search paths are `/var/lib/redpanda/.config/rpk/rpk.yaml`, `$PWD/redpanda.yaml`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override rpk configuration settings; '-X help' for detail or '-X list' for terser detail.

|--profile |string |rpk profile to use.

|-v, --verbose |- |Enable verbose logging.
|===