= rpk cluster maintenance status
:description: rpk cluster maintenance status

Report maintenance status.

This command reports maintenance status for each node in the cluster. The output
is presented as a table with each row representing a node in the cluster.  The
output can be used to monitor the progress of node draining.

   NODE-ID  ENABLED  FINISHED  ERRORS  PARTITIONS  ELIGIBLE  TRANSFERRING  FAILED
   1        false     false     false   0           0         0             0

Field descriptions:

        NODE-ID: the node ID
        ENABLED: true if the node is currently in maintenance mode
       FINISHED: leadership draining has completed
         ERRORS: errors have been encountered while draining
     PARTITIONS: number of partitions whose leadership has moved
       ELIGIBLE: number of partitions with leadership eligible to move
   TRANSFERRING: current active number of leadership transfers
         FAILED: number of failed leadership transfers

Notes:

   - When errors are present further information will be available in the logs
     for the corresponding node.

   - Only partitions with more than one replica are eligible for leadership
     transfer.

== Usage

[,bash]
----
rpk cluster maintenance status [flags]
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-h, --help |- |Help for status.

|--config |string |Redpanda or rpk config file; default search paths are `/var/lib/redpanda/.config/rpk/rpk.yaml`, `$PWD/redpanda.yaml`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override rpk configuration settings; '-X help' for detail or '-X list' for terser detail.

|--profile |string |rpk profile to use.

|-v, --verbose |- |Enable verbose logging.
|===