= rpk transform deploy
:description: rpk transform deploy

Deploy a data transform.

When run in the same directory as a `transform.yaml`, this reads the configuration file, then looks for a `.wasm` file with the same name as your project. If the input and output topics are specified in the configuration file, those are used. Otherwise, the topics can be specified on the command line using the `--input-topic` and `--output-topic` flags.


== Example

To deploy Wasm files directly without a `transform.yaml` file:

[,bash]
----
rpk transform deploy transform.wasm --name myTransform --input-topic my-topic-1 --output-topic my-topic-2
----

Specify environment variables for the transform with the `--env-var` flag, separated by an equals sign. For example: `--env-var=KEY=VALUE`

The `--env-var` can be repeated to specify multiple variables.

== Usage

[,bash]
----
rpk transform deploy [WASM] [flags]
----

== Flags

[cols="1m,1a,2a]
|===
|*Value* |*Type* |*Description*

|`--env-var` |- |Environment variable in the form of `KEY=VALUE``.

|`-h, --help` |- |Help for deploy.

|`-i, --input-topic` |string |The input topic to apply the transform to.

|`--name` |string |The name of the transform.

|`-o, --output-topic` |string |The output topic to write the transform results to.

|`--config` |string |Redpanda or rpk config file; default search paths are `~/.config/rpk/rpk.yaml`, `$PWD`, and `/etc/redpanda/redpanda.yaml`.

|`-X, --config-opt` |stringArray |Override rpk configuration settings; '-X help' for detail or '-X list' for terser detail.

|`--profile` |string |rpk profile to use.

|`-v, --verbose` |- |Enable verbose logging.
|===