= rpk transform deploy
:page-aliases: labs:data-transform/rpk-transform-deploy.adoc

Deploy a data transform.

When run in the same directory as a `transform.yaml`, this reads the configuration file, then looks for a `.wasm` file with the same name as your project. If the input and output topics are specified in the configuration file, those are used. Otherwise, the topics can be specified on the command line using the `--input-topic` and `--output-topic` flags.

== Example

To deploy Wasm files directly without a `transform.yaml` file:

[,bash]
----
rpk transform deploy transform.wasm --name myTransform \
--input-topic my-topic-1 \
--output-topic my-topic-2
----

Environment variables can be specified for the transform using the `--var` flag, these are separated by an equals for example: `--var=KEY=VALUE`. 

The --var flag can be repeated to specify multiple variables like so:

[,bash]
----
rpk transform deploy --var FOO=BAR --var FIZZ=BUZZ
----

== Usage

[,bash]
----
rpk transform deploy [WASM] [flags]
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-h, --help |- |Help for deploy.

|-i, --input-topic |string |The input topic to apply the transform to.

|--name |string |The name of the transform.

|-o, --output-topic |string |The output topic to write the transform results to.

|--var |- |environmentVariable   Specify an environment variable in the form of KEY=VALUE.

|--config |string |Redpanda or `rpk` config file. Default search paths are: 
`~/.config/rpk/rpk.yaml`, `$PWD`, and `/etc/redpanda/redpanda.yaml`.


|-X, --config-opt |stringArray |Override `rpk` configuration settings. See xref:reference:rpk/rpk-x-options.adoc[`rpk -X`] or execute `rpk -X help` for inline detail or `rpk -X list` for terser detail.

|--profile |string |Profile to use. See xref:reference:rpk/rpk-profile.adoc[`rpk profile`] for more details.

|-v, --verbose |- |Enable verbose logging.
|===