= rpk transform pause
:description: rpk transform pause

Pause a data transform.

This command suspends execution of the specified transform without removing it from the system. In this way, a transform may resume at a later time, with each new processor picking up processing from the last committed offset on the corresponding input partition.

Subsequent `rpk transform list` operations will show transform processors as `inactive`.

To resume a paused transform, use `rpk transform resume`.

== Usage

[,bash]
----
rpk transform pause [NAME] [flags]
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-h, --help |- |Help for pause.

|--config |string |Redpanda or `rpk` config file; default search paths are `~/.config/rpk/rpk.yaml`, `$PWD`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override `rpk` configuration settings. See xref:reference:rpk/rpk-x-options.adoc[`rpk -X`] or execute `rpk -X help` for inline detail or `rpk -X list` for terser detail.

|--profile |string |Profile to use. See xref:reference:rpk/rpk-profile.adoc[`rpk profile`] for more details.

|-v, --verbose |- |Enable verbose logging.
|===