= rpk transform build
:page-aliases: labs:data-transform/rpk-transform-build.adoc

Build a data transform.

This command looks in the current working directory for a `transform.yaml` file. It installs the appropriate build plugin, then builds a `.wasm` file.

When invoked, it passes extra arguments directly to the underlying toolchain.

For example, to add debug symbols and use the `asyncify` scheduler for `tinygo`:

[,bash]
----
rpk transform build -- -scheduler=asyncify -no-debug=false
----

Language-specific details:

TinyGo - By default, TinyGo are release builds (-opt=2) and goroutines are disabled, for maximum performance.

== Usage

[,bash]
----
rpk transform build [flags]
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-h, --help |- |Help for build.

|--config |string |Redpanda or rpk config file; default search paths are `~/.config/rpk/rpk.yaml`, `$PWD`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override `rpk` configuration settings. See xref:reference:rpk/rpk-x-options.adoc[`rpk -X`] or execute `rpk -X help` for inline detail or `rpk -X list` for terser detail.

|--profile |string |Profile to use. See xref:reference:rpk/rpk-profile.adoc[`rpk profile`] for more details.

|-v, --verbose |- |Enable verbose logging.
|===