= rpk generate app
:description: rpk generate app

Generate a sample application to connect with Redpanda.

This command generates a starter application to produce and consume from the
settings defined in the rpk profile. Its goal is to get you producing and
consuming quickly with Redpanda in a language that is familiar to you.

By default, this will run interactively, prompting you to select a language and
a user with which to create your application. To use this without interactivity,
specify how you would like your application to be created using flags.

The --language option allows you to specify the language. There is no default.

The --new-sasl-credentials <user>:<password> allows you to generate a new SASL
user with admin ACLs. If you don't want to use your current profile user nor
create a new one, you may use --no-user flag to generate the starter app without
the user.

If you are having trouble connecting to your cluster, you can use -X
admin.hosts=comma,delimited,host:ports to pass a specific admin api address.

EXAMPLES

Generate an app with interactive prompts:
  rpk generate app

Generate an app in a specified language with the existing SASL user:
  rpk generate app --language <lang>

Generate an app in the specified language with a new SASL user:
  rpk generate app -l <lang> --new-sasl-credentials <user>:<password>

Generate an app in the 'tmp' dir, but take no action on the user:
  rpk generate app -l <lang> --no-user --output /tmp

== Usage

[,bash]
----
rpk generate app [flags]
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-h, --help |- |Help for app.

|-l, --language |string |The language you want the code sample to be generated with.

|--new-sasl-credentials |string |If provided, rpk will generate and use these credentials (<user>:<password>).

|--no-user |- |Generates the sample app without SASL user.

|-o, --output |string |The path where the app will be written.

|--config |string |Redpanda or rpk config file; default search paths are `/var/lib/redpanda/.config/rpk/rpk.yaml`, `$PWD/redpanda.yaml`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override rpk configuration settings; '-X help' for detail or '-X list' for terser detail.

|--profile |string |rpk profile to use.

|-v, --verbose |- |Enable verbose logging.
|===