= rpk profile set-globals
:description: rpk profile set-globals

Set rpk globals fields.

This command takes a list of key=value pairs to write to the global config 
section of rpk.yaml. The globals section contains a set of settings that apply
to all profiles and changes the way that rpk acts. For a list of global flags
and what they mean, check 'rpk -X help' and look for any key that begins with
"globals".

This command supports autocompletion of valid keys. You can also use the
format 'set key value' if you intend to only set one key.

== Usage

[,bash]
----
rpk profile set-globals [KEY=VALUE]+ [flags]
----

== Flags

[cols="1m,1a,2a"]
|===
|*Value* |*Type* |*Description*

|-h, --help |- |Help for set-globals.

|--config |string |Redpanda or rpk config file; default search paths are `/var/lib/redpanda/.config/rpk/rpk.yaml`, `$PWD/redpanda.yaml`, and `/etc/redpanda/redpanda.yaml`.

|-X, --config-opt |stringArray |Override rpk configuration settings; '-X help' for detail or '-X list' for terser detail.

|--profile |string |rpk profile to use.

|-v, --verbose |- |Enable verbose logging.
|===