=== rebalancing
:term-name: rebalancing
:hover-text: Process of moving partition replicas and transferring partition leadership for improved performance. 
:category: Redpanda features

Redpanda provides various topic-aware tools to balance clusters for best performance.

- Leadership balancing changes where data is written to first, but it does not involve any data transfer. The partition leader regularly sends heartbeats to its followers. If a follower does not receive a heartbeat within a timeout, it triggers a new leader election. Redpanda also provides leadership balancing when brokers are added or decommissioned.
- Partition replica balancing moves partition replicas to alleviate disk pressure and to honor the configured replication factor across brokers and the additional redundancy across failure domains (such as racks). Redpanda provides partition replica rebalancing when brokers are added or decommissioned. 
- With an Enterprise license, you can additionally enable Continuous Data Balancing to continuously monitor broker and rack availability and disk usage.

For more information, see xref:manage:cluster-maintenance/cluster-balancing.adoc[].